### ISSUE TITLE
Rule for BindToStream

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1001]
Create a binding factory rule for BindToStream. This enables [Blob] and [File] to share the same code. 
This is the last remaining major rule that we need. 
There is a prototype of this in ApiHub's file binding.

**Comment by tohling** [comment]
Can't wait to have this support!

**Comment by MikeStall** [comment]
This requires https://github.com/Azure/azure-webjobs-sdk/issues/1406

**Comment by daulet** [comment]
This issue is mentioned in [Creating custom input and output bindings](https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings). Update the wiki with details how to use BindToStream.

**Comment by AymanGaafar** [comment]
Is there another updated version of [Creating custom input and output bindings](https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings) wiki page or is it not updated yet?
