### ISSUE TITLE
EventHubTrigger not reading from EventHub

### ISSUE THREAD

**Issue by alexandruc16** [Azure/azure-webjobs-sdk#1003]
Using the Azure WebJobs SDK with the latest prerelease version of Microsoft.Azure.WebJobs.Extensions v2.0.0-beta2-10392 to read events from an EventHub will not work. The function is never called.

Known workaround: downgrade Microsoft.Azure.WebJobs.Extensions to v2.0.0-beta2.

**Comment by fabiocav** [comment]
@mamaso  can you check if there was a breaking change?

**Comment by mamaso** [comment]
Ran with the latest pre-release nugets as well as 10392 without issue.

Looked at the relevant commits and didn't see anything likely to have been a breaking change.

**Comment by mathewc** [comment]
@alexandruc16 We can't repro - if this is still a problem for you, can you please provide us a complete repro with code + configuration?
