### ISSUE TITLE
Default WebJob template in Visual Studio instatiates JobHost without providing the config

### ISSUE THREAD

**Issue by MickVermeer1991** [Azure/azure-webjobs-sdk#1015]
When a new WebJob project is created, the JobHost is instantiated as follows:
`var host = new JobHost();`

It is not using the configuration that is created right above that line:
```
var config = new JobHostConfiguration();
if (config.IsDevelopment)
{
     config.UseDevelopmentSettings();
}
```

Please update the template to do: 
`var host = new JobHost(config);`

**Comment by mathewc** [comment]
I'm not seeing this. What version of VS are you using? I'm using Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3

**Comment by MelvinVermeer** [comment]
I'm seeing the same thing using Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3. 

I am running Azure SDK 2.9 (v2.9.41104.6)

**Comment by MickVermeer1991** [comment]
I am currently using Visual Studio Enterprise 2015, Version 14.0.25431.01, Update 3.

**Comment by mathewc** [comment]
Thanks guys. @davidebbo is going to investigate this

**Comment by davidebbo** [comment]
I just created a new project, and I indeed see the behavior. @mlorbetske, could this be a recent regression in the WebJob template?

**Comment by davidebbo** [comment]
@mlorbetske I also tried with VS 2017 and it has the same issue.

**Comment by mlorbetske** [comment]
This shouldn't be a recent regression, we've not changed that template in quite some time nor have we released an SDK update recently that could have regressed this. I'll get a fix prepped but it's probably too late to take it for RTW/the next SDK.

**Comment by paulbatum** [comment]
@mlorbetske Were you able to confirm the regression and implement a fix? If so whats the likely ship vehicle?

**Comment by mlorbetske** [comment]
This will go in the VS platform update & the accompanying Azure SDK

**Comment by paulbatum** [comment]
@mlorbetske For both VS 2015 and VS 2017?

**Comment by mlorbetske** [comment]
Yep

**Comment by paulbatum** [comment]
Closing this as fixed: external. Details of when the fix will ship are above.
