### ISSUE TITLE
Binding to Instance of Generic Class

### ISSUE THREAD

**Issue by markolbert** [Azure/azure-webjobs-sdk#1017]
I posted a question about this over on SO (http://stackoverflow.com/questions/42195319/webjob-dependency-injection-binding-to-generic-class). But I've done some more work on it, and wanted to run a theory by folks here.

It looks like whatever standard scan is being done to find Types that respond to QueueTriggers doesn't pick up on generic Types. In other words, this Type will be found:

```
    public class ConnellFilteredVoterFileJob : FilteredVoterFileJob<ConnellJobContext, ConnellUser>
    {
        public ConnellFilteredVoterFileJob( StringWriter swLogger )
            : base( swLogger )
        {
        }

        [Singleton()]
        public new async Task ProcessMessage(
            [ QueueTrigger( "%" + nameof( ContainerQueueConstants.FilteredVoterFiles ) + "%" ) ] AgencyOutreachMessage
                msg,
            TextWriter azureLogWriter
        )
        {
            PhaseNames.SetNames( "Exporting Data", "Job Completed" );

            await ExecuteFromMessage( msg, azureLogWriter, Launch );
        }
    }

```

But this won't be found:

```
    public class FilteredVoterFileJob<TContext, TUser> : FileOutputJob<TContext, TUser>
        where TContext : IdentityDbContext<TUser>, ICampaignContext, new()
        where TUser : IdentityUser, INamedUser
    {
        public FilteredVoterFileJob( StringWriter swLogger )
            : base( swLogger, "Generate Filtered Voters File Job", "Filtered Voters" )
        {
        }

        [Singleton()]
        public async Task ProcessMessage(
            [ QueueTrigger( "%" + nameof( ContainerQueueConstants.FilteredVoterFiles ) + "%" ) ] AgencyOutreachMessage
                msg,
            TextWriter azureLogWriter
        )
        {
            PhaseNames.SetNames( "Exporting Data", "Job Completed" );

            await ExecuteFromMessage( msg, azureLogWriter, Launch );
        }
    }

```

At least, when I only have that second class definition, the WebJobs app starts up, but complains it can't find any message processing functions :)

If there's a way to make the "pure" generic approach -- the second example -- work, I'd love to know about it.

This is using WebJobs 1.1.2

**Comment by MikeStall** [comment]
WebJobs doesn't instantiate generic classes.  
In the generic case, `FilteredVoterFileJob<TContext, TUser>`, it doesn't know what TContext and TUser are.  In the first case, it knows they are `FilteredVoterFileJob<ConnellJobContext, ConnellUser>`. 

That said, in the latest bits (not 1.1.2) you could use binding extensions to create a _parameter_ binding to an arbitrary type.   https://github.com/Azure/azure-webjobs-sdk/wiki/Extensibility has some details here.  IE, like
```
  [QueueTrigger]  AgencyOutreachMessage<ConnellJobContext, ConnellUser> msg. 
````

Can you elaborate a bit on your scenario and we can get a sample for to show how.  For example, are you expecting multiple instantiations of your generic with different type args?

**Comment by MikeStall** [comment]
@markolbert  - can you elaborate on your scenario?

**Comment by markolbert** [comment]
Apologies, but I ended up revising my code so I'm no longer trying to instantiate generics. I'll close the item.
