### ISSUE TITLE
Webjobs BatchSize does not work

### ISSUE THREAD

**Issue by isaackhazi** [Azure/azure-webjobs-sdk#1018]
I am using the Webjobs SDK v 1.1.2
I am trying to get the web job to process queue messages one by one. In order to do that I have researched online and found that you could set the BatchSize as below: 

`Sub Main()
Dim config As New JobHostConfiguration()
config.Queues.BatchSize = 1
config.Queues.MaxDequeueCount = 1
config.Queues.MaxPollingInterval = TimeSpan.FromSeconds(10)
If (config.IsDevelopment) Then
config.UseDevelopmentSettings()
End If
Dim host As New JobHost(config)
host.RunAndBlock()
End Sub`

In spite of explicitly setting the number of BatchSize to 1, when I deploy the WebJob app, it seems to accept all the messages at the same time and process in parallel. My Function that processes queue messages looks something like this:

`
Public Sub ProcessQueueMessage(<QueueTrigger("parserqueue")> message As String, log As TextWriter)
        Dim ClientId = "RC_" + message
        log.WriteLine(ClientId)

        If CheckActiveClient(ClientId, log) = True Then
            Dim ParseCVs As New Parse(message, log)
            LockClientId(ClientId, log)
            While ParseCVs.Connect(ClientId) <> 0
                log.Write(ParseCVs.Connect(ClientId).ToString() + " CVs in queue")
                ParseCVs.ParseResumes.Wait()
            End While
        End If
        UnlockClientId(ClientId, log)
    End Sub
` 

#### Repro steps

Details in "Known Workarounds"

#### Expected behavior

The web job should process one message at at time.

#### Actual behavior

The webjob is processing all messages in parallel when deployed.

#### Known workarounds

When I run the webjob in debug mode on my local machine, the job seems to accept only one message at a time and works as expected. Rather than publishing the webjob using VS 2015, I zipped the release folder and create d webjob using the zip. However, this does not seem to fix the issue. 

Here you can see that the web job is running while 2 messages are still in queue. This is while debuggin locally.

https://www.screencast.com/t/wfliQxqkDkYj

As you can see below, when the webjob is deployed the behavior changes and the job starts processing all messages at once.

https://www.screencast.com/t/Fbewc31NpU7F

#### Related information 

Provide any related information 

* Package version: 1.1.2
* Links to source

**Comment by mathewc** [comment]
How many instances do you have your host WebApp scaled out to? Note that the batch size knob only applies to each instance, not globally across scaled out instances.

**Comment by isaackhazi** [comment]
Hi Mathew, I have my webjob set to 3 instance count for scaling out. However, whenever I have tried, the web job does not seem to scale. I see only one job running at all times. From what I have read, the web job must scale out if the first job is in progress and a new queue message appears in the queue.

**Comment by isaackhazi** [comment]
I changed the scale out instance count to 1 and it works as expected. What am I doing wrong here? Isn't the scale out meant to process multiple messages in parallel on different instances if I set the "BatchSize" to 1?

**Comment by mathewc** [comment]
When you scale out to 3 instances (assuming you also have AlwaysOn enabled), there will always be 3 instances of your host running, once per instance. They will all be processing the queue in parallel. The WebJobs UI will only show a single WebJob, to provide a single unit of management for stop/restart/etc. operations. However log files will show that there are 3 different instances active (logs include an instance ID).
