### ISSUE TITLE
Webjobs Dashboard warning.

### ISSUE THREAD

**Issue by isaackhazi** [Azure/azure-webjobs-sdk#1019]
In the dashboard of any of my web jobs, there is a warning message about setting the connections strings for the storage account. I have already set them. However they still appear. Is this by default? 

**Warning message**

https://www.screencast.com/t/wgpzPvK9K4

**Connections in app.config**

https://www.screencast.com/t/TCwvZZI7CBd

Provide any related information 

* Package version
* Links to source

**Comment by christopheranderson** [comment]
Dashboard settings have to be set as App Settings on the Web App (in the portal). It runs as a separate app so cannot read from that app.config.
