### ISSUE TITLE
The service provider should be replaced by something else

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#102]
What we do today with the service provider looks like a service locator. Instead of that we should maybe use something like a factory with a default implementation - similar to the controller factory in MVC. That way, one could do nice DI on it. 

 I think this should be addressed soon-ish because otherwise we might have to rewrite more code.

**Comment by mathewc** [comment]
The path we're taking with the new extensibility model is to retain the IServiceProvider approach because it is simple and serves our extensibility needs. Rather than using a full blown DI solution, which doesn't seem needed. We don't want to be choosy about one (e.g. choosing AutoFac).
