### ISSUE TITLE
Queue MaxPollingInterval doesn't seem to be honored

### ISSUE THREAD

**Issue by davidlfox** [Azure/azure-webjobs-sdk#1026]
Working with beta-2.0.0beta1, local storage, local dashboard. 

I'm reviewing `RandomizedExponentialBackoffStrategy` and it _appears_ that the interval should always stay at or below the MaxPollingInterval I set in my WebJobs initialization:

```
var config = new JobHostConfiguration();
if (config.IsDevelopment)
{
    config.UseDevelopmentSettings();
}
config.Queues.MaxPollingInterval = TimeSpan.FromSeconds(1);
var host = new JobHost();
// The following code ensures that the WebJob will be running continuously
host.RunAndBlock();
```
#### Repro steps

1. Run web app locally

2. Debug local instance of web job

3. Queue a message from local web app

```var storageAccount = CloudStorageAccount.Parse(ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ToString());
CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
CloudQueue addResourceRequestQueue = queueClient.GetQueueReference("addresources");
addResourceRequestQueue.CreateIfNotExists();

// queue message with delay
var queueMessage = new CloudQueueMessage(JsonConvert.SerializeObject(new MyThing
{
    Prop1 = "prop1",
    Prop2 = "prop2",
}));
await addResourceRequestQueue.AddMessageAsync(queueMessage, null, TimeSpan.FromSeconds(5), null, null);
```

4. Open storage explorer, observe message is not immediately available (due to visibility delay.) Refresh until it appears. It does appear.

5. Eventually, the message is dequeued--as long as 30 seconds at times

#### Expected behavior

Messages should wait in queue no longer than 1 second once they're visible in the queue.

#### Actual behavior

Eventually, the message is dequeued--as long as 30 seconds at times

#### Known workarounds

No known workarounds. I'd either like to 1) resolve this by configuration, or 2) be able to specify an `IDelayStrategy`, but previous issues suggest that's too far internal to be an option. My long term goal is queue a delayed (invisible) message for an exact amount of time and have it dequeued immediately when it becomes visible.

#### Related information 

* Package version: 2.0.0beta1
* Links to source: https://github.com/davidlfox/pixelpbbg/tree/delayed-resource-collection/ResourceCollector

**Comment by mathewc** [comment]
In your code above, you're not passing the config object into your JobHost :) I.e. you need:

```chsarp
var host = new JobHost(config);
```
