### ISSUE TITLE
Make MaxPollingInterval configurable for each queue processor

### ISSUE THREAD

**Issue by Dia6lo** [Azure/azure-webjobs-sdk#1030]
In some cases there is a need to poll queues with different latencies (e.g. chat queue with low latency or image processing queue with moderate latency). In such cases one global MaxPollingInterval makes it impossible to maintain only the needed amount of polling, i.e. it leads to increased storage costs.

**Comment by mathewc** [comment]
Agreed. Here is the [line of code](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListenerFactory.cs#L86) where we create the delay strategy using MaxPollingInterval.

We could move the creation of this strategy into QueueListener, where we could then pull the override value off of the custom QueueProcessor you implemented. Note that we already employ that override capability for other settings like BatchSize, MaxDequeueCount, NewBatchThreshold, etc. So this totally makes sense.
