### ISSUE TITLE
Option to create service bus topic or queue when using attributes

### ISSUE THREAD

**Issue by JamesCrann** [Azure/azure-webjobs-sdk#1052]
When the output of a webjob function is a service bus, and a queue/topic does not already exists, there appears to be no way to specify whether a Queue or a Topic should be created.

In a environment where the sender and consumer are running in different webjobs, the startup sequence determines whether a queue of a topic is created.

#### Repro steps
Given the following sender and receiver :

**Sender**

`public async Task ProcessQueueMessage([ServiceBusTrigger("Queue1")] string message,
             [ServiceBus("Topic1")] IAsyncCollector<SomethingMessage> outputMessages)`

**Receiver**

`public async Task ProcessTopicMessage([ServiceBusTrigger("Topic1", "Subscription1")] SomethingMessage message)`

If the sender starts up first, "Topic1" is created as a queue.
but if the Receiver starts up first "Topic1" is created as a topic.

It is also worth noting that once the sender creates the queue, no topic subscribers are able to function.

#### Expected behavior

Having the ability to specify whether the output is a queue or a topic via an attribute property
```
 public async Task ProcessQueueMessage([ServiceBusTrigger("Queue1")] string message,
             [ServiceBus("Topic1", IsTopic : true)] IAsyncCollector<SomethingMessage> outputMessages)
```

or perhaps via a different attribute

```
 public async Task ProcessQueueMessage([ServiceBusTrigger("Queue1")] string message,
             [ServiceBusTopic("Topic1")] IAsyncCollector<SomethingMessage> outputMessages)
```

#### Known workarounds

On startup of the sending webjob worker, manually create topics if they dont exist

**Comment by christopheranderson** [comment]
This creates a bug for Functions for the Service Bus Topic output where we'd always create a Queue.
