### ISSUE TITLE
Azure function app in dedicated App Service.

### ISSUE THREAD

**Issue by RamsankarRajendran** [Azure/azure-webjobs-sdk#1063]
I have a topic in service bus and its having some number of subscription (nearly 1000) with different filters. Each subscription have ServiceBusTopicTrigger-JS listener in Azure function. When ever the topic get huge messages, unable to consume the messages from the ServiceBusTopicTrigger-JS azure function app. After that my messages are get accumulate in subscription and unable to get the messages in function app log(for all subscription).

I've raised ticket with Microsoft support regarding the issue. They suggest to migrate my Function App from a dynamic sku to a dedicated to have a better performance.

Then, I have moved my Function App to the dedicated App Service Plan. But Still I am facing same issue.

**Comment by christopheranderson** [comment]
Please provide a proper repro for this:
1. Code examples
2. Log messages errors
3. Timestamp
4. Function App name
5. Example Topic Message (what does "huge" mean?)
