### ISSUE TITLE
Improve Test Reliability on CI

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk#1077]
in particular: BlobGetsProcessedOnlyOnce_MultipleHosts

https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-rqm4t/build/10589/tests

**Comment by mathewc** [comment]
Yeah, there are quite a few flaky tests. Some of these tests might need an overhaul.

**Comment by mamaso** [comment]
Yep. Improved things a bit by ditching the .yml and doing some manual test ordering (ensuring E2E tests run after all others), but there's still plenty of room for improvement
