### ISSUE TITLE
Expand BlobTrigger/QueueTrigger binding metadata

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1083]
Recently I expanded the set of built in binding metadata for ServiceBusTrigger and EventHubTrigger (PRs https://github.com/Azure/azure-webjobs-sdk/pull/1071 and https://github.com/Azure/azure-webjobs-sdk/pull/1069). It would be good to do the same for BlobTrigger - e.g. add Uri, Metadata (custom properties), etc.

Our binding data for queues is already pretty good, I don't think there are any more properties that we need.

**Comment by mathewc** [comment]
@davidebbo FYI - this would address the blob URI scenario you had recently

**Comment by davidebbo** [comment]
Relates to http://stackoverflow.com/questions/42981770/azure-functions-c-sharp-get-blob-uri/42982455#42982455
