### ISSUE TITLE
Issue with two event hubs with the same name in different namespaces

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#1086]
The EventHubs binding does not correctly handle the case where a function app has two different event hub triggered functions, when the event hubs are in different namespaces but have the same name.

#### Repro steps

1. Create two event hub namespaces ns1 and ns2. 
2. Create an eventhub called 'test' in each namespace. 
3. Create a function app with two event hub triggered functions, func1 and func2. Configure func1 to point to ns1/test and configure func2 to point to ns2/test.
4.  Write data onto each event hub

#### Expected behavior

Each function triggers for the events on the appropriate hub

#### Actual behavior

func1 triggers for messages to ns2. func2 does not trigger

#### Known workarounds

Either rename one of the eventhubs or split the two functions into different function apps.

#### Related information 

Problem seems to be related to the code here:
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubConfiguration.cs

The dictionaries are keyed off of the event hub name, but this is not a unique identifier.

**Comment by myob-tristanlawrence** [comment]
Hello Fellow Microsoft peeps, just wondering when we are going to have this issue resolved? When you get the chance. Many thanks, from your fellow Microsoft patrons down under!

**Comment by paulbatum** [comment]
@myob-tristanlawrence the fix is in and will go live with the next release of functions v1 (should be complete globally by end of November).

I've filed https://github.com/Azure/azure-webjobs-sdk/issues/1432 to track porting the fix to functions v2.
