### ISSUE TITLE
Would like to access TimerInfo.ScheduleStatus

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/azure-webjobs-sdk#1103]
When running a timed web job, it would be nice to be able to access `ScheduleStatus` on `TimerInfo`. Rather than trying to find the current time. flooring it to find the exact time the job started etc., it should be possible to access `TimerInfo.ScheduleStatus.Next` which contains the exact time that the timed job started.

**Comment by ThomasArdal** [comment]
Workaround right now is this:

```csharp
dynamic dynamicTimer = myTimer;
var jobExecutionTime = dynamicTimer.ScheduleStatus.Next;
```

**Comment by mathewc** [comment]
I don't understand the ask. You provided workaround code that shows you can access TimerInfo.ScheduleStatus. What are you asking for specifically?

**Comment by ThomasArdal** [comment]
@mathewc What I'm asking for, is a strongly typed property for getting the "started time" of a scheduled job. Using a dynamic to access the `Next` property is a hack to access `ScheduleStatus`, which isn't public accessible on `TimerInfo`.

**Comment by christopheranderson** [comment]
Sounds reasonable.

**Comment by SimonLuckenuik** [comment]
FYI @christopheranderson this seems to be fixed.

**Comment by brandonh-msft** [comment]
@brettsam @fabiocav close as fixed?

**Comment by fabiocav** [comment]
Indeed. Thanks!
