### ISSUE TITLE
Return value support for BYOB

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1104]
BYOB is all about Script consuming SDK extensions directly - with no additional Script-specific glue code. 
Script has some support for return values (IResultProcessingBinding), but SDK does not support return value binding. 

There are 2 ways we use return value:
1. an implicit 'out' parameter.  This is just binding sugar and can work with existing IAsyncCollector patterns where:
```
T Foo()  { 
return T;
}
```
becomes
```
void Foo2(ICollector<T> temp)
{
  T x = Foo();
  temp.Add(x);
}
```

2. applying something to the trigger (ie, HttpResponseMessage)

This is primarily for case #2.  Need some means for SDK extensions to signal about return value binding.

**Comment by MikeStall** [comment]
FYI, existing bug for case 1: https://github.com/Azure/azure-webjobs-sdk/issues/656

**Comment by cgillum** [comment]
FYI we need this for Durable Functions: https://github.com/Azure/azure-functions-durable-extension/issues/4

This is required both for handling return values and for binding to input parameters - thus is really important for our experience.

**Comment by lindydonna** [comment]
Visual Studio tooling depends on this, see https://github.com/Azure/azure-webjobs-sdk-script/issues/1508

**Comment by MikeStall** [comment]
As a design point, An explicit binding on the return attribute should take place over an implicit trigger binding. 

Case | Example |  What does return value do?
--- | --- | ---
1 | void Foo()   | none 
2 | [Q] string Foo()   |  [Q] 
3 | string Foo(Request)  | error, no bindings at all 
4 | string Foo([Http] Request)  |  [Http], return is implicit given the trigger binding 
5 |  [Q] string Foo([Http] Request)  |  [Q], takes precedence.
