### ISSUE TITLE
Poison messages stay undeleted-but-invisible with  the latest WindowsAzure.Storage 8.1.1  

### ISSUE THREAD

**Issue by AliMoeen** [Azure/azure-webjobs-sdk#1107]
Hi Folks, 

I think this is  a quite high impact bug because of the following reasons:

- The impact could be grave. Imagine mass amount Poison messages pile up in a job queue in a production system. Inspecting and cleaning queue messages are not as easy as some other data structures like Tables.
- This issue is quite easy to miss in typical development tests.  I could find any test case in the sdk repository to check for left-undeleted-invisible poison messages.
- Developers tend to use the latest version of WindowsAzure.Storage to the latest version 8.1.1 which is not compatible with WebJob SDK 2.0 and cause this issue
- Spotting the issue and finding the workaround was not so quick for me.

**The Issue**

The issue is that Microsoft.Azure.WebJobs Nuget package has a dependency to on an older version of WindowsAzure.Storage V 7.2.1 package. If someone upgrades the WindowsAzure.Storage to the latest version 8.1.1  (like another class library has a reference to the latest version), the following subtle, confusing and potentially dangerous defect arises:

**Symptoms**

When a Queue message reaches config.Queues.MaxDequeueCount, the SDK adds the poison message to “*-poison” queue; however, it fails to delete the message from the main queue, and the message stays invisible until it reaches its visibilitytimeout.

The matter becomes confusing since the poison message stays invisible, so you might think it is has been deleted. But the message will eventually become visible again. This is how all of the poison messages will come back to the job queue indefinitely. 

I think this is due to a bug in the method DeleteMessageAsync called here:
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs#L119 
the method DeleteMessageAsync swallows a few StorageException here:
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs#L198 

Thank you,
Ali Moeen

**Comment by mamaso** [comment]
related to #1091

**Comment by christopheranderson** [comment]
We will tackle this issue when we upgrade to the latest storage SDK in the next major release. Unfortunately, for now, you cannot use Storage SDK 8.x with WebJobs SDK.

**Comment by brettsam** [comment]
It's been resolved (#985) and available in our nightly drops: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds
