### ISSUE TITLE
On deployment from KUDU you receive listener error but Functions still appear to work OK.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-webjobs-sdk#1108]
Would suggest this is a low priority issue.

I have a Function App containing a series of Functions that is deployed from a Git repository in VSTS using Kudu. On deployment every one of the Apps shows the following in their Log window after successfully compiling:

`The listener for function 'Functions.' was unable to start. mscorlib: The operation was canceled.`

However, it appears the Functions all still work as expected, so it appears this error is spurious / transient and a retry occurs silently.

The same error experience occurred for the 7 Functions in the App instance.

App host in Azure is running v1.0.10841of the runtime.

#### Repro steps

Provide the steps required to reproduce the problem

1. Setup Function App project (VS2015) and add to VSTS Git Repository.
2. Configure continuous deployment from VSTS to the target Function App in Azure.
3. Trigger deployment and oberve the Log Window on the Function App in Azure. After deployment and compilation the error is displayed.

#### Expected behavior

Functions are compiled and work as expected with no errors being displayed.

#### Actual behavior

Functions are compiled, the error is displayed but the Functions work as expected.

#### Known workarounds

It appears there is no need for additional steps to resolve, however it is disconcerting to the user to see this message, particularly in trigger-driven environments.

#### Related information 

None.

**Comment by christopheranderson** [comment]
You don't see this on host start up, just on the deployment?

Could you provide info like what triggers you're using?

**Comment by sjwaight** [comment]
Given age of this issue, and as nobody else has reported (and I've not had it repeat) I am going to close. Happy 2018!
