### ISSUE TITLE
Add a "connection" property to EventHubTriggerAttribute

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk#1114]
For the Visual Studio tooling to produce function.json, we need a "connection" property in [EventHubTriggerAttribute](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubTriggerAttribute.cs). For SDK customers, we need to wire up the connection string.

It should be called `Connection` to make serialization easy.

**Comment by MikeStall** [comment]
This is also needed to support https://github.com/Azure/azure-webjobs-sdk-script/issues/1409
