### ISSUE TITLE
Extensions shouldn't need to depend on all the AppInsights dependencies

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1129]
With AppInsights, the SDK needs the ILogger interface, but that shouldn't pull in the rest of the AppInsights dependencies:
The problem is that these new dependencies get pushed to every single extension. 

We should minimize SDK dependencies. In this case, the AI dependencies could be in the existing WebJobs.Logging  package or in Script. 

  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.7" targetFramework="net46" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.3.0" targetFramework="net46" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.3.0" targetFramework="net46" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.3.0" targetFramework="net46" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.3.0" targetFramework="net46" />

**Comment by brettsam** [comment]
I'm working on this now -- I'm pulling it into it's own new package `WebJobs.Logging.ApplicationInsights`. I first attempted to do this with the existing Logging package, but since it requires ILogger, all of those dependencies flowed to the Dashboard as well.
