### ISSUE TITLE
Move projects and nuget packages to modern csproj format

### ISSUE THREAD

**Issue by damienpontifex** [Azure/azure-webjobs-sdk#1130]
It'd be great to move all packages to the new csproj format (and subsequently pull together nuget definitions into the csproj also). This would also enable a first step towards #541 without changing functionality.

What I propose is adopting the new format while still targeting net46. 
Once the migration to this format and dependencies are brought into the csproj, the next step towards providing a netstandard library would be adding extra TFM definitions to the `<TargetFrameworks>` property in the project.

This would provide a good first step to enabling .net core compilation in the future with continuing work.

I would be happy to post a PR, but wanted to open an issue on the topic first as suggested in the contributing guidelines.

**Comment by mathewc** [comment]
@fabiocav would you like a PR for this? I'm curious whether you have a copy of a similar change with your .net core work

**Comment by fabiocav** [comment]
This will be part of the migration work.

@damienpontifex, I should have this up on a branch and a PR either this coming week or next.

**Comment by paulbatum** [comment]
Please track the .NET core migration work. This is going to be landing in the main repo very soon.
