### ISSUE TITLE
Would like to set queue name for the QueueTriggerAttribute at runtime

### ISSUE THREAD

**Issue by will-beta** [Azure/azure-webjobs-sdk#1139]
It would be much convenient to be able to allowed generating the queue name from the name of the class like this:

``` c#
        private class MyCustomNameResolver : INameResolver
        {
            public string Resolve(ParameterInfo parameterInfo)
            {
                return $"{parameterInfo.Member.DeclaringType.Name}-{parameterInfo.Member.Name}".ToLower();
            }
        }
```

Thanks!

**Comment by mathewc** [comment]
I don't understand the ask - can you please clarify? For example, what QueueAttribute declaration would you like to see? What are you trying to do?

**Comment by will-beta** [comment]
@mathewc  hi! What I am trying to do is eliminate the hardcode queue name.

``` c#
public class Job1
{
    public static void ProcessQueueMessage([QueueTrigger] string message)
    {
        //todo...
    }
}

public class Job2
{
    public static void ProcessQueueMessage([QueueTrigger] string message)
    {
        //todo...
    }
}
```

**Comment by will-beta** [comment]
@mathewc hi! Actually, in our projects, we wrote dozens of webjobs.
we would like to generate the queue names for them by a regular rule, to save time and to avoid careless mistakes.

**Comment by xt0rted** [comment]
Depending on the version of .net you're using you could do `[QueueTrigger(nameof(Job1))]` which is similar to how I call a couple of mine so I don't have to worry about magic strings.

```c#
var uploadNotifications = host.CallAsync(typeof(Functions).GetMethod(nameof(Functions.SendUploadNotifications)));
```

**Comment by will-beta** [comment]
@xt0rted Thanks for advice! It works this way, though not the most convenient.
Besides the CustomNameResolver would be called only when the queue name is surrounded with '%'.

**Comment by will-beta** [comment]
@xt0rted We seperate webjobs into several kinds by namespaces.
The 'nameof' cannot help me with that.

**Comment by MikeStall** [comment]
I'd recommend using C# constants.  These can also include %% and even a custom INameResolver .   
We'd discourage people from relying on class name or anything that makes queue triggers names too automatic because:
1. we need to that both the [Queue] and [QueueTrigger] are in sync. Queues are global resources within a storage account, so you need to take some care that they don't conflict. 
2. As we get cross-language (like Node) and Azure Functions, code may not have a class name. 

How's this:
```
public class Config {  // Central place to identify your queues. 
 public const string Queue1= "q1";
 public const string Queue2= "q2";
}
public class Job1
{
    public static void ProcessQueueMessage([QueueTrigger(Config.Queue1)] string message)
    {
        //todo...
    }
}

public class Job2
{
    public static void ProcessQueueMessage([QueueTrigger(Config.Queue2)] string message)
    {
        //todo...
    }
}
```

**Comment by will-beta** [comment]
@MikeStall Thanks for replying!
I understand your concerns.
Actually, we can survive without that, though we have dozens of web jobs.
But sometimes programmers made mistakes by the hardcoding, and it took us quite some time to find  what was really going on and fix them.
