### ISSUE TITLE
Support for controlling task awaiting 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1140]
Some extensions, like durable tasks, need better control of the await semantics. 

Our current pipeline is like:
Pre() 
await UserFunction()
Post() // does cleanup logging, etc 

And we need to allow 
Pre()
Task t = UserFunction()
Post() 
// do some checking on T. 

This would be consumed by the extensions trigger binder. This is likely on ITriggeredFunctionExecutor.

**Comment by MikeStall** [comment]
Mathew has a PR that supersedes 1167

**Comment by mathewc** [comment]
Addressed by https://github.com/Azure/azure-webjobs-sdk/pull/1178
