### ISSUE TITLE
Would like to have a execution context parameter for BeginProcessingMessageAsync & CompleteProcessingMessageAsync in QueueProcessor

### ISSUE THREAD

**Issue by will-beta** [Azure/azure-webjobs-sdk#1151]
It would be very convienient for us to be able to know which method will/have process(ed) the message.
Actually, in our projects, there're some common actions needed to be executed for the message, and the actions need some information of the method or the class (instance) outside.

**Comment by mathewc** [comment]
Might a feature like invocation filters https://github.com/Azure/azure-webjobs-sdk/issues/980 address your need? Is the logic you need to run specific to queues, or is it more general?

**Comment by will-beta** [comment]
@mathewc yes, this is exactly what I need !
Thanks!

**Comment by mathewc** [comment]
Addressed via the Invocation Filters feature #980
