### ISSUE TITLE
Validate attribute for bindings

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1169]
Add a binding attribute "Validate", that goes on other binding properties (similar to AutoResolve, AppSeting) which enforces validation to a regex. 

```
        [AutoResolve]
        [Validate(Required = true, Regex = "^[A-Za-z][A-Za-z0-9]{2,62}$")]
        public string TableName
```
This would be enforced by AttributeCloner. 
This can also deal with the %% / { }   problem.  If a property is missing { }, we can validate statically (earlier). If it has { } , we must validate later. We have tests and existing expectations about validating early when possible. 

1. This lets us remove hacky code like this: 
```
        private static void ValidateAttribute(TableAttribute attribute, Type parameterType)
        {
            // Queue pre-existing  behavior: if there are { }in the path, then defer validation until runtime. 
            if (!attribute.TableName.Contains("{"))
            {
                TableClient.ValidateAzureTableName(attribute.TableName);
            }
        }
```
Many bindings (Blob, Table,Queue) have this sort of adhoc checking that can be replaced. 

2. Enables the portal to get the validation regex (https://github.com/Azure/azure-webjobs-sdk-script/issues/1416 ) 

3. Remove  BindingFactory.AddValidator -  https://github.com/Azure/azure-webjobs-sdk/issues/757

**Comment by mathewc** [comment]
DataAnnotations: https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations(v=vs.110).aspx

**Comment by paulbatum** [comment]
Can we use the existing data annotation attributes instead of creating our own? There is already an ecosystem of tools and libraries that understand these.

**Comment by MikeStall** [comment]
We could. Is it ok to take the new dependency on System.ComponentModel.DataAnnotations?

**Comment by MikeStall** [comment]
Replacing Queue and Table can be tricky. a) there's a lot of existing cruft; b) they have some richer errors beyond just RegEx. 

Several phases here:
1. Expose this for extensions., 
2. Solve https://github.com/Azure/azure-webjobs-sdk/issues/757
3. Remove obvious hacks for Table + Queue (see comment above).
4. Fully apply to all internal types (Table, Blob, Queue)  and purge old-style validation logic. 

Queue has custom logic that's richer than just a regex: https://github.com/Azure/azure-webjobs-sdk/blob/663a508e8a851629c26a51e7de3af36629dfd120/src/Microsoft.Azure.WebJobs.Host/Queues/QueueClient.cs#L47 

We could apply this to Table's Name, RowKey, PartitionKey.
