### ISSUE TITLE
SDK should Honor FunctionName attribute 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1170]
We added a FunctionName attribute https://github.com/Azure/azure-webjobs-sdk/pull/1075 
It's only a placeholder used by VS tooling, but SDK should honor this attribute too and plumb it through. 

1. Function indexing 
2. {sys.MethodName} 
3. JobHost.Call?    (maybe moot since that uses MethodInfo, but double check) 
4. Dashboard 
5. New InvokeFunctionFilterAttribute attribute that specifies function names

**Comment by paulbatum** [comment]
sys.MethodName should be the actual name of the method, it shouldn't be overridden by the functionname attribute

**Comment by MikeStall** [comment]
@paulbatum  -  I'd disagree.  The actual C# method name should be viewed as an implementation detail - we don't want things taking a direct dependency on that. VS Tooling includes [FunctionName] attributes by default and that's what they show up in Script.  For example, Bot uses {sys.MethodName} and expects to get the Script function name which would be [FunctionName].

**Comment by fabiocav** [comment]
I agree that {sys.MethodName} should reflect the method name as opposed to the logical function name. If we want to expose a way to get the function name, we should probably introduce a {sys.FunctionName} instead, as passing the function name when binding to the method would be surprising/confusing.

**Comment by MikeStall** [comment]
@fabiocav  - please see my comments above. Exposing the reflection name would actually be incorrect; and there's not a good reason to add that low-level functionality.

**Comment by fabiocav** [comment]
I agree, but I'd argue that, given its name today, that's what people would expect. We don't refer to the function name as a method name anywhere. Introducing a FunctionName and perhaps deprecating MethodName would probably be the right approach.

**Comment by MikeStall** [comment]
This is recently new surface area. If it's a naming issue, we can do a full rename MethodName --> FunctionName, and we just need to update BOT.  But we shouldn't have anything handing out the underlying Reflection name.

**Comment by paulbatum** [comment]
I'm fine with that, assuming we never disclosed sys.methodname publicly and therefore not a breaking change

**Comment by MikeStall** [comment]
It was added here: https://github.com/Azure/azure-webjobs-sdk/commit/962dfa6ff28fd14f960cc948bc3a40e420f5713e
