### ISSUE TITLE
Remove JobHostConfiguration.HostMetadata

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1179]
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs#L303

I think this API was added in haste, and we can improve here. We don't what this Azure Functions specific concept sitting top level on this core config object. Instead, we should investigate pushing this into a metadata provider service that is registered or something.

**Comment by MikeStall** [comment]
Some background:  we needed extensions to be fully self-describing and initialize themselves from host.json, without any imperative code.  
This then  feeds into the ApplyConfig() method that extensions can call to pull config.

**Comment by mathewc** [comment]
This issue is obsolete after the v2 migration.
