### ISSUE TITLE
Allow for hooking in predefined methods to incoming bindings

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-webjobs-sdk#1186]
https://github.com/Azure/azure-webjobs-sdk/issues/1041
https://github.com/Azure/azure-webjobs-sdk/issues/734
https://github.com/Azure/azure-webjobs-sdk/issues/980
https://github.com/Azure/azure-webjobs-sdk/pull/1167

Along the same lines as those above but with a few twists:

1) predefined commonly used functions
2) written in C# usable by others
3) reduces function code 
4) Standardised and tested to run reliably on Appservice environment.

# Description
One promise of serverless is to write only your business logic and we take care of the rest. Functions addresses a lot of the machinations related to running the user’s code. However the code is still not business logic. Common tasks like transforming between formats, compression/encryption are still handled by the users. There are also nuances related to these operations running on the azure functions sandbox that both users and our support folks can live without. 

# Enter functions filters  

The proposal is to have a standard set of functionality available as “filters” to users likely as an IBinder interface. Any function can include the filter and the based on the configuration set in function.json the filter would run the custom operation on the incoming Stream. 
In short the incoming stream would get applied to another binder before/after the main binder is done with its job.

``` javascript
{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "filters": "certdecrypt{param1,param2}",
      "path": "samples-workitems/{name}",
      "connection": "AzureWebJobsDashboard"
    },
    {
      "type": "blob",
      "name": "outputBlob",
      "path": "outcontainer/{rand-guid}",
      "filters": "certencrypt{param1,param2},zip",
      "connection": "AzureWebJobsDashboard",
      "direction": "out"
    },
    {
      "type": "blob",
      "name": "inputBlob",
      "path": "incontainer/{name}",
      "filters": "unzip",
      "connection": "AzureWebJobsDashboard",
      "direction": "in"
    },
    {
      "type": "http",
      "name": "res",
      "filters": "addcerttorequest{param1,param2}",
      "direction": "out"
    }
  ],
  "disabled": false
}

**Comment by mathewc** [comment]
Going to close this because the Function Filters feature has been checked in (see https://github.com/Azure/azure-webjobs-sdk/issues/980). That feature allows you to apply custom pre/post logic to function parameters. I think that would enable your scenario.

**Comment by fashaikh** [comment]
Yes I looked at it. Thanks !
I think a metadata driven approach would be more standard across C# and Node.js

**Comment by mathewc** [comment]
We will be allowing filters to be used in other languages soon, tracked by https://github.com/Azure/azure-webjobs-sdk-script/issues/1761.
