### ISSUE TITLE
Wiki page "StackOverflow for WebJobs" link not correct

### ISSUE THREAD

**Issue by SummerSun** [Azure/azure-webjobs-sdk#1196]
In wiki page,  "StackOverflow for WebJobs" link not correct: http://stackoverflow.com/questions/tagged/azure-webjobssdk
Should be: http://stackoverflow.com/questions/tagged/azure-webjobs

It is a little difficult to create a pull request to fix wiki, so I just submit an issue for your information.

**Comment by paulbatum** [comment]
Fixed
