### ISSUE TITLE
Webjobs Dashboard does not show Function Invocations when sharing the same Storage Account Dashboard

### ISSUE THREAD

**Issue by anblanco** [Azure/azure-webjobs-sdk#1213]
When creating 2 webjobs with the same name in different app services, and using the same storage connection string, the dashboard for function invocations can fail to display for one of the webjobs.

It would appear that 2 webjobs of the same name sharing a storage connection string is not supported by the SDK - this causes weird behavior in the dashboard.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a webjob that uses the functions sdk
2. Create an app service such as appservice-test with a webjob name "job" and a given storage connection string

e.g. appservice-test, "job", AzureWebJobsStorageDashboard="storageconnection1"

3. Create a second app service such as appservice-prod with a webjob of the same name and using the same connectionstring

e.g. appservice-prod, "job", AzureWebJobsStorageDashboard="storageconnection1"

4. Visit the Dashboard for the both webjobs 

#### Expected behavior

Both Dashboards show their respective function invocations, or an error / alert is presented

#### Actual behavior

Dashboard 1 (appservice-test) shows function information correctly
Dashboard 2 (appservice-prod)does not show function information correctly

#### Known workarounds
Looking into our configurations, we noticed that we were using the same storage connection string for both webjobs dashboards, so we changed the connection string on the 2nd instance and the portal began working again. 

Looking more into the SDK, it appears that the dashboard infers a lot of metadata based on the existence of certain blobs and blob paths. When we have the same job name in the same storage account, there was collision in some of the paths causing the webjobs dashboard not to display correctly. I'm not certain if this would've affected any other behavior (such as singleton)

#### Related information 

N/A

**Comment by christopheranderson** [comment]
Need to look at this the next batch of Dashboard issues we investigate. Not prioritizing since this isn't blocking.

**Comment by mathewc** [comment]
See my explanations here https://github.com/Azure/azure-webjobs-sdk/issues/1541 on the subtleties of sharing a storage account across multiple WebJobs. I think in your case it all comes down to HostID - if the job functions running in the 2 different WebApps have the same host ID they'll conflict.
