### ISSUE TITLE
Did ValueWatcher references get deleted erroneously?

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1217]
Microsoft.Azure.WebJobs.Host.Executors.ValueWatcher is no longer used.  
However, @mathewc had concerns that somebody should be using it for the Dashboard, and perhaps the usage was erroneously deleted and should be revisited.  This may have broken a dashboard feature. 

Recommended syncing to an older SDK and seeing if there was a reference to it that got deleted. 

I deleted the class permenantly in this PR since there were no references:  https://github.com/Azure/azure-webjobs-sdk/pull/1209
But if there is a reference that should be there, we'll need to add the class back.

**Comment by mathewc** [comment]
Closing this since it appears there isn't an issue. We can reopen if one is discovered.
