### ISSUE TITLE
Configure ServiceBusTriggerAttribute from AppSettings

### ISSUE THREAD

**Issue by juchom** [Azure/azure-webjobs-sdk#1221]
I'm developing an application where the infrastructure is completely deployed with ARM.
I create the service bus / the topic / the subscription with it also.

In my azure functions, I set the app settings for the service bus with ARM also.

Currently only the Connection parameter parameter looks in app settings.

Since the Attribute is sealed and it wants constant parameters there is no way to fix this.

```csharp
[FunctionName("MyFunction")]
public static void Run(Run([ServiceBusTrigger("MyTopic", "MySubscription", AccessRights.Listen, Connection = "ConnectionString")]BrokeredMessage mySbMsg, TraceWriter log)
```

It would be nice to have MyTopic & MySubscription fetched from AppSettings like the ConnectionString

**Comment by TheeJamesLee** [comment]
Been in the same boat.  It is already done.

Have a look at this sample function [here](https://github.com/Azure-Samples/functions-customer-reviews/tree/master/Source/ContentModeratorFunction) and in the AnalyseImage.cs file at the trigger attribute:

```
[FunctionName("ReviewImageAndText")]
  public static async Task ReviewImageAndText(
  [QueueTrigger("%queue-name%")]  ReviewRequestItem queueInput,
  [Blob("input-images/{BlobName}", FileAccess.Read)]  Stream image,
  [DocumentDB("customerReviewData", "reviews", Id = "{DocumentId}", PartitionKey = "Reviews", ConnectionStringSetting = "customerReviewDataDocDB")]  dynamic inputDocument)
  {
```

In the QueueTrigger,   the '%' is specifying that it wants to be resolved from a setting.  This will look (when deployed on azure) at the WebApp settings you can set via arm.  When running functions locally, they are defined in the [local.settings.json](https://github.com/Azure-Samples/functions-customer-reviews/blob/master/Source/ContentModeratorFunction/local.settings.json) as you can see in the sample app, that the queue-name has been assigned there.

In the ARM template, as normal, resolve and apply the values as settings in the web app properties with the same name as you use for the config setting in local.settings.json, which is the same as between the %'s

**Comment by juchom** [comment]
Perfect this works like a charm!

Is there any documentation about this syntax? I've never seen it before...

Thanks

**Comment by TheeJamesLee** [comment]
There is somewhere... couldn't re find the link I found a while back whilst writing the above. If I spot to again I'll put it here.  
It's to do with Webjob Trigger Bindings.

**Comment by juchom** [comment]
Found it here: [Azure Functions triggers and bindings concepts](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings)

Check this part in the doc: "Resolving app settings"

**Comment by TheeJamesLee** [comment]
👍 yes, that's where I found it originally

**Comment by tsahi** [comment]
How does this help? `QueueTrigger` is for storage queue, and `ServiceBusTrigger` is for Service Bus queue.

**Comment by PhilKermeen** [comment]
Thanks! @tsahi the look up from settings / config is the same regardless of the trigger

**Comment by dasiths** [comment]
Does this work for web jobs sdk as well? I've used this with Azure functions but wasn't able to get it working with webjobs. The web jobs sdk official documentation says to do this for custom binding expressions https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#custom-binding-expressions

**Comment by grahambunce** [comment]
I think you can make this work in webjobs by getting the variable you need from App Settings in the program.cs host, and then setting it as an environment variable, e.g.

<code>
Environment.SetEnvironmentVariable("regional-subscription-name", regionalSetting);
</code>

and then

<code>
public async Task ExecuteAsync(
		[ServiceBusTrigger("patroncirculation", "%regional-subscription-name%")]Message msg)
</code>

**Comment by rhythmnewt** [comment]
In my case i have config for keyvault loaded first, then I have to load keyvault, then I have to deserialize my credentials from keyvault and only then I can have the service bus connection string to bind to. It took me a bit of time to get it right, but here's the solution in case someone else runs into same issue. Hope it helps someone!
```
           // Gets the default configuration so we can load keyvault
            var bootstrapConfig = new ConfigurationBuilder()
                .AddEnvironmentVariables("config:") //this only picks app settings that start with "config:" and at the same time strips off "config;" after load
                .Build();

           //get the keyvault URL from current config
           var keyvault = bootstrapConfig["VaultBaseUrl"];

            // Creates a new config based on the default one and adds the keyvault configuration builder
            var keyVaultConfig = new ConfigurationBuilder()
                .AddConfiguration(bootstrapConfig)
                .AddAzureKeyVault(keyvault)
                .Build();

            //this is my custom step to deserialize JSON in mycustomsecret to an POCO that I can work with
            var credentials = CredentialManager.GetFromString(keyVaultConfig["mycustomsecret"]);

            //this is needed for the servicebus function binding to work properly
            Environment.SetEnvironmentVariable($"dynamic:ServiceBusConnectionString", credentials.ConnectionStrings.ServiceBus);

            //creates a final config including dynamic environment variables used for function bindings like ServiceBus
            var config = new ConfigurationBuilder()
                .AddConfiguration(keyVaultConfig)
                .AddEnvironmentVariables("dynamic:") //this only picks app settings that start with "dynamic:" and at the same time strips off "dynamic;" after load
                .Build();

            //this is required to replace the IConfiguration with current settings otherwise the new Environment variable isn't picked up
            builder.Services.AddSingleton<IConfiguration>(config);
```
Now when setting up the binding for the function I can reference the new environment variable
```
        [ServiceBusAccount("ServiceBusConnectionString")]
        [FunctionName("ProcessMessage")]
        public async Task ProcessMessage([ServiceBusTrigger("%myQueueName%")] Message message, ILogger log, CancellationToken cancellationToken, MessageReceiver messageReceiver)
        {
              var request = JsonConvert.DeserializeObject<dynamic>(Encoding.UTF8.GetString(message.Body));
        }
```

local.settings.json
NOTE: You will get a warning on build/run that ServiceBusConnectionString doesn't exist in local.settings.json
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "config:VaultBaseUrl": "https://MYKEYVAULT.vault.azure.net",
    "myQueueName": "service-bus-dev-queue"
  }
}
```

**Comment by JohanForngren** [comment]
Necroposting in case some else stumbles in here trying to figure out how to do this with Azure App Configuration.
```
    public override void Configure(IFunctionsHostBuilder builder) {
       ConfigurationBuilder configurationBuilder = new();
       configurationBuilder.AddAzureAppConfiguration( /* ... */ );
       var configurationRoot = configurationBuilder.Build();
       builder.Services.AddSingleton <IConfiguration>(configurationRoot);
```

```
    [FunctionName("Function")]
    public void Run(
        [ServiceBusTrigger("QueueName", Connection = "ConnectionStrings:ServiceBus")] string myQueueItem, string messageId) {
```

```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "ConnectionStrings:ServiceBus": "This value will be overwritten from App Configuration in Startup.cs. This text just suppresses the build warning."
    }
}
```
