### ISSUE TITLE
Webjobs Dashboard does not show Function Invocations when Function invoked from Worker Role

### ISSUE THREAD

**Issue by raxitr** [Azure/azure-webjobs-sdk#1252]
I have deployed Web Job function in a worker role with queue trigger. I noticed function invocation from worker role does not get displayed on a dashboard however when I invoked function from the dashboard it is getting displayed correctly. 

#### Repro steps

1. Write a function with QueueTrigger
2. Deploy it within Worker Role
3. Create an Empty Web App in azure portal and add storage connection AzureWebJobsDashboard string same used by worker role app.
4. Check the Dashboard and it shows the function.
5. Added a message in queue and function invoked successfully in Worker role.
6. Dashboard does not display anything in recent invocation and execution stats are zero.
7. Invoke the function from Dashboard and invocation stats are getting displayed correctly.

#### Expected behavior

Function invocation should get displayed in dashboard for all executions.

#### Actual behavior

I am seeing blob is getting created inside  azure-webjobs-dashboard > functions > instances but only function executed from dashboard is displayed. 

* Package version
Microsoft.WinowsAzure.Storage Version 7.2.1.0
Microsoft.Azure.Webjobs Version 2.0.0.0

**Comment by christopheranderson** [comment]
Do you see data from your Worker Role showing up in your storage account or only data from running via the dashboard. Do you see any differences between the two pieces of data? Host id or something?

**Comment by raxitr** [comment]
I see it in the storage from worker role as well and there is no difference
in the host Id.  There are couple places where blobs are written so not
sure where else to compare. I see the one ran from dashboard is moved to
archive whereas the one from worker role still present in
 azure-jobs-host-output.

Let me know if you need further details

**Comment by raxitr** [comment]
I no longer experience the issue after deploying worker role to production slot. Dashboard is getting displayed correctly. 

Does it have to with Debug/Staging deployment where dashboard does not work?

**Comment by christopheranderson** [comment]
To be honest, we don't actively test WebJobs SDK running anywhere outside of Web Apps, so we're not sure what might be causing the issue with Worker role. 

Do you see your old data s well as new data in now that you moved the slots? Were you definitely looking at the right scm endpoint for the dashboard?

**Comment by raxitr** [comment]
Unfortunately I have cleaned everything before going to production so can't
confirm. The dashboard was correct since it was showing my function but not
statistics.
