### ISSUE TITLE
Create `dotnet new` template nuget for folks to install

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk#1255]
If we create a template and publish it as a nuget, people can install it via `dotnet new -i <NUGET>`. We should do this for the 3.0.0 release.

**Comment by christopheranderson** [comment]
Created a PR for this: https://github.com/Azure/azure-webjobs-sdk-templates/pull/506

**Comment by paulbatum** [comment]
Closing as there is a pr open against templates
