### ISSUE TITLE
setting BatchSize out of range (>32) results in silent host exception in functions

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk#1261]

**Comment by paulbatum** [comment]
Cases where bad user input results in silent failure are definitely problematic, they just lead to time wasted by both the user and us once they request assistance.

I believe this is referring to the batchsize property in the queues section of the host.json.

**Comment by mathewc** [comment]
I just tried to repro this in prod and I get an error popup as expected in the portal:

_"The function runtime is unable to start. Please check the runtime logs for any errors or try again later. Newtonsoft.Json: Error setting value to 'BatchSize' on 'Microsoft.Azure.WebJobs.Host.JobHostQueuesConfiguration'. Microsoft.Azure.WebJobs.Host: Specified argument was out of the range of valid values.
 Parameter name: value."_

Now you could argue that the error message could be improved, but it doesn't error silently. E.g. I don't think we should be letting the Newtonsoft.Json details slip here - user just wants to see the inner error.

**Comment by paulbatum** [comment]
Yup, I tried another case:

`The function runtime is unable to start. Please check the runtime logs for any errors or try again later. Microsoft.Azure.WebJobs.Script: FunctionTimeout must be between 00:00:01 and 00:10:00.`

@kashimiz looks like this bug can be closed as no-repro. Maybe some other change made in the last few months had a side effect of fixing this?
