### ISSUE TITLE
Increase BatchSize limit beyond 32

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk#1262]
I can't find a reason for this arbitrary number and have created scenarios limited by this parameter.

**Comment by paulbatum** [comment]
@mamaso Batch limit of what? Storage queues? Its not our limit, its theirs.

**Comment by christopheranderson** [comment]
Is there any good scenarios for why we'd need to do this?

**Comment by mamaso** [comment]
Forgot to update this, yep it is the limit that their batch api supports - couldn't find the documentation for it so I did a quick manual test

The scenario is when more parallelism is required, but it seems like that can be achieved by setting `NewBatchThreshold` above `BatchSize`: https://stackoverflow.com/questions/35678524/how-to-maximize-webjob-cpu-usage

**Comment by mamaso** [comment]
For an example of a scenario, queue -> webhook function only utilizes ~5% cpu and doesn't necessarily use max machine connections
