### ISSUE TITLE
WebJobs Host

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-webjobs-sdk#1303]
Please consider implantation of the WebJobHost using ASP.NET Core Kestrel as IMHO would make the host image smaller (no need for IIS) more performant, it would also give possibility of a cross platform implementation of the host.

**Comment by fabiocav** [comment]
https://github.com/Azure/azure-webjobs-sdk-script/tree/core :)

**Comment by christopheranderson** [comment]
We've already converted WebJobs SDK to .NET core 2.0. We don't use Kestrel/ASP.NET in WebJobs SDK. For Functions (Webjobs SDK Script), we're moving to .NET core 2.0, as Fabio linked, which will use Kestrel by default.
