### ISSUE TITLE
Correlate enqueued message and triggered function?

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#1309]
To my knowledge currently there is no mechanism to correlate a message that was put into a queue and a function that was triggered by that message/queue.

Here's a real-world scenario:

1. API accepts a request which would take longer than 230 seconds to process (Azure balancer hard-coded timeout)
2. API generates an ID, puts it into message, puts message into queue
3. API returns HTTP status 202 Accepted with the Location header pointing to another endpoint which would provide request processing status, e.g. /api/queue?id={guid}
4. Function is triggered, reads the ID from message, updates status in custom storage to 'processing'
5. Function is completed, updates status to either 'processed' or 'error'.
6. All this time caller queries the status endpoint to check request status

It would great to simplify 3,4,5 such as:

- Enqueuing a message would provides an ID which would be used to correlate message and trigger
- Internal host IDs could be used for such correlation
- An API could be exposed (hosted by Kudu) that would provide such correlation

Closes #735.

**Comment by mathewc** [comment]
Perhaps related to https://github.com/Azure/azure-webjobs-sdk/issues/1304?

**Comment by abatishchev** [comment]
I'm willing to do the HTTP part myself (the API in above scenario is mine), what I'm missing is the correlation. Currently (if I don't miss anything) enqueuing is similar to fire-and-forge, isn't it? How to get know whether the trigger has been triggered, whether the message was processed successfully or ended up in the dead-letter queue?

**Comment by christopheranderson** [comment]
We don't think we'll do this for Functions anytime soon, but you can implement at pattern like Durable Functions where:
HTTP Trigger creates a correlation id and puts it in SQL/Table storage, drops a queue message with that id, and the queue trigger then updates the SQL/Table storage when complete, with a final HTTP triggered Function reading the status/result from SQL/Table storage.

**Comment by abatishchev** [comment]
Yes, I'm doing the storage part myself right now. And not really ask to implement it by the SDK. Or maybe I do buy only partially.

Remember the issue I opened first (see above)? The issue is that there is a plenty of ids but they all are different, no way to correlate what was put into the queue and what was read from the queue. Right now the only way is to generate your own id and persist it in the message payload.

And that's what my ask is about. Make possible/simplify (if I'm missing something) this correlation.

**Comment by abatishchev** [comment]
@mathewc hi, should we come back to this idea? Or give up and close?

**Comment by mathewc** [comment]
Yes, we're not planning on adding any first class features for this currently. I think this is best left to application code - you should have everything you need to implement this for your specific scenario.
