### ISSUE TITLE
Add Uri support to blob 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1320]
Allow [Blob] binding to work with URi (instead of just Container/BlobName). 
This should enable blob bindings to SAS URL or public URLs. 
This means we could get a blob binding without specifying a connection property

IE, 
Function([Blob(Path=”https://test.blob.core.windows.net/test/public.txt”)] CloudBlob x)

**Comment by christopheranderson** [comment]
Fixed in https://github.com/Azure/azure-webjobs-sdk/pull/1315

**Comment by watashiSHUN** [comment]
![image](https://user-images.githubusercontent.com/6531400/37055862-a1f0fc88-2137-11e8-99cc-8b6171fc3518.png)

For eventGrid, we only have public blob URLs, not SAS URL
