### ISSUE TITLE
Push updated 2.1.0 bits to NuGet

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk#1330]
We need to push an updated package with the recent changes made to 2.x. (2.1.0)

In addition to enabling customers to consume those enhancements, the Event Grid extension, Durable Functions and the Functions SDK all depend on newer functionality not available in what we have published.

**Comment by lindydonna** [comment]
When this is done, please notify @lindydonna, @ahmelsayed and @soninaren so we can update the Visual Studio tooling.

**Comment by fabiocav** [comment]
This has been completed: https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.1.0-beta3
