### ISSUE TITLE
FunctionName attribute resolves templated strings.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-webjobs-sdk#1334]
The Durable Functions team would like the FunctionName attribute to resolve templated strings. This is important for [#27](https://github.com/Azure/azure-functions-durable-extension/issues/27) (Versioning) as we need to do models like 'myOrchestration-%version%' to handle graceful version rollover.

**Comment by MikeStall** [comment]
After some discussion, we've decided to not do this. While it's easy enough to do in the SDK; it creates problems for Scale Controller, Portal, and VS Tooling - all of which expect function names to be stable regardless of appsettings.
