### ISSUE TITLE
3.0.0-beta2 release in NuGet appears to be unsigned

### ISSUE THREAD

**Issue by idg10** [Azure/azure-webjobs-sdk#1335]
The current latest publicly available version of this SDK up on NuGet is the 3.0.0-beta2 preview. It seems to contain unsigned assemblies (built for delay signing, but the delay signing was never done). I know delay signing is what we are required to work with if doing development work on this code, but this is the first time I've come across a Microsoft component published to the main NuGet feed (even if in preview) that contains unsigned assemblies. So I'm not sure if this was intentional.

#### Repro steps

1. Create a new C# WebJob project.

2. In the NuGet package manager, check "Include prerelease" and then upgrade `Microsoft.Azure.WebJobs` to 3.0.0-beta2.

3. Attempt to run the program. It will fail with this log output:

`An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)`

#### Expected behavior

I would normally expect preview components released on the main NuGet feed by Microsoft to work without requiring me to disable strong name validation.

#### Actual behavior

This preview cannot be used without disabling strong name validation for the relevant assemblies.

#### Known workarounds

You can disable strong name validation for the relevant assemblies. (This is normal for anyone working on the code directly, and is not uncommon when working with CI builds or nightly builds, but is not normal for public NuGet releases.)

#### Related information 

* 3.0.0-beta2
* https://github.com/Azure/azure-webjobs-sdk/releases/tag/v3.0.0-beta2
* https://www.nuget.org/packages/Microsoft.Azure.WebJobs/3.0.0-beta2

**Comment by fabiocav** [comment]
Thank you for bringing this up! The signing properties were not supposed to be set in 3.0 as the signing process was intentionally disabled, at least for the time being. We'll have new packages published soon.
