### ISSUE TITLE
ServiceBus should use INameResolver, not ConfigurationManager

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#1347]
ServiceBus should use INameResolver for getting appsettings - not ConfigurationManager. 
This came up here: https://stackoverflow.com/questions/46272395/override-net-connection-string-resolution

**Comment by paulbatum** [comment]
Lets make sure the service bus extension for v2 uses INameResolver as part of the porting work.

**Comment by RyanONeill1970** [comment]
Should this be closed now? INameResolver works for me. https://stackoverflow.com/questions/46272395/override-net-connection-string-resolution

**Comment by alrod** [comment]
yes, INameResolver already works
