### ISSUE TITLE
[AppInsights] Allow for QuickPulse AuthenticationApiKey

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#1349]
Create an easy way to authenticate QuickPulse for filtering: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream#secure-the-control-channel

**Comment by paulbatum** [comment]
So basically we need a well established name for this API key environment variable that we naturally pick up? It does occur to me, does app insights have any functionality for picking this key up ambiently?

**Comment by harshithkashyap** [comment]
@brettsam @paulbatum The grace period telemetry filter without Authenticated channel has expired. Currently, there is no way to filter the Quick Pulse telemetry without setting up authenticated channel using API key as mentioned in the docs. I see that the issue is in Backlog milestone. Could you get this feature to be implemented sooner?
![image](https://user-images.githubusercontent.com/4183260/45072395-5d63ce00-b0f8-11e8-9b47-204eb816e0ed.png)

**Comment by paulbatum** [comment]
@lmolkova Can you help us with this one? Is there an app setting that can be set that the app insights SDK will pick up and use as the API key?

**Comment by lmolkova** [comment]
@brettsam @paulbatum 

sure, this could easily be done by setting `quickPulseModule.AuthenticationApiKey = "YOUR-API-KEY"` [here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs#L178)

I'll submit a PR to add a new property on `ApplicationInsightsLoggerOptions` in webjobs. Functions would need to read it from env variable or other secure ~~enough~~ channel.

**Comment by paulbatum** [comment]
Just to be 100% clear I was asking something slightly different.. is there already a known environment variable (i.e. app setting) that App Insights reads this from? Think of it as an equivalent of `APPINSIGHTS_INSTRUMENTATIONKEY`. That way we don't need functions to define a new app setting for this.

**Comment by brettsam** [comment]
`APPINSIGHTS_INSTRUMENTATIONKEY` is (kind of) our key -- I believe App Service introduced it before us. App Insights doesn't inherently know anything about it. We're using it b/c the tooling will auto-set it for us without much extra work. We'll likely need to define a new key and plug it in similarly.

**Comment by lmolkova** [comment]
APPINSIGHTS_INSTRUMENTATIONKEY is widely used besides AppService and is AI concept. But it's a bit special - almost all other settings are done explicitly through the config/code.
So, unfortunately, no, there is no setting based on environment variable for quick pulse auth key.

**Comment by paulbatum** [comment]
My bad, thank you for the clarification.

**Comment by brettsam** [comment]
All that being said -- is there a nice key we can use and try to make standard? `APPINSIGHTS_QUICKPULSEAPIKEY`? Other suggestions? Once we have a name, it should be easy to get working from functions with an app setting.

**Comment by lmolkova** [comment]
We've chatted about it in the team. It seems that having this setting through environment variable like APPINSIGHTS_QUICKPULSEAPIKEY makes sense for AppInsights SDK for runtime/extension based AppInsights instrumentation. 

We'll consider supporting it natively on SDK side and also auto-enablement experience to apply env variable when user requests auth key.

@tokaplan, assuming we'll do this at some point do you think APPINSIGHTS_QUICKPULSEAPIKEY is a good name for such env variable?

**Comment by brettsam** [comment]
I'm looking at getting this wired-up for Functions very soon -- do we want to lock on a name for us to stick with? Are you okay with APPINSIGHTS_QUICKPULSEAUTHENTICATIONAPIKEY? It's the accurate name -- but a little verbose :-)

**Comment by dotsad** [comment]
@brettsam any updates on this? Thanks.

**Comment by brettsam** [comment]
@lmolkova / @tokaplan -- are you okay with us going with `APPINSIGHTS_QUICKPULSEAUTHENTICATIONAPIKEY` as the app setting?

**Comment by lmolkova** [comment]
I'm fine either way, but APPINSIGHTS_QUICKPULSEAUTHAPIKEY seems a bit shorter and still descriptive enough

**Comment by tokaplan** [comment]
I like APPINSIGHTS_QUICKPULSEAUTHAPIKEY as well.

**Comment by asvishnyakov** [comment]
Because this is AppInsights API Key, not something special for QuickPulse, I will propose APPINSIGHTS_AUTHAPIKEY name

**Comment by brettsam** [comment]
Sounds good -- I'll go with `APPINSIGHTS_QUICKPULSEAUTHAPIKEY`. This should be a fairly quick change so I'll try to get it into our current Sprint, which means it should release with our first Functions release in January.
