### ISSUE TITLE
Log Event Hubs related exceptions captured by ProcessErrorAsync

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#1357]
This code appears to be silently throwing away errors that come from event processor host.
https://github.com/Azure/azure-webjobs-sdk/blob/901764c1aa610685ce850748103c8554aef3d250/src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs#L117-L121

We need to wire this code path up to both system logs and application logs.

**Comment by paulbatum** [comment]
Ideally fix for both functions v1, v2

**Comment by pragnagopa** [comment]
Will not porting this fix to V1 as [ProcessErrorAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.ieventprocessor.processerrorasync?view=azure-dotnet#Microsoft_Azure_EventHubs_Processor_IEventProcessor_ProcessErrorAsync_Microsoft_Azure_EventHubs_Processor_PartitionContext_System_Exception_)  - helper method where we can log underlying errors is only available in V2 as it depends on [Microsoft.Azure.EventHubs.Processor](https://www.nuget.org/packages/Microsoft.Azure.EventHubs.Processor/). V1 depends on [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) which does not have an equivalent of ProcessErrorAsync.
