### ISSUE TITLE
ILogger - LogException does not log Exception Message property

### ISSUE THREAD

**Issue by doreenali** [Azure/azure-webjobs-sdk#1365]
When using ILogger with Application Insights integration, passing an Exception should result in a row added to the exceptions table in AI with various exception properties, including Exception Message. Currently there are a lot of helpful properties there, including outerMessage and innermostMessage, but no message from the Exception.Message property, which contains whatever message is passed via new Exception("my message string").

Repro steps:

1. Set your Azure Function App up to send data to AI.
2. From an Azure function, make a call to your ILogger Log method with an exception that has a message.
3. In AI, Find your Exception in the exceptions table
4. Notice that the text you passed in as a message is in none of the properties.

**Comment by paulbatum** [comment]
@brettsam seems like a pretty bad one if true! Can you confirm?

**Comment by brettsam** [comment]
@doreenali -- can you add your line of logging code (step 2 above). 

It looks like the interplay betweeen the `Exception` and `Message` properties on `ExceptionTelemetry` isn't what I'd expected -- so if you set both it overwrites one. Internally, we only use this without a message so we'd never bumped into it. 

I want to see exactly how you're using it to see if I can come up with a plan -- it may mean that if you give us both an Exception and a message, we log one `ExceptionTelemetry` and one `TraceTelemetry`.

**Comment by doreenali** [comment]
This is the custom code we are currently using for logging:

	private const string EventNameKey = "eventName";
        private const string MessageKey = "message";
        private const string ExceptionMessageKey = "exceptionMessage";

        public static void Log(this ILogger logger, LogLevel logLevel, string eventName, string message, IDictionary<string, object> properties, Exception exception = null)
        {
            if (!properties.ContainsKey(EventNameKey))
            {
                properties[EventNameKey] = eventName;
            }
            if (!properties.ContainsKey(MessageKey))
            {
                properties[MessageKey] = message;
            }
            if (exception?.Message != null && !properties.ContainsKey(ExceptionMessageKey))
            {
                properties[ExceptionMessageKey] = exception.Message;
            }

            logger.Log(logLevel, new EventId(0, eventName), properties, exception, Format);
        }

You can test it with any Exception like this:

var exeption = new Exception("myExceptionMessage")
logger.Log(LogLevel.Information, "myevent", "mymessage", null, exception);

**Comment by brettsam** [comment]
What is `Format` in this case? I think this is inadvertently overwriting your Exception message.

Do you see your `prop__message` in `customDimensions? I want to make sure that it's showing up as expected as well.

I think the fix here will be to move the `Format` string to a dedicated value `LogMessage` (or something similar) in `customDimensions`. The `ExceptionTelemetry` doesn't have a first-class place to stick that value -- I thought `Message` was it, but that actually overwrites your exception's message.

**Comment by doreenali** [comment]
Not sure what you mean by "Format". There is no such field in my exception log. 

With the code above my message comes in under customDimensions as "prop__exceptionMessage"

**Comment by brettsam** [comment]
I meant the `Format` method that's passed in here: `logger.Log(logLevel, new EventId(0, eventName), properties, exception, Format);`

I really don't need that info anymore, though, as I worked through the issues. I've got a fix already checked in (#1380) so this should start working properly in a couple of weeks with our next release.

**Comment by doreenali** [comment]
Oh, got it. Thanks for digging into this for us!
