### ISSUE TITLE
Setting the AzureWebJobsStorage & AzureWebJobsDashboard in .net core 2.0 webjobs

### ISSUE THREAD

**Issue by mattwoberts** [Azure/azure-webjobs-sdk#1367]
I've got a webjob, coded in .net core 2.0, that I'm deploying to azure.

I have `AzureWebJobsStorage` and `AzureWebJobsDashboard` defined as connection strings in my appsettings.json. In azure application settings for my web app, I define values for these 2 connection strings in the format:

`DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=yyy;EndpointSuffix=core.windows.net`

Additionally, in my webjob code, I ensure the environment variables are set correctly with:

    Environment.SetEnvironmentVariable("AzureWebJobsStorage", configuration.GetConnectionString("AzureWebJobsStorage"));
    Environment.SetEnvironmentVariable("AzureWebJobsDashboard", configuration.GetConnectionString("AzureWebJobsDashboard"));

When I deploy this webjob and try to run it, it won't start, and the error is:

```
Unhandled Exception: System.InvalidOperationException: Failed to validate Microsoft Azure WebJobs SDK Dashboard connection string. The Microsoft Azure Storage account connection string is not formatted correctly. Please visit https://go.microsoft.com/fwlink/?linkid=841340 for details about configuring Microsoft Azure Storage connection strings.
```

*However* if I then change my code so that my connection strings in my appsettings.json file and in azure's application settings are renamed to something else (e.g. `WebJobsStorage` and `WebJobsDashboard`), and then I set them accordingly:

```
Environment.SetEnvironmentVariable("AzureWebJobsStorage", configuration.GetConnectionString("WebJobsStorage"));
Environment.SetEnvironmentVariable("AzureWebJobsDashboard", configuration.GetConnectionString("WebJobsDashboard"));
```

Then, when I run these webjobs, they do run without error. But when I try to visit the WebJobs Dashboard, I see:

```
The configuration is not properly set for the Microsoft Azure WebJobs Dashboard. 
In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored. 
```

I'm using the 3.0.0beta3 of the azure.webjobs.sdk.

Am I incorrectly configuring the webjobs, or is this a bug with the sdk?

**Comment by paulbatum** [comment]
Set them as app settings rather than connection strings and you shouldn't run into this.

**Comment by mattwoberts** [comment]
Sorry, but that doesn't work.

I can set an app setting, rather than a connection string, but then when I try to navigate to the web jobs dashboard:

![image](https://user-images.githubusercontent.com/109196/31549391-eb635966-b025-11e7-822f-4885a37c7499.png)

The only way I can get this working is to create duplicate connection strings - so I create my 2 connection strings `AzureWebJobsStorage` and `AzureWebJobsDashboard`, and then I need to create 2 other connection strings called something like `WebJobsStorage` and `WebJobsDashboard`, and then use those in my code via `SetEnvironmentVariable`

**Comment by mattwoberts** [comment]
Played with this some more, and it turns out it's a duplicate of https://github.com/Azure/azure-webjobs-sdk/issues/1408 so I'm going to close this, cheers 👍

**Comment by rochapablo** [comment]
it seems that this still happening. I had set AzureWebJobsDashboard and AzureWebJobsStorage, but the warning and error still there.
