### ISSUE TITLE
Azure WebJobs SDK Service Bus - Referencing DLL Issue

### ISSUE THREAD

**Issue by DeanShoultz** [Azure/azure-webjobs-sdk#1376]
I have created a simple web job that monitors a queue. The function is called properly passing in the message from my bus. There is a third-part DLL that I manually added to the References collection (not via NuGet). In the function, I have a using statement that leverages the methods in the library.

When I F5 to test, I get an error message that the DLL cannot be found, In the properties of the DLL, I have output set to True.

As further information, this project started with a previous VS project type that monitored a service bus, but the deployment target was a cloud service. Since Cloud Services are on the way out, I am trying to convert the same code to a WebJob SDK project. Doing so was quite simple, minus this one lingering issue. The same configuration works fine in the existing project, so it seems to be something unique to a WebJob SDK project.

Provide the steps required to reproduce the problem

1. Add a reference to the references collection. 

2. Build code that uses the reference.

I have no workarounds at this time. I feel I am missing something silly and obvious. :-) 

UPDATE: The referenced DLL is 64-bit. I experimented with changing the target platform but this had no effect.

**Comment by paulbatum** [comment]
It doesn't sound like this is a webjobs sdk issue. Unless you've found that referencing and using the same library from a console application works fine? If you think its a webjobs specific issue please reopen with full error details and fusion logs for the assembly load failure.
