### ISSUE TITLE
Azure WebJobs Dashboard fails to load for known Function Invocations

### ISSUE THREAD

**Issue by JoeBrockhaus** [Azure/azure-webjobs-sdk#1394]
I have an App with a series of continuous WebJobs running a high number of Service Bus Topic-driven invocations. The Dashboard will almost always say "Indexing in progress. Information may not be up to date." 

My jobs log some metadata out to Table Storage, and it includes the AzureWebJobs Id & ParentId for troubleshooting the Invocation. When troubleshooting, we use the dashboard, plugging in the JobId. 

When this issue occurs, more-recent 'New Invocations' are being shown down the Invocation Log, and clicking any of them shows the details. But if I replace the JobId with the Id from my external logging, the app redirects back to `#/functions/`. It will not always indicate 'Invalid Function invocation'. 

I also notice a high number of dependency fails to table storage in App Insights, and usually the CPU of the ASP will get maxed out. The ASP is currently scaled-out with 2 instances, but I've definitely seen this occur with a single instance. 

I am also interested in retrieving the Job Instance data programmatically. Can you point me in the direction of some documentation for querying this data directly so that I don't have to rely on the Dashboard?

**Comment by paulbatum** [comment]
It sounds like you are running into some of the limitations of the dashboard. Our investigations in high performance scenarios for webjobs and functions have lead us to App Insights being the best monitoring solution. The documentation on webjobs integration with App Insights is [here](https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration). 

I don't believe there is any documentation for the format of the data stored by the dashboard. Unfortunately you would need to go look at the blobs themselves in your storage account.
