### ISSUE TITLE
Missing documentation: build steps for signing assemblies

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-webjobs-sdk#1401]
I expected that the assemblies in all NuGet packages would be signed but the v3 beta packages I'd like to try are not. Do you have a signing procedure in place? Is it documented?

I have no choice but to consume nothing but signed assemblies. Here are the packages I would like to build, assuming you don't already produce signed versions:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Azure.WebJobs" version="3.0.0-beta3" targetFramework="net462" />
  <package id="Microsoft.Azure.WebJobs.Core" version="3.0.0-beta3" targetFramework="net462" />
  <package id="Microsoft.Azure.WebJobs.Extensions" version="3.0.0-beta3" targetFramework="net462" />
  <package id="Microsoft.Azure.WebJobs.Extensions.EventHubs" version="3.0.0-beta3" targetFramework="net462" />
  <package id="Microsoft.Azure.WebJobs.Extensions.Http" version="3.0.0-beta3" targetFramework="net462" />
```

**Comment by paulbatum** [comment]
Yes, we're not signing the webjobs and functions related assemblies we are generating for functions v2, webjobs v3. So its expected that there is no documentation, since there is no procedure. To sign this yourself, follow standard .NET signing procedures.
