### ISSUE TITLE
Appsettings.json override Environment variable values

### ISSUE THREAD

**Issue by nelsonmorais** [Azure/azure-webjobs-sdk#1408]
Looking at https://github.com/Azure/azure-webjobs-sdk/blob/v3.0.0-beta2/src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs I see that the BuildConfiguration function adds the Environment variables first and then the appsettings.json file.

#### Repro steps

See the code mentioned in the link above

#### Expected behavior

I would expect that the Environment variables would override the appsettings.json values (but please correct me if I'm wrong). At least this seems to be the correct practice according to the documentation available at: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration. See excerpt:

> It's typical to have different configuration settings for different environments, for example, development, test, and production. The CreateDefaultBuilder extension method in an ASP.NET Core 2.x app (or using AddJsonFile and AddEnvironmentVariables directly in an ASP.NET Core 1.x app) adds configuration providers for reading JSON files and system configuration sources:2
> 
> - appsettings.json
> - appsettings.<EnvironmentName>.json
> - environment variables
> 

So instead of this:
```
        private static IConfigurationRoot BuildConfiguration()
        {
            var configurationBuilder = new ConfigurationBuilder()
                .AddEnvironmentVariables()
                .AddJsonFile("appsettings.json", optional: true);

            return configurationBuilder.Build();
        }
```

I would expect this:
```
        private static IConfigurationRoot BuildConfiguration()
        {
            var configurationBuilder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: true)
                .AddEnvironmentVariables();

            return configurationBuilder.Build();
        }
```

#### Actual behavior

Appsettings.json values override Environment variables.

#### Known workarounds

No known workarounds.

#### Related information 

* See documentation on how to set up configuration settings in ASP.NET Core/.NET Core: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration

* Package version: v3.0.0-beta2
* Links to source:
https://github.com/Azure/azure-webjobs-sdk/blob/v3.0.0-beta2/src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs

**Comment by fabiocav** [comment]
@nelsonmorais there's a PR out but we're still discussing the change as this is a behavior change from the previous version, where configuration settings took precedence over environment variables.

In the meantime, you can use the ability to register your own configuration factory (here https://github.com/Azure/azure-webjobs-sdk/blob/99c06adbd208ce531e1327118f59c71e6408cce7/src/Microsoft.Azure.WebJobs.Host/ConfigurationUtility.cs#L31-L34) as a workaround since you'd have full control over the configuration provider order.

**Comment by fabiocav** [comment]
We did merge it in. It does introduce a behavior change from previous versions but we agree that consistent with the rest of the ecosystem (including the Functions CLI) is worth the change.

**Comment by nelsonmorais** [comment]
@fabiocav Thanks!
