### ISSUE TITLE
DefaultType not matching when using JavaScript with OpenType

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#1415]
This scenario came up with the CosmosDB output binding, but it may affect others. The `AsyncCollecto`r is registered as supporting `OpenType`: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/Config/CosmosDBConfiguration.cs#L68

In v2 we had our `DefaultType` support as `JObject`/`JArray`, which was the fallback when using JavaScript -- https://github.com/Azure/azure-webjobs-sdk-script/blob/v1.x/src/WebJobs.Script/Binding/DocumentDBScriptBindingProvider.cs#L84-L98.

In the new world without our own ScriptBindingProvider, this DefaultType when using a JavaScript output binding now comes back as `object`, which doesn't seem to hit the collector.

We did this to work around it: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/324

What's the expected behavior here?

**Comment by brettsam** [comment]
@fabiocav FYI

**Comment by fabiocav** [comment]
Thank you, @brettsam !

**Comment by MikeStall** [comment]
Execpation is that we still return IAsyncCollector<JObject>. Need to fix AsyncCollectorBindingProvider.GetDefaultType to be smarter here.

**Comment by MikeStall** [comment]
I've made the fix as a commit in the Converter PR I have out: https://github.com/Azure/azure-webjobs-sdk/pull/1413/commits/7c059b07c1bb65db58f384e43d106d9d9a1e9757
