### ISSUE TITLE
No documentation for using [singleton] in node? 

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-webjobs-sdk#1429]
How to we indicate singleton functions in node?

**Comment by MikeStall** [comment]
[Singleton] is not supported yet in Node.  Can you file a feature request in this repro: https://github.com/Azure/azure-webjobs-sdk-script 

Basically, we'd need some update to function.json and have that generate a [Singleton]  attribute underneath.

**Comment by paulbatum** [comment]
Tracked by https://github.com/Azure/azure-webjobs-sdk-script/issues/912
