### ISSUE TITLE
HTTP 401 Response for GitHub Webhook on runtime 2.0.11370.0 (beta)

### ISSUE THREAD

**Issue by jerriep** [Azure/azure-webjobs-sdk#1433]
I have an existing C# GitHub webhook which I ported over to a .NET Standard 2.0 project (using VS 15.5 Preview 4), running on Azure functions runtime version 2.0.11370.0 (beta).

When the webhook gets called from GitHub, the function keeps returning an HTTP 401 response to GitHub.

The problem is that the actual function never seems to get invoked as there is no logs for function invocations being generated.

So it appears that whatever Azure function infrastructure sits infront of my actual function, is for some or other reason rejecting the webhook from GitHub.

I double checked my Github configuration (webhook URL and webhook secret), and everything is correct.

Any ideas why this is not working? Or how I can find some sort of logs to try and track this down?

EDIT: I also did a test, and took an existing .NET 4.6 app which works 100% with GitHub webhooks, and changed the functions runtime from 1.x to 2.x, then I get the same error. As soon as I switch the runtime back from 2.x to 1.x, then all works fine again

**Comment by paulbatum** [comment]
Webhooks are not supported yet in functions v2:
https://github.com/Azure/azure-webjobs-sdk-script/issues/1698

Basically we are working with the ASP.NET team on getting a .NET standard 2.0 version of the webhooks library that we can use in functions.

Closing as a dupe.
