### ISSUE TITLE
.Netstandard 2.0 support in Microsoft.Azure.WebJobs.ServiceBus

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-webjobs-sdk#1436]
As of now, we can create Azure Functions as .netstandard 2.0 class libraries by referencing `Microsoft.NET.Sdk.Functions v.1.0.6`. This package itself depends on `Microsoft.Azure.WebJobs v.3.0.0-beta3`. In my case, I use service bus queue as a trigger for the function and there is the corresponding attribute `ServiceBusTrigger` in `Microsoft.Azure.WebJobs.ServiceBus` package. But the latest version of this package seems to support only `net 4.6` and have a dependency on `Microsoft.Azure.WebJobs v. 2.1.0-beta4`. Are there any plans on porting this package to `.netstandard2.0`?

**Comment by paulbatum** [comment]
We published a 3.0.0-beta4 version of the Service Bus package to NuGet just a few days ago:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus/3.0.0-beta4

**Comment by Badabum** [comment]
Cool!Thanks guys!
