### ISSUE TITLE
Use of AsyncLocal<T> to store context when running functions in parallel

### ISSUE THREAD

**Issue by j055** [Azure/azure-webjobs-sdk#1441]
Can we use `System.Threading.AsyncLocal<T>` to store context for webjob functions running in parallel? I.e. we want to protect and isolate the data in each method call from others executing on different threads at the same time.

I have tested the following code by populating a queue with a 100 unique messages at a time. The results appear to provide the desired results. The `InvocationId` is correctly matched to the message in the log.

```
        private static readonly AsyncLocal<string> AsyncLocal = new AsyncLocal<string>();

        public static async Task ProcessQueueMessageAsync([QueueTrigger("queue")] string message, TextWriter log,
            Microsoft.Azure.WebJobs.ExecutionContext context)
        {
            await log.WriteLineAsync($"{DateTime.Now:o} {message} {context.InvocationId}");
            AsyncLocal.Value = message;

            Thread.Sleep(100);

            message = AsyncLocal.Value;
            await log.WriteLineAsync($"{DateTime.Now:o} {message} {context.InvocationId}");
        }
```

Can you confirm this is safe to use and if so provide official support in the SDK? I'm using Microsoft.Azure.WebJobs 2.0.0.

**Comment by paulbatum** [comment]
We're not aware of any issues with using AsyncLocal but i don't think its really had any test coverage. My suggestion is that you try it and file any issues you find. Closing this one.
