### ISSUE TITLE
.NET Standard 2.0: Could not load file or assembly (ADAL)

### ISSUE THREAD

**Issue by onovotny** [Azure/azure-webjobs-sdk#1455]
Trying to use a .NET Standard function with the 2.0 host, I'm getting an error. It's the 1.0.6 SDK with version 2.0.11353.0 of the host.

I've checked the output directory and Microsoft.IdentityModel.Clients.ActiveDirectory is there (and the correct version).

This appears specifically related to ADAL. If I use any ADAL types (`AuthenticationResult`) it fails.

Any ideas?
```
[12/8/2017 7:12:32 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'RefreshDB.Run'. System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.17.2.31801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.17.2.31801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

**Comment by onovotny** [comment]
It looks like it's having issues here:
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Indexers/DefaultTypeLocator.cs#L120

Does the Host need a custom AsssemblyLoadContext? It seems like you need something like:
https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/MSBuildExtensionTask/ContextAwareTask.cs#L13

To load the dll's from the "right" directory. Either that or something might be missing (like a runtime deps file)?

**Comment by paulbatum** [comment]
I think you're hitting https://github.com/Azure/azure-webjobs-sdk-script/issues/2146. As far as I understand ADAL does some reflection to load the correct platform specific assembly and this reflection fails due to a lack of binding redirects in functions.

Closing this issue as a dupe. Please comment if you think there's something I'm missing.

**Comment by onovotny** [comment]
I thought the latest versions got rid of that reflection load. The platform dll is a type forwarder. @kanishk?

**Comment by onovotny** [comment]
Also netcore doesn't need binding Redirects, only desktop.net does.

**Comment by fabiocav** [comment]
We have a function load context in the runtime, but most of the issues we've see in the past were related to the way the platform assembly was being loaded. I have the issue @paulbatum linked to assigned to me and will be taking a look at that.
