### ISSUE TITLE
Where does ILogger in filter go?

### ISSUE THREAD

**Issue by adrianm64** [Azure/azure-webjobs-sdk#1456]
I'm doing some tests with IFunctionInvocationFilter.

The context passed to the OnExecut(ed|ing) functions contain an ILogger. Can I view the log output from this somewhere?

Is it possible to access the called function's ILogger? I can find it in the function argument list but only if the function actually has an ILogger argument.

**Comment by paulbatum** [comment]
So log entries written to the ILogger in OnExecut(ed|ing) should appear in host logs, app insights, etc. Its just likely that you don't see them in the function specific logs (e.g. what appears on the monitor tab today). 

For your second question, I think you're correct that this is only possible if the function takes an ILogger and you have to manually go find it in the argument list.

Are you using App Insights? You might find if you enable it, everything is captured and you don't really need to use the function specific logger.

**Comment by adrianm64** [comment]
Ok, that clears it up. Thank you. 

Application insights will work fine for the production monitoring.  In this case the intention is to use it for centralised validation of settings and hooking up our logging framework. Validation errors happen mostly during development and testing and it feels more natural to see them directly in the function log. 

Using the ILogger argument works fine. Only troublesome validation is ”function is missing ILogger argument” 😄 but that will be obvious anyway. 

Thanks again for your reply.

**Comment by paulbatum** [comment]
Great, closing this as I dont think any product work is necessary here.
