### ISSUE TITLE
Fix Queue & table output bindings (v1 and v2)

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#1467]
In reference to his MSDN post: https://social.msdn.microsoft.com/Forums/azure/en-US/88b3c06a-2383-4ff0-861a-e9e507ad88f1/troubleshooting-bottleneck-in-simple-azure-function?forum=AzureFunctions&prof=required

This highlighted an issue we have with the Queue output binding (and possibly others): running high throughput (like via an HttpTrigger) that simply adds a message to a queue behaves *MUCH* worse than if you use a static StorageClient. 

Some rough examples --
- Using a static StorageClient with 500 RPS would slow down the requests to about 2.5 sec each, but they'd eventually complete.
- Using a queue output binding the requests would completely timeout. And from the Function perspective, they would never actually complete (I was killing the process manually). 

It seems like something may be getting queued-up, perhaps via our Task usage or somewhere else. It's not obvious as I looked through the code briefly.

**Comment by mpseidel** [comment]
Good to see you are investigating this. Happy to help if you have any more questions about my scneario where this became appearent.

**Comment by mhoeger** [comment]
Details on the issue in PR, opened a new issue for the root cause: #1632

**Comment by mhoeger** [comment]
Closing as #1632 tracks this issue
