### ISSUE TITLE
How to release injected dependency ?

### ISSUE THREAD

**Issue by guilmori** [Azure/azure-webjobs-sdk#1479]
I use the IJobActivator to implement dependency injection into WebJobs.
But this interface has no Release method.
Where can I hook in the SDK so I can properly release dependencies ?
I do not want to pollute my webjobs with the dispose code, I want it to be done automatically within the infrastructure.

**Comment by MikeStall** [comment]
There is not a good way to do this today. But we are providing proper DI support in the SDK:     https://github.com/Azure/azure-webjobs-sdk/issues/1206

**Comment by christopheranderson** [comment]
Closing as dupe
