### ISSUE TITLE
Functions v2 HttpTrigger on SDK v1.0.7 fails using out of the box template

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-webjobs-sdk#1491]
When creating a Functions v2 project with VS 2017.15.5.2 extension v15.0.31201.0

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new Azure Functions project
1. Choose Functions v2 and an HttpTrigger function. Leave Storage Account as `Storage Emulator` and the Access rights as `Functions`
1. Hit F5

At this point, the Functions runtime works and creates a `localhost/` endpoint for your function without issue.

Now update the Functions nuget package from its OOB value of 1.0.6 to [v1.0.7](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.7)

Hit F5 to run the function.

#### Expected behavior

The Functions runtime executes the function and provides a `localhost/` endpoint for it.

#### Actual behavior

Runtime fails out continually with error:
~~~
[1/4/2018 4:45:15 PM] Host configuration file read:
[1/4/2018 4:45:15 PM] {
[1/4/2018 4:45:15 PM] }
[1/4/2018 4:45:15 PM] ScriptHost initialization failed
[1/4/2018 4:45:15 PM] System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Listening on http://localhost:7071/
Hit CTRL-C to exit...
Object reference not set to an instance of an object.
~~~

#### Known workarounds

* `IActionResult` -> `HttpResponseMessage`
* `HttpRequest` -> `HttpRequestMessage` 

Additionally, make the accompanying code changes to the body of the function, the runtime won't fail. eg: code now looks like:
```csharp
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            string name = req.RequestUri.ParseQueryString()["name"];

            string requestBody = await req.Content.ReadAsStringAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? new HttpResponseMessage(System.Net.HttpStatusCode.OK) { Content = new StringContent($"Hello, {name}") }
                : new HttpResponseMessage(System.Net.HttpStatusCode.BadRequest) { Content = new StringContent("Please pass a name on the query string or in the request body") };
        }
    }
}

```
Notice the change in the `using` namespaces as well.

**Comment by kashimiz** [comment]
This is related to Azure/Azure-Functions#625, where the Functions V2 CLI version is bound to the version of the VS Functions extension installed. A v2 HttpTrigger on SDK 1.0.7 works if you force the project to use the latest Functions V2 CLI by doing the following:

1. Install the Azure Functions Core Tools 2.0 [per instructions here.
](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local)
2. In VS, right-click project > Properties > Debug and set the following:

- **Launch:** Executable
- **Executable:** {full path of .NET Core CLI’s dotnet.exe, ex. C:\Program Files\dotnet\dotnet.exe}
- **Application Arguments:** {full path of the Azure Functions CLI assembly you want to run, ex. C:\Users\SomeUser\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\Azure.Functions.Cli.dll} host start
- **Working Directory:** {full path of your project’s build output folder, ..\bin\Debug\netstandard2.0}

**Comment by fabiocav** [comment]
@brandonh-msft, thanks for opening these detailed issues!

Closing this in favor of Azure/Azure-Functions#625, as this will need to be handled in the VS tools.
