### ISSUE TITLE
Functions v2 HttpTrigger fails with Autofac resolution exceptions

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-webjobs-sdk#1492]
Attempting to create a HttpTrigger-based Durable Function with an `OrchestrationClient` input binding will fail when the HTTP endpoint is hit with an Autofac exception.

VS 2017 version: 15.5.2
VS 2017 Extension version: 15.0.31201.0
Microsoft.NET.Sdk.Functions version: 1.0.6

### Repro steps
1. Create a new Azure Function v2 project, with an HttpTrigger-based function
1. Modify the function code as follows:
```csharp
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using System.Net;
using System.Net.Http;

namespace AzureFunctions.Durable
{
    public static class Orchestrator
    {
        [FunctionName("Orchestrator")]
        public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            return req.CreateResponse(HttpStatusCode.OK, @"return value");
        }
    }
}
```
3. Hit F5
4. Send a request to the endpoint

### Expected behavior
The request is fielded and an OK result it sent back

### Actual behavior
The Functions runtime errors out trying to resolve things from Autofac:
~~~
[1/4/2018 6:50:20 PM] Host lock lease acquired by instance ID '000000000000000000000000C0DDBD63'.
[1/4/2018 6:50:22 PM] Job host started
[1/4/2018 6:50:28 PM] Function started (Id=a5660c71-2983-4431-8f54-939bd99b6460)
[1/4/2018 6:50:28 PM] Executing 'Orchestrator' (Reason='This function was programmatically called via the host APIs.', Id=a5660c71-2983-4431-8f54-939bd99b6460)
[1/4/2018 6:50:29 PM] A ScriptHost error has occurred
[1/4/2018 6:50:29 PM] Exception while executing function: Orchestrator. Autofac: The requested service 'System.Net.Http.Formatting.IContentNegotiator' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
~~~

## Workaround
Instead of using `req.CreateResponse`, creating a *new* `HttpResponseMessage` object like `new HttpResponseMessage(HttpStatusCode.OK) { Content = new StringContent(@"return value") };` will alleviate the Autofac resolution errors.. However, it's not known what other impacts this lack of an ability to resolve types will have down the line, and `req.CreateResponse` is the way we create responses from `HttpRequestMessage` objects in Functions v1

**Can't use `IActionResult` types due to #1491**

### Suspicions

I suspect this is a side-effect of the build warning we get currently with Azure Functions v2:
```
AzureFunctions.Durable.csproj : warning NU1701: Package 'Microsoft.AspNet.WebApi.Client 5.2.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

**Comment by brandonh-msft** [comment]
If I update Microsoft.NET.Sdk.Functions to v1.0.7 the situation deteriorates. While trying to create endpoints for detected functions, the Functions runtime errors out with
~~~
[1/4/2018 7:06:42 PM] Job host started
[1/4/2018 7:06:42 PM] The following 1 functions are in error:
[1/4/2018 7:06:42 PM] Orchestrator: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
~~~

**Comment by paulbatum** [comment]
I believe this is fixed, please comment if you have a repro on latest bits.

**Comment by brettsam** [comment]
I've had a report that this is still repro'ing with 2.0.1-beta.28.

@fabiocav -- any ideas? I know our DI changes should remove Autofac, but we should make sure this doesn't repro after that work goes in.

**Comment by fabiocav** [comment]
Will be god to revalidate this after the changes, but the Autofac mention doesn't necessarily means it is a problem with the DI framework, but likely with the dependency registration/creation, which could potentially be a case of type mismatch as well. The warning about the package shouldn't happen with any of the SDK/Extensions/Script bits, so I'm assuming Durable Functions is still using the old package. Will take a closer look at this.

**Comment by Aumnia** [comment]
I get this exception in my Azure v2 Function that has an HTTP trigger if I try and use the provided HttpRequestMessage and CreateResponse for my return. As suggested creating an HttpResponseMessage myself works around the issue.

* Microsoft.NET.Sdk.Functions (1.0.13)
* 'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.7 ...
* 'dotnet.exe' (CoreCLR: clrhost): Loaded ... \AzureFunctionsTools\Releases\2.1.0\cli ...

If you want to know the variations I tried or if I can provide anything else that will help let me know.

**Comment by Zordid** [comment]
I am trying a simple send to EventGrid and get these very strange and annoying errors. How can that be? What does it mean? None of the things you explain here are relevant for me.

I just call EventGridClient's PublishEventsWithHttpMessagesAsync method and get this error!

**Comment by fabiocav** [comment]
@Zordid can you please open a separate issue with the full error details (messages, stack, etc.) so we can investigate? If the information in this issue is not relevant, it would be good to look at your specific error details and a sample of what you're trying to do.

**Comment by fabiocav** [comment]
@shannoncarver what is the loader exception information you're seeing when you run into this problem? With the latest versions, if you run into this, you should have detailed traces indicating what types failed to load.

**Comment by spboyer** [comment]
Replicated using `return req.CreateResponse(HttpStatusCode.OK, result);`

Error:

```console
System.Private.CoreLib: Exception while executing function: UrlInjest. Autofac: The requested service 'System.Net.Http.Formatting.IContentNegotiator' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```

**Comment by fabiocav** [comment]
Thanks. Will take a look at this.

**Comment by dluc** [comment]
having the same issue with Azure Functions v2, as a result cannot use bindings with `HttpRequestMessage`

**Comment by fabiocav** [comment]
Verified this with the latest bits and that does seem to be resolved.

Can you please validate against the latest CLI 2.3.3/Runtime 2.0.11946.0?

**Comment by shannoncarver** [comment]
i still seeing the same issue on Runtime 2.0.11946.0.
Here are the details:
System.Private.CoreLib: Exception while executing function: CreateUsers. Autofac: The requested service 'System.Net.Http.Formatting.IContentNegotiator' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

Autofac.Core.Registration.ComponentNotRegisteredException
  HResult=0x80131500
  Message=The requested service 'System.Net.Http.Formatting.IContentNegotiator' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
  Source=Autofac
  StackTrace:
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.Net.Http.HttpRequestMessageExtensions.CreateResponse[T](HttpRequestMessage request, HttpStatusCode statusCode, T value, IEnumerable`1 formatters)
   at System.Net.Http.HttpRequestMessageExtensions.CreateResponse[T](HttpRequestMessage request, HttpStatusCode statusCode, T value)
   at usermgt.svc.Api.UserManagement.<CreateUsers>d__0.MoveNext() in C:\sandboxes\architecture\arch-svc-usermanagement\usermgt.svc\Api\UserManagement.cs:line 36

**Comment by fabiocav** [comment]
@shannoncarver thank you for verifying.

I had validated with a repro that did not hit the same content negotiation path. Will keep this open and assigned to the current sprint.

**Comment by fabiocav** [comment]
Closing this in favor of https://github.com/Azure/azure-functions-host/issues/2475

Issue has been resolved in the HTTP extension (https://github.com/Azure/azure-webjobs-sdk-extensions/pull/462), this will be pulled into the host and validation will be added.
