### ISSUE TITLE
VS 2017 extension - function.json not regenerated by Build/F5. Must manually do Rebuild or Clean+Build

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-webjobs-sdk#1494]
When using VS 2017 v15.5.2 and Functions Tools extension v15.0.31201.0 it's error prone and annoying when creating/augmenting function bindings in an Azure Function due to the build tasks not correctly regenerating the function.json at build time.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new Functions project and accompanying Azure Function (v1 or v2; both have the problem)
1. Hit F5

The project builds and executes just fine. This was the first execution, so a full build (ie: Rebuild) took place.

1. Now, change the name or bindings of the Function created by step 1 above
1. Hit F5

Depending on what you changed, you'll either get error messages from the Functions runtime (input/outputs mismatch) or the function name will be incorrect.

#### Expected behavior

Changing a Function's properties and hitting F5 should correctly regenerate the function.json for all affected Functions.

#### Actual behavior

Changes to a Function's properties are not reflected in the generated function.json, making execution incorrect or impossible.

#### Known workarounds

Right-clicking the Function project in question and manually choosing `Rebuild` any time you change something that affects function.json gets the user around this issue but is easily forgotten and inhibits productivity.

**Comment by fabiocav** [comment]
This issue was moved to Azure/azure-functions-vs-build-sdk#154
