### ISSUE TITLE
Remove Analyzer projects from WebJobs.sln

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk#1502]
The Analyzer projects are all full framework projects that probably don't belong in the WebJobs.sln. We should consider moving them elsewhere.

FYI @fabiocav @MikeStall

**Comment by MikeStall** [comment]
Devs can locally unload projects from a solution they don't care about. 

1. Is there a problem mixing full framework and core projects in a single solution? Analyzer will eventually be .net core once VS allows it 
2. Analyzer depends directly on WebJobs projects (not via nuget), so they need to be in the same solution.  It also uses internal-visible-to surface area. 
3. We still need some solution that builds everything.

**Comment by paulbatum** [comment]
This is done see https://github.com/Azure/azure-webjobs-sdk/pull/1553
