### ISSUE TITLE
AzureStorageDeploymentValidator.cs fails on .net core 2.0

### ISSUE THREAD

**Issue by ErikApption** [Azure/azure-webjobs-sdk#1505]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem
When running a command line with Azure.WebJobs in netcore20 the following error happens
\bin\Debug\netcoreapp2.0> dotnet AzureDataConsolidator.dll

Unhandled Exception: System.InvalidOperationException: Microsoft.WindowsAzure.Storage is deployed incorrectly. Are you missing a Table Service assembly (Microsoft.Data.Services.Client, Microsoft.Data.OData or Microsoft.Data.Edm) or a related binding redirect? ---> System.TypeLoadException: Could not load type 'Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext' from assembly 'Microsoft.WindowsAzure.Storage, Version=8.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Azure.WebJobs.Host.AzureStorageDeploymentValidator.VerifyTableServiceAssemblyLoad()
   at Microsoft.Azure.WebJobs.Host.AzureStorageDeploymentValidator.Validate()

After analyzing the assemblies, an issue is that in WindowsAzure.Storage 8.7.0, the TableServiceContext is not present anymore. Also this class is deprecated.

**Comment by brettsam** [comment]
@ErikApption -- which version of the WebJobs nugets are you using? It looks like that line is commented out in our NetStandard builds:

https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/AzureStorageDeploymentValidator.cs#L39-L46

**Comment by baywet** [comment]
Running into the same issue with .net 4.6.2, webjob 2.0.0 (or 2.1.0, doesn't matter) and storage v9. It looks like the namespace `Microsoft.WindowsAzure.Storage.Table.DataServices` has been removed in v9

**Comment by abatishchev** [comment]
Does this mean that WebJobs 2.x aren't compatible with Storage 9.0? Nice.

**Comment by zxed** [comment]
Can we update the title - this is not core specific.

**Comment by abatishchev** [comment]
I see few options here:

- WebJobs SDK 2.1 nuspec to require Storage < 9.0
- WebJobs SDK 2.2 nuspec to require Storage >= 9.0 (preferably)
- WebJobs SDK 3.0 nuspec to require Storage >= 9.0

**Comment by abatishchev** [comment]
As of the initial issue, I suppose the appropriate assembly binding redirects are missing as 2.x works perfectly fine with 8.7

**Comment by brettsam** [comment]
@abatishchev: So you have things running now with the binding redirects for 8.7?

@baywet: Unfortunately, if a type or namespace was removed, you'll get errors as we build against 7.2.1. Do you have a need for v9 (I've not reviewed what it adds yet), or were you just trying to move to the newest packages?

**Comment by baywet** [comment]
@brettsam I was only trying to use latest. I believe then the package dependencies should be updated to a range to avoid "accidental breakage". This is even more crucial because it's a runtime failure and not a build failure, so mean time to detection is much higher (and costly).

**Comment by brettsam** [comment]
Thanks @baywet. I've opened #1574 to track that issue since it looks like a separate issue from what was originally intended here. If we can confirm that @abatishchev was able to get 8.7 working with redirects, we'll close this one.

**Comment by baywet** [comment]
@brettsam
 Doing a cleanup of my GitHub issues here. You can most likely close this issue as mentioned in your previous comment
