### ISSUE TITLE
Adding Application Insights to .NET Core Web Job breaks Azure blob client

### ISSUE THREAD

**Issue by erick-thompson** [Azure/azure-webjobs-sdk#1511]
I am attempting to get Application Insights working on my .NET Core 2 Web Job. The Web Job works correctly.

After I add Microsoft.Azure.WebJobs.Logging.ApplicationInsights (3.0.0-beta4) to the project, I get the following error whenever I try to interact with Azure Blob Storage using the .NET client.

> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Everything seems to indicate that this the same issue (AI changing header values to include dependency tracking) as:

- https://github.com/Azure/azure-storage-net/issues/490
- https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/640
- https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/488

The first thread contained a workaround by way of editing/creating the ApplicationInsights.config file, but this does not seem to work for .NET Core Web Jobs (the config is being correctly copied to the output folder).

I'm trying to find code that I can add to correctly configure the telemetry modules, but the ITelemetryClientFactory/DefaultTelemetryClientFactory does not appear to have a way to do this. I can create a custom implementation of ITelemetryClientFactory, but is there a better way?

**Comment by brettsam** [comment]
Do you get this error as soon as you add the package to the project? Or do you do some wire-up as well? If so, can you share that?

We shouldn't be doing any dependency collection by default -- so I'm curious as to where this is coming from.

I'm going to be looking into some of this when I attack this issue (very soon): https://github.com/Azure/azure-webjobs-sdk/issues/1419

**Comment by xt0rted** [comment]
I'm pretty sure I ran into this error when I was migrating mine to .net core 2.0 as well. If this was the same error I don't recall what I did that resolved it since there was a lot changing then. Here's the skeleton of my web job that's been running fine over the last month. Maybe comparing the two could help.

https://gist.github.com/xt0rted/d15bc65617120e00e3e87c8388c8f3a2

**Comment by brettsam** [comment]
I've just moved us up to using App Insights 2.5, which changed a bunch of internal stuff (and added Live Metrics, Sampling, etc, back in now that they're supported). I didn't see these errors during my testing, so I'm going to resolve this issue. But if you hit this with our latest 3.0 bits, please re-open and I can take another look.

To test, try out the latest 3.0 MyGet package from the nightly builds: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds

**Comment by jiimaho** [comment]
Is `Microsoft.Azure.WebJobs.Logging.ApplicationInsights` the same for WebJobs, as `Microsoft.ApplicationInsights.AspNetCore` is for WebAPI's?
