### ISSUE TITLE
Azure Web Jobs roadmap

### ISSUE THREAD

**Issue by sergey-netdev** [Azure/azure-webjobs-sdk#1512]
Is there any? According to [the official Nuget]( https://www.nuget.org/packages/Microsoft.Azure.WebJobs/ ) it's almost a year to 2.1 beta like everything is OK with 2.0 release and no new features needed. Is Microsoft abandoning web jobs in favor of Azure Functions? What are expected from 3.0?

**Comment by mathewc** [comment]
No we are definitely not abandoning WebJobs SDK - it is the foundation of Azure Functions and is very important, and use outside of Azure Functions also remains important to us.

I do agree with you that we have been neglecting regular package releases. I'll take it up with the team internally today and we'll figure out when we can release the 2.1. In the 3.0 release our primary focus is moving to .NET Core and making progress on our extensibility model. Other areas of focus are tracked in our issues for that release.

**Comment by jonsagara** [comment]
Hi @mathewc, any update on this?

**Comment by mathewc** [comment]
Our primary concern was reviewing everything in the 2.1 release up to this point to ensure there are no breaking changes w.r.t semantic versioning because this is a minor release. I reviewed and I think we're good - we should be able to do the release soon.

**Comment by mathewc** [comment]
Release 2.1 of core SDK and Extensions is now up on Nuget.

**Comment by sergey-netdev** [comment]
Thank you for this long awaited release! Can you please also update Microsoft.Azure.WebJobs.ServiceBus package? I can't update my solution to use 2.1:

> Unable to resolve dependencies. 'Microsoft.Azure.WebJobs 2.1.0' is not compatible with 'Microsoft.Azure.WebJobs.ServiceBus 2.0.0 constraint: Microsoft.Azure.WebJobs (= 2.0.0)'.			0
