### ISSUE TITLE
Using INameResolver from exception filter

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/azure-webjobs-sdk#1517]
I'm creating a custom exception filter to catch and log all exceptions happening in WebJobs and Functions:

```csharp
public class MyExceptionFilter : FunctionExceptionFilterAttribute
{
    public MyExceptionFilter(string myParam)
    {
        ...
    }

    public override void OnExceptionAsync(FunctionExceptionContext exceptionContext, CancellationToken cancellationToken)
    {
        ...
    }
}
```

I want to be able to parameterize the filter, in this example my sending in `myParam`. Like with input and output bindings, I would like to be able to tell the filter to take the value from application configuration like this:

```csharp
[MyExceptionFilter("%someKey%")]
``` 

This doesn't work out of the box, since `%someKey%` is simply send to the constructor of my filter. I've looked in the code for the bindings, which are using `INameResolver` to resolve these values to configuration settings. But I cannot seem to find out, if I am able to inject or resolve `INameResolver` from within my filter.

Is this possible or planned?

**Comment by brettsam** [comment]
I'm pretty sure this isn't supported today as it looks like we just pull the custom attribute straight from the class with doing any resolution first.

@mathewc -- Is this something we can add?

**Comment by mathewc** [comment]
Right - not supported today. We're not in the construction pipeline for these attribute at all.

You can do the resolution yourself currently I presume, by resolving the expression yourself in your ctor, e.g.:

```csharp
var resolver = new DefaultNameResolver();
var resolved = resolver.ResolveInWholeString(myParam);
```

We might also consider adding a resolver as a context param for use at invocation time.

**Comment by ThomasArdal** [comment]
@mathewc Wow. That's so simple that I didn't though about that :) "Just works" would be nice.

Would you create the `DefaultNameResolver` in the constructor of the filter, or on every call to `OnExceptionAsync`?

**Comment by mathewc** [comment]
You only need to resolve this value once since its coming from app settings right? So ctor would make sense.

**Comment by ThomasArdal** [comment]
Would make sense. But I think there's a problem when doing so. When adding resolve to the constructor, I get the following build error:

```
System.InvalidOperationException: '%myKey%' does not resolve to a value.
   at Microsoft.Azure.WebJobs.Host.NameResolverExtensions.ResolveWholeStringCore(INameResolver resolver, String resolve, Boolean throwOnFailure)
```

When adding the resolver to the `OnExceptionAsync`-method, the setting is correctly resolved.

**Comment by ThomasArdal** [comment]
@mathewc I believe this issue can be closed. You answered my question about how to resolve variables and it works. It doesn't work in v2 though, but I've created [another](https://github.com/Azure/azure-webjobs-sdk/issues/2118) question for that.
