### ISSUE TITLE
All not finished functions go back to "Running" on dashboard

### ISSUE THREAD

**Issue by victorhurdugaci** [Azure/azure-webjobs-sdk#152]
``` C#
public static void QueueFuncX([QueueTrigger("myqueue")] SuperT message, TextWriter log)
{
    Thread.Sleep(10 * 60 * 1000);
    log.WriteLine(message.Name);
}
```

Run this function a few times and stop the host while it is running.
Go on dashboard and wait for the instance to show as "Never finished".
Run again the function.

Result: all the instances go back to "Running"
Expected: only the current instance is showing as Running

@davidmatson

**Comment by isaleem** [comment]
I am facing this same issue, with version 1.1.2, any thoughts on this please.
