### ISSUE TITLE
AzureFunc: Blob Trigger not firing

### ISSUE THREAD

**Issue by ethanturk** [Azure/azure-webjobs-sdk#1521]
I have an AzureFunc that is set up to trigger off of a Blob container in a Storage Account. Whenever a Json BLOB is dropped into the container via DataFactory, the Blob trigger is not firing. This has occurred for 2 days in a row.

#### Known workarounds

Whenever I enumerate the Blob container using Azure Storage Explorer, the Blob trigger is immediately fired.

#### Related information 

Azure Functions v1 - C#, Precompiled, Consumption billed
Data Factory v1
General Purpose V1 Storage Account, Blob Container with Diagnostic Logging Enabled

**Comment by brettsam** [comment]
Looking at the container in Storage Explorer causes the trigger to fire? I don't know anything about Data Factory, but I wonder if it does something special when it uploads these blobs.

Internally, we use `container.ListBlobsAsync(prefix: null, useFlatBlobListing: true, cancellationToken: cancellationToken)` to see if there are any blobs that we need to process. Can you get your storage container and function into the state and try to run that command from a separate C# app? Does it return the new blobs?

We also look at the LastModified value of the blobs to see if they're new. I'm wondering if something unique is going on with Data Factory.

**Comment by ethanturk** [comment]
Thanks for the response, Brett. It isn't easy for me to purposefully get it into the invalid state but it will happen reliably overnight. It seems to have something to do with the spin-down or maybe some overnight reset that occurs. 

I will test the C# method on Monday morning and report back. As a side note, I wrote a Timer trigger to run and use that same method to help the Blob triggers along and it seems to be working.

Thanks.

**Comment by brettsam** [comment]
That's really interesting. What does your Timer trigger do, exactly? How often does it run?

**Comment by ethanturk** [comment]
Sorry for the delay. We had to go a different route on this one due to the inconsistency and are no longer using the Blob Storage Trigger. I'm going to go ahead and close this. Thanks for your help.

**Comment by bonggoy** [comment]
I am in the same situation and has been happening consistently now i.e. files dropped in the blob container are not being processed.

**Comment by RajamohanShilpa** [comment]
HI,
My azure function not trigger after upload my file to corresponding storage account container, but this is working fine when I test my local with following settings.

I had to use local.setting.json like below
```
"Values": {
....
"AzureWebJobsStorage" : "UseDevelopmentStorage=true",
"AzureStorageMyUpload" : "<<My storage account access key, which is get copy from my container>>"
.....
}
```
