### ISSUE TITLE
AzureWebJobsServiceBus is missing or empty

### ISSUE THREAD

**Issue by rick1c** [Azure/azure-webjobs-sdk#1531]
When deploying webjob to Azure having removed AzureWebJobsServiceBus connection string from app.config.

I expected this connection string to be picked up from Application Settings for App Service. Works for 
AzureWebJobsDashboard and AzureWebJobsStorage.

![image](https://user-images.githubusercontent.com/1764969/35286323-9d56caf0-0057-11e8-91ca-764d11fd5108.png)

Getting 'AzureWebJobsServiceBus is missing or empty' error message.

Is this not supported?

**Comment by mathewc** [comment]
Hmmm, that should work. Can you try changing the Type to "Custom" and let us know if that works? While this should work, if you need to get unblocked while we sort it out, if you move the connection string from the "Connection Strings" section to "Application Settings" using the same name it should definitely work.

**Comment by rick1c** [comment]
Hi
Many thanks for your help
Changing type to Custom worked.  In the meantime, I had deleted the whole appservice and recreated it.
When I came to re-add the connection strings, SQLAzure is no longer there.
I now have them all set to Custom and it is now working.

**Comment by mathewc** [comment]
Good to hear you're unblocked. I'll track down why the other Types aren't working - clearly something is broken.

**Comment by mathewc** [comment]
https://github.com/Azure/azure-functions-ux/issues/2248 is now tracking the UI issue.
