### ISSUE TITLE
Will this ever come out of Beta?

### ISSUE THREAD

**Issue by smurfster** [Azure/azure-webjobs-sdk#1534]
I was wondering if this package will ever come out of Beta as my place of work deems this as a high risk for live environments?

**Comment by mathewc** [comment]
Duplicate of https://github.com/Azure/azure-webjobs-sdk/issues/1512. See discussion there.

**Comment by mathewc** [comment]
Release 2.1 of core SDK and Extensions is now up on Nuget.
