### ISSUE TITLE
Function V2 fails with 502 Bad Gateway after 2 minutes

### ISSUE THREAD

**Issue by Szer** [Azure/azure-webjobs-sdk#1536]
#### Repro steps

Create FunctionApp:
Consumption Plan,
WIndows host,
Central US,
Runtime V2

Create C# HttpTrigger function, make it `async`
Add `await Task.Delay(200000);` somewhere. More than 3 minutes delay
Run it

#### Expected behavior

After ~200 sec it will respond with 200 OK and some message

#### Actual behavior

Fails after ~120 sec with 502 Bad Gateway:

| Header| Value
|--|---|
|Content-Length | 89
|Content-Type | text/html
|Server | Microsoft-IIS/10.0
|X-Powered-By | ASP.NET
|Date | Thu, 25 Jan 2018 15:39:37 GMT

`The specified CGI application encountered an error and the server terminated the process.`

BUT logstream show success run:
`2018-01-25T15:41:09.308 Function completed (Success, Id=73809f6f-0c4d-4f45-800d-f5dc3fd97495, Duration=200311ms)`
Monitor tool also shows a success run.

#### Known workarounds

None.

Probably some proxy between client and function has 2 min timeout and cut out any connections.

**Comment by brettsam** [comment]
Another similar issue was created recently here: https://github.com/Azure/azure-webjobs-sdk-script/issues/2338. 

In short:

> For HTTP Functions, they must complete within ~2 minutes or our gateway will timeout. It's recommended you follow async patterns with HTTP and return a location where they can ping the status of that request.
