### ISSUE TITLE
Can WebJob instances in 2 deployment slots share the same storage account for dashboard usage?

### ISSUE THREAD

**Issue by tmenier** [Azure/azure-webjobs-sdk#1538]
I can log more details once I confirm whether this should be considered a bug or just something that's not supported.

I have an Azure web app with 2 deployment slots. (I deploy to each slot directly and do not currently use the slot swap feature; they're more less just set up this way for organizational purposes.) Each has its own instance of a WebJob, and the names are unique. (Let's call them "wj-prod" and "wj-staging".) The app settings `AzureWebJobsStorage` and `AzureWebJobsDashboard` are the same for both, i.e. they use the same Azure storage account.

On multiple occasions while using the dashboard to run the staging WebJob, we've inadvertently triggered the prod version, and vice-versa. There are multiple ways to drill down to a function and trigger it, and I believe there's a glitch in that sometimes you get a list specific to that slot/instance (which I'd expect), and sometimes you get a list of both. This is where I could certainly investigate further and provide more details if needed (please let me know), but I suspect this may already be a known issue, or perhaps using the same storage accounts for multiple slots/WebJobs simply isn't supported.

Thanks.

**Comment by brettsam** [comment]
If you have some specific scenarios, that would help. Including the WebJobs version you're using. @MikeStall -- the dashboard should be able to handle this, right?

**Comment by tmenier** [comment]
Sorry for the delay in getting you details. I do believe there are some bugs here, and I've created a new issue for them: #1541
