### ISSUE TITLE
Stable 2.1.0 release of the Application Insights logger

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-webjobs-sdk#1542]
Now that there's a stable 2.1.0 release of [Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.1.0) will the application insights logger be receiving a stable 2.1.0 release as well? The current version on nuget is [2.1.0-beta4](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/2.1.0-beta4).

**Comment by fabiocav** [comment]
Looks like the package was missed. @mathewc, want to publish 2.1.0? If you're unable to, just reassign this to me and I can publish them.

**Comment by takekazuomi** [comment]
I have the same problem. What is the release schedule?

**Comment by mathewc** [comment]
Sorry we missed that - I just pushed it.

**Comment by kamilzzz** [comment]
@mathewc what about Microsoft.Azure.WebJobs.Logging? It's still 2.1.0-beta4.

**Comment by mathewc** [comment]
Pushed that as well just now.
