### ISSUE TITLE
Multiple WebJobs under 1 web app monitoring

### ISSUE THREAD

**Issue by AndrewPeterPowell** [Azure/azure-webjobs-sdk#1543]
Unable to split insights for different webjobs under one web app

Is it possible to see the different webjobs under a single application insights, e.g. running 2 web jobs. Currently it displays memory and processor for the whole server (web app) not the actual web jobs, is it possible to get the web job specific telemetry?

Thanks in advance

Andrew

**Comment by paulbatum** [comment]
Some of the data you see in app insights will be per webjob. For example, if you look in the requests table, or the traces table you will see per execution, per webjob data. 

However for the machine stats - memory, processor, etc, you'll get those per VM you're running on. So if your webjobs are configured to run on an App Service Plan with two VMs, you'll see data broken up for each of those VMs. There is no such thing as 'per webjob memory data'.

Closing this as answered, I can reactivate if you have any outstanding questions here.

**Comment by smurfster** [comment]
So there is no way to distinguish which part of the app service is consuming all the cpu/memory?

e.g. If I have a AppService consisting of a WebApi project and 5 Webjobs. I cannot distinguish which of these is using all the memory/cpu?

**Comment by paulbatum** [comment]
As far as I know this is not possible through the data that is collected today by App Insights. The only workaround I can think of would be to temporarily move each of the jobs/apps onto a separate app service plan to get this data.

**Comment by smurfster** [comment]
Do you know if I can can make a request somewhere for this feature to be added?

**Comment by paulbatum** [comment]
@smurfster I'm not sure if its even a feasible feature to implement - it would depend on how your webjobs execute. Specifically whether they each run in their own process or not. If you go to `https://<yoursite>.scm.azurewebsites.net/ProcessExplorer/` when you have all your webjobs running and you see several child processes (cmd.exe, node.exe, java.exe, etc - depends on what language your jobs are written in) then in theory App Insights could report the cpu and memory for each of those processes. But if all your jobs run within the same process then this data is impossible to collect.

If your jobs are mostly running as separate processes, then perhaps enabling the App Insights profiler would collect per process data. You could try that:
https://functiondevpbtest.scm.azurewebsites.net/ProcessExplorer/
