### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.1.0.0 ...

### ISSUE THREAD

**Issue by lpunderscore** [Azure/azure-webjobs-sdk#1557]
Functions project created using visual studio with a CosmosDb binding does not build.

#### Repro steps

Create a new functions project targeting version 2.0 (netstandard 2.0)
 (Microsoft.NET.Sdk.Functions (1.0.7)
Add an a new function (select any of the triggers)
Add Microsoft.Azure.Webjobs.Extensions.CosmosDB (3.0.0-beta6) nuget

Add attribute 
 [CosmosDB(ConnectionStringSetting = "DatabaseConnectionString")] IDocumentClient documentClient

// so far this builds

add a call to 
 await documentClient.CreateDocumentAsync(collectionUri, newdoc);

#### Expected behavior

project builds and we can use the documentclient to perform operations

#### Actual behavior

Project does not build. removing the call to createdocumentasync will let the project build. We can also see that the documentclient is provided to the function.

#### Known workarounds

comment out the line: await documentClient.CreateDocumentAsync(collectionUri, newdoc); and the project will build. No way to use the client provided though.

Actuall build exception:

1>C:\Users\JJFUE\.nuget\packages\microsoft.net.sdk.functions\1.0.7\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(32,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Also, creating my own documentclient ends up with the same build error.

**Comment by paulbatum** [comment]
@lpunderscore I can't reproduce. Maybe there is something different about your environment? Here's what mine looks like:

Win 10
VS 15.5.6
.NET Framework 4.7.02556
Azure Functions and Web Jobs Tools 15.0.40108.0

I pushed my attempted repro here:
https://github.com/paulbatum/webjobs-issue-1557

If you clone that do you still get the same error? If yes then I think it has to be environmental...

**Comment by lpunderscore** [comment]
@paulbatum Thanks for taking the time to try to repro.

I have the same issue when cloning your project.

The only difference I can see is .net framework version. I have 4.6, installing 4.7 now and will update on my results.

thanks!

**Comment by lpunderscore** [comment]
Installing .net framework 4.7 fixed the issue for me.

Thanks a lot @paulbatum I don't think I would have found this any time soon...

**Comment by paulbatum** [comment]
@lpunderscore It runs on .NET core 2.0. You'll see this if you look in process explorer after hitting F5 in VS to run the function - you'll see its running under 'dotnet.exe'. 

As to why installing .NET Framework 4.7 matters, I think its because a functions 2.0 project targets .NET Standard 2.0, and the .NET framework updates still have impact on how such projects are built. Maybe @fabiocav can explain better, I don't understand this stuff super well myself.

**Comment by fabiocav** [comment]
The issue you ran into is caused by our SDK tooling, which, when running from a VS build (as opposed to using the dotnet CLI), initiates a process that runs on full framework. The runtime itself runs on .NET Core.
