### ISSUE TITLE
System.InvalidOperationException: 'Microsoft.WindowsAzure.Storage is deployed incorrectly

### ISSUE THREAD

**Issue by mguntli** [Azure/azure-webjobs-sdk#1565]
Please provide a succinct description of the issue.

#### Repro steps

1. VS2017 with latest updates (as of 9th of February 2018)

2. File -> New -> Project -> Visual C# -> Cloud -> Azure WebJob (.NET Framework)

3. Manage NuGet Packages -> Update 10 outdated packages

4. After previous update of 10 packages, update another 8 outdated packages

5. Add reference to Microsoft.Azure.WebJobs.ServiceBus

6. You get it, after adding the ServiceBus reference update 2 more outdated packages

7. Follow the documentation to create the simple EventProcessor
https://github.com/Azure/azure-webjobs-sdk/wiki/EventHub-support#configuration

#### Expected behavior

The application should start, since it's a tutorial.

#### Actual behavior

System.InvalidOperationException
  HResult=0x80131509
  Message=Microsoft.WindowsAzure.Storage is deployed incorrectly. Are you missing a Table Service assembly (Microsoft.Data.Services.Client, Microsoft.Data.OData or Microsoft.Data.Edm) or a related binding redirect?
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
   at Microsoft.Azure.WebJobs.Host.AzureStorageDeploymentValidator.Validate()
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config)
   at Microsoft.Azure.WebJobs.JobHost.InitializeServices()
   at Microsoft.Azure.WebJobs.JobHost.<InitializeHostAsync>d__44.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__25.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.Start()
   at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
   at bernina_eventprocessor.Program.Main() in C:\WorkGIT\imtmedical\Bernina\BerninaCloud\Applications\bernina-eventprocessor\bernina-eventprocessor\Program.cs:line 25

Inner Exception 1:
TypeLoadException: Could not load type 'Microsoft.WindowsAzure.Storage.Table.DataServices.TableServiceContext' from assembly 'Microsoft.WindowsAzure.Storage, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

#### Known workarounds

Don't use Webjobs SDK and use the EventBus SDK.
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-receive-eph

#### Related information 
```
    class Program {
        // Please set the following connection strings in app.config for this WebJob to run:
        // AzureWebJobsDashboard and AzureWebJobsStorage
        static void Main() {
            var config = new JobHostConfiguration();

            if (config.IsDevelopment) {
                config.UseDevelopmentSettings();
            }

            var eventHubConfig = new EventHubConfiguration();
            // Event Hub-compatible name of IoT Hub
            string eventHubName = "xyz-iothub";
            // Event Hub-compatible endpoint of IoT Hub
            string eventHubConnectionString = "Endpoint=sb://iothub-xyz.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=xyz";
            eventHubConfig.AddReceiver(eventHubName, eventHubConnectionString);

            config.UseEventHub(eventHubConfig);
            JobHost host = new JobHost(config);

            // The following code ensures that the WebJob will be running continuously
            host.RunAndBlock();
        }
    }
```

**Comment by jeffmikan** [comment]
Alternative Work around is to roll back WindowsAzure.Storage to version 8.7

**Comment by mguntli** [comment]
**After rollback to Azure.Storage Version 8.7**, I attempted to rollback NetStandard.Library to 2.0.0 due to the following exception at startup:
```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

However, a rollback to NetStandard.Library to 2.0.0.0 results in the following build error:
_error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\NETStandard.Library.2.0.1\build\netstandard2.0\NETStandard.Library.targets._

**Comment by jeffmikan** [comment]
Sorry, I wasn't clear in my response.  The rollback to 8.7 fixed my issue with MY program.  I didn't test it with your test configuration.  I just wanted to leave it for other developers as an option since this was the only post coming up on the issue.

**Comment by CYBERRRR** [comment]
Yeah I also hit that today while creating a new webjob. Downgrading to the version the other webjobs I have are running (8.6.0) fixes it.

**Comment by brettsam** [comment]
WebJobs has an issue when running against the Storage V9 package. This is being tracked here #1574. There's currently a PR out here #1575.

Closing this as a duplicate.
