### ISSUE TITLE
Functions v2: Can't bind Table to type System.Linq.IQueryable

### ISSUE THREAD

**Issue by Quass1m** [Azure/azure-webjobs-sdk#1566]
While executing Azure Functions v2 under .NET Core the Azure Storage Table IQueryable binding throws an exception.

#### Repro steps

1. Create new Azure Function v2 project (tested using VS 2017 with all updated up to 10.02.2018 and Functions SDK versions 1.0.6/1.0.7).
2. Create Azure Function using any trigger and "[Table("myTable")]IQueryable<TableEntity> readTable" input binding
3. Run function

#### Expected behavior

Function is indexed and optionally starts depending on trigger type.

#### Actual behavior

An exception is thrown:
> A ScriptHost error has occured
> Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1.Run'. Microsoft.Azure.WebJobs.Host: Can't bind Table to type System.Linq.IQueryable
> Error indexing method

#### Known workarounds

Switch to Azure Functions v2

#### Related information 

Source:
https://github.com/Quass1m/FunctionApps---Can-t-bind-Table-to-type-System.Linq.IQueryable
Function1 - Azure Functions v2 - throws exception
Function2 - Azure Functions v1 - no error

**Comment by pragnagopa** [comment]
This is by design. Functions V2 does not support this scenario. See [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table#input---usage)
