### ISSUE TITLE
FunctionNameAttribute vs webjob-publish-settings.json webJobName

### ISSUE THREAD

**Issue by ggirard07** [Azure/azure-webjobs-sdk#1580]
I don't understand how the new `FunctionName` attribute is being used.

Currently when deploying a new webjob from Visual Studio the wizard still prompt for the webjob name in order to create the appropriate `webjob-publish-settings.json` file locally prior to proceed with deployment. The default name available in that wizard does not honor the `FunctionName` attribute.

- Is the VS tooling still pending an update to support it properly?
- If yes, what will be the behavior on build/deployment if FunctionNameAttribute does not match webjob-publish-settings.json? Does one take precedence on the other?

#### Repro steps

1. Create a new webjob project in C#

2. Add the FunctionName attribute to the default function

3. Right click the project then select "Publish as Azure Webjob..."

4. Follow publication wizard

#### Expected behavior

Webjob name should not be configurable from the wizard as it is driven by `FunctionName` attribute or at least its default value should match the attribute value.

#### Actual behavior

Webjob name in the wizard match the project name.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Microsoft Visual Studio Professional 2017 
Version 15.5.6
```
  <package id="Microsoft.Azure.WebJobs" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.Azure.WebJobs.Core" version="2.1.0" targetFramework="net461" />
...
  <package id="Microsoft.Web.WebJobs.Publish" version="1.1.0" targetFramework="net461" />
```

**Comment by paulbatum** [comment]
There is no plan for the webjobs VS tooling to honor the FunctionName attribute.
