### ISSUE TITLE
Documentation suggestions - Getting Started

### ISSUE THREAD

**Issue by tmenier** [Azure/azure-webjobs-sdk#1596]
I appreciate the amount of work that was put into the main [readme](https://github.com/Azure/azure-webjobs-sdk/blob/dev/README.md) and the [docs wiki](https://github.com/Azure/azure-webjobs-sdk/wiki) it links to, but for someone new to this, it's surprisingly difficult to figure out how to get started. A couple of the most basic questions that anyone getting started would need to know:

1. Where do I get it? ([Here](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/), I think.)

2. What platforms are supported? I know that's not necessarily a simple question, and just because the core SDK supports a given platform doesn't mean the VS tooling, Kudu dashboard, etc. are necessarily there, but just a brief summary of the current state of things would be immensely helpful.

Bonus:

3. Version 3.x has been in beta for quite some time. In a nutshell, what's this release all about? I _think_ I've concluded (via reading through some of the open issues) that .NET Standard 2.x targeting is the biggest new feature coming and most compelling reason to upgrade (perhaps early), but I'm not certain. (The [release notes](https://github.com/Azure/azure-webjobs-sdk/releases) weren't particularly helpful in answering this either.)

**Comment by mathewc** [comment]
The doc pages you linked to are what we have at the moment. We're working on improvements that we'll be releasing soon, promoting these to proper Microsoft documentation. Did you also see https://github.com/Azure/azure-webjobs-sdk/wiki/Resources which is linked to above?
