### ISSUE TITLE
"Found conflicts between different versions of the same dependent assembly" despite AutoGenerateBindingRedirects ON

### ISSUE THREAD

**Issue by ggirard07** [Azure/azure-webjobs-sdk#1598]
I recently migrated my solution to .Net Core with .netstandard 2.0. The only project still using .Net Framework 4.6.1 is my webjob (a console app project) because the NuGet package for the WebJobs SDK supporting .Net Standard is still in preview (3.0-beta4).

My solution is working properly but I can' t get ride of this last warning:
> 2>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.

In order to get the NuGet package management right when mixing a class library in .Net Standard with an executable still in full framework, I had to update the console app project to use `PackageReference` instead of `packages.config`, as explained [here](https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx). I uninstalled every packages in the packages.config prior to switch to `PackageReference` and then reinstalled only the required packages. For the `Microsoft.Web.WebJobs.Publish` package, I used the workaround detailed in https://github.com/Azure/azure-webjobs-sdk/issues/1109 as `PackageReference` does not support PowerShell installation.

I found the following [announcement](https://github.com/dotnet/standard/issues/481) describing a similar pattern generating this kind of warning. But it does not cover my warning as the console application is an executable and is already using `AutoGenerateBindingRedirects`.

#### Repro steps

1. Clone the repository containing the reproduction sample at https://github.com/ggirard07/bindingredirect.

2. Open the solution `BindingRedirectIssue.sln`.

3. Build the solution (Build > Rebuild Solution).

4. Check the build errors and warnings.

#### Expected behavior

No error or warning should be produced.

#### Actual behavior

A warning is reported about assembly version conflicts.

#### Known workarounds

None.

#### Related information 

The issue starts when adding the `Microsoft.Web.WebJobs.Publish` package to the solution.
The warning seems to be related to a conflict about the `Newtonsoft.Json.dll`.
There should be no conflict in the solution as everyone is using `Newtonsoft.Json` in version `9.0.1`.
The only reference to a different version is in the `Microsoft.Web.WebJobs.Publish` which use `6.0.4`. it is used only during the build by the added .targets, there is no impact at runtime. This is also why the `Microsoft.Web.WebJobs.Publish` does not define any dependency to the `Newtonsoft.Json` package.

I am pretty sure this assembly, `$(NuGetPackageRoot)Microsoft.Web.WebJobs.Publish\1.1.0\tools\Newtonsoft.Json.dll` raises the issue because as soon as you remove the `webjob-publish-settings.json` file from the disk or the `webjobs.targets` from the console app csproj, the warning disappear (but you can no longer build the webjob...).

Versions involved:
* Microsoft.Azure.WebJobs 2.1.0
* Microsoft.Web.WebJobs.Publish 1.1.0

**Comment by mathewc** [comment]
We'll try to repro and see if there is a workaround possible or if there is an actual issue needing fixed.

**Comment by ggirard07** [comment]
Updated all my webjobs with `Microsoft.Web.WebJobs.Publish` version `2.0.0` which support `PackageReference` but issue still persist.

**Comment by dsplaisted** [comment]
I took a look at this, and here's what's happening:

- `webjobs.console.targets` from the Microsoft.Web.WebJobs.Publish NuGet package is importing `Microsoft.WebApplication.targets`
- `Microsoft.WebApplication.targets` is typically used by web applications, which:
    - Have an output type of `Library`
    - Use a web.config file, which is where the binding redirects go
    - Don't support automatic binding redirects (because the web.config file from the source directory is used in F5 scenarios, so the build can't update it)
- Because web applications don't support automatic binding redirect generation, `Microsoft.WebApplication.targets` sets `AutoUnifyAssemblyReferences` to false.  This tells the `ResolveAssemblyReference` task to [generate a warning message](https://github.com/Microsoft/msbuild/blob/1e574340ca00a71678d7eb67f3f3e68d981fd994/src/Tasks/AssemblyDependency/ResolveAssemblyReference.cs#L1088) with the suggested redirects, since they won't be automatically applied.
- When `AutoUnifyAssemblyReferences` is false and the `OutputType` is Exe, MSBuild will generate the warning that `AutoGenerateBindingRedirects` should be set, even if it already is.

To fix this, the Microsoft.Web.WebJobs.Publish package should probably save the value of `AutoUnifyAssemblyReferences` before it imports Microsoft.WebApplication.targets, and restore the value afterwards.

MSBuild should also fix the issue where it can generate a warning telling you to set `AutoGenerateBindingRedirects` when it is already set.

To workaround this issue, you can put the following in your .csproj file after all of the .targets imports:

```xml
  <PropertyGroup>
    <AutoUnifyAssemblyReferences>true</AutoUnifyAssemblyReferences>
  </PropertyGroup>
```

**Comment by ggirard07** [comment]
Can this be related in any way? https://devblogs.microsoft.com/visualstudio/using-newtonsoft-json-in-a-visual-studio-extension/

**Comment by ghost** [comment]
What's the status of this? I think I'm facing this same issue with a project migrated from NetCore 2.2.100 to NetCore 3.1.201 and the proposed workaround https://github.com/Azure/azure-webjobs-sdk/issues/1598#issuecomment-468501905 doesn't work for me.

**Comment by StingyJack** [comment]
> F5 scenarios

@dsplaisted - "F5" like the networking device?

Also linking [this](https://github.com/microsoft/msbuild/issues/608) because of similar convo

**Comment by dsplaisted** [comment]
By default, F5 is the shortcut key in Visual Studio to "Start Debugging".  In classic ASP.NET projects, when starting debugging, Visual Studio would not do a full build where it copied the content and web.config to an output directory.  Rather it would use those files from the project directory, so there was no opportunity to inject binding redirects during the build process.

**Comment by nicholastic** [comment]
I'm also seeing this issue in my webjob. Can you get this fixed?

**Comment by dsplaisted** [comment]
@nicholastic Have you tried the workaround [here](https://github.com/Azure/azure-webjobs-sdk/issues/1598#issuecomment-468501905)?

**Comment by nicholastic** [comment]
@dsplaisted Yes, unfortunately workaround https://github.com/Azure/azure-webjobs-sdk/issues/1598#issuecomment-468501905 doesn't work for me.

**Comment by dsplaisted** [comment]
@nicholastic Can you share a [binlog](https://aka.ms/binlog) of the failing build (with the workaround applied)?

**Comment by ChristopherHaws** [comment]
To add on to @dsplaisted's solution, if you are building using `Microsoft.NET.Sdk` where props/target files dont live in your csproj file, I was able to fix the issue by adding the properties in a `BeforeBuild` target:

```xml
<!-- This is in a target because it must run after Microsoft.WebApplication.targets is imported -->
<!-- https://github.com/Azure/azure-webjobs-sdk/issues/1598#issuecomment-468501905 -->
<Target Name="_WebJobAutoUnifyAssemblyReferences" BeforeTargets="ResolveAssemblyReferences">
    <PropertyGroup>
        <AutoUnifyAssemblyReferences>true</AutoUnifyAssemblyReferences>
    </PropertyGroup>
</Target>
```

**Comment by v-anvari** [comment]
Hi @ggirard07 , Can we know if this is still persisting, we apologize for not following up frequently.

**Comment by ggirard07** [comment]
@v-anvari we no longer have that mixed solution with .Net Core / .Net Framework projects. So going to close it.
