### ISSUE TITLE
Failed ServiceBus messages can lead to reprocessing

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1605]
Repro function below. For the repro, set up another thread pumping messages once per second into the queue.

On the first delivery we cause a failure and we expect the message to be reprocessed. However in steady state, we don't expect the delivery count to go above 2. I mention steady state because if you ungracefully kill the repro, any in progress messages will be abandoned and get retried, so you might see a few re-deliveries.

What actually ends up happening is messages get reprocessed multiple times with delivery counts going over 3.

```csharp
public static void Run([ServiceBusTrigger("myqueue")] string message, string messageId, int deliveryCount, DateTime enqueuedTimeUtc, TraceWriter log)
{
    if (deliveryCount == 1)
    {
        throw new ApplicationException($"Exception for message {messageId}! Retry please.");
    }
    else if (deliveryCount > 2)
    {
        log.Info($"Unexpected delivery count Id={messageId}, DeliveryCount={deliveryCount}, EnqueuedTime={enqueuedTimeUtc}");
    }
    else
    {
        log.Info($"Message Id={messageId}, DeliveryCount={deliveryCount} processed successfully.");
    }
}
```

**Comment by krislw** [comment]
I have tried this now that the SDK has been released to all servers. I am **still** getting this issue where messages are being replayed, despite going over the specified dequeue count, and more importantly, successful messages are also being replayed.

Is there a specific client version of these APIs that we should be building our functions/webjobs with?
I am also struggling to find any best practice information regarding exception/error handling on message processing.
