### ISSUE TITLE
Servicebus triggers do not fire 

### ISSUE THREAD

**Issue by hentie** [Azure/azure-webjobs-sdk#1615]
We have 2 Function Apps: one with only Servicebus trigger and one with a Servicebus trigger and HTTP triggers.

For the Function App that only has Servicebus triggers, the functions are not always being triggerd as expected.    For the Function App that also contains HTTP triggers, the Servicebus triggers always trigger as expected.

The host.json is empty and I have no *setting.json file in the app.
All the app settings (including the Servicebus connectionstring) are defined in the App Settings section the Azure Portal.

Both Function Apps are using the Consumption plan 

#### Repro steps

1. I have a function app with only servicebus triggers
2. I have a servicebus and the function app has a connection string with manage rights
3. When messages are received in the servicebus topic the function app is subscribed to, the servicebus triggered function doesn't fire automatically.

#### Expected behavior

The function app always processes messages in the servicebus topics it is subscribed to when messages are present in the servicebus queue.

#### Actual behavior

The function app does processes messages in the servicebus topics it is subscribed to when messages are present in the servicebus queue, until I refresh the Function app in the Azure portal.

#### Known workarounds

1.  I click on monitoring for a function in the Function App via the Azure portal
2.  I open the root http link for the Function App in the browser
3.   I add an HTTP  trigger function to the Function app
4.  I call the "Invoke-AzureRmResourceAction syncfunctiontriggers" call via Azure CLI on the Function App after it is deployed

#### Related information 

The function apps use the following packages:
Microsoft.Azure.WebJobs.ServiceBus 2.1.0-beta4
Microsoft.NET.Sdk.Functions 1.0.6

Sample of a function.json in the Function App that does not trigger automatically:
`{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "topicName": "SessionCompleted",
      "subscriptionName": "AddMissingItemResults",
      "accessRights": "manage",
      "name": "message"
    }
  ],
  "disabled": false,
  "scriptFile": "...",
  "entryPoint": "..."
}`

**Comment by pragnagopa** [comment]
Can you share your Function App name either here or [indirectly](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately). Also, approximate time range when you would expect servicebus trigger to run

**Comment by hentie** [comment]
Hi Pragna,

My apologies for the late response.  I'm closing this issue as it was solved with the closure of another issue I logged: https://github.com/Azure/azure-functions-host/issues/2499  and it is also related to https://github.com/Azure/Azure-Functions/issues/229

Regardless, thank you for looking into this
