### ISSUE TITLE
Application insights logger is incompatible with AI 2.5.0+

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-webjobs-sdk#1619]
I just updated to 2.1.0 of the webjobs sdk and 2.5.0/1 of application insights. Locally everything was running fine, but once the webjobs landed on azure they started crashing and wouldn't run. After further investigation it turned out to be due to the **Microsoft.Azure.WebJobs.Logging.ApplicationInsights** package. Locally it wasn't running because the AI key wasn't set but once I configured that the crash started happening locally as well.

The issue is a result of namespaces changing in 2.5.0 of application insights. This should have been part of a 3.0.0 release but for some reason happened in 2.5.0. This causes classes that the webjobs logger tries to load to not be found, and you can't wire it up manually either.

#### Repro steps

1. Setup a webjob using AI logging with 2.1.0 of the sdk and 2.4.0 or 2.4.1 of application insights
1. Run the webjob and it should be fine
1. Update AI from 2.4.0 to 2.5.0+
1. Run the webjob again and it should crash on the `loggerFactory.AddApplicationInsights(instrumentationKey, null);` call

#### Expected behavior

Webjob to startup and run normally

#### Actual behavior

Webjob crashes because the namespace changed between 2.4.0 and 2.5.0 for `SamplingPercentageEstimatorSettings`, and probably many other classes, so the required types aren't found

#### Known workarounds

Revert to a version of AI prior to 2.5.0

#### Related information 

* Package versions
  * Webjobs SDK 2.1.0
  * Application Insights 2.5.0 and 2.5.1
* Links to source: 2.4.0 [SamplingPercentageEstimatorSettings.cs](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/v2.4.0/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/SamplingPercentageEstimatorSettings.cs) and 2.5.0 [SamplingPercentageEstimatorSettings.cs](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/v2.5.0/src/ServerTelemetryChannel/Implementation/SamplingPercentageEstimatorSettings.cs)

**Comment by xt0rted** [comment]
This is slightly off topic but the crash that happened on startup isn't being picked up by application insights (I have the site extension installed) or the AI snapshot collector. I only realized this was an issue when I noticed my storage requests chart a little while ago.

![image](https://user-images.githubusercontent.com/831974/37133465-884864d0-2261-11e8-888b-59d5d47d7f1e.png)

Are there any best practices on how to setup your webjobs so crashes on startup are logged and you can get notified about it? Using AI and Raygun are great, but they don't seem to help when the webjob is starting up unless you start wrapping your `Main` method in a try/catch and manually logging any exceptions, which gets tedious when you have a lot of webjobs.

Should the AI snapshot collector work with webjobs, or is that only good for the website?

**Comment by pragnagopa** [comment]
Thanks for reporting the issue: [Namespaces changed between 2.4.0 and 2.5.0 #727](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/727). We will wait for that issue to be resolved and check if we need to update in webjobs sdk. 
Please open a different issue for "how to capture errors on start up"?

**Comment by xt0rted** [comment]
Looks like version 2.6.0 of the app insights sdk (due out in a few weeks) should fix this issue by adding the class back in to the old namespace. Then in 3.0.0 the class will be moved to the new namespace permanently.

**Comment by paulbatum** [comment]
Closing this as its not a webjobs issue. The problems are on the app insights side.

**Comment by xt0rted** [comment]
Version 2.6.1 of app insights was released today, updating to this version does not fix this issue. I get the following error on both 2.1.0 and 2.2.0 of of the webjobs sdk:
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.ApplicationInsights.WindowsServer.Channel.Implementation.SamplingPercentageEstimatorSettings' from assembly 'Microsoft.AI.ServerTelemetryChannel, Version=2.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
  Source=Microsoft.Azure.WebJobs.Logging.ApplicationInsights
  StackTrace:
   at Microsoft.Extensions.Logging.ApplicationInsightsLoggerExtensions.AddApplicationInsights(ILoggerFactory loggerFactory, String instrumentationKey, Func`3 filter)
   at EquineExchange.Tasks.Emailer.Program.Main(String[] args) in C:\dev\equineexchange\EEI\src\EquineExchange.Tasks.Emailer\Program.cs:line 23
```

**Comment by paulbatum** [comment]
Got it, I see you commented on the app insights issue. I'll follow the discussion there and reactivate this if there is work needed on our side.

**Comment by xt0rted** [comment]
Digging into it a bit more I don't think the fix actually made it into this version despite the release notes saying it did. I've added my findings to the issue in their repo for further investigation.

**Comment by xt0rted** [comment]
Cross posting here for anyone that might be following along. Version 2.6.4 of app insights was just released which fixes this issue. Versions 2.5.x are broke and don't work at all with the app insights logger, and versions 2.6.1 - 2.6.3 don't fix the issue entirely so you'll need to update to 2.6.4+
