### ISSUE TITLE
Provide current instance number and instance count to webjob

### ISSUE THREAD

**Issue by jrr** [Azure/azure-webjobs-sdk#1634]
From inside a webjob, I'd like to query:

- how many instances this webjob is scaled out to
- this instance's number

Is this possible today?

## Use case: dynamic sharding boundary

I have a bunch of work to do on a large collection of records, and the data can't safely be naïvely operated on concurrently.

So, what I'd like to do is e.g., given `num_webjob_instances` and `this_webjob_instance_number`:

`select records where (record.owner.id % num_webjob_instances == this_webjob_instance_number)`, and operate on _those_.

Are there other patterns to achieve this?

**Comment by paulbatum** [comment]
There is no built in capability to expose the number of instances or to assign a machine a given instance number. But its generally not that hard to solve this problem by splitting it into two phases:
1. identify the work and break it up into logical chunks
2. Execute the work in each chunk

For example you might have a timer triggered webjob that queries the data source for the total number of records to process, and it gets back 1000. You've decided that you would like to process records in blocks of 100, so you write 10 queue messages that look like this:

```
{
 "mod": 10,
 "value": 1
},
{
 "mod": 10,
 "value": 2
}, etc
```

Then your queue triggered webjob does `where record.owner.id % msg.mod == msg.value`

Make sense?

**Comment by jrr** [comment]
That makes sense, and I'd definitely consider the approach for places where I'd use a timer trigger.

In this case I have a continuous webjob with a while(1) and dynamic sleep durations. I was hoping to scale out evenly across instances as I crank up the (traditional) app service plan.

**Comment by paulbatum** [comment]
Yeah! Should we close this issue, or would you prefer to keep it open to track this feature of actually providing an instance count and instance number. I don't expect we would do this any time soon..

**Comment by jrr** [comment]
It'd still be nice to have, to avoid paying latency and dollars for a message queue, but this is good enough for now. Thanks!
