### ISSUE TITLE
ApplicationInsightsLogger does not log EventId parameter

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-webjobs-sdk#1636]
The [ApplicationInsightsLogger](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLogger.cs) does not log the EventId parameter.

I expect this may be by design, but its not good design if the parameter is made available but then just ignored.

#### Repro steps

Log using ApplicationInsightsLogger (I am using an instance created internally within azure function host) and suppy an EventId parameter.

#### Expected behavior

The EventId parameter should be included in the application insights logs?

#### Actual behavior

The EventId parameter is not included in any application insights logging

#### Related information 

ApplicationInsightsLogger instance is used as a logging provider for logger created by internal logger factory in azure functions host.

**Comment by brettsam** [comment]
We can certainly log it, if it's there.
