### ISSUE TITLE
Deserializing POCO objects: note in Wiki

### ISSUE THREAD

**Issue by artkpv** [Azure/azure-webjobs-sdk#1639]
Thanks for the great ready to use tool for Queue!

Can we add a note in the wiki that WebJobs SDK can not determine type of POCO objects if properties are the same for classes? Or that should be handled manually somehow.

#### Repro steps
```
public class PocoCommandA { public string Prop { get; set; } }

public class PocoCommandB { public string Prop { get; set; } }

public static void Func1([QueueTrigger("myqueue")] PocoCommandA aCommand)
{... }

public static void Func2([QueueTrigger("myqueue")] PocoCommandB bCommand)
{ ... }
```
And it calls Fun2 (or some other) when

```
var a = new PocoCommandA();
var cloudQueueMessage = new CloudQueueMessage(JsonConvert.SerializeObject(a));

await queue.AddMessageAsync(cloudQueueMessage);
```

#### Expected behavior
How to make it deserialize to PocoCommandA?

#### Actual behavior
It deserializes to PocoCommandB. 

#### Related information 

* https://stackoverflow.com/questions/49412846/many-poco-types-per-one-queue-in-queuetriggerattribute
* WebJobs SDK 2.2.0-beta1-11229

**Comment by brettsam** [comment]
If you have two functions watching the same queue, it will be a race. Whichever function sees the message first will get it. I think that's the underlying issue.

Also note that when you serialize your objects to a JSON string and stick them in a message, you're not providing any type details. All the string sees is the properties, so there's no way to determine which type it is anyway. You'll need to provide some discriminating details about the type so you can make the proper decision when you see that message.

If you can determine what kind of message it is, you can then have one function that watches that queue and has an if/else to handle your logic. Or you can even stick them into different queues for further processing.

**Comment by artkpv** [comment]
@brettsam Thanks for the answer. It appears to me that only one function to a queue then, right? Wasn't clear from the doc. I've done it via putting a type in a message as described at SO (`TypeNameHandling`). Probably Azure WebJobs can do the same and allow multiple functions with different POCO per one queue. It uses Reflection anyway there. Can be closed now.
