### ISSUE TITLE
Cannot find a nuget package containing definition for CosmosDBTrigger 

### ISSUE THREAD

**Issue by reddy6ue** [Azure/azure-webjobs-sdk#1642]
I created a CosmosDBTrigger using the Visual Studio template for azure functions. A class definition for CosmosDBTrigger cannot be found. Usually when I use a vsix file, the nuget definition should automatically be populated. I don't know if this is the right forum to add this, but I'm unable to find a definition for CosmosDBTrigger class anywhere in any nuget package. Where do I find this class?

**Comment by pragnagopa** [comment]
Please install [Microsoft.Azure.WebJobs.Extensions.CosmosDB](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB).
