### ISSUE TITLE
ServiceBusQueue-CSharp get "Parameter 'Buffer' is null" error after triggered

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk#1644]
_From @SimonGuo009 on March 26, 2018 10:15_

**Portal Environment:** https://ms.portal.azure.com
**Browser:** English/Chrome
**Runtime Version:** 2.0.11651.0 (~1) (Private Site Extension)

Please refer to the snapshot:
![bug3_buffernullerror](https://user-images.githubusercontent.com/18321627/37900667-81ca73b8-3121-11e8-9f6b-ba67b8e03d03.png)

**Error content:**
_[Information] Executing 'Functions.ServiceBusQueueTriggerJS1' (Reason='New ServiceBus message detected on 'myinputqueue'.', Id=2f927311-bba0-4de8-814d-2331d701f55a)
[Error] System.Private.CoreLib: Exception while executing function: Functions.ServiceBusQueueTriggerJS1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'mySbMsg'. System.Private.CoreLib: Buffer cannot be null.
Parameter name: buffer._

**Repro steps:**
1. Open or create a function app.
2. Create a function using ServiceBusqueueTrigger template.
3. Send a message using ServiceBus queue.
4.Verify logs for the function.

_Copied from original issue: Azure/azure-functions-ux#2468_

**Comment by pragnagopa** [comment]
We need to look into this ASAP as servicebustrigger  is one of our core templates

**Comment by soninaren** [comment]
This is a dup of https://github.com/Azure/azure-functions-host/issues/2573. Happens when an empty message is sent.

```CSHARP
QueueClient Client = QueueClient.CreateFromConnectionString(connectionString, "queueName");
Client.Send(new BrokeredMessage());
```
