### ISSUE TITLE
Exception was thrown when upload a 0 byte file

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk#1645]
_From @SimonGuo009 on March 26, 2018 10:10_

**Portal Environment:** https://ms.portal.azure.com
**Browser:** English/Chrome
**Runtime Version:** 2.0.11651.0 (~1) (Private Site Extension)

Please refer to the snapshot:
![bug2_zerobytefileexception](https://user-images.githubusercontent.com/18321627/37900456-dce356ee-3120-11e8-8ecf-532dc584193b.png)

**Repro steps:**
1. Open or create a function app.
2. Create a function using BlobTriggerWithParameters-JavaScript template.
3. Upload a 0 byte file in the corresponding blob.
4.Verify logs for the function.

_Copied from original issue: Azure/azure-functions-ux#2467_

**Comment by SimonGuo009** [comment]
This bug can be reproduced in **Beta runtime** as well.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-nodejs-worker#69
