### ISSUE TITLE
Invalid target framework (4.5 expected but 4.6)

### ISSUE THREAD

**Issue by artkpv** [Azure/azure-webjobs-sdk#1651]
Can not build solution because of invalid framework

#### Repro steps

0.

.csproj:

```
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
```

1. 
`Install-Package  Microsoft.Azure.Webjobs `

2.
In .csproj (note *net45*)
```
      <HintPath>..\packages\Microsoft.Azure.WebJobs.Core.2.2.0\lib\net45\Microsoft.Azure.WebJobs.dll</HintPath>

```

3. 
Build:
```
6> warning MSB3274: The primary reference "Microsoft.Azure.WebJobs" could not be resolved because it was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".
```

In manifest of of the assembly `lib\net45\Microsoft.Azure.WebJobs.dll`:
```
NETFramework  ,Version=v4.6..T ..FrameworkDisplayName..NET Framework 4.6
```

#### Expected behavior

Works for 4.5.2

#### Actual behavior

Don't work

#### Related information 

https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.2.0

**Comment by paulbatum** [comment]
The package dependencies changed in webjobs 2.1.0 to be based on .NET Framework 4.6. So its expected that you would get this warning. If you want to be able to build without warnings while targeting 4.5.2, the solution is to stay on webjobs 2.0.0. 

Closing this as answered.
