### ISSUE TITLE
Functions V2 Runtime errors on F5 for a Functions project in Visual Studio

### ISSUE THREAD

**Issue by bzhu94** [Azure/azure-webjobs-sdk#1661]
Please provide a succinct description of the issue.

#### Repro steps

INSTALL STEPS
1. Clean machine: Win 8.1 x64 ENU

2. Install  15.7 Preview 3 VSC (Web + Azure workload) from : \\\cpvsbuild\drops\VS\d15.7\products\27602.00\bootstrappers 

3. Select Web + Azure workload

4. Install the VSIX: \\\vwdbuild01\Drops\WTA\AzureFunctions-Dev15-OOB.Nightly\Dev15\2018-04-04_b5536\Release\Signed\VSIX\enu\Microsoft.VisualStudio.Web.AzureFunctions.vsix

#### Expected behavior

This error message should not appear when the runtime is started.

#### Actual behavior

The following error shows up upon starting the runtime: 

Unable to configure java worker.Could not find JAVA_HOME app setting.

Could not configure language worker Java

![attachments](https://user-images.githubusercontent.com/8541576/38690928-33e8609a-3e34-11e8-9bff-f18a54551bf0.png)

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-host#2668
