### ISSUE TITLE
Provide specific error details instead of generic error "can't be invoked from Azure WebJobs SDK" 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk#1666]
[Jobhost](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/JobHost.cs#L372) needs to be updated to provide specific error message coming from ScriptHost. 
One example:  ScriptHost now throws error [here](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L1410) if invalid language is provided for setting [Functions_Worker_Runtime](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/ScriptConstants.cs#L70) but we do not see this error

**Comment by brettsam** [comment]
@pragnagopa -- ping
