### ISSUE TITLE
v3.0.0-beta5 failing with “Invalid storage account” exception

### ISSUE THREAD

**Issue by markosaric** [Azure/azure-webjobs-sdk#1672]
I was playing with .NET core WebJobs using version v2.2.0 of NuGet packages. I hit an “Invalid storage account” exception and I've replaced v2.2.0 packages with the v3 beta. I've tried all of the betas but I cannot overcome this issue.

#### Repro steps

I've followed the workaround described in this issue:

[https://github.com/Azure/azure-webjobs-sdk/issues/1649#issuecomment-377633805](https://github.com/Azure/azure-webjobs-sdk/issues/1649#issuecomment-377633805)

I am using Visual Studio for Mac version 7.4.3 (build 10) and I am working on macOS High Sierra Version 10.13.4

[Example project](https://github.com/markosaric/weblica2018)

**Comment by markosaric** [comment]
After removing the references, adding the 3.0.0-beta5 references and restarting the system I've overcome the issue with the "invalid storage account".

But I cannot read the environment variables when I set the variables on the project level or in the app.config. Also when I debug the WebJob locally I need to add the following code in Main() method for everything to work 

```
    class Program
    {
        static void Main()
        {
            var config = new JobHostConfiguration();
            config.UseTimers();

            if (config.IsDevelopment)
            {
                config.UseDevelopmentSettings();
            }

//These two lines resolve the issue 
            config.DashboardConnectionString = ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ConnectionString;
            config.HostId = Guid.NewGuid().ToString("N");

            var host = new JobHost(config);
            host.CallAsync(typeof(Functions).GetMethod("ProcessFileAsync"));
            // The following code ensures that the WebJob will be running continuously
            host.RunAndBlock();
        }
    }```

**Comment by pragnagopa** [comment]
When running in Azure config.HostId is calculated based on the AppName. You do not have to set it when running locally. 
For app settings you can use appsettings.json. Here is a sample : [azure-webjobs-dotnet-core-sample](https://github.com/christopheranderson/azure-webjobs-dotnet-core-sample)
