### ISSUE TITLE
SamplingPercentageEstimatorSettings could not be found.

### ISSUE THREAD

**Issue by wortho** [Azure/azure-webjobs-sdk#1688]
When following the steps described in https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration I get the error: 

>  'SamplingPercentageEstimatorSettings' claims it is defined in 'Microsoft.AI.ServerTelemetryChannel', but it could not be found. 

If I don't try and implement the CustomTelemetryClientFactory then I get a different error:

> System.TypeLoadException: 'Could not load type 'Microsoft.ApplicationInsights.WindowsServer.Channel.Implementation.SamplingPercentageEstimatorSettings' from assembly 'Microsoft.AI.ServerTelemetryChannel, Version=2.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'

Is there another package needed?	

#### Repro steps

Provide the steps required to reproduce the problem

1.  Create a WebJob project targetting .Net Framework 4.7 and follow the steps described in **https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration**

#### Expected behavior

It should build.

#### Actual behavior

Build fails with 'SamplingPercentageEstimatorSettings' claims it is defined in 'Microsoft.AI.ServerTelemetryChannel', but it could not be found.

Provide any related information 

* Package version 2.2.0

**Comment by pragnagopa** [comment]
There were namespace changes in Microsoft.ApplicationInsights.WindowsServer nuget package. related issue: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/727.
Application Insights with webjobs sdk should work as long as you do not update the dependent nuget packages. Closing this issue for now.
