### ISSUE TITLE
Bump dependencies to latest

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#1699]
In preparation for cutting 3.x we want to get our dependencies up to date. Couple of examples:

- Json.NET 10.x -> 11.x
- Storage 8.x -> 9.x
- Microsoft.Extensions.Logging.Abstractions 2.0.0 -> 2.1.0 (assuming it goes GA soon, its in RC right now)
- Microsoft.ApplicationInsights 2.5.0 -> 2.6.2 (about to be released, fixes a regression in 2.6)

**Comment by fabiocav** [comment]
Most of the dependencies have been updated with the move to .NET Core 2.1 (including Json.NET). Storage is still pending as we need to finish the DI work and bring the isolated extensions. This will bleed into the next sprint.

**Comment by paulbatum** [comment]
Resolved as part of other work items.
