### ISSUE TITLE
Newtonsoft.Json.JsonReaderException exception on all queue messages.

### ISSUE THREAD

**Issue by FrikkinLazer** [Azure/azure-webjobs-sdk#1702]
'Newtonsoft.Json.JsonReaderException' thrown from JsonSerialization.cs on any queue message received.
The message does get processed successfully though, despite the exception.

#### Repro steps
I have attached a zip with the solution as well.

Packages:
```
<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta5" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.4.1" />  
```  

Here is the function:
```
public static void TEST1(
            [QueueTrigger("testqueue")] string queueItem
        ) {
            Console.WriteLine(queueItem);
        }
```

The code inside the function gets called successfully. But for every message received on the queue this exception is also thrown:

An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll but was not handled in user code: 'Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 4.'
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Azure.WebJobs.Host.Protocols.JsonSerialization.ParseJObject(String json) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Protocols\JsonSerialization.cs:line 102
   at Microsoft.Azure.WebJobs.Host.Queues.QueueCausalityManager.GetOwner(IStorageQueueMessage msg) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Queues\QueueCausalityManager.cs:line 56

#### Expected behavior

The exception should not be thrown.

#### Known workarounds

Ignore the exception.

#### Related information 

Provide any related information 

[coregeneral.zip](https://github.com/Azure/azure-webjobs-sdk/files/2009109/coregeneral.zip)

**Comment by paulbatum** [comment]
Do you have first chance exceptions turned on in VS? This exception is thrown and caught as part of the pipeline that attempts to determine if the payload is JSON and whether it should be deserialized as such.

**Comment by FrikkinLazer** [comment]
In VS Code, I have "All Exceptions" unticked, and "User-Unhandled Exceptions" ticked.

**Comment by paulbatum** [comment]
I can reproduce this behavior in VS code but not in VS. I think there must be a problem with how VS code determines "user unhandled". We know the exception is handled because the application continues to work and process messages. I suggest you follow up with VS code, but for completeness I also filed this cleanup item to remove this particular exception: https://github.com/Azure/azure-webjobs-sdk/issues/1706

**Comment by BowserKingKoopa** [comment]
I wonder if this is similar to the issue that surprised me: https://github.com/Azure/azure-functions-host/issues/2688 I had Visual Studio breaking on a serialization Exception, which caught me by surprise because I have 'Just My Code' enabled and I've never had it break on library Exceptions like this before. I ended up having to 'ignore' that one particular Exception manually.

**Comment by paulbatum** [comment]
Thats interesting, because its actually the same exception. So now I'm wondering why does my VS behave "as desired". Perhaps there is not VS code issue here, and something else is having an impact on whether the debugger stops at this exception or not..

**Comment by FrikkinLazer** [comment]
I am getting the same behavior in VS2017 15.6.5 on windows 10, with core 2.1.200. The exception is thrown. I am not sure what is different in my environment.

![image](https://user-images.githubusercontent.com/2371314/40218710-9ed6cdd8-5a72-11e8-8ac4-92ea8cb28eb0.png)

**Comment by RichardMisiak** [comment]
I'm encountering the same issue.
VS 2017 15.7.3
Windows 10
Azure Functions and Web Jobs Tools 15.04.0502.0
.NET Standard 2.0

"Just my code" is enabled

**Comment by pankhaniyanarendra** [comment]
An exception of type 'Newtonsoft.Json.JsonReaderException' occurred in mscorlib.dll but was not handled in user code

Additional information: Input string '1.44' is not a valid integer. Path 'change', line 1, position 656.

how  to fix error

**Comment by pankhaniyanarendra** [comment]
protected void btnsymbol_Click(object sender, EventArgs e)
        {
            var symbol = "AAPL";
            var IEXTrading_API_PATH = "https://api.iextrading.com/1.0/stock/{0}/quote";

            IEXTrading_API_PATH = string.Format(IEXTrading_API_PATH, symbol);

            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                //For IP-API
                client.BaseAddress = new Uri(IEXTrading_API_PATH);
                HttpResponseMessage response = client.GetAsync(IEXTrading_API_PATH).GetAwaiter().GetResult();
                if (response.IsSuccessStatusCode)
                {
                    var companysInfo = response.Content.ReadAsAsync<CompanyInfoResponse>().GetAwaiter().GetResult();
                    if (companysInfo != null)
                    {
                        lblCompanyName.Text = Convert.ToString(companysInfo.companyName);
                        lblOpen.Text = Convert.ToString(companysInfo.open);
                        lblClose.Text = Convert.ToString(companysInfo.close);
                        lblLow.Text = Convert.ToString(companysInfo.low);
                        lblHigh.Text = Convert.ToString(companysInfo.high);
                        lbl52WeekLow.Text = Convert.ToString(companysInfo.week52Low);
                        lbl52WeekHigh.Text = Convert.ToString(companysInfo.week52High);
                    }
                }
            }
        }


give me solusion for this eror

**Comment by pankhaniyanarendra** [comment]
protected void btnsymbol_Click(object sender, EventArgs e)
        {
            var symbol = "AAPL";
            var IEXTrading_API_PATH = "https://api.iextrading.com/1.0/stock/{0}/quote";

            IEXTrading_API_PATH = string.Format(IEXTrading_API_PATH, symbol);

            using (HttpClient client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                //For IP-API
                client.BaseAddress = new Uri(IEXTrading_API_PATH);
                HttpResponseMessage response = client.GetAsync(IEXTrading_API_PATH).GetAwaiter().GetResult();
                if (response.IsSuccessStatusCode)
                {
                    var companysInfo = response.Content.ReadAsAsync<CompanyInfoResponse>().GetAwaiter().GetResult();
                    if (companysInfo != null)
                    {
                        lblCompanyName.Text = Convert.ToString(companysInfo.companyName);
                        lblOpen.Text = Convert.ToString(companysInfo.open);
                        lblClose.Text = Convert.ToString(companysInfo.close);
                        lblLow.Text = Convert.ToString(companysInfo.low);
                        lblHigh.Text = Convert.ToString(companysInfo.high);
                        lbl52WeekLow.Text = Convert.ToString(companysInfo.week52Low);
                        lbl52WeekHigh.Text = Convert.ToString(companysInfo.week52High);
                    }
                }
            }
