### ISSUE TITLE
Log background errors coming from EventProcessorHost

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1705]
When setting up the EventProcessorHost, we don't currently add an event handler to [EventProcessorOptions.ExceptionReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.eventprocessoroptions.exceptionreceived?view=azure-dotnet). This means that any background exceptions will be silently ignored.

See related issue https://github.com/Azure/azure-webjobs-sdk/issues/1703

**Comment by pragnagopa** [comment]
Related info: Fix for Issue #1357 added logging in [EventHubListener.cs#L131](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubListener.cs#L131). 

Issue tracking to add E2E test #1604.
