### ISSUE TITLE
Do not automatically try to deserialize queue messages as JSON

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#1706]
The code path for handling queue messages blindly does a `JObject.Load(..)` on the contents of the message and this results in a JsonReaderException being thrown for every message. These exceptions are handled but they still impact user debugging experience (users sometimes have first chance exceptions turned on, and VS code has issues with these, see [here](https://github.com/Azure/azure-webjobs-sdk/issues/1702#issuecomment-389743961)). 

It'd be a significant amount of work to root out every "unnecessary" first chance exception but this one feels like low hanging fruit.

**Comment by paulbatum** [comment]
It seems like Json.NET does not have a `TryParse` or `TryLoad`, but you can specify an error handler in the serializer settings, maybe we can use that to avoid the thrown exception:

https://www.newtonsoft.com/json/help/html/ErrorHandlingEvent.htm

**Comment by maiqbal11** [comment]
Fix is in #1930
