### ISSUE TITLE
Can a javascript function have multiple input bindings?

### ISSUE THREAD

**Issue by sgwatgit** [Azure/azure-webjobs-sdk#1725]
Please provide a succinct description of the issue.

#### Repro steps

I'm running my 1.x function locally. When I have either the http binding or the timer binding enabled my function executes as expected. When I try to enable both bindings I get an error in the terminal.

Here is my `functions.json`
```json
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "authLevel": "anonymous",
      "methods": ["post", "get"]
    },
    {
      "schedule": "0 */1 * * * *",
      "name": "timerTrigger",
      "type": "timerTrigger",
      "direction": "in"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```
Here is my function signature
`module.exports = function(context, data, timerTrigger) { }`

Here is the error in the console
```
[5/25/2018 4:35:23 AM] Loaded custom extension 'BotFrameworkConfiguration'
[5/25/2018 4:35:23 AM] Loaded custom extension 'SendGridConfiguration'
[5/25/2018 4:35:23 AM] Loaded custom extension 'EventGridExtensionConfig'
[5/25/2018 4:35:23 AM] registered EventGrid Endpoint = http://localhost:7071/admin/extensions/EventGridExtensionConfig
[5/25/2018 4:35:24 AM] Generating 0 job function(s)
[5/25/2018 4:35:24 AM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
[5/25/2018 4:35:24 AM] Host initialized (729ms)
[5/25/2018 4:35:24 AM] Host started (895ms)
[5/25/2018 4:35:24 AM] Job host started
[5/25/2018 4:35:24 AM] The following 1 functions are in error:
[5/25/2018 4:35:24 AM] SlackWebhookJS: Sequence contains more than one matching element.
[5/25/2018 4:35:24 AM]
[5/25/2018 4:35:24 AM]
[5/25/2018 4:35:24 AM] Host lock lease acquired by instance ID '0000000000000000000000007A67151E'.
[5/25/2018 4:35:24 AM] Executing HTTP request: {
[5/25/2018 4:35:24 AM]   "requestId": "f1e3d0c7-0bdd-4c80-8abf-c35ba6c28565",
[5/25/2018 4:35:24 AM]   "method": "GET",
[5/25/2018 4:35:24 AM]   "uri": "/"
[5/25/2018 4:35:24 AM] }
[5/25/2018 4:35:24 AM] Executed HTTP request: {
[5/25/2018 4:35:24 AM]   "requestId": "f1e3d0c7-0bdd-4c80-8abf-c35ba6c28565",
[5/25/2018 4:35:24 AM]   "method": "GET",
[5/25/2018 4:35:24 AM]   "uri": "/",
[5/25/2018 4:35:24 AM]   "authorizationLevel": "Anonymous",
[5/25/2018 4:35:24 AM]   "status": "OK"
[5/25/2018 4:35:24 AM] }
launch.json for VSCode configured.
Debugger listening on [::]:5858
```

#### Expected behavior

I can trigger my function the timer or http request

#### Actual behavior

The function errors and doesn't respond to either triggers.

#### Known workarounds

None? Can't find any documentation stating whether this is or is not supported with Javascript

#### Related information 

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#trigger doesn't show a multi-in example

https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings states **Bindings are optional and a function can have multiple input and output bindings.**

My motivation behind this is wanting my function to be triggered via http for its functionality and triggered by a timer to keep it fresh (not have to wait for cold start, which Slack does not care about - 3 seconds max response time before it displays an error to the user).

**Comment by paulbatum** [comment]
Azure Functions has three types of bindings - trigger, input, output. A given function must have exactly one trigger. You've defined two. To achieve your goal of having a timer to keep the app fresh, move it into a separate function.

For more details on all of this, see here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings

**Comment by dxkaufman** [comment]
@paulbatum, I am pretty new to Azure functions... I'm using Visual Studio Code.  I have one function working well, which is based on a Timer trigger.  It uses a storage blob to look up the configuration information (database connection string, auth keys for 2 APIs, etc.) and then uses the 2 APIs to pull data from two systems which it then stores in a SQL database.  

Now, I need to write an http trigger as a webhook endpoint to get event based information from one of the systems that isn't available via their API.  I was hoping to put the additional function in the same folder so as to use the same python environment, etc., but it sounds as if that's not an option.  I'll have to create a completely new env and folder for the new function, right?  And once I deploy, they'll appear as two separate entries under the function list in the Azure portal:

![image](https://user-images.githubusercontent.com/26446314/56841761-934ef180-6844-11e9-9d49-774c7d465f81.png)

So, instead of just saying DataPipeline, it'll list DataPipeline and LoginEvents (assuming I call it that).

As I mentioned, I'm pretty new to this; am I on the right track?

Thanks so much for your help!
Dylan

**Comment by dxkaufman** [comment]
Well, and as soon as I wrote that, I discovered that a sample I set up in a different account actually has two triggers in the same folder:

![image](https://user-images.githubusercontent.com/26446314/56841944-972f4380-6845-11e9-91c9-58170d48766c.png)

Now I just have to figure out why that works but my attempt to do the same didn't... That is, when I had DataPipeline (timer) and LoginEvents (http trigger) in the same project folder, the deployment only seems to have deployed DataPipeline but not LoginEvents.

**Comment by paulbatum** [comment]
Yep that screenshot looks correct. Two different functions within the same function app. If you're using the [azure functions core tools](https://github.com/Azure/azure-functions-core-tools), this is what you'll get if you do the following:

```
> func init
(select python)
> func new
(select timertrigger)
> func new
(select httptrigger)
> tree /f

Folder PATH listing for volume FAST
Volume serial number is 4E91-2693
D:.
│   .gitignore
│   host.json
│   local.settings.json
│   requirements.txt
│
├───.vscode
│       extensions.json
│
├───HttpTrigger
│       function.json
│       sample.dat
│       __init__.py
│
└───TimerTrigger
        function.json
        readme.md
        sample.dat
        __init__.py
```

**Comment by dxkaufman** [comment]
Interesting... unfortunately, with the sample app I can get the http trigger to work, but adding a new folder (where HttpTrigger would be, but with just function.json and a .py file) to my existing project doesn't work... 

Aaaannnd... I went to run it again to get the error message, and now it is working.

**Comment by dxkaufman** [comment]
OK, that's pretty cool.  Thanks for the confirmation!  

I assume that if I wanted I could put more functions in as well, whether on a timer or http trigger?  So I could have a separate http trigger for each webhook I want to receive, and I could have one timer trigger that runs at midnight and another that runs every hour, right?  All in the same project folder?

**Comment by paulbatum** [comment]
Yes. The way to think about it is that the function app (i.e. a collection of functions) is the unit of deployment.  You make changes, potentially across several functions, and then you deploy them all in one action.

**Comment by dxkaufman** [comment]
Awesome.  Thanks!
