### ISSUE TITLE
ServicePointManager settings

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-webjobs-sdk#1734]
Apart from the connection limit, are there any other ServicePointManager settings that are appropriate to set.

For example, on my web applications I have
```
<settings>
    <servicePointManager expect100Continue="false" dnsRefreshTimeout="120000" useNagleAlgorithm="false"/>
</settings>
```
I was wondering if this was also appropriate for WebJobs

**Comment by phatcher** [comment]
Nudge

**Comment by brettsam** [comment]
It really depends on the scenario -- we wanted to call out what we determined was an absolute requirement (the default of 2 was causing lots of bad behavior from customers that didn't know about it). The `Expect100Continue` and `UseNagleAlgorithm` settings may be beneficial to disable in some scenarios.

The Nagle algorithm, for example, is good to disable for Azure Storage Queues and Tables, but not necessarily for Blobs: https://docs.microsoft.com/en-us/azure/storage/common/storage-performance-checklist#subheading26. So we didn't want to give blanket guidance on those.

**Comment by phatcher** [comment]
@brettsam Thanks for the response
