### ISSUE TITLE
Microsoft.ServiceBus.Messaging vs Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by ryancrawcour** [Azure/azure-webjobs-sdk#1737]
some parts of this extension appear to use the older client library (Microsoft.ServiceBus.Messaging), and other parts use the newer one (Microsoft.Azure.ServiceBus).

https://github.com/Azure/azure-webjobs-sdk/blob/v2.x/src/Microsoft.Azure.WebJobs.ServiceBus/ServiceBusAttribute.cs

vs 

https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.ServiceBus/Triggers/ServiceBusTriggerBinding.cs

Is there a reason for this?

Quite happy to submit a PR to use the newer client only if there are no obvious issues with this. 

Has this been looked at already? 
Am I about to open Pandora's box here if I go down this road?

**Comment by paulbatum** [comment]
You linked to two different branches. This is deliberate. The newer version uses the newer client library.
