### ISSUE TITLE
Provide a way to receive alerts if the webjob host failed to start a job

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-webjobs-sdk#1742]
If you deploy a webjob and it fails to start for any reason, including one out of your control https://github.com/aspnet/websdk/issues/347, there should be a way to get alerted of this. My site has the AI extension installed, the site & webjobs use AI & Raygun for error monitoring, but none of this picks up issues when the webjob host fails to run the job. I've run into this once before (#1619) and it's incredibly frustrating to find out hours or days later instead of immediately.

I'd love to see these issues get surfaced into AI, as well as some way to tell a 3rd party system such as Slack, Raygun, or Bugsnag that there was a problem.

#### Repro steps

1. Publish a full framework webjob with a `run.cmd` that contains `dotnet WebJob.exe`
2. Watch it never startup
3. Wonder how you can get alerted of this type of issue

#### Expected behavior

At the very least the portal should give me an error alert that the webjob is failing to start

#### Actual behavior

Nothing happens, everything continues on as normal

#### Known workarounds

None

**Comment by paulbatum** [comment]
This issue was moved to projectkudu/kudu#2789
