### ISSUE TITLE
Event Grid Subscription for Event Hub to ingest logs in particular partition

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk#1750]
_From @himanshu219 on May 31, 2018 12:55_

While creating event subscription and using eventhub as endpoint there is no way of specifying the partitionID to which all messages should be sent. Is it possible via Webhook? I found that it is possible via Rest API see [here](https://stackoverflow.com/questions/32251517/selecting-partition-of-azure-event-hub-when-using-rest-api). It uses the following url. https://{serviceNamespace}.servicebus.windows.net/{eventHubPath}/publishers/{deviceId}/messages. I am trying to ingest those events to event hub. but what I want is those events to be ingested into a particular partition in event hub.
Is it possible via Event subscription (probably by passing deviceid as parameter)? Or Is there any way to configure event subscription to route those events to a particular partitionID in event hub.

_Copied from original issue: Azure/azure-functions-eventgrid-extension#41_

**Comment by jeffhollan** [comment]
I believe (and correct me if I'm wrong) that this issue is closer to do with creating an event hub trigger for functions than event grid?  If I'm wrong this issue is likely not a function issue at all but something on Event Grid.

Regardless assuming what you are trying to do is trigger a function from an Event Hub on a particular partition (potentially ignoring the other ones).  I could be wrong as you also talk about sending messages to a specific partition.  Here's some info:

1. For the Event Hub trigger we use the Event Processor Host which automatically locks available partitions from event hubs and ensures all events are streamed from all partitions.  There isn't a way with the current trigger to only read from a single partition - and also not something we will likely support.  The Event Hubs team generally discourages trying to prioritize specific partitions, but a conversation we can have with them.

1. If trying to send to an event hub, you can specify a "partition key" using the event hubs SDK.  This is used mainly to preserve ordering so that all events for the same publisher land in the same partition.

Hopefully this helps.  I'm going to close this issue for now as I'm not sure there's anything actionable on functions side.  Potentially a feature request on Event Grid to support creating an event grid subscription per partition of event hubs (though I suspect they may also bring up 1 above).  Let me know if I've misunderstood something

**Comment by himanshu219** [comment]
Yes you are right this is about Event Grid and is related to web hooks that's why I asked there. I couldn't find any specific event grid repo to post that that's why posted in Event Grid Extension for Azure Functions hoping they might know.
Also I wanted to raise a feature request on Event Grid to support creating an event grid subscription per partition of event hubs to ensure all events for the same publisher land in the same partition. I think than I can configure multiple publishers for each of those partitions so that it solves the distribution issue you mentioned in point 1)

**Comment by jeffhollan** [comment]
Fair enough - yes Event Grid team not tracking either of these repos though.  Best place would be creating items [in their uservoice here](https://feedback.azure.com/forums/909934-azure-event-grid) or potentially reaching out to their product managers on Twitter @DanRosanova @BAHRAwesoMe
