### ISSUE TITLE
Don't checkpoint when Event Hubs Listener is closing

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk#1752]
Here we do a checkpoint if an EventHubListener is closing [because of a server shutdown](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.closereason?view=azure-dotnet)
https://github.com/Azure/azure-webjobs-sdk/blob/700947786067834c775bce588483c4560c1eb0ca/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/EventHubListener.cs#L118-L121

I'm not sure why we would want to checkpoint in this case.  Since this appears to be invokable in parallel to an execution that may be in progress (and not yet completed), seems it could result in an invalid checkpoint for in flight data.

Seems we shouldn't have these lines.

**Comment by paulbatum** [comment]
I agree this looks like an issue. Here's an example sequence:

1. Functions are in the process of executing.
2. For one of several reasons, we decide we need to start a graceful shutdown of the host. This calls `StopAsync` on the listener.
3. Stopping the listener triggers a call to CloseAsync on each partition listener, which cancels the cancellation token passed into user code.
4. User code aborts the execution (assuming they are handling the token cancellation). Their functions did not finish running
5. The line that Jeff highlighted checkpoints anyway, and so the system "loses" the data from the aborted executions.

@mathewc Can you see any mistakes in the above reasoning?

**Comment by mathewc** [comment]
Agreed - this seems like an issue. Recommend we create a simple repro that demonstrates the problem that we can use to verify the fix.

**Comment by mathewc** [comment]
Possibly related: ICM 73233348

**Comment by jeffhollan** [comment]
Thanks for looking into this. Yes that ICM is what first made me inspect the code and find a potential gap. I don't think necessarily this is what they were hitting but is a possibility as it is clear during the logs of their incident during data loss was a transition of partition listeners between instances (one instance took a partition lock away from another) - so possible is related
