### ISSUE TITLE
Queue trigger is not working for Web Job SDK 2.2.0

### ISSUE THREAD

**Issue by RudraKN** [Azure/azure-webjobs-sdk#1779]
Please provide a succinct description of the issue.

#### Repro steps

1. When there is a new message  in the storage queue, web job is not picking that message until we re-start the web-job.

Provide the steps required to reproduce the problem

1. Add messages to the storage queue
2. Run the Web Job
3. After all the messages are processed
4. Again add messages to the storage queue
5. Messages are not processed, though the Web-Job status is showing it as running.

#### Expected behavior

Messages should get processed.

#### Actual behavior

Messages are not processed, though the Web-Job status is showing it as running.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

 * I am running the Web-Job from Visual studio & also from the Azure Web-App
* Package version (Web-Job-SDK 2.2.0) and (Storage SDK 9.3)
* Links to source

**Comment by brettsam** [comment]
Some questions that will help:
- What if you go back to Storage 7.2.1?
- Is it possible that another app is dequeuing messages?

**Comment by RudraKN** [comment]
Hi Brett,

Thanks for your response, we have found the issue and fixed it. You can close the case.

Regards
Rudra

**Comment by askgupta** [comment]
Hi Rudra,

We're facing the same problem. Could you please let us know what fix did you apply for this?

Thanks,
Ashish
