### ISSUE TITLE
ExtensionConfigContext & JobHostConfig

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-webjobs-sdk#1786]
The ExtensionConfigContext has had the Config property removed?
this property was useful when an extension wished to inspect the host configuration

public void Initialize(ExtensionConfigContext context)

please advise on how/what method to use moving forward to access JobHostConfig

note this seem only to occur when referencing Microsoft.Azure.WebJobs.Extensions.Storage v3.0.0.0-beta7-11365

**Comment by brettsam** [comment]
There is no more `JobHostConfiguration` in the v3 builds as everything is moving to the .NET Core DI/Configuration model. So anything you want from the host can be requested as a constructor parameter, and it'll be injected.

We'll have more info on this as we move all of our other extensions to the new model (we're still working our way through the changes ourselves).

**Comment by grahamehorner** [comment]
@brettsam I understand that this is the case; nothing stands still in development, can you advise what branch this work is getting done in so I may monitor & review changes and keep up to speed ready for when this is published and we can have our code support this new build quickly.  PS. I'm all for these updates and support for the .NET core DI/Configuration/Logging 👍 x100

**Comment by brettsam** [comment]
All of this work is now going into the `dev` branch, which is our "WebJobs v3" branch.
