### ISSUE TITLE
When using Microsoft.Azure.WebJobs.ServiceBus, StyleCop.Analyzers is running on customer code.

### ISSUE THREAD

**Issue by acollard** [Azure/azure-webjobs-sdk#1794]
The StyleCop.Analyzers nuget package is not marked as "&lt;PrivateAssets&gt;all&lt;/PrivateAssets&gt;" in the Microsoft.Azure.WebJobs.ServiceBus csproj file. See https://github.com/Azure/azure-webjobs-sdk/blob/98fa140a1f3da243602be0aa14bb2e1f04dadb0b/src/Microsoft.Azure.WebJobs.ServiceBus/WebJobs.ServiceBus.csproj#L13

#### Repro steps
1. Create a new project (ex. .net core console app).
2. Add nuget package Microsoft.Azure.WebJobs.ServiceBus (3.0.0-beta7-11365). StyleCop.Analyzers is now referenced and runs against your code.

#### Expected behavior
StyleCop.Analyzers nuget package should not be pulled into customer projects.

#### Actual behavior
StyleCop.Analyzers nuget package is pulled into customer projects. Which results in style cop errors everywhere.

#### Known workarounds
None.

#### Related information 
* Package version: Microsoft.Azure.WebJobs.ServiceBus 3.0.0-beta7-11365
* Screenshot: 
![image](https://user-images.githubusercontent.com/2044172/42292658-17b791c0-7fa2-11e8-9829-0b8dbecd846b.png)

**Comment by fabiocav** [comment]
@brettsam to validate if this is still an issue.

**Comment by brettsam** [comment]
I validated that all of our released packages now have this set correctly.
