### ISSUE TITLE
ConfigureWebJobsHost in (latest, right now) Beta-5 nuget?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk#1798]
Hi 👋 

I'm looking at the latest code for Program.cs and notice some really nice stuff, like this:

```
    .ConfigureWebJobsHost()
    .AddWebJobsLogging() // Enables WebJobs v1 classic logging 
    .AddAzureStorageCoreServices()
    .AddAzureStorage()
```

Q] Are these extension methods available now in the (currently latest) Beta-5 of WebJobs nuget?

cheers!

**Comment by mathewc** [comment]
Not published to nuget yet, since we're still in the process of finishing up / integrating all the DI changes across the core WebJobs SDK + extensions repos. We're working towards an integrated beta release of all this stuff soon. @fabiocav

**Comment by xt0rted** [comment]
@mathewc now that Beta8 is out which has all the new DI/Hosting bits are there plants to put this on MyGet or NuGet?
