### ISSUE TITLE
System.MissingMethodException: 'Method not found: 'Microsoft.Azure.WebJobs.Host.JobHostTraceConfiguration Microsoft.Azure.WebJobs.JobHostConfiguration.get_Tracing()'.'

### ISSUE THREAD

**Issue by tjrobinson** [Azure/azure-webjobs-sdk#1811]
When using `Microsoft.Azure.WebJobs` `3.0.0-beta5` this exception occurs when using `https://github.com/JSkimming/serilog-extensions-webjobs`:

```
System.MissingMethodException: 'Method not found: 'Microsoft.Azure.WebJobs.Host.JobHostTraceConfiguration Microsoft.Azure.WebJobs.JobHostConfiguration.get_Tracing()'.'
```

It can be resolved by downgrading `Microsoft.Azure.WebJobs` to `3.0.0-beta4`.

#### Repro steps

1. Add `Serilog.Extensions.WebJobs` to a WebJob project as described here: https://github.com/JSkimming/serilog-extensions-webjobs
2. Start the WebJob
3. Exception occurs

#### Expected behavior

No exception occurs, WebJob output is logged via Serilog.

#### Actual behavior

```
System.MissingMethodException: 'Method not found: 'Microsoft.Azure.WebJobs.Host.JobHostTraceConfiguration Microsoft.Azure.WebJobs.JobHostConfiguration.get_Tracing()'.'
```

#### Known workarounds

It can be resolved by downgrading `Microsoft.Azure.WebJobs` to `3.0.0-beta4`.

#### Related information 

https://github.com/JSkimming/serilog-extensions-webjobs/issues/8

**Comment by tjrobinson** [comment]
I haven't seen this happen for months so I expect updates to various packages have now resolved this.

**Comment by TejaKommineni** [comment]
> When using `Microsoft.Azure.WebJobs` `3.0.0-beta5` this exception occurs when using `https://github.com/JSkimming/serilog-extensions-webjobs`:
> 
> ```
> System.MissingMethodException: 'Method not found: 'Microsoft.Azure.WebJobs.Host.JobHostTraceConfiguration Microsoft.Azure.WebJobs.JobHostConfiguration.get_Tracing()'.'
> ```
> It can be resolved by downgrading `Microsoft.Azure.WebJobs` to `3.0.0-beta4`.
> 
> #### Repro steps
> 1. Add `Serilog.Extensions.WebJobs` to a WebJob project as described here: https://github.com/JSkimming/serilog-extensions-webjobs
> 2. Start the WebJob
> 3. Exception occurs
> 
> #### Expected behavior
> No exception occurs, WebJob output is logged via Serilog.
> 
> #### Actual behavior
> ```
> System.MissingMethodException: 'Method not found: 'Microsoft.Azure.WebJobs.Host.JobHostTraceConfiguration Microsoft.Azure.WebJobs.JobHostConfiguration.get_Tracing()'.'
> ```
> #### Known workarounds
> It can be resolved by downgrading `Microsoft.Azure.WebJobs` to `3.0.0-beta4`.
> 
> #### Related information
> [JSkimming/serilog-extensions-webjobs#8](https://github.com/JSkimming/serilog-extensions-webjobs/issues/8)

It worked by downgrading to 3.0.0-beta4

**Comment by tjrobinson** [comment]
Microsoft.Azure.WebJobs 3.0.0 is out now, have you tried that?

https://www.nuget.org/packages/Microsoft.Azure.WebJobs/
