### ISSUE TITLE
ExecutionContext exists in both WebJobs.Extensions and WebJobs.Host

### ISSUE THREAD

**Issue by Davy-F** [Azure/azure-webjobs-sdk#1867]
Running Azure Functions and Web Jobs Tools v15.0.40617.0. 
C# Function App.

I get the following message:

> Error	CS0433	The type 'ExecutionContext' exists in both 'Microsoft.Azure.WebJobs.Extensions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'	

This is causing a conflict when trying to run my app using Azure WebJobs.

**Comment by Davy-F** [comment]
Nevermind. This was an issue when having the Nuget Package and Visual Studio Tools/Extensions both installed.

**Comment by klogan12** [comment]
What is the solution here?
