### ISSUE TITLE
Change to Azure Runtime 2.0.12050.0 breaks my Azure Function

### ISSUE THREAD

**Issue by wpqs** [Azure/azure-webjobs-sdk#1873]
I last published an Azure Function about a month ago. It has worked fine for weeks, but this afternoon I noticed it was failing. Inspection of the Test/Log blade showed an error - see below. 

It seems that the runtime Azure.WebJobs.Extensions can't support the ExecutionContext type needed by my code. This suggests that there has been a change to the Runtime which breaks existing Function Apps. The current runtime is version 2.0.12050.0 (beta). If this is a know issue it would be great if Azure subscribers using Azure Functions, like myself, we given a bit of warning about such things. 

![defect-2](https://user-images.githubusercontent.com/41650443/44988409-3302fb00-afa8-11e8-8b9b-553cb7492287.PNG)

**Comment by Liversage** [comment]
The announcement [Azure Functions Runtime 2.0.12050-alpha breaking changes notice](https://github.com/Azure/app-service-announcements/issues/129) might apply to your problem.

**Comment by paulbatum** [comment]
Indeed, closing this.
