### ISSUE TITLE
trying to cope with the demise of JobHostConfiguration 

### ISSUE THREAD

**Issue by cResults** [Azure/azure-webjobs-sdk#1882]
We were using the JobHostConfiguration property as illustrated in the code snippet below.  We've accounted for the LoggerFactory by passing in ILoggerFactory via the constructor of the InjectExtension.

The remaining issue is how do we access TypeLocator?  ie context.**Config**.TypeLocator.GetTypes().

Thank you for an already amazing product that is continuously improving.

```
    public class InjectExtension: IExtensionConfigProvider
    {
        public void Initialize(ExtensionConfigContext context)
        {
            var rule = context.AddBindingRule<InjectAttribute>();

            rule.BindToInput<Anonymous>((attribute) => null);

            var dependencyConfig = InitializeContainer(context);
            if (dependencyConfig != null)
            {
                var serviceCollection = new ServiceCollection();
                dependencyConfig.RegisterServices(serviceCollection);

                var configuration = new ConfigurationBuilder()
                    .AddEnvironmentVariables()
                    .Build();
                serviceCollection.AddSingleton<IConfiguration>(configuration);

                var logger = context.**Config**.LoggerFactory.CreateLogger("Host.General");
                serviceCollection.AddSingleton(logger);

                var container = serviceCollection.BuildServiceProvider();
                rule.AddOpenConverter<Anonymous, OpenType>(typeof(InjectConverter<>), context.Config, container);
            }
        }

        private static IDependencyConfiguration InitializeContainer(ExtensionConfigContext context)
        {
            var configType = context.**Config**.TypeLocator.GetTypes()
                .Where(x => typeof(IDependencyConfiguration).IsAssignableFrom(x) && !x.IsInterface && !x.IsAbstract)
                .FirstOrDefault();

            IDependencyConfiguration configuration = null;
            if (configType != null)
            {
                var configInstance = Activator.CreateInstance(configType);
                configuration = (IDependencyConfiguration)configInstance;
            }
            return configuration;
        }
    }

```

**Comment by ielcoro** [comment]
@cResults Just use constructor injection, [looking at the code](https://github.com/Azure/azure-webjobs-sdk/blob/cc43252bc518a8425e8ada1be3cdf2feb2634ea7/src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsServiceCollectionExtensions.cs#L54) it's registered with DI as ITypeLocator interface (BTW, looking at that file you can tell what dependencies are available to you and how they are registered):

public class InjectExtension: IExtensionConfigProvider
    {
        private readonly ITypeLocator typeLocator;

        public InjectExtension(ITypeLocator typeLocator)
        {
            this.typeLocator = typeLocator;
        }
        public void Initialize(ExtensionConfigContext context)
        {
            ...
         }
   }

**Comment by cResults** [comment]
Perfect!  I have the azure-webjobs-sdk repo locally but had not yet found ITypeLocator.  Thank you.

**Comment by cResults** [comment]
ITypeLocator did not work as the Config.TypeLocator did.  However, I found a way that works for now; BindingProviderContext.Parameter.Member.DeclaringType.Assembly.GetExportedTypes()
