### ISSUE TITLE
Review 3.0 Public Surface Area

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1884]
Apply Obsolete as needed to new extensibility interfaces. E.g. to the new WebJobsStartup stuff added, new DI interfaces, etc. as appropriate.

Also consider what to do with Filters since the feature is not yet complete.

**Comment by paulbatum** [comment]
Resolved by  https://github.com/Azure/azure-webjobs-sdk/pull/1900
