### ISSUE TITLE
How to use Dependency Injection in webJobs 3.0.0-beta8

### ISSUE THREAD

**Issue by ioantoader** [Azure/azure-webjobs-sdk#1887]
I tried to use web jobs sdk version 3.0.0-beta8 Links to source but I don't know how o use Dependency Injection.
This is my main function:
        static async Task  Main(string[] args)
        {
            var typeLocator = new SamplesTypeLocator(
                            typeof(Functions.Z3ExportScheduler));

            var builder = new HostBuilder()                
                .ConfigureWebJobs(wjb =>
                {
                    wjb.UseHostId("ec08c5f41ae749c2a9bf02bff7a975de")
                    .AddWebJobsLogging()
                    .AddAzureStorageCoreServices()
                    .AddAzureStorage()
                    .AddTimers();
                    
                })
                .ConfigureAppConfiguration(cb=>
                {
                    cb.AddJsonFile("appsettings.json");
                    cb.AddEnvironmentVariables();
                    cb.AddCommandLine(args);
                    
                })
                .ConfigureServices((hostBuilderContext, services)=>
                {
                    services.AddScoped<Functions.Z3ExportScheduler, Functions.Z3ExportScheduler>();                                        
                    services.AddZ3Store(hostBuilderContext.Configuration);
                })
                .UseConsoleLifetime();
            var host = builder.Build();
            using (host)
            {
                await host.RunAsync();
            }
        }

and this is my web job.

  public class Z3ExportScheduler
    {
        public  Z3ExportScheduler(TaxMart.Z3Export.Common.Services.IZ3ExportRepository repo)
        {
        }

        public void Monitor([TimerTrigger("00:01:00", RunOnStartup =true)] TimerInfo timerInfo
            ,Microsoft.Extensions.Logging.ILogger logger)
        {            
            Console.WriteLine("Timer job fired!");
        }
    }

when I execute I got System.MissingMethodException: 'No parameterless constructor defined for this object.'

**Comment by kyleLogic** [comment]
I was able to register a new IJobActivator which used the service provider:

```
    public class WebJobActivator : IJobActivator
    {
        private readonly IServiceProvider _service;

        public WebJobActivator(IServiceProvider service)
        {
            _service = service;
        }

        public T CreateInstance<T>()
        {
            var service = _service.GetService<T>();
            return service;
        }
    }
```
And then register it in the ConfigureServices::
```
    var builder = new HostBuilder()
        .UseEnvironment("Development")
        .ConfigureWebJobs(b =>
        {
            b.UseHostId("ecad61-62cf-47f4-93b4-6efcded6")
            .AddWebJobsLogging() // Enables WebJobs v1 classic logging 
            .AddExecutionContextBinding();
        })
        .ConfigureAppConfiguration((builderContext, config) =>
        {
            config.AddDefaultOptions(builderContext.HostingEnvironment.EnvironmentName);
        })
        .ConfigureServices((context, services) =>
        {
            services.AddSingleton<IJobActivator>(new WebJobActivator(services.BuildServiceProvider()));
        })
        .UseConsoleLifetime();
````

**Comment by kyleLogic** [comment]
I got it from the sameple host [here](https://github.com/Azure/azure-webjobs-sdk/blob/dc489f46aab67a885428b27a4b3134b46d38ecd9/sample/SampleHost/Program.cs) which was only included due to [issue 1802](https://github.com/Azure/azure-webjobs-sdk/issues/1802). However, it looks like the issue is closed, so this can be removed as I've updated my post.

**Comment by GuidoNeele** [comment]
> What is the purpose of UseHostId ? At a glance I cant find what it's true purpose is....

Id is used in Azure storage container. See Azure Storage / Blob containers / azure-webhost-hosts / <guid>

**Comment by GuidoNeele** [comment]
@ioantoader Did the solution by @kyleLogic work for your issue? I've run into the same and have been looking for a solution for the last hour.
Thanks!

**Comment by GuidoNeele** [comment]
I can confirm registering the IJobActivator solves the issue.
For more info see https://github.com/Azure/azure-webjobs-sdk/issues/1915

**Comment by mathewc** [comment]
We'll be improving the DI story soon so you don't have to register an IJobActivator. See https://github.com/Azure/azure-webjobs-sdk/issues/1917.
