### ISSUE TITLE
What is the replacement for JobHostConfiguration().Queues config properties?

### ISSUE THREAD

**Issue by 1zias01** [Azure/azure-webjobs-sdk#1903]
Prior to Beta-8 

We could set MaxPollingInterval, BatchSize, etc from the JobHostConfiguration object.

ex. 
var configuration = new JobHostConfiguration();
  configuration.Queues.MaxPollingInterval = TimeSpan.FromSeconds(5);
            configuration.Queues.VisibilityTimeout = TimeSpan.FromMinutes(1);
            configuration.Queues.BatchSize = 10;
            configuration.Queues.MaxDequeueCount = 3;

But with the new HostBuilder() object, I am unable to locate properties for these.  How can I go about configuration this in beta-8

Everything else works so far.

Thanks

**Comment by vertical-codes** [comment]
Im also looking for a solution for this because i need to set the queuenameresolver? Did you find out how to set the Queueoptions?

**Comment by superjulius** [comment]
I have not tried it out yet but searching the source code, I think that you could do this in the appSettings file with a key like "AzureWebJobs:Extensions:Queues:BatchSize"

You can check the [unit test](https://github.com/Azure/azure-webjobs-sdk/blob/dab4163c3ab0fd99a93decbf63f96def806943bc/test/Microsoft.Azure.Webjobs.Extensions.Storage.UnitTests/Queues/StorageWebJobsBuilderExtensionsTests.cs) method **ConfigureOptions_AppliesValuesCorrectly_Queues**

Else try looking at the class QueueOptions

**Comment by superjulius** [comment]
@vertical-codes Below is how I managed to hook a QueueNameResolver with 3.0 simply using DI

Note that there is supposedly a **DefaultNameResolver** which should be registered with **ConfigureWebJobs** but it did not seem to work for me.

```C#
public static async Task Main(string[] args)
{
  var builder = new HostBuilder()
    .ConfigureWebJobs(b =>
    {
      b.AddAzureStorageCoreServices().AddAzureStorage();
    })
    .ConfigureAppConfiguration(b =>
    {
      ...
    })
    .ConfigureLogging((context, b) =>
    {
      ...
    });

  builder.ConfigureServices((hostBuilder, services) => {
    services.AddSingleton<INameResolver, QueueNameResolver>();
  });

  var host = builder.Build();
  using (host)
  {
    await host.RunAsync();
  }
}

public class QueueNameResolver : INameResolver
{
  private readonly IConfiguration _configuration;

  public QueueNameResolver(IConfiguration configuration)
  {
    _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
  }

  public string Resolve(string name)
  {
    // implement your logic
     return name;
  }
}
```

**Comment by 1zias01** [comment]
I did the same exact thing implementing INameResolver.  I stumbled upon it since I had it wired up in DI from before.  So I second that answer.  And thanks for the reply!

**Comment by mathewc** [comment]
Looks like you guys helped answer the question, thanks :) There is also an overload on AddAzureStorage that allows you to specify the configure delegate inline for QueuesOptions.

**Comment by ranouf** [comment]
I upgraded from 3.0.0-beta5 to 3.0.0.
@superjulius _QueuesOptions_ is not available, where did you find it?

**Comment by superjulius** [comment]
@ranouf This is available in Microsoft.Azure.WebJobs.Extensions.Storage nuget package

**Comment by Echarnus** [comment]
I installed the nuget package Microsoft.Azure.WebJobs.Extensions.Storage version v3.0.1, yet it complains it can't find the following extensionfunctions: 

`                        .AddAzureStorageCoreServices()
                        .AddAzureStorage()
                        .AddServiceBus()
                        .AddEventHubs();
                        .AddCommandLine(args);
                        .AddConsole();`
