### ISSUE TITLE
Method not found error with CosmosDB binding in Azure Functions

### ISSUE THREAD

**Issue by enthudev** [Azure/azure-webjobs-sdk#1911]
CosmosDB binding (Microsoft.Azure.WebJobs.Extensions.CosmosDB version 3.0.1-rc1)  is throwing a "Method not found" error in Azure functions when there is an explicit reference to Microsoft.Azure.DocumentDB.Core v2.0 package in one of the referenced projects in the solution. Getting the below error when trying to save a document in CosmosDB.

> System.Private.CoreLib: Exception while executing function: TestPost. Microsoft.Azure.WebJobs.Host: Error while handling parameter testModel after function returned:. Microsoft.Azure.WebJobs.Extensions.CosmosDB: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.Client.DocumentClient.UpsertDocumentAsync(System.Uri, System.Object, Microsoft.Azure.Documents.Client.RequestOptions, Boolean)'.

I downgraded the version v1.9.1 and the error is gone.

#### Repro steps

1. In Visual Studio create a new project using template Azure Function.

2. In the Function project add a nuger reference to the library "Microsoft.Azure.WebJobs.Extensions.CosmosDB" version 3.0.1-rc1.

3. To a function add a CosmosDB binding and write code to save a document in CosmosDb using the binding.

4. Add another Project using template Class Library (.NET Standard).

5. In the new project add a nuget reference for the library "Microsoft.Azure.DocumentDB.Core v2.0".

6. In the Function project add a project reference to the class library.

7. Run the Functions project.

8. Post a request to the function with CosmosDB binding and try to save the document.

9. You will see error in Func console.

#### Expected behavior

The Function should not throw any error and save the document in to the target collection.

#### Actual behavior

The Function is throwing the above error in the console and is not saving the document.

#### Known workarounds

In the Class Library project downgrade the version of Microsoft.Azure.DocumentDB.Core to 1.9.1.

**Comment by paulbatum** [comment]
Thanks for the report! We have already updated the 3.x cosmos extension to reference `Microsoft.Azure.DocumentDB.ChangeFeedProcessor 2.1.0` which in turn references `Microsoft.Azure.DocumentDB.Core 2.0.0`. The PR for this update is here: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/491 and you'll see this in the next release.

**Comment by paulbatum** [comment]
I should clarify this update I was referring to already absorbs the breaking changes that were made in `Microsoft.Azure.DocumentDB.Core 2.0.0`. So Function Apps that reference the next released version of the Cosmos extension will need to use `Microsoft.Azure.DocumentDB.Core 2.0.0` at a minimum.
