### ISSUE TITLE
Reconcile IJobActivator with DI

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#1917]
When we did the DI work, we didn't reconcile the existing IJobActivator interface with DI. There are patterns that can be used to bridge the gap (e.g. see https://github.com/Azure/azure-webjobs-sdk/issues/1915) however, registration of a custom IJobActivator instance shouldn't be needed. Instead our activation channel should be able to just use the IServiceProvider to dynamically get instances as needed.

**Comment by jnevins-gcm** [comment]
Is this (first class DI for functions themselves) this expected for part of initial v2 GA release?

**Comment by ggirard07** [comment]
@mathewc does the change mean having a static class to host functions is no longer the way to go?
Do we now need to pay attention to `Functions` object lifetime?

**Comment by bryansray** [comment]
This issue shows closed, but I'm not quite seeing if DI is still natively supported? Is there an example of how to do dependency injection that works? I can't seem to get it going.

**Comment by Zebusch** [comment]
Also can't get it to work. Trying the sample but the constructor for Functions is not being called (which in turn makes all services null when trying to call them from triggered method).

**Comment by Zebusch** [comment]
Also can't get it to work. Trying the sample but the constructor for Functions is not being called (which in turn makes all services null when trying to call them from triggered method).
