### ISSUE TITLE
VS 2017 nuget v3.0.0 pacakge

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-webjobs-sdk#1921]
The WebJobs.Extensions.Storage v3.0.0 package on nuget freeze VS 2017 when attempting to download/install package

**Comment by tjrobinson** [comment]
Which version of Visual Studio 2017 are you using? Can you paste the log messages before the point it freezes?

**Comment by grahamehorner** [comment]
@tjrobinson I'm using VS 2017 v15.8.4 and have now regressed the tools; which has restored the functionality and no longer freezing; looking at nuget stats 0 downloads of v3.0.0 seem a little odd, would have at least expected a few people ;)
