### ISSUE TITLE
Which ILogger should we use

### ISSUE THREAD

**Issue by forki** [Azure/azure-webjobs-sdk#1922]
![image](https://user-images.githubusercontent.com/57396/45816629-82e9fd80-bcdc-11e8-8ba6-f5cf7e464cb5.png)

TraceWriter seems to be obsolete now, but which ILogger should we use? There are multiple in the framework.

**Comment by grahamehorner** [comment]
the ILogger I'm using is the one from the Microsoft.Extensions.Logging namespace, this gets DI into the AzureFunction and I typically have the following (see below) at the end of every C# function.

```
> ExecutionContext ctx,
> IBinder binder,
> ILogger logger)
```


however; I'm not sure what that would be/result in when using F#

**Comment by mathewc** [comment]
Yes, use Microsoft.Extensions.Logging.ILogger

**Comment by forki** [comment]
The issue was meant as a hint for you guys to improve the error message ;-)

**Comment by davidebbo** [comment]
I agree, the obsolete message needs to be improved. Problem is that VS intellisense finds two ILogger classes to resolve to, and the one it proposes first is the wrong one (in `Microsoft.Build.Framework`). The message should include the namespace.

**Comment by mathewc** [comment]
Addressed via https://github.com/Azure/azure-webjobs-sdk/pull/1926
