### ISSUE TITLE
Looking for example for Web Jobs v3.0.0

### ISSUE THREAD

**Issue by aderderian** [Azure/azure-webjobs-sdk#1923]
Does anyone have a working example of webjobs using v3.0.0? Would like to see the new Program.cs with logging being injected and then a Functions.cs file. Trying to create a job using .net core 2.1. Thanks!

**Comment by Stolpe** [comment]
There is an updated sample in the SDK source code. Look at https://github.com/Azure/azure-webjobs-sdk/tree/dev/sample/SampleHost
