### ISSUE TITLE
No 3.0.0 nuget package for Microsoft.Azure.WebJobs.ServiceBus

### ISSUE THREAD

**Issue by tjrobinson** [Azure/azure-webjobs-sdk#1929]
Although `Microsoft.Azure.WebJobs` is now on `3.0.0`, `Microsoft.Azure.WebJobs.ServiceBus` is still on `3.0.0-beta8`. 

* https://www.nuget.org/packages/Microsoft.Azure.WebJobs/
* https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus/

**Comment by a-silva** [comment]
This one took me a while to figure out, but here you go:

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/
