### ISSUE TITLE
[EventHubTrigger] Log LeaseLostException and ReceiverDisconnectedException as warnings

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk#1947]
Issue reported https://github.com/Azure/Azure-Functions/issues/978 and https://github.com/Azure/Azure-Functions/issues/979

Exceptions Microsoft.ServiceBus.Messaging.LeaseLostException and  Microsoft.ServiceBus.Messaging.ReceiverDisconnectedException  are harmless but fill up user logs as errors.

See [what-is-causing-azure-event-hubs-receiverdisconnectedexception-leaselostexception](https://stackoverflow.com/questions/41496754/what-is-causing-azure-event-hubs-receiverdisconnectedexception-leaselostexceptio/41867611#41867611) and [is-there-a-recommanded-way-to-handle-microsoftservicebusmessagingreceiverdisconnectedexception](https://social.msdn.microsoft.com/Forums/azure/en-US/f89ade2f-c695-42e6-944b-6a744f081f90/is-there-a-recommanded-way-to-handle-microsoftservicebusmessagingreceiverdisconnectedexception?forum=servbus) for more details.

Need to investigate if there is a way these can be logged as warnings

**Comment by fgheysels** [comment]
What is the status on this ?
