### ISSUE TITLE
When will Microsoft.Azure.WebJobs.ServiceBus package release 3.0.0?

### ISSUE THREAD

**Issue by TianqiZhang** [Azure/azure-webjobs-sdk#1951]
right now Microsoft.Azure.WebJobs.ServiceBus still stays on beta8, while the other packages are all at 3.0.0. This is causing version mismatch at build time.

**Comment by xt0rted** [comment]
This package was renamed to [Microsoft.Azure.WebJobs.Extensions.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/)

**Comment by TianqiZhang** [comment]
@xt0rted thanks.
