### ISSUE TITLE
ConfigureWebJobs adds appsettings.json in wrong order

### ISSUE THREAD

**Issue by davidkarlsson** [Azure/azure-webjobs-sdk#1966]
#### Repro steps

If you add multiple appsettings.json files with `AddJsonFile()` in `ConfigureAppConfiguration` and you also use the `ConfigureWebJobs` method the order of the loaded appsettings.json files will be out of order because `ConfigureWebJobs` will add its own call to `AddJsonFile("appsettings.json")` which will be added after the appsetting files that were added in `ConfigureAppConfiguration`.

So if I try to use a setting from `ConfigureServices` from the `HostBuilderContext` parameter I expect the appsetting from the last appsettings file I added but it will instead always use the setting from appsettings.json because that's what `ConfigureWebJobs` added last.

#### Expected behavior

I expected that the settings from my appsettings files would be used in the order that added them in with `AddJsonFile()` with the file I added last having precedence. 

#### Actual behavior

If you try to use a setting from the context.Configuration variable that you get from `ConfigureServices`'s first parameter the setting returned will always be from appsettings.json even if I added another appsettings.json file after that one in `ConfigureAppConfiguration`. 

#### Known workarounds

As a workaround I think you could just not call `ConfigureWebJobs` at all and just configure the `JobHostService` without it because if I remove the call to `ConfigureWebJobs` the correct settings will be loaded in `ConfigureServices`.

#### Related information 

Provide any related information 

* I'm using Microsoft.Azure.WebJobs.* 3.0.0

**Comment by Skovvart** [comment]
Same issue reported here: https://github.com/Azure/azure-webjobs-sdk/issues/1931

**Comment by davidkarlsson** [comment]
Duplicate of #1931

**Comment by reginald81** [comment]
This Issue is STILL VALID !
