### ISSUE TITLE
JobHostConfiguration dropped?

### ISSUE THREAD

**Issue by Zordid** [Azure/azure-webjobs-sdk#1977]
I was using JobHostConfiguration to get a logger which is attached to my AppInsights.

This is my code snippet:

            return new JobHostConfiguration(configuration)
                .LoggerFactory
                .AddApplicationInsights(configuration["APPINSIGHTS_INSTRUMENTATIONKEY"], null)
                .AddConsole()
                .CreateLogger("MyWebJob");

Up until 3.0.0-beta5 this worked fine. Beta8 silently and without notice dropped the class `JobHostConfiguration`. I do find this question in closed issues - but the presented solutions look completely different and have nothing to do with getting a logger.

1) Why can you break compatibility in the middle of beta versions?
2) How can I get a logger now?

Thanks!

**Comment by Zordid** [comment]
The technique described here is now broken:
https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration

**Comment by mathewc** [comment]
Guys - please see my comments on duplicate issue here: https://github.com/Azure/azure-webjobs-sdk/issues/1871#issuecomment-432347037, where I answer these questions.
