### ISSUE TITLE
Adding Application Insights and set Instrumentation Key

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-webjobs-sdk#1979]
Hi,
I've built a webjobs using dotnet core (2.1) and all the latest packages. How can I set the instrumentation key to the loggerFactory? I've found many examples using loggerFactory.AddApplicationInsights(instrumentationKey, null).AddConsole(); but it seems that this signature is not valid anymore. What is the right way to achieve that?

**Comment by thdotnet** [comment]
Seems that not even the official doc has a sample about it: https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to

**Comment by mattwoberts** [comment]
Is this what you're looking for?

https://github.com/Azure/azure-webjobs-sdk/blob/dev/sample/SampleHost/Program.cs#L38

**Comment by fabiocav** [comment]
Indeed, the line above is where that is set in the SDK, by setting the option when adding application insights. Does that help?

**Comment by thdotnet** [comment]
Thanks!
