### ISSUE TITLE
TrackEvent with ILogger

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-webjobs-sdk#1994]
I'm using the `ILogger` interface and ApplicationInsights extensions to log webjob (3.0.0) operations to AppInsights.
However, I saw there is a `LogMetric` extension method, but no `LogEvent` (or `LogCustomEvent`).
Why is that? I believe it's a very useful part of AppInsights and should not be omitted?

Currently I worked around the issue by using the `TelemetryClient` directly, but this kind of breaks the whole generic logging principle.

PS: Also, as a side question: is there any way to remove the `prop__` prefix for custom properties?

**Comment by kasturi3k** [comment]
+1. We are interested in sending events to App Insights via ILogger interface too and avoid using TelemetryClient directly. Any recommendations would be helpful.

**Comment by RamunasAdamonis** [comment]
+1

**Comment by naxxxel** [comment]
I would also be interested in both
- being able to do something like `TrackEvent`
- having a way of removing `prop__` prefix for properties (at least for some of them)

**Comment by mpaul31** [comment]
+1

**Comment by fbertilsson** [comment]
+1

**Comment by NickSevens** [comment]
Not seeing anything happening here, so I assume this is off the table...
