### ISSUE TITLE
WebJob TimerTrigger - schedule from AppSettings ?

### ISSUE THREAD

**Issue by acds** [Azure/azure-webjobs-sdk#2007]
I'm using WebJobs 3.0 to be deployed with a WebApp not Functions

Given thin docs - How does one use AppSettings to configure the schedule of a TimerTrigger job ?
Seems anything related to INameResolver is old documentation?

More generally how does one access AppSetting from inside a function implementation?
When will there be more complete documentation on the WebJob 3.0 packages ?

**Comment by brettsam** [comment]
You can set the schedule string in `%%` and they'll be resolved as app settings. The docs for Functions (which use the same underlying code) shows a sample: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#configuration

>You can put the schedule expression in an app setting and set this property to the app setting name wrapped in % signs, as in this example: "%ScheduleAppSetting%".

**Comment by DeepakkSHAW** [comment]
Thanks, I have been looking something similar - suggestion worked for me,
Regards,
Deepak

**Comment by SashaSidorenko** [comment]
Hi There! I've tried to set schedule in app settings and this suggestion won't help.
So I have an appsetting
  {
    "name": "FGScheduleStandard",
    "value": "0 */5 * * * *",
    "slotSetting": false
  }

and I've got added it's as schedule in settings.job file

{
  "schedule": "%FGScheduleStandard%"
}

and all I have in https://{sitename}.scm.azurewebsites.net/api/triggeredwebjobs/{jobname}  is 

"settings":{"schedule":"%FGScheduleStandard%"}}

in portal it's looks like this

![image](https://user-images.githubusercontent.com/30925159/86588972-67291780-bf95-11ea-9d69-0881a7a6e484.png)

probably something has changed in syntax?
