### ISSUE TITLE
Using different name on connection string

### ISSUE THREAD

**Issue by pekspro** [Azure/azure-webjobs-sdk#2022]
I’m using Azure WebJobs SDK 3.0 and as I understand the connection string to the storage account must be named **Storage**. Is it possible to customize this? Or provide the connection string manually, just like when a connection to a database context is configured?

**Comment by chrisdunne** [comment]
You can create an appSettings.json file and add the following:

`{
  "ConnectionStrings": {
    "StorageNameHere": "ConnectionStringHere"
  }`

**Comment by pekspro** [comment]
@chrisdunne . I don’t get it :-) Let’s say the connection string I want to use is name **MyCustomStorage**. And this library always uses the connection string **Storage**. How could I solve that by just making changes to the config file?

**Comment by chrisdunne** [comment]
Set up the config file like the first message, then in your code use “%MyCustomStorage%”

**Comment by chrisdunne** [comment]
@pekspro like..

appSettings.json
`{ "ConnectionStrings": { "MyCustomStorage": "ConnectionStringHere" }`

queue trigger example:
`public static async Task TriggerFunction([QueueTrigger("%MyCustomStorage%")] CloudQueueMessage message, CancellationToken cancellationToken)
        {
//do stuff
}`

**Comment by pekspro** [comment]
Oh… Thanks @chrisdunne, that looks useful. I will try that :-)
