### ISSUE TITLE
Setting RetryPolicy for Table binding with IAsyncCollector

### ISSUE THREAD

**Issue by bragma** [Azure/azure-webjobs-sdk#2024]
Hi,
In a Function I am using IAsyncCollector interface with a runtime TableAttribute binding (via IBinder) since I need to write to multiple tables with variable names. While testing I've noticed in Application Insights a table batch operation failing with error 500. Apparently this didn't cause the function request to fail and I am not sure to what happened to that data. I am not using try/catch in the code writing to the IAsyncCollector so I expected to see an exception and a failure. Is it normal?
Also is it possible to set the RetryPolicy on the CloudTableClient created internally in the IAsyncCollector TableEntityWriter?

Thanks!

**Comment by fabiocav** [comment]
@bragma  This issue tracks bringing this capability back into the SDK: https://github.com/Azure/azure-webjobs-sdk/issues/1945

Closing this, but please follow the linked issue for updates.
