### ISSUE TITLE
error "Can't bind ErrorTriggerAttribute to type 'System.Diagnostics.TraceFilter'" occurs when use sendgrid to send an email

### ISSUE THREAD

**Issue by imeya** [Azure/azure-webjobs-sdk#2031]
I wanna use ErrorTrggier to monitor my webjobs, when some exception/error occurs in webjob, I want to use sendgrid to send an alert email to me.

I installed the Microsoft.Azure.WebJobs.Extensions(version 3.0.0-beta4) and Microsoft.Azure.WebJobs.Extensions.SendGrid(version 3.0.0-beta4).

The sample code as below:

in program.cs:
```
 static void Main()
        {
            var config = new JobHostConfiguration();
            config.DashboardConnectionString = "";
            config.StorageConnectionString = "connection string";

            if (config.IsDevelopment)
            {
                config.UseDevelopmentSettings();
            }
            config.UseCore();
            config.UseSendGrid();
            var host = new JobHost(config);
            // The following code ensures that the WebJob will be running continuously
            host.RunAndBlock();
        }
```

And in the Functions.cs:
```
public class Functions
    {
        
        public static void ProcessQueueMessage([QueueTrigger("queue")] string message, TextWriter log)
        {
            log.WriteLine(message);
        }

        public static void GlobalErrorMonitor(
            [ErrorTrigger("0:01:00", 1, Throttle = "0:10:00")]TraceFilter filter,
            [SendGrid(From = "xxx", To = "yyy")]SendGridMessage message)
        {
            message.Subject = "WebJobs Error Alert";
            message.PlainTextContent = "error occurs here in your webjobs!!!!";
        }
    }
```

But when execute it, the following error occurs:

![error-trigger](https://user-images.githubusercontent.com/25738099/49006266-ab421c80-f1a3-11e8-93f0-19cec5224ee9.JPG)

Could you please point me out what I'm missing? Or can you give me an example how to send email in webjobs(and point out that which version of some nuget packages I should use)?

Thank you.

**Comment by fabiocav** [comment]
@imeya the Error Trigger is not supported in 3.0. If you need that feature, using 2.x is the only option at the moment.

**Comment by imeya** [comment]
@fabiocav but if I use 2.x, then there is no `config.UseCore()`; method.
