### ISSUE TITLE
App Insights integration - new TelemetryClient() should match the telemetry client configured through  loggingBuilder.AddApplicationInsights(... 

### ISSUE THREAD

**Issue by stephenschwan** [Azure/azure-webjobs-sdk#2032]
With the new webjobs sdk working more like the buildup of asp.net core, I would expect the App Insights integration to behave the same.  While using the extensions to setup App Insights through normal buildup, in asp.net core, new TelemetryClient() is the same as the TelemetryClient registered in the service collection.

Provide the steps required to reproduce the problem

1. Register App Insights through ILoggingBuilder extensions

#### Expected behavior

In web job function, a call to new TelemetryClient() should match the TelemetryClient registered in the service collection.

#### Actual behavior

new TelemetryClient() does not match, though, it does have the instrumentation key set

#### Known workarounds
Just resolve TelemetryClient from service collection - but I would think we would want the experience to be the same between asp.net core and web jobs logger buildup extensions

#### Related information 
Latest webjobs SDK -3.0.2, latest asp.net core SDK

**Comment by johnkwaters** [comment]
I am in a similar scenario. I add a TelemetryClient Singleton in DI setup:

`services.AddSingleton<TelemetryClient>();`

Then, where I need one I resolve or inject it:

`        public async Task EndTripsTimerAsync(
            [TimerTrigger("0 0 */2 * * *", RunOnStartup = true)]
            TimerInfo timerInfo,
            TextWriter log)
        {
            using (var scope = _serviceScopeFactory.CreateScope())
            {
                var ttp = scope.ServiceProvider.GetRequiredService<ITimedTaskProcessor>();
                var tc = scope.ServiceProvider.GetRequiredService<TelemetryClient>();
                try
                {
                    await ttp.EndTripsAsync();
                }
                catch (Exception e)
                {
                    tc.TrackException(e);
                }
            }
        }`

DI doesn't work that well yet. Is this the way to do it? In AspNetCore, is that Singleton added when you call the extension method

`.AddApplicationInsightsTelemetry()`

**Comment by johnkwaters** [comment]
That was my first approach. I do add App Insights as above in the builder, but when I requested it, got an exception, which went away when I added it manually to the services. Do you have an example of how to resolve or inject a TelemetryClient in code that works without manually adding TelemetryClient Singleton as above?

**Comment by johnkwaters** [comment]
I also noticed the undocumented "UseWebJobsStartup" above ... looks like the pattern for AspNetCore. Is there a sample of how to properly structure this and what goes where?

**Comment by stephenschwan** [comment]
If you want to use startup, just create a class implementing IWebJobsStartup.  This would replace the .ConfigureServices in your sample above.

**Comment by stephenschwan** [comment]
You would have to just new up a new configurationbuilder.

I am closing this now and going to start a new issue on metrics - working through the buildup - though not perfect and congruent with asp.netcore, it is working.

**Comment by gonace** [comment]
@stephenschwan Bumping this since there are no examples or information found for how to use `UseWebJobsStartup`, would be great if someone (that knows) can provide a working (simple) example.

I've been trying to figure out how to use but without any success, I've created a class implementing `IWebJobsStartup` but the `ConfigureServices` method is never called.
