### ISSUE TITLE
Investigate storage connection issues in Functions 2.0.12210

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#2044]
From @tekking [here](https://github.com/Azure/azure-storage-net/issues/580#issuecomment-444010750): 

> Thanks for the quick response. We just restarted our functions to update to this new version, will be keeping an eye on them to see if this fixes our problem.
> 
> Update: First tests of our function have not thrown the socket exhaustion error yet, but it appears our function still creates quite a large amount of connections, the diagnostic tool shows a peak of 3826 connections (http://puu.sh/Ccbi8/9954ece895.png).

**Comment by brettsam** [comment]
@tekking -- Is that chart from the diagnostics in the portal? Can you share exactly where you see it so I can repro?

Also, can you share your site name ([privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately), if you'd like). I can take a look at the metrics on our end. 

Our runtime will monitor its connections and shut down with the "Host thresholds exceeded" message if you hit 80% of the threshold, which is 300 today. If you're not seeing that, then I'm curious whether the chart is just incorrect. I can investigate either way.

**Comment by tekking** [comment]
I reached that chart by going to the diagnose and solve problems link on our function, then clicking the banner on top to return to the old experience and then selecting the TCP connections option.

The function is currently running on a service plan (S2), rather than a consumption plan. I'm not sure if that might be why our number of connections can get that high?

I've also sent you an e-mail with the url of our function.

**Comment by brettsam** [comment]
Oh -- running on an App Service Plan shouldn't ever see any connection limits. Those restrictions only apply to Consumption, which runs in a restricted sandbox. So that chart makes sense.

If you have a chance to run this on a Consumption plan, can you let us know what the results look like? I'll close this issue now -- but feel free to re-open.
