### ISSUE TITLE
[App Insights] "Executed..." logs do not contain correct operation id

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#2057]
See https://social.msdn.microsoft.com/Forums/en-US/c6e1c384-068a-4175-a272-29b4f8854ad4/function-app-having-invocation-id-in-app-insight-with-out-the-operationid?forum=AzureFunctions.

I believe this is an easy fix -- we're marking the function as complete (as far as App Insights is concerned) and *then* logging this message. Swap those two lines and things should work.

In v2.x, we explicitly set this: https://github.com/Azure/azure-webjobs-sdk/blob/v2.x/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobsTelemetryInitializer.cs#L38.

In v3.x, we let Application Insights track this automatically. Since the log isn't happening in the scope of the function, it is missing that id.

**Comment by rkbalu** [comment]
@brettsam Please confirm if this is fixed because I am still seeing same sort of behavior.  Thanks.

**Comment by brettsam** [comment]
It's fixed in the repo, but we haven't had a release since the fix was merged (we pause releases over the holidays). It'll be in the next release.

**Comment by rkbalu** [comment]
Thanks for the update @brettsam.

**Comment by frellis** [comment]
@brettsam is the next release mid January?

**Comment by brettsam** [comment]
Yes, likely starting soon and takes a few days to roll out across all regions.
