### ISSUE TITLE
Unable to execute [NoAutomaticTrigger] method

### ISSUE THREAD

**Issue by cbrianball** [Azure/azure-webjobs-sdk#2095]
Please provide a succinct description of the issue.

I use `HostBuilder` to build an `IHost`. I then call `RunAsync` on `IHost`. Methods decorated with `NoAutomaticTrigger` are discovered, but not executed.

I don't expect them to run automatically, but I don't see a way via `IHost` to invoke them. Previous to v3.0 of the SDK, I would invoke the `Call` method of `JobHostConfiguration`.

I can't find any samples/documentations that use `NoAutomaticTrigger`.

I am using Microsoft.Azure.WebJobs.Host version 3.0.3

**Comment by fabiocav** [comment]
The pattern here would require you to use an `IJobHost` that you can retrieve from the host services. You can see an example of that here: https://github.com/Azure/azure-webjobs-sdk/blob/3eb3dc7a5d1d6e51c6edad4cdcaa1d6b553084e4/test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs#L251-L254
