### ISSUE TITLE
64 bit webjobs deployed to Azure App Service are not working

### ISSUE THREAD

**Issue by ffMathy** [Azure/azure-webjobs-sdk#2096]
I get the following error in the logs:

> System.BadImageFormatException: Could not load file or assembly 'Easywork.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

I am compiling as AnyCPU, but with the `dotnet.exe` 64 bit version.

The app service is running just fine on x64, but not the webjob.

Is this supported?

**Comment by fabiocav** [comment]
64-bit is supported, but it does look like you have a dependency that has an incorrect bitness. Do you have a full stack? Do you see an issue if you deploy a simple WebJob without your dependencies? Isolating and inspecting your dependencies would help identify the issue.

Also, do you have a 64-bit specific dependency? Or can you switch the app to 32-bit?
