### ISSUE TITLE
ConfigureWebJobs should have an overload with a delegate that accepts the HostBuilderContext

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-webjobs-sdk#2116]
#### Problem

If I use `ConfigureWebJobs` to add service bus:

```csharp
                .ConfigureWebJobs(builder =>
                {
                    builder.AddServiceBus(o =>
                    {
                        var configuration = ????
                        o.ConnectionString = configuration["ServiceBus:ConnectionString"];
                    });
                })
```

I need to access the configuration, but it's not available. There should be an overload that takes a `Action<HostBuilderContext, IWebJobsBuilder>`, so that we can access the configuration via the `HostBuilderContext` when configuring webjobs. Most other host builder methods (`ConfigureAppConfiguration`, `ConfigureServices`, `ConfigureLogging`...) have an overload like this.

#### Known workarounds

For now, I just made my own version of `ConfigureWebJobs`:

```csharp
    public static class WebJobsHostBuilderExtensions
    {
        public static IHostBuilder ConfigureWebJobs(this IHostBuilder builder, Action<HostBuilderContext, IWebJobsBuilder> configure)
        {
            return builder.ConfigureWebJobs(configure, o => { });
        }

        public static IHostBuilder ConfigureWebJobs(this IHostBuilder builder, Action<HostBuilderContext, IWebJobsBuilder> configure, Action<JobHostOptions> configureOptions)
        {
            builder.ConfigureServices((context, services) =>
            {
                IWebJobsBuilder webJobsBuilder = services.AddWebJobs(configureOptions);
                configure(context, webJobsBuilder);

                services.TryAddEnumerable(ServiceDescriptor.Singleton<IHostedService, JobHostService>());
            });

            return builder;
        }
    }
```

(it also solves #1931 by removing the extra configuration sources)

**Comment by fabiocav** [comment]
Looks like you've solved the problem! :)

Would you like to send a PR with this?

**Comment by thomaslevesque** [comment]
@fabiocav I already did ;)
#2117

I didn't include the change related to #1931, though, as it should probably be handled separately.

**Comment by DarkCompiled** [comment]
Beautiful, thank you... I was getting IConfiguration from the registered Services, a nasty "hack".
Now it is clean. 👍
