### ISSUE TITLE
VisibilityTimeout does not affect NextVisibleTime

### ISSUE THREAD

**Issue by jjasloot** [Azure/azure-webjobs-sdk#2158]
I have a webjob with queuetrigger running a short function that is somewhat time-critical.  If an execution of a queuemessage fails I want the webjob to try again quickly. To do this I set the visibilityTimeout to 60 seconds.  When logging the NextVisibleTime I however see that it is 10 minutes later, instead of 1 minute as I expected.

#### Repro steps
1. Create a webjob as per https://docs.microsoft.com/nl-nl/azure/app-service/webjobs-sdk-get-started

2. Set visibility timeout:
```c#
  builder.ConfigureWebJobs(b =>
            {
                b.AddAzureStorageCoreServices();
                b.AddAzureStorage(a => a.VisibilityTimeout = TimeSpan.FromSeconds(30));
           });
```
and/or
```c#
            builder.ConfigureServices((context, services) =>
            {
                services.Configure<QueuesOptions>(options =>
                {
                    options.MaxPollingInterval = TimeSpan.FromSeconds(2);
                    options.VisibilityTimeout = TimeSpan.FromSeconds(40);
                });
            });
```

3. Add logging for the NextVisibleTime in the function:
``` c#
public static void ProcessQueueMessage([QueueTrigger("queue")] string message, DateTimeOffset NextVisibleTime, ILogger logger)
        {
            logger.LogInformation(message);
            logger.LogInformation("Now:" + DateTime.UtcNow + " NextVisibleTime: " + NextVisibleTime.ToString());
        }
```

4. Add a message to the queue
5. Observe that the NextVisibleTime is 10 minutes later than now.

Please see the repo here: https://github.com/jjasloot/QueueVisibilityTimeoutPOC

#### Expected behavior

I expect the NextVisibleTime of a message to be either 30 or 40 seconds after now, as per my setting for VisibilityTimeout.

#### Actual behavior

The NextVisibleTime is 10 minutes (the default) later than now.

#### Known workarounds
None

#### Related information 
Packages:
* Microsoft.Azure.WebJobs 3.0.5
* Microsoft.Azure.WebJobs.Extensions 3.0.2
* Microsoft.Azure.WebJobs.Extensions.Storage 3.0.4
* Microsoft.Azure.WebJobs.Host.Storage 3.0.5

Source: https://github.com/jjasloot/QueueVisibilityTimeoutPOC

Issue first created in [extensions/issues/560](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/560), moved here as QueueTrigger seems to live here.

**Comment by wboevink** [comment]
We are experiencing the exact same issue.

**Comment by ErikAndreas** [comment]
somewhat related? I set visibilityTimeout in host.json to 5 secs and consume message in queue trigger function and intentionally throw exception to have it "returned" to queue (just for testing purposes)
[2019-04-15 17:41:55] consumed  with next visible 2019-04-15 17:51:55 +00:00, ID 77063412-a30b-4946-9f33-7ff366b4e261
(throwing exception)
[2019-04-15 17:42:01] consumed with next visible 2019-04-15 17:52:01 +00:00, ID 77063412-a30b-4946-9f33-7ff366b4e261

Seems visibiltyTimout works as expected but value on NextVisibleTime is offset +10 mins?

**Comment by jjasloot** [comment]
That seems related indeed. However, in our case the host just disappears, no exception is thrown. In that case the VisibilityTimeout does seem to revert to the default of 10 minutes.

**Comment by ErikAndreas** [comment]
"host disappears"? VisibilityTimout default should be 0 (v2 https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#hostjson-settings). The 10 mins are, to my understanding, not right and NextVisibleTime is out of sync with VisibilityTimout.?

**Comment by jjasloot** [comment]
Yea, we observe in our application insights logging that the execution logs some of the steps and then the logging just stops, no exception and no finished message.

In the change in the associated PR Azure/azure-webjobs-sdk#2172 you can see that the QueueListener did indeed have a default VisiblityTimeout of 10 minutes. The QueueListener didn't read that value from its settings but always used the default of 10 minutes.

**Comment by andrew-vandenbrink** [comment]
Same issue here

**Comment by andrew-vandenbrink** [comment]
I think we all have wrong idea about visibilityTimeout on host.json
visibilityTimeout in this case is _time before the message will be retried_
https://github.com/Azure/azure-webjobs-sdk/issues/844

> I have a webjob with queuetrigger running a short function that is somewhat time-critical. If an execution of a queuemessage fails I want the webjob to try again quickly.

So @jjasloot, your visibility timeout should be "00:00:00"

Again, its different with `queue.GetMessageAsync(TimeSpan.FromMinutes(visibilityTimeout), null, null);`

The 10 minutes is being used to keep updating the message to stay invisible during duration of execution.

On my case, what I'm looking is called "functionTimeout" (defaulted to 30 minutes)

**Comment by wouter-b** [comment]
> So @jjasloot, your visibility timeout should be "00:00:00"

It doesn't matter as long as the options value is being used. Now it's ignoring the options value and using a hardcoded 10 minutes. PR Azure/azure-webjobs-sdk#2172 resolves this bug.

**Comment by mathewc** [comment]
It's by design that the "initial" visibility is different from the VisibilityTimeout that we allow you to configure. The feedback I believe is that you want the former to be customizable. I've logged a new issue https://github.com/Azure/azure-sdk-for-net/issues/32635 for that and will close this one.
