### ISSUE TITLE
Update EventHubs to use Microsoft.Azure.EventHubs.Processor 3.0

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#2168]
https://www.nuget.org/packages/Microsoft.Azure.EventHubs.Processor is now up to 3.0. We should move the EventHubs extension forward.

**Comment by brettsam** [comment]
@jeffhollan / @fabiocav - FYI. Had a customer request to move forward for perf improvements.

**Comment by jeffhollan** [comment]
Thanks - have an issue for this already as well https://github.com/Azure/azure-webjobs-sdk/issues/2155.  May be worth bumping up to P2?

**Comment by jeffhollan** [comment]
Closing for dupe if that's ok
