### ISSUE TITLE
Long Running Loop Function / Job

### ISSUE THREAD

**Issue by essmd** [Azure/azure-webjobs-sdk#2175]
Hi,

We are using Azure Service Bus with multiple topics. In an Azure SQL Database there is a table containing some pair of values (e.g.: `A-A` and `A-B` and so on). Now we need to start an Azure Service Bus Listener for every topic (=every value pair, one for `A-A`, another for `A-B` etc.). This is required to get max performance. Since the pairs are dynamic, we can not use the ServiceBusTrigger and to get more performance (parallel processing of pairs) using a single topic for all pairs is not possible.

Now we can create a simple console application, get the "pairs" from the database, and start service bus listener manually for every pair. Deploy to azure and run as continous job.
But since the graceful shutdown is not that easy, we would prefer to use the Azure WebJob SDK to accomplish the same with graceful shutdown support.

Is there any way to get the CancellationToken (Shutdown/Stop) from the IHost / IJobHost? This way we can just spawn the listener and stop them and those execution/processing on IsCancellationRequested etc. There is also an overload for the `await host.RunAsync();` using a CancellationToken. Are there any issues by providing a custom CancellationToken here, like no longer working graceful shutdown caused by the custom cancellation token?

Any other or better idea?

Thank you very much in advance!

**Comment by corneliutusnea** [comment]
@essmd I'm using the following code to monitor when the WebJob shuts down and seems to be working properly:
```
private WaitHandle _shutDownHandle;
...
_shutDownWatcher = new WebJobsShutdownWatcher();
_shutDownHandle = _shutDownWatcher.Token.WaitHandle;

//You can then do
_shutDownHandle.WaitOne(); // to wait on a background thread until the handle is signalled
```

When the handle is signalled basically your process started the shut down.
You do have enough time to disconnect from the ServiceBus.

**Comment by brettsam** [comment]
@essmd -- the suggested answer by @corneliutusnea should work.

How are you spawning all of your listeners? Are they all in a manual trigger? If so, you also should be able to request a CancellationToken as part of the function signature, which should be signaled when the host is shutting down. 

I'm going to close this as it's pretty old at this point, but please let me know if you need more guidance. Thanks!

**Comment by essmd** [comment]
@brettsam
i would like to do something like the following. The code is just dummy code to show how i expect or think about it to look like. I dont know the exact type names currently and i am only on mobile phone - so sorry for that, and i hope the idea for my expected behavior and process is visible anyway. 

And sorry that i did not respond/react earlier. The project has been suspended then and i forgot about the issue. But we will continue with this project and issue in about 1-2 months. 


**Simplified**
- Start Program
- Get some names from db
- Creat a topic for each name and start listening/processing messages on those in the background (parallel)
- Wait for a shutdown (restart/deploy/stop) in azure while processing
- Stop listening and processing if signal occours
- Program (clean) exit


**Code Idea**
```csharp
class Program
{
    async Task Main()
    {
        // get some names (strings) from the db first
        string[] typeNames = await GetTypeNamesFromDbAsync();
        var busService = GetServiceBusService();
        var busListeners = new List<Listener>();

        // create (if neccessary) a topic for each name and start listening on it
        foreach (var name in typeNames)
        {
            await busService.CreateTopicIfNotExistAsync(name);
            var listener = await busService.StartListenToTopicAsync(name);
            busListeners.Add(listener);
        }

        // now there is a listener for every „name“ (=1 topic and processor per name)
        // new messages on topics are processed paralell

        // during processing, wait for s shutdown signal (stop, restart, deployment, ...)
        // to stop the active processing and listening
        await shutdownHelper.WaitForShutdownOrRestartInAzureAsync();

        foreach (var listener in busListeners)
        {
            await listener.StopAsync();
        }

         // listeners are all stopped now, safe & clean shutdown possible
    }
}
```
