### ISSUE TITLE
Make sure that you are setting a connection string named AzureWebJobsDashboard

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk#2179]
`WebJobsDashboard` is being deprecated.
Nowhere in my code I've configured it, yet get the following errors when reviewring webjob execution in Kudu SCM portal:

<details><summary>Make sure that you are setting a connection string named `AzureWebJobsDashboard`</summary>
 in your Microsoft Azure Website configuration by using the following format `DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY` pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.

Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.
</details>

and

<details><summary>The configuration is not properly set for the Microsoft Azure WebJobs Dashboard.</summary>
In your Microsoft Azure Website configuration you must set a connection string named `AzureWebJobsDashboard` by using the following format `DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY` pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored. 

Please visit the article [about configuring connection strings](http://go.microsoft.com/fwlink/?LinkID=320957) for more information on how you can configure connection strings in your Microsoft Azure Website.
</details>

I've tried to set up `ConnectionStrings:AzureWebJobsDashboard` with the connection string, but that doesn't work.

1. Why is `AzureWebJobsDashboard` required when no call to `.AddDashboardLogging()` is made?
2. Where's can I find documentation on what needs to take place?

#### Repro steps

```c#
public static IHostBuilder ConfigureConcierge(this IHostBuilder hostBuilder)
        {
            hostBuilder.ConfigureHostConfiguration(builder =>
            {
                builder.SetBasePath(Directory.GetCurrentDirectory());
                builder.AddEnvironmentVariables(prefix: "ASPNETCORE_");
                builder.AddEnvironmentVariables();
            });

            hostBuilder.ConfigureAppConfiguration((context, builder) =>
            {
                builder.SetBasePath(Directory.GetCurrentDirectory());
                builder.AddJsonFile($"appsettings.{context.HostingEnvironment.EnvironmentName.ToLowerInvariant()}.json", optional: true);

                var configuration = builder.Build();

                var appConfigurationConnectionString = configuration.GetConnectionString("AppConfigurationConnectionString");
                builder.AddAzureAppConfiguration(o => o.Connect(appConfigurationConnectionString)
                    .Use("*", labelFilter: context.HostingEnvironment.EnvironmentName));
            });

            hostBuilder.ConfigureWebJobs(builder =>
            {
                builder.AddAzureStorageCoreServices();
                builder.AddAzureStorage();
                builder.AddTimers();
            });

            hostBuilder.ConfigureLogging((context, builder) => { builder.AddConsole(); });

            hostBuilder.ConfigureServices((context, services) =>
            {
                services.AddSingleton<ITypeLocator>(new FunctionsLocator());
                services.AddScoped<PoisonErrorSlackNotifierFunction>();
                services.AddScoped<ErrorQueueToBlobFunction>();
                services.AddHttpClient();
            });

            return hostBuilder;
        }
```

#### Expected behavior

Expected to work.

#### Actual behavior

Doesn't work with the warning/errors above.

#### Related information 

Provide any related information 

Microsoft.Azure.WebJobs: 3.0.6
Microsoft.Azure.WebJobs.Extensions: 3.0.1
Microsoft.Azure.WebJobs.Extensions.Storage: 3.0.5

**Comment by SeanFeldman** [comment]
More information: this looks like an issue with _any_ WebJobs 3.x webjob deployed under WebApp. The warning/error is showing up regardless if `.AddDashboardLogging()` is used or not.

![image](https://user-images.githubusercontent.com/1309622/56528557-9f694500-650c-11e9-92b4-1a6540ce5b2e.png)

**Comment by SeanFeldman** [comment]
Also, if a webjob based on 3.x SDK happens to have any Functions, those are executed, but their execution is no longer available for review in Kudu. The log output is truncated 
![image](https://user-images.githubusercontent.com/1309622/56528699-d7708800-650c-11e9-8b71-262732833d1b.png)

And trying to switch to the Functions dashboard (`webapp-scm.azurewebsites.net>/#/functions`) is not going to show anything
![image](https://user-images.githubusercontent.com/1309622/56528814-04bd3600-650d-11e9-957a-66f0bd8684d7.png)

**Comment by paulbatum** [comment]
The fundamental problem that you're running into is that the webjobs dashboard UX cannot be be used for webjobs 3.x onwards and functions 2.x onwards. It has been replaced with [App Insights integration](https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration#webjobs-version-3x). We are no longer making any engineering investments into this UX.

I filed the following tracking issue for us to add the warning:
https://github.com/Azure/azure-webjobs-sdk/issues/2180

@SeanFeldman Assuming we complete the above work item, do you think there is anything else that needs an answer or followup here?

**Comment by SeanFeldman** [comment]
Thank you @paulbatum. #2180 is good to address this one.
Regarding Application Insights - I had a poor experience hooking an existing WebJob to an existing AI, but will review the [doco you've linked](https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration#webjobs-version-3x) and find out what did I do wrong.

**Comment by paulbatum** [comment]
@SeanFeldman BTW it looks like some of the app insights content has been migrated to the official docs site - also take a look at this content:
https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#add-application-insights-logging

**Comment by SeanFeldman** [comment]
Thank you! Updated documentation is music to my ears.
