### ISSUE TITLE
application insights logging - observations

### ISSUE THREAD

**Issue by funkycoding** [Azure/azure-webjobs-sdk#2192]
Hello,

I'm doing some finetuning for our application insights logging within webjobs and while testing and trying things out, i found a few things that i don't totally understand.

### **Events, requests, and remote dependencies are not logged when LogLevel is set to Warning or higher**

Using the following setup:

```
{
  "ApplicationInsights": {
    "InstrumentationKey": "--"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  }
}
```

```
public class ServiceBusWebJob
{
    private readonly ILogger<ServiceBusWebJob> _logger;
    private readonly TelemetryClient _telemetryClient;

    public ServiceBusWebJob(ILogger<ServiceBusWebJob> logger, TelemetryClient telemetryClient)
    {
        _logger = logger;
        _telemetryClient = telemetryClient;
    }

    public void ReceiveMessage([ServiceBusTrigger("test", "test")] Message message)
    {
        _logger.LogInformation("information");
        _logger.LogWarning("warning");
        _logger.LogCritical("critical");

        _telemetryClient.TrackEvent("test event", new Dictionary<string, string> { { "nice", "yes" } });
    }
}
```

I receive the following information in Application Insights:
![afbeelding](https://user-images.githubusercontent.com/307410/56899216-309f6500-6a93-11e9-9f86-351c89fd6b18.png)

However, setting the `LogLevel` in `appsettings.json` to `Warning`, i receive the following information in Application Insights:
![afbeelding](https://user-images.githubusercontent.com/307410/56899518-eb2f6780-6a93-11e9-9084-ad0bd971fb2f.png)

I would expect that:
- the request (e.g. the webjob function) is logged and my logged values are scoped to the request
- that my custom event would be visisble and scoped to the request

Are my expectations wrong?

### **Missing ASB as a dependency call in Application Insights**
![afbeelding](https://user-images.githubusercontent.com/307410/56899702-6a24a000-6a94-11e9-88bb-6e6d83cfd8a6.png)

Different example, but after pulling the library locally and doing some modifications i can see the ASB as a dependency call, which i would expect. I miss this when using the 'default' application insights logging. Is this expected?

@lmolkova - pulling you in here, as i know you did quite some work in this area

Regards,
Mark

**Comment by brettsam** [comment]
For the filtering:
It's behaving as-designed. Those logs are written out as "Information" level, so you're effectively turning them off by saying you only want "Warning". These docs are for Functions, but the same applies for WebJobs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#category-hostresults. Function results are logged with the "Host.Results" category and at the "Information" level. You can explicitly allow this category through the filter (you can leave default as "Warning" and set `"Host.Results": "Information"`), which may be what you'd like to see.

For the SB dependency:
What did you do to get that dependency to show up? What version of WebJobs are you using? I *think* this should show up by default...

**Comment by brettsam** [comment]
This is pretty stale so closing. Please re-open if you have more questions. Thanks!
