### ISSUE TITLE
AppInsight - Custom Dependency Tracking not correlating correctly to the InvocationId

### ISSUE THREAD

**Issue by rkbalu** [Azure/azure-webjobs-sdk#2201]
We are using Function app V2 with tracking additional custom Dependency using Microsoft.ApplicationInsights 2.8.1 SDK. We are using the TrackDependency method to track it. The custom dependency correlated to the Function InvocationId nicely until early April'19 and now it seems that correlation broken.

#### Repro steps

1. Except the tracking custom dependency, all other tracking is happening with default setting.
2. We do not have any configuration added in host.json file
3. We create a object for TelemetryClient and calling the method TrackDependency.
Ex: 
telemetryClient.TrackDependency("EventHub", "BetSettlement", "outstream", settlementStartDateTime, settlementTimer.Elapsed, settlementIsSucess);

#### Expected behavior or behavior early April

**Request, Traces and Dependency are correlated nicely under the one operationId/invocationid. Please see below:**

![image](https://user-images.githubusercontent.com/33522349/57443572-473d7d00-7246-11e9-9471-ef2292924335.png)

#### Actual behavior or current behavior

However, now few changes i have noticed such as 

1) correlation not happening correctly and infact the custom dependency has different parent id. See below:

![image](https://user-images.githubusercontent.com/33522349/57443726-a3080600-7246-11e9-9216-d45e6dd5df8a.png)

2) some time invocationId linked to the request, sometime does not:
has request telemetry:
![image](https://user-images.githubusercontent.com/33522349/57465346-54726000-7276-11e9-87da-fb93da387ce4.png)

does not have a request telemetry:
![image](https://user-images.githubusercontent.com/33522349/57465393-6fdd6b00-7276-11e9-9e09-3297ebaf6b1b.png)

I'm really not sure if this is an issue within the appinsight behavior itself or something has changed which i need to change my function app to get it correct.

Any help on this would be much appreciated.

#### Known workarounds

Not sure what to fill in this section.

#### Related information 

Provide any related information 

Function app v2
VS 2019
nuget version:
Microsoft.ApplicationInsights - 2.8.1

**Comment by brettsam** [comment]
/cc @lmolkova to help look at this one.

@rkbalu -- what kind of trigger is FundGame using?

The issues seem to correspond to when we turned on our auto-http tracking. This looks similar to https://github.com/Azure/azure-functions-host/issues/4389 (fix coming soon), but I want to make sure it's the same root cause.

**Comment by rkbalu** [comment]
@brettsam,  FundGame is an Eventhub Trigger binding. but note that the app this function deployed to has a timer trigger function too. Hope this helps. I have even noticed the  behavior mentioned the ticket https://github.com/Azure/azure-functions-host/issues/4389

**Comment by brettsam** [comment]
Thanks @rkbalu. I wonder if EventHubs has the same problems as Timers. I'll need to give it a try. I'm hopeful that the fix for the other issue with take care of this for you as well. I'll set some time aside to try to repro and verify.

**Comment by rkbalu** [comment]
@brettsam also just wondering does this issue cause a spike in cpu as we noticed it quite recently. any help on this one would be much appreciated.

**Comment by lmolkova** [comment]
@rkbalu 

> correlation not happening correctly and infact the custom dependency has different parent id. See below

could you please share how you create TelemteryClient and TelemetryConfiguration to manually track your dependencies?

> some time invocationId linked to the request, sometime does not:
has request telemetry:

this is definitely a bug. Do you know if those requests are from different triggers or it is the same trigger with and without invocation Id? Also, can you check if there is a request  that just didn't get invocation Id (but it should have correct operationId) or the request is missing at all?

**Comment by rkbalu** [comment]
@lmolkova 

> could you please share how you create TelemteryClient and TelemetryConfiguration to manually track your dependencies?

> 

`var cloudRoleName = System.Environment.GetEnvironmentVariable("CloudRoleName");
var telemetryClient = new TelemetryClient();
telemetryClient.Context.Cloud.RoleName = cloudRoleName;
`

BTW telemetryClient is singleton. and additional setting in host.json file.

> this is definitely a bug. Do you know if those requests are from different triggers or it is the same trigger with and without invocation Id? Also, can you check if there is a request that just didn't get invocation Id (but it should have correct operationId) or the request is missing at all?

> 

We have 2 and only Eventhub trigger function, and i can confirm the pattern exists in both the function eventhub trigger. 

I think when there is a request trace mostly correlation is correct. when request trace missing, the other trace/dependency traces are correlated to some random operationid. quite recently there is lot if gap in the request telemetry, some time no request for about an hour as well. Please refer the screenshot below:

![image](https://user-images.githubusercontent.com/33522349/58287200-54ab4900-7da8-11e9-9784-793f34be24b5.png)

**Comment by lmolkova** [comment]
Thanks for update!

> var telemetryClient = new TelemetryClient();
this is the problem for custom dependencies.
This de-facto uses TelemetryConfiguration.Active singleton which is NOT the same as instance Functions uses. So they are configured differently. 
Check out this article on how to get the configuration here https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3.

On ApplicationInsights side we are making some improvements around this to stop this confusion.

Regarding missing requests, @brettsam it indeed seems like https://github.com/Azure/azure-functions-host/issues/4389.

**Comment by rkbalu** [comment]
Thanks @lmolkova 

If you see the below screenshot, all my custom dependency correlated nicely under single invocationid/operationid.

Correlation is inconsistent if there is **no** request trace at all. In this we get a **unique invocationid**, but multiple invocationid mapped to some random operationid.

I feel this is in consistent behavior or i may be wrong. any help on this one would be much useful to understand how it works.

![image](https://user-images.githubusercontent.com/33522349/58322253-5280d300-7e18-11e9-8557-e7b22e13f4e9.png)

**Comment by rkbalu** [comment]
@lmolkova any thought about my above question? thanks.

**Comment by lmolkova** [comment]
@rkbalu  thanks for the update,

> Correlation is inconsistent if there is no request trace at all

This should be solved with Azure/azure-functions-host#4389

Regardless of that, please consider not using TelemetryConfiguration.Active to track custom dependencies - it will make sampling, filtering and post-processing of telemtery different between custom telemetry and functions. Please follow this article on how to get the configuration here https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3.

**Comment by rkbalu** [comment]
@brettsam / @lmolkova , All seems to okay after the release (Azure/azure-functions-host#4389). Thanks.

Can you please help to understand why CosmosDB and Eventhub not tracking the Dependency automatically within App insight? 

Not get tracked when we use direct as connectionModel and tcp as Protocol when create cosmos db client & function eventhub outbinding?

**Comment by lmolkova** [comment]
> Can you please help to understand why CosmosDB and Eventhub not tracking the Dependency automatically within App insight?

Cosmos DB in tcp mode and EventHubs are not supported now. We plan to address by the end of the year.

**Comment by rkbalu** [comment]
Can you please share the work item link related to above. This would help us to monitor that feature progress.

**Comment by lmolkova** [comment]
There is no public work item about this.

**Comment by rkbalu** [comment]
Thanks @lmolkova & @brettsam
