### ISSUE TITLE
ServiceBusTrigger and ServiceBus outpub binding in a transaction

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk#2207]
Azure Service Bus supports a transactional processing of an incoming message with emitting the outgoing messages using [`TransactionScope` and Send-Via feature](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions).

As of today (using Functions 2.0 / WebJobs 3.0) there's no way to achieve this as `ServiceBusTrigger` and `ServiceBusAttribute` used for collectors do not share the same `ServiceBusConnection`.

1. Is this going to be supported?
1. While the support for transactional messaging is not there, is there a way to get access to the receiver's connection to be used from the function to emit messages bypassing collector?

**Comment by alrod** [comment]
1. We do not have plans to support `TransactionScope`.
2. You can access `MessageReceiver` inside your function app code:
https://github.com/Azure/azure-webjobs-sdk/blob/f386e54e5000ddddf255f529689ab2a9c3ee78cd/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs#L378

**Comment by SeanFeldman** [comment]
@alrod thank you.

Just before I close this issue, is there a documented list of things that are available for injection for Service  Bus trigger? `MessageReceiver` is there, but if I try to inject `IClientEntity`, it fails. I'd rather look it up in the documentation than raise an issue each time. Thank you.

**Comment by alrod** [comment]
It looks like we do not have the full list in the docs. The only list I found is message properties:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#trigger---message-metadata

You can find full list here:
https://github.com/Azure/azure-webjobs-sdk/blob/2e374a2c58fd89232945e997141f199723dc04db/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/ServiceBusTriggerBinding.cs#L142

**Comment by SeanFeldman** [comment]
That is peculiar. I've raised a doco issue (https://github.com/MicrosoftDocs/azure-docs/issues/32126) to point that out. Would be nice have MessageReader in the context of the output binding, but affraid the modular design will not allow it. If you have two output bindings with two different namespaces, this would not work.
Thank you @alrod.

**Comment by SeanFeldman** [comment]
You will hate me, but one more question - when using `MessageReceiver` to perform a transactional send from a Function, the incoming message must be completed within the transaction scope. Which is against the Functions design, assuming SDK has to complete the incoming message. It's not a biggie, but will cause the host to log a nasty exception for no good reason:

![image](https://user-images.githubusercontent.com/1309622/58349868-a93eda80-7e21-11e9-8865-06f7c44b3117.png)

Is there a way to suppress it or indicated to the SDK that a function will take care of the message completion? I don't recall anything like that in the Functions doco.

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/issues/4397
`"autoComplete": false`

**Comment by SeanFeldman** [comment]
🤦‍♂️ Fantastic, thank you!
