### ISSUE TITLE
Webjob with keyvault

### ISSUE THREAD

**Issue by sahil209** [Azure/azure-webjobs-sdk#2219]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by sahil209** [comment]
Can we add keyvault configuration  just as we do in asp.net core. Which replace by appsetting.json value with same key

**Comment by fabiocav** [comment]
Yes, you should be able to use the same provider in WebJobs. The priority will depend on the order of registration.
