### ISSUE TITLE
Close Older Milestones

### ISSUE THREAD

**Issue by shaggygi** [Azure/azure-webjobs-sdk#2221]
It appears many milestones are past/completed.  For example, it looks like the current milestone is [Functions Sprint 51](https://github.com/Azure/azure-webjobs-sdk/milestone/73).  Would it be possible to close them out?  Thx

**Comment by fabiocav** [comment]
Thank you @shaggygi. That has actually just been done. We appreciate the push to have the repo cleanup up.
