### ISSUE TITLE
Support interface IMessageReceiver via Dependency Injection, instead of MessageReceiver

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-webjobs-sdk#2222]
Is it possible to use interface for function parameter or constructor, instead of concrete type like below?

```

public static async Task ProcessMessage(
    [ServiceBusTrigger("myqueue")] string message, int deliveryCount,
    MessageReceiver messageReceiver,
    string lockToken)
{
    . . .

    await messageReceiver.DeadLetterAsync(lockToken);

    . . .
}
```

https://github.com/Azure/azure-webjobs-sdk/issues/1986

**Comment by brettsam** [comment]
@alrod -- is this something we can do?

**Comment by alrod** [comment]
Using `IMessageReceiver` interface is not possible right now. We can add it in future if community will be interested in having one. Moved to back log.

**Comment by alrod** [comment]
Using `IMessageReceiver` interface is not possible right now. We can add it in the future if community will be interested in having one. Closed as answered.

Fell free to create a feature request in https://github.com/Azure/azure-webjobs-sdk

**Comment by jjcv2304** [comment]
There is a solution proposal on stackoverflow https://stackoverflow.com/questions/64904741/how-to-unit-test-when-microsoft-azure-servicebus-core-messagereceiver-is-involve#comment114768525_64904741
But I'm not sure of possible side effects when casting down to the interface, Does someone knows if that solution has any inconvenient, aside from having to add more code?

**Comment by StannieV** [comment]
Perhaps [my suggestion](https://github.com/Azure/azure-webjobs-sdk/pull/2218#issuecomment-647584346) in #2218 is also an option.
