### ISSUE TITLE
Custom startup not always called when extensionBundle is used in host.json

### ISSUE THREAD

**Issue by APIWT** [Azure/azure-webjobs-sdk#2223]
During local development of a C# class library-based Azure function, you must follow these instructions (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#local-development-with-azure-functions-core-tools-and-extension-bundles) in order to properly load extensions such as storage. However, when you combine this effort with dependency injection (https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection), then the custom startup function defined does not get executed.

#### Repro steps
For convenience, I have created a sample project that demonstrates this bug: https://github.com/APIWT/DIBugExample

If you want to reproduce the bug with your own project, simply follow the instructions below:
1. Follow these instructions to install the extensions bundle for local development with Azure Functions Core Tools: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#local-development-with-azure-functions-core-tools-and-extension-bundles

2. Follow these steps to enable dependency injection: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection

3. Create a function that utilizes Azure Storage Queue

4. Run the function using Azure Functions Core Tools and observe that the Startup function is not called

#### Expected behavior

The Startup function should be called.

#### Actual behavior

The Startup function is not called.

#### Known workarounds

You can work around the bug simply by removing the extensionBundle from host.json after running the Azure Function Host for the first time.

#### Related information 

Please see the Github link for an example project demonstrating this issue: https://github.com/APIWT/DIBugExample

Make sure to follow the instructions in the README on the repository.

**Comment by brettsam** [comment]
Can you move to the latest version of `Microsoft.NET.Sdk.Functions` and give this another try? If it still doesn't work, can you share what's in your `extensions.json` file after you build? It should be in the `{project}/bin/debug/{framework}/bin` folder
