### ISSUE TITLE
QueueTrigger rejects queue name containing . characters, but Azure Service Bus allows creation of Queues with . characters

### ISSUE THREAD

**Issue by tap-absg** [Azure/azure-webjobs-sdk#2226]
My organization uses queues and topics that contain . characters in the names. We have had no issue with these when writing messages to the service bus queues and topics through other means, like Azure Scheduler, TopicClient (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.topicclient?view=azure-dotnet), etc. 

When testing a new durable function locally with a QueueTrigger, which is the first time we have used one, we get the error message found on line 79 of https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/QueueClient.cs which is presumably what QueueTrigger uses.

Changing the queue name to use - instead of . gets past the error, of course. However, it makes no sense that your code is unable to process a queue name that Azure Service Bus allows me to create.

#### Repro steps

1. Create an Azure Function with a QueueTrigger
2. In the QueueTrigger attribute, set the name to something containing .s (e.g. foo.bar.baz)
3. Setup the rest of the project configuration as necessary (I used an actual Azure Service Bus connection)
4. Run the function locally using Azure Storage Emulator

#### Expected behavior

The function should run locally so that I can test it, as Azure Service Bus allows Queue Names containing . characters

#### Actual behavior

I receive error messages during function startup stating that only numbers, letters and dashes are valid characters for queue names

![queue-name-error](https://user-images.githubusercontent.com/13423517/59456867-e709a000-8ddc-11e9-8065-5861328a680e.PNG)

#### Known workarounds

None if you want . characters in your queue names.

#### Related information 

* NuGet Microsoft.Azure.WebJobs.Extensions.Storage 3.0.6
* Code causing the error: https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/QueueClient.cs

**Comment by tap-absg** [comment]
Apparently Service Bus Queue Trigger has no issues with this and is a viable workaround for Azure Service Bus. It still seems weird that queues exist that accept . characters in names and now you have to choose the wrong queue trigger.

**Comment by brettsam** [comment]
Are you using Service Bus Queues or Storage Queues? The `[QueueTrigger]` is explicitly for storage queues, which do not accept `.` If you're using service bus, use `[ServiceBusTrigger]`.
