### ISSUE TITLE
All WebJobs functions hanging randomly, Timeout initiated but functions do not fail

### ISSUE THREAD

**Issue by zx2ner05** [Azure/azure-webjobs-sdk#2233]
Most of the time our continuous webjob functions using queue and timer triggers finish in well under 1 second. However, a couple times a day, all of the currently executing functions will hang for 2-5 minutes. Eventually finishing in most cases.

I have since implemented the timeout attribute, passing the cancellation token to all async operations. However, when this phenomenon occurs, the timeout is initiated for all the functions but the functions do not fail. 

As stated in another issue, this generally only occurs when the timeout is triggered and the code being executed belongs to the SDK. 

Please help me resolve this issue, it is currently affecting our production environment and we currently don't even have a workaround since the timeout does not happen.

Here is the job log at the time of issue:
[job_log.txt](https://github.com/Azure/azure-webjobs-sdk/files/3298570/job_log.txt)

* Package version 2.0.0.0
* source
[Source.zip](https://github.com/Azure/azure-webjobs-sdk/files/3298599/Source.zip)

**Comment by brettsam** [comment]
At a high level, if you'd like the function to fail, you'll need to throw an exception from within the function.

Some things to look at:
- If you want to fail when the timeout is hit, something needs to be checking that token and throwing (usually with `token.ThrowIfCancellationRequested()`). 
- I see you're passing the token down to a bunch of sub-methods -- are any of those checking this token and throwing?
- Are they all passing the token down to their sub-methods?

In general, something, somewhere needs to be throwing if that token is cancelled. Then the function will exit and be marked as failed.
