### ISSUE TITLE
Questions about best practice to run an endless, no automatic trigger job

### ISSUE THREAD

**Issue by kuyeduwu** [Azure/azure-webjobs-sdk#2239]
Could anyone provide some suggestions about creating an endless webjob? I have searched many articles, including the official articles from Azure, they all seems to focus one event triggered jobs like queue message or timer, but I would like to have an endless webjob running, for now, it seems there are two options to do this:

### Option 1:
```cs
//program.cs
var config = new JobHostConfiguration();
var host = new JobHost(config);

while (true) {
    host.call(typeof(Functions).GetMethod("my_function_name"));
}

host.RunAndBlock(); //the above while loop actually makes this line unreachable.
```

### Option 2:
```cs
//program.cs
var config = new JobHostConfiguration();
var host = new JobHost(config);

host.call(typeof(Functions).GetMethod("my_function_name"));

host.RunAndBlock(); //The while loop inside the function also makes this line unreachable.

//function.cs
[NoAutomaticTrigger]
public static void MyFunction(TextWriter log) {
    while (true) {
        //process my business logic
    }
}
```

1. Could anyone provide some suggestions or insights about the two options?
2. Is there other ways to do this kind of endless job?

**Comment by brettsam** [comment]
In your Option 2 -- what if you wrap your host call in `Task.Run()`?

**Comment by kuyeduwu** [comment]
> In your Option 2 -- what if you wrap your host call in `Task.Run()`?

Thank you Brett. Yes, I think that should be the correct way
