### ISSUE TITLE
Dependency on unavailable version of Microsoft.Azure.WebJobs package in Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.6

### ISSUE THREAD

**Issue by sbest-gcm** [Azure/azure-webjobs-sdk#2244]
The newly released Microsoft.Azure.WebJobs.Extensions.ServiceBus version 3.0.6 has a dependency on Microsoft.Azure.WebJobs >= 3.0.10, but the latest version of Microsoft.Azure.WebJobs available on NuGet is 3.0.9.

I realize this was only updated less than an hour ago, but it happened to break our build because we were referencing version 3.0.* in our csproj file.

Downgrading to 3.0.5 fixes the issue. Is this something that could potentially happen again and we should reference the exact version?

**Comment by rickvdbosch** [comment]
We're experiencing the same issue here. Here's the message we get: 

```
Unable to find package Microsoft.Azure.WebJobs with version (>= 3.0.10)
  - Found 42 version(s) in nuget.org [ Nearest version: 3.0.9 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

Version 3.0.10 of `Microsoft.Azure.WebJobs` is also _not_ available as a prerelease version.

**Comment by jeffhollan** [comment]
Thanks for reporting - looking into this now

**Comment by jeffhollan** [comment]
WebJobs 3.0.10 is getting pushed out now so this should get resolved in a few min

**Comment by rickvdbosch** [comment]
Awesome. Thanks for jumping in so fast @jeffhollan!
Will provide additional information if needed.

**Comment by jeffhollan** [comment]
It should be fixed now (may take some time for NuGet to refresh).  If someone can confirm it's working I'll close the issue.  Apologies for the inconvenience

**Comment by rickvdbosch** [comment]
Confirmed: it's working!

```
[...]
Installing Microsoft.Azure.WebJobs.Core 3.0.10.
Installing Microsoft.Azure.WebJobs 3.0.10.
Installing NuGet package Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.6.
Committing restore...
Writing assets file to disk. Path: C:\code\github\functions-triggers-bindings-example\functions-triggers-bindings-example\ExampleFunctionProject\obj\project.assets.json
Successfully uninstalled 'Microsoft.Azure.WebJobs 3.0.8' from ExampleFunctionProject
Successfully uninstalled 'Microsoft.Azure.WebJobs.Core 3.0.8' from ExampleFunctionProject
Successfully uninstalled 'Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.0.5' from ExampleFunctionProject
Successfully installed 'Microsoft.Azure.WebJobs 3.0.10' to ExampleFunctionProject
[...]
```

**Comment by jeffhollan** [comment]
Thanks again for reporting and making us aware.  Sorry again.
