### ISSUE TITLE
Wiki is extremely outdated

### ISSUE THREAD

**Issue by CReich02** [Azure/azure-webjobs-sdk#2252]
The documentation in the wiki on this repo is very outdated and nearly unusable with the current version of the SDK. Here are just a couple examples that are very inaccurate and do not work.

https://github.com/Azure/azure-webjobs-sdk/wiki/Initialization
https://github.com/Azure/azure-webjobs-sdk/wiki/Running-Locally

Please update wiki documentation as breaking changes occur, or document the version the specific wiki pages are relevant to.

**Comment by fabiocav** [comment]
@CReich02 thank you for the feedback. Most of the relevant documentation has been moved to Microsoft Docs (links are in the Wiki home), and we're working on improved contributor guides that will cover the local development experience. We went ahead and removed the stale/outdated information for now as having inaccurate information is pretty impactful.
