### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.ServiceBus beta3, topicname

### ISSUE THREAD

**Issue by MarkoatPriva** [Azure/azure-webjobs-sdk#2257]
When i use the following ServiceBusTrigger:

[ServiceBusTrigger("%ServiceBusTopicName%", SubscriptionName, Connection = "ServicebusConnection", IsSessionsEnabled = true)]

The topicname is no longer resolved from the settings.
This is happening in version Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0 beta3.
It works in version 3.0.6.

Has this functionality changed in V3.1.0?

**Comment by soninaren** [comment]
@MarkoatPriva can you explain what do you mean by topicName is no longer resolved. Can you share the generated function.json.

**Comment by soninaren** [comment]
cc: @alrod

**Comment by MarkoatPriva** [comment]
Hi,

I mean in previous version, when placing the topicname in between @'s, the name was read from the settings. This no longer seems to work.

Marko
________________________________
Van: Naren Soni <notifications@github.com>
Verzonden: donderdag 25 juli 2019 02:52:40
Aan: Azure/azure-webjobs-sdk <azure-webjobs-sdk@noreply.github.com>
CC: Marko Vermeer <marko.vermeer@priva.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Azure/azure-webjobs-sdk] Microsoft.Azure.WebJobs.Extensions.ServiceBus beta3, topicname (#2257)


@MarkoatPriva<https://github.com/MarkoatPriva> can you explain what do you mean by topicName is no longer resolved. Can you share the generated function.json.

**Comment by alrod** [comment]
Fixed in: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/3.1.0-beta4
