### ISSUE TITLE
Dependency Injection not working for ServiceBusTriggers

### ISSUE THREAD

**Issue by johnkwaters** [Azure/azure-webjobs-sdk#2262]
I have a dotnetcore WebJob using the 3.0.10 nuget.
It has Timer functions and Service bus functions, both registered the same way:

            services.AddScoped<TimerFunctions>();
            services.AddScoped<ServiceBusFunctions>();

For the timer functions, DI works as expected: each time the timer triggers, my constructor is called:

`    public class TimerFunctions
    {
        private readonly ITimedTaskProcessor _timedTaskProcessor;

        public TimerFunctions(ITimedTaskProcessor timedTaskProcessor)
        {
            _timedTaskProcessor = timedTaskProcessor;
        }

        /// <summary>
        /// Run every 1 hour 
        /// </summary>
        /// <param name="timerInfo">Timer info</param>
        /// <param name="log">Log</param>
        /// <returns></returns>
        public async Task HourlyTaskTimerAsync(
            [TimerTrigger("0 0 * * * *", RunOnStartup = true)]
            TimerInfo timerInfo,
            ILogger log)
        {
            log.LogInformation("1H Job!");
        }
    }`

However, for my ServiceBus functions, while the handler triggers. the constructor is NEVER called 

`    public class ServiceBusFunctions
    {
        private readonly IUserRepo _userRepo;

        public ServiceBusFunctions(IUserRepo userRepo)
        {
            _userRepo = userRepo;
        }

        public static void ProcessQueueMessage(
            [ServiceBusTriggerAttribute("portal_in", "StatusChange")]
            Message message,
            TextWriter log)
        {
            log.WriteLine(message);
        }
    }`

What gives?

**Comment by johnkwaters** [comment]
Found the fix!

If I change the method declaration to this, DI works!

`    public class ServiceBusFunctions
    {
        private readonly IUserRepo _userRepo;

        public ServiceBusFunctions(IUserRepo userRepo)
        {
            _userRepo = userRepo;
        }

        public async Task ProcessQueueMessage(
            [ServiceBusTriggerAttribute("portal_in", "StatusChange")]
            Message message,
            ILogger log)
        {
        }
    }`

**Comment by fabiocav** [comment]
Yes, this is expected. If the invocation target is a static method, that method will be called without class instantiation.

**Comment by johnkwaters** [comment]
That may be true... but a lot of the examples and documentation use that signature, which is where I got it from, and I only found the correct signature by mimicing what works for timer functions. The docs are hopelessly out of date for most of WebJobs.
