### ISSUE TITLE
ServiceBusTrigger Resolve Connection String from Outside Settings

### ISSUE THREAD

**Issue by Freddy090909** [Azure/azure-webjobs-sdk#2267]
I have the following code:
``` cs
[ServiceBusTrigger("%topicname%", 
                "%subscriptionname%", 
                Connection = "%connectionString%")]string myQueueItem
```

I am able to write a custom INameResolver for the topicname and subscriptionname and it will correctly pass in these attributes as their resolved values (I am grabbing these values from somewhere other than the settings).

However, for the connection string, it correctly resolves to the value I want it to be, but then passes in that resolved value as the key into the IConfiguration, which obviously doesn't resolve to anything.

**My suggestion:** If a connection string is passed in using %% syntax (meaning to send it through the INameResolver), assume the result of that is the resolved connection string, and not the name of the config value to pull from.

If that is not possible to do, are there any workarounds that I could do to achieve the behavior I want?

**Comment by ghost** [comment]
This is really inconsistent behaviour and I do not get how this came through code review. For the topic and subscription name you need to use `%` for using INameResolver. But for `ConnectionString` do not use `%`, it will use INameResolver when it's an incorrect connection string.

**Comment by brettsam** [comment]
We've had lots of discussions around this and it is indeed confusing. 

@Freddy090909 -- is this in WebJobs or Functions? How are you resolving it? Can you add that resolution to a ConfigurationProvider that you register with the host? Then the lookup will go through that to resolve it...

**Comment by Freddy090909** [comment]
This is in a function app.
Currently, we are resolving %topicname% and %subscriptionname% using an INameResolver, because we grab these connection strings from an API endpoint that stores all of our application connection strings. For the %connectionString%, we are just falling back on using the function app settings until we can find a work around.

I wrote up a ConfigurationProvider as a work around, which seems to have worked. I do get warning messages while running the functions locally, but that's not a big deal: 
"Warning: Cannot find value named 'connectionString' in local.settings.json that matches 'connection' property set on 'serviceBusTrigger'"

I do still think that being able to use the nameresolver would be the best final solution, as this is a lot less clean in terms of implementation.

Thanks for the help with the workaround!

**Comment by v-anvari** [comment]
Hi @Freddy090909, closing this issue hoping that the issue has been resolved for you. Please feel free to reopen for any queries regarding this issue.
