### ISSUE TITLE
Queue Trigger Polling Instrumentation Request

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk#2269]
There have been a number of reports of the QueueTrigger stop polling and a restart of the Web Job is needed.

This is on QueueTrigger jobs written using Web Jobs 3.x.

E.G.

[Queue trigger stops picking up messages after connection drops and restores}(https://github.com/Azure/azure-webjobs-sdk/issues/2072) 
[QueueTrigger stops triggering - how to troubleshoot?] (https://github.com/Azure/azure-webjobs-sdk/issues/2136) 

This is referenced in general at [Instrument Polling Algorithms with Trace statements](https://github.com/Azure/azure-webjobs-sdk/issues/1956)

The main idea would be to show if we're still polling the Queue or if it has stopped for some reason. 

Otherwise to troubleshoot this we would need more information.

1. Storage Account Logs for the Queue we are polling.
2. A Dump file of the Dotnet.exe process hosting the WebJob that is not responding.

**Comment by FinVamp1** [comment]
Queue trigger stops picking up messages after connection drops and restores (https://github.com/Azure/azure-webjobs-sdk/issues/2072)
QueueTrigger stops triggering - how to troubleshoot? (https://github.com/Azure/azure-webjobs-sdk/issues/2136)

**Comment by FinVamp1** [comment]
https://github.com/Azure/azure-webjobs-sdk/pull/2277 is going to help here.

**Comment by brettsam** [comment]
I think #2277 addresses this completely -- I'm going to mark this one as closed. Note that customers will have to move their extensions forward to that release when it gets out (this won't happen automatically).
