### ISSUE TITLE
Servicebus and eventgrid extension discontinued?

### ISSUE THREAD

**Issue by Alxandr** [Azure/azure-webjobs-sdk#2280]
I noticed that service bus and eventgrid extensions was removed from this repo. Are then being discontinued? Or simply moved elsewhere?

**Comment by kashimiz** [comment]
They're alive and well, just living in their own repositories now. :)

* [azure/azure-functions-eventgrid-extension](https://github.com/Azure/azure-functions-eventgrid-extension)
* [azure/azure-functions-servicebus-extension](https://github.com/Azure/azure-functions-servicebus-extension)

You can use [this GitHub query](https://github.com/Azure?utf8=%E2%9C%93&q=functions%20extension) to find all extension repos, as per the [azure/azure-webjobs-sdk-extensions](https://github.com/azure/azure-webjobs-sdk-extensions) repo's README.

**Comment by Alxandr** [comment]
You're wery right. I was searching for `webjobs` and not `functions`. Thanks :)
