### ISSUE TITLE
Support for Application Insights in the Azure Government Cloud [v2.x]

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#2284]
Creating a separate copy of #2263 to explicitly do this for v2.x (and functions v1). The changes will be very different from the v3.x changes tracked in the other issue.

**Comment by oshevnin** [comment]
What are the plans to backport the setting (APPLICATIONINSIGHTS_CONNECTION_STRING) to v1?
We have production app that is running v1 and are planning to deploy it in Azure Government

**Comment by fabiocav** [comment]
Assigning this to 81 for estimation/planning

**Comment by fabiocav** [comment]
Work has been scoped. We'll have an issue tracking the specific work and linked to this.

**Comment by jcbrooks92** [comment]
For context this will need to be added to your host.json:

  "applicationInsights": {
    "ingestionEndpoint": "https://dc.applicationinsights.us/v2/track",
    "liveEndpoint": "https://quickpulse.applicationinsights.us/QuickPulseService.svc"
  }
