### ISSUE TITLE
jobs host is incompatible with ApplicationInsights-Kubernetes

### ISSUE THREAD

**Issue by blushingpenguin** [Azure/azure-webjobs-sdk#2288]
Please provide a succinct description of the issue.

#### Repro steps

class Blah : FunctionsStartup {
    public override void Configure(IFunctionsHostBuilder builder) {
        builder.Services.AddApplicationInsightsKubernetesEnricher();
    }
}

#### Expected behavior

the k8s enricher modifies TelemetryConfiguration and injects a helper which records k8s details in the telemetry

#### Actual behavior

Since the functions host initialises application insights itself, it does not use the options pattern that the regular AI startup code does, and the additional configuration added by the k8s enricher is ignored.

see:
https://github.com/Azure/azure-webjobs-sdk/blob/v2.x/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/DefaultTelemetryClientFactory.cs

and:
https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/develop/src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs

#### Known workarounds

I don't have one.  I suppose I might be able to poke around with reflection and inject the k8s initializer into the telemetry configuration but a supported method of injecting the telemetry initialiser would be preferrered.

**Comment by blushingpenguin** [comment]
seems like i was looking at an old version of the code:

https://github.com/Azure/azure-webjobs-sdk/blob/5df91e0e6a23b08db0ff37ecdf803c7a145bda1b/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs

I tried registering an ITelemetryInitializer via a FunctionsStartup, but it wasn't seen by serviceProvider.GetServices<ITelemetryProvider>() somehow.  There is some custom DI going on in the jobs host -- I couldn't quite figure out why the registered ITelemetryInitializer wasn't found.

**Comment by brettsam** [comment]
Is this using WebJobs or Functions? Can you share how you're registering it?

In general, the `AddApplicationInsights...()` methods that come from other teams aren't going to work well with WebJobs because so much custom stuff was built before these exist. Now they're using some new patterns that we'll have to adopt.

That being said, if you're looking to add an `ITelemetryInitialzer`, that should work.

**Comment by blushingpenguin** [comment]
It's functions.  To register it I have a class derived from FunctionsStartup:

```csharp
public class DuffTelemetryInitializer : ITelemetryInitializer
{
  public void Initialize(ITelemetry telemetry)
  {
    throw new Exception("duff telemetry initializer");
  }
}

public abstract class CommonFunctionsStartup : FunctionsStartup
{
  public override void Configure(IFunctionsHostBuilder builder)
  {
    var services = builder.Services;
    services.AddSingleton<ITelemetryInitializer, DuffTelemetryInitializer>();
  }
}
```

then I've done some fiddling about with the debugger where I see DuffTelemetryInitializer being added to services.  Next I end up in ApplicationInsightsServiceCollectionExtensions.cs where SetupTelemetryConfiguration is called, and stepping into that function I don't see the DuffTelemetryInitializer, just these:

```
[0]	{Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer}
[1]	{Microsoft.Azure.WebJobs.Logging.ApplicationInsights.WebJobsRoleEnvironmentTelemetryInitializer}
[2]	{Microsoft.Azure.WebJobs.Logging.ApplicationInsights.WebJobsSanitizingInitializer}
[3]	{Microsoft.Azure.WebJobs.Logging.ApplicationInsights.WebJobsTelemetryInitializer}
[4]	{Microsoft.Azure.WebJobs.Logging.ApplicationInsights.MetricSdkVersionTelemetryInitializer}
[5]	{Microsoft.Azure.WebJobs.Script.Config.ScriptTelemetryInitializer}
```

I guess the provider in ```provider.GetServices<ITelemetryInitializer>(),``` isn't created from the service collection passed into the FunctionsStartup class, but I haven't been able to figure out exactly what's going on (the debugger isn't a great help on the release mode code).

Thanks,

Mark

**Comment by brettsam** [comment]
Can you share your PackageReferences in your csproj? What version of the host are you running locally (it should say on startup). You may be on an older host that is not using the latest App Insights packages. That means we don't see your `ITelemetryInitializer` b/c it's too far ahead.

**Comment by blushingpenguin** [comment]
```
Azure Functions Core Tools (2.7.1373 Commit hash: cd9bfca26f9c7fe06ce245f5bf69bc6486a685dd)
Function Runtime Version: 2.0.12507.0
```

refs is a bit fiddly, but ultimately ends up as:
```
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.7.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="1.1.0" />
```
which pulls in Microsoft.ApplicationInsights 2.10.0

**Comment by brettsam** [comment]
Yeah, that's it -- grab the latest CLI and you should start working.

**Comment by blushingpenguin** [comment]
Yes, that's got it working so I should be able to bootstrap the k8s extension that way. Thanks very much for the help.  I haven't closed this as it would be nice if this just worked out of the box -- given that the functions host configures AI anyway, it would seem reasonable for it to configure the k8s extensions too.  (Similarly to not having AI turned on, they don't do any thing if they aren't used -- all they actually do is to add some helpful metadata to the AI logs).

**Comment by brettsam** [comment]
I've gone ahead and created a more global issue that I can start to link all of these individual issues to: #2292. I'll close this one since this specific issue is addressed. Ultimately, we'll need to rewrite a lot of our service registration code in order to work with what they've added recently.

Thanks for the report!
