### ISSUE TITLE
Where's the document of creating a binding in new extensibility mode

### ISSUE THREAD

**Issue by zackliu** [Azure/azure-webjobs-sdk#2289]
https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/Binding-Extensions-Overview said there's a newer extensibility model to create a binding. But the link to  https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings has broken. I can't find related topic at https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started neither. 
So, where can I get the latest document about creating a binding?

**Comment by paulbatum** [comment]
We recently removed a bunch of out of date information hosted on the webjobs wiki and it looks like this was included in that (I think by accident). I've restored the content:
https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings
