### ISSUE TITLE
Graceful Shutdown for Triggered Webjob with only NoAutomaticTrigger

### ISSUE THREAD

**Issue by czb182** [Azure/azure-webjobs-sdk#2290]
.NET Core 2.2
Webjobs SDK 3.0.10

I am trying to figure out a way I can do a graceful shutdown of my triggered webjob when i manually restart app service, or it is automatically restarted/recycled.  I have only a single function decorated with [NoAutomaticTrigger] called like this.  This is a long running job for many hours, and there are things i would like to do before it is forcibly stopped.

```
            using (host)
            {
                await host.StartAsync();
                var jobHost = host.Services.GetService<IJobHost>();
                await jobHost.CallAsync(nameof(Functions.ProcessData));
                await host.StopAsync();
            }
```
here is my function

```
        [Singleton]
        [FunctionName(nameof(ProcessData))]
        [NoAutomaticTrigger]
        public async Task ProcessData(ILogger logger, CancellationToken cancellationToken)
        {
                cancellationToken.Register(() =>
                {
                    logger.LogInformation("cancelled!");
                    Console.WriteLine("cancelled");
                });

                while (!cancellationToken.IsCancellationRequested)
                {
                    await Task.Delay(1000, cancellationToken).ConfigureAwait(false);
                    logger.LogInformation("waiting");
                }
                logger.LogInformation("escaped");
        }
```

i monitor the cancellation token, register a function when cancelled, but it doesn't appear to be working.   Function gets stuck in "waiting" loop I'm not sure if this is just not a supported scenario, or I'm doing something wrong.  All the documentation around graceful shutdown i see seems to be around continuous webjobs.

**Comment by brettsam** [comment]
@mathewc -- we should be canceling this token, right? Looking through the code, it looks like we'll use the `ShutdownFunctionExecutor` which should be canceling the correct token here.

**Comment by czb182** [comment]
I see several cancellation tokens linked together, but I wasn't able to follow in code, if was actually passed to a webjob function of that particular trigger (NoAutomaticTrigger).  I also wasn't sure if maybe the ShutdownFunctionExecutor was did work for continuous webjobs, rather than trigger.  I also tried passing in my only CancellationToken into the JobHost.CallAsync method, but it seems to be a different one than is injected into the function, although it could be linked to that one, not sure how to verify that.  Having said all that, I think it would be a reasonable expectation that the injected CancellationToken would in fact be cancelled upon a soft or hard shutdown to all the job to spin down.

**Comment by czb182** [comment]
Anything needed from me to help move this along?

**Comment by woutercx** [comment]
I have the same problem. Using .NET Core 3.0, Webjobs SDK 3.0.14. This is really bothering me.

**Comment by NickSevens** [comment]
@czb182 did you get any solution for this? I'm having what I think is the same issue.
Thanks

**Comment by czb182** [comment]
No.  I put in the code as I thought it should work, hoping that a future library update will make it work.  Unfortunately there is not a lot of activity in this repo, so not sure if/when that would happen

**Comment by fabiocav** [comment]
@czb182 going through some of these old issues and came across this without a response. Apologies for the delay, but are you still experiencing issues?

**Comment by czb182** [comment]
I no longer have access to the particular piece of software which experienced this issue, but presumably the issue still exists. 

Thanks for reaching out.  I hope MSFT is able dedicate resources to catch back up on this particular SDK, as I'm sure your aware of the size of untriaged issues and pending PR's.  This SDK seems to be used on every project I get assigned.

**Comment by v-anvari** [comment]
@brettsam , any thoughts here?

**Comment by pragnagopa** [comment]
@v-anvari - Please repro this issue.

**Comment by brettsam** [comment]
@NickSevens (or @czb182, if you remember) -- how were you cancelling the host in your repro? Were you using CTRL+C from the console to cancel locally?

**Comment by NickSevens** [comment]
Well, it's been a while :/ But I do believe I tried it using CTRL+C, yes.
