### ISSUE TITLE
WebJobs 3.0.11 depends on WebJobs.Core 3.0.11 which is not listed

### ISSUE THREAD

**Issue by raymens** [Azure/azure-webjobs-sdk#2297]
The current released version of Microsoft.Azure.WebJobs (3.0.11) depends on Microsoft.Azure.WebJobs.Core (3.0.11) which is not listed. Most updated version of Microsoft.Azure.WebJobs.Core is 3.0.10.

Other package(s) that depend on Microsoft.Azure.WebJobs (3.0.11) and thus cannot be updated are:
- Microsoft.Azure.WebJobs.Extensions.Storage
- ?

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A
- Add reference to Microsoft.Azure.WebJobs 3.0.11

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior
```
NU1102	Unable to find package Microsoft.Azure.WebJobs.Core with version (>= 3.0.11)
  - Found 44 version(s) in nuget.org [ Nearest version: 3.0.10 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in dotnet.myget.org roslyn
```
Provide a description of the actual behavior observed. 

#### Known workarounds

Don't update.

#### Related information 

Provide any related information 

* https://www.nuget.org/packages/Microsoft.Azure.WebJobs/
* https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Core/

**Comment by forki** [comment]
noticed the same:

![image](https://user-images.githubusercontent.com/57396/62861708-9e9b2f80-bd04-11e9-853b-7146c53c7b5f.png)

**Comment by soninaren** [comment]
This has been fixed. Microsoft.Azure.WebJobs.Core version 3.0.11 has been published
