### ISSUE TITLE
Support for Application Insights in the Azure China Cloud [v3.x] 

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk#2305]
As mentioned in #2263  there is a way via DI to configure the endpoints for the Application Insights Telemetry for C# Functions. 

We've had an IcM 140683853 which is asking for similar functionality for the Azure China Cloud but for PowerShell Functions. 

The steps in the linked post can't be used for the out of process language workers.

**Comment by kulkarnisonia16** [comment]
@brettsam - just noticed this was assigned to Sprint 58, what is the current status on this?

**Comment by brettsam** [comment]
This is all done with the connection string work completed by @gzuber. It's a part of [2.0.12998](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12998) but this hasn't been released to China yet.

**Comment by FinVamp1** [comment]
This should be resolved and live in China
