### ISSUE TITLE
Azure Blob Trigger function: sometime the function was not trigger for some blob/file, it's a random issue

### ISSUE THREAD

**Issue by itsashish-patel** [Azure/azure-webjobs-sdk#2307]
#### Investigative information

- Timestamp: 2019-08-08T05:30:57.6444613Z
- Function App version (1.0 or 2.0): 2.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: c27df957-9b67-4164-a1a7-da53c7d9d4ce
- Region: Australia East

#### Repro steps

- As it random issue, the azure function was skipped blog trigger for some file, 
- you may upload many file in blob storage and check

#### Expected behavior

- The azure function should trigger for each file which either added/uploaded or modified in blob storage container

#### Example:

- Whenever new file added/uploaded in blob storage container, azure function need to trigger and process that as per logic of the function

#### Actual behavior

- The azure function does not trigger for all newly added file in blob storage container

**Comment by brettsam** [comment]
It may be related to #2202. Waiting on more details.

**Comment by itsashish-patel** [comment]
Hi @brettsam,



> they're just never triggered?

They are sometime triggered and sometime not, the blob are available in container but the blob function was not trigger for the blob when the blob got uploaded through logic app

**Comment by gjmoyer** [comment]
We have the same issue that just started 11/1/2019.  Has been working daily for more than a year, and now we are experiencing occasional failures.  The production code has Microsoft.Azure.WebJobs.Extensions.Storage 3.0.6 deployed.  I see issue https://github.com/Azure/azure-functions-host/issues/4784 that reports a fix in 3.0.8 that I am trying to determine if this is effecting us.

**Comment by v-anvari** [comment]
@gjmoyer / @itsashish-patel , I believe this might have been caused by a race condition which has been fixed -- Azure/azure-webjobs-sdk [#2194](https://github.com/Azure/azure-webjobs-sdk/issues/2194)

The Functions runtime updates should have included the fix by now. Closing the issue, please feel free to re-open if you continue to see any such issue.
