### ISSUE TITLE
How to do Integration Tests with Azure Webjobs V3?

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-webjobs-sdk#2310]
Hi,

I have an Azure WebJob with a QueueTrigger. I use HostBuilder with Autofac for Dependancy Injection.

I can test manually that my QueueTrigger is launch each time a new element is added to the queue and read the log to verify that every things is correct. I would like to automatize it.

I dont really know where to start, I thought [DispatchQueueEndToEndTests.cs](https://github.com/Azure/azure-webjobs-sdk/blob/e30f8544e63019911a6d07a6a449f13017b09ce4/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/DispatchQueueEndToEndTests.cs) could help me but I don't understand where to start.

Here is what I have to do integration test for my API:

```
public class TestServerFixture : IDisposable
    {
        public TestServer Server { get; }
        public HttpClient Client { get; }
        public T GetService<T>() => (T)Server.Host.Services.GetService(typeof(T));

        public TestServerFixture()
        {
            var builder = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseEnvironment("Development")
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                          .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", optional: true, reloadOnChange: true)
                          .AddEnvironmentVariables();
                })
                .UseStartup<TestStartup>();

            Server = new TestServer(builder);
            Client = Server.CreateClient();
        }
        public void Dispose()
        {
            Server.Dispose();
            Client.Dispose();
        }
```

   ```
 public class TestStartup : Startup
    {
        public TestStartup(IConfiguration configuration)
            : base(configuration)
        {
            // nothing
        }

        public override void SetUpDataBase(IServiceCollection services)
        {
            services.AddDbContext<MyDBContext>(options => options
                .UseInMemoryDatabase("MyDB")
                .EnableSensitiveDataLogging()
            );
        }
    }
```

   ```
 [Collection(Constants.TEST_COLLECTION)]
    public class Users_Tests : BaseTest
    {
        public Users_Tests(
            TestServerFixture testServerFixture, 
            ITestOutputHelper output
        ) : base(testServerFixture, output)
        {
        }

        [Fact]
        public async Task Should_Unauthorized_Register_User()
        {
            TestServerFixture.ClearHeader();
            var response = await TestServerFixture.Client.PostAsync(
                Common.Constants.Urls.Users,
                null
            );
            Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
        }
  }
```

Do you have an easy sample like this to do Integration Tests for Azure Webjob with QueueTrigger, NoAutomaticTrigger (and other triggers for other people who could be interested)?

Thanks

**Comment by brettsam** [comment]
You can find all of our Storage EndToEnd tests (they actually hit storage, but I believe they'd work with an emulator as well) here: https://github.com/Azure/azure-webjobs-sdk/blob/dev/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs.

You can see that it creates a new host for the tests to run here: https://github.com/Azure/azure-webjobs-sdk/blob/dev/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs#L534-L545. The key is that `ConfigureDefaultTestHost<T>()` call -- which builds a host and uses the type `T` as its source for functions to load. You can find the implementation of that here (there's lots of overloads too): https://github.com/Azure/azure-webjobs-sdk/blob/dev/test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs#L150.

Once the host is running, you can start putting items into your queue and test the results of your function.

There's a lot of pieces there that you likely don't need -- but setting up your own `ITypeLocator` and having it point to your test type with your functions is the first step to get the tests running.

For some of our other storage tests, we have implemented a bunch of in-memory mocks here: https://github.com/Azure/azure-webjobs-sdk/tree/dev/test/FakeStorage. There's a lot there, though, and some pieces don't necessarily work (as we'd never needed them). If you can get away with using the emulator to test, that'd be my recommendation.

**Comment by brettsam** [comment]
I'm going to close this as it's not an active (code-related) issue. But please let me know if you need any more follow up and I can help out.

**Comment by ranouf** [comment]
Thanks @brettsam for your answer, I will take a look on it.

**Comment by ranouf** [comment]
From what I see there [AzureStorageEndToEndTests.cs](https://github.com/Azure/azure-webjobs-sdk/blob/dev/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AzureStorageEndToEndTests.cs), QueueTrigger functions are not Async which allow you to have a out parameter which can be read by Integration Tests. Is there a solution to do that with Async?

It s not an easy going Testing, to use "ConfigureDefaultTestHost" I need to import [Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs](https://github.com/Azure/azure-webjobs-sdk/blob/3eb3dc7a5d1d6e51c6edad4cdcaa1d6b553084e4/test/Microsoft.Azure.WebJobs.Host.TestCommon/TestHelpers.cs) which need :
- [JobHost](https://github.com/Azure/azure-webjobs-sdk/blob/77234d6aef493788cfa25c02467fe31e1db265d6/src/Microsoft.Azure.WebJobs.Host/JobHost.cs) 
- [AddTestSettings](https://github.com/Azure/azure-webjobs-sdk/blob/00bc34086ed262fcb3b23739d11246661bfe0a17/test/Microsoft.Azure.WebJobs.Host.TestCommon/TestConfigurationBuilderExtensions.cs) 
- [FakeTypeLocator](https://github.com/Azure/azure-webjobs-sdk/blob/b798412ad74ba97cf2d85487ae8479f277bdd85c/test/Microsoft.Azure.WebJobs.Host.TestCommon/Fakes/FakeTypeLocator.cs)
- [TestExceptionHandlerFactory](https://github.com/Azure/azure-webjobs-sdk/blob/7c7f8debea917d3f78b71370288173b8c360e4f6/test/Microsoft.Azure.WebJobs.Host.TestCommon/TestExceptionHandler.cs)

I m writing this for next one who is interested for doing the same, and it s only the first step of dependencies. I will try to make it works :)

Or is there any nuget with all of this?

**Comment by brettsam** [comment]
You need to decide how you want to verify that your function executed as expected:
- Check some output artifact.
- Log something. We register a TestLogger so we can check logs.
- Inject some test services that allow you to monitor behavior internally (i.e mock out some service call, etc, that allows for easier validation in tests).

All of this works sync or async.

I don't necessarily recommend taking everything we did as-is. I was trying to show you the pieces we use to run these end-to-end tests ourselves. You should be able to pick the minimum number of pieces there to get things working like you expect (`FakeTypeLocator` would be the first thing I'd look at -- it lets you point to your class as the source of Functions).
