### ISSUE TITLE
[Question] Timeline for .NETStandard 2.1

### ISSUE THREAD

**Issue by metoule** [Azure/azure-webjobs-sdk#2312]
I'm trying to migrate an Azure function to ASP.NET Core 3, but the Nuget package `Microsoft.Azure.WebJobs` is not available for netstandard2.1. 

Could we have a roadmap / timeline for netstandard2.1 support?

**Comment by brettsam** [comment]
We have a branch in Functions working on ASP.NET Core 3.0 support right now (https://github.com/Azure/azure-functions-host/tree/3.x). However, we will not be moving WebJobs forward to netstandard2.1 as that's not actually required to move Functions to ASP.NET Core 3.0.

As for timeline -- the work is in progress but I'm not sure if we've given out any dates yet -- @paulbatum?

I'd love to hear your scenario -- is there something in your project that makes 3.0 a requirement?

**Comment by brettsam** [comment]
I'm going to close this as it's not an active issue -- but we can continue the conversation here.

**Comment by metoule** [comment]
My scenario is that I have shared libraries between my main web app (ie. customer facing) and my Azure functions, and I'd like to avoid multi-targeting because it's not that easy: netstandard2.1 introduces `IEnumerable.ToHashSet` while I previously used the MoreLinq implementation, and both conflict with one another. If I want to multi target, I'd need to introduce a lot of compilation guards around the using statements.

I don't have hard requirements to use 3.0 yet, but I'm very interested in the latest endpoint routing middleware. I can wait a couple of weeks until the final release, and in the meantime I'll have a look at the 3.x branch, thanks for pointing it out!

**Comment by paulbatum** [comment]
A related issue: https://github.com/Azure/azure-webjobs-sdk/issues/2286

@metoule Can you help me understand why the scenario you described requires multi-targeting? Your shared library can be .NET Standard 2.1 and reference the WebJobs 3.x packages while they remain on .NET Standard 2.0. 

As far as I can tell, the only scenario where it would make sense for us to provide a .NET Standard 2.1 target for WebJobs is if we wanted to provide additional API surface area that relies on types that aren't available in .NET Standard 2.0, such as `Span<T>`. 

Please let me know if there is something I'm missing.

**Comment by metoule** [comment]
I encountered a bunch of weird MSBuild issues when trying to compile my Azure function code, and I assumed it was an issue with the netstandard version. 

After trying to compile an Hello world example, it seems that I'm simply not using the proper VS tooling, because I find myself in the scenario described in Azure/azure-functions-host#3854.

For reference, I'm currently using: 

- `Microsoft.NET.Sdk.Functions` v1.0.30-beta1 
- `AzureFunctionsTools` v2.32.0

It will probably be simpler to wait for the proper release to try again.
