### ISSUE TITLE
Assembly missing in WebJob temp working directory

### ISSUE THREAD

**Issue by 8ggmaker** [Azure/azure-webjobs-sdk#2313]
our own code bug, ignore this

**Comment by zsybupt** [comment]
And I try to set is_in_place = true to avoid copy to a temp working dir, it works, but another problem occurs: we use RoleEnvironment.IsAvailable = true to check if job runs on azure, when is_in_place = true, it return false and leads to read wrong configuration in app.config.

**Comment by zsybupt** [comment]
before we receive a servicebus queue message, there are 258 items in the temp working dir
![beforeservicebus](https://user-images.githubusercontent.com/3711046/63911328-76c5fe80-ca5c-11e9-86dd-c15e14028eee.PNG)

but receive a service bus message, and try to load Microsoft.Graph.Core.dll to process the message, it becomes 39 items, lots of assembly disappeared, it is really confused.
![afterservicebus](https://user-images.githubusercontent.com/3711046/63911407-a8d76080-ca5c-11e9-84c7-518e420eaebd.PNG)

**Comment by zsybupt** [comment]
@brettsam @mathewc  Anyone can help ?

**Comment by zsybupt** [comment]
@jzbuaa

**Comment by zsybupt** [comment]
our own code bug, ignore this
