### ISSUE TITLE
Changing Triggered WebJob schedule doesn't work with WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by manu4rhyme-zz** [Azure/azure-webjobs-sdk#2324]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Deploy a .NET project (with webjobs) using the WEBSITE_RUN_FROM_PACKAGE app setting. 

2. Try to change schedule using the Kudu API

#### Expected behavior

Schedule should be changed

#### Actual behavior

1) A folder write access error is thrown. 
2) Apparently schedule is obtained directly from the settings.job file, and even the API ultimately tries to modify this file.
3) Since WEBSITE_RUN_FROM_PACKAGE locks the project folder, and makes it read-only, settings.job cannot be updated, and the API call fails. 

#### Known workarounds
None. 
1) Basically our scenario demands that we disable the triggered webjob when not in use. 
2) We were setting the webjob's schedule to a very long time for accomplishing this.
3) In Azure functions we can disable a webjob with an app setting. However, we cannot use that here, because it might cause the web-app to restart everytime this app setting is changed. 

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by v-anvari** [comment]
Hi @manu4rhyme-zz , Apologies for the delay in response.

You are right, Run-from-package makes the entire site directory read-only. You can't disable the individual webjobs as it requires a file "disable.job" to be present in the webjobs directory for the job you wish to stop. Which is more clearly explained in [#2389](https://github.com/Azure/azure-webjobs-sdk/issues/2389). 

let us know If you have any further queries.
