### ISSUE TITLE
If exception occurs is there any way to send message into dead letter topic using c#?

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-webjobs-sdk#2325]
I have azure function app which trigger based on new message into service bus topic.

But if any exception occurs i want to send message into dead letter topic how to do that?

 [FunctionName("ProcessData")]
        public static void Run([ServiceBusTrigger("topic", "sub1", Connection = "ConnectionStringSettingName")]string mySbMsg, TraceWriter log)
        {           
            try
            {
                //process message mySbMsg
                DataSchema data = JsonConvert.DeserializeObject<DataSchema>(mySbMsg);
                ...
            }
            catch(Exception ex)
            {

               sendErrorEmail();               

              // How to send message into Dead letter explicitly ?
            }
        }

or adding throw new Exception(); is the only solution?

**Comment by v-anvari** [comment]
Hi @ashuthinks , Apologies for the delay in response. If we understood it right, do you want to move the messages to [Dead-letter queue](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#moving-messages-to-the-dlq)? if yes, then you can move message to DLQ by calling the [DeadLetter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.queueclient.deadletterasync?view=azure-dotnet) method.
