### ISSUE TITLE
WebJob triggered not working when deployed to azure

### ISSUE THREAD

**Issue by geotinc** [Azure/azure-webjobs-sdk#2328]
Hi, 
I have a proble with .net core azure webjob.
I use packages version 3.0.X of Microsoft.Azure.WebJobs.*

Locally, my job works great :

```
class Program
    {
        static void Main(string[] args)
        {
            HostBuilder builder = new HostBuilder();
            builder.ConfigureWebJobs(b =>
            {
                b.AddAzureStorageCoreServices();
                b.AddAzureStorage();
                b.AddTimers();
            });
            IHost host = builder.Build();
            using (host)
            {
                host.Run();
            }
        }
    }
```

And job function :

```
public class FunctionApplication1
    {
        public async static void ProcessTimerAction([TimerTrigger("0 0 0 * * *", RunOnStartup = true)] TimerInfo timer)
        {
            // MyCode
            }
        }
    }
```

Once deployed to azure app (I have already a deployed website deployed to that app), the webjob never run.

Don't understand why.

Thanks for helping.

**Comment by v-anvari** [comment]
Hi @geotinc , apologies for the delay in response. Kindly let us know if you are still using this scenario, and are facing issue, So that we can look into it further.

**Comment by nicklasjepsen** [comment]
@v-anvari  I have the exact same issue, however, I'm using version 4.0.1 of the web job packages.

**Comment by nicklasjepsen** [comment]
> @v-anvari I have the exact same issue, however, I'm using version 4.0.1 of the web job packages.

But my issue was caused by a wrong publish setting 😶

Change WebJob Type to **Continuous** when publishing from VS and running Timer triggered functions in the web job solved my problem.
