### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0.0, dll signature seems to be invalid

### ISSUE THREAD

**Issue by artsherwood** [Azure/azure-webjobs-sdk#2330]
Please provide a succinct description of the issue.

Microsoft.Azure.WebJobs.Extensions.dll from Microsoft.Azure.WebJobs.Extensions.ServiceBus package version 3.1.0.0 won't load.

Provide the steps required to reproduce the problem

1. Download version 3.1.0.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus package
2. Call Assembly.LoadFile(_file location of Microsoft.Azure.WebJobs.ServiceBus.dll_)

#### Expected behavior

Assembly should load

#### Actual behavior

FileLoadException: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

#### Known workarounds

Downgrade to version 3.0.6.0

**Comment by v-anvari** [comment]
Hi @artsherwood , Apologies for the delay in response. We are sure this scenario has been resolved in later releases. But, kindly let us know if you are still looking out for a description for older version.
