### ISSUE TITLE
Make AzureWebJobsStorage work with Sas-Definition from keyvault storage.

### ISSUE THREAD

**Issue by vitalii-lebedev** [Azure/azure-webjobs-sdk#2341]
I want to create a Function App and make it work with Storage Account through KeyVault Storage Sas-Definition. 
In documentation it's written that there are 2 possible options:

1) @Microsoft.KeyVault(VaultName=myvault;SecretName=mysecret;SecretVersion=ec96f02080254f109c51a1f14cdb1931)
2) @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/ec96f02080254f109c51a1f14cdb1931)

The first one requires a connection string, and the second one requires a secret URI of connection string. But I don't want to have connection string at all. I want KeyVault Storage manages it instead.

Seems like now this behavior is not supported at all.

**Comment by brettsam** [comment]
Sorry for the slow reply here -- are you referring to the App Service Key Vault references? https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references.

If you can show exactly what you're trying to do, we may be able to point you in the right direction.
