### ISSUE TITLE
502 "Bad Gateway" errors consistently occurring when hitting "Run" on any function in Kudu

### ISSUE THREAD

**Issue by tmenier** [Azure/azure-webjobs-sdk#2343]
As of Friday morning 10/4/2019, we cannot run a WebJob function manually through the Kudu console. When we click "Run", It spins for 2 minutes and returns a 502 error.

![](https://content.screencast.com/users/tmenier/folders/Jing/media/f45fc8d8-7acc-4efc-9560-074e3b1638be/2019-10-05_1130.png)

We're seeing it with multiple completely isolated production WebJobs (different App Service Plans, storage accounts, regions), none of which have had code changes in a while, as well as a totally trivial test WebJob deployed solely to troubleshoot this issue.

We have googled this extensively, been through many troubleshooting guides, and examined our code and app service health carefully. Nothing seems to apply. But the [announcement](https://github.com/Azure/app-service-announcements-discussions/issues/118) of .NET Core 3.0 availability on Friday makes us wonder if that's somehow related.

Steps to reproduce:

1. Create a WebJob project using .NET Framework and the WebJobs SDK.
2. Add a trivial no-op function, marked with `[NoAutomaticTrigger]` (or any trigger attribute).
3. Deploy to a continuous WebJob.
4. Browse to the WebJob and specific function in Kudu.
5. Click the "Run" button.

**Comment by tmenier** [comment]
Update: As of today time-of-day timer triggers are again working, but still 502 from manual runs through Kudu. Seeing the same in an entirely new WJ with no code other than and empty function, backed by a new, empty storage account.

**Comment by sjkp** [comment]
@tmenier I have the same error in the Lets Encrypt Site Extensions, I think their upgrade to support .net core 3.0 broke something.

**Comment by ohiobobcat** [comment]
can confirm I'm also receiving a 502 when attempting to manually trigger a timer function from the Kudu console.

**Comment by danikun** [comment]
We are facing the same issue, must be a general azure problem.

**Comment by robertsoniv** [comment]
I have the same issue. I contacted Azure support and they were able to recreate the 502. She has informed me they are working on a fix... hopefully soon!

**Comment by mathewc** [comment]
We've found a regression in our recent App Service deployment (not related to .NET Core 3 or WebJobs). The issue affects form POSTs to the SCM/Kudu endpoint using SSO login. ARM and basic auth are not impacted and could be used for a workaround (@ahmelsayed). We're actively working on a patch for this.

**Comment by suwatch** [comment]
BTW you can browse to Kudu using basicauth by https://your-site-name.scm.azurewebsites.net/basicauth.   Please use that as workaround for now.

**Comment by tmenier** [comment]
I confirmed the work-around is working for us.

If it helps anyone else, the Microsoft account you likely use to log into the Azure portal won't work for basic auth. You can find the credentials in the portal by navigating to your WebJob, highlight it, click Properties, and grab the username/password from that blade.

**Comment by scp-mb** [comment]
https://github.com/projectkudu/kudu/issues/3052#issuecomment-540413571

ETA for fix is 2019/10/18 it seems.

**Comment by tmenier** [comment]
I'm hearing reports from several people on my team that this appears to be fixed. I'll let you guys close this once it's official, but just FYI to anyone waiting on this.

**Comment by scp-mb** [comment]
Can confirm, seems to be resolved and certs can be requested properly now.
