### ISSUE TITLE
Package description is "Package Description:

### ISSUE THREAD

**Issue by ChadNedzlek** [Azure/azure-webjobs-sdk#2349]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage

The package description is "Package description"

That is unhelpful and makes me not trust this is the correct assembly.

**Comment by v-anvari** [comment]
Hi @ChadNedzlek , Thank you for bringing out this point to us. The "package description" shall be updated in the mentioned package.

**Comment by v-anvari** [comment]
Thankyou @chris-johnston for updating the package description, we are good to close this issue
