### ISSUE TITLE
Job failed due to exit code -2146232576

### ISSUE THREAD

**Issue by gmanvel** [Azure/azure-webjobs-sdk#2353]
I left a comment under [Job failed due to exit code -2146232576](https://github.com/Azure/azure-webjobs-sdk/issues/616) which is closed, so thought maybe I should create a new issue.

Please let me know if this should be closed & discussion continued under the [closed issue](https://github.com/Azure/azure-webjobs-sdk/issues/616).

We have a .NET 4.7 deployment (Web App + Web Job), but web job fails to start with the following in the logs

> [10/18/2019 13:29:05 > abf022: SYS INFO] Run script 'Workers.WebJob.exe' with script host - 'WindowsScriptHost'
> 
> [10/18/2019 13:29:05 > abf022: SYS INFO] Status changed to Running
> 
> [10/18/2019 13:29:06 > abf022: SYS ERR ] Job failed due to exit code -2146232576
> 
> [10/18/2019 13:29:06 > abf022: SYS INFO] Process went down, waiting for 60 seconds
> 
> [10/18/2019 13:29:06 > abf022: SYS INFO] Status changed to PendingRestart

Do we have to specifically target **.NET 4.7.2** for this to work ?
Based on https://github.com/Azure/app-service-announcements/issues/89 .NET 4.7.2 is supported since December 11, 2018.

**Comment by v-anvari** [comment]
Hi @gmanvel , We apologize for un-attending the issue, let us know if you are still looking out for help with this issue?
