### ISSUE TITLE
ServiceBus message being moved to dead letter queue unexpectedly in Azure Function

### ISSUE THREAD

**Issue by shaykchen** [Azure/azure-webjobs-sdk#2360]
#### Please provide a succinct description of the issue.

A dotnet function app running on V2 runtime on consumption plan and has a Service Bus trigger (Service Bus SDK 3.3.0). It is found that part of the Service Bus messages are going to dead letter queue without being processed.

The below exception would be thrown out accordingly while the problem occurred:

_System.OperationCanceledException : The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at async System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter,Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.ServiceBus.MessageReceivePump.MessagePumpTaskAsync()_

#### Related information 

This issue is clarified already in https://github.com/Azure/azure-sdk-for-net/issues/6410 and https://github.com/Azure/azure-sdk-for-net/pull/8449

Submit this issue to wait for service bus side fix so we can update ServiceBus extension accordingly.

**Comment by joeyeng** [comment]
I'm getting this exception as well. I'm using Microsoft.Azure.ServiceBus 4.0.0. It works fine running in debug mode, but fails when deployed to Azure.

**Comment by joeyeng** [comment]
Update: I updated Microsoft.Azure.ServiceBus to 4.1.1, and although I'm no longer getting the exception, the message still goes straight to dead letter. It has no dead letter reason/description and there are no function host errors or errors in app insights.

**Comment by shaykchen** [comment]
Thanks to @alrod confirmation, the new SB extension which uses 4.1.1 SDK has been published as well: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.0.0

**Comment by alrod** [comment]
New package is released pointed to 4.1.1 SDK
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.0.0
