### ISSUE TITLE
ServiceBusTrigger on Topic/Subscription does not "wake up" when the Subscription is reactivated after being disabled

### ISSUE THREAD

**Issue by cgrevil** [Azure/azure-webjobs-sdk#2362]
Azure function with ServiceBusTrigger on topic/subscription, and with sessions enabled, works fine initially, and triggers as expected. But if we disable the subscription, and then activate it again, then the function will not trigger until the function has been restarted.

We expect the function to start triggering again after the subscription has been reactivated, without needing to restart the function.

Microsoft.Azure.WebJobs.Extensions.ServiceBus 3.1.0
TargetFramework netcoreapp2.2
AzureFunctionsVersion v2

**Comment by v-anvari** [comment]
Hi @cgrevil , Apologies for the delayed response. Functions in [Consumption plan](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#consumption-plan) usually scales out if the host is not up and running. If you are still facing the issue, please provide us additional information of your function app for us to go through logs. 

Repro steps:
Function App Name:
Region:
Timestamp: (Latest preferably)
