### ISSUE TITLE
How to get Run/Replay Function with Azure WebJob 3.0

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-webjobs-sdk#2371]
Hi,

I try to find a code sample in c# core for Webjob 3.0 enabling the Run/Replay function in Azure for a QueueTrigger? 

![image](https://user-images.githubusercontent.com/1764519/68689122-e5840580-053d-11ea-8da7-7c6a43241e1d.png)

Do you know how to do that? Any documentation?

Thanks

**Comment by v-anvari** [comment]
Hi @ranouf , This is a known issue for webjobs 3.x onwards. Check this issue [comment](https://github.com/Azure/azure-webjobs-sdk/issues/1716#issuecomment-485967715) and this [comment](https://github.com/Azure/azure-webjobs-sdk/issues/2179#issuecomment-485555607).

Closing this issue as duplicate

**Comment by Grepsy** [comment]
Sorry to bring this back up, but the proposed solution "Use Application Insights" doesn't seem to offer any functionality to _invoke or replay_ a webjob function, but only monitor it. I'd like to get conformation on whether this is correct.

Our scenario involves a function with a timer, but we do require the possibility to run it manually for testing. Is there any other way we can do this?
