### ISSUE TITLE
Not getting regular service bus messages when configuring to receive messages from deadletterqueue

### ISSUE THREAD

**Issue by utkarsh24** [Azure/azure-webjobs-sdk#2374]
this is how my azure function code looks like

```
[FunctionName("Function1")]
        public static void Run([ServiceBusTrigger("myqueue/$DeadLetterQueue", Connection = "ServiceBusConnection")]Message myQueueItem, ILogger log, int deliveryCount,
            string messageId,
            string deadLetterSource,
            System.Collections.Generic.IDictionary<string, object> UserProperties
            )
        {}
```

I am able to get deadletter messages, but somehow not receiving regular messages from the service bus queue,

Is this expected behaviour?

if so how can i receive regular/deadletter messages in the same function.

I am using function 2.0 runtime.

**Comment by v-anvari** [comment]
Hi @utkarsh24 , apologies for delayed response, to access the Dead letter Queue you can use the [syntax](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#path-to-the-dead-letter-queue).

For regular messages, you can set up [different modes](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#receive-modes) to receive messages

Please feel free to re-open this issue ticket if you are still facing an issue with service bus queues or if you are unclear with the provided solution.
