### ISSUE TITLE
Microsoft.Azure.WebJobs includes an old version of Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by retheon** [Azure/azure-webjobs-sdk#2381]
If you include the package `Microsoft.Azure.WebJobs (3.0.14)`, this includes the package `Microsoft.Extensions.Hosting (2.1.0)`, which is not compatible with EF 3.0.  The former works with `IHostingEnvironment` while the latter changed it to `IWebHostEnvironment`. This creates problems like [this one ](https://stackoverflow.com/questions/58163988/asp-net-core-3-0-get-hostingenvironment-method-not-found-in-extension).

**Comment by MichalGrzegorzak** [comment]
Any news guys?

**Comment by v-anvari** [comment]
_Below are my findings on the webjobs (.Net framework) package in visual studio._

Repro steps:

1. Visual studio - webjobs (.Net framework)
2. Updates with older version of _Microsoft.Azure.WebJobs_
![webjob framework](https://user-images.githubusercontent.com/66122429/95772565-9066eb80-0cda-11eb-8b13-ac8e5e1524b3.jpg)
3. Upon Upgrading to Latest versions of _Microsoft.Azure.WebJobs_ , installs the older versions of _Microsoft.Extensions.Hosting_ 
![hosting](https://user-images.githubusercontent.com/66122429/95772636-b12f4100-0cda-11eb-8fe3-60872e5e6fc4.jpg)
4. Latest versions of _Microsoft.Azure.WebJobs_ does not allow few of the types shown in the error list below
![error list](https://user-images.githubusercontent.com/66122429/95773114-7ed21380-0cdb-11eb-8be7-8908089b3b13.jpg)
5. The latest versions of _Microsoft.Azure.WebJobs_ works fine with the _"hostbuilder"_ shown in [the code sample](https://stackoverflow.com/questions/58163988/asp-net-core-3-0-get-hostingenvironment-method-not-found-in-extension)

**Comment by v-anvari** [comment]
The version hasn't been updated in the csproj file as seen below, to use the latest packages, we need to explicitly install the required package, so the dependency will be prioritized with the explicitly downloaded package. I have checked with the team for an update in the csproj file. As it is not a blocker, closing this issue 
https://github.com/Azure/azure-webjobs-sdk/blob/f3f78bab110503515a08c4440e06c900ca6e3cb4/src/Microsoft.Azure.WebJobs.Host/WebJobs.Host.csproj#L30

Latest version - https://www.nuget.org/packages/Microsoft.Extensions.Hosting/
