### ISSUE TITLE
Aggregate custom metrics when using LogMetric

### ISSUE THREAD

**Issue by deadwards90** [Azure/azure-webjobs-sdk#2382]
Is there anyway to get aggregations of custom metrics sent up by the ILogger using LogMetric? I know that the metrics that are logged under Host.Aggregator do this.

Alternatively, anyway I could use whatever Host.Aggregator uses? 

Specifically I'm using ApplicationInsights.

#### Repro steps

Provide the steps required to reproduce the problem

1. Call LogMetric with some key and value
2. Do it a lot over the lifetime of a function

#### Expected behavior

Metrics are rolled up like the ones for `Host.Aggregator`

#### Actual behavior

Each metric is a single metric.

#### Known workarounds

Guess you could write your own wrapper for the host and log out custom metrics that way but unsure how that would work with things like host shutdowns.

**Comment by v-anvari** [comment]
Hi @dantheman999301 , Apologies for the delayed response, kindly let us know if you were able to find a solution, if not, can you explain your scenario further, what are you trying to achieve.
