### ISSUE TITLE
Simple Timer function webjobs 3.0 exit code -1

### ISSUE THREAD

**Issue by charlesw23** [Azure/azure-webjobs-sdk#2383]
Please provide a succinct description of the issue.

1. Create a new project with the following setup

static void Main(string[] args)
        {
            var builder = new HostBuilder().UseEnvironment("Development");            
            
            builder.ConfigureWebJobs(b =>
            {
            b.AddAzureStorageCoreServices()
            .AddAzureStorage()
            .AddEventHubs()
            .AddTimers()
            ;
             });

            builder.ConfigureLogging((context, b) =>
            {
                b.AddConsole();
                
                string instrumentationKey = context.Configuration["APPINSIGHTS_INSTRUMENTATIONKEY"];
                if (!string.IsNullOrEmpty(instrumentationKey))
                {
                    b.AddApplicationInsightsWebJobs(o =>   o.InstrumentationKey = instrumentationKey);
                }
            });
            var host = builder.Build();
            using (host)
            {
                host.Run();
            }
        }

2. And the following function:

`        
[FunctionName("TimerTriggerCSharp")]
        public static void Run([TimerTrigger("0 */5 * * * *")]TimerInfo myTimer, ILogger log)
        {
            if (myTimer.IsPastDue)
            {
                log.LogInformation("Timer is running late!");
            }
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }`

3. Run the function in local development environment and go away for a long time.

#### Expected behavior

The timer fires every 5 minutes until stopped

#### Actual behavior

Job Exits with exit code of -1 after roughly 8+ hours

#### Known workarounds

None

#### Related information 

This is running local on dev machine in development mode and not in Azure

* Package version
`    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.14" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.0" />`

* Links to source

**Comment by fabiocav** [comment]
Do you observe the same behavior with a deployed WebJobs app? Do you have any logs you can share?
