### ISSUE TITLE
Parameter binding expression not working properly

### ISSUE THREAD

**Issue by dersia** [Azure/azure-webjobs-sdk#2384]
Binding expressions are used to bind values across bindings and triggers.
For HttpTriggers for example parameter binding expressions can be used to bind blob-name's to a value from the http-request.

This works great, if expressions are known ahead of running a webjob.
For example, if you bind to http-headers or http-query-params, but it does not work for the https -body.

In general the code supports binding expressions even for the json-payload-body, but the `ValidateContractCompatibility` stops this from working.

In [`C:\sources.net\azure-webjobs-sdk\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingTemplateExtensions.cs` line 66](https://github.com/Azure/azure-webjobs-sdk/blob/fca811638dd3c7dcf55905dea6837be5b30f5f15/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingTemplateExtensions.cs#L66), we check if the binding expressions is allowed by the contract:

```c#
public static void ValidateContractCompatibility(IEnumerable<string> parameterNames, IReadOnlyDictionary<string, Type> bindingDataContract)
{
	if (parameterNames != null && bindingDataContract != null)
	{
		foreach (string parameterName in parameterNames)
		{
			if (string.Equals(parameterName, SystemBindingData.Name, StringComparison.OrdinalIgnoreCase))
			{
				continue;
			}
			if (BindingParameterResolver.IsSystemParameter(parameterName))
			{
				continue;
			}

			if (!bindingDataContract.ContainsKey(parameterName))
			{
				throw new InvalidOperationException(string.Format(CultureInfo.CurrentCulture, Resource.UnableToResolveBindingParameterFormat, parameterName));
			}
		}
	}
}
```

At the time the Framework checks for available binding expression, not all binding expressions are available. Often allowed expressions only become available in runtime, because the payload isn't known before.
This is not just true for the HttpTrigger but also for every other trigger, payload is not known before run-time.

As far as I can see, there are two ways to fix this and allow binding expressions to bind to payloads.

- `bindingDataContract` will include the trigger parametername. This way binding expressions can use the parametername  and the "Dot notation" to bind. `{req.myField}` or `{queue.myField}` would than be possible.

- Removing the Validation all together. The validation only makes sense, if we know what will be available and we want to prevent the user from running into issues at run-time. But it is more limiting than helping, I would argue, that the benefits of using binding expressions to bind to payload is worth the risk. 

We could also go for 3rd option, which is allowing the user to opt out of the validation by setting an AppSetting like `ALLOW_UNSAFE_PARAMETER_BINDING_EXPRESSION`.

**Comment by dersia** [comment]
bump

**Comment by v-anvari** [comment]
Hi @dersia , Apologies for the delayed response, a similar issue like this is being tracked as a feature request which requires a breaking  change. Can you look into that issue and tell us if the ask is similar. This will help us understand the request better

https://github.com/Azure/azure-webjobs-sdk/issues/2713#issuecomment-845291397
