### ISSUE TITLE
FakeStorage nuget for Unit Testing

### ISSUE THREAD

**Issue by bb-naveenkumar** [Azure/azure-webjobs-sdk#2391]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

I have been trying to do webjob trigger unit testing and using FakeStorage seems like a good approach to do end to end test. However like test common NuGet there is no NuGet for FakeStorage (this is what I believe don't know for sure)

#### Expected behavior

Can there be or is there a NuGet for FakeStorage project under the test folder?

If there is one, can anyone help me on figuring out how to use or where is it.

If FakeStorage is not available can we get it in Nuget.

#### Actual behavior

Need to know how we can use FakeStorage in my project, if there is a nuget which have this or if we can create a nuget for it. 

#### Known workarounds

Workaround would be import code in my project which does not seems a right approach

#### Related information 

Provide any related information - This will help me reduce a lot of code import into my project which in turn could be readily available to anyone if it is in a NuGet.

* Package version - Any
* Links to source - https://github.com/Azure/azure-webjobs-sdk/tree/dev/test/FakeStorage

**Comment by bb-naveenkumar** [comment]
Also if there is a need to contribute, do let me know the process or guidelines so that I can follow them and contribute.

Many Thanks!

**Comment by v-anvari** [comment]
@bb-naveenkumar , apologies for the delayed response.  let us know if you are still looking for a fake storage for your unit testing.
