### ISSUE TITLE
Releases notes for 3.2 and 4.0 ?

### ISSUE THREAD

**Issue by jonathanantoine** [Azure/azure-webjobs-sdk#2392]
Hello,

Can we have some releases notes for these 2 nuget package ?

Thanks !

**Comment by v-anvari** [comment]
Hi @jonathanantoine, Apologies for the delayed response. I am sure there has been further releases in last few months. 

But, If you are still wanting the release notes, kindly help us with the package or link of the NuGet package that you are referring to.
