### ISSUE TITLE
how to run a console application as azure web job and window service in dotnet core

### ISSUE THREAD

**Issue by bilalmalik777** [Azure/azure-webjobs-sdk#2393]
I have console application which is working perfectly as azure web jobs in azure App Service code is given below. Now I want to deploy same console application as windows service in windows. Some client want it as windows service and some want it in azure as web-jobs. So please anyone helps me, how can i configure same console application to work as both web-job and windows service? There is one way in mind that is by passing argument in main method.
Is there any other more efficient way?
The application is developed in .net core 2.2

> 
  public static void Main(string[] args)
        {
            var environmentName = Environment.GetEnvironmentVariable("CORE_ENVIRONMENT");
            var builder = new ConfigurationBuilder()
                              .SetBasePath(Directory.GetCurrentDirectory())
                              .AddJsonFile($"appsettings.{environmentName}.json", true, true)
                              .AddEnvironmentVariables();
            CustomerEnvironment = environmentName;
            Configuration = builder.Build();
            if (ServiceProvider == null)
            {
                ServiceProvider = BuildServiceProvider();
            }
            var hostbuilder = new HostBuilder()
                                  .UseEnvironment(environmentName)
                                  .ConfigureWebJobs(b =>
                                  {
                                    b.AddAzureStorageCoreServices()
                                     .AddAzureStorage()
                                     .AddTimers();
                                  })
                                  .ConfigureHostConfiguration(c =>
                                  {
                                    c.AddConfiguration(Configuration);
                                  })
                                  .ConfigureLogging((context, config) =>
                                  {
                                    config.AddSerilog(dispose: true);
                                  })
                                  .UseConsoleLifetime();
            ThreadPool.SetMinThreads(200, 200);
            ServicePointManager.DefaultConnectionLimit = 1000;
            var host = hostbuilder.Build();
            using (host)
            {
                host.RunAsync().Wait();
            }
        }

**Comment by v-anvari** [comment]
Hi @bilalmalik777, running webjobs would be an alternative to windows service, you can find a bit more information on windows service migration in [here](https://stackoverflow.com/a/59476088).
