### ISSUE TITLE
Clarification: [AppInsight] - CosmosDB Dependency for Tcp protocol is not tracking automatically

### ISSUE THREAD

**Issue by rkbalu** [Azure/azure-webjobs-sdk#2400]
We are using Microsoft.Azure.DocumentDB.Core SDK with in Azure function V2.

AppInsight does not track the telemetry automatically when we use Protocol.Tcp and ConnectionMode.Direct as per https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies.

Are there any plan to support this in future? 

* Microsoft.Azure.DocumentDB.Core ( 2.3.0 )
* Microsoft.Azure.WebJobs.Logging.ApplicationInsights ( 3.0.8)

**Comment by v-anvari** [comment]
Hi @rkbalu ,  Apologies for the delayed response, thank you for your feedback! We will investigate this further and update as appropriate.

**Comment by v-anvari** [comment]
Hi @rkbalu , Apologies for the delayed response, As you have mentioned in your comments, this feature isn't supported yet and we do not have an ETA. I see that users are interested for this feature to be supported for redis.  Requesting you to submit a new idea in the below mentioned link.

![image](https://user-images.githubusercontent.com/66122429/122389056-264fc600-cf8e-11eb-9f81-efc8091a966d.png)

https://feedback.azure.com/forums/357324-azure-monitor-application-insights

**Comment by v-anvari** [comment]
Feature requests will be tracked in the feedback forms, closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue
