### ISSUE TITLE
How to spread out singleton locks across VMs

### ISSUE THREAD

**Issue by RickBlouch** [Azure/azure-webjobs-sdk#2401]
Is there a way to influence the VM a singleton function will execute on?

For example, let's say I have 2 VMs running a webjob project with 10 timer triggers (among other service bus triggers, etc).  I'm looking for a way to control it such that each VM would execute ~5 singleton functions, rather than one of the nodes processing all 10 (which is what seems to happen by default).

I realize one way to handle this differently would be to have a timer trigger that simply creates a service bus message and allow that to distribute evenly, however some of the timer triggers run frequently (5 seconds), and I don't want to (occasionally) trigger a second instance to run before the first is completed.  Timer trigger handles this scenario.

**Comment by v-anvari** [comment]
Hi @RickBlouch , Apologies for the delayed response. The job can be distributed while using dedicated plan. To know more about the plans, [here is the document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#overview-of-plans)
