### ISSUE TITLE
Blob binding expression to servicebus trigger property no longer works

### ISSUE THREAD

**Issue by mliesmons** [Azure/azure-webjobs-sdk#2403]
Please see also https://github.com/Azure/azure-functions-servicebus-extension/issues/44#issue-545396362

This is a real blocking issue and makes upgrading for us imposible.

**Comment by tomgallard** [comment]
I think this is also related to:

https://github.com/Azure/azure-functions-servicebus-extension/issues/48
https://github.com/Azure/azure-functions-servicebus-extension/issues/52

**Comment by alrod** [comment]
the issue is fixed in https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/4.1.1

**Comment by mliesmons** [comment]
Great, POCO binding works again, tnx.
