### ISSUE TITLE
IConfiguration not available in Startup class before service configuration

### ISSUE THREAD

**Issue by idg10** [Azure/azure-webjobs-sdk#2406]
Classes that perform initialization at startup via the `Microsoft.Azure.WebJobs.Hosting.WebJobsStartup` assembly attribute have no documented way to obtain configuration settings. An `IConfiguration` is available through dependency injection, but that is only accessible after service configuration is complete.

Compare this with startup types in ASP.NET Core, which are able to define a constructor that takes an argument of type `IConfiguration`. This is important if you need access to configuration settings as part of your service configuration code. The WebJobs SDK should offer this same service.

Doing this would also fix the equivalent problem in the Azure Functions SDK - https://github.com/Azure/azure-functions-host/issues/4577 - which relies on WebJobs for this feature.

#### Repro steps

1. Create a new Azure Function project in Visual Studio 2019
2. Define a class named `Startup`, which implements the `IWebJobsStartup` interface
3. Add an `[assembly:WebJobsStartup(typeof(MyApp.Startup))]` attribute to declare that this is a startup class.
4. Defined a constructor taking a single argument of type `IConfiguration` in `Startup`.
5. Run.
6. Note that the function fails to start, with an error complaining that no parameterless constructor exists on `Startup`.

#### Expected behavior

Should be the same as in ASP.NET Core: the `Startup` class should be instantiated successfully, and the `IConfiguration` passed should provide access to all the settings normally available through this interface. (I.e., since we're using the Functions host here, that should include everything in the `local.settings.json` file's `Values` section, and also a setting indicating whether we're running in the `Development` environment or something else.

#### Actual behavior

Host fails to start.

#### Known workarounds

The only way to avoid the error is to provide a parameterless constructor (either explicitly, or by not writing any constructors) on `Startup`. But then there's no good way to get the configuration settings. You can dig into the `IServiceCollection` passed via the `IWebJobsBuilder`, and find the entry for `IConfiguration` but this is not a documented technique, and can cause problems because it bypasses the normal lifecycle management performed by DI containers.

Alternatively you can attempt to code your service initialization without access to configuration settings. This is sometimes OK, but it can often be onerous or even impossible.

Another alternative is to attempt to discover configuration settings yourself. Creating a new configuration builder and adding in an environment variable based provider works, but again this relies on undocumented behaviour: it so happens that the local development host for debugging functions copies all the settings from `local.settings.json` into environment variables. But this doesn't seem to be guaranteed. And it doesn't help with the various other elements that get added to the `IConfiguration` the host builds. (It puts something like 6 different providers in there, so looking in the environment only sees a subset of the settings).

#### Related information 

I've put together a draft PR at https://github.com/Azure/azure-webjobs-sdk/pull/2405 which I think shows that this is not a particularly complex thing to add.

**Comment by MarkAtAgilliance** [comment]
Anything moving on this?

Given that we have a         
`public` override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)

that allows us to add in file-based json configurations, it seems then that we cannot use them in the Configure() override.

Similar to Ian, I have used a temporary config in Configure() to work around this but wonder if ConfigureAppConfiguration is even useful if we can't use it in Configure() nor use it for options.

**Comment by pawel-zolty** [comment]
I suppose that it could be quite a good workaround since _Microsoft.Azure.Functions.Extensions_ version 1.1.0:

```
IConfiguration configuration = builder.GetContext().Configuration;
builder.Services.MyCustomExtension(configuration);
```

**Comment by v-anvari** [comment]
Hi @idg10 , I see the PR has been reviewed and required changes were made, as per the comment here - https://github.com/Azure/azure-webjobs-sdk/pull/2405#issuecomment-627979743

Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue
