### ISSUE TITLE
Blob triggered function causes unhandled exception

### ISSUE THREAD

**Issue by backan10** [Azure/azure-webjobs-sdk#2413]
I have a blob triggered Azure function created using the VS2019 (v16.4.0) template.

When running the function crashes with unhandled exception: "System.Private.CoreLib: The given key 'LogType' was not present in the dictionary."

![image](https://user-images.githubusercontent.com/34470692/70634031-cd350280-1c31-11ea-906e-f6c705e21c38.png)

Azure Functions Core Tools (2.7.1948 Commit hash: 29a0626ded3ae99c4111f66763f27bb9fb564103)
Function Runtime Version: 2.0.12888.0

**Comment by brettsam** [comment]
@semawah -- do you happen to have Hierarchical Namespace enabled for your storage account?

**Comment by backan10** [comment]
Yes, that I have.

**Comment by brettsam** [comment]
Thanks, that explains it. There's some subtle differences when using the Storage APIs against Data Lake: https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-known-issues#issues-and-limitations-with-using-blob-apis. But this fix should handle that.
