### ISSUE TITLE
CancellationToken never cancelled in Triggered WebJob

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-webjobs-sdk#2420]
I'm having a triggered webjob which executes some `async` actions (Graph API calls) in a loop.
When trying to use the `cancellationToken` to handle application shutdown, it seems it's never set to cancelled.

My webjob is initiated with:

```
using var host = hostBuilder.Build();

await host.StartAsync();

var jobHost = host.Services.GetService<IJobHost>();
await jobHost.CallAsync(nameof(Functions.RunBoxSync));

await host.StopAsync();
```
and Functions.RunBoxSync is defined as such:
```
public async Task RunBoxSync(ILogger log, CancellationToken cancellationToken)
```
But, as said, the cancellationToken is never cancelled.

How do I pass the **correct** cancellationToken to the Function?

**Comment by divinci** [comment]
See issue #2088 only a year old!

**Comment by gidziu** [comment]
same issue, is anyone working on this? Probably it is better to stay away from thsi webjob business

**Comment by mathewc** [comment]
In your code above, you're awaiting function completion BEFORE calling stop. So the function has completed before the token is cancelled by stop, so it's expected that the token your function receives isn't cancelled. What does your function body look like?

**Comment by v-anvari** [comment]
Hi @NickSevens , Apologies for the delayed response. Let us know if you are still facing the issue, so that we can look into it further
