### ISSUE TITLE
 No job functions found when using ProjectReference/PackageReference in some projects, version 3.x

### ISSUE THREAD

**Issue by clauchiorean** [Azure/azure-webjobs-sdk#2422]
I have a common lib project that is used by all the background workers that are using the webjobs sdk. This is the only lib that has the references to the webjob sdk libs.

I'm using package reference and project reference with the new csproj version.

I have a weird case in which the host does not find any functions in some workers.

I've traced the problem in the function AssemblyReferencesSdkOrExtension in the DefaultTypeLocater from Microsoft.Azure.Webjobs.Host
This happens because the Microsoft.Azure.WebJobs, Microsoft.Azure.WebJobs.Host are not found as dependencies

Here are the dependencies of the common lib and 2 workers:
 
Common lib
![A2Z Workers Common](https://user-images.githubusercontent.com/4329538/73208920-f3662180-414f-11ea-9bf5-0f4fe5234206.png)

No functions found 
![A2Z Worker Indexing Build](https://user-images.githubusercontent.com/4329538/73208917-f2cd8b00-414f-11ea-8152-fdc95d285489.png)

Functions found
![A2Z Workers Indexing](https://user-images.githubusercontent.com/4329538/73208921-f3662180-414f-11ea-81d7-c261c218f0a6.png)

I don't know if this is a problem of the webjobs sdk or of the whole package reference and project reference system because the assemblies from the common lib don't appear as dependencies.

As a workaround I had to comment the code bellow form the DefaultTypeLocator.
![DefaultTypeLocator](https://user-images.githubusercontent.com/4329538/73209584-3248a700-4151-11ea-9b2f-5d1932c68ced.png)

I'll try to reproduce this behavior outside of our solution.
I understand why you are using the AssemblyReferencesSdkOrExtension function to filter assemblies that are not referencing the webjobs sdk but this is causing the above behavior is some cases.

I've did not see this in the v2.x sdk.

**Comment by digitalfuller** [comment]
I'm using a similar project structure to you and had the same issue.

I found that if I added the FunctionNameAttribute to my method then the function was found at startup (no additional file/project/nuget references required).

e.g.
```csharp
[FunctionName("something")]
public async Task DoSomething([QueueTrigger("the-queue")] SomethingData somethingData)
{
    ...
}
```

**Comment by mountain65** [comment]
One year later this is still a problem. Maybe add it to the documentation? "When you move your reference to the Webjob SDK to a different project to re-use som initialization code make sure you add the [FunctionName] attribute to your functions"

**Comment by v-anvari** [comment]
Hi @clauchiorean, Apologies for the delayed response. The issue was somehow lost in the course, please let us know how can we help you further. If the scenario needs to be documented, then please raise an issue in - https://github.com/MicrosoftDocs/azure-docs/issues/new
