### ISSUE TITLE
Concurrency issue in AsyncCollector for Table Storage while doing AddAsync 

### ISSUE THREAD

**Issue by abbasc52** [Azure/azure-webjobs-sdk#2425]
We are using IAsyncCollector for table storage to push data to table. In our use case, we need to push up to 5 table entities parallelly in an async manner. 
We are getting frequent batch size exceeded error. I suspect it is due to -
https://github.com/Azure/azure-webjobs-sdk/blob/a5049fe18e80699ebe7b6b3f0e144c3adc582b2c/src/Microsoft.Azure.WebJobs.Extensions.Storage/Tables/TableEntityWriter.cs#L109

Can we add batch splitting if we exceed the maxBatchSize ?
Also there might be concurrency issues like batch pushing similar items twice if they are the 2 addAsync calls at the same time when batchSize has reached.

#### Repro steps

1. Try pushing more than 100 entities with same partitionKey with some concurrency(i used 5)

#### Expected behavior

AddAsync should push entities with multiple batches and not throw error

#### Actual behavior

AddAsync throws maximum batchSize exceeded error.

#### Known workarounds

limiting batch size to 100

#### Related information 

* Package version: Microsoft.Azure.WebJobs.Extensions.Storage 3.0.8

**Comment by v-bbalaiagar** [comment]
Hi @abbasc52, Apologies for the delayed response, We would like to know if you are still seeing these error.

**Comment by abbasc52** [comment]
hi @v-bbalaiagar, I used semaphore as a workaround in my code to get around this issue.

```c#
 var semaphore = new SemaphoreSlim(1, 1);


//inside my parallel execution
await semaphore.WaitAsync();
try{
 await collector.AddAsync(@event);
}
finally{
   semaphore.Release();
}
```

**Comment by v-bbalaiagar** [comment]
Hi @abbasc52, Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue
