### ISSUE TITLE
WebJobs Dashboard needs to support TLS1.2 for its outbound calls

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk#2436]
The webjobs dashboard is a legacy component but it is still run in some environments that are undergoing upgrades, including TLS 1.2 enforcement. Right now the dashboard will fail if it tries to connect azure storage and TLS 1.2 is enforced.

I suspect viable options are:
- retarget the dashboard at a newer version of .NET Framework
- configure service point manager, something like this:

```csharp
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
```

**Comment by paulbatum** [comment]
This work item needs to be complete by early April to align with an Azure Stack release.

**Comment by apwestgarth** [comment]
Six months since this was raised, can I get an ETA on it's resolution?

**Comment by soninaren** [comment]
This is now complete.

**Comment by paulbatum** [comment]
The fix was made and deployed to Azure Stack, but deploying to public Azure is still pending. Reopening until that happens.

**Comment by soninaren** [comment]
This has now been deployed to public Azure.
