### ISSUE TITLE
Custom ITelemetryInitializer in azure function .Net Core 3.1 does not work

### ISSUE THREAD

**Issue by amigup** [Azure/azure-webjobs-sdk#2442]
Custom `ITelemetryInitializer` in azure function .Net Core 3.1 does not work.

I've implemented a custom ITelemetryInitializer and injected using Dependency injection as Singleton but `Initialize` method of `ITelemetryInitializer` of custom class is not hit.

#### Repro steps

1. Created a new .Net core 3.1 Azure function with Http binding.
1. Installed Microsoft.Azure.Functions.Extensions 1.0.0 package
1. Installed Microsoft.ApplicatoinInsights 2.13.1 package

Created a new Custom `ITelemetryInitializer` class

```
public class MyCustomTelemetryInitializer : ITelemetryInitializer
{
    public MyCustomTelemetryInitializer()
    {
    }

    public void Initialize(ITelemetry telemetry)
    {
        if (telemetry == null)
        {
            return;
        }

        telemetry.Context.GlobalProperties["SomePropertyName"] = "SomePropertyValue";
    }
}
```
Added Startup implemenation
```

[assembly: FunctionsStartup(typeof(SomeNamespace.Startup))]

namespace SomeNamespace
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<ITelemetryInitializer, MyCustomTelemetryInitializer>();

        }
    }
}

```
The configure method is hit (If I hit the breakpoint) but breakpoint at `MyCustomTelemetryInitializer` is never hit and due to that the custom telemetry properties are not injected.

#### Expected behavior

The custom properties injected by `MyCustomTelemetryInitializer` should be logged.

#### Actual behavior

The custom properties injected by `MyCustomTelemetryInitializer` are **NOT** being logged.

#### Known workarounds

NA

#### Related information 

1. .Net Core : 3.1
1. Microsoft.NET.Sdk.Functions - 3.0.1
1. Microsoft.Azure.Functions.Extensions 1.0.0 
1. Microsoft.ApplicatoinInsights 2.13.1

Tried downgrading the Microsoft.ApplicatoinInsights to 2.11.0 but still did not work.

**Comment by amigup** [comment]
Any update on this issue?

**Comment by amigup** [comment]
Any update on this issue? @brettsam - Can you please assist here?

**Comment by brettsam** [comment]
Is this not getting hit when running locally? If so, make sure you have an `APPINSIGHTS_INSTRUMENTATIONKEY` in your local.settings.json file.

**Comment by amigup** [comment]
I do have the setting in local.settings.json; even then in local it does not hit.
![image](https://user-images.githubusercontent.com/16287600/78576627-8dca9b80-784a-11ea-984c-5220cef9eed0.png)


However, after updating the package Microsoft.NET.Sdk.Functions to 3.0.5, things started working.

So closing this thread. Thanks for your assistance.

**Comment by dongup** [comment]
I have the same issue, and I am using Microsoft.NET.Sdk.Functions 4.0.1. Please help me, thank you.

**Comment by KamranMammadov** [comment]
Any updates? .Net 6.0 isolated
