### ISSUE TITLE
Broken wiki link

### ISSUE THREAD

**Issue by estensen** [Azure/azure-webjobs-sdk#2457]
#### Repro steps
1. Go to https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings
2. Press `Simple binding` link
2. 404

**Comment by MisinformedDNA** [comment]
+1, expect there are actually lots of broken links on that page.

**Comment by v-anvari** [comment]
Hi @estensen, @MisinformedDNA , Thank you for pointing this out to us. We will update the WIKI page with the updated links. 

CC @brettsam, if you had any comment on this ask.

**Comment by v-anvari** [comment]
The page has been updated accordingly. Closing as resolved
