### ISSUE TITLE
Upgrade Snapshot Collector version to 1.3.7

### ISSUE THREAD

**Issue by renatosalas** [Azure/azure-webjobs-sdk#2465]
Snapshot Collector version (1.3.4) does not have the Gov Clouds supports. (it was introduced in 1.3.5)

Could it be upgraded to the latest version 1.3.7, please?

Reference: https://github.com/Azure/azure-webjobs-sdk/blob/40572c8f719e044b0a58184697793791cdf8823a/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj#L29

**Comment by renatosalas** [comment]
I could not assign people. @brettsam

**Comment by fabiocav** [comment]
@brettsam , should we be moving this to 74?

**Comment by fabiocav** [comment]
@brettsam assigning this back to `Triaged`, please update if needed.

**Comment by brettsam** [comment]
Submitted the PR -- will get this in.
