### ISSUE TITLE
Azure WebJob fails to start with null reference exception

### ISSUE THREAD

**Issue by stasyess** [Azure/azure-webjobs-sdk#2466]
We have a WebJob project that is using Microsoft.Azure.WebJobs 1.1.2.
WebJob has a BlobTrigger function to unzip files and push them to another folder in a container:

```
 [Singleton(Mode = SingletonMode.Function)]
        public static void 
 Unzip([BlobTrigger("%blobContainer%/%blobZippedLogFiles%/_new/{name}.zip")]CloudBlockBlob 
 blob,
            [Blob("%blobContainer%/%blobZippedLogFiles%/_processed/{name}.zip")]CloudBlockBlob 
 processedBlob)
        {
            try
            {
                using (Stream input = blob.OpenRead())
                {
                    UnzipData(input, blob.Container);
                }

                processedBlob.StartCopy(blob);
                blob.Delete();
            }

            catch (Exception) { }
        }
```

However, the web job kept failing to start with a null reference exception, until we noticed that in another folder we had a blob of type AppendBlob. 
Stack trace:

at Microsoft.Azure.WebJobs.Host.Storage.Blob.StoragePageBlob.get_Name()   at Microsoft.Azure.WebJobs.Host.Blobs.StorageBlobExtensions.ToBlobPath(IStorageBlob blob)   at Microsoft.Azure.WebJobs.Host.Blobs.Listeners.BlobTriggerExecutor.<ExecuteAsync>d__1.MoveNext()  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 

Removing this blob has solved the issue.
However, it would be nice to get some more readable exception that blob type is unsupported.
I see that it always assumes that blob has a page type, if it is not block type in StorageBlobContainer.cs:

```
 private static IStorageBlob ToStorageBlob(IStorageBlobContainer parent, ICloudBlob sdkBlob)
        {
            Debug.Assert(sdkBlob != null);

            CloudBlockBlob blockBlob = sdkBlob as CloudBlockBlob;

            if (blockBlob != null)
            {
                return new StorageBlockBlob(parent, blockBlob);
            }
            else
            {
                CloudPageBlob cloudPageBlob = sdkBlob as CloudPageBlob;
                Debug.Assert(cloudPageBlob != null);
                return new StoragePageBlob(parent, cloudPageBlob);
            }
        }
```

**Comment by v-anvari** [comment]
Hi @stasyess , Apologies for the delayed response, are you still seeing this issue, do you want to see a warning explaining the above scenario?
