### ISSUE TITLE
Update appinsights SDK to 2.13

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-webjobs-sdk#2475]
Appinsights updated their SDK to include this fix https://github.com/microsoft/ApplicationInsights-dotnet/pull/1661 and functions needs to pull this in.

cc: @brettsam @lmolkova

**Comment by v-anvari** [comment]
Hi @yojagad, Do we have any updates here, request you to Triage the issue in case it still requires implementation.

**Comment by yojagad** [comment]
AppInsights is at 2.16. https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj . This can be closed.
