### ISSUE TITLE
Improve Queue Trigger\Storage binding to be more resilient when transient issues occur.

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk#2476]
The Queue Trigger may timeout after two minutes and this causes a restart of the Host.

E.G

System.TimeoutException : The operation 'GetMessages' with id '60c56e17-66e8-49a3-b1dc-9ac5b393eabd' did not complete in '00:02:00'.    at async Microsoft.Azure.WebJobs.Extensions.Storage.TimeoutHandler.ExecuteWithTimeout[T](String operationName,String clientRequestId,IWebJobsExceptionHandler exceptionHandler,Func`1 operation) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\TimeoutHandler.cs : 30

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a Timer Trigger to put 5000 messages into a Queue.
E.G

using System;

public static void Run(TimerInfo myTimer, ICollector<CustomQueueMessage> outputQueueItem, ILogger log)
{
    log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");

    for (int i = 0; i < 5000; i++)
    {
        var queueMessage = new CustomQueueMessage {PersonName= i.ToString(), Title= "Mr " + i.ToString()};
        outputQueueItem.Add(queueMessage);
    }

}

public class CustomQueueMessage
{
    public string PersonName { get; set; }
    public string Title { get; set; }
}

2. Step B

Write a Console App or Function to poll this Queue.
This needs to be in another region or geographically distant from the storage account. 

Sample Code attached. 

[timeouthandler.zip](https://github.com/Azure/azure-webjobs-sdk/files/4487525/timeouthandler.zip)

#### Expected behavior

The Queue Trigger should be able to handle the transient issues.

System.IO.IOException
  HResult=0x80131620
  Message=Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1107

Inner Exception 1:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#### Actual behavior

The application restarts because of the Timeout handler and a number of customers are seeing this. 

#### Known workarounds

No workarounds. 
Testing with a new approach in using this code to see if it helps. 

                string clientRequestId = Guid.NewGuid().ToString();
                OperationContext context = new OperationContext { ClientRequestID = clientRequestId };
                Console.WriteLine("Entering Loop {0}{1}", i.ToString(),DateTime.Now.ToString());
                using(CancellationTokenSource cts = new CancellationTokenSource()){
                    cts.CancelAfter(_cancelTimeout);
                    await queue.GetMessagesAsync(32,
                        _visibilityTimeout,
                        options: null,
                        operationContext: context,
                        cancellationToken: cts.Token);
                };

#### Related information 

Provide any related information 

* Package version
3.0.10 and 4.0.0.0-Preview1
* Links to source

https://github.com/Azure/azure-webjobs-sdk/blob/4130350327c6d637d48456222de7e658c6cf729a/src/Microsoft.Azure.WebJobs.Extensions.Storage/Queues/Listeners/QueueListener.cs#L201

                   batch = await TimeoutHandler.ExecuteWithTimeout("GetMessages", context.ClientRequestID, _exceptionHandler, () =>
                    {
                        return _queue.GetMessagesAsync(_queueProcessor.BatchSize,
                            _visibilityTimeout,
                            options: null,
                            operationContext: context,
                            cancellationToken: cancellationToken);
                    });

**Comment by FinVamp1** [comment]
https://github.com/Azure/azure-webjobs-sdk/pull/2486 will help with this.

**Comment by FinVamp1** [comment]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/4.0.0-preview2 should help on this.

**Comment by velocicoder-1** [comment]
Even after upgrading to 4.0.0 I am still having this issue:
System.TimeoutException : The operation 'GetMessageAsync' with id '' did not complete in '00:03:00'.

**Comment by brettsam** [comment]
@velocicoder-1 -- can you let us know how you're set up? What region is your site in? What about your storage account? What kind of account is it?

**Comment by velocicoder-1** [comment]
**Function app:**
3.x runtime
location: USGov Virginia
app service plan: P1V2

**Storage account:**
location: USGov Virginia, USGov Texas
account kind: StorageV2 (general purpose V2)

I have noticed that the exception occurs more often when one of the functions is performing a task that takes longer than 5 minutes.

**Comment by brettsam** [comment]
Also, did you remove the id from your copied error message above, or was it empty?

**Comment by velocicoder-1** [comment]
I removed it.

**Comment by brettsam** [comment]
I think I know the issue... I believe it's due to https://github.com/Azure/azure-storage-net/issues/999. 

When I get confirmation from the storage team, it should be easy for us to roll out a 4.0.1 fix that explicitly sets the NetworkTimeout rather than relying on the default.

**Comment by velocicoder-1** [comment]
I see. Ok sounds good thanks.

**Comment by brettsam** [comment]
I'll release 4.0.1 tomorrow morning -- thank you for the report @velocicoder-1.

**Comment by velocicoder-1** [comment]
Thank you for the quick response. I will let you know if I have any trouble with the latest release.

**Comment by brettsam** [comment]
4.0.1 is now available: https://github.com/Azure/azure-webjobs-sdk/releases/tag/storage-v4.0.1

**Comment by velocicoder-1** [comment]
@brettsam, unfortunately I am seeing the same exception as before with the latest release.

**Comment by brettsam** [comment]
If you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

**Comment by velocicoder-1** [comment]
UTC Execution Time: 2020-06-02T18:16:34.2749751Z
Execution ID Value: 597f4304-b199-4db7-bb65-52d7294caf3d
Region: USGov Virginia

**Comment by brettsam** [comment]
Could you try explicitly adding a reference to the 11.1.7 Storage Queue package and see if that helps at all?

```
<PackageReference Include="Microsoft.Azure.Storage.Queue" Version="11.1.7" />
```

**Comment by velocicoder-1** [comment]
I added the reference and am still seeing the same exception.

**Comment by brettsam** [comment]
Yeah I see that from the backend logs. I was able to confirm that this package cancels `GetMessagesAsync` correctly (without an exception) in my repro app so I'm not entirely sure what you're running into. The only other scenario that I can think of is that you're hitting some kind of issue where the cancellation isn't able to correctly fire. It's interesting that I can see a bunch of your triggers all fail simultaneously sometimes, which leads me to believe there may be something else happening.

Can you share your .csproj file? I want to see what other packages you are referencing and your `TargetFramework` -- is it `netcoreapp3.1`?

**Comment by brettsam** [comment]
Also -- could any of your functions be doing anything that are consuming resources (threads, connections) while they are running? Anything that could block timers and connections in the process?

You seem to be hitting this a lot and I do see an interesting correlation here -- one function, `PdfOcrStart` seems to be running whenever these timeouts occur, and often it doesn't complete. Could that function be doing something that's blocking these requests? I see that it typically takes 6+ minutes to run. Can you temporarily disable this function to see if things run more smoothly?

**Comment by velocicoder-1** [comment]
The target framework is netcoreapp3.1.
csproj file:
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mandrill" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Storage.Queue" Version="11.1.7" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.16" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
    <PackageReference Include="SkiaSharp" Version="1.68.3" />
    <PackageReference Include="Syncfusion.DocIO.Net.Core" Version="18.1.0.54" />
    <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="18.1.0.54" />
    <PackageReference Include="Syncfusion.PDF.OCR.Net.Core" Version="18.1.0.52" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <None Update="ocr_tesseract64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="pdfix64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TesseractBinaries\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tessdata\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="" />
    <ProjectReference Include="" />
  </ItemGroup>
  <ItemGroup>
    <None Update="pdf_to_html64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>`
 
Two projects are referenced, but I am excluding their paths. 


 

When PdfOcrStart is executing this does happen more often, but that particular function was only just recently added to the function app and was originally in its own webjob. The exception was still occurring in the function app. If you look far enough back in the logs you will see it. It has only been apart of the function app since around 5/20/2020. The function is used to perform OCR on PDF documents programatically. Depending on the contents of the document, the function could take anywhere from a few seconds to over an hour to complete. I cannot think of any way that a long running function could block requests to get messages from a storage queue. If the PdfOcrStart function could theoretically still cause this problem for the function app from a webjob, would the webjob also get the same exception? I tried finding any occurrences of similar behavior in the webjob logs but I have not been able to find any. The target framework of the webjob is **net48**. I will disable that function and see if the exception still occurs.

Here are two log files (with sensitive info removed) that you may find useful:
https://github.com/velocicoder-1/hello-world/blob/master/OCRFUNCTIONINWEBJOB.LOGS.06.03.2020.1PM.json
https://github.com/velocicoder-1/hello-world/blob/master/OCRFUNCTIONINCLUDED.LOGS.06.03.20209AM.json
One file has the logs showing the exception in the function app you have been looking at and the other shows the exception in the same function app, except with the pdfocrstart function in a webjob and not apart of the function app. 

Please let me know if you need any other information.

**Comment by velocicoder-1** [comment]
Similar issue: https://github.com/Azure/azure-webjobs-sdk/issues/2506

**Comment by v-anvari** [comment]
Hi @FinVamp1 , Do we support this scenario fully as of today? Is there any improvement in supportability yet to be made, since there are few users receiving the error

**Comment by FinVamp1** [comment]
@v-anvari  The improved error handling was added in version 3.0.11 and above of the Storage Extension. https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/3.0.11 . Customers seeing this issue first need to migrate to that version or higher and then see if they see the issue resolved. Depending on the geographic location of the Storage account in relation to the Azure Functions App there may still be increased latency.
