### ISSUE TITLE
Classic .NET Web App - Web Jobs v1 or v3? Support for v1?

### ISSUE THREAD

**Issue by JakubHolovsky** [Azure/azure-webjobs-sdk#2479]
We have a classic .NET Web App (4.7.2) however recently I needed to add time triggered Web Job. As soon as you create a Web Job it adds it with the Nuget package version 1.12 My first instinct is to push the version to the latest but as soon as you add version v3 and up (maybe this happened for v2 as well) it starts adding these .NET core packages which in classic .NET app solution seem very strange/uncomfortable especially since the documentation for configuration sometimes refers to methods like "AddDbContext" but the DbContextType needs to inherit from .NET Core DbContext (which in our case is simply not possible).

So my question is - for classic .NET Framework should v1.12 be used or v3 is safe to use as well?

I know that they are saying in their docs that it's designed to be used in classic .NET and .NET Core apps but the reality is not convincing me much.

Is Web Jobs v1 still OK to use and will be OK for the coming months?

**Comment by v-bbalaiagar** [comment]
Hi @JakubHolovsky, Apologies for the delayed response, For classic .NET Framework v3 should be safe to use and web jobs v1 is OK for the coming months. 
If the question is about using Web Jobs SDK is .NET Framework apps, as long as they're on 4.6.1 and above, you should be able to reference and use the SDK.

**Comment by JakubHolovsky** [comment]
OK, fine with that :)
