### ISSUE TITLE
Continuous webjob does not restart on failure 

### ISSUE THREAD

**Issue by Glebby** [Azure/azure-webjobs-sdk#2493]
I have an indefinitely-running continious webjob (sdk version 2.2). I would expect the webjob to restart automatically if any exception is thrown, but it doesn't. How can I make the webjob to restart autiomatically upon failure?

        static void Main()
        {
            var config = new JobHostConfiguration()
            {
                JobActivator = new UnityJobActivatorDependencyScope(UnityConfig.GetConfiguredContainer())
            };

            if (config.IsDevelopment)
            {
                config.UseDevelopmentSettings();
            }
            ServicePointManager.DefaultConnectionLimit = 10;

            WebJobsShutdownWatcher watcher = new WebJobsShutdownWatcher();

            XmlConfigurator.Configure();
            Logger.SetProvider(new Log4NetLoggingProvider("RebatesWorker"));

            var instrumentationKey = ConfigurationManager.AppSettings["APPINSIGHTS_INSTRUMENTATIONKEY"];

            var filter = new LogCategoryFilter();
            filter.DefaultLevel = LogLevel.Warning;
            filter.CategoryLevels[LogCategories.Function] = LogLevel.Error;
            filter.CategoryLevels[LogCategories.Results] = LogLevel.Error;

            var loggerFactory = new LoggerFactory();
            config.LoggerFactory = loggerFactory
                .AddApplicationInsights(instrumentationKey, filter.Filter)
                .AddConsole();

            AppDomain currentDomain = AppDomain.CurrentDomain;
            currentDomain.UnhandledException += new UnhandledExceptionEventHandler((s, a) =>
            {
                var e = (Exception)a.ExceptionObject;
                Logger.LogException(e);
                if (e.InnerException != null)
                {
                    Logger.LogException(e.InnerException);
                }
            });

            var host = new JobHost(config);
            // The following code ensures that the WebJob will be running continuously

            host.CallAsync(typeof(Functions).GetMethod("StartRebatesWorker"), watcher.Token);
            host.RunAndBlock();
        }

    public class Functions
    {
       [Singleton]
        [NoAutomaticTrigger]
        public async Task StartRebatesWorker(ILogger logger)
        {
            try
            {
                  // ....here I am setting up event handlers listening for some events.

                 while (true)
                {
                    await Task.Delay(TimeSpan.FromSeconds(1));
                }
            }
            catch (Exception e)
            {
                LogException(e);
                throw;
            }
        }
}

**Comment by v-anvari** [comment]
Hi @Glebby, Let us know if you are still facing the issue, if yes, we require additional information to find the errors. Please provide us the details of your App name and timestamp of the error and repro steps
