### ISSUE TITLE
Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.5.1.0 

### ISSUE THREAD

**Issue by vicky96talokar** [Azure/azure-webjobs-sdk#2502]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by v-anvari** [comment]
Hi @vicky96talokar ,  Apologies for the delayed response, are you still seeing this error, If yes, could you give us more information for us to understand the root cause of the error and resolve it for you
