### ISSUE TITLE
QueueTrigger - CloudQueueMessage  doesnt work

### ISSUE THREAD

**Issue by bbakermmc** [Azure/azure-webjobs-sdk#2504]
If you make a trigger on 4.0.1 that use CloudQueueMessage  it wont work, it wants a string.

public static async Task RunAsync([QueueTrigger(SFQueues.DownloadBackupQueue)]
                                          CloudQueueMessage queueItem,
                                          ILogger log)

var queueObject = JsonConvert.DeserializeObject<QueueRecordDto>(queueItem.AsString);

**Comment by bbakermmc** [comment]
@brettsam you going to take a look at this, this currently breaks the current functionality

![image](https://user-images.githubusercontent.com/30090055/83890984-86285580-a71a-11ea-87e6-3a22fe754f8f.png)

**Comment by brettsam** [comment]
I think you're seeing this b/c your `using` statement is still using `Microsoft.WindowsAzure.Storage.Queue`. 

It now needs to be `Microsot.Azure.Storage.Queue` -- https://github.com/Azure/azure-webjobs-sdk/releases/tag/storage-v4.0.0. 

If that still doesn't fix it, please let me know and I can investigate. But I tried both namespaces and `WindowsAzure` gave me this error, so I suspect that's what you're seeing.

**Comment by bbakermmc** [comment]
Thanks, of course we would be changing namespaces for the like 10x for all this azure stuff.
