### ISSUE TITLE
Web Job not working when adding a new message on the Service Queue 

### ISSUE THREAD

**Issue by manjunathreddy1** [Azure/azure-webjobs-sdk#2516]
We have configured continuously running web job to get triggered when the new message is added to the queue. But some time it is not getting triggered and if the web job is restrted it will start processing messages from queue and sometimes it is taking 10 to 15 minutes for the web job to get triggered.

Repro steps

When there is a new message in the storage queue, web job is not picking that message until we re-start the web-job.

1. Configure the web job to get triggered from queue

2. Add a message to the queue

Expected behavior

Expected behavior is that web job should get triggered immediately.

Actual behavior

Web job is not getting triggered until we restart the webjob and sometimes it taking 10 to 15 minutes to get triggered automatically.

**Comment by v-bbalaiagar** [comment]
Hi @manjunathreddy1,  Apologies for the delayed response, We tried to reproduce and we are able to trigger the web job as expected. Let us know if you are still facing the same issue, if yes please provide us the latest error logs and share us the function app details privately by following the below link.
https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately
