### ISSUE TITLE
Microsoft.Azure.WebJobs 3.0.18 (and associated packages) not released to NuGet

### ISSUE THREAD

**Issue by Methuselah96** [Azure/azure-webjobs-sdk#2517]
This GitHub repository shows a Microsoft.Azure.WebJobs 3.0.18 release on June 5 (https://github.com/Azure/azure-webjobs-sdk/releases/tag/v3.0.18), but there has been no corresponding version change on NuGet (https://www.nuget.org/packages/Microsoft.Azure.WebJobs/), which still has the latest version as 3.0.16.

**Comment by czb182** [comment]
please release to nuget

**Comment by Methuselah96** [comment]
Looks like it's been released (https://www.nuget.org/packages/Microsoft.Azure.WebJobs/3.0.18). Thanks!
