### ISSUE TITLE
Make QueueTrigger poll interval configurable per queue

### ISSUE THREAD

**Issue by zmarty** [Azure/azure-webjobs-sdk#2518]
Azure Functions v3 and .NET Core 3.1

In host.json under the queues JSON key we can set some system-wide settings on how often to poll for new Azure Storage queue items. 

Can you please make the poll interval configurable as a constructor of QueueTriggerAttribute? We use more than 500 queues and we want to make some poll more aggressively, while let most of them poll more leisurely.

Right now we need to use the more aggressive setting for all of them, which is causing our Azure Storage account to hit the upper limit of 20K requests per second !

Thanks!

**Comment by zmarty** [comment]
Sort of / maybe related: https://github.com/Azure/azure-webjobs-sdk/issues/4

**Comment by brettsam** [comment]
@mathewc didn't we have another issue on this in the past? I can't recall what we decided, but it does seem useful to move some of these down to the function itself where possible.

**Comment by mathewc** [comment]
Yes this has come up many times in the past, e.g. https://github.com/Azure/azure-functions-host/issues/1054 and https://github.com/Azure/azure-functions-host/issues/5972.

**Comment by v-anvari** [comment]
Hi @zmarty , Issue 1054 is a tracking issue and the updates will be given there, can we close this issue as duplicate.
