### ISSUE TITLE
WebJobsOptionsFactory implementation ignores the "validations" parameter

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-webjobs-sdk#2522]
Because the implementation of the `WebJobsOptionsFactory` ignores the validation, it does not perform the intended validation.

#### Repro steps

```csharp
public class Startup : FunctionsStartup
{
    public Startup()
    {
        var config = new ConfigurationBuilder()
            .AddEnvironmentVariables();

        Configuration = config.Build();
    }

    public IConfiguration Configuration { get; }

    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddOptions<SampleOptions>()
               .Bind(Configuration.GetSection("Sample"))
               .ValidateDataAnnotations();
    }
}

public class SampleOptions
{
    [Required]
    public string Value { get; set; }
}
```

#### Expected behavior

I expect the validation to run.
`Sample:Value` key if the application settings are not set and `OptionsValidationException` is thrown.

#### Actual behavior

No validation is performed and the property values are not checked.

#### Known workarounds

```csharp
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        // Replace default implementation
        builder.Services.Replace(ServiceDescriptor.Transient(typeof(IOptionsFactory<>), typeof(OptionsFactory<>)));
    }
}
```

#### Related information 

https://github.com/Azure/azure-webjobs-sdk/blob/f386e54e5000ddddf255f529689ab2a9c3ee78cd/src/Microsoft.Azure.WebJobs.Host/Hosting/OptionsFormatter/WebJobsOptionsFactory.cs#L28

**Comment by fabiocav** [comment]
Assigning this to the upcoming sprint

**Comment by fabiocav** [comment]
Moving to sprint 86, but we're trying to get this into the 85 payload.

**Comment by selMicrosoft** [comment]
@fabiocav Any update on this? I was trying to validate options for azure functions v3 with no luck

**Comment by fabiocav** [comment]
@selMicrosoft  Let me follow up with @soninaren on this issue.

**Comment by fabiocav** [comment]
Assigning this to @brettsam as he was recently impacted by the issue and worked on a fix.
