### ISSUE TITLE
Not able to set AzureWebJobsDashboard and AzureWebJobsStorage from KeyVault

### ISSUE THREAD

**Issue by abhishek-msft** [Azure/azure-webjobs-sdk#2523]
#### Description
I want to set the connection string for AzureWebJobsStorage from Key Vault instead of picking from appSettings.json > connectionStrings > AzureWebJobsStorage.

I don't want to load this from Azure Cloud Configuration either.

#### Repro steps

I tried using the InMemory configuration and Environment.SetEnvironmentVariable to provide the connection strings as below:

1. InMemory configuration

 var builder = new HostBuilder()
``
 .ConfigureHostConfiguration(b =>
                {
                    b.AddInMemoryCollection(new Dictionary<string, string>
                    {
                        { "ConnectionStrings:AzureWebJobsDashboard", storageConnString},
                        { "ConnectionStrings:AzureWebJobsStorage", storageConnString},
                    });
                })
```

2. Setting Environment Variable
```
Environment.SetEnvironmentVariable("AzureWebJobsDashboard", storageConnString);
Environment.SetEnvironmentVariable("AzureWebJobsStorage", storageConnString);
```

#### Actual behavior
I get the following error if I do not add the config key "AzureWebJobsDashboard" in appSettings.json, or set it as empty/null.
`ArgumentNullException: Value cannot be null. (Parameter 'connectionString')`



Provide any related information 

* Package version
* Links to source

**Comment by mohsinonxrm** [comment]
@abmis-mi , here's how I got it to work
`
builder.ConfigureHostConfiguration(configuration =>
            {
                configuration.AddJsonFile("appsettings.json", false);
                var builtConfig = configuration.Build();

                var azureServiceTokenProvider = new AzureServiceTokenProvider();
                var keyVaultClient = new KeyVaultClient(
                    new KeyVaultClient.AuthenticationCallback(
                        azureServiceTokenProvider.KeyVaultTokenCallback));

                var kvUrl = $"https://{builtConfig.GetValue<string>("KeyVaultName")}.vault.azure.net/";

                if (!string.IsNullOrEmpty(kvUrl))
                {
                    configuration.AddAzureKeyVault(new AzureKeyVaultConfigurationOptions { Client = keyVaultClient, Vault = kvUrl });
                }
            });`

That's it!

**Comment by abhishek-msft** [comment]
Looks neat!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by v-bbalaiagar** [comment]
Hi @abmis-mi, Apologies for the delayed response. Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by abhishek-msft** [comment]
Yes,I used the solution by @mohsinonxrm above.

**Comment by v-bbalaiagar** [comment]
Hi @abmis-mi, Closing this issue, please feel free to re-open the issue for any further queries regarding this issue.
