### ISSUE TITLE
Question: is there any way to load entry function from another assembly?

### ISSUE THREAD

**Issue by ms-teli** [Azure/azure-webjobs-sdk#2524]
Please provide a succinct description of the issue.

My Function project is Project1. I want to have it loading another method with attribute "[FunctionName]" from project Project2, which doesn't work. Project1 depends on Project2.

Is that supposed to work or is there any workaround? Thank you!

**Comment by v-anvari** [comment]
Hi @ms-teli ,

Were you able to find a solution here? We can add the dependencies. But, the scenario you are asking is not clear enough. Can you tell us the error that you are facing
