### ISSUE TITLE
Support config to prevent Event Hub trigger sequence number advancement on exception

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-webjobs-sdk#2525]
If I have an Event Hub trigger and my processing fails, those events (or at least the ones in a batch that haven't been processed yet) are effectively lost. Yes, you can retry, within your invocation, however Functions are time-bound, so if you can't successfully do whatever you need to within the limit, you're screwed and the messages are lost. If your Function dies due to an unhandled exception, your messages are lost. Networking issues? Cancellation token flips? Probably lost. Manually setting the numbers back can take a significant amount of effort.

In one app we resorted to a global try-catch and upon errors (such as timeouts preventing processing of the batch) the Function tries to _send the remaining events back to the hub_ so they can be reprocessed; gross. Maybe a bad example but it illustrates the issue.

In [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reliable-event-processing) it says:
> If the function completes execution (with or without exception) the pointer advances and a checkpoint is saved to the storage account.

I must be missing something because this really seems bizarre to me. Usually there is one potential positive result and several negative results. This essentially forces all positive results and disallows errors, even though errors will always be a possibility; it ignores that. I would consider it a failure if a Function invocation threw an exception... The runtime certainly seems to. This seems like effectively at-most-once and unreliable event processing rather than the opposite. Doing it the other way, not advancing in the face of exceptions, seems more logical to me and adheres to the typical positive/negative paradigm. If someone didn't care, and wanted to advance regardless of errors, they could wrap everything in a try-catch. This way allows both scenarios whereas the current behavior actively prevents one (i.e. a negative result).

Changing the default behavior is unlikely but I think it would be useful to have a config option to change the current behavior such that it prevents advancing the pointer if the Function invocation fails (including exceptions). I'm not aware of one and don't see one mentioned in [this doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#hostjson-properties).

**Comment by v-bbalaiagar** [comment]
Hi @josh-endries, Apologies for the delayed response, checking this internally for the possibilities. We will update you with any information found.

**Comment by v-bbalaiagar** [comment]
Hi @josh-endries, Here is a[ tracking issue ](https://github.com/Azure/azure-webjobs-sdk/issues/1597)which is being addressed and worked upon on a similar scenario.

Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
