### ISSUE TITLE
Implement an api to put host in drain mode.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk#2527]
When the host is put in drain mode, It should:
- Stop watching / listening for new traffic. 
- Call cancel on the cancellation token passed as a parameter to the function invocation

The idea behind implementing this mode is that Antares would put the host in drain mode. Wait a certain amount of time for the existing / pending invocations to complete. Finally perform a scale-in operation.

Currently scale in operation happens arbitrarily causing the existing function host to lose in-flight and pending invocations.

**Comment by Kdamour** [comment]
Please do not forget to check on the prefetch messages when determining if a cancelled function has completed.  Traffic would need to be stopped to the Az Function instance and then any prefetched messages and the current processing function would need to be completed to safely reclaim the process/host.

**Comment by soninaren** [comment]
> Please do not forget to check on the prefetch messages when determining if a cancelled function has completed. Traffic would need to be stopped to the Az Function instance and then any prefetched messages and the current processing function would need to be completed to safely reclaim the process/host.

You are correct, we do check and handle prefetch messages during drain mode.

**Comment by soninaren** [comment]
Addressed in the the PR https://github.com/Azure/azure-webjobs-sdk/pull/2526

**Comment by drdamour** [comment]
fwiw seems https://github.com/Azure/azure-webjobs-sdk/issues/2795 has reversed part 2 about triggering cancellation tokens
