### ISSUE TITLE
Functions v3: Can't bind Table to type System.Linq.IQueryable

### ISSUE THREAD

**Issue by realrubberduckdev** [Azure/azure-webjobs-sdk#2529]
Hitting this issue while trying to follow [Azure Table storage bindings for Azure Functions - IQueryable](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table?tabs=csharp#iqueryable).

#### Repro steps

Provide the steps required to reproduce the problem

1. Unzip attached [FunctionApp3.zip](https://github.com/Azure/azure-webjobs-sdk/files/4853029/FunctionApp3.zip)
2. Open in Visual Studio and debug.

See binding errors:
```
[30/06/2020 15:52:37] Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'System.Linq.IQueryable`1[FunctionApp3.MyPoco]'.
[30/06/2020 15:52:37] Error indexing method 'Function1'
[30/06/2020 15:52:37] Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'System.Linq.IQueryable`1[FunctionApp3.MyPoco]'.
[30/06/2020 15:52:37] The 'Function1' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'System.Linq.IQueryable`1[FunctionApp3.MyPoco]'.
```

#### Expected behavior

I would expect it to start debugging and be able to access the table rows from the function binding.

#### Actual behavior

As described above, the debug console shows binding errors.

#### Known workarounds

I currently do not know of any. Suggestions welcome.

#### Related information 

I have seen a few [issues](https://github.com/Azure/azure-webjobs-sdk/issues?q=System.Linq.IQueryable) related to this. But they are V2 and the function project I have attached has `<AzureFunctionsVersion>v3</AzureFunctionsVersion>`. So I believe this is a new/different issue.

**Comment by Rafaelki** [comment]
I have the same problem.
I have Microsoft.Azure.WebJobs.Extensions.Storage (4.0.2) and Microsoft.NET.Sdk.Functions (3.0.9) with target framework .NET Core 3.1.
Replacing IQueryable by CloudTable I get a similar error:
 Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'

**Comment by ThejaChoudary** [comment]
@realrubberduckdev was able to repro and found no build errors.Can you please provide more related data to investigate more.

**Comment by realrubberduckdev** [comment]
@ThejaChoudary Just to confirm you followed the steps described and didn't see the binding errors in the console when you started debugging?

Please let me know and I'll try again.

**Comment by Rafaelki** [comment]
@ThejaChoudary I didn't have any build errors either. The error is in the console when you started debugging:

![image](https://user-images.githubusercontent.com/24438807/90009047-43907580-dc95-11ea-9793-1cd82d7f23ef.png)

**Comment by ThejaChoudary** [comment]
@realrubberduckdev was saying that I was able to repro and getting the errors in console but the build was successfull.

**Comment by realrubberduckdev** [comment]
@ThejaChoudary then what more related data is needed for investigating? Sorry I misunderstood your comment earlier.

**Comment by ThejaChoudary** [comment]
@pragnagopa Can you please look into this as I am able to repro it locally .Thank You !

**Comment by pragnagopa** [comment]
@realrubberduckdev  - Thank you for reporting the issue. This is same as https://github.com/Azure/azure-webjobs-sdk/issues/1566 - binding `IQueryable` is only supported in the Functions V1.

Opened:  https://github.com/MicrosoftDocs/azure-docs/issues/60812 to track documentation update.

**Comment by Rafaelki** [comment]
So if IQueryable is not supported, what are we supposed to use? I tried replacing IQueryable with CloudTable and I got a similar, as I posted previously (https://github.com/Azure/azure-webjobs-sdk/issues/2529#issuecomment-671592965) and you can see in this screenshot:

![image](https://user-images.githubusercontent.com/24438807/90164260-17591f80-dd8f-11ea-9eba-5cbdfc9b4d19.png)
