### ISSUE TITLE
Graceful Shutting down of Multi instance continuous running webjob during Auto Scale-in 

### ISSUE THREAD

**Issue by kannannet** [Azure/azure-webjobs-sdk#2530]
When a multi instance continuous running webjob  reduces the number of instance because of Auto Scale-in that instance should  use to the shutdown file to gracefully close rather than termination of that instance

#### Expected behavior

Should use shutdown file and gracefully shutdown the instance during Auto scale-in 

#### Actual behavior

Instance gets terminated which leads to loss of data.

**Comment by v-bbalaiagar** [comment]
Hi @kannannet, Apologies for the delayed response, Were you able to find a solution here. Let us know if you are still facing this issue.
