### ISSUE TITLE
Why this version limit System.IdentityModel.Tokens.Jwt (>= 5.4.0 && < 6.0.0)

### ISSUE THREAD

**Issue by mliesmons** [Azure/azure-webjobs-sdk#2532]
Not making our lives easier doing this, we currently are at 6.7.1

**Comment by mliesmons** [comment]
Not making our lives easier doing this, we currently are at 6.7.1

**Comment by v-anvari** [comment]
Hi @mliesmons , Could you please elaborate the ask? The version is currently at [6.8.0](https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/)
