### ISSUE TITLE
Inability to index a function should cause ARM template deployment to fail

### ISSUE THREAD

**Issue by lostmsu** [Azure/azure-webjobs-sdk#2542]
When I deploy an ARM template, I'd like to know, that some of my Azure Functions have not been recognized.

#### Repro steps

1. Create a function with two triggers

2. Deploy it using an ARM template + MSDeploy resource

#### Expected behavior

Deploy should fail mentioning inability to index the function.

#### Actual behavior

Deploy succeeds, and there's little indication of anything going wrong whatsoever. I was only able to figure out why the function is not triggered after seeing `FunctionIndexingException` in ApplicationInsights (which, strictly speaking, should not even be necessary).

#### Known workarounds

Unknown

**Comment by v-anvari** [comment]
Hi @lostmsu , Apologies for the delayed response. Are you still facing this issue?

Can you provide us the complete error and the code that is busted by adding breaking points in your code.
