### ISSUE TITLE
Using System.Text.Json with Azure Functions

### ISSUE THREAD

**Issue by andres-j** [Azure/azure-webjobs-sdk#2545]
While attempting to use [System.Text.Json](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) in our functions app we have run into an issue where the returned IMvcCoreBuilder's _AddJsonOptions_ function expects an _MvcJsonOptions_ object. The _MvcJsonOptions_ object contains only _SerializerSettings_, which accepts only Newtonsoft-specific types for converters and options:

![image](https://user-images.githubusercontent.com/17058214/89321807-61d0f280-d651-11ea-9153-441c02fd641a.png)

This in turn prevents us from using System.Text.Json or applying json options/converters that use System.Text.Json. 

#### Expected behavior

An options object that implements _AddJsonOptions_  and accepts json converters that use System.Text.Json

#### Actual behavior

_AddJsonOptions_ accepts an MvcJsonOptions object which implements only newtonsoft derived json options

**Comment by andres-j** [comment]
We have identified a possible fix by including 

```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

in our project file. Our only concern is whether adding this dependency directly might interfere with WebJobs specific dependencies designed to work with Azure Functions?

**Comment by andres-j** [comment]
Unfortunately this is not a viable solution - while it allows the project to compile this does not actually configure what is used to serialize a response. The application continues to serialize following the separate (and unconfigurable) webjobs framework configuration

**Comment by hansmbakker** [comment]
This is related to https://github.com/Azure/azure-functions-host/issues/5469.

**Comment by v-anvari** [comment]
Hi @andres-j , We hope your issue is resolved by taking reference from "[Azure/azure-functions-host#5469](https://github.com/Azure/azure-functions-host/issues/5469)". We are closing this issue, since this is related to #5469. Please feel free to reopen this issue, in case of any further concerns.
