### ISSUE TITLE
Add ability to turn on SQL query logging for Azure Functions

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-webjobs-sdk#2548]
Before 28 july 2020 we were able to see the sql queries in appinsight dependencies logs, but now we are only seeing server names and no sql queries are logged from azure functions consumption plan.  We have other code in aks cluster and sql queries are logged for calls done for app hosted in aks.

#### Expected behavior

Sql queries not logged in appinsight for azure function consumption plan.

#### Actual behavior

Sql queries should be logged in appinsight for azure function consumption plan.

#### Known workarounds
i tried this link but it didnt help
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1425
Also adding reference to this dll brings aspnetcore things in azurefuctions project and is not making sense 

#### Related information 

Provide any related information 

* Package version
* Links to source
![image](https://user-images.githubusercontent.com/10679463/90161806-4b195280-dd59-11ea-918f-94a59a9f42da.png)

**Comment by krishnasingh1818** [comment]
in appinsight under command section we are just seeing server name instead of full sql query that is execute. please advise.
![image](https://user-images.githubusercontent.com/10679463/90161962-8b78d080-dd59-11ea-8860-c00d01b560b5.png)

**Comment by ThejaChoudary** [comment]
@krishnasingh1818 it would be great if you share a simple repro ,we will investigate further.

**Comment by pragnagopa** [comment]
More details: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1425


@brettsam  - Do you have any more details on this? Do we have to update SDK to expose an option to enable SQL query logging?

**Comment by brettsam** [comment]
We need to expose a new setting that we flow through to the App Insights SDK -- `EnableSqlCommandTextInstrumentation`. Will assign this to next sprint.

**Comment by piotrzbyszynski** [comment]
@brettsam I have SQL command text instrumentation (in Azure Function Startup.cs) disabled like so:

```
builder.Services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((m, o) =>
            {
                m.EnableSqlCommandTextInstrumentation = configuration.GetValue<bool>("SqlQueryLoggingIsEnabled");
            });
```

Now, not only SQL command text is not logged, but SQL dependency is not logged at all. I would expect that dependency is still logged, bu only SQL query text is disabled. If I turn `EnableSqlCommandTextInstrumentation` on, both dependency and sql query text is logged

Here are dependencies I am using:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.15.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
  </ItemGroup>
```

Any thoughts would be appreciated

**Comment by krishnasingh1818** [comment]
i added below code in my function startup but still its not showing sql command text. it is showing dependency in appinsight but command text is only show sql servername instead of full command text.
 
builder.Services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((m, o) =>
            {
                m.EnableSqlCommandTextInstrumentation = true;
            });

![image](https://user-images.githubusercontent.com/10679463/97041838-bfc8f400-1535-11eb-995d-d41561798b60.png)

**Comment by brettsam** [comment]
@krishnasingh1818 -- doing that won't work in Functions. PR #2608 will fix this by exposing these settings in host.json.

**Comment by krishnasingh1818** [comment]
Microsoft.Azure.WebJobs 3.0.24 seems has fix for this issue but I don't see it available on nuget.org . within how many days should I expect it to be available on nuget.org so that I can upgrade my version. pls advise.

thanks.
krishna

**Comment by piotrzbyszynski** [comment]
@brettsam Not sure how to use this fix, so I have few questions:

1. Should we use it via `host.json` like so (I do not see this setting documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsights)? 
```
    "applicationInsights": {
      "enableDependencyTracking": true,
      "dependencyTrackingOptions": {
        "enableSqlCommandTextInstrumentation": true
      }
    }
```

2. Is there ability to set `enableSqlCommandTextInstrumentation` in code?
3. Do we need to explicitly include `Microsoft.Azure.WebJobs` and `Microsoft.Azure.WebJobs.Logging.ApplicationInsights` nugets in function project
4. Even though I have dependency tracking enabled I can not see any SQL dependencies logged (with or without SQL command text included)

Any help would be highly appreciated

**Comment by cmanoliu** [comment]
@soninaren @brettsam 
Hello, 

Can anyone please respond to @pzbyszynski ?
I have the same problem and wasting a lot of time trying to workaround this issue. Existing documentation does not help. 
An answer would be very helpfull. Thank you.

Regards,

Catalin

**Comment by piotrzbyszynski** [comment]
@cmanoliu Please have a look here: https://github.com/Azure/Azure-Functions/issues/1613#issuecomment-802899247

The workaround for this issue is downgrading EF & AI libraries
