### ISSUE TITLE
Functions v3: Can't bind Table to type Microsoft.WindowsAzure.Storage.Table.CloudTable

### ISSUE THREAD

**Issue by Rafaelki** [Azure/azure-webjobs-sdk#2549]
I am following the steps described here https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table?tabs=csharp#cloudtable to use CloudTable in a V3 Function.

I have Microsoft.Azure.WebJobs.Extensions.Storage (4.0.2) and Microsoft.NET.Sdk.Functions (3.0.9) with target framework .NET Core 3.1.

The solution compiles but when I debug in Visual Studio I get this error:
`The 'Function1' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Extensions.Storage: Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.`

![image](https://user-images.githubusercontent.com/24438807/90164260-17591f80-dd8f-11ea-9eba-5cbdfc9b4d19.png)

_Originally posted by @Rafaelki in https://github.com/Azure/azure-webjobs-sdk/issues/2529#issuecomment-673594890_

**Comment by brettsam** [comment]
When we moved the Storage extension to 4.0, it updated to the latest Storage SDK -- which changed namespaces on us. 

Change the `using Microsoft.WindowsAzure.Storage.Table;` statement to `using Microsoft.Azure.Cosmos.Table;` and it should get you working.

**Comment by Rafaelki** [comment]
Thanks @brettsam 
I can confirm that the errors in the debug console are gone.
(I would have prefered that you give me the time to reproduce the fix BEFORE closing the issue)

**Comment by KonKri** [comment]
This issue was gone for me when Microsoft.Azure.WebJobs.Extensions.Storage and Microsoft.NET.Sdk.Functions were both in the 3.0.11 version.
