### ISSUE TITLE
Question: is there a way to remove "prop__" prefix from custom dimensions?

### ISSUE THREAD

**Issue by hiraldesai** [Azure/azure-webjobs-sdk#2559]
I would like to know if I use logger.BeginScope() with a state dictionary, is there a way for me to tell the SDK not to prefix the property with "prop__"?

**Comment by v-anvari** [comment]
Hi @hiraldesai , Apologies for the delayed response. Could you please elaborate the scenario, for us to understand the issue better. Can you give us an example of the usage

**Comment by v-anvari** [comment]
This is not possible by-design, we still require to look into the usage to find a work around. Closing this issue, please feel free to re-open the issue in case you want us to look into it further
