### ISSUE TITLE
Azure Functions Blob storage trigger not firing for deleted blobs from container

### ISSUE THREAD

**Issue by sanjaykulkarni04** [Azure/azure-webjobs-sdk#2566]
Please provide a succinct description of the issue.

Hi Team,

Azure Function is not being called for deleted blobs. I am referring sample code - https://docs.microsoft.com/bs-latn-ba/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp

**Below is the sample code** - 
`[FunctionName("BlobTriggerCSharp")]        
public static void Run([BlobTrigger("samples-workitems/{name}")] Stream myBlob, string name, ILogger log)
{
    log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
}`

**Expected behavior**

Azure Functions Blob storage trigger (azure function) should be fired (called) when the blob is deleted from the container

**Actual behavior**

Azure Functions Blob storage trigger (azure function) is not being fired (called) when the blob is deleted from the container

I am using the latest **Package** - **Microsoft.Azure.WebJobs.Extensions.Storage (version - 4.0.2)**

Can someone please help me?

Thanks,
Sanjay

**Comment by ThejaChoudary** [comment]
@sanjaykulkarni04 Could you please make sure that blob storage logs is enabled, because this service would scan through the logs and try to identify blobs that have been deleted, modified in addition to the usual blob strategy that it uses. So it is important to have logging enabled otherwise we wont be able to detect where blobs were deleted. 
Also it may take a few minutes to delete and not a immediate action. 
Please feel free to get back to us if you still face the issue.

**Comment by sanjaykulkarni04** [comment]
@ThejaChoudary Thank you so much for the quick response. Can you please share with me the documentation link?

Actually, my requirement is, whenever the user is uploading new/modifying/deleting files/blobs thru REST API calls (react client), I want to store the entire custom audit trail chain on each file (e.g. user name - person, blob creation time, last modified time, etc.). I am using Blob metadata to do that. But it only saves the current state of the object/blob, not the entire history of the user when he is doing multiple actions on the same file. And also you confirmed that, while deleting is not possible.

Is there any alternate way to accomplish this requirement?

Thanks,
Sanjay

**Comment by ThejaChoudary** [comment]
@sanjaykulkarni04 Please refer the [link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#polling) and also can you please confirm if deleted blobs were detected after enabling the logs.
And also for above question can you please elaborate the issue like what is your exact requirement?

**Comment by sanjaykulkarni04** [comment]
@ThejaChoudary I am using Event Grid now. I wanted to implement custom audit trail info of each uploaded/overwrite/deleted blob/file as I mentioned in my last comments. Is there any way?

**Comment by ThejaChoudary** [comment]
@sanjaykulkarni04 Yes it is possible ,it is something you can do now that you are notofied of every action and every activity against the blob storage. Event create is going to call the function anytime there is an update modification,like anytime a blob is deleted or blob is created ,which gives a notification and the information is logged about the blob.

**Comment by sujjitt** [comment]
This issue is still relevant. I have logs turned on

**Comment by goutamsamal** [comment]
> @sanjaykulkarni04 Please refer the [link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#polling) and also can you please confirm if deleted blobs were detected after enabling the logs. And also for above question can you please elaborate the issue like what is your exact requirement?

For myself, it is not working after enabling the log.
![image](https://user-images.githubusercontent.com/109196721/189095935-9c7aa466-97a5-4f97-914a-c3a6655c95b3.png)
