### ISSUE TITLE
Event Grid Trigger Azure Function: How to access metadata(user defined key, value pair) of deleted blobs?

### ISSUE THREAD

**Issue by sanjaykulkarni04** [Azure/azure-webjobs-sdk#2567]
How to get metadata of deleted blob in Event Grid Trigger Azure Function? Below is a sample C# code -

[FunctionName("EventGridTriggerFunction")] 
public static void Run([EventGridTrigger]EventGridEvent eventGridEvent, ILogger log) 
{ log.LogInformation(eventGridEvent.Data.ToString());
}

Can I get from EventGridEvent --> data object property? Is there any way to set custom event schema with blob's metadata?

Referring link - https://docs.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage

`[{
  "topic": "/subscriptions/{subscription-id}/resourceGroups/Storage/providers/Microsoft.Storage/storageAccounts/my-storage-account",
  "subject": "/blobServices/default/containers/test-container/blobs/new-file.txt",
  "eventType": "Microsoft.Storage.BlobCreated",
  "eventTime": "2017-06-26T18:41:00.9584103Z",
  "id": "831e1650-001e-001b-66ab-eeb76e069631",
  "data": {
    "api": "PutBlockList",
    "clientRequestId": "6d79dbfb-0e37-4fc4-981f-442c9ca65760",
    "requestId": "831e1650-001e-001b-66ab-eeb76e000000",
    "eTag": "\"0x8D4BCC2E4835CD0\"",
    "contentType": "text/plain",
    "contentLength": 524288,
    "blobType": "BlockBlob",
    "url": "https://my-storage-account.blob.core.windows.net/testcontainer/new-file.txt",
    "sequencer": "00000000000004420000000000028963",
    "storageDiagnostics": {
      "batchId": "b68529f3-68cd-4744-baa4-3c0498ec19f0"
    }
  },
  "dataVersion": "",
  "metadataVersion": "1"
}]`

**Comment by sanjaykulkarni04** [comment]
@brettsam can you please help me?

**Comment by sanjaykulkarni04** [comment]
@brettsam just reminding you.. also please let me know how to set meta data while deleting blob using Rest api call?

**Comment by v-anvari** [comment]
Hi @sanjaykulkarni04, This feature is not controlled by functions, this is controlled by storage. Were not aware of a mechanism to customize the event schema from storage, but once you have notification and once event is identified, you will have the ability to communicate with storage and retrieve any additional information you need. Yeah, but functions don't have the control of everything that comes to it from the event. 

We believe that the workaround here could be that you can enable few additional properties associated with the BLOB, you can enable soft deletes and you would have access to the blob and you can access the metadata for that blob programmatically. So, when you get the events you will have a reference to the BLOB that was deleted. 

But, the storage team can help you with a better approach. Feel free to re-open this issue in case of any concerns.
