### ISSUE TITLE
Update build to use .net 3.1

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-webjobs-sdk#2571]
Opened PR here: https://github.com/Azure/azure-webjobs-sdk/pull/2569

But there was an error: 
```
105dotnet.exe : Testhost process exited with error: It was not possible to find any compatible framework version
106At C:\projects\azure-webjobs-sdk-rqm4t\runtests.ps1:15 char:3
107+ & dotnet $cmd
108+ ~~~~~~~~~~~~~
109 + CategoryInfo : NotSpecified: (Testhost proces...amework version:String) [], RemoteException
110 + FullyQualifiedErrorId : NativeCommandError
111 
112The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
113 - The following frameworks were found:
114 2.0.0 at [C:\Program Files (x86)\dotnet
115\shared\Microsoft.NETCore.App]
116 3.1.8 at [C:\Users\appveyor\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
117You can resolve the problem by installing the specified framework and/or SDK.
118The specified framework can be found at:
119 - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x86&rid=win10-x86
120. Please check the diagnostic logs for more information.
121
122
123Test Run Aborted.
124
```

**Comment by fabiocav** [comment]
What is driving this change/requirement?

**Comment by fabiocav** [comment]
Moving to sprint 86 for discussion.

**Comment by Scooletz** [comment]
Hey @fabiocav . Is it possible to see the plans for this kind of issues? You mention `sprint 86`. Using `Projects` on GitHub would allow external contributors to plan their work in a wiser way. For instance, recently I issued a few performance related PRs and I don't know what are the plans for the components I changed. Are there any plans for this?

**Comment by pragnagopa** [comment]
Moving to Sprint 87 to figure out if this change is needed or not.

**Comment by fabiocav** [comment]
Closing this issue as this is not something will be doing now.

@Scooletz will provide some information using the other issue we have open to track some enhancements. Would love to get more feedback once those changes are done.
