### ISSUE TITLE
Update storage SDK to 12.x

### ISSUE THREAD

**Issue by mauve** [Azure/azure-webjobs-sdk#2575]
For example I really would like to migrate to `Azure.Storage.Blobs` (i.e. the v12 SDK) so that I can start using `Azure.Identity` for authentication instead of these annoying connection strings.

What is the timeline for migration? Is there some preview packages I can use? I am a new user so I do not care about backwards compatibility even though I understand that is important for GA.

**Comment by pragnagopa** [comment]
@brettsam - Do we have any planned workitems to update storage SDK to v12?

cc @soninaren for bundles udpates.

**Comment by mauve** [comment]
I am aware that this is a breaking change, but it would be nice if there were a timeline or a way to opt in to early.

**Comment by pragnagopa** [comment]
To consume any major version updates in the dependency packages - major version updates will be released for extension packages and bundles. 

Updated the title for the issue and triaged. We will update this issue when we have a timeline or a plan

**Comment by mauve** [comment]
Do you know when you might have a plan? How long should I be holding my breath for?

**Comment by paulbatum** [comment]
Hi folks, we have some work in progress on this, for example see [here](https://github.com/Azure/azure-sdk-for-net/pull/15139). There is still significant work remaining, so we're not sure of when we might have a preview ready yet. But you should at least hear from us again later this calendar year on how the work is progressing.

**Comment by mauve** [comment]
@paulbatum thanks for the followup, do you also know the status of ServiceBus (as the latest SDK there also supports Azure.Identity)?

**Comment by paulbatum** [comment]
Hi folks, good news - the first 5.0 preview release of the storage extension is now available:
https://github.com/Azure/azure-sdk-for-net/releases/tag/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs_5.0.0-beta.1
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/5.0.0-beta.1

Also please be aware that the new extension lives here:
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage

So if you want to file a issue regarding the new extension, do so here:
https://github.com/Azure/azure-sdk-for-net/issues/new/choose

@mauve We have work planned for the service bus extension but it has not started yet. Expect to hear more on this early 2021.

**Comment by mauve** [comment]
That is amazing, can't wait to try it out on Monday!

This means I can omit the key from the AzureWebJobsStorage setting even when deploying?

**Comment by paulbatum** [comment]
@mauve Not yet. AzureWebJobsStorage is used by the functions host and we have not updated it to the v12 SDK yet. Similarly, our scale infrastructure uses your connection strings to monitor event sources and that has not been updated either. We are beginning design and planning for this work now. You should treat this preview release as an opportunity to see how much of your code you are going to need to change (because the v12 storage SDK made quite a few API changes), test locally and report bugs, etc. 

My best guess for when the MSI scenario will be working fully end-to-end with all the necessary platform support is around March 2021 (and to reiterate this is just a guess).

**Comment by mauve** [comment]
Hi @paulbatum do you have a new estimate?

**Comment by paulbatum** [comment]
You can track most of the remaining work by keeping an eye on these two PRs:
https://github.com/Azure/azure-webjobs-sdk/pull/2680
https://github.com/Azure/azure-functions-host/pull/7198

So allowing a week or so of reviews and changes, then allowing for a few weeks of deployment related activities, I think end of May seems likely.

**Comment by mauve** [comment]
Thanks @paulbatum do you know if there is work in progress for moving the ServiceBus binding to track2 as well?

Actually seems to already be supported: https://github.com/Azure/azure-functions-servicebus-extension/issues/128#issuecomment-761213261

**Comment by paulbatum** [comment]
Yes, support is in this preview release:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.0.0-beta.2

**Comment by mauve** [comment]
Oh cool it looks like both PRs (#2680 and Azure/azure-functions-host#7198) have been merged. 🥳🥳🥳

**Comment by jmelkins** [comment]
I looked at the  5.0 preview release of the storage extension that targets Azure Storage SDK v12 but there is only support for blobs and queues, not tables which is what I was hoping for. Are there any plans to integrate support for Azure Storage Tables, perhaps using the new Azure.Data.Tables package assuming that package is going to be the recommended package for Azure Storage Tables going forward?

**Comment by cristicazan** [comment]
Hello,

Before updating to the 5.0 version and trying to use managed identity for the blob trigger, we were loading the azure connection string from another file than the local settings one, as we are using that file for other projects besides the function one. In that way, we received a warning but the solution worked.
![image](https://user-images.githubusercontent.com/22996385/133264561-d864f1a0-a7c4-4be1-89b8-531490bf700b.png)

Now, with managed identity I configured the "MyConnection__acountName" in the local.settings.json as described [in the beta article](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-function-extension-libraries-beta/). Everything worked just fine. However, when I tried to move it from local.settings.json to the file that we used for loading the settings I receive these errors:
![image](https://user-images.githubusercontent.com/22996385/133268085-d953b245-9327-4e13-a553-7e98a88defbe.png)

Do you have any idea that this kind of setup ( with accountName or serviceUri ) will be available when loading the connection for other files than local.settings.json?

**Comment by camerondm9** [comment]
I'm also interested in support for the new Azure.Data.Tables package.

**Comment by v-anvari** [comment]
Closing the initial issue as it is resolved. @camerondm9 / @cristicazan Please open a new issue with all the required details as it requires investigation with respect to the scenario
