### ISSUE TITLE
 Disable attribute doesn't seem to work for "NoAutomaticTrigger"

### ISSUE THREAD

**Issue by v-anvari** [Azure/azure-webjobs-sdk#2583]
Please provide a succinct description of the issue.

Disabling continuous web jobs for "NoAutomaticTrigger" that are invoked explicitly.  "Disable" attribute doesn't seem to work for "NoAutomaticTrigger".

**Repro steps**:

Deploy a .NET project (with webjobs) using the WEBSITE_RUN_FROM_PACKAGE app setting.

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Disable" attribute doesn't seem to work for "NoAutomaticTrigger".

#### Known workarounds

NA

#### Related information 

[#2389](https://github.com/Azure/azure-webjobs-sdk/issues/2389) - To disable webjobs which is deployed using "WEBSITE_RUN_FROM_PACKAGE"

[#12462](https://github.com/Azure/azure-cli/issues/12462) -  cannot stop or disable webjobs when using the WEBSITE_RUN_FROM_PACAKGE app setting enabled

**Comment by brettsam** [comment]
I believe that Disabled functions are still invokable directly, we just didn't start their listeners, but @mathewc can help confirm for us. If that's the case, then there's no real way to make a `NoAutomaticTrigger` function completely disabled.

**Comment by mathewc** [comment]
Correct - DisableAttribute only affects triggered functions (we don't start their listeners). They're still directly invokable via code however (JobHost.Call). See https://github.com/Azure/azure-webjobs-sdk/blob/b798412ad74ba97cf2d85487ae8479f277bdd85c/src/Microsoft.Azure.WebJobs/DisableAttribute.cs#L17.
