### ISSUE TITLE
Event and setting repos

### ISSUE THREAD

**Issue by samuel-velazquez** [Azure/azure-webjobs-sdk#2587]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by samuel-velazquez** [comment]
Here from this class import and get url if go null.

**Comment by samuel-velazquez** [comment]
Array compose time: and reset so call back im process tasks hidden or blind if regular expression and if test and element above

**Comment by ThejaChoudary** [comment]
@samuel-velazquez Can you please explain us what was the exact issue you are facing?

**Comment by samuel-velazquez** [comment]
only disponice town nice two me with

**Comment by samuel-velazquez** [comment]
us run this shape in bool is skeleton if func dynamic or them is declarate main soget inst feature cell (markdown) as frameworks

**Comment by ThejaChoudary** [comment]
@samuel-velazquez Can you elaborate the issue and also provide us the repro steps of the issue your facing as we are unable to understand the issue by the above given information.

**Comment by samuel-velazquez** [comment]
andwer list statement only them so char in platform include top if getso and hidden information class single do call like string validation

**Comment by ThejaChoudary** [comment]
@samuel-velazquez The information provided here is not sufficient to work on the issue, hence proceeding to close the issue. Please free to open a new issue with required details .Thank You!
