### ISSUE TITLE
Microsoft.Azure.WebJobs.Logging.ApplicationInsights NuGet package has dependency with known security vulnerabilities

### ISSUE THREAD

**Issue by ghost** [Azure/azure-webjobs-sdk#2588]
#### Description

Microsoft.Azure.WebJobs.Logging.ApplicationInsights references Microsoft.ApplicationInsights.AspNetCore as dependent package.
Microsoft.ApplicationInsights.AspNetCore had a security vulnerability issue in 2.14.0 (with Microsoft.AspNetCore.Hosting). 
This has been fixed in 2.15.0.
The package Microsoft.Azure.WebJobs.Logging.ApplicationInsights references is >=2.14.0. 
Please upgrade to >=2.15.0 to fix the vulnerability in the dependent package.

I understand that this is probably can be fixed by using latest version of runtime in hosting, but this gets reported by security scanners as vulnerability in the project, so it is still good idea to use references on libraries without known security vulnerabilities.

#### Repro steps

Provide the steps required to reproduce the problem

1. Use nuget package Microsoft.Azure.WebJobs.Logging.ApplicationInsights version v3.0.18

2. See that required version of dependent package Microsoft.ApplicationInsights.AspNetCore is of >=2.14.0 instead of >=2.15.0

#### Expected behavior

Required version of dependent package Microsoft.ApplicationInsights.AspNetCore is >=2.15.0

#### Actual behavior

Required version of dependent package Microsoft.ApplicationInsights.AspNetCore is >=2.14.0

#### Known workarounds

None known

#### Related information 

See original fixed issue in Microsoft.ApplicationInsights.AspNetCore 2.15.0 here:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1902

* Package version
v3.0.18
* Links to source

**Comment by ThejaChoudary** [comment]
Able to repro the issue.
![image](https://user-images.githubusercontent.com/57453616/96500059-e9e79100-126b-11eb-91bc-d8fb912c6155.png)
![image](https://user-images.githubusercontent.com/57453616/96500199-1f8c7a00-126c-11eb-9cc0-6c34974e3a55.png)
Even though the  Microsoft.ApplicationInsights.AspNetCore is >=2.15.0 , the Required version of dependent package Microsoft.ApplicationInsights.AspNetCore is  >=2.14.0 instead of >=2.15.0

**Comment by ghost** [comment]
This is automatically fixed by upgrading to version 3.0.27 (dependency is updated to >= 2.16.0) (released on 23 march 2021)! 
Closing this issue now
