### ISSUE TITLE
Microsoft.Azure.Webjobs.Logging.ApplicationInsights 3.0.23 Dependencies - Microsoft.Azure.Webjobs 3.0.23 Does Not Exist

### ISSUE THREAD

**Issue by velocicoder-1** [Azure/azure-webjobs-sdk#2600]
I tried installing the latest Microsoft.Azure.Webjobs.Logging.ApplicationInsights Nuget Package and it has Microsoft.Azure.Webjobs v3.0.23 as a dependency, which does not exist.

**Comment by robertmclaws** [comment]
You folks need to either increpemtn Microsoft.Azure.WebJobs to version 3.0.23, or issue a new ApplicationInsights package that has the right dependency.

**Comment by brettsam** [comment]
We're trying to get ApplicationInsights 3.0.23 hidden -- it was inadvertently released early. @fabiocav as FYI

**Comment by ThejaChoudary** [comment]
@velocicoder-1 as **Microsoft.Azure.Webjobs.Logging.ApplicationInsights 3.0.23** is released accidentally and we are trying to get it hidden ,Please use the existing nuget package i.e **Microsoft.Azure.Webjobs.Logging.ApplicationInsights 3.0.18**.Hence proceeding to close the issue.Please free to reach out to us if you have any further queries.
