### ISSUE TITLE
Clarify when and how external PRs are reviewed

### ISSUE THREAD

**Issue by Scooletz** [Azure/azure-webjobs-sdk#2601]
This is a question related to a the process of accepting Pull Requests that is described in [Contributing.md](https://github.com/Azure/azure-webjobs-sdk/blob/dev/CONTRIBUTING.md#submitting-pull-requests). Recently I opened a few PRs. They are not bug fixes. They're mostly focused on performance aspects of Azure Storage Queues, just to list a few:

- https://github.com/Azure/azure-webjobs-sdk/pull/2599
- https://github.com/Azure/azure-webjobs-sdk/pull/2593
- https://github.com/Azure/azure-webjobs-sdk/pull/2510 (MERGED)

Would it possible to clarify expectations that an external contributor (like me) can have in terms of when and how external PRs are reviewed? Whether it's a week or a month? Having PRs open is ok. At the same time, having them open a bit too long makes it possible that they are no longer valid or that they require loading the context again. 

So far my usual workflow was to ping @brettsam (probably too frequently), ask for `full-ci` (which is a separate thing) and then after some time have a conversation about the content.

I think that for all the external contributors it'd be easier if they knew what and when to expect. Whether their PR will be reviewed in a week, a month or (I hope not) not reviewed at all.

I was trying to do my best to flush out the doubts. If you find any part of the issue weird, please assume good will.

**Comment by brettsam** [comment]
@Scooletz -- good question. Right now a lot of these are coming to me and it's getting backlogged a bit. We currently have a bot that assigns issues to people on the team immediately (round-robin style), so that we can have some accountability for responses. The same thing isn't happening for community PRs, though. 

@fabiocav -- Is that something that we can adjust the bot to also do? Also it looks like maybe it's not auto-assigning anyone to issues in this repo? I see this one is unassigned (but I just grabbed it).

**Comment by Scooletz** [comment]
Thank you for your input @brettsam 🙇 Looking forward to hearing more about the process or its amendments.

**Comment by mathewc** [comment]
Thanks for all your work @Scooletz, much appreciated. All the PRs referenced by this issue are now merged. We're focusing heavily on performance right now, so your changes are timely. I've been applying the "performance" tag to all performance related work.

**Comment by brettsam** [comment]
Going to assign this to @fabiocav to take care of some bot improvements next sprint.

**Comment by Scooletz** [comment]
Thank you for this positive feedback @mathewc I noticed the label and it looks awesome 😄 

Just to clarify, I put the PRs as an example not as a leverage point or some kind of pressure. Being passive aggressive is not my cup of tea.
