### ISSUE TITLE
Namespace clash on ConsistencyLevel with CosmosDB v3 SDK

### ISSUE THREAD

**Issue by TimPosey2** [Azure/azure-webjobs-sdk#2616]
Latest version of `Microsoft.Azure.WebJobs.Extensions.Storage` references `Microsoft.Azure.Cosmos.Table`, which has a namespace collision on `ConsistencyLevel` with `Microsoft.Azure.Cosmos`. 

#### Repro steps

1. Upgrade (or create new) project to `Microsoft.Azure.WebJobs.Extensions.Storage` 4.0.3

2. Include `Microsoft.Azure.Cosmos` to use the latest v3 SDK for CosmosDB (v3.14.0)

3. Reference `ConsistencyLevel` anywhere in the code to get the build error

Bonus: `Microsoft.Azure.Cosmos.Table` v2.0.0-preview has the naming issues fixed. However when trying to reference that directly in the project, it will compile, but the Functions runtime will report an error: ` Microsoft.Azure.WebJobs.Extensions.Storage: Could not load type 'Microsoft.Azure.Cosmos.Table.CloudTable' from assembly 'Microsoft.Azure.Cosmos.Table, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

#### Expected behavior

Namespaces shouldn't clash between the two. Perhaps related to https://github.com/Azure/azure-cosmos-dotnet-v3/issues/247. Would be nice to be able to at least self-reference `Microsoft.Azure.Cosmos.Table` v2.0.0-preview to be able to use the latest version of `Microsoft.Azure.WebJobs.Extensions.Storage`

#### Actual behavior

Build error: `The type 'ConsistencyLevel' exists in both 'Microsoft.Azure.Cosmos.Client, Version=3.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Azure.Cosmos.Table, Version=1.0.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

#### Known workarounds

Downgrade to `Microsoft.Azure.WebJobs.Extensions.Storage` v3.0.7

#### Related information 

Provide any related information 

* Microsoft.NET.Sdk.Functions v3.0.9
* Microsoft.Azure.CosmosDB v3.14.0
* Microsoft.Azure.WebJobs.Extensions.Storage v4.0.3

**Comment by v-anvari** [comment]
@TimPosey2 , I tried to repro it by using "consistency level" in my code, but didn't get any build error. Can you kindly give us your piece of code or the solution in a zip file that's busted so that I can clone it. 

If its a clone of [#247](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/247), then it's a known bug and team is still working on it.

**Comment by TimPosey2** [comment]
In your Function1.cs:

````
using System;
using System.IO;
using Microsoft.Azure.Cosmos;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([BlobTrigger("samples-workitems/{name}", Connection = "tbd")]Stream myBlob, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");

            Microsoft.Azure.Cosmos.ConsistencyLevel level = ConsistencyLevel.Eventual;
        }
    }
}
````

And the .csproj looks like:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.14.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

**Comment by v-anvari** [comment]
Thankyou for providing the code @TimPosey2 , I am able to repro the issue 

If you are willing to work with the latest Microsoft.Azure.WebJobs.Extensions.Storage 4.0.3 version, then its ideal to uninstall Microsoft.Azure.Cosmos. Since, Microsoft.Azure.Cosmos.Table is included in the latest storage package. 

Feel free to open the issue in case of any queries related to this issue

**Comment by TimPosey2** [comment]
Using `Microsoft.Azure.Cosmos` is the ONLY way to utilize CosmosDB v3. Even if you're only using the SQL API (and *NOT* the Tables API) this issue prevents you from utilizing CosmosDB v3 within Azure Functions and changing the `ConsistencyLevel`. Again, I'm not using `Microsoft.Azure.Cosmos.Table`, but because it is now included in v4.0.3 of `Microsoft.Azure.WebJobs.Extensions.Storage` then it breaks any app that wants to utilize CosmosDB v3 SDK and change `ConsistencyLevel`.

**Comment by pragnagopa** [comment]
cc @brettsam 
Thanks for reporting the issue. Moving it next sprint to discuss options we have to address this issue.

**Comment by fabiocav** [comment]
This is a compatibility issue. Currently, the version of the extension you're using does not support the version of the Cosmos DB SDK you're referencing. This is currently in progress.

If you need to use the latest SDK version, you can use that standalone, without the extension functionality.
