### ISSUE TITLE
TimerTrigger stopped working for the service 

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-webjobs-sdk#2622]
Timer trigger on the webjob stopped working with no errors.

We recently upgraded the web job package versions and deployed the service and the timer trigger ran for the first pulse and then never recovered. Looking at the service logs we saw the web job thread trying to acquire the lock and was stuck on it.
Redeployment of the service fixed it. We have not seen this issue again however would like to know if it is a known issue with existing code patterns\ package version etc. Would also like to RCA the issue.

#### Repro steps
1. Packages we recently upgraded to are
Microsoft.Azure.WebJobs - version 3.0.18
Microsoft.Azure.WebJobs.Core - version 3.0.18
Microsoft.Azure.WebJobs.Extensions - Version=4.0.1
Microsoft.Azure.WebJobs.Host.Storage - Version 4.0.1

#### Expected behavior

Timer trigger working as expected.

#### Actual behavior

Timer trigger stopped working and the function to be called never got called.

#### Known workarounds

Redeployment of the service fixed the issue.

#### Related information 

Please let me know what other information I can share.

**Comment by v-anvari** [comment]
Hi @pallavit, We will try to retrieve the logs from our end if you could you please provide the function app name and approx. time stamp during which timer got busted.

**Comment by pallavit** [comment]
FunctionName: ScheduleTriggerFunctions.TriggerScheduleAsync
StartTime: 2020/10/25 10:26 AM UTC
Stop 2020/10/27 7:19 AM UTC

**Comment by v-anvari** [comment]
Hi @pallavit , is this a running function App, because our logs says that it doesn't exist
