### ISSUE TITLE
FunctionName incorrectly parsed in Kusto logs

### ISSUE THREAD

**Issue by gohar94** [Azure/azure-webjobs-sdk#2623]
Please provide a succinct description of the issue.

We noticed that after our instrumentation changes #2557, some of the apps’ logs have an incorrect `FunctionName` for the newly added log statement, while some of them are fine.

#### Repro steps
Kusto query:
```
let Time=ago(1d);
let BlobAllOps=
FunctionsLogs
| where PreciseTimeStamp > Time
| where Summary startswith "BlobReadAccess" or Summary startswith "BlobWriteAccess"
| project PreciseTimeStamp, Region=tostring(split(EventStampName, "-", 2)[0]), AppName, FunctionName, Summary, FunctionInvocationId;
BlobAllOps
| take 1000
```

#### Expected behavior

The `FunctionName` field should have the name of the function and not the name of the blob being accessed.

#### Actual behavior

The `FunctionName` field, in some cases, has the name of the blob being accessed instead of the name of the function.

#### Known workarounds

n/a

#### Related information 

I can share examples of logs that are facing this issue offline.

**Comment by gohar94** [comment]
cc: @pragnagopa @brettsam @goiri

**Comment by ThejaChoudary** [comment]
@gohar94, Could you please provide the function app name and time stamp ,which would be helpful for us to retrieve the logs.

**Comment by pragnagopa** [comment]
@ThejaChoudary - thanks for pinging. I have context on this. Assigned this to myself.

**Comment by fabiocav** [comment]
PR out, fix in progress. @pragnagopa is working on additional validation, so bumping this to sprint 91

**Comment by pragnagopa** [comment]
Released https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/4.0.4 to nuget . Package includes fix for this issue.
