### ISSUE TITLE
AsyncLocal doesn't work between FunctionInvocationFilterAttribute and HttpTrigger

### ISSUE THREAD

**Issue by hooyao** [Azure/azure-webjobs-sdk#2625]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem
I use .net core 3.1 to implement the azure functions.
The AsyncLocal doesn't work between FunctionInvocationFilterAttribute and the HttpTrigger
1. Step A
Implements FunctionInvocationFilterAttribute and set AsyncLocal value in OnExecutingAsync

2. Step B
Implements HttpTrigger and access the AsyncLocal value, the value is null.

#### Expected behavior
The AsyncLocal value should be accessible in HttpTrigger after setting its value in OnExecutingAsync.

Provide a description of the expected behavior.

#### Actual behavior
The AsyncLocal value is null in HttpTrigger after setting its value in OnExecutingAsync.
Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version  3.0.18.0
* Links to source

I use the following code to wrap the AsyncLocal
```
public class UserContextAccessor
    {
        private static readonly AsyncLocal<UserContextHolder> UserContextCurrent = new AsyncLocal<UserContextHolder>();

        public static User UserContext
        {
            get => UserContextCurrent.Value?.Context;

            set
            {
                var holder = UserContextCurrent.Value;
                if (holder != null)
                {
                    // Clear current UserContext trapped in the AsyncLocals, as its done.
                    holder.Context = null;
                }

                if (value != null)
                {
                    // Use an object indirection to hold the UserContext in the AsyncLocal,
                    // so it can be cleared in all ExecutionContexts when its cleared.
                    UserContextCurrent.Value = new UserContextHolder { Context = value };
                }
            }
        }

        private class UserContextHolder
        {
            public User Context;
        }
    }
```

**Comment by v-anvari** [comment]
Hi @hooyao , Apologies for the delayed response, we were looking at the possibilities of this scenario but, as of today this is not a supported scenario. As Async class cannot be called from a binding in this case.
