### ISSUE TITLE
Azure DevOps build fails due to inability to restore dependencies

### ISSUE THREAD

**Issue by command0r** [Azure/azure-webjobs-sdk#2632]
We've got an Azure durable function we're building in a Docker container (using Azure Pipelines). The process fails due to the following error:
`Determining projects to restore...
Restored /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj (in 11.14 sec).
/src/azure-functions-host/src/WebJobs.Script/WebJobs.Script.csproj : error NU1605: Detected package downgrade: Microsoft.Azure.WebJobs from 3.0.22 to 3.0.20. Reference the package directly from the project to select a different version.  [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
/src/azure-functions-host/src/WebJobs.Script/WebJobs.Script.csproj : error NU1605:  Microsoft.Azure.WebJobs.Script -> Microsoft.Azure.WebJobs.Extensions 4.0.1 -> Microsoft.Azure.WebJobs.Host.Storage 4.0.1 -> Microsoft.Azure.WebJobs (>= 3.0.22)  [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
/src/azure-functions-host/src/WebJobs.Script/WebJobs.Script.csproj : error NU1605:  Microsoft.Azure.WebJobs.Script -> Microsoft.Azure.WebJobs (>= 3.0.20) [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
  Failed to restore /src/azure-functions-host/src/WebJobs.Script/WebJobs.Script.csproj (in 30.01 sec).
  Restored /src/azure-functions-host/src/WebJobs.Script.Grpc/WebJobs.Script.Grpc.csproj (in 3.69 sec).
` 
After some digging, it was determined that [the change has been committed here](https://github.com/Azure/azure-functions-host/commit/002a4997dd7a388283ffb873f74d69bab057e027#), and this is what the Function uses to get the packages restored. However, as long as only v.3.0.23 is available in the NuGet, the build fails.

#### Repro steps
1. Create Azure durable function and a Docker file to get it deployed
2. Create a Build pipeline in Azure DevOps to run the build for the container. Run the build and enjoy the errors popping up :)

#### Expected behavior
The expected behavior is a flawless build (as it was last week and at the beginning of this week, before the changes for Microsoft.Azure.WebJobs were introduced, according to the aforementioned commit).
**The package with respective version (3.0.25) should be available in NuGet**, so it can be restored by the pipeline from there.

#### Known workarounds
The workaround is ugly and I don't like it. Not only it adds more 'noise' to the Dockerfile but also, just because it's a workaround and not a working properly solution. Basically, you get the latest package [from the Release page here](https://github.com/Azure/azure-webjobs-sdk/releases/tag/v3.0.25). You create a private feed and copy the package there, so it can be restored from the private NuGet repository as the Docker image builds.

#### Related information 
All links were provided in the text.

**Comment by v-anvari** [comment]
Hi @command0r, 3.0.25 version is yet to be updated in the NuGet gallery, which will be updated soon.

**Comment by v-anvari** [comment]
Closing this issue as these issues have been addressed with later versions. Please feel free to open the issue if you see anything with the latest release
