### ISSUE TITLE
Unhide the previously hidden Microsoft.Azure.Webjobs.Logging.ApplicationInsights 3.0.23 on NuGet

### ISSUE THREAD

**Issue by tompazourek** [Azure/azure-webjobs-sdk#2634]
In #2600, the **[Microsoft.Azure.WebJobs.Logging.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/) 3.0.23** was hidden because **[Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/) 3.0.23** was not yet released on NuGet.

On Wednesday 4th November, the **Microsoft.Azure.WebJobs 3.0.23** has already been released on NuGet.

@brettsam @fabiocav Can you please **unhide** the **Microsoft.Azure.WebJobs.Logging.ApplicationInsights 3.0.23**?

I've been waiting for that release for quite some time (see #2536), it'd be great to finally see it on NuGet after all that waiting.

Thank you!

**Comment by brettsam** [comment]
Done.
