### ISSUE TITLE
Custom Metrics are not collected using Application Insights

### ISSUE THREAD

**Issue by okyrylchuk** [Azure/azure-webjobs-sdk#2638]
Hi,
I've added custom Event Counters to my WebJob. I can collect them using `dotnet-counters` tool locally. I have a problem to configure Application Insights to collect them.

My Program.cs file looks this:
   ```csharp
 public class Program
 {
     public static async Task Main()
     {
        string appInsightsKey = config["WebJobApplicationInsights:InstrumentationKey"];
         var builder = new HostBuilder()
             .ConfigureWebJobs(webJobConfiguration =>
             {
                 webJobConfiguration.AddAzureStorageCoreServices();
             })
             .ConfigureLogging((context, b) =>
             {
                 // If this key exists in any config, use it to enable App Insights
                 if (!string.IsNullOrEmpty(appInsightsKey))
                 {
                     b.AddApplicationInsightsWebJobs(o => o.InstrumentationKey = appInsightsKey);
                 }
             })
             .ConfigureServices(services =>
             {
                 services.AddSingleton(config);
                 if (!string.IsNullOrEmpty(appInsightsKey))
                 {
                      services.AddApplicationInsightsTelemetry(o => o.InstrumentationKey = appInsightsKey);
                 }
                 services.ConfigureTelemetryModule<EventCounterCollectionModule>((module, o) =>
                 {
                     module.Counters.Clear();
                     module.Counters.Add(new EventCounterCollectionRequest("MyEventCounterSource", "api-request-time"));
                     module.Counters.Add(new EventCounterCollectionRequest("MyEventCounterSource", "job-processing-time"));
                 });
             })
             .UseConsoleLifetime()
             .UseAutofac();

         var host = builder.Build();
         using (host)
         {
             await host.RunAsync();
         }
     }
}
```

I found the example of customizing counters to be collected here https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected. 

I've also added `TelemetryClient` and tried to track custom metrics using `_telemetryClient.GetMetric(Job.Name).TrackValue(stopWatch.ElapsedMilliseconds);` But no custom metrics in App Insights either. 

Could you help please? Thank you in advance. 

#### Related information 

Package versions I use
* Microsoft.Azure.WebJobs.Extensions Version="4.0.1"
* Microsoft.Azure.WebJobs.Extensions.Storage Version="4.0.2"
* Microsoft.Azure.WebJobs.Host.Storage Version="4.0.1"
* Microsoft.Azure.WebJobs.Logging.ApplicationInsights Version="3.0.18" 
* Microsoft.Extensions.Hosting Version="3.1.6"
* Microsoft.Extensions.Logging.Console Version="3.1.9"

**Comment by v-anvari** [comment]
Hi @okyrylchuk , [azure-functions-supported-features](https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-functions-supported-features#supported-features), Event Counters are not listed in the supported features as of now, which could be why you are unable to see them in insights.

 Tagging  @brettsam, for more inputs

**Comment by okyrylchuk** [comment]
Hi @v-anvari, thank you for your response. 
Besides Event Counters, custom metrics from TelemetryClient also didn't show up in the App Insights. I did workaround. I've created my own instance of TelemetryClient and register it as singleton. It's not recommended in documentation. But it's the only working way I found.

**Comment by v-anvari** [comment]
Hi @okyrylchuk , Thank you for the update. It should be fine to create an instance of your own, until there is a warning or error. Let us know if you are facing any difficulty with your work around

**Comment by okyrylchuk** [comment]
Hi @v-anvari, I've been using my workaround more than a month. No warning or error. I can see my custom metrics in the App Insights.

**Comment by v-anvari** [comment]
Thankyou for the update. Closing the issue
