### ISSUE TITLE
Update package reference to Azure.Storage

### ISSUE THREAD

**Issue by matejskubic** [Azure/azure-webjobs-sdk#2644]
WebJobs.Extensions.Storage still [refers](https://github.com/Azure/azure-webjobs-sdk/blob/72cf608c3891045390b0f26d7ecec63c8a81cef7/src/Microsoft.Azure.WebJobs.Extensions.Storage/WebJobs.Extensions.Storage.csproj#L98) to obsolete package [Microsoft.Azure.Storage.Queue](https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/). 

All references should be updated to Azure.Storage ([Azure.Storage.Queues](https://www.nuget.org/packages/Azure.Storage.Queues/),...)

**Comment by v-anvari** [comment]
Hi @matejskubic, Thank you for pointing this out to us. 

Triaging the issue for updating the changes

**Comment by Bubelgin** [comment]
Is there any update possibly of when this would be implemented? We're upgrading all of our webjobs from SDK v2 to v3 since the old version is using the deprecated WindowsAzure.Storage package just to find out that v3 also uses deprecated packages...

**Comment by v-anvari** [comment]
Hi @Bubelgin , The packages are deprecated but they still support the functionalities. If this is causing you any impact, You can use [https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/4.0.4](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/4.0.4 ) package instead.

**Comment by v-anvari** [comment]
Closing this issue as the packages are still supported, only that there won't be any new releases to such packages. But, this shouldn't impact the application.

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage depends on packages above 11.1.17 of Microsoft.Azure.Storage.Queue
![image](https://user-images.githubusercontent.com/66122429/139662531-b53d4596-f6b7-480e-a24d-92a886aa6c6d.png)
