### ISSUE TITLE
Latest releases not on nuget

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-webjobs-sdk#2647]
The last release on nuget is 3.0.23 though your release page shows 24 and 25 as being released.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by v-anvari** [comment]
Hi @phatcher, Thank you for pointing this out to us.

Hi @mathewc, Can you please look into this and kindly make the required changes. 

[NuGet gallery](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/):

![image](https://user-images.githubusercontent.com/66122429/101610754-ac62e100-3a2e-11eb-82c0-46059c336710.png)

[azure-appservice](https://myget.org/gallery/azure-appservice):

![image](https://user-images.githubusercontent.com/66122429/101610887-d4eadb00-3a2e-11eb-8715-04a2ed28057c.png)

**Comment by pragnagopa** [comment]
@mhoeger  - Assigned this to you as the current release owner.  Can you please follow up and check if runtime is deployed to Windows and Linux if yes, release from myget to nuget?

**Comment by fabiocav** [comment]
Just waiting on deployments to be finalized before pushing this out.

**Comment by mhoeger** [comment]
Deployment complete and packages pushed to NuGet. Thanks!
