### ISSUE TITLE
[BlobTrigger] Change BlobScanInfo to use continuation token rather than timestamp

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#2648]
Several years ago, I added the `BlobScanInfo` to speed up our processing of blobs in large containers: #824
 
Because blob queries cannot sort or filter, we still have to list all blobs in the container on host startup. But now if the `LastUpdated` timestamp is older than the serialized `BlobScanInfo`, we'll skip it quickly. 

We've had some customer incidents where a customer is trying to trigger on a container with (I assume) many, many, many thousands of blobs. We can see the host startup, start the scan, and then it never completes a full scan as the Scale Controller scales it back down in 20 minutes 

This got me thinking -- can we instead serialize the `BlobContinuationToken` after every call to `ListBlobsSegmentedAsync()` that we make? Then when a host starts up, it can deserialize that value and continue where it left off, without needing to start from the beginning?

We consulted with @kasobol-msft and it seems like this should be possible.

Some additional pointers from @mathewc:
>We’d want to do some tests verifying the behavior where the next blob pointed to by the token is deleted, if it is indeed implemented as a “next blob name/path”. Would enumeration start after that deleted blob, or at the beginning? Not sure. As long as it doesn’t error it’s fine.

**Comment by brettsam** [comment]
FYI -- flagging as a supportability issue (even though it's more of a perf issue) so we don't lose track of it. It takes a long time to diagnose problems like this and ideally customers would never hit it.

**Comment by kasobol-msft** [comment]
If implemented plz make sure this also lands in latest extension here: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs

**Comment by kulkarnisonia16** [comment]
Closing since we are deflecting this with Blob Trigger detector. Recommendation is to use Event Grid storage integration.
