### ISSUE TITLE
Detect if Application Insights is not able to connect to the Telemetry and Live Metrics Endpoints.

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk#2649]
Customers run their Functions in a number of environments.
In some of these environments like Isolated and\or Functions Premium it is possible that they may have configured the Virtual Networks in such a way as to block access to the endpoints.
E.G DNS, Route Tables, NSG's etc.

https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-addresses 

The customer may also choose to block ingestion from the public internet.

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/private-link-security#configure-application-insights

#### Repro steps

Provide the steps required to reproduce the problem

1. Configure a New Function App and enable Application Insights. 

2. Turn off Public Network Access ingestion on the Application Insights resource. 

![image](https://user-images.githubusercontent.com/1410302/100920958-c7d06800-34d3-11eb-97d1-110eb9999709.png)

#### Expected behavior

That the Functions runtime would let you know when it is unable to send data to Application Insights. 

#### Actual behavior

No monitor data is available and there's no way to know why.

#### Known workarounds

No workarounds exist.

**Comment by brettsam** [comment]
Merging this comment from https://github.com/Azure/azure-functions-host/issues/6944 (which we'll close as dupe):

>The `ServerTelemetryChannel` now has a `TransmissionStatusEvent` that we can subscribe to and log transmission failures. This will help us diagnose failures to send telemetry to App Insights.

**Comment by fabiocav** [comment]
@brettsam moving this to next sprint, but we may need to push this back because of the .NET work.
