### ISSUE TITLE
Looking for an example of .net framework and not .netcore

### ISSUE THREAD

**Issue by kumarz** [Azure/azure-webjobs-sdk#2656]
Provide the steps required to create .net framework project for Azure webjobs. I have found the sample for .net core and it works great. However, would like to know about .net Framework

since I am getting an error for missing AzureWebStorage in-app settings in spite of having it in in the app.config file.

#### Repro steps

* create a .net framework project of version 4.6.2
* reuse the code of .net core for program.cs file
* have azureWebStorage settings in app.config file
* start the app

#### Expected behavior

A working web job with .net framework version 4.6.2

#### Actual behavior

getting an error for missing AzureWebStorage in-app settings in spite of having it in in the app.config file.

#### Known workarounds

Provide a description of any known workarounds.

**Comment by v-anvari** [comment]
Hi @kumarz, We would like to understand your scenario better. Can you provide us the piece of code that's busted. We require the content of your [app settings](https://github.com/Azure/azure-functions-core-tools/issues/1473) file or the zip deploy so that we can clone the scenario.

Also, Could you please go through the issue number [#1473](https://github.com/Azure/azure-functions-core-tools/issues/1473), this looks like a similar issue. Let us know if you are able to solve with this information

**Comment by kumarz** [comment]
@v-anvari 
Thanks for taking time to look into my issue. So I don't have any code with me. Hence asking for a sample project that is of .net framework 4.X for a webjob.

I thought it would be nice to have

**Comment by v-anvari** [comment]
Hi @kumarz , Please find the link to [create the webjobs using . Net Framework](https://docs.microsoft.com/en-us/azure/app-service/webjobs-dotnet-deploy-vs#webjobs-as-net-framework-console-apps). 

Can you confirm if you have [configured Storage](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#configure-storage-to-run-locally) to run locally in Appsetting.json file and not in the app config file. 

For the errors, #1473 might help you find some answers.

.Net Core supports all the latest features and is more reliable with the NuGet packages, so the samples are around the same.

**Comment by kumarz** [comment]
I was looking for this, 
I found it finally. 
https://github.com/Azure/azure-webjobs-sdk-samples/tree/master/BasicSamples/QueueOperations

Thanks @v-anvari 

> Hi @kumarz , Please find the link to [create the webjobs using . Net Framework](https://docs.microsoft.com/en-us/azure/app-service/webjobs-dotnet-deploy-vs#webjobs-as-net-framework-console-apps).
> 
> Can you confirm if you have [configured Storage](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#configure-storage-to-run-locally) to run locally in Appsetting.json file and not in the app config file.
> 
> For the errors, #1473 might help you find some answers.
> 
> .Net Core supports all the latest features and is more reliable with the NuGet packages, so the samples are around the same.
