### ISSUE TITLE
Triggered webjob became aborted without any reasons

### ISSUE THREAD

**Issue by haletskipavel** [Azure/azure-webjobs-sdk#2659]
#### Repro steps

We are using web jobs in the asp net core web application and faced that sometimes triggered web job changes status to aborted without any reasons and there are no related exceptions. How we can clarify the reason of why web job became aborted?

#### Expected behavior

Webjob should be always in running status

#### Actual behavior

Sometimes webjob changes its status to aborted

#### Related information 

* Application name - app-google-analytics-production
* Web job name - GoogleAnalyticsReporting.Daily.TimerWebJob
* Proximate time when webjob became aborted - from 12.01.2021 to 13.01.2021
* Always On is switched on

Installed packages
![image](https://user-images.githubusercontent.com/30402551/104422119-5cc38800-558d-11eb-93a2-fa3730fdf36c.png)

**Comment by v-bbalaiagar** [comment]
Hi @Haletski, You may review and make changes to WEBJOBS_IDLE_TIMEOUT and stopping_wait_time parameters appropriately based on your requirement and see if that helps. Checkout the [document](https://github.com/projectkudu/kudu/wiki/WebJobs#changing-the-shutdown-wait-time) for more details on this configuration.

For Continuous jobs, there is a default period of 5 seconds waiting for the job process to shutdown before getting killed.
For Triggered jobs. When a shutdown request is detected there is a 30 seconds default waiting period for the job process to stop.
You can change the grace period of a job by specifying it (in seconds) in the settings.job file where the name of the setting is stopping_wait_time like so:
{ "stopping_wait_time": 60 }

If you need 30 minutes of execution time before azure aborts it use:
"stopping_wait_time": 1800
As an aside, note that App Service has a 230 second limit for http requests that don't return data.

Also, Could you please give us location name where you have deployed the app to see the backend logs.

**Comment by haletskipavel** [comment]
Hi @v-bbalaiagar, Thank you for your answer.

WEBJOBS_IDLE_TIMEOUT is set to 36000 in the app setting value but I haven't change stopping_wait_time. Is it possible to change  stopping_wait_time via app settings? Or do we need to make a change for settings.job?

Our application deployed in the UK South location.

Thank you in advance

**Comment by v-bbalaiagar** [comment]
Hi @Haletski, You can change the grace period of a job by specifying it (in seconds) in the settings.job file where the name of the setting is stopping_wait_time like so:
{ "stopping_wait_time": 60 }

checkout the [document ](https://github.com/projectkudu/kudu/wiki/WebJobs#changing-the-shutdown-wait-time)for more details on this configuration.

Also, Could you please go through the issue number [#19686](https://github.com/MicrosoftDocs/azure-docs/issues/19686) this looks like a similar issue. Let us know if you are able to solve with this information.
