### ISSUE TITLE
Storage Extension Feature Request: Log the details about the Storage account bindings for Queues and Blobs 

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-webjobs-sdk#2660]
#### Repro steps

Customers use the Queue and Blob Storage account bindings very frequently.
If these don't work then we need to ask the customer for the details of those storage accounts to see if there is an issue on that side. 
Adding this information when the Storage extension starts to listen on the Queue or Blob container would allow us to be able to 
a) Build Detectors that access this information if the customer does raise a support request.
b) Look at automated solutions that will check connectivity to the Storage account and allow the customer to resolve transient issues on their own. 

#### Expected behavior

1.  A log entry is written when we attach to the binding. 

#### Actual behavior

1.  We log information about the queue name or the blob container but not the FQDN of the Storage account. 

#### Known workarounds

No workarounds exist.

**Comment by sidkri** [comment]
Option 1: Expand on logic in azure-functions-host\src\WebJobs.Script.WebHost\Management to include event source information
Option 2: Log these details at startup and have an analytics job that keeps a copy of startup events in a separate table.
Option 3: Log these details on each trigger event

**Comment by fabiocav** [comment]
@sidkri do we need to discuss this work item, or is this something you're expecting to handle?

**Comment by sidkri** [comment]
@fabiocav I'm handling this one but will be reviewing the solution with you before submitting a PR.

**Comment by mathewc** [comment]
Is the ask only for triggers, or for input/output bindings as well? What about binding types other than Queues (e.g. CosmosDB, etc.)? For triggers, I can see us logging some account/queue details on listener startup.

**Comment by fabiocav** [comment]
We also need to make sure any changes are ported to the track 2 SDK extensions.

**Comment by sidkri** [comment]
At present the focus is for both triggers and input/output bindings (any place a customer configures a connection with another Azure service).  Based on frequency of issues, the initial focus is Storage, Service Bus and Event Hubs.

**Comment by fabiocav** [comment]
@sidkri should we move this to the next sprint?

**Comment by sidkri** [comment]
> @sidkri should we move this to the next sprint?

Yes, I have updated it just now to the next sprint.

**Comment by fabiocav** [comment]
Moving. this back to triaged. Please assign to an appropriate sprint if needed.

**Comment by alrod** [comment]
This is done for both track1 and track2
