### ISSUE TITLE
Binding to Trigger Property - fails with "Unable to resolve binding parameter"

### ISSUE THREAD

**Issue by bgribaudo** [Azure/azure-webjobs-sdk#2663]
In an input binding's binding expression, referencing a public property on the object returned by the trigger fails with the the following error:
````
Microsoft.Azure.WebJobs.Host: Error indexing method 'HttpTriggerCSharp1'. Microsoft.Azure.WebJobs.Host: 
Unable to resolve binding parameter 'ContentType'. Binding expressions must map to either a value provided 
by the trigger or a property of the value the trigger is bound to, or must be a system binding expression 
(e.g. sys.randguid, sys.utcnow, etc.).
````

**Trigger/binding setup being used:**
_Note how binding `Special`'s `ContentType` value is set to a binding expression which attempts to reference the `ContentType` property from the trigger input object._
````
public static IActionResult Run(
   [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
   [Special(ContentType="{ContentType}")] string special)
````

#### Repro steps

Provide the steps required to reproduce the problem

1. Create an Azure Function defined as follows:
	<details>
	 <summary>Function definition, including custom input binding.</summary>
        <pre>
	using System;
	using System.Threading.Tasks;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.Azure.WebJobs;
	using Microsoft.Azure.WebJobs.Extensions.Http;
	using Microsoft.AspNetCore.Http;
	using Microsoft.Azure.WebJobs.Description;
	using Microsoft.Azure.WebJobs.Host.Config;
	using Microsoft.Azure.WebJobs.Hosting;
	using Work;

	[assembly: WebJobsStartup(typeof(SpecialBindingStartup2))]
	namespace Work
	{
		public class SpecialBindingStartup2 : IWebJobsStartup
		{
			public void Configure(IWebJobsBuilder builder) {
				builder.AddExtension`<SpecialBinding`>();
			}
		}

		[AttributeUsage(AttributeTargets.Parameter)]
		[Binding]
		public sealed class SpecialAttribute : Attribute
		{
			[AutoResolve]
			public string ContentType {get; set; }
		}

		[Extension("SpecailBinding")]
		public class SpecialBinding : IExtensionConfigProvider
		{
			public void Initialize(ExtensionConfigContext context) =>
				context.AddBindingRule<SpecialAttribute>()
					.BindToInput<string>(BuildItemFromAttribute);
				
			private string BuildItemFromAttribute(SpecialAttribute arg) =>
				"hello - content type: " + arg.ContentType;
		}
		
		public static class HttpTriggerCSharp1
		{
			[FunctionName("HttpTriggerCSharp1")]
			public static IActionResult Run(
				[HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
				[Special(ContentType="{ContentType}")] string special)
			{
				
				return new OkObjectResult("Hi - special: " + special);
			}
		}
	}
        </pre>
	</details>

2. Start the Function (`func host start`). The above-mentioned error will appear in the logs displayed in the console.

#### Expected behavior

`SpecialAttribute`'s `ContentType` property should be set to the value of `req`'s `ContentType` property.

#### Actual behavior

Binding fails with the above-mentioned error.

#### Related information 

Creating custom input and output bindings first [binding expressions example](https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings#binding-expressions) suggests that an input binding's attribute's binding expression can reference public properties on the object provided by the trigger binding.

Package version: Microsoft.NET.Sdk.Functions 3.0.11

**Comment by v-anvari** [comment]
Hi @bgribaudo , Can you give us an example of the custom binding that you are using. We would like to reproduce the scenario to understand the error better

**Comment by bgribaudo** [comment]
Hi @v-anvari,

Thanks for looking at this. The custom binding is included in the source code in this issue's body (hidden under the spoiler under "Repo Steps", "1. Create an Azure Function defined as follows:", "Function definition, including custom input binding.").

**Comment by v-anvari** [comment]
Thankyou @bgribaudo , We will be looking into it

**Comment by bgribaudo** [comment]
Thank you, @v-anvari!

**Comment by v-anvari** [comment]
Hi @bgribaudo , I tried to repro but, unable to repro it right. What is in the namespace Work. Can you give a zip file of the project to my mail?

**Comment by bgribaudo** [comment]
@v-anvari, thanks for looking into this. Zip shared.

**Comment by v-anvari** [comment]
Hi @bgribaudo , Thankyou for the repro, I could get the error, it could be because the special attribute that you are building is not defined completely. The rules need to be defined as explained in the document you have referred to earlier . Can you tell us the purpose of the special attribute used here.

**Comment by bgribaudo** [comment]
HI @v-anvari,

Thanks for looking at this.

I believe the custom binding implementation itself works fine. This can be tested by changing:

````
public static IActionResult Run(
  [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
  [Special(ContentType = "{ContentType}")] string special)
````

to

````
public static IActionResult Run(
  [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
  [Special(ContentType = "abc")] string special)
````

After making this change, "abc" gets passed into `Special`. This can be observed by setting a breakpoint inside `BuildItemFromAttribute`. Based on this, it seems the custom binding itself works fine.

It seems the problem is that the binding expression `{ContentType}` isn't being properly evaluated by the SDK. My understanding is that public properties on the trigger object (in this case, `HttpRequest`) should be available to other bindings via binding expressions. However, that isn't happening here; otherwise, `Special(ContentType = "{ContentType}")` should be passed the value of `HttpRequest`'s content type property.
