### ISSUE TITLE
Release Storage extension to nuget

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk#2668]
https://github.com/Azure/azure-webjobs-sdk/commit/21d9d4ea4917a11f274bcd9f61600fbfbfceed17

Assigning to myself as currently I am currently on the release loop

**Comment by fabiocav** [comment]
Need to ensure the Azure SDK team is notified or a PR is sent to them.

**Comment by pragnagopa** [comment]
Track 2 porting issue: https://github.com/Azure/azure-sdk-for-net/issues/18720

**Comment by pragnagopa** [comment]
Release: https://github.com/Azure/azure-webjobs-sdk/releases/tag/storage-v4.0.4

Increment to next version: https://github.com/Azure/azure-webjobs-sdk/pull/2675

**Comment by pragnagopa** [comment]
Pushed Microsoft.Azure.WebJobs.Extensions.Storage 4.0.4  to myget feed: azure-appservice-staging

**Comment by pragnagopa** [comment]
Closing as addressed: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage/4.0.4
