### ISSUE TITLE
How to listen to multiple topics across multiple service bus

### ISSUE THREAD

**Issue by ssumit** [Azure/azure-webjobs-sdk#2673]
Is there an example or a recommended way when there are multiple service bus involved ?
Currently I can use a single service bus and multiple topics (via multiple function/event handlers).
I'm using 1 JobHost with 1 ServiceBusConfiguration object in my app service

In case of say 2 service bus, should we create 2 JobHost objects or there is way to use multiple service bus using 1 JobHost ?

I also see ServiceBusTrigger attribute with field connection. However, m not sure how to use it as the connection string is fetched from key-vault dynamically. If only I could inject it via some DI magic. Its not calling INameResolver implementation for Connection field.

Versions m using -
    "Microsoft.Azure.WebJobs" Version="2.3.0"
    "Microsoft.Azure.WebJobs.Core" Version="2.3.0"
    "Microsoft.Azure.WebJobs.ServiceBus" Version="2.3.0"

**Comment by v-bbalaiagar** [comment]
Hi @ssumit, A single job function is tied to a single ServiceBus connection. The trigger attribute model is not designed to allow you to have a single function that is triggered by multiple different connections/queues.
Also, Could you please go through the issue number [#2042](https://github.com/Azure/azure-webjobs-sdk/issues/2042)  this looks like a similar issue.

**Comment by ssumit** [comment]
Hi, thanks for the response. I wanted to add more clarification. The requirement is to listen to multiple service bus say A and B.
I'm creating two different functions for this purpose. 
The problem m facing is that in AppService, m not able to use Connection attribute in ServiceBusTrigger annotation or ServiceBusAccount annotation.
We use key-vault to get the key and therefore the value is not present directly in settings. Currently in my setup, the key is fetched from key-vault and stored in one of the objects. However I don't know how i can inject that object/value to use ServiceBusTrigger or ServiceBusAccount.

Note that for a single bus scenario, m able to use ServiceBusConfiguration which gets added to JobHostConfiguration.

**Comment by v-bbalaiagar** [comment]
cc @alrod, Tagging alexey for more inputs

**Comment by alrod** [comment]
You can use KeyVault secrets values as AppSettings:
https://azure.microsoft.com/en-us/blog/simplifying-security-for-serverless-and-web-apps-with-azure-functions-and-app-service

**Comment by v-bbalaiagar** [comment]
Hi @ssumit, Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
