### ISSUE TITLE
The log of Azure Function on Application Insights changed customDimensions name from prop__FunctionName to prop__functionName

### ISSUE THREAD

**Issue by FanBaoMS** [Azure/azure-webjobs-sdk#2676]
#### Repro steps

1. Create a new Azure Function project (HTTP trigger) with following codes
```
        [FunctionName("Function1")]
        public static IActionResult Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)] HttpRequest req,
            ILogger log)
        {
            using (log.BeginScope(new Dictionary<string, object> { ["FunctionName"] = "Test" }))
            {
                log.LogInformation("C# HTTP trigger function processed a request.");
            }

            return new OkResult();
        }
```

2. Create a new Azure Function (Windows) resource with Application Insights enabled, deploy the project. (When I test all deployed to West US 2).

3. Test run and wait for the log available.

#### Expected behavior

The trace looks like `customDimensions={ "prop__FunctionName" : "Test" }` (Uppercase for F)

#### Actual behavior

The trace looks like `customDimensions={ "prop__functionName" : "Test" }` (lowercase for f).

#### Known workarounds

Not found.

#### Related information 

I noticed this issue recently (our other Azure resources read the prop_functionName) and found that the behavior changed since 2/4, with different SDK versions on that day.

I ran following query on Application Insights around 2/4

```
traces
traces
| where not (message startswith "Executing '" or message startswith "Executed '" or message startswith "Stopped the listener" or message startswith "Stopping the listener")
| summarize f = countif(tostring(customDimensions.prop__functionName) != ''), F = countif(tostring(customDimensions.prop__FunctionName) != '') by sdkVersion, bin(timestamp, 1d)
| order by timestamp asc
```

Here is the result

timestamp [UTC] | skdVersion | f | F
-- | -- | -- | --
2/2/2021, 12:00:00.000 AM | azurefunctions: 3.0.15193.0 | 0 | 12,017
2/3/2021, 12:00:00.000 AM | azurefunctions: 3.0.15193.0 | 0 | 12,580
2/4/2021, 12:00:00.000 AM | azurefunctions: 3.0.15371.0 | 567 | 0
2/4/2021, 12:00:00.000 AM | azurefunctions: 3.0.15193.0 | 0 | 12,232
2/5/2021, 12:00:00.000 AM | azurefunctions: 3.0.15371.0 | 10,893 | 0
2/6/2021, 12:00:00.000 AM | azurefunctions: 3.0.15371.0 | 181 | 0

According to the result, the change happens along with the SDK version update from 3.0.15193 to 3.0.15371.

My question is that is the behavior change expected (e.g., functionName is a preserved word now)? If the change is expected, we would change our project to use another value to replace FunctionName.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @brettsam / @pragnagopa.  Can you please have a look at this issue? Thank you!

**Comment by FanBaoMS** [comment]
Hi @ChaitanyaNaykodi-MSFT, @brettsam, @pragnagopa. I did some investigation in the code, and I suspect it's due to following change. However, it's a change made 3 months ago. I'm not sure about Azure Function host release cycle, so not sure if this change was made into product on 2/4.

https://github.com/Azure/azure-webjobs-sdk/commit/b65cd520e7a6e6fc08dd59d7ab6328d79ee480d5#diff-53748978dccb3c067e2aec0255d681b45146638d23f2c806c1033ca524db0b81

In line 26 there is a property name cache added with `StringComparer.OrdinalIgnoreCase`, and based on the log I see 2 additional system logs generated before and after the actual function logic `Executing '{functionName}'...` and `Executed '{functionName}'...`. Therefore, my assumption is that the property names are shared between the system log and user log, and case ignored (whichever name appears first will keep the capitalization form). Therefore, since `Executing` is generated first, the `functionName` gets into the cache and all following logs would use `functionName` even if it's `FunctionName`. Similarly, other properties would be affected. I verified my assumption with following code.

```
            using (log.BeginScope(new Dictionary<string, object>
            {
                ["FunctionName"] = "Test1",
                ["InvocationId"] = "Test2",
                ["Reason"] = "Test3",
                ["Status"] = "Test4",
                ["ExecutionDuration"] = "Test5"
            }))
            {
                log.LogInformation("C# HTTP trigger function processed a request.");
            }
```

Here `FunctionName`, `InvocationId`, and `Reason` are used by `Executing`, so in this user log, their first letters are lowercase. The `Status` and `ExecutionDuration` are used by `Executed`, so they keep their first letters as uppercase in user log, but in the `Executed` system log, they are still uppercase (their first letters would be lowercase if I don't have this user log) since I get these property names into cache before the `Executed` log.

I think it's wrong to have system logs and user logs share the same property name cache and suggest to fix it. I'm also not sure if it's a good idea to make the cache case ignored. I think there could be cases like I may use different libraries in the same Azure Function, and they have different naming styles for the same property name. I don't want the log appears differently for each function run just because whether and when a particular log is triggered in this case.

**Comment by v-anvari** [comment]
Triaging this issue, as it requires further investigation.
CC @mathewc , Could you confirm if the commit was intentional or requires an update. As the change happens along with the SDK version update from 3.0.15193 to 3.0.15371.

**Comment by mathewc** [comment]
Agree with the analysis. The name cache was added as an optimization, and the fact that it's case insensitive was a subtle unintentional change. The cache should probably be case sensitive to preserve the previous behavior. @brettsam do you agree?

**Comment by FanBaoMS** [comment]
Ping, is there any plan for the fix?

**Comment by baconpat** [comment]
It appears I'm also seeing this same issue, although in my case the variable went from the expected lower case to upper case, starting on January 26th, 2021.

Looking at the `sdkVersion`, the problem seems appears to have started for us with the switch from 3.0.15185.0 to 3.0.15277.0 on that date.

I've got App Insights queries that are looking for specific values under `prop__variableName` that are now broken because after January 26th the logs only contained `prop__VariableName`.

**Comment by mm-gmbd** [comment]
@mathewc @brettsam pinging for a timeline for a fix as well.

I'm considering this a fairly **serious issue**, as this has caused some important information in our production App Insights logs being unqueryable, or at least unqueryable without additional work. This has negatively affected internal and external support requests for our production system.

Also, looking at the [App Insights REST API](https://docs.microsoft.com/en-us/rest/api/application-insights/), it doesn't appear that there is a way to update logs after they've been pushed into App Insights. So, even when this is resolved, will we have a bulk of logs between January and April (hopefully not any longer) that we will have to treat specially?

With all that in mind, I'd appreciate a fix as well as suggestions on how to deal with logs that have been impacted.

**Comment by mathewc** [comment]
Guys - I just sent a PR https://github.com/Azure/azure-webjobs-sdk/pull/2691 fixing this issue. Please have a look. We'll expedite this into our next release.

**Comment by FanBaoMS** [comment]
Verified that the issue was fixed since 4/26 for our Azure Function resources. Thanks for the fix and close the issue.
