### ISSUE TITLE
How to debug an IScaleMonitor implementation (scale controller) ?

### ISSUE THREAD

**Issue by cbar92** [Azure/azure-webjobs-sdk#2681]
I develop a custom azure function trigger which implement the IScaleMonitor interface but I'm not able to view any log activity into Application Insights after deployment into Azure Function with Consumption plan.
In //, my extension works well but I can't able to scale in or scale out the Azure Function.

Also can you provide sample and documentation because no technical resources are available.

Thanks

**Comment by v-anvari** [comment]
Hi @cbar92 , We require more information to understand the scenario. Can you provide us the repro steps and what are you trying to achieve
Meanwhile, can you check if you have configured the Application Insights properly - [https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-trace-logs#configure-application-insights-to-collect-logs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-trace-logs#configure-application-insights-to-collect-logs)
