### ISSUE TITLE
Microsoft.Azure.Functions.Extensions package with Microsoft.Extensions.DependencyInjection v5.x.x needed

### ISSUE THREAD

**Issue by Fraegle** [Azure/azure-webjobs-sdk#2685]
We are using WebJobs in Azure App Services and we want to migrate to using Azure Functions instead. The WebJob projects are targeting netcoreapp3.1 and we reference (amongst others)
Microsoft.Extensions.DependencyInjection v5.0.1
Microsoft.Extensions.Logging v5.0.0
Microsoft.EntityFrameworkCore.Tools v5.0.4

As documented, the current version (1.1.0) Microsoft.Azure.Functions.Extensions does only support Microsoft.Extensions.DependencyInjection v3.x.x

#### Repro steps

I created a repro here
https://github.com/Fraegle/azure-functions-dependency-injection-repro

 - If we reference Microsoft.Extensions.DependencyInjection v3.x.x in the Functions project, we are getting a package downgrade error (NU1605) on compilation when referencing the projects using the 5.x.x packages.

 - If we reference the 5.0.1 version of of Microsoft.Extensions.DependencyInjection, we are getting runtime exceptions like these:
   - System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions
   - Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

#### Expected behavior

We would like to be able to use the same code that currently runs in our WebJobs also in Azure Functions

#### Actual behavior

As EntityFramework Core 5.x requires 5.x NuGets that ultimately force us to use Microsoft.Extensions.DependencyInjection 5.x, we are currently not able to migrate to Azure Functions.

#### Known workarounds

None

**Comment by vigouredelaruse** [comment]
if i understand you your project references resemble 

    PackageReference Include="AutoMapper" Version="10.1.1" />
    PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    PackageReference Include="Azure.Data.Tables" Version="3.0.0-beta.5" />
    PackageReference Include="azure.identity" Version="1.4.0-beta.3" />
    PackageReference Include="AzureFunctions.Extensions.DependencyInjection" Version="1.1.3" />
    PackageReference Include="AzureFunctions.Extensions.Swashbuckle" Version="1.4.4" />
    PackageReference Include="DurableFunctionsAnalyzer" Version="0.1.26" />
    PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    PackageReference Include="microsoft.azure.management.fluent" Version="1.37.1" />
    PackageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.37.1" />
    PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.25" />
    PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.1" />
    PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.4.0" />
    PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    PackageReference Include="Microsoft.Azure.WebJobs.Host.Storage" Version="4.0.1" />
    PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.25" />
    PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.1" />
    PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
    PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.0.0" />
    PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.0.0" />
    PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.13" />
    PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
    PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.14" />
    PackageReference Include="System.Linq.Async" Version="5.0.0" />
    PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.9.0" />
    PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="6.9.0" />

i can get this to work in a linux container in a b1 app service function app but not via webdeploy - i haven't looked into the background issues but this is another option to try - running out of process https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

**Comment by Fraegle** [comment]
We are not running containers and we are not running Linux. The issues happened, when running the Functions App project on the local dev box, so it wouldn't even make it to a PR advancing to the deployed service.

**Comment by Fraegle** [comment]
Also, as men

**Comment by Fraegle** [comment]
Also, as mentioned above, the target of the WebJob Projects are also netcoreapp3.1. That works well, even though the NuGets are 5,x

**Comment by vigouredelaruse** [comment]
the package refs i pasted above go with this netcoreapp3.1 situation - i only mention the docker option as a potential way to get unblocked locally and potentially in production - the configuration i've shared here will only run in a docker container

          <PropertyGroup>
            <TargetFramework>netcoreapp3.1</TargetFramework>
            <AzureFunctionsVersion>v3</AzureFunctionsVersion>
        
            <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
           <DockerfileTag>azure-table-retention-appliance</DockerfileTag>
            <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
            <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
            <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
            <PublishReadyToRun>true</PublishReadyToRun>
            <RuntimeIdentifier>win-x86</RuntimeIdentifier>
            <Platforms>AnyCPU;x86</Platforms>
          </PropertyGroup>
          <ItemGroup>

**Comment by Fraegle** [comment]
At the moment we would prefer, that it works without containerizing the project.

**Comment by Fraegle** [comment]
I have created a repro and updated the repro steps at the top. I added a link to that repo there. 

You were right and the Microsoft.Extensions.DependencyInjection was not the actual issue. I was just assuming it, because the [documentation ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) stated, that it only works with 3.x. 

The actual problem started, when I added Microsoft.Extensions.Logging.Abstractions v5.0.0 to the project. Then I started seeing the file load exceptions. 

 - Adding the two binding redirect elements did not fix the issue.
 - Adding PublishReadyToRun did not help, but I just ran the project in VisualStudio, I did not actually call dotnet publish
 - I am using VisualStudio 2019 Preview 1.0 to build and run the project.

**Comment by vigouredelaruse** [comment]
> The actual problem started, when I added Microsoft.Extensions.Logging.Abstractions v5.0.0 to the project. Then I started seeing the file load exceptions.

sorry to hear you're still blocked on this definite issue that i can also reproduce as you reported (break by upgrading to 5x, fix by downgrading to 3x) with the config i posted

on the other hand i fixed my build configuration and now i can publish with the 3.x setup to either docker or windows function apps as advertised

**Comment by Fraegle** [comment]
We cannot downgrade to 3.x, because that would violate the requirements of Entity Framework 5.x, which is one of the packages required by one of dependencies we need to inject.

**Comment by v-anvari** [comment]
Hi @Fraegle , Apologies for the delay, we will be looking into this issue and update you

**Comment by v-anvari** [comment]
This issue requires further investigation for a workaround on the dependencies. Tagging @brettsam for more insights here.

**Comment by v-anvari** [comment]
Hi @Fraegle ,
5.X.X versions are supported and were explicitly released for .Net 5. .Net core 3.xx or lesser do not support the 5.x.x versions. There has been a 5.x.x package release for the required package. Below is the link. 
https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/5.0.2

Closing this issue hoping that the issue will be fixed with this package. Please feel free to open in case of any issue or queries
