### ISSUE TITLE
Suggestion to improve code and performance

### ISSUE THREAD

**Issue by Shazhko-Artem** [Azure/azure-webjobs-sdk#2689]
Why does the [BindingFactoryHelpers](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingFactoryHelpers.cs) class uses reflection to build the [CustomTriggerArgumentBinding](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Triggers/TriggerArgumentBinding/CustomTriggerArgumentBinding.cs)? There are no advantages in this approach, only disadvantages: 
- It makes the code very difficult to understand.
- Worsens performance.

#### Solution option

Reflection is not needed to build the `SimpleTriggerArgumentBinding`, it is enough to take the following steps:
1. To get the [FuncAsyncConverter ](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/FuncConverter.cs )you need to use the `FuncAsyncConverter GetConverter<TAttribute>(Type typeSource, Type typeDest)` method in the [IConverterManager](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/IConverterManager.cs) instance.
2. Create `CustomTriggerArgumentBinding<TMessage, TTriggerValue>` class in which "UserType" can be passed through the constructor.

##### Code examples

The `GetDirectTriggerBindingWorker` method in the [BindingFactoryHelpers](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingFactoryHelpers.cs) class should be rewritten as follows.

``` c#
private static SimpleTriggerArgumentBinding<TMessage, TTriggerValue>
    GetDirectTriggerBindingWorker<TMessage, TTriggerValue>(
        ITriggerBindingStrategy<TMessage, TTriggerValue> bindingStrategy,
        IConverterManager converterManager,
        Type userType)
{
    var directConvert = converterManager.GetConverter<Attribute>(typeof(TMessage), userType);
    if (directConvert != null)
    {
        var argumentBinding = new CustomTriggerArgumentBinding<TMessage, TTriggerValue>(
            bindingStrategy, converterManager, directConvert, userType);
        return argumentBinding;
    }
    return null;
}
```

The `GetDirectTriggerBinding ` method in the [BindingFactoryHelpers](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingFactoryHelpers.cs) class should be rewritten as follows.

``` c#
private static SimpleTriggerArgumentBinding<TMessage, TTriggerValue>
    GetDirectTriggerBinding<TMessage, TTriggerValue>(
        Type exactType,
        ITriggerBindingStrategy<TMessage, TTriggerValue> bindingStrategy,
        IConverterManager converterManager)
{
    return GetDirectTriggerBindingWorker(bindingStrategy, converterManager, exactType);
}
```

An example of the implementation of the class `CustomTriggerArgumentBinding<TMessage, TTriggerValue>`.

``` c#
internal class CustomTriggerArgumentBinding<TMessage, TTriggerValue> :
    SimpleTriggerArgumentBinding<TMessage, TTriggerValue>
{
    private IBindingDataProvider _bindingDataProvider;
    private readonly FuncAsyncConverter _converter;
    private readonly Type _userType;

    public CustomTriggerArgumentBinding(
        ITriggerBindingStrategy<TMessage, TTriggerValue> bindingStrategy,
        IConverterManager converterManager,
        FuncAsyncConverter converter,
        Type userType) : base(bindingStrategy, converterManager)
    {
        if (converter == null)
        {
            throw new ArgumentNullException(nameof(converter));
        }

        this._converter = converter;
        _userType = userType;
        this.ElementType = _userType;

        _bindingDataProvider = BindingDataProvider.FromType(ElementType);
        AddToBindingContract(_bindingDataProvider);
    }

    internal override async Task<object> ConvertAsync(
        TMessage value,
        Dictionary<string, object> bindingData,
        ValueBindingContext context)
    {
        var obj = await _converter(value, null, context);

        AddToBindingData(_bindingDataProvider, bindingData, obj);

        return obj;
    }
}
```

##### Result

The above code examples allow you to get the same behavior, but with more readable code and without sacrificing performance.

**Comment by v-anvari** [comment]
Hi @Shazhko-Artem , This requires further investigation on the code to work on the improvements. I suggest you to raise a new pull request for this case and link it here.

**Comment by Shazhko-Artem** [comment]
Hi @v-anvari , I raised a new pull request for this case. The solution was successfully built, but I can't figure out what the problem is with _vstest.console_. Looks like it's a pipeline setup problem. Let me know if the problem is with my pull request.
![image](https://user-images.githubusercontent.com/31850295/117451562-55185c80-af4b-11eb-9ac6-45a4008d1b29.png)

**Comment by v-anvari** [comment]
Hi @Shazhko-Artem , I shall follow up with the team to check if there is any known issue, will reach back to you if we require any further information

**Comment by Shazhko-Artem** [comment]
Hi @v-anvari, do you have any updates?

**Comment by v-anvari** [comment]
Hi @Shazhko-Artem , I am following up with the team and the PR will be assigned to anyone from the team for further look up.
