### ISSUE TITLE
Azure Functions V2 - Unable to use Retry Policy due to versioning isues

### ISSUE THREAD

**Issue by ghost** [Azure/azure-webjobs-sdk#2696]
For an Azure Function (HTTP Function)
Can't install Microsoft.Azure.WebJobs 3.0.23 because of Newtonsoft versioning issue with Microsoft.NET.Sdk.Functions 1.0.13.  Microsoft.NET.Sdk.Functions 1.0.13 is the versioning that must be set for V2 functions, nothing higher than version 1.0.13 works out of the box with no other changes.

#### Repro steps

Steps to replicate issue:

1. Add the ExponentialBackoffRetry code:
[FunctionName("HWebhookHandler")]
[ExponentialBackoffRetry(5, "00:00:04", "00:15:00")]
public static IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequest req, TraceWriter log)
{
	//Code & logic here
}

2. Attempt to install NuGet package Microsoft.Azure.WebJobs 3.0.23 (required for Retry Policy use as referenced here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-policies-preview).  This creates a versioning warning and stops the install til resolved
![Can't install webjobs because of Newtonsoft version issue](https://user-images.githubusercontent.com/8828716/114445903-3b773580-9b96-11eb-993b-991036973107.png)

3. Install NuGet package Newtonsoft 11.0.2.  This creates the warning below in reference to Microsoft.NET.Sdk.Functions 1.0.13:
![image](https://user-images.githubusercontent.com/8828716/114446468-dec84a80-9b96-11eb-8ba4-c3c15e3ac394.png)

4. Installing NuGet package Microsoft.Azure.WebJobs 3.0.23 resolves the ExponentialBackoffRetry reference but project still doesn't work do to Microsoft.NET.Sdk.Functions 1.0.13 needing Newtonsoft (= 10.0.23)

**Comment by fabiocav** [comment]
@LockpickingDev is there something preventing you from targeting Functions 3.0? V2 will no longer see feature updates

**Comment by ghost** [comment]
We are currently only using .NET Standard 2.0.  Is that the only way to go about it other than hard coding retry logic in?

**Comment by fabiocav** [comment]
You can continue to target .NET Standard 2.0 and run on V3. 

For new features and SDK updates, remaining in 2.0 would become a blocker.

**Comment by ghost** [comment]
Is there any documentation to assist in showing how to do that?  My first thought was to edit that project and change V2 to V3 then change target in Azure to V3.  But, that doesn't seem like something that would allow me install more a recent version of NuGet packages.

**Comment by ghost** [comment]
I'm using Visual Studio 2017.  I don't see an option for V3 while creating a project (I'm assuming because I have .NET Standard 2.0?)
![image](https://user-images.githubusercontent.com/8828716/114492788-e0b5fc00-9bde-11eb-845d-40a6b5d42c63.png)

**Comment by ghost** [comment]
If it isn't possible to use V3 due to some constraint, is there logic to recall the Azure Function?  This way we could implement our own Retry policy on Exception?

**Comment by v-anvari** [comment]
Hi @LockpickingDev, You would need Visual studio 19 for using version 3 - [https://dotnet.microsoft.com/download/dotnet/3.1](https://dotnet.microsoft.com/download/dotnet/3.1). 

You can use the .net standard 2.0 and target version 3. 
[https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal)

**Comment by LockpickingDev** [comment]
Ok, so other than going to Visual Studio 19, there is no way to do actual retry logic other than hard coding some loop to try the code again on a fail?  Sounds like no way to retry a request given what we have at the moment...

**Comment by ghost** [comment]
> Hi @LockpickingDev, You would need Visual studio 19 for using version 3 - https://dotnet.microsoft.com/download/dotnet/3.1.
> 
> You can use the .net standard 2.0 and target version 3.
> https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal

For using .NET Standard 2.0 to target V3, are you referring to referencing Extension Bundles in the host.json file to prevent incompatibilities?  If so, will that work with HTTP Triggers (this project is a HTTP Trigger)?  The article says: "With the exception of HTTP and timer triggers, Functions bindings in runtime version 2.x and higher are implemented as extension packages. HTTP bindings and timer triggers don't require extensions."

**Comment by ghost** [comment]
> Hi @LockpickingDev, You would need Visual studio 19 for using version 3 - https://dotnet.microsoft.com/download/dotnet/3.1.
> 
> You can use the .net standard 2.0 and target version 3.
> https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal

I read through that document and made no real progress nor have any new findings.  Here's what I encountered when trying each section in the referenced link (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register)

"Extension bundles"
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles
It says "To add an extension bundle to your function app, add the extensionBundle section to host.json."  I added the code suggested with the updated version from the article:
`{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 3.0.0)"
  }
}`
There's nothing in this section other than basically "add this code and it will work" that explains what to do after adding the code.  So I added the code, cleaned the project, and built it.  All the NuGet packages with conflictin references were installed before doing this and they're still throwing the same reference conflict error.  My next thought was removing all the packages with errors then running but that wouldn't make sense in fixing the package issues while they are installed from what I'm seeing.  Even tried manually installing Microsoft.Azure.WebJobs.Extensions and no luck after a clean and build.

"Explicitly install extensions"
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#explicitly-install-extensions
I don't have access to the .NET Core CLI due to permission within my org so that's a no-go.  I tried running the func extensions install in the "Command Window" and "Package Manager Console" but "func" is not recognized.  If I did have the CLI available, does installing 2 different versions of Newtonsoft.Json actually work?  I haven't seen a situation where this is possible yet...  That is the original issue, 2 NuGet packages needed for Retrys need different versions of Newtonsoft.Json.

"Install extensions from NuGet in .NET languages"
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#local-csharp
What would I install from NuGet to get this working?  As already mentioned, I've tried installing Microsoft.Azure.WebJobs.Extensions.  What package from that bundle would I install that would allow 2 versions of Newtonsoft.Json to work at the same time to resolve conflicting references?

**Comment by fabiocav** [comment]
Extension bundles should not be used by .NET Applications, particularly pre-compiled apps.

The steps to work with extension bundles (either by referencing them or installing the extensions with the tool) do not apply to .NET, as all that is. needed for that scenario is a NuGet package reference to the relevant extensions. 

Visual Studio 2019 is not a requirement to work with Functions 3.0, but it's the only version of VS that supports it, so you need to be on that version if you want to continue using VS for development.

**Comment by ghost** [comment]
> Extension bundles should not be used by .NET Applications, particularly pre-compiled apps.
> 
> The steps to work with extension bundles (either by referencing them or installing the extensions with the tool) do not apply to .NET, as all that is. needed for that scenario is a NuGet package reference to the relevant extensions.
> 
> Visual Studio 2019 is not a requirement to work with Functions 3.0, but it's the only version of VS that supports it, so you need to be on that version if you want to continue using VS for development.

Ok.  What section of the article (or what article in general) helps me get .net standard 2.0 working with V3 that will resolve the conflicting references to different versions of Newtonsoft.Json?  I'm reading through everything as carefully as I can but not seeing no solutions.

**Comment by fabiocav** [comment]
My assumption is that @v-anvari shared the article above as a guide on how to target/change the runtime version. She can confirm.

For your original problem, targeting Azure Functions 3.0, which you can continue to do even if targeting .NET Standard 2.0, is what will give you access to the functionality you're looking for. For VS support, 2019 is required in order to work with 3.0.

Can you clarify the conflicts you're experiencing?

**Comment by ghost** [comment]
> My assumption is that @v-anvari shared the article above as a guide on how to target/change the runtime version. She can confirm.
> 
> For your original problem, targeting Azure Functions 3.0, which you can continue to do even if targeting .NET Standard 2.0, is what will give you access to the functionality you're looking for. For VS support, 2019 is required in order to work with 3.0.
> 
> Can you clarify the conflicts you're experiencing?

The original post has a detailed description of the NuGet package version conflicts we are experiencing with V2 using Visual Studio 2017.  From what you just said though, sounds like we **need** VS 2019 in order to do this in Visual Studio and get the functionality of Azure Functions V3.

Thank you for all the help!
