### ISSUE TITLE
Probable DDoS vulnerability on error binding

### ISSUE THREAD

**Issue by AlbertoLeon** [Azure/azure-webjobs-sdk#2699]
When a negotiate end point expects UserId binding in headers for example {headers.x-ms-signalr-userid} but it is not present, the end point responds a 500 InvalidOperationException instead of a BadRequest.

This could overload the server handling the error and logging the stack trace and all that stuff.
Apart of taking so mutch time to respond, what impacts negatively in performance.

A proposed solution could be to respond BadRequest with the message "A required header is missing for binding purposes".
Then log in appropiately on Application Insights with the message:
An attemp missed the header x-ms-signalr-userid required in Binding UserId.

1. Create an Azure Functions with SignalR
2. Add negotiate EndPoint / Function
3. Add the binding UserId on the SingalR Connection Info binding with the mentioned value `{headers.x-ms-signalr-userid}` ex. `[SignalRConnectionInfo(HubName = "notifications", UserId = "{headers.x-ms-signalr-userid}")]`
4. Call the endpoint negotiate without the expected header

Returns a 500 server error.

**Comment by v-bbalaiagar** [comment]
Hi @AlbertoLeon, Thank you for reaching out to us, Can you provide us more information regarding the project scenario, any repro steps

**Comment by AlbertoLeon** [comment]
> Hi @AlbertoLeon, Thank you for reaching out to us, Can you provide us more information regarding the project scenario, any repro steps

I've just updated the description

**Comment by v-bbalaiagar** [comment]
Tagging @anthonychu, for more inputs

**Comment by fabiocav** [comment]
@AlbertoLeon thank you for reporting this. We'll continue to follow up on this but remove the issue as per security policies. I've also updated the repo with the reporting information. 

Thanks again!
