### ISSUE TITLE
Method not found: 'Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1<!!0> 

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-webjobs-sdk#2703]
We've been running into a problem between Azure Functions (.NET Core 3.1) and Application Insights.

I've already let the AppInsights team know, but filing a bug here, since they say the host is different.

I've created a sample repo to show the problem.

#### Repro steps

https://github.com/kirk-marple/function-app-missingmethodexception

Simply updating from 2.15.0 to 2.16.0 or 2.17.0 causes the missing method exception.  I've been able to reproduce this in VS2019,  just running func.exe in the debugger.

#### Expected behavior

No exception.

#### Actual behavior

```
[2021-04-05T21:01:48.941Z] System.Private.CoreLib: Exception while executing function: HttpFunction. FunctionApp: Method not found: 'Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1<!!0> Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation(Microsoft.ApplicationInsights.TelemetryClient, System.Diagnostics.Activity)'.
```

**Comment by v-anvari** [comment]
Hi @kirk-marple , These dependencies were coming from other packages which contained similar packages. The issue occurred due to a mismatch which has been fixed with the later packages. Closing this issue as fixed, please feel free to reach back to us or re-open this issue in case of any queries.
