### ISSUE TITLE
.NET Core WebJobs can't be linked with web projects

### ISSUE THREAD

**Issue by MagnusBraathen** [Azure/azure-webjobs-sdk#2706]
From the [docs ](https://docs.microsoft.com/en-us/azure/app-service/webjobs-dotnet-deploy-vs#webjobs-as-net-core-console-apps) ".NET Core WebJobs can't be linked with web projects."
Why not? 

We got dozens of webjobs. We need them to run on the same webapp. 

Why is it not supported on .net core? 

Not in .net 5?

.net 4 is slowly being deprecated. We need to port. We can't port without being able to run our webjob processes.

And no we're not gonna run them as dozens of standalone webapps! We're paying for one webapp, we should be able to run whatever we want on it and pool the resource usage. That's the whole point of the cloud in the first place!

**Comment by v-anvari** [comment]
Hi @MagnusBraathen , Thank you for reaching us. We are internally working on this issue.

**Comment by v-anvari** [comment]
Document reference: 
![image](https://user-images.githubusercontent.com/66122429/117457366-c6b1d400-af66-11eb-8283-11bc1a5ff25f.png)

cc: @ggailey777 , Do you know what is addressed as web projects here.

**Comment by v-anvari** [comment]
Closing this issue here , as a doc issue has been raised for clarification
