### ISSUE TITLE
Is it possible to ask you to change the license to MIT in v4.x.x please?

### ISSUE THREAD

**Issue by yuanweilei** [Azure/azure-webjobs-sdk#2716]
Regading Microsoft.Azure.WebJobs.Extensions.Storage, I noticed that from v5.0.0-beta1, you changed the license to MIT. 
Since the latest stable version is still v4.0.4, is it possible that you release a new version (e.g. v4.0.5) which is MIT license?

The license of v4.0.4 is:
https://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_ENU.htm

**Comment by v-anvari** [comment]
Hi @yuanweilei , Thank you for your feedback! We will investigate and update as appropriate.

**Comment by v-anvari** [comment]
Hi @yuanweilei , The license used in 4.x.x is MIT license. You may have to update the packages with the license information if they are not updated. https://github.com/Azure/azure-webjobs-sdk/blob/dev/LICENSE.txt. 

The project might not be updated to use the license for now, we will use this issue to track the update

**Comment by yuanweilei** [comment]
Hi @v-anvari , thank you for checking!

I am not sure if I can ask this question here, but even I used the latest v4.0.4 Nuget, it still shows this license: 
https://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_ENU.htm

Our legal team check the www.nuget.org and they worry that the license is not MIT.
Can I see you answer above (The license used in 4.x.x is MIT license) as an "official answer" before you updated the license documents? 

![image](https://user-images.githubusercontent.com/26296423/119419968-4a750a00-bd36-11eb-8943-17bc8e5493f7.png)

![image](https://user-images.githubusercontent.com/26296423/119420080-97f17700-bd36-11eb-8814-c1516369d971.png)

**Comment by v-anvari** [comment]
@yuanweilei , Apologies for the confusion if caused any, I have confirmed the above with the team before updating it here. As commented above, this issue will be used to track the required changes that are to be made in the packages. But, the 4.x.x  project shares the MIT license. So you can update the license details for now. 

https://stackoverflow.com/questions/57682160/upload-nuget-package-how-to-set-the-license
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg

Triaging the issue as the link in packages need to be updated to reflect the MIT license

Edit: I have mailed the package owners to validate this issue

**Comment by v-anvari** [comment]
Tagging @davidmatson / @mathewc for further inputs

**Comment by yuanweilei** [comment]
Hi, @kashimiz 
Thank you for fixing this!

Could you please tell me when you plan to release this?
