### ISSUE TITLE
Suggestion to improve code and performance 2 (like #2689)

### ISSUE THREAD

**Issue by Shazhko-Artem** [Azure/azure-webjobs-sdk#2717]
I found two more places that have similar situations as in task #2689. In the [TriggerAdapterBindingProvider](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/TriggerAdapterBindingProvider.cs) and [BindToStreamBindingProvider](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/BindToStreamBindingProvider.cs) classes, we can get rid of the reflection to create instances of the `ExactBinding` and `StreamBinding` classes, respectively.

The solution is exactly the same as for the [#2689](https://github.com/Azure/azure-webjobs-sdk/issues/2689). Do you mind if I make a PR for this case?

**Comment by Shazhko-Artem** [comment]
Also in the file [BindToStreamBindingProvider.cs](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingProviders/BindToStreamBindingProvider.cs) on line 308 (after creating the variable), an extra curly brace is opened, it can also be removed.

**Comment by v-anvari** [comment]
Hi @Shazhko-Artem , Thank you for your feedback, you can create a PR. I shall follow up with the team to validate the scenario.
