### ISSUE TITLE
deploy an azure web job via arm template and ev2?

### ISSUE THREAD

**Issue by Liphi** [Azure/azure-webjobs-sdk#2718]
Hi, i don't know if below post has enough authority, or there's any update since last year. Today, is it supported to deploy an azure web job via arm template and ev2 (https://ev2docs.azure.net) ?

https://stackoverflow.com/questions/62633653/how-to-create-azure-webjob-using-azure-arm-template

**Comment by v-bbalaiagar** [comment]
Hi @Liphi , Thank you for reaching out to us, checking internally on this issue. We will update you with any information found.

**Comment by Liphi** [comment]
thanks. i've got response from the team. Solution is documented here: https://github.com/projectkudu/kudu/wiki/WebJobs

**Comment by v-bbalaiagar** [comment]
@Liphi ,Thank you for the update.
