### ISSUE TITLE
null logging entry when using SEQ

### ISSUE THREAD

**Issue by BeChaRem** [Azure/azure-webjobs-sdk#2722]
When using an azure function with Seq.Extensions.Logging, some logging done by Host.Aggregator or Host.Results doesn't contain any message.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new empty azure function project with an empty http trigger.
2. Install Seq.Extensions.Logging
3. Configure SEQ in startup.cs
 ```csharp
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddLogging(logging => logging.AddSeq("http://localhost:5341/"));
        }
    }
```
4. Trigger a function so that `Host.Results` can log a result.

#### Expected behavior

All logging in SEQ from azure function sdk should contains message.
![image](https://user-images.githubusercontent.com/60513607/119676448-dad14e80-be0b-11eb-8b94-c1ba4c29edea.png)

#### Actual behavior

Some entry by Host.Results and Host.Aggregator are logged with `null` as message
![image](https://user-images.githubusercontent.com/60513607/119674036-de63d600-be09-11eb-90c3-108561a80a4d.png)
![image](https://user-images.githubusercontent.com/60513607/119674141-f3d90000-be09-11eb-84bd-d10797304f17.png)

#### Known workarounds

Supress Host.Results and Host.Aggregator logging to prevent null entry.

#### Related information 

Provide any related information 

If I understood the problem correctly, some logging are done without an EventId which cause logging without a message
* https://github.com/Azure/azure-webjobs-sdk/blob/804820cdce76b12f2e36ac12eb632beceba3e7da/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs#L59

**Comment by v-bbalaiagar** [comment]
Hi @BeCharem, Thank you for reaching out to us, Checking this internally for the possibilities. We will update you with any information found.

**Comment by BeChaRem** [comment]
To give more context, I added the namespace and took another screenshot of the SEQ output.

![image](https://user-images.githubusercontent.com/60513607/121398829-c5881400-c923-11eb-896e-df70b03fffe6.png)

**Comment by Lenkelheit** [comment]
Hi @v-bbalaiagar. Do you have any updates about it?

**Comment by BeChaRem** [comment]
Hi, the issue progressed. Thanks to this PR #3005. However, it seems like there's a conflict on the name.

In `Host.Aggregator`, the constant have an Ms at the end of the name.

https://github.com/Azure/azure-webjobs-sdk/blob/8960a7294b854b65c2b416b23dfc2fcc80574725/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/LogConstants.cs#L50

However, the string to be formatted doesn't have the Ms at the end.

https://github.com/Azure/azure-webjobs-sdk/blob/8960a7294b854b65c2b416b23dfc2fcc80574725/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/States/FunctionResultAggregateState.cs#L12

So, the variables replacement doesn't occurs for the three variables that end with Ms.
<img width="685" alt="image" src="https://github.com/Azure/azure-webjobs-sdk/assets/60513607/041b14bb-c3db-44ee-bf27-dad9fdea753a">

Edit: `Host.Results` have another issue
The string reference FunctionName
https://github.com/Azure/azure-webjobs-sdk/blob/8960a7294b854b65c2b416b23dfc2fcc80574725/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/States/FunctionResultState.cs#L13

While the key is changed for this value.
https://github.com/Azure/azure-webjobs-sdk/blob/8960a7294b854b65c2b416b23dfc2fcc80574725/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/Constants/ScopeKeys.cs#L19 so the replacement doesn't occur either.

<img width="676" alt="image" src="https://github.com/Azure/azure-webjobs-sdk/assets/60513607/7656e047-4795-445d-85ce-0371421fee32">


Thanks.

**Comment by RohitRanjanMS** [comment]
This is fixed now.
<img width="1339" alt="image" src="https://github.com/Azure/azure-webjobs-sdk/assets/90008725/fdc62ab3-d837-4b68-b230-c003f00c961a">
