### ISSUE TITLE
.Net Core TimerTrigger not firing

### ISSUE THREAD

**Issue by furkanyildiz** [Azure/azure-webjobs-sdk#2724]
I have two time triggered functions to run every minutes but they are not firing. I tested it locally and on Azure but the result is same.

Program.cs:
```
class Program
{
    static async Task Main(string[] args)
    {

      var builder = new HostBuilder()
          .ConfigureServices((hostContext, services) =>
          {
              services.AddTransient<MyTimerJobs>();
          })
          .ConfigureWebJobs(b =>
          {
              b.AddAzureStorageCoreServices();
              b.AddTimers();
          });

        builder.UseEnvironment(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"));
        
        var host = builder.Build();
        using (host)
        {
            await host.RunAsync();
        }
    }
}

```

MyTimerJobs.cs
```
public class MyTimerJobs
{
    public async Task Func([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo timer)
    {
        Console.WriteLine($"{DateTime.UtcNow} Func function started.");
    }

    public async Task Func2([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo timer)
    {
        Console.WriteLine($"{DateTime.UtcNow} Func2 function started.");
    }
}
```

#### Expected behavior

`Func` and `Func2` should trigger every minutes.

#### Actual behavior

They are not triggered.

#### Known workarounds

There are 2 workaronds to run these functions.

1) If I rename `Func` as `FuncTest` and `Func2` as `Func2Test`, they are running as expected.
2) If I rename `MyTimerJobs` as `Functions`, they are running as expected.

#### Packages

* .NetCore 3.1
* Microsoft.Azure.WebJobs.Extensions 4.0.1
* Microsoft.Extensions.Hosting 5.0.0

**Comment by v-bbalaiagar** [comment]
Hi @furkanyildiz, Thank you for your feedback! Shall try to reproduce this scenario and update you with findings.

**Comment by v-bbalaiagar** [comment]
Hi @mathewc, Could you please look into this issue.

**Comment by mathewc** [comment]
I'm unable to repro this. Using the code above, I see the functions are triggered correctly once per minute. @v-bbalaiagar are you able to repro this?

One thing I notice above is that your functions aren't correctly async - they don't return tasks. So you should fix that for things to work properly. However even using your code, I see the functions being triggered.

**Comment by v-bbalaiagar** [comment]
Hi @mathewc, Thank you for looking into this issue. I tried to repro this issue.

Below are my findings :

MyTimerJobs.cs:
        
  ```
  public class MyTimerJobs
    {
       
        public async Task Func([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo timer)
        {
            Console.WriteLine($"{DateTime.UtcNow} Func function started.");
        }
        
        public async Task Func2([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo timer)
        {
            Console.WriteLine($"{DateTime.UtcNow} Func2 function started.");
        }
    }
```
               


Program.cs:

       class Program
        {
           static async Task Main(string[] args)
            {

         var builder = new HostBuilder()
          .ConfigureServices((hostContext, services) =>
          {
              services.AddTransient<MyTimerJobs>();
          })
          .ConfigureWebJobs(b =>
          {
              b.AddAzureStorageCoreServices();
              b.AddTimers();
          });

        builder.UseEnvironment(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"));
        
        var host = builder.Build();
        using (host)
            {
            await host.RunAsync();
             }
           }
         }

output:

![image](https://user-images.githubusercontent.com/74654421/121183024-42ae7d00-c881-11eb-9037-7376b0b6a5d6.png)

If I rename Func as FuncTest ,Func2 as Func2Test and MyTimerJobs as Functions, they are not running as expected. 

If I change the code to below, they are working as expected.

          public class Functions
            {
             [FunctionName("Function1")]
              public async Task Func([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo timer)
                 {
                     Console.WriteLine($"{DateTime.UtcNow} Func function started.");
                  }
              [FunctionName("function2")]
              public async Task Func2([TimerTrigger("0 * * * * *", RunOnStartup = true)] TimerInfo timer)
                 {
                  Console.WriteLine($"{DateTime.UtcNow} Func2 function started.");
                  }
             }

 Output:

![image](https://user-images.githubusercontent.com/74654421/121188167-77710300-c886-11eb-992b-83ec8c989a80.png)

**Comment by mathewc** [comment]
@v-bbalaiagar The customer isn't using Azure Functions, this is a WebJobs SDK app. Looks like you're running this via Functions core tools?

Anyhow, I'm unable to repro this.  @furkanyildiz - please share the console output from your repro, ensuring that you've enabled console logging, and set the level to Debug as follows:

```csharp
using Microsoft.Extensions.Logging;

...

var builder = new HostBuilder()
    .UseEnvironment("Development")
    .ConfigureServices((hostContext, services) =>
    {
        services.AddTransient<Functions>();
    })
    .ConfigureLogging((context, b) =>
    {
        b.SetMinimumLevel(LogLevel.Debug);
        b.AddConsole();
    })
    .ConfigureWebJobs(b =>
    {
        b.AddAzureStorageCoreServices();
        b.AddTimers();
    });
```

The issue might be that you're sharing the storage account with another running instance of this app, and that instance has the singleton lock meaning your local instance won't run. You can verify if this is the case by ensuring that you see your local instance acquiring the locks:

```
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
info: Host.Startup[0]
      Found the following functions:
      WebJobsSDKTest.Functions.Func
      WebJobsSDKTest.Functions.Func2

dbug: Host.Singleton[0]
      Singleton lock acquired (f08047b6dde564daff9ff21dacdac377/WebJobsSDKTest.Functions.Func2.Listener)
dbug: Host.Singleton[0]
      Singleton lock acquired (f08047b6dde564daff9ff21dacdac377/WebJobsSDKTest.Functions.Func.Listener)
```

A timer only runs if the instance has the lock ("Singleton lock acquired"). If this is what you're experiencing, it explains why renaming the function causes it to run, since that works around the lock contention.

**Comment by keremkambur** [comment]
https://stackoverflow.com/a/66479106/7273196 please check this life-saver comment, `UseHostId` is your keyword @furkanyildiz.

I had the same problem after upgrading to v3.

**Comment by v-bbalaiagar** [comment]
Hi @furkanyildiz, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by keremkambur** [comment]
Like most of the eastern developers, of course no feedback left if the issue is solved or not xD
