### ISSUE TITLE
how to remove redundancy of schedule configuration for timer-triggered azure web job?

### ISSUE THREAD

**Issue by Liphi** [Azure/azure-webjobs-sdk#2725]
Hi, My timer-triggered azure web job is written with c# web job v3 SDK, and I use TimerTrigger attribute to decorate my timer callback. Problem is, this attribute has to take a schedule parameter in cron or scheduleType format, so i have to duplicate this schedule in both settings.job and TimerTrigger decorator. Is there any mechanism for my c# code to get the schedule from settings.job, so that in my code base i only need to define this schedule in 1 place (settings.job) ?
One work-around I can think of is to maybe define this web job as a continuous job, so that i don't need to config schedule on settings.job, and i only need to hard-code the schedule in c# code. But I feel it's not ideal.

    // timer callback
    public static async Task TimerCallback([TimerTrigger("0 0 */1 * * *")] TimerInfo timerInfo)
    {
        // business logic
    }
Any suggestion would be helpful. Thanks!

**Comment by v-anvari** [comment]
Hi @Liphi , Thank you for your feedback! Checking this internally for any other workarounds

**Comment by v-anvari** [comment]
Tagging @mathewc , to validate this request. Request to provide any related documentation or information regarding this scenario

**Comment by mathewc** [comment]
Correct - you're incorrectly mixing two different cron timer patterns here. If you're wanting to use the WebJobs SDK TimerTrigger, then your WebJob should be a Continuous WebJob with no settings.job schedule defined. WebJobs SDK should only be used in Continuous WebJobs. Going this route note that you don't have to hardcode the cron expression - you can define an app setting in your WebApp named whatever you want to provide the schedule (e.g. "MySchedule") then reference that setting in your attribute `[TimerTrigger("%MySchedule%")]`. The schedule will then be pulled from the referenced app setting.

Alternatively, if you don't want to use the WebJobs SDK/TimerTrigger, then you'd remove the TimerTrigger function and WebJobs SDK usage, and just define your job as a triggered WebJob following instructions https://github.com/projectkudu/kudu/wiki/WebJobs#scheduling-a-triggered-webjob. Then on schedule, your WebJob will be invoked.

**Comment by Liphi** [comment]
Thanks. it works.
