### ISSUE TITLE
Run blob trigger only on new event

### ISSUE THREAD

**Issue by rdenisi** [Azure/azure-webjobs-sdk#2732]
Please provide a succinct description of the issue.

When I create for example, an azure function listening on the blob with a trigger in a specific path, all the files present are processed, while I would like to be able to specify not to process them (and immediately mark them as already processed).

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a blob storage account and a container
2. Upload one or more files into the container
3. Create an azure function with a trigger on that container

#### Expected behavior

I would like to be able to configure the function to process only new events; in this case, starting the function would not process the files already present.

#### Actual behavior

When I execute the function the trigger is also triggered on the files already present at the time of the function start.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by v-bbalaiagar** [comment]
Hi @rdenisi, Thank you for reaching out to us, We shall try to reproduce this scenario and update you with findings.

**Comment by v-bbalaiagar** [comment]
Hi @rdenisi, I reproduced this issue with uploading blobs before creating a function and it is not getting read. Can you try to delete all the existing blobs and try again, restart the function app and try again.
