### ISSUE TITLE
No parallel execution for service bus triggers

### ISSUE THREAD

**Issue by victorhurdugaci** [Azure/azure-webjobs-sdk#275]

**Comment by HansOlavS** [comment]
Wow, this has been in the backlog since Sep 2014.

**Comment by HansOlavS** [comment]
I've made a PR with a proposed fix for this issue at #533.

**Comment by mathewc** [comment]
Related SO post here: http://stackoverflow.com/questions/31731733/intercept-azure-webjobs-queue-service-bus-triggers

This user needs to intercept all SB messages and run custom code BEFORE his job function gets called.

**Comment by BrianVallelunga** [comment]
I'm the one who wrote the SO post. Specifically, I have a Tenant custom property set on my messages and want to be able to set Tenant-specific context data before the job is run. Ideally, I'd have access to this custom data from within my custom IJobActivator so I could inject tenant-specific services into my jobs. The job itself would then never need to know which tenant it was processing. That would all be moved down to the infrastructure level.

**Comment by mathewc** [comment]
Guys, I've created an initial PR for this here: https://github.com/Azure/azure-webjobs-sdk/pull/558. @HansOlavS @BrianVallelunga please take a look and verify this will meet your needs. The E2E tests include an example of how custom processors can be specified [see this test](https://github.com/Azure/azure-webjobs-sdk/blob/sbconfig/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/ServiceBusEndToEndTests.cs#L99).

@HansOlavS This PR incorporates your PR #533 :) As I mentioned previously, we needed to also enable deeper customization, so I'm doing both here.

**Comment by HansOlavS** [comment]
Looks great!

But I do feel that going concurrent is a pretty big breaking change. Isn't it better to opt-in and explicitly set the concurrency level yourself? Is there a default concurrency level on Azure Queues as well?

I feel the two should have the same default setup as far as possible...

**Comment by mathewc** [comment]
Yes, I'm thinking you're right about the concurrency. I'll probably leave it at the existing default - at least we've opened it up now for people.

**Comment by HansOlavS** [comment]
Another thing I've been thinking of: Wouldn't it be cool to adjust the concurrency-level per queue/method?
```c#
[ServiceBusTrigger("", OnMessageOptions = new OnMessageOptions()]
```

or just
```c#
[ServiceBusTrigger("", MaxConcurrentCalls = 5)]
```

I'd love to have those...

**Comment by mathewc** [comment]
Well, you can already per queue with these changes - in your custom MessageProcessorFactory you can define the options per queue.

**Comment by HansOlavS** [comment]
Yeah, I should probably look more closely into the MessageProcessorFactory before I suggest anything more.

**Comment by HansOlavS** [comment]
I just love the easiness of declarative attributes. So easy and elegant.

**Comment by mathewc** [comment]
Yes - definitely if this is something people end up needing to configure often per queue, then declarative would be the way to go. I'm just not convinced that it is that mainline of a scenario.

**Comment by HansOlavS** [comment]
True dat!

**Comment by mathewc** [comment]
Changes have been merged.

**Comment by mathewc** [comment]
Nightly build: 1.1.0-alpha1-10061 contains these changes.

**Comment by BrianVallelunga** [comment]
I think these changes will work for me. I believe I'll create custom MessageProcessor and performing my logic in the overridden methods. I'll give it a try.

**Comment by mathewc** [comment]
@BrianVallelunga Thanks Brian - let me know how it goes, and if the interfaces need any changes.

**Comment by BrianVallelunga** [comment]
I was unable to look into this at the time, but am trying out the feature now. I've implemented my MessagingProvider and MessageProcessor. In `BeginProcessingMessageAsync` I can inspect the message properties, log the message, etc, but not much else. It doesn't appear that I can set any sort of context for downstream use. It would be ideal if I could create a context/unit of work for the message that would survive the duration of the processing and be available to the JobActivator and triggered function.

Without built-in support, I believe I could accomplish this by creating my own context object and storing it in thread-local storage. Does this seem a safe way to proceed?

**Comment by mathewc** [comment]
You can do a lot more than inspect/log - you can completely take over the processing of the message. To set message specific properties I recommend adding them to `BrokeredMessage.Properties`. These will flow for downstream use in your job functions. Not sure about being available to JobActivator - what is the scenario there? I don't think the JobActivator should know anything about specific messages being processed. It's job is only to create class instances. I think you should put the logic you're talking about in your MessageProcessor.

**Comment by BrianVallelunga** [comment]
The Properties would work well. The reason I mention JobActivator is that my jobs might need to be injected with a database connection or a logger, etc. I'd like each of these to be scoped to a specific tenant, which I get from inspecting the BrokeredMessage metadata.

I've accomplished this in the past (using systems such as NServiceBus) in the following way:

Assume a job with a constructor of `MyJob(IDatabase database, ILogger logger)`

1. Message arrives. Using a container like Unity, I'd create a child container scoped to the message that has configuration specific to the tenant.
2. Job is instantiated by the child container, with injected arguments specific to that tenant.
3. Job executes, unaware of the context it's working in. It just has a database connection and a logger.
4. Everything gets cleaned up, including the child container.

Now of course I can (and currently do) manage the tenant-specific work inside of my job. I can certainly make the constructor `MyJob(IDatabaseFactory databaseFactory, ILoggerFactory loggerFactory)` but I prefer to push that to the infrastructure and let the job just focus on its core function.

**Comment by BrianVallelunga** [comment]
Following-up on my last post, the context being available in the JobActivator is useful for non-tenant specific features as well. I briefly mentioned logging, but thought I should explain more.

I'm using Serilog for my logging, which allows logging of structured data. Part of that structured data can be extra contextual information that gets logged.

For example, I have a class called LogEnricher that takes a BrokeredMessage and adds contextual data to a logger instance. The code looks like:

    public class LogEnricher : ILogEventEnricher
    {
        private readonly BrokeredMessage message;

        public LogEnricher(BrokeredMessage message)
        {
            this.message = message;
        }

        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty("MessageId", this.message.MessageId));
            logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty("Tenant", this.message.Properties["Tenant"]));
            logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty("MessageType", this.message.Properties["MessageType"]));
        }
    }

Adding this enricher to a logger instance appends all of the metadata to every call made by that logger instance. Thus `logger.Information("Hello World")` actually contains not only the string, but also the MessageId, Tenant, and MessageType.

**Comment by babyplanner** [comment]
How am I supposed to get parallel processing of queue messages through use of [ServiceBusTrigger]? 

I'm using RTM 1.1.1 and have elaborated with both MaxConcurrentCalls for OnMessageOptions and PrefetchCount on ServiceBusConfiguration but I just cannot seem to get [ServiceBusTrigger] to process more than one message at a time.

If I remove .UseServiceBus(ServiceBusConfiguration) and instead just manually hookup my ProcessQueueMessage-method using QueueClient.OnMessageAsync it works just fine.

Any ideas what might be wrong? It's worth noting that I'm using a custom MessageProcessor but all it does is handling IOC.

**Comment by mathewc** [comment]
You don't have to do anything to get parallel execution - it will happen out of the box. The default value value we configure for OnMessageOptions.MaxConcurrentCalls is 16 ([code here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusConfiguration.cs#L26)).

Recommend trying a simplified example to prove to yourself there is concurrency, then add back your custom message processor to see where things might be getting configured wrong. Or, if you have a simple repro solution in a public repo somewhere I could take a look. Or you could share your function definition and custom processor code for starters.
