### ISSUE TITLE
[Service Bus] [Design flaw?] - Replay message from subscriber's DLQ only to same subscriber rather than topic

### ISSUE THREAD

**Issue by Camios** [Azure/azure-webjobs-sdk#2751]
When a message is sent to a service bus topic it is sent to all of the topic's subscribers. There is a 1:* relationship between topic and subscribers.
I assume each subscriber has their own incoming message queue/box - a 1:1 relationship.
If a subscriber fails to process the message it can end up on the subscriber's specific dead letter queue (DLQ). There is a 1:1 relationship between the subscriber and their DLQ.

Yet when when you want to replay a message from a subscriber-specific DLQ, why does it have to be sent to the topic and distributed to all subscribers. The DLQ is subscriber-specific and the failure could very well be subscriber-specific, so why (wastefully) send to all the other subscribers? 
Why isn't there an ability to send from a subscriber's DLQ directly to the subscriber's incoming message box/queue? 
This request is seeking for this functionality to be implemented.

If there is a reason it cannot be implemented, is there a alternative (eg pattern)?

**Comment by v-bbalaiagar** [comment]
Hi @Camios, Thank you for reaching out to us, Can you please open the issue in service bus repo as this would be a service bus specific question.

Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
