### ISSUE TITLE
Need to read ExponentialBackoffRetry settings from unction App Configuration(local.settings.json)

### ISSUE THREAD

**Issue by TJSagar** [Azure/azure-webjobs-sdk#2752]
I have implemented Retry Mechanism in Azure Function using attribute **ExponentialBackoffRetry**

        [FunctionName("TestFunction")]
        [ExponentialBackoffRetry(5, "00:02:00", "00:05:00")]

However now we want to move **ExponentialBackoffRetry** parameter values to Function App configuration(local.settings.json).
As there are multiple Functions in FunctionAPP we are not able to use Host.Json

What we need is something like below 
[ExponentialBackoffRetry("%maxRetryAttempts%", "%minInterval%", "%maxInterval%")]

Provide any related information 

* Package version 3.0.27
* Links to source

**Comment by v-anvari** [comment]
Hi @TJSagar , The two ways of configuring the retry policy is [App level config](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#retry) and [function level config](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#function-level-configuration). Retry cannot be included in the application settings or local.settings.json. They need to be specified in code or host.json. There is only one host.json file for a single function App with multiple functions.

Here is a sample host.json file - https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#sample-hostjson-file

Here is an App settings reference for you - https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings

**Comment by TJSagar** [comment]
Thank you for the reply, is there any plan to add Retry Policy Configurable at Function level and not at Function App level, may be next releases?

**Comment by v-anvari** [comment]
Hi @TJSagar , As mentioned in the comment earlier, you can add the configuration in function level - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#function-level-configuration

**Comment by LuMeff** [comment]
Hi, I am facing the same issue in the moment. We need to have different retry policies for different stages of the application. Having it only hard coded in the function.json won't work in our case.
Is there a work around for this?
We are using the latest azure functions with python.

**Comment by Aleksey-Kudryavtsev** [comment]
@v-anvari , @pragnagopa , Could you share the specific setting names for configuring the re-tries in host.json? I cannot find anything in the documentation at https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json#sample-hostjson-file.

In particular is it possible for the Timer trigger to have it configured in host.json?
