### ISSUE TITLE
MSI for web job storage accounts

### ISSUE THREAD

**Issue by sdandu21** [Azure/azure-webjobs-sdk#2760]
Is it possible to use MSI token credentials to authenticate web job storage accounts instead of a connection strings?

**Comment by v-bbalaiagar** [comment]
Hi @sdandu21, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @sdandu21, I checked this internally. Team was working on an official version of this but it was not published yet.
Specifically for the we jobs storage part, this is the current relevant doc section -
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connecting-to-host-storage-with-an-identity
