### ISSUE TITLE
NU1100: Unable to resolve 'Microsoft.NET.Sdk.Functions (>= 3.0.13)' for '.NETCoreApp,Version=v3.1'

### ISSUE THREAD

**Issue by dpapkin** [Azure/azure-webjobs-sdk#2762]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1.  https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs-code?tabs=csharp
In the **Install binding extensions** section 

After I type 
dotnet add package Microsoft.Azure.WebJobs.Extensions.Storage --version 3.0.4

I get alot of errors

CreateAzureFunctionDemopg64.csproj...    
error: NU1100: Unable to resolve 'Microsoft.NET.Sdk.Functions (>= 3.0.13)' for '.NETCoreApp,Version=v3.1'.
error: NU1100: Unable to resolve 'Microsoft.Azure.WebJobs.Extensions.Storage (>= 3.0.4)' for '.NETCoreApp,Version=v3.1'.
error: Package 'Microsoft.Azure.WebJobs.Extensions.Storage' is incompatible with 'all' frameworks in project 'C:\Users\davidpapkin\OneDrive - tsiconsultingservices.com\Documents\training\Courses\Microsoft\az-204\visualstudiocodepractice\CreateAzureFunctionDemopg64\CreateAzureFunctionDemopg64.csproj'.

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version
* Links to source

**Comment by v-bbalaiagar** [comment]
Hi @dpapkin, Thank you for your feedback! We will reproduce this issue and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @dpapkin, I am able to reproduce the issue. I am able to add `add dotnet add package Microsoft.Azure.WebJobs.Extensions.Storage --version 3.0.4 ` as expected.

![image](https://user-images.githubusercontent.com/74654421/134154374-22e34c42-cd26-4260-a483-9aab8e03fb39.png)

Let us know if you are still facing the same issue.
