### ISSUE TITLE
Blob Trigger Stream Timeout and Operation was Canceled

### ISSUE THREAD

**Issue by acranefei** [Azure/azure-webjobs-sdk#2770]
When processing (XML) many blobs of various sizes (50MB to 1G), I receive the following exception. It seems that the stream on the blob trigger times out when trying to parse the files. I was able to lessen these errors by adjusting the batch size down to 1, but they still come up every so often. Originally I thought the file sized matter so I reprocessed one of the largest files one at a time an no issues.

"Message": "The operation was canceled.",
"StackTrace": "   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)\r\n   at Microsoft.Azure.Storage.Blob.BlobReadStream.DispatchReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Storage.Blob.BlobReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at Microsoft.Azure.WebJobs.Host.Blobs.WatchableReadStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Extensions.Storage\\Blobs\\WatchableReadStream.cs:line 78\r\n   at System.Xml.XmlTextReaderImpl.ReadData()\r\n   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)\r\n   at System.Xml.XmlTextReaderImpl.ReadContentAsBinary(Byte[] buffer, Int32 index, Int32 count)\r\n   at System.Xml.XmlTextReaderImpl.ReadElementContentAsBinary(Byte[] buffer, Int32 index, Int32 count)\r\n   at System.Xml.XmlTextReaderImpl.ReadElementContentAsBase64(Byte[] buffer, Int32 index, Int32 count)\r\n   at ProductAssetProcessorIPFunction.services.implementation.ProductFileStreamParser.Parse(String fileName, Stream fileContent) in 
      
#### Repro steps

Provide the steps required to reproduce the problem

1. Copy ~1800 XML files to blob storage

2. Function triggers on new files

3. Error occurs above, out of ~1800 files the timeout occurs less than 10 times

#### Expected behavior

All files are processed successfully

#### Actual behavior

Timeout errors on stream parameter of function app 

#### Known workarounds

No workarounds, but setting batch size to 1 has helped many of the errors

#### Related information 

Provide any related information 

* Package version: 4.0.5
* Links to source

**Comment by v-anvari** [comment]
Hi @acranefei , Can you provide us the function invocation id, time stamp and region in which the App is running. This will help us go through the logs. 

Also, which plan are you currently using in your App

**Comment by acranefei** [comment]
> Hi @acranefei , Can you provide us the function invocation id, time stamp and region in which the App is running. This will help us go through the logs.
> 
> Also, which plan are you currently using in your App

@v-anvari 
Invocation id: c0f88d07-e188-4e7d-ada9-41ede8a82141
Timestamp (UTC): 10/5/2021 6:35:34 PM
ASP: P2V3
Region: EastUS2

**Comment by v-anvari** [comment]
Hi @acranefei , Apologies for the delay, Somehow missed the reply. Here is a quick analysis done through the logs. 
I do see that at times the files are not processing and causing the host to shutdown not so gracefully. This is impacting other requests as well. I see the error `Singleton lock renewal failed for blob`- this can be mitigated by troubleshooting the cause as mentioned here - https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#troubleshooting

There is also high memory utilization, this can be analyzed by taking a memory dump. Here is how you can capture a memory dump - http://jsandersblog.azurewebsites.net/2017/02/02/how-to-get-a-full-memory-dump-in-azure-app-services/
