### ISSUE TITLE
What is the best approach to delete/move a blob from a BlobTrigger?

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-webjobs-sdk#2778]
Hi,

I'm creating an azure function that has a BlobTrigger and this function can output in two other places: success-container or fail-container.

Something like:
start-container -> copying file to success-container or fail-container.

Since I don't want to have the same file in two different containers, I would like to either move or delete the initial blob.

What is the best approach for this design?

thank you!

**Comment by mathewc** [comment]
If you have a .NET function, you can do something like the following, using the Azure Storage blob APIs to perform the operations:

```csharp
public async Task BlobTrigger(
            [BlobTrigger("test/{name}")] CloudBlockBlob blob,
            string name,
            [Blob("test-success")] CloudBlobContainer successContainer,
            [Blob("test-failure")] CloudBlobContainer failureContainer,
            CancellationToken cancellationToken)
{
    bool success = false;
    CloudBlobContainer targetContainer = success ? successContainer : failureContainer;

    CloudBlockBlob copy = targetContainer.GetBlockBlobReference(name);
    await copy.StartCopyAsync(blob, cancellationToken);

    await blob.DeleteAsync(cancellationToken);
}
```

There's likely other ways you can accomplish this as well.

**Comment by eddynaka** [comment]
Hi @mathewc ,

when to choose CloudBlockBlob vs Stream in the arguments? Do we have a benefit from using the CloudBlockBlob?

**Comment by mathewc** [comment]
You could use either. The StartCopyAsync method takes a CloudBlockBlob, which is why I used it above.
