### ISSUE TITLE
Dependencies not logged for Microsoft.Azure.WebJobs.Logging.ApplicationInsights newer than 2.0.25

### ISSUE THREAD

**Issue by ben-002** [Azure/azure-webjobs-sdk#2781]
Please provide a succinct description of the issue.

We have a .NET Core 3.1 azure service bus triggered function and we are using the Microsoft.Azure.WebJobs.Logging.ApplicationInsights package. 
Versions newer than 3.0.25 don't log dependencies anymore. For example outgoing dependencies for service bus. 
Are there some extra settings that needs to be done starting with 3.0.27?

#### Expected behavior

Dependencies logs should be collected.

#### Actual behavior

Dependencies logs are not collected, or at least, they are no more visible in Azure portal, Application Insights.

#### Known workarounds

Revert Microsoft.Azure.WebJobs.Logging.ApplicationInsights to Version 3.0.25

#### Related information 

Provide any related information 

* Package version
Microsoft.Azure.WebJobs.Logging.ApplicationInsights

**Comment by v-anvari** [comment]
Hi @ben-002 ,Can we know more about the configuration. Is there anything that changed in your code during this period. How are you tracking these dependencies. Can we have a code snippet
