### ISSUE TITLE
Storage account connection string for 'AzureWebJobsStorage' is invalid

### ISSUE THREAD

**Issue by aggieben** [Azure/azure-webjobs-sdk#2783]
Copied from https://github.com/Azure/azure-functions-dotnet-worker/issues/706; seems this issue actually belongs here.

I have a simple F♯ worker function:

```
[<Function("Index")>]
let run ([<HttpTrigger(AuthorizationLevel.Function, "get", Route = "")>]req: HttpRequestData)
        (executionContext:FunctionContext)
        ([<BlobInput("sabine-content")>] containerClient:BlobContainerClient)
        =
    async {
        let log = executionContext.GetLogger("Index")
        log.LogInformation("F# HTTP trigger function processed a request.")

        let responseMessage =  "This HTTP triggered function executed successfully."

        let resp = req.CreateResponse(HttpStatusCode.OK);
        do! resp.WriteStringAsync(responseMessage) |> Async.AwaitTask

        return resp
    } |> Async.StartAsTask
```

However, when I run it in the debugger or with `func start`,  any request fails like this (essential error message is in the title):

```
For detailed output, run func with --verbose flag.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://127.0.0.1:1745/AzureFunctionsRpcMessages.FunctionRpc/EventStream application/grpc -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /AzureFunctionsRpcMessages.FunctionRpc/EventStream'
[2021-11-09T14:55:25.706Z] Worker process started and initialized.
[2021-11-09T14:55:30.432Z] Host lock lease acquired by instance ID '000000000000000000000000449BC4F9'.
[2021-11-09T14:55:35.943Z] Executing 'Functions.Index' (Reason='This function was programmatically called via the host APIs.', Id=8e0b2761-3730-44de-b1a1-f3bcc74d9d6b)
[2021-11-09T14:55:36.037Z] Executed 'Functions.Index' (Failed, Id=8e0b2761-3730-44de-b1a1-f3bcc74d9d6b, Duration=114ms)
[2021-11-09T14:55:36.038Z] System.Private.CoreLib: Exception while executing function: Functions.Index. Microsoft.Azure.WebJobs.Host: Storage account connection string for 'AzureWebJobsStorage' is invalid.
```

I'm trying to connect to the local storage emulator, so my `local.settings.json` is as follows:
```
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=True",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
    }
}
```

I also confirmed that this file is copied into the `output` folder.

Something similar happens in VS Code, the only difference being that it shows me this error dialog almost right away:
![image](https://user-images.githubusercontent.com/1321/141147366-8b79a2e9-aaab-4fe7-89ef-87aa034d2a21.png)

I'm at a bit of a loss as to why this is failing.  

*Update*: I did find this [explanation that the Azure Storage Emulator is deprecated](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator).  I stopped the legacy emulator, installed and started Azurite instead, and the result is the same - it still says the connection can't be validated.

**Comment by v-anvari** [comment]
Can you confirm if the former was in visual studio. Can you also tell us the repro steps and how are you adding the json file

**Comment by aggieben** [comment]
@v-anvari Of course.  Here are the steps I followed.

1. Create new function with `func new --language F♯ -t HttpTrigger`, select `dotnet-isolated` when prompted, provide function name when prompted.
2. The output of that command incorrectly creates a C♯ project, so I manually edit it into an F♯ project, using https://github.com/Azure/azure-functions-templates/issues/1096 and https://github.com/landy/azurefunctions-isolated-example as guides.
3. At this point, the project works as expected.
4. Then, in an attempt to use a Blob input binding, I added the `([<BlobInput("sabine-content")>] containerClient:BlobContainerClient)` parameter to my `run` function.  This required adding a couple of nuget packages: `Azure.Storage.Blobs` 12.10.0, and `Microsoft.Azure.Functions.Worker.Extensions.Storage` 4.0.4.

The errors I experienced were consistent between Visual Studio 2022 and VS Code / `func start` (although VS Code did seem to surface the error earlier as shown in the error dialog screenshot I included in the issue).

The `local.settings.json` file was created for me by the templated used by `func new`.  I never modified or otherwise worked with that file.  I did have to edit the .fsproj to use `Include` instead of `Update` in the Item element, as explained in https://github.com/Azure/azure-functions-templates/issues/1096.

**Comment by aggieben** [comment]
@v-anvari well, I may have accidentally discovered the issue.  I was going back through my steps to reproduce the issue, and was even setting up an example repository for you with commits organized by the steps outlined above, and I discovered that my minimal repro was actually not a repro.  It turns out that the `AzureWebJobsStorage` setting will be considered invalid if the connection string uses a capital 'T' in the value for "true".  i.e., this is valid: `"AzureWebJobsStorage": "UseDevelopmentStorage=true"`, but this is not: `"AzureWebJobsStorage": "UseDevelopmentStorage=True"`.

**Comment by v-bbalaiagar** [comment]
Hi @aggieben, Let us know if you were able to find a solution ,or if you have any further queries.

**Comment by fabiocav** [comment]
@aggieben looks like the casing adjustment addressed your issue. I agree this is questionable behavior, but we're relying on the storage SDK to parse that information [here](https://github.com/Azure/azure-webjobs-sdk/blob/f3f78bab110503515a08c4440e06c900ca6e3cb4/src/Microsoft.Azure.WebJobs.Extensions.Storage/StorageAccountProvider.cs#L56), so the best course of action would be to open an issue against the SDK if still needed.

**Comment by fabiocav** [comment]
Closing as there will be no further action on this repo, but let us know if you need anything else from us. Thanks!
