### ISSUE TITLE
What is the proper way to instantiate a QueueProcessor instance?

### ISSUE THREAD

**Issue by plamber** [Azure/azure-webjobs-sdk#2810]
Hi there!
I recently upgraded from Azure Functions v3 to Azure Functions v4. During this upgrade, I had to update Microsoft.Azure.WebJobs.Extensions.Storage.Queues assembly to Version 5.0.0.0.

In the previous version, it was possible to implement the interface IQueueProcessorFactory and modify in code the processor options (MaxPolilingInterval, MaxDequeueCount, VisibiltyTimeout). This allowed us to apply different values for each queue based on our business requirements. 

With the latest version of the assembly, the QueueProcessor class became a protected internal class, making it impossible to return a new instance of this object. 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/18241305/146490891-f43d882b-a633-4eac-acd3-f4946953de2a.png">

I haven't seen a way to configure individual values for each queue. Maybe there is a more elegant way to do this.

#### Expected behavior
Allow creating an instance of the QueueProcessor class in other assemblies. Make the constructor public.

#### Actual behavior
It is not possible to instantiate a dedicated instance of QueueProcessor

#### Known workarounds
Not aware of other workarounds. As far as I know, it is only possible to specify a central set of settings for all queues in the host.json.

Thank you for your feedback.

**Comment by v-bbalaiagar** [comment]
Hi @plamber, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by superjulius** [comment]
Hi @v-bbalaiagar, any update on this question?

**Comment by v-bbalaiagar** [comment]
Hi @plamber , Apologies for the delay in response. I checked this internally. This is a limitation so this would be essentially a feature. 
Please open an issue here for further insights  - https://github.com/Azure/azure-sdk-for-net/issues

**Comment by plamber** [comment]
Hi @v-bbalaiagar,
thank you. The issue has been created.

Cheers

**Comment by v-bbalaiagar** [comment]
Closing this issue here, please feel free to reach back to us in case of any further queries related to this issue.
