### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80070057

### ISSUE THREAD

**Issue by Uffman** [Azure/azure-webjobs-sdk#2812]
Upgraded Azure Functions App to .NET6.0 and v4. Since then build fails, using Visual Studio 2022 debug, Any CPU

C:\Users\marko\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): warning : Failed to initialize CoreCLR, HRESULT: 0x80070057

C:\Users\marko\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\4.0.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37,5): error : Metadata generation failed. Exit code: '-2147450743' Error: 'Failed to initialize CoreCLR, HRESULT: 0x80070057'

![image](https://user-images.githubusercontent.com/1281907/147047416-d706f1f6-7301-4446-a23a-8e6d3df51349.png)

**Configuration**
.NET SDK (reflecting any global.json):
Version: 6.0.101
Commit: ef49f6213a

Runtime Environment:
OS Name: Windows
OS Version: 10.0.22000
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
Version: 6.0.1
Commit: 3a25a7f1cc

.NET SDKs installed:
2.1.526 [C:\Program Files\dotnet\sdk]
2.2.110 [C:\Program Files\dotnet\sdk]
2.2.207 [C:\Program Files\dotnet\sdk]
3.1.416 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.300 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]
5.0.404 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by v-bbalaiagar** [comment]
Hi @Uffman, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.
Meanwhile, here is a SO which addresses similar scenario and solutions to resolve it - https://stackoverflow.com/questions/59295465/getting-metadata-generation-failed-when-building-c-sharp-function-app-in-visua

Please check and let us know if this helps.

**Comment by Uffman** [comment]
OK, thank you for the info

**Comment by Uffman** [comment]
Still the same problems as described here:
[https://stackoverflow.com/a/69917702/4058437](https://stackoverflow.com/a/69917702/4058437)

**Comment by v-bbalaiagar** [comment]
Hi @fabiocav , any thoughts on this issue?

**Comment by Uffman** [comment]
The problem also exists if I try to build V3 Azure Functions Project with Visual Studio 2022. I have no issues building with VS 2019

**Comment by v-bbalaiagar** [comment]
Apologies for the delay in response. We would like to know if you are having this issue with a project that has been modified or if the repro with a project that is just using the template out of the box.

**Comment by Uffman** [comment]
The project has been modified. The same problem exists if I create a new Azure Functions project from VS template

**Comment by v-bbalaiagar** [comment]
Hi @fabiocav , Could you please look into this issue.

**Comment by fabiocav** [comment]
@Uffman a couple of questions

- Would you be able to run with verbose MSBuild logs, **sanitize the output**, and share that information?
- Do you have this issue on similar machines? This is looking like an environment issue with a .NET installation
- Is there a global.json potentially at play here?

**Comment by Uffman** [comment]
Here is the build log from the new Azure Function project.
I build the project with these settings:
![image](https://user-images.githubusercontent.com/1281907/153360142-c0055222-101f-415b-875f-c82b0a3c359a.png)

The problem is still the same:
[build_log.txt](https://github.com/Azure/azure-webjobs-sdk/files/8038976/build_log.txt)

**Comment by Uffman** [comment]
Any updates on this?

**Comment by liliankasem** [comment]
@fabiocav @mathewc - is this something you can help with?

**Comment by Uffman** [comment]
I tried to build my project with Azure Function tools and get this error:
![image](https://user-images.githubusercontent.com/1281907/158558164-bdb5113d-a694-41e4-a5cb-cbc96b009bdf.png)
also noticed it says
Core Tool Version: 3.0
Function Runtime Version: 3.0


could this be the problem? My project is on .NET 6.0 and V4 of AZ Function

**Comment by Uffman** [comment]
I tried to build the project on clean VM and it worked. Do you have a tools so I could remove all older .NET installations and try again

**Comment by liliankasem** [comment]
It looks like maybe you had the old core tools version (v3) and were trying to build a v4 project - make sure [core tools is up to date](https://github.com/Azure/azure-functions-core-tools).

> Do you have a tools so I could remove all older .NET installations and try again

I don't believe we (Azure Functions) have any tools to do that, but if you're trying to uninstall .NET versions, there's a [doc](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=macos) for that. And if you're trying to upgrade core tools, you can follow this [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools).

**Comment by Uffman** [comment]
I removed all .NET SDKs (version from 2.1.x to the latest 6. x), removed VS and this clean install and error is gone. You can close the ticket. Thank you for the help👍
