### ISSUE TITLE
Update WebJobs.Logging.ApplicationInsights dependency Microsoft.ApplicationInsights to 2.20

### ISSUE THREAD

**Issue by Havunen** [Azure/azure-webjobs-sdk#2816]
Snyk has found vulnerable component in WebJobs.Logging.ApplicationInsights project.

```
Microsoft.Azure.WebJobs.Logging.ApplicationInsights@3.0.30
Microsoft.ApplicationInsights.WindowsServer@2.17.0 <--
System.Runtime.Serialization.Json@4.3.0
System.Private.DataContractSerialization@4.3.0
System.Text.RegularExpressions@4.3.0
```

Latest version 2.20 does not seem to have System.Runtime.Serialization.Json defined as its dependency:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer/2.20.0

So updating the version should fix the issue

**Comment by v-bbalaiagar** [comment]
Hi @Havunen , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by kashimiz** [comment]
It looks like this is being addressed by the following PRs/issue: 

https://github.com/Azure/azure-functions-host/issues/7869

https://github.com/Azure/azure-functions-host/pull/8040
https://github.com/Azure/azure-functions-host/pull/8041

**Comment by kashimiz** [comment]
Closing as duplicate issue.
