### ISSUE TITLE
Is there a way of using Middleware without Isolated functions v4.0.1

### ISSUE THREAD

**Issue by scott-david-walker** [Azure/azure-webjobs-sdk#2825]
Hi,
We've just done an upgrade from our Azure Functions V3 (.NET core 3.1) to V4 and we're unable to insert middleware. All the documentation says that this is possible but only when using Isolated functions. Is there a method to do this for functions not using the isolated process?

We found the [Functions Filters](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Filters/FunctionInvocationFilterAttribute.cs) but these are marked as obsolete.

Any advice on this is appreciated

**Comment by v-bbalaiagar** [comment]
Hi @scott-david-walker , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Tagging @mathewc / @fabiocav , for more inputs

**Comment by mathewc** [comment]
Correct - middleware registration is only possible in the isolated model, details [here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#middleware). The Function Filters feature you reference is marked obsolete because we don't plan on carrying that model forward - see [here](https://github.com/Azure/azure-webjobs-sdk/issues/1284), in favor of a more standard middleware approach.

**Comment by rafek1241** [comment]
> Correct - middleware registration is only possible in the isolated model, details [here](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#middleware). The Function Filters feature you reference is marked obsolete because we don't plan on carrying that model forward - see [here](https://github.com/Azure/azure-webjobs-sdk/issues/1284), in favor of a more standard middleware approach.

Do you plan to make the standard middleware approach available in `in-process` hosting model?

**Comment by mathewc** [comment]
No we don't plan on extending the in-proc model with middleware capabilities.

**Comment by MisinformedDNA** [comment]
@mathewc The "more standard middleware approach" has been open since 2017. Can you update that [thread](https://github.com/Azure/azure-webjobs-sdk/issues/1284) with any progress and roadmap?
