### ISSUE TITLE
Use new reliable way of flushing Application Insights logs

### ISSUE THREAD

**Issue by marnilss** [Azure/azure-webjobs-sdk#2847]
As discussed here (https://github.com/Microsoft/ApplicationInsights-dotnet/issues/407) the old synchronous `telemetryClient.Flush()` was not reliable since it wasn't really synchronous, but instead relied upon some variation of `Thread.Sleep(n)` afterwards.

This is implemented with a sleep of 2 seconds in Dispose() in ApplicationInsightsLoggerProvider.cs (https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerProvider.cs)

But when functions exceed the function timeout value, and the host shuts down, the following trace-messages are never seen in Application Insights with the current sleep-setting.

> "A function timeout has occurred. Host is shutting down."
> "Timeout value of 00:00:30 exceeded by function 'AddressImportOnlyFunction_LogVersion' (Id: 'a9ac9cd6-f299-4d72-9ecf-d74f0b032299'). Initiating cancellation."
> 

neither is the Exception:

> Microsoft.Azure.WebJobs.Host.FunctionTimeoutException

Solution: he new asynchronous FlushAsync() method should be awaited instead, and then the sleep can be removed.

#### Repro steps

1. Create new Function App project with application insights logging enabled
2. Create a new function which calls `Thread.Sleep(TimeSpan.FromMinutes(5));`
3. Set `"functionTimeout": "00:00:30"` in host.json
4. Run and observe that the log messages detailed above is never seen in Application Insights database.

#### Expected behavior

Both trace- and exceptions-messages surrounding timeout should be visible in Application Insights.

#### Actual behavior

None of the trace- and exceptions-messages surrounding timeout are visible in Application Insights.

#### Known workarounds

An ugly workaround is to add the following function to the project, but which also proves that FlushAsync solves the problem:
```
    public class LogFlusher
    {
        private static bool _isSetup = false;

        private readonly TelemetryClient _telemetryClient;
#pragma warning disable CS0618 // Type or member is obsolete - BUT Function App is still relying on it
        private readonly IApplicationLifetime _applicationLifetime;

        public LogFlusher(TelemetryClient telemetryClient, IApplicationLifetime applicationLifetime)
#pragma warning restore CS0618 // Type or member is obsolete
        {
            _telemetryClient = telemetryClient;
            _applicationLifetime = applicationLifetime;
        }

        [FunctionName($"{nameof(LogFlusher)}_{nameof(SetupStoppingCallbacks)}")]
        public void SetupStoppingCallbacks([TimerTrigger("01:00:00", RunOnStartup = true)] TimerInfo myTimer)
        {
            if (!_isSetup)
            {
                _applicationLifetime.ApplicationStopping.Register(() =>
                {
                    var task = _telemetryClient.FlushAsync(CancellationToken.None);
                    task.Wait();
                });
                _isSetup = true;
            }
        }
    }
```

**Comment by v-bbalaiagar** [comment]
Hi @RohitRanjanMS / @gzuber , Could you please look into this issue.

**Comment by RohitRanjanMS** [comment]
@v-bbalaiagar I will have a look at this.
@marnilss thank you very much for raising this issue. I will reach out to you if I need more information.

**Comment by Eli-Black-Work** [comment]
Excited for this! 🙂

**Comment by 304NotModified** [comment]
Is this still needed? What is the next step?

**Comment by RohitRanjanMS** [comment]
I haven't got time to make this change, but this is in my todo list.
