### ISSUE TITLE
IJobActivator usage

### ISSUE THREAD

**Issue by fabiomaulo** [Azure/azure-webjobs-sdk#2850]
This is just a "please" issue. sdk v3.0.31.
We are pushing everything from net472 to netstandard2.0, netcoreapp3.1 to then move to net6 and future.
We are using the webjobs-sdk mostly to consume queues (since the beginning of the SDK... and before).
Our consumers are stateless classes with DI in the ctor. In the v1.9 we were using the `IJobActivator` injecting it in the `JobHostConfiguration`.
In the v3.x I know that, if we use the default DI, you can instantiate our consumer injecting other classes but... so far we need to use another DIcontainer. I tried to register the consumer/function class as `Transient` but the SDK does not look at the container to check if the consumer class have a ctor already registered; instead it use its internal DefaultActivator.
So... you know... 
```
public static void UseOurJobActivator(IServiceCollection services)
{
	var sdkDefaultJobActivatorDescriptor = services.FirstOrDefault(sd => sd.ServiceType == typeof(Microsoft.Azure.WebJobs.Host.IJobActivator));
	services.Remove(sdkDefaultJobActivatorDescriptor);
	services.AddSingleton<Microsoft.Azure.WebJobs.Host.IJobActivator>(c => new LocalJobsActivator());
}
```

*Please, for some months, please, don't remove the `IJobActivator` from your code.*

Thanks.

**Comment by v-bbalaiagar** [comment]
Tagging @mathewc , for more inputs

**Comment by fabiomaulo** [comment]
Perhaps you can add something like the extension defined in `Microsoft.Extensions.Hosting.Abstractions`:
```
public static IServiceCollection AddHostedService<THostedService>(this IServiceCollection services, Func<IServiceProvider, THostedService> implementationFactory) where THostedService : class, IHostedService;
```
May be as:
```
public static IWebJobsBuilder AddJob<THostedJob>(this IWebJobsBuilder builder, Func<IServiceProvider, THostedJob> implementationFactory) where THostedJob : class;
```

**Comment by fabiomaulo** [comment]
Ok. We do it more quickly than I think.
Everything is working as expected using `Microsoft.Extensions.DependencyInjection`.
BTW would be useful to have something as `AddJob<THostedJob>`, with the ctor `Func`, just to replace the old `JobHostConfiguration.JobActivator` 
Thanks.
