### ISSUE TITLE
The 'Function1' function is in error: The binding name _ is invalid. Please assign a valid name to the binding.

### ISSUE THREAD

**Issue by anton-gustafsson** [Azure/azure-webjobs-sdk#2868]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new timer triggered function project (.net 6)

2. Rename TimerInfo parameter to underscore (_) 

#### Expected behavior

I expect this to work. I could not find any naming rules for timerInfo parameter name, so it would be nice to know why this is a limitation. 

#### Actual behavior
Runtime error:
The 'Function1' function is in error: The binding name _ is invalid. Please assign a valid name to the binding.

#### Related information 

Provide any related information 

* PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" 

![image](https://user-images.githubusercontent.com/22906905/168738401-0fe8359f-c388-4883-9da7-a80e53389f2c.png)

**Comment by Ved2806** [comment]
Hi @anton-gustafsson We are discussing this internally and let you know about the findings soon!

**Comment by Ved2806** [comment]
Hi @anton-gustafsson It is recommended that parameter name should be something meaningful. It is allowed that name can start with underscore. It is not supporting the "underscore" as a parameter name. You may want to go through [ValidateBinding](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Utility.cs#L556)
