### ISSUE TITLE
Microsoft.Azure.WebJobs.Logging.ApplicationInsights is incompatible with Polly

### ISSUE THREAD

**Issue by nathangelman123** [Azure/azure-webjobs-sdk#2875]
When adding application insights as a dependency to a web job that has Microsoft.Extensions.Http.Polly (version 6.0.5), upon calling builder.Build() the following exception occurs:

`System.MethodAccessException: 'Attempt by method 'Microsoft.Extensions.Logging.Configuration.LoggerProviderConfigurationFactory.GetConfiguration(System.Type)' to access method 'Microsoft.Extensions.Logging.ProviderAliasUtilities.GetAlias(System.Type)' failed.'
`

This is an issue for trying to use both Polly and Application Insights in the same webjob.

#### Repro steps

Provide the steps required to reproduce the problem

1. Follow the [Microsoft web jobs tutorial](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started) up to [this step](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#initialize-the-application-insights-logging-provider) and then add `<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.5" />` to the project

Alternatively, use the code from [this gist](https://gist.github.com/nathangelman123/da979712ee8872a50cc2f746104ae033)

2. Run the project, upon hitting builder.Build(), an exception will be thrown.

3. Remove the reference to polly OR comment out the `b.AddApplicationInsightsWebJobs(o => o.ConnectionString = connectionString);` line, and suddenly the project works

#### Expected behavior

builder.Build() does not throw an exception

#### Actual behavior

builder.Build() throws `System.MethodAccessException: 'Attempt by method 'Microsoft.Extensions.Logging.Configuration.LoggerProviderConfigurationFactory.GetConfiguration(System.Type)' to access method 'Microsoft.Extensions.Logging.ProviderAliasUtilities.GetAlias(System.Type)' failed.'
`

#### Known workarounds

N/A

#### Related information 

Provide any related information 

* Microsoft.Extensions.Http.Polly@6.0.5
* Microsoft.Azure.WebJobs.Logging.ApplicationInsights@3.0.33
* [Links to source](https://gist.github.com/nathangelman123/da979712ee8872a50cc2f746104ae033)

**Comment by Ved2806** [comment]
Hi @nathangelman123 Please refer [#18834](https://github.com/dotnet/efcore/issues/18834) and let us know if it helps. Thanks.
