### ISSUE TITLE
Update dependency on Microsoft.ApplicationInsights

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-webjobs-sdk#2900]
A new [version](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nuget.org%2Fpackages%2FMicrosoft.ApplicationInsights%2F2.21.0&data=05%7C01%7CLove.Josh%40microsoft.com%7Cee33cb46b71c4d831e7808da770a8908%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637953184376476224%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UV6kova49ZDTzhCJDIF3Yv4jFwBQwgm1DifDaK07Qmc%3D&reserved=0) of the App Insights library has been released that adds additional support for the new Service Bus library. In order for Service Bus extension users to benefit from these changes, we would need to update the dependency version used in the WebJobs SDK, which would in turn pull up the version used by the Functions host.

**Comment by ilmax** [comment]
Since the referenced version of AppInsights doesn't have support for the new Service Bus library and the old one is deprecated and suggest to use the newly `Azure.Messaging.ServiceBus`, this one should be prioritized otherwise distributed tracing is not working as expected when using service bus.

**Comment by maskati** [comment]
@ilmax in addition to expanded support for Service Bus, this will probably also unblock use of [Azure AD authentication for Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication):

> Support for Azure AD in the Application Insights .NET SDK is included starting with [version 2.18-Beta3](https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.18.0-beta3)

**Comment by brettsam** [comment]
This has been completed in for a while now:

- WebJobs: https://github.com/Azure/azure-webjobs-sdk/pull/2916
- Functions: https://github.com/Azure/azure-functions-host/pull/8838.
