### ISSUE TITLE
WebJobs SDK Roadmap

### ISSUE THREAD

**Issue by buzzaII** [Azure/azure-webjobs-sdk#2902]
As Azure function looks to be moving away from In-Process model - It looks like the newer 'isolated process' doesn't require the webjobs SDK anymore (please correct me if that is not the case):

![image](https://user-images.githubusercontent.com/7981600/184459997-dc3b2e44-9267-4e1c-8110-b1db1dd6f399.png)

What will the future of the WebJobs SDK look like - is it still something that will be maintained after Azure Functions moves off the webjobs SDK.

**Comment by ramya894** [comment]
@buzzaII We will check this request with our next level team and update you soon.

**Comment by ramya894** [comment]
@mattchenderson can you please answer to the above question.

**Comment by bhagyshricompany** [comment]
@buzzaII Yes, it's true that Azure Functions has moved away from the In-Process model, but it doesn't mean that the WebJobs SDK will be deprecated or no longer maintained. The WebJobs SDK is a toolset for creating background jobs that can run in an Azure App Service app, and it is still a valid option for building background jobs, even with Azure Functions moving away from the In-Process model.

Microsoft has indicated that they will continue to invest in and maintain the WebJobs SDK, so it will still be a viable option for developers to create background jobs in the future.
