### ISSUE TITLE
Azure functions and application insights. AddTag() working but not AddBaggage()

### ISSUE THREAD

**Issue by miiic** [Azure/azure-webjobs-sdk#2915]
Please provide a succinct description of the issue.

```
 [FunctionName(nameof(MyOrchestrator))]
        public async Task RunAsync([OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var input = context.GetInput<Input>();
            Activity.Current?.AddTag("tag", input.test1.ToString());
            Activity.Current?.AddBaggage("baggage", input.test2.ToString());
}
```

Provide the steps required to reproduce the problem

When viewing the "performance" tab in application insights I can see the tag that I have added, but I cannot see the property for baggage

#### Expected behavior

The baggage will appear the same as the tag in custom properties of the request

#### Actual behavior

I can see the tag, but not the property for baggage

#### Known workarounds

In order to see the tag I had to explicitly use 

`<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.6.0"></PackageReference>`

#### Related information 

Provide any related information 

`  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <Configurations>Debug;Release;Integration Test CI</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AzureFunctions.Extensions.DependencyInjection" Version="1.1.3" />
    <PackageReference Include="Guard.Net" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.6.0" />
      <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
	<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.6.0">
		<NoWarn>NU1605</NoWarn>
	</PackageReference>
  </ItemGroup>`

**Comment by ramya894** [comment]
@miiic we will check this with our next level team and update you with the results.

**Comment by ramya894** [comment]
@davidmrdavid /@AnatoliB Can you please have a look into this issue.

**Comment by AnatoliB** [comment]
@RohitRanjanMS Any idea?

**Comment by miiic** [comment]
> @RohitRanjanMS Any idea?

Still interested in finding an answer to this, my workaround at the moment is just to litter my codebase with AddTag()

**Comment by miiic** [comment]
Still interested in finding an answer to this, my workaround at the moment is just to litter my codebase with AddTag()

**Comment by RohitRanjanMS** [comment]
Hi @miiic yes, we have the implementation to copy tags and include it in the custom dimensions. We don't do this for the baggage. It's the same behavior with OpenTelemetry as well. Tags are included in the traces while baggages are not.
