### ISSUE TITLE
Development settings not been correctly loaded when using `ConfigureWebJobs`

### ISSUE THREAD

**Issue by huco95** [Azure/azure-webjobs-sdk#2924]
I am getting the following error when using development settings file ("appsettings.Development.json"): `FormatException: Settings must be of the form "name=value".` 

#### Repro steps

1. Create `appsettings.json` file:
```json
{
  "AzureWebJobsStorage": "ConnectionString",
}
```

2. Create `appsettings.Development.json` file:
```json
{
  "AzureWebJobsStorage": "ConnectionStringDevelopment",
}
```

3. Execute the following code:

``` c#
using IHost host = Host.CreateDefaultBuilder()
        .ConfigureLogging((context, b) => { b.AddConsole(); })
        .ConfigureServices((context, services) => {
            // DI configuration
        })
        .ConfigureWebJobs((context, builder) => {
            builder
                .AddAzureStorageCoreServices()
                .AddAzureStorageQueues()
                .AddAzureStorageBlobs();
        })
        .Build();

await host.RunAsync();
```

#### Expected behavior

`appsettings.Development.json` values should be loaded in `context.Configuration`.

#### Actual behavior

`appsettings.json` values are loaded in `context.Configuration`.

#### Known the workarounds

- Delete `appsettings.json` file. After deleting this file the program is loading the correct configuration file.
- Also, if I comment `ConfigureWebJobs` section, the program loads the correct configuration file.

#### Related information

- .NET 6
- Microsoft.Azure.WebJobs.Extensions 4.0.1

**Comment by ramya894** [comment]
@huco95 Please follow the instructions given in the below link.
https://github.com/Azure/azure-webjobs-sdk/issues/1931
If you still face the issue, please provide us the details related to webjob so that we can check further.
