### ISSUE TITLE
Unable to start project after upgrade to .NET 7

### ISSUE THREAD

**Issue by javissimo** [Azure/azure-webjobs-sdk#2934]
#### Repro steps

1. Upgrade solution to .NET 7

2. Start the application

#### Expected behavior

Application starts successfully.

#### Actual behavior

`Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=7.0.0.0` 

![image](https://user-images.githubusercontent.com/369572/201651043-0c001840-18d6-4b19-9b86-ca8376e356bc.png)

#### Related information 

Package `Microsoft.Extensions.Configuration.Abstractions` version 7.0.0.0 exists and it is installed in a base .csproj using CPM (Directory.Packages.props)

The app is an Azure Function v4

* Package version: 3.0.33

**Comment by ramya894** [comment]
@javissimo : If you are having trouble to switch to .net 7 in isolated model app, please open an issue in the [dotnet isolated worker repo](https://github.com/Azure/azure-functions-dotnet-worker).
