### ISSUE TITLE
Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider does not implement ISupportExternalScope

### ISSUE THREAD

**Issue by badbort** [Azure/azure-webjobs-sdk#3012]
The `ApplicationInsightsLoggerProvider` in `Microsoft.Azure.WebJobs.Logging.ApplicationInsights` does not implement `ISupportExternalScope`.

This results in activity tracking custom properties not appearing in app insights:

```
            logging.Configure(options =>
            {
                options.ActivityTrackingOptions =
                    ActivityTrackingOptions.SpanId |
                    ActivityTrackingOptions.TraceId |
                    ActivityTrackingOptions.ParentId;
            });
```

You also miss out on your own logging scopes like so:

```
            using var _ = logger.BeginScope(new Dictionary<string, string>()
            {
                {"hello", "world"}
            });
```

None of these are being added as custom properties because the provider doens't implement ISupportExternalScope.

The `Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider` does implement this:

```
    [ProviderAlias("ApplicationInsights")]
    public class ApplicationInsightsLoggerProvider : ILoggerProvider, ISupportExternalScope
```

* "Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.35"

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the all repro steps.
