### ISSUE TITLE
ScaleManager pollutes App Insights with DuplicateKey exception logs when switching to Elastic Premium plan

### ISSUE THREAD

**Issue by aceltuk** [Azure/azure-webjobs-sdk#3015]
After switching our Durable Orchestration solution to an Elastic Premium plan we started to get immense numbers of exceptions being logged but not thrown from line 113 of the ScaleManager class. It seems that whoever wrote this was aware that there is a problem where duplicate keys are stored in a repository based on the InMemoryScaleMetricsRepository class. We have had to filter out error messages sourced from the namespace that contains the ScaleManager class (in host.json) but wonder if a fix or different approach to this will be coming down the track?

Details of the error thrown:

System.ArgumentException at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException
An item with the same key has already been added. Key: durabletasktrigger-netherite-fa-polaris-pipeline-dev-coordinator

As you can see, we have already moved to a Netherite backing store for increased performance.
Our application is unaffected as such because the error is logged but not thrown, ensuring that a collection of unique keys is returned, but we dislike the notion of removing the logging of exceptions from any part of a referenced library and would appreciate some idea of whether or not it is even worth monitoring any fixes/behaviour changes related to this or is it just something we have to live with?

Many thanks in advance for taking the time to read this and for any advice you may offer.

https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Scale/ScaleManager.cs

**Comment by bhagyshricompany** [comment]
Thanks for  informing will check and confirm for the same .please share the all repro steps if possible.Thanks
