### ISSUE TITLE
Custom metrics published to App Insights / Azure Monitor have custom dimensions with excessively high cardinality

### ISSUE THREAD

**Issue by pmalmsten** [Azure/azure-webjobs-sdk#3040]
The Functions runtime publishes custom metrics to App Insights. These custom metrics have custom dimensions that can assume a high number of unique values (high cardinality). When the multi-dimensional metrics feature is enabled in App Insights ( https://learn.microsoft.com/en-us/azure/azure-monitor/app/get-metric#enable-multidimensional-metrics ), these high-cardinality dimensions consume a lot of the 50k time series quota offered for the feature, which makes Azure Monitor visualizations of custom metrics unreliable.

#### Repro steps

1. Create an Azure Application Insights instance.
2. Enable multi-dimensional metrics on the App Insights instance: https://learn.microsoft.com/en-us/azure/azure-monitor/app/get-metric#enable-multidimensional-metrics
3. Create an Azure Logic Apps Standard instance.
4. Enable Application Insights integration in the Azure Logic Apps Standard instance: https://learn.microsoft.com/en-us/azure/connectors/connectors-azure-application-insights
5. Create a workflow in the Azure Logic Apps Standard instance and run it continuously (e.g. trigger it 100 times every 5 minutes for a month).

#### Expected behavior

The **Active Time Series** metric reported by Azure Monitor remains low (https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-custom-overview#quotas-and-limits). Custom metrics published by Logic Apps Standard and/or the Functions runtime do not include custom dimensions that may assume many unique values (aka. high cardinality).

#### Actual behavior

The **Active Time Series** metric reported by Azure Monitor is very high, e.g. 70k+. Custom metrics visualizations in Azure Monitor are unreliable due to time series usage exceeding the 50k active time series limit (https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-custom-overview#quotas-and-limits):

![MicrosoftTeams-image (2)](https://github.com/Azure/azure-webjobs-sdk/assets/2946675/5e320474-40f2-4d37-b2b8-848506659370)

Querying the `customMetrics` table in the `Logs` blade of the Application Insights instance reveals that custom dimensions are published by the Logic App Standard instance with an excessively high number of unique values, which consumes all of our active time series quota. An example of some custom dimensions and their observed cardinality over 30 days:

- `HostInstanceId`: 6162 unique values
- `ProcessId`: 1757 unique values
- `InvocationId`: 8687 unique values

These custom dimensions can be seen on custom metrics with names like `Runs Succeeded` and `<Workflow Action Name> Action Success Latency`, etc.

When running a Function App (outside of Logic Apps), these dimensions can be seen on custom metrics with names like `<Function Name> SuccessRate`, `<Function Name> Failures`, etc.

#### Known workarounds

Azure Support has suggested the following workaround in `host.json` for Logic Apps Standard / Function Apps to disable the related metrics entirely:

```json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  },
  "logging": {
    "logLevel": {
      "Host.Aggregator": "Warning"
    }
  }
}
```

My team and I have not yet evaluated whether this workaround would be suitable for us (e.g. whether it would disable custom metrics that we need to monitor).

#### Related information 
The custom metrics entries in the App Insights `Logs` `customMetrics` table include `sdkVersion` values of:
- af_azurefunctions: 4.26.0.0
- af_m-agg2c:2.21.0-429

The Logic Apps Standard resource is configured with:
- `FUNCTIONS_EXTENSION_VERSION`: `~4` 
- `FUNCTIONS_WORKER_RUNTIME`: `dotnet-isolated`

**Comment by taraldr** [comment]
Hi @RohitRanjanMS, you don't happen to know if MS stopped counting the active time series stemming from these "default" custom metrics yesterday as contributing towards the active time series quota of 50k, do you?

I was just preparing a host.json `"Host.Aggregator": "Warning"` workaround yesterday (pending the fix in this PR to be included in a release on nuget) when I observed that while the volume of custom metrics stayed consistent across the last three days, the active time series dropped to a fraction of what it previous was.

Don't know how to explain this (as we did not change anything in this period) without MS doing something internally.

![image](https://github.com/Azure/azure-webjobs-sdk/assets/2229049/2538f173-a788-4780-b3a7-6531d1974201)

![image](https://github.com/Azure/azure-webjobs-sdk/assets/2229049/da1308ae-1ff0-4bbe-846d-eed2a3021b80)

**Comment by RohitRanjanMS** [comment]
@taraldr , I have no idea. I will check with the Azure Monitor team.
