### ISSUE TITLE
System.TimeoutException with message "The operation 'GetMessageAsync' with id '<guid>' did not complete in '00:03:00'" - how to find the queue that cause timeout?

### ISSUE THREAD

**Issue by tadassukys** [Azure/azure-webjobs-sdk#3054]
Randomly an exception of type `System.TimeoutException` is thrown in our function app containing an error message:

 "The operation 'GetMessageAsync' with id '{guid}' did not complete in '00:03:00'". 

Stack trace:
``` C#
System.TimeoutException:
   at Microsoft.Azure.WebJobs.Extensions.Storage.TimeoutHandler+<ExecuteWithTimeout>d__1`1.MoveNext (Microsoft.Azure.WebJobs.Extensions.Storage, Version=4.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\TimeoutHandler.cs:36)
```

We run a number of functions that are triggered by different queues. I would like to understand which of these queues cause a timeout error. How does '{guid}' value correlate with individual function apps? The code in[ TimeoutHandler.cs](https://github.com/Azure/azure-webjobs-sdk/blob/ca14c114a61bd3693f629c89063655fc6ee2c522/src/Microsoft.Azure.WebJobs.Extensions.Storage/TimeoutHandler.cs#L36C27-L36C27) says that it is `clientRequestId` value. All logs go to Azure Application Insights. Is it possible to get more context from Application Insights about the error?

* Package version: 4.0.4.0

Thank you.

**Comment by bhagyshricompany** [comment]
Thanks for reporting.
To correlate this with individual function apps and gain more context from Azure Application Insights, you can follow these steps:

Application Insights Instrumentation:
Ensure that your Azure Function Apps are correctly instrumented with Application Insights. This includes having the Application Insights SDK installed and configured in your function app.

Correlation Ids:
Application Insights uses correlation IDs to tie together different telemetry data for a specific operation. The correlation ID is usually propagated across different components involved in processing a request. This includes HTTP requests, background jobs, etc.

Logging Custom Properties:
In your Azure Functions code, you can enrich the logs with custom properties, including the correlation ID. For example, you can log the correlation ID associated with the function execution.
