### ISSUE TITLE
StorageAccount and Conection ignored if not named AzureWebJobsStorage

### ISSUE THREAD

**Issue by vllama** [Azure/azure-webjobs-sdk#3057]
Please provide a succinct description of the issue.
Neither the StorageAccount attribute, nor the Connection property on the BlobTrigger attribute are respected.
#### Repro steps

Provide the steps required to reproduce the problem

1. Define a Function as such:  
`public class AzureArtifactChange
{
    [FunctionName("AzureArtifactChange")]
	//[StorageAccount("ArtifactChecker_AZURE_CONNECTION_STRING")]
	public void Run([BlobTrigger("artifacts/{name}", Connection = "ArtifactChecker_AZURE_CONNECTION_STRING")] Stream myBlob, string name, ILogger log) {
		log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
	}
}`

2.  add Value to local.settings.json  `{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard2": "dotnet",
    "ArtifactChecker_AZURE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=yyy;EndpointSuffix=core.windows.net"
  }

}`

3. Step B

#### Expected behavior

Function runs and watches for changes to the specified container in the storage account
#### Actual behavior

Provide a description of the actual behavior observed.  
`
[2024-02-05T22:47:51.844Z] Job host started
[2024-02-05T22:47:51.852Z] The 'AzureArtifactChange' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'AzureArtifactChange'. Microsoft.Azure.WebJobs.Extensions.Storage.Blobs: Storage account connection string 'AzureWebJobsStorage' does not exist. Make sure that it is a defined App Setting.
`

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version : 
PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
	<PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.39" />
      <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
      <PackageReference Include="Azure.Storage.Files.Shares" Version="12.17.1" />
      <PackageReference Include="Azure.Storage.Queues" Version="12.17.1" />
      <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.2.2" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.3" />
	  <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.1" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
	  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.3.0" />
	<PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="5.0.0" />
  </ItemGroup>
* Links to source

**Comment by bhagyshricompany** [comment]
Hi @vllama Thanks for reporting .can you try it again.if its not working please share all sdk you have used.
this I set up in config:{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard2": "dotnet",
    "ArtifactChecker_AZURE_CONNECTION_STRING": "",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
  }
}
////////////////////////////////////////////////////////////
using System.IO;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace FunctionApp2
{
    public class Function1
    {
        private readonly ILogger<Function1> _logger;

        public Function1(ILogger<Function1> logger)
        {
            _logger = logger;
        }



        //public class AzureArtifactChange
        //{
        //    [FunctionName("AzureArtifactChange")] 
        //    [StorageAccount("ArtifactChecker_AZURE_CONNECTION_STRING")] 
        //    public void Run([BlobTrigger("artifacts/{name}", Connection = "ArtifactChecker_AZURE_CONNECTION_STRING")] Stream myBlob, string name, ILogger log) { 
        //        log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        //    } 
        //}


            /// <summary>
            /// ///////////////////////////////////////////
            /// </summary>
            /// <param name="stream"></param>
            /// <param name="name"></param>
            /// <returns></returns>

            [Function("AzureArtifactChange")]
        public async Task Run([BlobTrigger("artifacts/{name}", Connection = "ArtifactChecker_AZURE_CONNECTION_STRING")] Stream stream, string name)
        {
            using var blobStreamReader = new StreamReader(stream);
            var content = await blobStreamReader.ReadToEndAsync();
            _logger.LogInformation($"C# Blob trigger function Processed blob\n Name: {name} \n Data: {content}");
        }
    }
}
///////////////////////////////////////////////
![Image](https://github.com/user-attachments/assets/c7b881bd-5b87-473d-abef-007ce7ab8c51)


///////////////////////////////////////////////output////////////////////////
![Image](https://github.com/user-attachments/assets/7644cb84-0453-4fb0-8188-a77b4d1d80e5)

**Comment by vllama** [comment]
I will have time to look at this this weekend.

**Comment by vllama** [comment]
Seems to still be not working:

I have started a new project using latest VS.

Function still only triggers when files are dropped in AzureWebJobsStorage and not in the **Connection** specified in the run method: ArtifactChecker_AZURE_CONNECTION_STRING

local.settings.json:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "ArtifactChecker_AZURE_CONNECTION_STRING": "DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=yyy5TE+AStLjuqFw==;EndpointSuffix=core.windows.net"
  }
}
```
![Image](https://github.com/user-attachments/assets/a5cbcd3f-a3d1-4365-afea-ae512bbe880d)

.csproject:
```
<PropertyGroup>
  <TargetFramework>net8.0</TargetFramework>
  <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  <OutputType>Exe</OutputType>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <UserSecretsId>e2c01b6c-27bb-4fc7-9127-e91fdb289af0</UserSecretsId>
</PropertyGroup>
<ItemGroup>
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  <PackageReference Include="Azure.Data.Tables" Version="12.9.1" />
  <PackageReference Include="Azure.Storage.Blobs" Version="12.22.2" />
  <PackageReference Include="Azure.Storage.Files.Shares" Version="12.20.1" />
  <PackageReference Include="Azure.Storage.Queues" Version="12.20.1" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs" Version="6.3.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.4" />
  <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
  <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.6" />
  <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.1" />
</ItemGroup>
<ItemGroup>
```


Files are only ever picked up from emulator, even though I specify a real storage account in azure:

![Image](https://github.com/user-attachments/assets/6380d3a3-ea7d-4bf0-809e-6db09e33d1b8)

**Comment by vllama** [comment]
I am expecting that `"AzureWebJobsStorage": "UseDevelopmentStorage=true"`   only applies to the function runtime, not to the connection parameter in the Run method.  Is this wrong?

**Comment by bhagyshricompany** [comment]
Thank you for your patience.  please try below options. use this  as key name AzureWebJobsArtifactChecker_AZURE_CONNECTION_STRING. 
![Image](https://github.com/user-attachments/assets/b4252e7c-ad08-45d9-a3c7-b9b4ea175d43)

Thanks again!

**Comment by vllama** [comment]
Prepending the setting with `AzureWebJobs` causes it to work correctly.   This should be documented somewhere.

Thanks

**Comment by bhagyshricompany** [comment]
yes will document this in in future.Thanks

**Comment by evaldas-raisutis** [comment]
@bhagyshricompany so just I understand, all app settings used for blob binding need to start with AzureWebJobs? Why is that?
