### ISSUE TITLE
Allow new log output shapes without dashboard changes

### ISSUE THREAD

**Issue by davidmatson** [Azure/azure-webjobs-sdk#308]
``` c#
class LogMessage 
{
                string Format;
                Dictionary<string,object> Properties;
}
```

Where Format can embed links into the property bag. 
“Table written {x} entities in {y} ms”,    {x : 15, y : 152 }

Maybe the property bag includes some type information if we wanted to have the dashboard own the formatting

**Comment by paulbatum** [comment]
Old issue. Dashboard logging is not under active maintenance.
