### ISSUE TITLE
WebJob AppInsights OperationId missing

### ISSUE THREAD

**Issue by BerenOneHand** [Azure/azure-webjobs-sdk#3105]
### Repro Steps
Add application insights to a standard webjob by following instructions here: [MS learn](https://learn.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started)

### Expected behavior 

- Any logging done should contain a operationid to track a single webjob run. 
- Any http requests done during the webjob run should also be included but none are logged.

I can see the metrics in the monitoring tab on the webapp but no requests are logged to app insights. 
What am i missing?

**Comment by BerenOneHand** [comment]
Using the worker service implementation seems to work better.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service

**Comment by bhagyshricompany** [comment]
Hi @BerenOneHand  Thanks for  informing will check and update you shortly.Thanks

**Comment by bhagyshricompany** [comment]
Hi @BerenOneHand  Can you try it again.please.Thanks

**Comment by JAdluri** [comment]
Hello @BerenOneHand  please let me know the step wise explanation to reproduce the issue .
