### ISSUE TITLE
Problem with Microsoft.Azure.Webjobs.Extensions version 5.3.3

### ISSUE THREAD

**Issue by philipcj** [Azure/azure-webjobs-sdk#3112]
I updated my packages on all 3 of my function apps (.NET 8, c#), which included updating the above package to 5.3.3.

When I release it, I get System.Private.CoreLib: Exception has been thrown by the target of an invocation. Microsoft.Azure.Webjobs.Extensions.Storage.Queues: Could not load file or assembly, System.Memory.Data, Version = 6.0.0.0, ... The system cannot find the file specified.

I have reverted back to 5.3.2 to resolve this issue.

**Comment by fabiocav** [comment]
Hi @philipcj. Thanks for reporting this.

We're track this issue in the host repo here: https://github.com/Azure/azure-functions-host/issues/10575
We'll continue to post updates there, so I'll close this as a duplicate.
