### ISSUE TITLE
Support Multiple Storage Accounts

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#395]
Support Triggers and Bindings for multiple storage accounts.
eg. a function can be triggered on a queue message on a queue which can come from different storage accounts.

**Comment by mathewc** [comment]
Addressed with commit https://github.com/Azure/azure-webjobs-sdk/commit/d2040232492494a21d6955088582fd63f8bbd206

We now allow you to apply an attribute at the parameter/method/class level to override the default storage account used for a binding. See [examples here](https://github.com/Azure/azure-webjobs-sdk/blob/master/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/MultipleStorageAccountsEndToEndTests.cs#L131)

**Comment by darewreck54** [comment]
@mathewc Does this work still?  I just posted this https://github.com/Azure/azure-webjobs-sdk/issues/1430
