### ISSUE TITLE
BlobTriggers should work with Read Only Geo replicated storage

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#497]
Storage offers a feature where they will replicate your containers in different regions. The user ask is to trigger a function for the blobs in the replicated regions.

The secondary cannot be treated as another storage account. You have to set it in code while creating the connection which is not allowed in the SDK yet.
The fix here would be to allow you to set the option of triggering on the secondary as well.

I’ve tried setting the connection string up as 

```
DefaultEndpointsProtocol=https;AccountName=<myaccount>-secondary;AccountKey=<mykey>

DefaultEndpointsProtocol=https;AccountName=<myaccount>-secondary;AccountKey=<mykey>; BlobEndpoint=https://<myaccount>-secondary.blob.core.windows.net/;

DefaultEndpointsProtocol=https;AccountName=<myaccount>;AccountKey=<mykey> BlobEndpoint=https://<myaccount>-secondary.blob.core.windows.net/;
```

I don’t get the web job to trigger on any of those connection strings. I’ve checked (using Cerbratas Azure Management Studio) that there are items in the Geo-Replica on which to trigger. I don’t get any errors logged in the webjobs dashboard. The last log is “Job host started”. I’ve also ran it in visual studio with break points in the trigger code.

I’ve noticed in both code and the Cerebra tools that the connection string takes the same account and key for the secondary that it does for the primary. In code you have to set an option to say you want to access the secondary read-only storage.

```c#
StorageCredentials sc_source = new StorageCredentials(SourceName.Text, SourceKey.Text);
CloudStorageAccount sourceaccount = new CloudStorageAccount(sc_source, true);
CloudBlobClient source = sourceaccount.CreateCloudBlobClient();

source.DefaultRequestOptions.LocationMode = Microsoft.WindowsAzure.Storage.RetryPolicies.LocationMode.SecondaryOnly;

CloudBlobContainer container = source.GetContainerReference(Container.Text);
```

This implies that there is not a connection string to directly access the storage. I couldn’t find anything on the web to contradict this.

**Comment by mathewc** [comment]
Note that geo-replication is supported for Tables as well as Blobs (but not Queues). The default LocationMode for both CloudBlobClient and CloudTableClient is PrimaryOnly. Sounds like the ask here is to allow a hook for user code to configure the client used per blob/queue?

**Comment by mathewc** [comment]
Addressed in this commit: https://github.com/Azure/azure-webjobs-sdk/commit/c406c78d1f5156f12544a9aea0b6f289115e5c22

A new [StorageClientFactory](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/StorageClientFactory.cs) is supported on JobHostConfiguration. This factory is used to create ALL Azure Storage clients (Blob/Queue/Table) used by the framework. You can replace the default by setting `JobHostConfiguration.StorageClientFactory` with your own subclass to customize the creation and configure the clients the way you wish. For example, to address this issue, you can override and set `CloudBlobClient.DefaultRequestOptions.LocationMode = LocationMode.PrimaryThenSecondary` if you have Read-Access Geo Redundant storage enabled on your account.

A context object is passed into the factory, allowing you to customize clients per job function / binding. For example, the context includes the ParameterInfo for a parameter binding when the client to be created is for a binding. You can inspect the parameter/method/attribute as needed to determine how to configure the client.
