### ISSUE TITLE
Provide an extensibility point to hook into WebJobs logging

### ISSUE THREAD

**Issue by daniel-chambers** [Azure/azure-webjobs-sdk#506]
I'd like a way to hook into the logging that WebJobs does, so that I can record the logs in a mechanism other than the WebJobs dashboard.

In our particular example, we centralise all our logging into [Seq][1] and we then have Seq notify us when things fail (ie. Error/Fatal logs are recorded). I wanted to hook into the JobHost in our continuous WebJobs project and capture and push its logs into Seq, but there doesn't seem to be a way to do this.

I've set up logging in our job functions themselves, but that only records a certain class of failures. An example of something it doesn't catch is JSON deserialization errors when deserializing queue messages because that happens before my function is called.

I could monitor the poison message queues, but that would require a fair bit of custom coding effort, and would require some digging to actually find the associated error information in the WebJobs dashboard to correlate with that particular poison message, since the poison queues don't contain the actual error info.

I would want the ability to distinguish between different levels of logs produced by WebJobs (ie Debug, Info, Warning, Error), so I can focus in on important events easily.

It would also be nice to be able to get the job run ID (the GUID that is logged that can be used to find a particular run of a job that fails) injected as a parameter to the job function, so that it can be used a correlation ID for any logs written directly to an external logging provider (like Seq) from inside the job function. Why wouldn't I just log using the TextWriter? Because Seq and Serilog do semantic logging, which simple textual logging mechanisms like TextWriter don't support.

[1]: https://getseq.net/

**Comment by rustd** [comment]
@mathewc this is another example for customizing extensibility. This was one focuses around logging

**Comment by mathewc** [comment]
Daniel, thanks. We're doing extensibility work now, and we'll include this suggestion in set of work items we're considering for the next release. I agree that this would be great to open up :)

**Comment by jpknoll** [comment]
Second this request.

**Comment by mathewc** [comment]
Guys - we're working on this now. The proposal is to add an ITraceWriter property to JobHostConfiguration. When set to something, in addition to the Console/Dashboard logging we do now, we'll also route logs to this ITraceWriter. This allows you to control logs via TraceLevel, and filter/persist as you need. How does that sound?

@daniel-chambers Regarding the request for being able to bind to the FunctionInstanceID in a job function. We had another request for that recently, and I added it to the Extensions repo as a new extension binding. See commit: https://github.com/Azure/azure-webjobs-sdk-extensions/commit/d18887123dd3f4d45a511e095e1ec7527ce20403

**Comment by jpknoll** [comment]
@mathewc Thoughts on using the Microsoft.Framework.Logging mechanisms?

**Comment by mathewc** [comment]
Our requirements are very simple here - I'd rather not take a dependency on another framework for this. We can keep things simple by using Diagnostics.TraceLevel, and define a simple TraceWriter class.

**Comment by jpknoll** [comment]
@mathewc Sounds good. Looking forward to it.

**Comment by daniel-chambers** [comment]
@mathewc Sweet, this'll be super useful.

**Comment by JacobSnyder** [comment]
This is very similar to #537 that I opened a few weeks ago.  Except in #537 in addition to logging I'd like  to also have access to publish my own performance counters.

**Comment by mathewc** [comment]
FYI - the PR for this feature is here: https://github.com/Azure/azure-webjobs-sdk/pull/555

Take a look at TraceWriter and confirm that this will meet your needs. The E2E tests show an example of using this (see https://github.com/Azure/azure-webjobs-sdk/blob/logging/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L87) and the corresponding job functions binding to TraceWriter/TextWriter.

@JacobSnyder I think #537 is different. It requires wrapping all our SDK calls in some way, and exposing that for interception.

**Comment by mathewc** [comment]
@daniel-chambers This is checked in now, and I've also produced a [nightly build](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds) (version 1.1.0-alpha1-10054) with this. Please kick the tires on it and let me know if it meets your needs :)

**Comment by kamranayub** [comment]
I'd like to test this, I use LogEntries in my existing job and I'm porting it to the WebJobs SDK (since I'm now introducing queues and storage). Will try it and let you know.

**Comment by mathewc** [comment]
@kamranayub Great, thanks :) Recommend using the latest nightly build: 1.1.0-alpha1-10061.

**Comment by kamranayub** [comment]
@mathewc Looks like it works--LogEntries is being dumb but the trace writer itself is being called as expected. I'm using it with Common.Logging and NLog.

**Comment by mathewc** [comment]
NIce! Thanks for trying it out :)

**Comment by daniel-chambers** [comment]
@mathewc Yeah, this is great. Thanks! :)

**Comment by RudyCo** [comment]
Hello @kamranayub, could you please provide me with more details on how to use the CommonLoggingTraceWriter class above?
Many thanks in advance!
