### ISSUE TITLE
Inconsistent container names (azure-jobs / azure-webjobs)

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#509]
The host output and host archive queues currently have the prefix "azure-jobs" (e.g. azure-jobs-host-output). However, the host container names "azure-webjobs-hosts" and "azure-webjobs-dashboard" use the prefix "azure-webjobs". We should make these consistent.

**Comment by davidmatson** [comment]
I suggested this change earlier but we intentionally chose not to do so. At this point, it would be a breaking change and v1 shipped job hosts would no longer work with the latest dashboard.

I'd recommended not making this change.

**Comment by mathewc** [comment]
Thanks David. I understand that it would be breaking - I added this issue to remind us to go see if there is some way we could make this happen in a backward compatible manner - not sure. It's the OCD in me that the naming inconsistency bothers me :)
