### ISSUE TITLE
Disable Logging by setting AzureJobsDashboard ConnectionString value =”” 

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#51]
We should be able to disable logging by setting the AzureJobsDashboard ConnectionString to be empty. This can  be done in config or Antares portal or environment variables. We used to have it in alpha2 but it got changed in beta1.

**If I set the ConnectionString in config to be empty then I get the following exception**
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Azure.Jobs.Host.dll

Additional information: Failed to validate Microsoft Azure Jobs dashboard connection string: Microsoft Azure Storage account connection string is missing or empty.

The Microsoft Azure Jobs connection string is specified by setting a connection string named 'AzureJobsDashboard' in the connectionStrings section of the .config file, or with an environment variable named 'AzureJobsDashboard', or through JobHostConfiguration.

**If I set the ConnectionString in config to be empty in code then I get the following exception**
Now I am forced to set the AzureJobsStorage ConnectionString in code since I need to set the dashboardConnectionString as well. This is bad because in this case I cannot set the ConnectionString through the portal
```c#
            JobHostConfiguration config = new JobHostConfiguration() {DashboardConnectionString="" };
            JobHost host = new JobHost();
            host.RunAndBlock();
```
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Azure.Jobs.Host.dll

Additional information: Failed to validate Microsoft Azure Jobs dashboard connection string: Microsoft Azure Storage account connection string is missing or empty.

The Microsoft Azure Jobs connection string is specified by setting a connection string named 'AzureJobsDashboard' in the connectionStrings section of the .config file, or with an environment variable named 'AzureJobsDashboard', or through JobHostConfiguration.

**Proposed solution**
*I should be able to disable logging by setting AzureJobsDashboard connectionstring "empty" or "none" in config. You cannot use an empty string since in the Antares portal you cannot set the value of the ConnectionString to be empty

**Comment by mathewc** [comment]
This is no longer an issue
