### ISSUE TITLE
Support configurable retry policies

### ISSUE THREAD

**Issue by JacobSnyder** [Azure/azure-webjobs-sdk#510]
We use the WebJobs SDK, specifically `QueueTriggers` in our service to process jobs and send messages to other services over HTTP.  

Currently, the behavior of the WebJobs SDK is that if an exception is thrown when processing a queue message, the visibility timeout window on the message will be updated such that the message is immediately visible in the queue:

```c#
private async Task ReleaseMessageAsync(CloudQueueMessage message, CancellationToken cancellationToken)
{
    try
    {
        // We couldn't process the message. Let someone else try.
        await _queue.UpdateMessageAsync(message, TimeSpan.Zero, MessageUpdateFields.Visibility, cancellationToken);
    }
    // snip...
```

What this means is the next time that the WebJobs SDK checks the queue, the message will be seen and reprocessed.

Due to the nature of sending requests to other services over HTTP, it's likely that an immediate retry might fail.  Consider the situation where the target receiving service is down.  In this case, immediately retrying likely won't work.  In this case, we would quickly go through the loop of "pull message from the queue > fail to process the message because the service is down > update the visibility of the message".  Eventually, we would hit the max dequeue count and the message would be moved to the Poison Queue.  This is a shame because if we had retried processing the message later (say in a few minutes or hours), the target receiving service might be up and processing the message would succeed.

It would be nice if the WebJobs SDK supported different backoff strategies out-of-the-box or allowed me to specify a function that would be called with the current dequeue count and then I could return the TimeSpan to set as the message's visibility timeout.  Either way, being able to support immediate retry, linear backoff, or exponential backoff would be nice.

Of course, we can "hack" this in by re-queueing the message in the queue and manually set the visibility timeout.  But this doesn't feel very "clean".  We would also have to use the storage APIs directly rather than use the WebJobs abstractions `ICollector<T>` or `IAsyncCollector<T>` because I don't think these allow us to set the visibility timeout.

**Comment by mathewc** [comment]
Thanks for the detailed suggestion. Basically you're asking for a way to plug in your own IDelayStrategy (currently an internal interface) or some other interface, and have use allow that strategy to inspect/handle execution results and determine/return a delay for the next message batch read?

**Comment by JacobSnyder** [comment]
I don't think `IDelayStrategy` is what I want.  I've briefly looked at it, and it looks like `IDelayStrategy` is used to determine how long to wait before attempting to read another batch from the queue.  In the scenario I mentioned, since we already had a message in the queue, presumably there are still more messages in the queue, so WebJobs should probably immediately check for a new batch.

Rather, what I want to be able to do is specify a strategy for how long a message should be re-queued for before showing back up in the queue.  I don't really care if this is done through built-in configuration or if I can specify some kind of `IRetryPolicy` to use.  

In Azure Queues, this can be done by altering the Visibility Timeout.  Essentially what this does is specify to Azure Queues how long the message should wait before being visible in the Queue again. The snippet that I pulled out above shows that right now, the Visibility Timeout is hard-coded to `TimeSpan.Zero`, which means that the queue message will be immediately visible again in the queue.  This means that the retry strategy is implicitly just "Immediate Retry".  What I want is the ability to be able to specify different values instead of just `TimeSpan.Zero`, which would allow me to specify "Linear Backoff" or "Exponential Backoff" or some more exotic backoff scheme.

Again, whether this is supported out-of-the-box or if I supply some kind of `IRetryPolicy` interface, I don't really care.  That should be up to whatever standards you're trying to achieve with the WebJobs SDK.

**Comment by daniel-chambers** [comment]
I would also like to add my +1 to this issue. We're in the same situation as @JacobSnyder, where our WebJobs talk to an external service which may go down, and currently the WebJobs SDK only allows us to pummel it n times in a row quickly, instead of backing off and waiting a few minutes for that external service to recover. The ``IRetryPolicy`` idea @JacobSnyder discussed above would be great.

**Comment by mathewc** [comment]
As part of this, also allow minimum queue polling time to be less than 2 seconds (remove check)

**Comment by mathewc** [comment]
@daniel-chambers @JacobSnyder Guys, the changes for this are now out for CR https://github.com/Azure/azure-webjobs-sdk/pull/526

**Comment by daniel-chambers** [comment]
Thanks, I'll add some feedback to that PR. :)
