### ISSUE TITLE
System.IO.IOException while accessing WebJobsSdk.marker

### ISSUE THREAD

**Issue by philcarbone** [Azure/azure-webjobs-sdk#511]
I am getting an exception from my WebJobs (stack trace below). 

It is a Website with 2 instances (currently) and the code looks like this:
```
    public class Program {
        // Please set the following connection strings in app.config for this WebJob to run:
        // AzureWebJobsDashboard and AzureWebJobsStorage
        static void Main() {
            try {
                var host = new JobHost();
                host.Call(typeof(Program).GetMethod("Receiver"));
            }
            catch (Exception ex) {
                Console.WriteLine("Fatal Error: {0}", ex);
            }
        }

        [NoAutomaticTrigger]
        public static void Receiver() {
                ...
        }
    }
```

Stack trace:
> System.IO.IOException: The process cannot access the file 'D:\home\data\jobs\continuous\blah\WebJobsSdk.marker' because it is being used by another process.
>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
>   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
>   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<WriteSiteExtensionManifestAsync>d__2d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__f.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Azure.WebJobs.JobHost.<CallAsyncCore>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at Microsoft.Azure.WebJobs.JobHost.Call(MethodInfo method)
>   at blah.Program.Main()

**Comment by philcarbone** [comment]
Also asked question on StackOverflow: http://stackoverflow.com/questions/30192881/why-might-i-be-gettig-an-access-error-from-an-azure-webjob-using-webjobssdk-mark

**Comment by amitapl** [comment]
This file is used for analytics, we should catch all exceptions [here](https://github.com/Azure/azure-webjobs-sdk/blob/605f161fa1594bd61b076271287ebccb2d373f29/src/Microsoft.Azure.WebJobs.Host/Executors/JobHostContextFactory.cs#L353).

**Comment by mathewc** [comment]
Thanks for reporting Phil. We'll look into it and fix it.

**Comment by lczc1988** [comment]
@mathewc , Greetings! Could you please help to check the same issue happens again for customer? Thank you.

**Comment by kbdavis07** [comment]
Is there a fix for this yet? I am getting same thing.

![image](https://user-images.githubusercontent.com/5434970/48674689-f497c980-eb1c-11e8-81d9-8dedbce25836.png)


> {"State":"Processing","Timestamp":"2018-11-18T10:13:48.9223663-05:00","LastWrite":"2018-11-18T15:13:48.9098828Z","ChangeType":"Created","InstanceId":"4828","ProcessCount":1}
{"State":"Failed","Timestamp":"2018-11-18T10:13:49.0504498-05:00","LastWrite":"2018-11-18T15:13:48.9098828Z","ChangeType":"Created","InstanceId":"4828","ProcessCount":1}
{"State":"Processing","Timestamp":"2018-11-18T10:13:49.0513999-05:00","LastWrite":"2018-11-18T15:13:48.9098828Z","ChangeType":"Created","InstanceId":"4828","ProcessCount":2}
{"State":"Failed","Timestamp":"2018-11-18T10:13:49.0615031-05:00","LastWrite":"2018-11-18T15:13:48.9098828Z","ChangeType":"Created","InstanceId":"4828","ProcessCount":2}
{"State":"Processing","Timestamp":"2018-11-18T10:13:49.0624828-05:00","LastWrite":"2018-11-18T15:13:48.9098828Z","ChangeType":"Created","InstanceId":"4828","ProcessCount":3}
{"State":"Failed","Timestamp":"2018-11-18T10:13:49.0666549-05:00","LastWrite":"2018-11-18T15:13:48.9098828Z","ChangeType":"Created","InstanceId":"4828","ProcessCount":3}

**Comment by kbdavis07** [comment]
Solved it by deleting the 
![image](https://user-images.githubusercontent.com/5434970/48684943-0eb7c300-eb82-11e8-8ffb-2991ff81ff8b.png)

Container and so far had not had the issue again.
