### ISSUE TITLE
Is there any plan to support CoreClr (Asp.net vnext console apps)

### ISSUE THREAD

**Issue by sandorfr** [Azure/azure-webjobs-sdk#515]
Is there a current plan to support Asp.net vnext console apps and use the webjobs sdk ?

**Comment by mathewc** [comment]
No immediate plans. This would require the SDK and our dependencies (e.g. Azure Storage SDKs) to be compiled against .NET Core.

**Comment by sandorfr** [comment]
As far as I know, Azure storage SDK supports aspnetcore50 but I guess there are other dependencies. However, a version that only supports aspnet50 would be a good start.

The main reason behind that request is that sharing some code between asp.net 5 & a old console program is not straightforward (mainly because of dependency injection, entity framework & configuration).

**Comment by damienpontifex** [comment]
I haven't seen updates to the service bus dependencies, but the storage SDK now has a 6.1.1 preview that supports .net core.

Does this now enable a migration of the base sdk and storage components? It would be great having .NET core webjobs along with ASP.NET 5 web apps.

**Comment by rustd** [comment]
#541

**Comment by fabiocav** [comment]
Closing as the SDK has been ported and .NET Standard packages have been published to NuGet.
