### ISSUE TITLE
I'd like a table argument binding that supports a diversity of efficient operations

### ISSUE THREAD

**Issue by marklio** [Azure/azure-webjobs-sdk#517]
Table bindings are really great, but the options available are either read or write, and mixing them (with multiple arguments) leads to observation of inconsistent state (because writes don't necessarily flush partitions).  I'd love to see a binding with the following abilities:
* Add (and I'd love Insert/Replace/Merge enforcement) (It would also be nice to have "bulk background adds" as well, with an associated WaitForBackgroundAddsAsync() or something)
* Flush (to force the flushing of batch operations so queries can see consistent state)
* AsQuery (that would return something IQueryable)
* Efficient single lookup by keys (Retrieve)
* Delete by keys or set of entities
(And async versions of all :) )

This, of course, can be accomplished with CloudTable directly, but requires far more code than the other bindings, and feels wrong in the world of WebJobs SDK.

Failing this, extensibility to add my own such binding would rock.

**Comment by mathewc** [comment]
Thanks for the details. This is one of the target scenarios for the new extensibility model we'll be releasing soon. Rather than release a new table binding in the box, I'll consider adding this to the new [WebJobs.Extensions](https://github.com/Azure/azure-webjobs-sdk-extensions) repo/package. It is another great extensibility example for people to follow (customizing existing bindings) in addition to the authoring of entirely new bindings/triggers, which is what Extensions showcases thus far.

**Comment by mathewc** [comment]
@marklio @rustd Guys, I've just pushed my proposed changes supporting Table binding extensions. Any feedback appreciated. https://github.com/Azure/azure-webjobs-sdk/pull/527

**Comment by mathewc** [comment]
I've checked this extensibility in to master. @marklio So when you gonna write your fancy Table extension binding leveraging this? :) If you're really planning on writing one, it would be great to get it into the [WebJobs Extensions](https://github.com/azure/azure-webjobs-sdk-extensions) repo. What do you think? I'll update the latest alpha SDK version [on the myget feed](https://www.myget.org/gallery/azure-appservice) with these changes so they're available.

**Comment by marklio** [comment]
I'll play with it this week. I'm on vacation next week, so it's likely to spill.

Sent from my Windows Phone
________________________________

**Comment by rustd** [comment]
cool.
