### ISSUE TITLE
Dont delete from queue until success

### ISSUE THREAD

**Issue by ricardopolo** [Azure/azure-webjobs-sdk#519]
Imagine this scenario:

You have a webjob that uses a QueueTrigger.
The message arrives to the Queue and the webjob starts, but for some reason in the middle of the process the webjob stops (Like an IIS reset or something).
So the message is gone but the process is not finished by the web job.

Is it possible to do not delete the message from the queue until it succesfully ends everything?

**Comment by mathewc** [comment]
This is how it works already - queue messages are only deleted if the job function returns successfully. You can see the details [in the code here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs#L247). As you can see, we only delete the message on success.

Are you seeing a different behavior? If so please provide a repro. Otherwise we'll close this issue :)

Thanks.

**Comment by ricardopolo** [comment]
Yes I am seeing a differente behavior

I have a code like this

````cs
    public class Job
    {

        private static IContainer _container;

        public static void Main(string[] args)
        {
            _container = BaseIoCConfig.GetBaseBuilder().Build();
            JobHostConfiguration config = new JobHostConfiguration();
            config.Queues.MaxPollingInterval = TimeSpan.FromSeconds(5);
            JobHost host = new JobHost(config);
            host.RunAndBlock();
        }

        public void DeployToWebMails([QueueTrigger(Constants.WebMailDeployStartQueueName)] Guid companyId)
        {
            using (var scope = _container.BeginLifetimeScope(Cross.Constants.AutofacWebRequest))
            {
                IDeployService deployService = scope.Resolve<IDeployService>();
                deployService.StartDeploy(companyId);
            }
        }
    }
````

StartDeploy method takes about 2 minutes.
So I started the process, in the middel of this I go to the azure portal and stops the web job.
Later I start the webjob again and the process does not restart.... even after 20 minutes.

![image](https://cloud.githubusercontent.com/assets/1263856/7788677/cea81f9e-020a-11e5-97eb-e9485beb6639.png)

Any idea?

**Comment by ricardopolo** [comment]
@mathewc @rustd any comment?

**Comment by mathewc** [comment]
So your problem isn't that queue message delete processing isn't working as you expect. You're saying, the job doesn't restart or appears to be hanging?

**Comment by ricardopolo** [comment]
@mathewc I think my issue is that the queue message is not showing up again after restart the web job...

**Comment by mathewc** [comment]
When a job function begins processing a message, the message is invisible to other instaces, and we automatically set up a timer to keep updating the message visibility while your function runs. You can see the [code for this logic here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs#L256). The default visibility timeout is 10 minutes, which means once a job function starts processing a message, we'll continually ensure the message remains invisible, until the function completes (or fails).

Above, you're saying you go to the portal and kill the job while it is in process. If you do this 1 minute in, it should mean that the message will become visible again within 9 minutes or so. Can you check to see if that is happening? We do not delete the message unless the function has successfully completed. You should not see that the message is deleted. Either it's invisible for a bit as I said, or it was successfully processed and deleted.

@rustd Pranav, does what I said match your understanding?

**Comment by rustd** [comment]
you are correct. @ricardopolo can you repro it consistently?

**Comment by cloudolaf** [comment]
Can this issue be reopened? Messages reappear back on the storage queue indeed when the webjob function doesn't complete successfully. However, when you're using a POCO object as an input message and the serialization fails the message disappears from the queue, never to be found again!

**Comment by pablocastillaquintas** [comment]
I have the same problem if a webjob is restarted. The messages are missing without going to the poison queue or being retried.

Are Azure Functions more reliable?

Thanks

**Comment by mathewc** [comment]
@cloudolaf If you have a repro that shows what you're claiming, then please open a new bug. However, what I believe happens in the case you mention is that the message will be retried up to the configured retry count (default 5) after which it is moved to the poison queue. That's the designed behavior.
