### ISSUE TITLE
Read web.config XML

### ISSUE THREAD

**Issue by ricardopolo** [Azure/azure-webjobs-sdk#523]
You have a web job with some settings that you read using ConfigurationManager.AppSettings.

ConfigurationManager.AppSettings reads parameters configure through the Azure Portal. Is it possible to read the ones configured in the web.config of the website instead the the settings configure in the Azure Portal?

**Comment by davidebbo** [comment]
No, this is not easily possible. The best way to share settings between the site and the WebJob is indeed to use the Azure settings (via portal or API).

**Comment by ricardopolo** [comment]
All right.... when you use a CI Server you use something like this
http://blogs.iis.net/elliotth/web-deploy-xml-file-parameterization

It works greate for websites, apis, etc. (things that use WAP)
To create the parameters for each enviroment. Any idea how to configure the parameters using a CI server instead going manually to the Azure Portal?

**Comment by davidebbo** [comment]
If you use an ARM template, you can provision your site with app settings. So it can be automated, and doesn't have to be a manual portal step.

As an aside, note that this topic is not specific to the WebJobs **SDK** (what this project is), but would apply to any WebJob written in .NET. General WebJobs issues normally go to https://github.com/projectkudu/kudu, or the [MSDN forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview).

**Comment by ricardopolo** [comment]
Well @davidebbo... if they are WEB jobs, why dont you read the settings of the WEB site?

Would you accept a PR doing that?

**Comment by davidebbo** [comment]
It's not inconceivable that this could be done, and yes, we do take good PRs! Can you open a Kudu issue to start discussion? We're just in the wrong place here since this project is strictly about the SDK :)

**Comment by ricardopolo** [comment]
I dont think this is a Kudu thing, I thing is a Webjob SDK issue.

We need this to work even if you deploy without Kudu.. (using Appveyor or TeamCity, etc).

**Comment by davidebbo** [comment]
Kudu supports multiple features that don't relate to git publishing. The WebJobs engine is fully implemented in Kudu. The SDK, on the other hand, is an optional piece that can be used to write .NET WebJobs. But many .NET WebJobs don't use it. So yes, Kudu is the right place :)

**Comment by ricardopolo** [comment]
@davidebbo I did not know that, so WebJobs is a feature of Kudu! :)
