### ISSUE TITLE
A few tests fail if your PC has non-American date format or decimal separator.

### ISSUE THREAD

**Issue by HansOlavS** [Azure/azure-webjobs-sdk#531]
There's a few tests failing if you're on a non-American date format (like Norwegian which is what my computer has that uses 'dd.MM.yyyy HH:mm'). Also there's a few tests failing if your culture doesn't have period (.) as decimal separator. Again, Norwegian uses comma (,) for decimal separator and this trips a few tests.

**Comment by mathewc** [comment]
Please change your computer settings to use US date formats :) (Just kidding)

**Comment by HansOlavS** [comment]
LOL!

I actually made a fixture for solving this the easy way, like this:
```c#
public class InvariantCultureFixture : IDisposable
{
    private readonly CultureInfo _originalCultureInfo;

    public InvariantCultureFixture()
    {
        _originalCultureInfo = Thread.CurrentThread.CurrentCulture;
        Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
    }

    public void Dispose()
    {
        Thread.CurrentThread.CurrentCulture = _originalCultureInfo;
    }
}
```

So classes dependent on en-US culture will just do:
```c#
public class SomeTest : IClassFixture<InvariantCultureFixture> { ... }
```

**Comment by HansOlavS** [comment]
mathewc, I'm a git-noob. How do I create a pull-request for my changes? I've committed them locally on my machine. When I try to make a branch or create a pull-request to master I get 403 Forbidden.

**Comment by mathewc** [comment]
Looks like you figured it out - you create a fork and make your changes there. When it comes time to merge, I'll merge from your fork.
