### ISSUE TITLE
Remove Queue MaxPollingInterval minimum value restriction

### ISSUE THREAD

**Issue by JacobSnyder** [Azure/azure-webjobs-sdk#536]
In the current release of the Web Jobs SDK, the minimum supported MaxPollingInterval is 2 seconds.  It looks like that has [since been updated to 1 second](https://github.com/Azure/azure-webjobs-sdk/blob/fa6992b88e01fbcef251c5d1dd6e4877da8aafde/src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueuePollingIntervals.cs).

To support extremely low latency messaging, I would like to be allowed to set this value as low as I like.  If I always have messages in the queue, this isn't a problem.  But as soon as there is a gap in messages, the SDK will start to back off.  I would rather pay a little bit extra for storage transactions for the benefit of decreasing latency.  

As an amusing aside, the [price per storage transaction](http://azure.microsoft.com/en-us/pricing/details/storage/) is so low now that if I was querying a queue every 50 ms for an entire year, it would only cost $22.70 (1 year = 31536000000 ms = 630720000 requests = $22.70592)!

**Comment by Eilon** [comment]
We should talk to the Azure storage team before making this any lower. I thought they had some guidance around the minimum polling time being around 2 seconds, but a few web searches don't seem to yield anything.

Though cost of polling was part of the concern, I think that only factored into deciding the original *default* poll time (yeah, $22/year isn't terribly expensive). I thought the minimum was based on not hammering the service beyond any actual guaranteed delivery time.

(I'm happy to be totally wrong about this -- I think the internal discussion we had on this was probably 18+ months ago, and since then official guidance may have changed anyway.)

**Comment by JacobSnyder** [comment]
I'd be interested in that discussion with the storage team as well.  According to [MSDN](https://msdn.microsoft.com/en-us/library/azure/hh767287.aspx), latency for queues is 10 ms.  I originally thought this meant the latency of messages traveling through the queue, but now I'm wondering if it means the actual latency of HTTP calls to the queue.

**Comment by Eilon** [comment]
@JacobSnyder yeah I saw that latency remark too and I'm not quite sure what it means.

**Comment by mathewc** [comment]
I recently lowered the max limit from 2 seconds to 1. The choice is arbitrary, but lowering all the way to zero felt wrong. However, while the SDK tries to set limits that prevent you from shooting yourself in the foot, I agree that advanced users should be able to configure things the way they want.

One issue with the global JobHostQueueConfiguration.MaxPollingInterval is that it applies to ALL queues in the application, including our SDK host control queues. You want to configure this for your  app queue only most likely - you don't want to be hammering all queues.

**Comment by JacobSnyder** [comment]
@mathewc Aren't these conflicting goals?  You say that users shouldn't be able to set the timeout to zero, but then you say advanced users should be allowed to.

I forgot that the `JobHostQueueConfiguration` also configures the control queues.  Perhaps these queues should use sane, hard-coded defaults or be controlled via a different setting?

**Comment by mathewc** [comment]
Yes, I was pointing out that there are some existing conflicts :) There is some existing legacy (i.e. queue settings apply to ALL queues) that I've been working around with the new extensibility work. You can now create per queue processing strategies, and control many things per queue, but the SDK still currently only has a single MaxPollingInterval that applies to all queues. That could change though, it would just require a bunch of refactoring that hasn't been done yet.

**Comment by mathewc** [comment]
Lowered the limit down to 100ms in this commit: https://github.com/Azure/azure-webjobs-sdk/commit/9e773a4e91dd8af13b2f4fdebc6f8b4c8358d701
