### ISSUE TITLE
EventHub Trigger

### ISSUE THREAD

**Issue by HorizonNet** [Azure/azure-webjobs-sdk#540]
It would be great to have triggers and listeners, similar to the one's we already have for Service Bus queues and topics, for Azure Event Hub. Are there any plans to include this one, do I miss something or should it be part of the [SDK Extensions](https://github.com/Azure/azure-webjobs-sdk-extensions)?

**Comment by mathewc** [comment]
No plans as of now, but it does sound interesting :) Lots of design work needed to figure out the right model for this (partitioning strategy, etc.). I think it would make sense for this to live as part of the existing [Service Bus bindings](https://github.com/Azure/azure-webjobs-sdk/tree/master/src/Microsoft.Azure.WebJobs.ServiceBus) since Event Hubs is part of ServiceBus.

**Comment by dirkju** [comment]
+1 for this!

**Comment by stiiifff** [comment]
+1

**Comment by GaryBrouwers** [comment]
+1

**Comment by mathewc** [comment]
We'll be looking at this in the near future, thanks :) We definitely want to bring the WebJobs SDK programming model to EventHubs :)

**Comment by mathewc** [comment]
Good news guys - we're making good progress on a new EventHub trigger. Very early pull request here: https://github.com/Azure/azure-webjobs-sdk/pull/630. @MikeStall is working on this and pretty soon will be ready to get feedback from you all on the model.

**Comment by MikeStall** [comment]
The pull request is merged back to main. 
Initial documentation is at https://github.com/Azure/azure-webjobs-sdk/wiki/EventHub-support 

We're ready for feedback!

**Comment by ajedwards** [comment]
Great news. Well done and thanks @MikeStall. We will be checking this out ASAP.

**Comment by mathewc** [comment]
This is already available on our myget feed (instructions [here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)). Give it a try and give us feedback :)

**Comment by Banchio** [comment]
mmhh, after tried the myget feed, added the right using clause etc. I managed to compile my webjob using eventhub trigger but when I try to debug it I get "Could not load file or assembly 'Microsoft.ServiceBus.Messaging.EventProcessorHost, Version=0.1.0.0'" 
Where can I find this dll? I didn't find it as a NuGet... TIA!

**Comment by MikeStall** [comment]
Add nugget reference: 
install-package -id "Microsoft.Azure.ServiceBus.EventProcessorHost" -version "2.1.5"

The WebJobs.Servicebus nugget package should include this automatically, but it's missing.

**Comment by mathewc** [comment]
Our latest packages declare the nuget reference correctly (e.g. https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.ServiceBus/2.0.0-alpha-10330) but earlier ones didn't - I fixed that bug.

**Comment by Banchio** [comment]
Thanks a lot, now the reference is ok. BTW, I tried to connect to EventHub compatible endpoint of an IoTHub using the SAS key for **service** policy and dequeuing in batch way. Is this a supported scenario? unfortunately I cannot get my service bus connection string recognized.Do you have an example for ioTHub? would it be the case to update the EventHub support page to include the ioTHub example? thanks!

**Comment by Banchio** [comment]
sorry forgot to add the **Endpoint=** at the beginning of the connection string, my fault :)

**Comment by mathewc** [comment]
I'm going to close this issue, since it was to track addition of the EventHub bindings which has been completed. Let's track any bugs as new issues.
