### ISSUE TITLE
Enable/disable individual functions

### ISSUE THREAD

**Issue by iremmats** [Azure/azure-webjobs-sdk#543]
It would be super if individual functions could be enabled/disabled via the portal or via an API.

**Comment by iremmats** [comment]
Can/should be moved to project kudu...

**Comment by mathewc** [comment]
Can you please elaborate on this? Are you talking about the core WebJobs - they can already be individually enabled/disabled in the portal. Or are you talking about SDK WebJobs which run within the context of a single core WebJob (e.g. a Continuous job)?

**Comment by iremmats** [comment]
I'm referring to the SDK WebJobs. You know you start the job host and then have a couple of functions discovered. It would be cool to be able to individually enable/disable those.
This would give us more flexibility when it comes to structuring webjobs in projects. 10 webjobs in one Visual Studio Project but still controllable one by one.

**Comment by mathewc** [comment]
Its not clear to me that what you're asking for here is the same as https://github.com/Azure/azure-webjobs-sdk/issues/545. Are you talking about the same thing? Would the Singleton feature I reference in the other issue address this ask? 

That case sounds more like ensuring a job only runs on a single instance, whereas you're talking more about being able to ensure the function isn't running on ANY instances (i.e., temporarily disable).

**Comment by kamranayub** [comment]
I use app settings to enable/disable functions and jobs. They still *run* but they exit early if they see they are disabled.

**Comment by iremmats** [comment]
Cool solution. Although its a little bit messy and can be a bit confusing it works. Ty. :+1:

**Comment by mathewc** [comment]
Resolved by f958e47. Also added a sample here.
