### ISSUE TITLE
Throttle initial blob container scan

### ISSUE THREAD

**Issue by Benjimawoo** [Azure/azure-webjobs-sdk#544]
Currently if a continuous web job contains blob triggers, the initial scan at startup can be very resource intensive. I have had a few instances where a webjob is scans a container of a few thousand blobs and it sucks up all available memory on the box. This, I believe, is causing operations by the storage client to timeout - I don't think it's timing out communicating with blob storage, but rather timing out waiting for an available connection. This can them be compounded by retrying on timeout. Webjobs that contain a mixture of blob and queue triggers are particularly problematic as the queue polls start to fail because they're resource bound, and the process is restarted causing the cycle to continue.

You could put it on a bigger instance, but I suspect that would a) only be effective to a point, and b) require much more resource to be available all the time just to allow the job to start, although resource requirements whilst running may be much lower.

**Comment by mathewc** [comment]
We just discovered and fixed a bad bug in Blob scan continuation token handling (see https://github.com/Azure/azure-webjobs-sdk/commit/2b82dafd098ca5f4a8d97db7899b5e84992c28c3). Do you think this might be the bug you're running into? We had another customer with hundreds of thousands of existing blobs on startup scan, and they were seeing the same behavior - the initial scan never completed. They verified the fix by pulling from our myget nightlies. If you'd like to try the fix and confirm it fixes things for you as well, I can point you to the myget feed.

**Comment by Benjimawoo** [comment]
That could well be it - I'll take a look.

Am I right in thinking that that bug would only manifest itself if there were > 1000 blobs in the container when the scan starts, but would run fine below that?


On 20 Jul 2015, at 18:05, Mathew Charles <notifications@github.com<mailto:notifications@github.com>> wrote:


We just discovered and fixed a bad bug in Blob scan continuation token handling (see 2b82daf<https://github.com/Azure/azure-webjobs-sdk/commit/2b82dafd098ca5f4a8d97db7899b5e84992c28c3>). Do you think this might be the bug you're running into? We had another customer with hundreds of thousands of existing blobs on startup scan, and they were seeing the same behavior - the initial scan never completed. They verified the fix by pulling from our myget nightlies. If you'd like to try the fix and confirm it fixes things for you as well, I can point you to the myget feed.

-

**Comment by mathewc** [comment]
The default Azure Storage batch size for blobs is 5000 (maxResults parameter to CloudBlobContainer.ListBlobsSegmentedAsync), and that's what we're using. So I'd only expect this bug to manifest if you're exceeding that limit (since the ListBlobsSegmentedAsync will continue to return a ContinuationToken and the previous code would then loop forever, since it wasn't following the tokens properly.

**Comment by Benjimawoo** [comment]
That sure sounds like the behaviour and the fix. If some else has already verified I'll clothe issue.

**Comment by mathewc** [comment]
Thanks for taking the time to report. If you decide you'd like to try the fix yourself, it's available here: https://www.myget.org/gallery/azure-appservice.

**Comment by Benjimawoo** [comment]
Thanks for getting back - Got it, tested it, deployed it. It was the same issue, and is indeed fixed.

**Comment by mathewc** [comment]
Thanks for taking the time to confirm :)
