### ISSUE TITLE
Allow continuous jobs to stop themselves from running

### ISSUE THREAD

**Issue by AlanParr** [Azure/azure-webjobs-sdk#545]
I've got 3 site instances located in different data centers but only want certain jobs to run on one of these instances rather than all of them. I currently stop them manually in the portal but it would be great if there was a way I could explicitly signal Stop or Disabled based on my own logic. I found the Stop() method on WebJobHost but this fails if Start() has not been called and continuous jobs use RunAndBlock(). Just returning causes the job to be continually restarted.

Something like:

if(mycondition) {
 host.Disable();
}

Edit: This is possibly related to #543

**Comment by mathewc** [comment]
I'm thinking this requirement if I understand you correctly will be addressed by [the Singleton feature](https://github.com/Azure/azure-webjobs-sdk/issues/513) we're working on, which will be released in the upcoming v1.1.0 release. That feature will allow you to declaratively annotate your job function, and the runtime will ensure that the function only runs on a single instance. Is this what you're looking for?

Behind the scenes that feature will use blob leases, and those blob leases will work globally across all datacenters, if you're using the same storage account for all.

**Comment by AlanParr** [comment]
In my case, the instances are not on the same server or region. One is in West Europe, one is in the US, and one is in Asia and they all use Queue or Service Bus triggers.
It isn't so much a case of wanting to stop them running at the same time, as in the Singleton case, I need to a way to stop them running at all.

As I use git deployment, they all get set up to be active by default, ideally I want to check a config setting in the webjob's constructor and Stop the job as if it were stopped from the Azure portal. This prevents the job from running when the instance is first created and performs it's first deployment from git. It also prevents accidental running of the job from the portal by an administrator.

An acceptable alternative to this would be if adding a config setting to the site, such as RUNWEBJOBS=false prevented all jobs from running without any code changes to the jobs themselves, although I can see cases for myself and other users where you might want some jobs to run and not others, so perhaps just adding a Stop mechanism to the JobHost is a more flexible approach.

**Comment by mathewc** [comment]
I see.One thing that you could do now is to use the existing TypeLocator mechanism. Basically define your own wrapper instance like this:

        public class SelectiveTypeLocator : ITypeLocator
        {
            private readonly ITypeLocator _innerLocator;

            public SelectiveTypeLocator(ITypeLocator innerLocator)
            {
                _innerLocator = innerLocator;
            }

            public IReadOnlyList<Type> GetTypes()
            {
                List<Type> types = new List<Type>(_innerLocator.GetTypes());
                // TODO: filter the list of types in any way you choose
                return types;
            }
        }

Then you would new one of these up and set it on your JobHostConfiguration like this:

        JobHostConfiguration config = new JobHostConfiguration();
        config.TypeLocator = new SelectiveTypeLocator(config.TypeLocator);

That would allow you to control the set of jobs in a fine grained manner. E.g., you could inspect all types, and not return/remove any jobs you don't want to run. Would something like that work for you?

However, if for a particular Job/JobHost you don't want ANY SDK jobs to run, I don't think you'd want to use this approach. Even if you were to use this mechanism to return an empty set of Types (so NO jobs would be running) - you don't want a continuous webjob running that isn't doing anything, right? I.e. it seems better for you to disable the job completely in the portal at that point, or not deploy it there in the first place.

**Comment by AlanParr** [comment]
I think a mixture of your suggested approach above and just turning the jobs off in the portal is probably going to be the best approach.
Your suggestion fulfils the requirement of preventing accidental running of the jobs. When I deploy to a new instance, I need to remember to log on and turn off the jobs, which isn't the end of the world.
You're absolutely right that it would be a terrible idea to just have the jobs run and exit.

Thankyou for your thoughts. I still think there is possibly some value in having an instance that can be set to not run any jobs, but I am thinking that this may be better done as part of the git deployment in Kudu to prevent them from being deployed, rather than a mechanism for them to self-stop.
