### ISSUE TITLE
Changing logging level for function started/completed to Debug

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-webjobs-sdk#557]
Right now logging happens at the Info level. Could that be reduced to Debug so that I don't see as much noise in my logs? I'm using Azure's application diagnostics logging to log to table storage and there are lots of "Executing 'MyJob' because service bus message detected" messages.

**Comment by mathewc** [comment]
In the current v1.0.1 bits, these logs don't have a verbosity - they're just Console logs. Are you referring to the changes I just checked in yesterday for TraceWriter? (in ConsoleTraceWriter?)

TraceLevel doesn't include a "Debug" level.

**Comment by mathewc** [comment]
I've added a new TraceLevel setting that will now allow you to control the TraceLevel for Console outupt. The default remains TraceLevel.Info, however you can now change this to TraceLevel.Warning/Error if you don't want to see the above informational logs, the JobHost starting/stopping logs, etc., or TraceLevel.Verbose if you want to see everything.

See [this commit](https://github.com/Azure/azure-webjobs-sdk/commit/2e8cc823c6c6cd2d10fda6d80a0ffb3cc2de8fb4) for details.

**Comment by BrianVallelunga** [comment]
Great. Thanks!
