### ISSUE TITLE
Request for modifications to BindingContract for helping with creating from a type object

### ISSUE THREAD

**Issue by JasonHaley** [Azure/azure-webjobs-sdk#561]
I'd love to see the equivalent functionality of the BindingDataProvider, IBindingDataProvider in a public class (from ServiceBus extension).

The Micorsoft.Azure.WebJobs.Extensions.Framework.BindingContract class comes close in nature, but it seems the functionality to create the contract from a given type is a useful bit of code (and needed for arbitrary argument types).  For my trigger (https://github.com/JasonHaley/Redis.WebJobs.Extensions)  I wanted to be able to utilize any json serializable object – so I borrowed the PropertyHelpers, BindingDataProvider and IBindingDataProvider from the ServiceBus extension implementation.

I am working on factoring out the code that has been borrowed (as I learn more about how things work) but it seems the contract creation from a Type would be a useful extension of the BindingContract class and exposed for all to use … and so I don’t have to write a simplified version of the same type of code 

**Comment by mathewc** [comment]
This has been addressed by commit https://github.com/Azure/azure-webjobs-sdk/commit/762e2739093da93dd17821e0a4f1ca719e100221.

I actually ended up needing the exact same functionality you did for a new WebHookTrigger binding I just added to the Extensions repo. You can [take a look at that binding](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.WebHooks/Bindings/WebHookTriggerBinding.cs#L36) to see how I handled adding POCO binding using BindingDataProvider from the core SDK. Here's [an example function](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Samples/WebHookSamples.cs#L38) showing the binding + model binding.

**Comment by mathewc** [comment]
@JasonHaley Give this a try and let me know. I've successfully used the updates in the WebHookTrigger binding (link above).
