### ISSUE TITLE
Make StorageConnectionString optional

### ISSUE THREAD

**Issue by GPetrites** [Azure/azure-webjobs-sdk#567]
With the TimeTrigger and FileTrigger extensions, there is no need to have a storage account for a WebJob to run.  Requiring a storage account is an unnecessary burden, especially if the WebJob SDK is used to write code to run on host servers outside of Azure.

**Comment by mathewc** [comment]
Can you please move this issue in the https://github.com/Azure/azure-webjobs-sdk-extensions repo where those extensions live? Thanks :)

**Comment by GPetrites** [comment]
The issue is with the WebJob SDK as this is the repo which requires StorageConnecitonString to have a valid value.  I only mention the extensions as they provide a reason for leaving this blank.

Method GetAcccountAsync in DefaultStorageAccountProvider throws an exception during JobHost startup if StorageConnectionString is blank, and there is no way to prevent this outside the SDK.

I believe the fix would be to change:

            // Only dashboard may be null when requested.
            if (account == null && connectionStringName != ConnectionStringNames.Dashboard)

to:

            // Only dashboard and storage may be null when requested.
            if (account == null && connectionStringName != ConnectionStringNames.Dashboard && connectionStringName != ConnectionStringName.Storage)

**Comment by mathewc** [comment]
Yes, the Files trigger/binding extensions don't require a storage account. Timer actually does now use storage - it uses the Singleton feature (blob leases) to ensure that only a single instance of a particular timer function is running across scaled out instances. I agree with you in principal that if you're only using aspects of the SDK that don't require storage, then it shouldn't be required. However, currently most of the SDK bindings use storage in some way, but with the new extensibility model allowing new types of bindings (e.g. Redis, SendGrid, Files) it will be more common for there to be interesting things to do w/o storage. I'll give it some thought. We'd want a good error message for when you attempt to use some aspect of the SDK/Extensions that require storage.

**Comment by mathewc** [comment]
Retitling this bug, since this issue came up again. In the latest case, no storage account was provided, and a Timer trigger function failed with a null ref exception [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs#L333).

**Comment by fwd079** [comment]
Hi, is this milestone reached at all? Thanks.

**Comment by mathewc** [comment]
Closing this

**Comment by mathewc** [comment]
Yes, in the latest builds, you can explicitly set JobHostConfiguration.StorageConnectionString/DashboardConnectionString to and you can run w/o a storage account. Of course if you're using any bindings that require storage, you'll get errors.
