### ISSUE TITLE
Azure Webjob Logging beyond 8 hours

### ISSUE THREAD

**Issue by NVentimiglia** [Azure/azure-webjobs-sdk#568]
I have a web job hosted on azure. I noticed that the logging system only retains logs for 8 hours. I have hooked up storage but that did not help. I feel I may be doing something wrong. 

Here is my program.cs

`````
 /// <summary>
    /// https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-get-started/
    /// </summary>
    class Program
    {
        // Please set the following connection strings in app.config for this WebJob to run:
        // AzureWebJobsDashboard and AzureWebJobsStorage
        static void Main()
        {
        
            //Call static method which does work. Work lasts 7 seconds or so.
             

            // If we go beyond this the WebJob will fail, says 120 second timeout.
            return;

            var host = new JobHost();           
            host.RunAndBlock();
        }
    }
`````

As you can see one big red flag is my use of JobHost. Whenever I put my code in functions.cs and run the JobHost it starts fine, but, the application ceases to work correctly. It just runs for 120 seconds, executing no desired code, and then throws an exception I read in the integrated logging.

**Comment by mathewc** [comment]
What error(s) are you seeing in your logs? WebJobs file system logging is discussed here: https://github.com/projectkudu/kudu/wiki/Web-jobs. You're using the SDK, so you also have Dashboard logs. What do they show?

Can you provide a repro for this (e.g. in a repository or something you can point us to?)

Also, check out the WEBJOBS_IDLE_TIMEOUT setting on the page I linked to above. That timeout value is 2 minutes for triggered jobs. If you're using the SDK, usually you'll be using a Continuous job. However, if you want to use the SDK with a triggered job, you can increase that WEBJOBS_IDLE_TIMEOUT value (it's in seconds).

**Comment by NVentimiglia** [comment]
Right now, no errors because I have a return statement. I`m just not sure why my logs are only being saved for 8 hours. I`ve hooked up Azure Storage, shouldn't my logs be persisting ?

![logexample](https://cloud.githubusercontent.com/assets/125889/9856469/ca3a0766-5ac9-11e5-9e1f-0e8533a33bd6.png)

When I remove the return statement, the thing does crash. From what I remember it was something about the job going beyond 120 seconds. I do not think extending the lifetime of the job is a good idea because the job should not be running for 120 seconds. It smells like a symptom of another problem. That said, I will recreate the exact error message and get back to you tonight.

**Comment by mathewc** [comment]
Also, provide details on your job - is it Continuous or Triggered? Looks like you're using the SDK in a triggered job. In that case, you shouldn't be using host.RunAndBlock(), you should be returning after you invoke your function via JobHost.CallAsync (make sure you await for completion).

RunAndBlock is only designed for us in Continuous jobs.

**Comment by rustd** [comment]
@NVentimiglia We need more details. Please reopen with more details.

**Comment by NVentimiglia** [comment]
@mathewc I dont understand. I am following the example.

https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/HelloWorld/Program.cs

CallAsync requires some reflection parameters, it does not smell right.

**Comment by mathewc** [comment]
I mentioned CallAsync because I thought that was what you were doing based on your "Call static method which does work" code comment earlier above.

What kind of job function are you trying to run? Generally when using the SDK you will be running your code in a Continuous WebJob ([as detailed here](https://github.com/projectkudu/kudu/wiki/Web-jobs)). As in the HelloWorld sample you linked to above, you will call RunAndBlock which will keep the SDK JobHost alive running your function.

Please provide details/code for the function you're having problems with so we can help. Thanks :)
