### ISSUE TITLE
Unable to specify SharedAccessSignature connection strings for Dashboard / Storage connection strings

### ISSUE THREAD

**Issue by dxlusby** [Azure/azure-webjobs-sdk#569]
Using WebJobs SDK in an Agented model with installations across tenants where distribution of dashboard / storage connection string account keys is not desirable.  SAS Signatures with container-limited permissions to the hosts and output containers (ideally write-only) is preferred, but host attempts to retrieve service metadata using the SAS Keys.

Requested Fix: If possible, make dashboard / storage connection strings optional (accepting that this will not produce logging or coordination among hosts?

Would the storage emulator function as a workaround?

Sample Fiddler Trace from .RunAndBlock()
GET https://SCRUBBED.blob.core.windows.net/?sv=2014-02-14&sr=c&si=writeOnlyPolicy&sig=SCRUBBED&api-version=2014-02-14&comp=properties&restype=service HTTP/1.1
User-Agent: WA-Storage/4.2.1 (.NET CLR 4.0.30319.42000; Win32NT 6.2.9200.0)
x-ms-client-request-id: 12f1f9b1-92c2-464b-b702-d1336b92007a
Host: acpstoragedml.blob.core.windows.net
Connection: Keep-Alive

**Comment by mathewc** [comment]
If you've provided no Dashboard/Storage connection strings, then where would the SDK go to perform your storage operations? Need more information on your scenario, and what you're trying to accomplish.

Note: We recently added Multiple Storage Account support. See commit: https://github.com/Azure/azure-webjobs-sdk/commit/d2040232492494a21d6955088582fd63f8bbd206 as part of the up coming release. It allows you to specify connection strings per parameter/method/class.

**Comment by dxlusby84** [comment]
The scenario uses service bus triggers to execute code in the clients
environment.  While no storage operations are required, the SDK requires a
dashboard and storage connection string before it discovers functions

**Comment by mathewc** [comment]
I see. I believe what you're asking for is covered by existing issue https://github.com/Azure/azure-webjobs-sdk/issues/567 "Make Storage connection string optional". We need to make this optional for people who won't be using Azure Storage features (e.g. ServiceBus, and some of the new Extension triggers/binders like SendGrid, Redis, Timer, Files, etc.)

**Comment by mathewc** [comment]
Closing this because #567 was addressed.
