### ISSUE TITLE
Add support for receiving Service Bus messages in batch

### ISSUE THREAD

**Issue by andrewrimmer** [Azure/azure-webjobs-sdk#570]

**Comment by rustd** [comment]
For reference, read this: http://geekswithblogs.net/asmith/archive/2012/04/10/149275.aspx

Implementing most integration patterns with webjobs and ServiceBus is pretty straight forward. For example, splitting is very easy with ICollector as output. 
 But Aggregating is kind of impossible. What I would like is to have a ServiceBusTrigger support some kind of combination of SessionId/Correlation id and a counter.
 Imaging sending 10 messages with same SessionId and property NumberOfMsgInSession = 10. My webjob with ServiceBusTriggerWithSessionId(queue) would not start until all 10 messages can be read from the queue/subscription.

**Comment by grbinho** [comment]
Hi guys, are there any updates on this one?

**Comment by snboisen** [comment]
Oh yes, having automatic batching with WebJobs somehow using MessageReceiver.ReceiveBatch / MessageReceiver.ReceiveBatchAsync and then invoking a custom WebJobs function with a collection typed parameter for the messages would be great!

**Comment by iremmats** [comment]
Agree!

**Comment by JasonBSteele** [comment]
I would love to see a solution for this too

**Comment by scramsby** [comment]
See #787 for a new request to support _sending_ messages in batches as well.

**Comment by christopheranderson** [comment]
Closing in favor of #1024 since it has a more detailed request (though this one is earlier)
