### ISSUE TITLE
Webjob Logging Retention Policy

### ISSUE THREAD

**Issue by NVentimiglia** [Azure/azure-webjobs-sdk#574]
I would like to retain my log data beyond 7 hours. Right now, when I log into the WebJob details 'website' I only see 7 hours of logs.

I have configured my webjob to use Table and Blob logging from the application manager. When asked, I set my detention policy to 14 days. After all is said and done my azure webjob 'website' only retains logs for 7 hours. 

![logsettings](https://cloud.githubusercontent.com/assets/125889/10182333/da5bcfca-66d7-11e5-8e75-9db3e92ccc50.png)

**Comment by mathewc** [comment]
This logging is not WebJobs SDK related - it's part of the core WebJobs functionality. Can you please move this issue over to https://github.com/projectkudu/kudu/issues? We'll look into it, thanks.

**Comment by NVentimiglia** [comment]
Thanks !
