### ISSUE TITLE
WebJobs + Application Insights = Not Working

### ISSUE THREAD

**Issue by advancedrei** [Azure/azure-webjobs-sdk#575]
I have a WebJob I've built using the WebJobs SDK. I also have the following NuGet packages installed:
- Microsoft.ApplicationInsights
- Microsoft.ApplicationInsights.Agent.Intercept
- Microsoft.ApplicationInsights.DependencyCollector
- Microsoft.ApplicationInsights.PerfCounterCollector
- Microsoft.ApplicationInsights.WindowsServer
- Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel

I have my InstrumentationKey in a config transform as follows:
```
<ApplicationInsights xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform" xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <InstrumentationKey>MYKEYHERE</InstrumentationKey>
</ApplicationInsights>
```
And have confirmed that transform works properly in production. I have also insured that no web-specific Application Insights modules are in the config file.

The Main function looks like this:
```
        internal static void Main()
        {
            try
            {
                _container = ComposeApplication();
                _telemetry = _container.Resolve<TelemetryClient>();
                _telemetry.TrackEvent("MessageBus: Console Started");

                //RWM: A single storage connection for everything.
                var storageConnection = ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString;
                var jobsConfig = new JobHostConfiguration(storageConnection);
                jobsConfig.Tracing.ConsoleLevel = TraceLevel.Verbose;
                jobsConfig.Queues.MaxDequeueCount = 1;
                new JobHost(jobsConfig).RunAndBlock();
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Exception: {ex.Message} \nCallStack: {ex.StackTrace}");
                _telemetry.TrackException(ex);
                _telemetry.Flush();
                Thread.Sleep(7000);
            }
        }
```
Given that setup, I should have at least 1 event tracked. Instead, I have 0 data points stored in this particular Application Insights instance.

So, is this a scenario that works, and I'm just missing something? Or does there need to be a custom WebJobs TraceListener written to support WebJobs? I am happy to provide any assistance in tracking this issue down. Thanks!

-Robert McLaws, .NET Framework MVP

**Comment by davidebbo** [comment]
I wonder if the issue can be generalized as: does App Insight work in a console exe (as opposed to a Web App), regardless of SDK use. Does it work for you when running on your local machine?

I found this comment from @JoshuaWeber on [this post](https://azure.microsoft.com/en-us/documentation/articles/app-insights-get-started/):

> You can be successful logging telemetry from a console application. We have some documentation that is closer to this scenario. https://azure.microsoft.com/en-us/documentation/articles/app-insights-windows-desktop/. You should be aware that this approach recommends our the core SDK. When using core SDK you won't get any telemetry collected automatically, you will need to code the telemetry you want sent.

Seems that post has some good information related to Console apps.

**Comment by advancedrei** [comment]
So apparently the Flush() command I added yesterday actually worked, but the TelemetryClient picked up another InstrumentationKey and was reporting the data somewhere else.

The problem still remains that a) Application Insights does not have a built-in way to initialize telemetry collection for console apps, and b) There needs to be a Application Insights TraceWriter for the Azure WebJobs SDK. I'm working on both, and will submit them to the AI team when I'm finished. Since this is not a WebJobs problem directly anymore, I'm gonna close this out. But thanks for your help!

**Comment by advancedrei** [comment]
For anyone that reads this and is interested, I published my helpers to simplify this scenario, and posted instructions here: https://github.com/advancedrei/ApplicationInsights.Helpers/wiki. Thanks!

**Comment by mathewc** [comment]
Cool. Please do note that JobHostTraceConfiguration.Trace has been changed to a Collection in the latest builds (available on the nightlies feed) to facilitate greater extensibility. You can add your custom tracers to the collection. Just a heads up on the changes you'll see when we release the final v1.1.0 packages in the coming weeks.

**Comment by advancedrei** [comment]
Yeah, I'm looking forward to the final release. I'll keep an eye on that, thanks!
