### ISSUE TITLE
Deploy webjob via git

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-webjobs-sdk#577]
I'm trying to deploy my webjob via git, because i've got a lot errors about path too long
But i did'nt figure out how to do it.

any guess??
Thanks

https://github.com/projectkudu/kudu/wiki/Web-jobs#deployment

**Comment by mathewc** [comment]
Please see if issue http://github.com/projectkudu/kudu/issues/1239 in the Kudu repo is the same issue you are experiencing. It sounds like it is. If so, please add your details to that bug.

Git deployment is not part of the WebJobs SDK repository - it's part of Kudu WebJobs core. Thanks.

**Comment by mauricionr** [comment]
Thanks @mathewc
