### ISSUE TITLE
Dynamic Enable/ Disable a function

### ISSUE THREAD

**Issue by rustd** [Azure/azure-webjobs-sdk#578]
have an option in the dashboard to disable a function.
Implementation
We could write to Storage the list of active functions. When a user clicks disable in the dashboard, we update the storage settings and disable the listener for this function.

**Comment by mathewc** [comment]
More implementation notes: Settings for whether each function is currently enabled/disabled could live in Azure Storage. When a user clicks disable in the Dashboard, we update the flag in storage for that function, and at the same time the currently active listener for that function is also disabled in the running host so it will stop immediately. It won't start running again until enabled.

In addition to this Dashboard mechanism, I can also see it being useful for us to support an **EnabledAttribute** that could be applied to functions. The attribute would allow a app setting / value to be specified, so that on startup, the function will only run if that appsetting / value exists. Thus, jobs can be enabled/disabled by changing settings in the portal. The setting change will cause the Web App host to restart.

**Comment by iremmats** [comment]
Please implement this. :)

**Comment by mathewc** [comment]
The proposal is to add a **DisableAttribute** that can be used to conditionally disable functions as follows:

* Can be applied at the Parameter/Method/Class level
* Only affects triggered functions
* [Disable("setting")] - If a config/environment value exists for the specified setting name, and its value is "1" or "True" (case insensitive), the function will be disabled.
* [Disable(typeof(DisableProvider))] - custom Type declaring a function of signature "bool IsDisabled(MethodInfo method)". We'll call this method to determine if the function should be disabled.
* Only triggered functions are affected.
* This is a startup time only check. For disabled triggered functions, we simply skip starting of the function listener.

Does that meet your needs @iremmats?

**Comment by kamranayub** [comment]
> This is a startup time only check.

So in a continuous job, let's say a queue processor, could I update a setting in Azure and it would disable it (or does changing a setting in Azure already auto-restart continuous webjobs?)?

That would need to work for this to be useful for continuous jobs. Right now I can check for the presence of an app setting myself when the function is triggered.

**Comment by mathewc** [comment]
Yes - updating a setting causes a restart of your continuous WebJob. This is just behavior inherited for all Web Apps - when you update settings, your WebApp needs to be restarted for those update to take effect.

So in this context, you have the ability to toggle individual jobs on/off depending on how you map the attributes to settings. Might be 1:1, 1:many, etc.

Checking for the setting yourself when the WebJob is triggered is very sub optimal - when I heard you were doing this as a workaround, I decided to implement this so you wouldn't have to do that :) With what you have now, you still have a listener that is continuously polling the queue, pulling messages off and starting the whole processing pipeline just to hit your code to ignore the message.

**Comment by kamranayub** [comment]
Excellent, then this will totally meet my use cases! :+1:

**Comment by iremmats** [comment]
I think this solves my uses cases too. Excellent work, really appreciate how easy it is to get in touch with you guys :+1:

**Comment by mathewc** [comment]
Resolved by https://github.com/Azure/azure-webjobs-sdk/commit/f958e470712f2bbeb65c8546ad3698e4064f2ee9. Also added a [sample here](https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/MiscOperations/Functions.cs#L104).

**Comment by phoxha** [comment]
Thank you for this.

When using [Disable("Disable_Queue")] I can't use an app setting or constant but need to do a DB look up (run a method) to see if queue is set to active by some outside process. How can I run a method here since this only uses a constant? Please give me a sample.

**Comment by kamranayub** [comment]
You may just need to do complex logic in the method. Exit if you don't want
it to run. I think you can reset the dequeue count to prevent dequeuing
when you exit.

**Comment by phoxha** [comment]
Thanks. What do you mean by "reset the dequeue count".

It looks like [Disable(typeof(DisableProvider))]  only fires on app start so it acts the same as using appsettings. I was hoping that it would allow me to stop AND restart the queue pump based on some dynamic value without having to restart the application. Am I wrong in saying that the solution provided does not really allow you you to stop and restart the queue pump. Once the queue has been disabled, you it cant really restart on its own based on some dynamic value, correct?
