### ISSUE TITLE
Invoking a function or replaying with different parameters on a TriggeredWebJob does not show the queued function nor does it execute it

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-webjobs-sdk#583]
I have some triggered web jobs that run on a schedule. I wanted to replay a failed run so I tried Replaying the function call but changed the parameters to some test values. It said the function was queued so I left the page and went to view the Function Invocation Log and it did not show up there. It hasn't since. I even POST'd to the Kudu endpoint to trigger a run and it did trigger a run, but it did not run the function I queued.

Is this a bug? Seems like Kudu should start the job host and execute the requested function if I replay it on a triggered web job.

I think I might be getting confused with runs vs. functions. I assumed that running a function that's part of a triggered web job would run the job with the parameters I specified. But I think I will have to use the `WEBJOBS_COMMAND_ARGUMENTS` variable and translate the args into the parameters I pass to the function itself.

**Comment by kamranayub** [comment]
This works if I POST to the API and provide an arguments string that I parse and override the functional call params. However, just a note, it appears that a "+" sign is stripped when it gets to the webjob.

For example:

```
POST https://site.scm.azurewebsites.net/api/triggeredwebjobs/Job/run

Querystring: ?arguments={now:"10/16/2015 4:07:23 PM +00:00"}
```

The webjob output:

```
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Could not convert string to DateTimeOffset: 10/16/2015 4:07:23 PM  00:00. Path 'now', line 1, position 35.
```

Notice how the `+` sign is missing.

**Comment by mathewc** [comment]
Can you clarify: are you talking invoking jobs using the WebJobs SDK TimerTrigger from the WebJobs Dashboard? Replay/Invoke from Dashboard works fine - I just tried it. The string you enter actually gets ignored.

It's unclear to me why you're talking about the api/triggeredwebjobs/run API. Perhaps your issue is a core WebJobs issue (https://github.com/projectkudu/kudu)?

**Comment by kamranayub** [comment]
I'm talking about invoking function on this screen:

![image](https://cloud.githubusercontent.com/assets/563819/10556203/ce66ecae-7442-11e5-8f1f-324b975cca6f.png)

When I fill out the parameters:

![image](https://cloud.githubusercontent.com/assets/563819/10556218/1f56038e-7443-11e5-95a9-837df9364d46.png)

It says it's queued but doesn't show anything in the UI nor does it ever execute anything, even when the job runs next time its scheduled.

![image](https://cloud.githubusercontent.com/assets/563819/10556219/3bc5126c-7443-11e5-9ff4-3018e800a75a.png)

See, no invocation logged:

![image](https://cloud.githubusercontent.com/assets/563819/10556225/5a3eb9f0-7443-11e5-9f92-2bc5da76f107.png)

It just disappears into the ether.

I talked about triggering through API because you can't trigger a job run from the UI, so I tried triggering a job run but it didn't do anything--the function I queued was never executed.

**Comment by mathewc** [comment]
The key is the warning message shown in your photo "The host is not running". This means that the job host for the original invocation **is not running** - the request is successfully queued, but since the host is not running, the function will not be run until it is started back up.

If you start the host, things will work. If you're using the WebJobs SDK, you should be running your JobHost in a **continuous web job** with AlwaysOn enabled. It sounds like you're trying to run it as a triggered job, which isn't going to work for you. That's probably why your host is not running.

**Comment by kamranayub** [comment]
Why even allow queuing triggered job functions then? It was confusing. I understand the host needs to *run*, but even when it did (i.e. triggered), it didn't do anything--it's not clear it's only meant to be used with continuous jobs. If it is, it should say so and not even allow it in the first place. 

As a workaround I've just used the WEBJOBS_COMMAND_ARGUMENTS to do the same thing and trigger from the API, so problem solved--but it was a sub-optimal UX. It would be nice if you could just run triggered jobs from the dashboard as well and pass arguments.

**Comment by mathewc** [comment]
@rustd @christopheranderson For the doc questions

I'd need to see your triggered job startup code - are you calling one of the JobHost.Run* methods? That's what starts the "message pumps" and only then would the queued invocation messages get picked up. Also there would be some delay as all the various queue watchers etc. start up, so if your triggered job finishes before that is complete, then the message might not get picked up in time. As I said, usually you use the SDK in a **continuous** WebJob. All our various [tutorials](http://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-get-started), etc. indicate that. However, I do agree that our fragmented documentation could be improved/consolidated.

Another option you might consider is taking a look at the new [WebHooks support](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/WebHooks-Walkthrough) that was recently added. The last section on that walkthrough mentions you HTTP invoke scenario. However, that would also require you running as a continuous WebJob.

Yes, the fact that there are 3 ways to schedule is confusing. However, you also have lots of options :) Support for the external Azure scheduler came first long ago, and is useful in cases where you're not running your job as continuous, or are not using the WebJobs SDK. If you're already running a continuous WebJob, then for cost/simplicity it makes sense to allow the schedule to run internally in the job - no need for an external service. If you're not using the WebJobs SDK (e.g. you want to schedule your PS script) then you can use the settings.job mechanism. However if you're all in on the WebJobs SDK you can use the convenient and easy to use TimerTrigger. I would recommend that.

**Comment by kamranayub** [comment]
Thanks for explaining, that helps.

I'm all in with the SDK because I like all the features it provides, I have a configurator class that configures all my jobs in a standard way and wraps all my executions in some code that handles exceptions gracefully and all that.

For triggered jobs, I do it like this:

    host.Call(typeof(Functions).GetMethod("MyJobFunction"));

and

    [NoAutomaticTrigger]

Since it handles injection and all that for me.

I will explore switching to continuous job(s) and a timer trigger. Conceivably I could combine all my jobs into a single one then. I kind of like the separation this provides right now, though.

**Comment by mathewc** [comment]
Yeah, if you're only calling host.Call, none of the queue listeners are being started, which is why your dashboard invoke isn't working.

You mentioned error/exception handling. We just added some new error monitoring/alerting functionality - see [Error Monitoring](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/Error-Monitoring).

**Comment by devsandeeps** [comment]
- [ ] 

- 

- [ ] 

- 

- 

1.
