### ISSUE TITLE
Strange issue when swapping: data swaps in Kudu console

### ISSUE THREAD

**Issue by kamranayub** [Azure/azure-webjobs-sdk#586]
So this is an interesting issue.

When I perform a swap in Azure, I noticed that the job data that Kudu displays in the web jobs dashboard *also* swaps.

Case in point.

On my dev slot, I issued a triggered job run:

![image](https://cloud.githubusercontent.com/assets/563819/10597302/0e3d0e54-76b3-11e5-9334-3d3470341a4e.png)

Take note of the run time: Tue, 20 Oct 2015 03:36:42 GMT

Then, after I swapped, I see that **exact run** in my production slot's dashboard:

![image](https://cloud.githubusercontent.com/assets/563819/10597312/27cb2e46-76b3-11e5-8d27-2f5674e4fe2e.png)

To prove it, I also can issue an API request against the production slot and see my run ID:

```
{
  "id": "201510200336425903",
  "name": "201510200336425903",
  "status": "Success",
  "start_time": "2015-10-20T03:36:42.5903978Z",
  "end_time": "2015-10-20T03:37:02.8328967Z",
  "duration": "00:00:20.2424989",
  "output_url": "https://xxx.scm.azurewebsites.net/vfs/data/jobs/triggered/QueueUpdates/201510200336425903/output_log.txt",
  "error_url": null,
  "url": "https://xxx.scm.azurewebsites.net/api/triggeredwebjobs/QueueUpdates/history/201510200336425903",
  "job_name": "QueueUpdates",
  "trigger": "External - Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"
}
```

It returns a 404 if I try the same API call against the dev slot.

(I didn't include the URLs but you'll have to trust me)

I assume each time I swap, it's swapping the dashboard storage connections too. I double checked my own connection strings (AzureWebJobsDashboard and AzureWebJobsStorage) and they are Slot Settings and remain the same after a swap.

**Comment by mathewc** [comment]
AppSettings also also move with a swap by default (see  [this post](https://azure.microsoft.com/en-us/documentation/articles/web-sites-staged-publishing/)). That post also describes how to make particular app settings "slot sticky".

**Comment by kamranayub** [comment]
All my settings are slot settings, so nothing moves in my case. What does the dashboard use?

-----Original Message-----

**Comment by davidebbo** [comment]
The SDK uses the storage account, but the base WebJobs feature uses the file system to store run history. Specifically, look under `D:\home\data\jobs\triggered` using Kudu Console. There is currently no way to make this sticky, so it will indeed move back and forth along with the rest of the site files as you swap.

**Comment by kamranayub** [comment]
Thanks, that makes sense--at least I know why now.

**Comment by kamranayub** [comment]
@mathewc @davidebbo is it possible to provide an option (opt-in) to store history in blob/table storage using the connection strings already available? I'm sure it's file based by default to save some cost? I'd rather opt-in to better swappability.

**Comment by davidebbo** [comment]
Currently it is not supported, but I agree it might be an interesting option for the future. Note that this is part of Kudu and not the WebJobs SDK. Can you open issue on https://github.com/projectkudu/kudu? Thanks.
