### ISSUE TITLE
Single point to log exceptions

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#588]
I'm looking for a single point to log all unhandled exceptions occuree in functions. For instance, pass it to Raygun or AppInsights.

Please consider to add an event or make it injectable into the host config. Or unseal the classes so it could be solved via inheritance.

**Comment by mathewc** [comment]
Check this out: [Error Alerting](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/Error-Alerting). The ErrorTrigger is built on TraceMonitor, which you can use to subscribe to and filter error events. A TraceMonitor is just a custom TraceWriter - could also just write your own low level TraceWriter and plug it in ([sample here](https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/MiscOperations/Program.cs#L54)).

Also see this recent issue here related to App Insights integration: http://github.com/Azure/azure-webjobs-sdk/issues/575. @advancedrei wrote some helpers built on TraceWriter to do this.
