### ISSUE TITLE
Specify connection strings in config only

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#589]
Is it possible to do not specify the dashboard connection strings in web app portal settings?

I tried to have them only in web project's Web.config and console project's App.config but still getting an error. But for better deployment and full automation story I'd like to do not specify them in the portal at all.

**Comment by mathewc** [comment]
Yes, you should be able to specify the AzureWebJobsStorage/AzureWebJobsDashboard connection strings in app.config. You're saying this isn't working for you? If the connection strings are in your app.config with the correct names, and the app.config is being deployed with your WebJob binaries, it should work.

**Comment by abatishchev** [comment]
I read them from a configuration provider injected into ctor and assign to host config. Seems it isn't enough?

**Comment by abatishchev** [comment]
I created an empty Api App project. Added an empty console project. Linked one to another. Deployed to Azure.

Still getting the same errors:

> Continuous WebJob Details AbWebJobsTestConsole

>Make sure that you are setting a connection string named AzureWebJobsDashboard in your Microsoft Azure Website configuration by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.

>Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website.

>The configuration is not properly set for the Microsoft Azure WebJobs Dashboard.
In your Microsoft Azure Website configuration you must set a connection string named AzureWebJobsDashboard by using the following format DefaultEndpointsProtocol=https;AccountName=NAME;AccountKey=KEY pointing to the Microsoft Azure Storage account where the Microsoft Azure WebJobs Runtime logs are stored.

>Please visit the article about configuring connection strings for more information on how you can configure connection strings in your Microsoft Azure Website. 

The source code is here: https://github.com/abatishchev/AbWebJobsTest. Please suggest.

**Comment by mathewc** [comment]
So, here's what is happening: the WebJob IS able to read the connection strings at runtime from app.config. However, the Dashboard (which runs as a separate site extension / web app) does NOT have access to that app.config. You have to make the connection string you want to use for the dashboard available to it via app settings.

So: you can set the Dashboard connection string once for the WebApp in the portal app settings, but you don't need to provide the AzureWebJobsStorage connection string - it can stay in app.config if you wish.

**Comment by hgjura** [comment]
This does not seem to work. The only place where you can set the AzureWebJobsDashboard, and have it work correctly it is in the portal. I tried in the Web.Config of the main/host web app and/or in the App.Config of the webjob project itself (as per the on-liner decumentation provided in the app.config), and it does not work. Which is kind of not nice, since I need to deploy and redeploy the webjobs via VSTS and connot ask people to go and mess around with the Azure portal only to set this config entry only.

**Comment by abatishchev** [comment]
I'd agree that this isn't nice, intuitive or useful.
I understand that this makes possible to have multiple webjobs to be monitored by a single dashboard.
Notwithstanding, I believe that more popular demand would be the ability to set all connection strings programmatically and indeed avoid deploying using ARM.

**Comment by haydenhancock** [comment]
Same issue here. I've defined the connection strings in my App.config, however, I received the error mentioned above. Once I went into the deployed WebJob in Azure and defined the same connection strings it started working as expected.

**Comment by YoungjaeKim** [comment]
I can reproduce that manual input at Portal `Application Settings` is required. `app.config` file does not help for `AzureWebJobsDashboard`.

**Comment by dennis-yemelyanov** [comment]
Agreed, there should be a way for the dashboard to read this connection string from some simple config file, such us settings.job instead of forcing users to mess with site settings.
