### ISSUE TITLE
ServiceBusTrigger should manage message lock renewals automatically

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#591]
QueueTrigger ensures that message visibility is updated periodically while a message is being processed. For ServiceBus messages, the analog is to renew the message lock (**BrokeredMessage.RenewLock**). We don't do this currently, meaning if a function runs longer than the default lock (I think 5 minutes), the lock will be lost.

For example, here's a [link](http://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Queues/Listeners/QueueListener.cs#L250) how QueueListener manages message visibility by creating a visibility timer. ServiceBus listener should do the same thing.

Here's the SO reported issue: http://stackoverflow.com/questions/33391888/service-bus-message-abandoned-despite-webjobs-sdk-handler-completed-successfully/33403158#33403158

**Comment by smartnose** [comment]
From the document here, it seems that lock renewal is taken care of. Can someone please explain?

https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-service-bus/

How ServicebusTrigger works

The SDK receives a message in PeekLock mode and calls Complete on the message if the function finishes successfully, or calls Abandon if the function fails. If the function runs longer than the PeekLock timeout, the lock is automatically renewed.

**Comment by mathewc** [comment]
Hmmm, yes, that article does suggest that. 

@tdykstra Regarding your ServiceBusTrigger sample - is that a working sample that you still have? Are you sure message locks are renewed in the RTM bits? I don't see any calls to RenewLock in the codebase.

**Comment by smartnose** [comment]
Thanks for looking into this. Will try with a dummy task. 

Meanwhile, about writing custom MessageProcessor, I see that this feature isn't available in 1.0.1, but 1.1.0 hasn't been released yet.

Is there a timeline for releasing 1.1.0?

**Comment by mathewc** [comment]
The beta1 for the v1.1.0 release is on nuget.org now. You can also get the latest and greatest prerelease packages from our "nightlies" feed, [instructions here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds). We'll be reasing the rc1 build for v1.1.0 very soon on nuget.org - we're finishing the release up now.

If it turns out that lock renewals for ServiceBus aren't possible, we can address that soon in a follow up bug fix release. However, the MessageProcessor might be a workaround for you until then.

**Comment by tdykstra** [comment]
@matthewc I recall a question about lock renewal coming up in an SO post, and I put in the doc what I undeerstood from Pranav's answer:  http://stackoverflow.com/questions/26570988/azure-webjob-sdk-service-bus-documentation

**Comment by mathewc** [comment]
On further investigation, while the ServiceBus documentation is very poor, it does appear that OnMessageAsync **does** do automatic renewals. These are goverened by the **OnMessageOptions.AutoRenewTimeout** value, which can be increased as needed. For a JobHost, you can override the default OnMessageOptions by setting it via ServiceBusConfiguration.OnMessageOptions, which you can then pass into config.UseServiceBus() on host startup.

**Comment by smartnose** [comment]
Confirmed that the lock is renewed using dummy Task.Delay(15min) example. Haven't tested longer delays, but 15mins is quite alright for my use cases for now.

**Comment by mathewc** [comment]
Thanks for confirming. Sorry about the confusion - I wasn't aware renewals were handled by SB by default. For Queues we had to do that ourselves.
