### ISSUE TITLE
downloaded all code from azure-webjobs-sdk and created packages but after install getting issue No functions found

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-webjobs-sdk#594]
downloaded all code from azure-webjobs-sdk and created packages but after install getting issue No functions found.

No functions found. Try making job classes and methods public.
Job host started

why so?

**Comment by mathewc** [comment]
You now have to call **config.UseServiceBus()** in your startup code. The ServiceBus bindings are now extensions (like the rest of the external binding extensions in [azure-webjobs-sdk-extensions](http://github.com/Azure/azure-webjobs-sdk-extensions) and must now be registered explicitly.

This change is also discussed in this [blog post](http://azure.microsoft.com/en-us/blog/extensible-triggers-and-binders-with-azure-webjobs-sdk-1-1-0-alpha1/).

**Comment by rustd** [comment]
@mathewc should we output a message saying if you are using ServiceBus, then use config.UseServiceBus()
This would help in the migration.

**Comment by mathewc** [comment]
It would have to be a more general message than that. I suggested something [in this Web App forum post](http://social.msdn.microsoft.com/Forums/azure/en-US/584070b0-08da-484d-bdfd-edf2d0ed5aa4/no-functions-found-try-making-job-classes-and-methods-public-for-servicebustriger) that I plan on doing.

**Comment by mathewc** [comment]
I've updated the error messages in all the various binding failure cases. You'll now see errors like the following, which hint the user to the correct path.

*No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).*

*Error indexing method 'Foobar'. Cannot bind parameter 'message' to type String&. Make sure the parameter Type is supported by the intended binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).*
