### ISSUE TITLE
Unable to impose strict ordering of output parameters

### ISSUE THREAD

**Issue by smartnose** [Azure/azure-webjobs-sdk#595]
Note that this issue has a workaround. I'll describe the issue first, and then the work-around.

Issue:

When a workhorse function has multiple outputs, we sometimes want to establish a strict if-then ordering. For example, I have a function that uploads a local file, and then send a file-is-uploaded message to service bus:

```
public static UploadLocalFile([ServiceBusTrigger] string inputFileName, [Blob...] out string fileContent, [ServiceBus...] out string fileIsUploadedMessage) {
.....
}
```
Here, there is no guarantee that the file content will be uploaded to blob storage before the message is sent. This lack of ordering complicates downstream code.

Quote from Mathew Charles:

> There is ordering of parameters. This is based on a concept of BindStepOrder (http://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Bindings/BindStepOrder.cs). You can see the code that orders parameter bindings here: http://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs#L406.

> This ensures that all “output parameters” are ordered after all other parameters. However, if you have multiple ouput parameters (as you do below), currently I don’t think ordering is guaranteed, since the current implementation uses Array.Sort, and Array.Sort doesn’t do a stable sort I believe (code here: http://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs#L588).

I wonder if we can specify an optional Order value in binding attributes (like JSON.net) to enforce certain ordering and help reason about causality between input/output.

Workaround:

For the example above, it's relatively easy to fix: we just need to use ICloudBlob binding instead of string value binding, so the function is rewritten as:

```
public static UploadLocalFile([ServiceBusTrigger] string inputFileName, [Blob...] ICloudBlob targetBlob, [ServiceBus...] out string fileIsUploadedMessage) {
        // upload file first
        targetBlob.UploadFromFile...
     
        // Then send the message
       fileIsUploadedMessage = inputFileName;
}
```

**Comment by mathewc** [comment]
Have you verified that you actually have a problem. I should clarify my comments above. It IS guaranteed that any **queue bindings** will happen after all other bindings. This is precisely to cover the scenario you described - a function has out bindings to write blobs/tables/etc. for processing, and then enqueues a message to trigger that processing. See [code comment here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs#L402). Clearly we need to guarantee the data is written before the queue message is.

There is no guaranteed ordering between the out queue bindings, but I don't think that is an issue. So in summary, I think your scenarios are already covered and you don't have any issues :)

**Comment by smartnose** [comment]
Thanks for explaining, Matt. I read the code again, and now it's clear to me.
