### ISSUE TITLE
Support MessageId binding for ServiceBus messages

### ISSUE THREAD

**Issue by smartnose** [Azure/azure-webjobs-sdk#598]
There doesn't seem to be a good way to set message id when using UserTypeToBrokeredMessage bindings.

https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/Bindings/UserTypeToBrokeredMessageConverter.cs

Being able to set message id would help us utilize duplicate detection feature of ServiceBus. 

We can currently use BrokeredMessage binding directly to set message id, but it would require us to maintain a duplicate copy of the serialization logic in UserTypeToBrokeredMessageConverter.cs.

**Comment by mathewc** [comment]
Please provide a sample job function showing what you're trying to accomplish

**Comment by smartnose** [comment]
We have a data ingestion web job that transports data from a legacy system to Azure blob storage. 

The WebJob basically has 3 functions:
1. Polls the legacy system to discover new data files, and send service bus message to kick off the following functions.
2. Upload the data files, and sends another message declaring the file is uploaded
3. Rename the uploaded data files.

Problem is that for function 1, multiple WebJobs instances may discover the same data file multiple times, and send duplicated ServiceBus message. The function signature:

'''
[NoAutomaticTrigger]
        public static void SendFileDiscoveredMessage(
            TextWriter logger,
            string fileKey,
            [ServiceBus(Topics.NewDataFileDiscovered)] out FileDiscoveredMessage message).

The main program:
while(true) {
      // Poll the legacy system
      foreach(var file in discoveredDataFiles) {
                host.call('SendFileDicoveredMessage'...);
      }
}

'''

I would like to ensure that for the same data file, I don't send FileDiscoveredMessage twice, so the downstream operations are not repeated unnecessarily.

I had several approaches on my mind, but decided to use Duplicate Detection feature from Azure. However, Duplicate Detection requires that identical messages should have identical Messages Ids.

To set MessageId, I had to abandon POCO binding to a ServiceBus message. Instead, use BrokeredMessage directly, so the function signature above becomes:

'''
[NoAutomaticTrigger]
        public static void SendFileDiscoveredMessage(
            TextWriter logger,
            string fileKey,
            [ServiceBus(Topics.NewDataFileDiscovered)] out BrokeredMessage message).
'''

Now, instead of sending out FileDiscoveredMessage directly, I had to wrap it up using the following function, so it carries a computed message id, while downstream functions can still keep using POCO binding to the wrapped FileDiscoveredMessage. This solved the problem for me, but created some extra serialization code that I have to make sure it will be in sync with WebJobs SDK internal logic. 

'''
public static BrokeredMessage WrapWithMessageId<T>(this T payload, string messageId)
        {
            string text = JsonConvert.SerializeObject(payload, SerializerSettings);
            byte[] bytes = Utf8.GetBytes(text);
            var stream = new MemoryStream(bytes, writable: false);

            return new BrokeredMessage(stream)
            {
                ContentType = ApplicationJson,
                MessageId = messageId
            };
        }
'''

**Comment by christopheranderson** [comment]
We're booting this out of 2.0 for now. Feel free to investigate this if it's important to you sooner.

**Comment by brandonh-msft** [comment]
this code no longer exists; @brettsam, @fabiocav recommend close?

**Comment by fabiocav** [comment]
The issue may still apply today (the code now exists here https://github.com/Azure/azure-functions-servicebus-extension/blob/master/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Bindings/UserTypeToBrokeredMessageConverter.cs), but it isn't something we've seen requests for. I'm closing this for now, but we can reopening if this is a feature others would find useful. This would require some discussion to settle on the proper design.
