### ISSUE TITLE
Extending / Inheriting ServiceBusTriggerAttribute

### ISSUE THREAD

**Issue by RonakThakkar** [Azure/azure-webjobs-sdk#600]
Hi,

We are working on complex enterprise application and using Azure Service Bus for that.

We have following use cases which as per my knowledge are not supported in current AzureServiceBusAttribute.

1). ServiceBusTriggerAttribute automatically creates Subscription if that does not exists. But we would like to create Subscription with Filter.

2). ServiceBusTriggerAttribute takes constant values for Topic and SubscriptionName. But in our case we are developing a common framework that our developers will use and hence we need to  resolve Topic and SubscriptionName for ServiceBusTriggerAttribute at run time based on parameters that are passed. But ServiceBusTriggerAttribute does not take parameters as input. 

We tried to solve this problem using INamespaceResolver but that error prone and does not look promising. See example below.

public void CreateCustomer([ServiceBusTrigger("%TopicName-Customer%", "%SubscriptionName-Command-Customer-Create-%")] Customer cusotmer, TextWriter log)

If you can see in above syntax that I am passing some hard coded strings like "Command", "Customer" which is my entity and "Create" which is my operation.

This is just one example of the complexity.

I would have appreciated If i could do something like 
CustomServiceBusTrigger(Constants.Command, typeoof(Entity).Name, Operation.Create);

I can create my CustomServiceBusTrigger that derives from ServiceBusTrigger attribute that takes some input parameters and internally sets TopicName and SubscriptionName.

But ServiceBusTriggerAttribute is sealed and I can not inherit that.

3). ServiceBusTriggerAttribute automatically de-serialize BrokeredMessage body section (paylod) into .NET object which is very useful. But In our case we would like to store body / paylod into BLOB storage instead of BrokeredMessage itself and BrokeredMessage would contain only URL of the BLOB storage. Hence we might have to write custom logic to de-serialzed that.

I thought of extending / inheriting ServiceBusTrigger attribute so that I can write my own logic to handle above scenarios but this class is sealed.

Is there any possibility of making that class Public or suggesting me some ideas to solve above issues.

I hope you understand that we are using Azure Service Bus extensively in our enterprise application and we are in tough time due to above scenarios.

**Comment by iremmats** [comment]
Regarding number 3. You should be able to fix this by supplying your own MessagingProvider and override the BeginProcessingMessageAsync and CompleteProcessingMessageAsync methods.

**Comment by mathewc** [comment]
Regarding 1 - Would it be possible for you to ensure that your subscriptions are created up front, somewhere in your host startup code? That way you can create them with your filters. Another possibility would be for us to add an overridable method on our MessagingProvider class that the SDK calls into to create subscriptions. That way, you could override that and create the subscription as needed. You can see the code that creates missing subscriptions [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/Listeners/ServiceBusSubscriptionListenerFactory.cs). We might be able to move that code into the MessagingProvider so it can be customized.

For 2 - The INameResolver strings that are passed in are effectively parameters, allowing you to use whatever logic you need to resolve them. Why doesn't this work for you?

Another more exotic possiblity might be for you to generate the functions you need on startup using the new WebJobs.Script stuff we're working on. You can see an example in the tests [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/test/WebJobs.Script.Tests/FunctionGeneratorTests.cs#L22). Basically you could develop whatever attributes you want, use reflection to translate those attributes into the SDK attributes, and use this method to generate the SDK functions. Once the functions are generated, they behave just like regular SDK functions.

**Comment by RonakThakkar** [comment]
I have created CustomMessagingProvider derives from MessagingProvider.

I have implemented BeginProcessingMessageAsync with following code

public void BeginProcessingMessageAsync(BrokeredMessage message, CancellationToken cancellationToken)
{
     string entity = blobStorageClient.ReadBlob(new Uri(brokeredMessage.GetBody<string>()));
     Customer customer = JsonConvert.DeserializeObject<Customer>(entity);
}

In above code, I have retrieved JSON string from body which is URL to paylod stored in Blob storage.
In next step I use my custom BlobStorageClient to get actual JSON customer object from BLOB stroage and de-serialze into Customer object.
This works fine.

Now where do I set this Customer object?
Will I get this Customer object directly in my Job function?

**Comment by mathewc** [comment]
I don't understand why you're trying to deserialize into a Customer in BeginProcessingMessage. ServiceBusTrigger already supports deserializing into your Types by default.

**Comment by RonakThakkar** [comment]
If you see my comments above, i am storing body paylod in blob storage for large messages and in BrokeredMessage i am storing only URL

**Comment by mathewc** [comment]
If your job function binds to BrokeredMessage, you could add such things to the BrokeredMessage.Properties collection and read them in your job function. However, if you bind to BrokeredMessage, then you can just do all this in your job function w/o all the indirection.

**Comment by mack0196** [comment]
I am also looking for a solution to 1). ServiceBusTriggerAttribute automatically creates Subscription if that does not exists. But we would like to create Subscription with Filter.

It would be great if the ServiceBusTriggerAttribute ctor had a parameter for filters.
