### ISSUE TITLE
how can I create microsoft.azure.webjobs.servicebus.1.0.1.nupkg package from git hub source code?

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-webjobs-sdk#601]
I tried using build project `WebJobs.ServiceBus` which creates dll `Microsoft.Azure.WebJobs.ServiceBus` but I dont find `microsoft.azure.webjobs.servicebus.1.0.1.nupkg` this nuget gets created :(

and if I tried to create my own package using this dll and use it in my webjob project, it gives me following error

An unhandled exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

can anyone help me
1.why package is not created or how to create microsoft.azure.webjobs.servicebus.1.0.1.nupkg
2.why getting this above error if I manually create package using Microsoft.Azure.WebJobs.ServiceBus.dll

**Comment by mathewc** [comment]
Why are you trying to create that package version? You can download it from nuget.

The reason you're getting the type load failure is because the assemblies in the repo are delay signed. The [development page](https://github.com/Azure/azure-webjobs-sdk/wiki/Development) has more on that.

**Comment by ashuthinks** [comment]
same my issue is related to this post again https://github.com/Azure/azure-webjobs-sdk/issues/600
want to make ServiceBusTriggerAttribute.cs this public instead of sealed so that I can have a full control on my code, can you please help me to do so? make it public and make available in that package will worth of my code thanks a lot

**Comment by ashuthinks** [comment]
I have also tried what you suggested  "sn -Vr *,31bf3856ad364e35"
after using this I get following issue:

No job functions found. Try making your job classes and methods public. If you'r
e using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've call
ed the registration method for the extension(s) in your startup code (e.g. confi
g.UseServiceBus(), config.UseTimers(), etc.).
Job host started

all methods are public though :( 
I need your expert help now thanks

**Comment by mathewc** [comment]
The error message is pretty clear - are you calling **config.UseServiceBus** as it indicates? As in this [sample here](https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/ServiceBus/Program.cs#L26).

**Comment by ashuthinks** [comment]
public class Program
    {
       public static void Main()
        {
            var host = new JobHost();
            // The following code ensures that the WebJob will be running continuously
            host.RunAndBlock();
        }
    }
