### ISSUE TITLE
When used derived class from ServiceBusTriggerAttribute - getting function not found error?

### ISSUE THREAD

**Issue by ashuthinks** [Azure/azure-webjobs-sdk#602]
My code is
  public class CustomServiceBusTriggerAttribute : ServiceBusTriggerAttribute
    {     
        public CustomServiceBusTriggerAttribute(string topicName, string SubscriptionName)
            : base(topicName, SubscriptionName)
        {
        }
    }
    public class Functions
    {
		public static void ProcessUsers([CustomServiceBusTriggerAttribute("my-demo-topic", "demo-Subscription")] BrokeredMessage message,
         TextWriter logger)
        {
               logger.WriteLine(message);
		}
    }

If I use directly "ServiceBusTriggerAttribute" inside "ProcessUsers" all works fine , but above code gives function not found error ? confusing why so , how should I work my above code?

**Comment by mathewc** [comment]
Custom derived trigger attributes are not supported currently by the SDK. All further discussion of this should take place on the other issue you created.
