### ISSUE TITLE
Expand ServiceBus Messaging configuration to allow PrefetchCount to be set

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#603]
Setting PrefetchCount on the MessageReceiver can dramatically improve message throughput. In addition to all the new configuration options/capabilities we added recently in v1.1.0, we should also allow this to be configured.

**Comment by iremmats** [comment]
Please implement! :+1:

**Comment by mathewc** [comment]
I actually implemented this yesterday and will be uploading a test build on myget for another customer to try. Would be happy if you also gave it a try. I did some perf testing, and it enables HUGE perf gains.

**Comment by iremmats** [comment]
Awesome. Will test it tomorrow. :)

**Comment by mathewc** [comment]
This has been addressed via commit https://github.com/Azure/azure-webjobs-sdk/pull/606. Please read the detailed notes I added to the PR on the new **TraceLevelAttribute** and SB **PrefetchCount** features. If you guys can give these a try and give me any feedback you might have I'd appreciate it. Thanks.

I've uploaded a build on our myget nightlies feed (instructions [here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)). The build is version **1.1.1-alpha-10181** of the WebJob assemblies.

**Comment by grbinho** [comment]
Hi,

I have a question about this feature.
If i understand correctly, this is what happens. 

Lets say PrefetchCount=100. 

SDK will deque up to 100 messages from the subscription (queue) and call our function up to 100 times with single message in each call?

Is it possible to reverse that? To make one function call with 100 messages passed to the function? We would get as function signature like..

```C#
public static async Task ProcessMessageAsync([ServiceBusTrigger("perftest", PrefetchCount=100)] ICollection<BrokeredMessage> messages)
{
    await ...
}
```
Scenario for this is if multiple requests are sent for processing that can eventually be reduced to a single request by some processing logic. This can in some cases dramatically speed up execution times. 

Simple scenario. If we want to rotate an image, and requests gives a rotation angle. We can always do %360 on any number of messages to reduce processing to one call.

**Comment by softeering** [comment]
Hi,

Wouldn't this go against the "message bus" architecture pattern?
The goal is to handle one message at a time in a decoupled / distributed way. Moreover, how would handle the failure of one message in the batch? WebJobs ServiceBus completes the item if no exception is thrown by the processing callback

**Comment by grbinho** [comment]
By the docs https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.messagereceiver.receivebatch.aspx

This is something that underlying framework supports via
```C#
MessageReceiver.ReceiveBatch
MessageReceiver.ReceiveBatchAsync
```
I wouldn't say it's against the architecture. I don't see why you would not batch if you can. You will just scale better.

Goal depends on the requirements. Sometimes it's one message at a time, sometimes it can be batch. Sometimes they need to be ordered, sometimes not. 

As far as i know, you can handle completion by yourself. You don't have to let the framework do it. For example, if you want to dead letter the message you can call

```C#
await message.DeadLetterAsync();
```
https://msdn.microsoft.com/library/microsoft.servicebus.messaging.brokeredmessage.aspx

**Comment by mathewc** [comment]
Batching is separate from this new PrefetchCount work. We already have a few issues that have been opened related to this. See: https://github.com/Azure/azure-webjobs-sdk/issues/570.

**Comment by grbinho** [comment]
Tnx. Will move over there :)
