### ISSUE TITLE
Read from one Service Bus namespace, write to another

### ISSUE THREAD

**Issue by iremmats** [Azure/azure-webjobs-sdk#605]
As of today you can set multiple Service Bus connection strings and per function choose which one to use. Is it possible today to use one for the ServiceBusTrigger and another for ServiceBus? Scenario is I want to read from one namespace and send to another namespace within the same function.

It can of course we achieved by reading from one and then in code connect to the other one...

**Comment by mathewc** [comment]
You can use the new **ServiceBusAccountAttribute** which works in the same way as the **StorageAccount** attribute as shown in the tests [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/MultipleStorageAccountsEndToEndTests.cs#L132). Is this what you're looking for? Both of these attributes can be applied at the class/method/parameter level.

**Comment by iremmats** [comment]
Thanks, your right. I thought it only was on function level but now I see its on parameter level too.


________________________________
