### ISSUE TITLE
DisableAttribute doesn't take RoleEnvironment settings into account

### ISSUE THREAD

**Issue by Fluwit** [Azure/azure-webjobs-sdk#607]
The DisableAttribute (and probably others too?) don't take the Azure service definition config settings into account, it only checks the app.config's settings. This pretty much makes it difficult to use these attributes within a worker role.

Basically the ConfigurationUtility class needs another check against RoleEnvironment.IsAvailable and if true return the value through RoleEnvironment.GetConfigurationSettingValue.

**Comment by mathewc** [comment]
The workaround for you would be to add a custom **INameResolver** via `JobHostConfiguration.NameResolver`. Than you can use `[Disable(%mysetting%)]` and the runtime will call your name resolver, allowing you to map the string `mysetting` to whatever runtime value you want. You can pull the value from your RoleEnvironment settings.

**Comment by mathewc** [comment]
Also, I don't know what you mean by ConfigurationUtility in the title of this issue.

**Comment by Fluwit** [comment]
I certainly feel stupid now. I've been looking over the examples and code but I still managed to miss the INameResolver functionality. Thanks, I got it working now.

As for what I meant by ConfigurationUtility: it's the object that seems to resolve the configuration setting values in the WebJobs.Host project. Bad manner of referencing my original intent, I admit.

**Comment by mathewc** [comment]
Don't feel stupid - if you couldn't find it, others probably can't as well :) Any thoughts on how to make this more discoverable? If the DisableAttribute xml doc mentioned INameResolver would that have helped?

**Comment by Fluwit** [comment]
I spoke too soon, apparently I still had the config setting present in my app.config. The INameResolver only allows to resolve the setting name, not its value -- unless I'm mistaken? Regardless, I managed to resolve it on my end by setting an Environment variable. Not the best solution, but it'll do.

As for knowing that INameResolver can be used, I'd add it to the attribute's xml definition, yeah. :-)

**Comment by mathewc** [comment]
INameResolver allows you to resolve a setting name to its value. In your implementation, you'll get the `mysetting` name, and you return the value.

**Comment by mathewc** [comment]
Yes you're right - INameResolver only allows you to map the name, allowing you to map to an app setting name or environment variable. In a WorkerRole, only the env var will work for you currently.

**Comment by mathewc** [comment]
One more thing to point out - DisableAttribute also has an overload that takes a Type. This allows you to implement an IsDisabled(MethodInfo) function that the runtime will call. You could use that to check RoleEnvironment.
