### ISSUE TITLE
Publishing a new WebJob sets it as 'On Demand'

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-webjobs-sdk#609]
Heya :)

When I first publish my webjob to the azure website/portal, it lists the webjob as 'On Demand'.

![image](https://cloud.githubusercontent.com/assets/899878/11837110/057b788e-a433-11e5-9e01-c0e478b9aa82.png)

I then have to _manually_ right click and select RUN NOW. (which, by the way .. took me _ages_ to figure out! Not very discoverable :crying_cat_face: )

Anyways, that works and my webjob runs.. but.. can this be programmatic?

**Comment by mathewc** [comment]
Yes the right click menu is TOTALLY not discoverable. Sigh. I thought you were using the WebJobs SDK, TimerTrigger, etc.? Those jobs should be published as Continuous (which is an option in the VS tooling). Please confirm what type of job you have here.

There are ways to invoke a job programmatically.

**Comment by PureKrome** [comment]
>I thought you were using the WebJobs SDK, TimerTrigger, etc.?

Correct.

>Those jobs should be published as Continuous.

Kewl! This was what I thought, too.

> (which is an option in the VS tooling)

Er.... I don't remember seeing _anything_ like this, in the VS Tooling? Here's a screen shot...

![image](https://cloud.githubusercontent.com/assets/899878/11854968/5de31712-a49b-11e5-8077-be11a14ee21a.png)


![image](https://cloud.githubusercontent.com/assets/899878/11854965/55760544-a49b-11e5-8f6b-7de277886dfe.png)

**Comment by mathewc** [comment]
In the VS dialog that came up when you chose "Publish as an Azure WebJob" there is a dropdown for "WebJob run mode" that defaults to "Continuously". That's what you want. Looks like you changed it to "On Demand".

**Comment by PureKrome** [comment]
> there is a dropdown for "WebJob run mode" that defaults to "Continuously". 

Nope. not there :( Is there a newer 'tooling' that is needed?

can this be defined programatically instead of relying on the tooling ?

![image](https://cloud.githubusercontent.com/assets/899878/11856603/4bac2a56-a4a6-11e5-9b17-4997727f57ca.png)

![image](https://cloud.githubusercontent.com/assets/899878/11856623/6a67f772-a4a6-11e5-977d-6a581897ad4a.png)

![image](https://cloud.githubusercontent.com/assets/899878/11856635/8647bf36-a4a6-11e5-8e0a-183373e37fcd.png)

**Comment by mathewc** [comment]
I'm talking about the tooling flow shown here: https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-deploy-webjobs/

That post shows the "WebJob Run Mode" dropdown.

**Comment by PureKrome** [comment]
AHH!

So this also means I can manually change my settings.. lets see..

Yep! looking at `\Properties\webjob-publish-settings.json` i can see: `"runMode": "OnDemand"`. Changing that to `"runMode": "Continuous"` will fix up my problem :)

Thank you @mathewc for your kind patience :+1:

**Comment by philringsmuth** [comment]
Looks like you can get this window to come back up by deleting the `webjob-publish-settings.json` file as well as the `PublishProfiles` folder from the project. Then the next time you right-click on the project and choose to Publish as Azure WebJob, you'll get the window you're looking for.
