### ISSUE TITLE
Refactor & expose access to the serialization logic in UserTypeToBrokeredMessageConverter.cs

### ISSUE THREAD

**Issue by smartnose** [Azure/azure-webjobs-sdk#610]
This issue is kind related to https://github.com/Azure/azure-webjobs-sdk/issues/598

Example: if I have a message type (MyMessage.cs), I should be able to serialize it using the same logic as in UserTypeToBrokeredMessageConverter.cs without c/p the serialization code, send it over as BrokeredMessage, and my WebJobs SDK  function would be able to bind it to MyMessage and successfully read from it. 

Scenario:
I designed a system containing many stateless services and a single stateful scheduling program that dispatches messages to these services according to current system/user state.

Each stateless service is implemented as a WebJob function with a particular service bus trigger. For example, we have services like the following:

CrawlerService([ServiceBusTrigger("crawl-a-page") CrawlerMessage, out StreamWriter page);
ExtractionService([ServiceBusTrigger("extract-data") ExtractionMessage, Blob inputData, out StreamWriter extractedData);
The list keeps growing...

WebJobs SDK absolutely kicks ass in helping to create these services, because they expect a fixed set of input/output. 

The scheduling program, however, is much trickier because it may send any of the dozen message types I have defined, and these message types may even grow dynamically as we add new service types.
As a result, I don't see an easy way to implement the scheduling program within the WebJobs SDK machinery. Instead, I have to write the scheduling program dealing with BrokeredMessage directly. To make sure my services understand the messages from the scheduling program, I had to copy/paste the serialization code in UserTypeToBrokeredMessageConverter.cs. It's not a big deal for now, but I fear this would break whenever WebJobs SDK upgrades its internal logic.

**Comment by mathewc** [comment]
So for both of these issues, your problem would be solved if you could reuse our currently internal serialization logic? If we exposed it to you some way?

**Comment by smartnose** [comment]
Yes.

**Comment by mathewc** [comment]
I think in in both of your scenarios binding to BrokeredMessage directly is correct. In the first case you need to set message properties, and in the second, you don't know what type of message is incoming, so you must handle all types.

Our internal serialization is simply JSON bytes, so as long as you do the same thing, you're safe. I don't really see much chance of you taking a breaking dependency since it's such a simple operation. Also, we won't be changing this representation because that would be a breaking change.

**Comment by christopheranderson** [comment]
Assigned to myself to make sure I follow up. Is this something which is still impacting you, @smartnose? We're considering putting this in the backlog and putting it up for community contributions.

**Comment by christopheranderson** [comment]
Closing since we didn't get a response.
