### ISSUE TITLE
WindowsAzure.Storage compatability

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-webjobs-sdk#620]
after updating webjobs nugetpackages to 1.1.1  i see that i now have a compatibility conflict with other dependant packages which use WindowsAzure.Storage 6.2.0.  The update has reverted my WindowsAzure.Storage package to 5.0.2 from 6.2.0. Was this intended, if so i need to downgrade other libraries in my solution to prevent me shipping a incompatible storage dll.

i.e.
When i try to upgrade my webjob's WindowsAzure.Storage nuget package i get.

Unable to resolve dependencies. 'WindowsAzure.Storage 6.2.0' is not compatible with 'Microsoft.Azure.WebJobs 1.1.1 constraint: WindowsAzure.Storage (≥ 4.3.0 && ≤ 5.0.2)'.

**Comment by mathewc** [comment]
Yes, this change was intentional. See issue https://github.com/Azure/azure-webjobs-sdk/issues/604 for details. Basically there are known breaking changes between the 4.3 version WebJobs SDK depends on and 6.2 which will lead to incorrect/broken WebJobs behavior.

We ran full tests up to 5.0.2 and those tests pass, so we allow you to upgrade up to that, but the SDK still targets 4.3.

**Comment by tbertenshaw** [comment]
OK cool I'll downgrade. Presumably the storage repo knows of this issue so we aren't permenantly limited to v5.0.2 of that library?

**Comment by mathewc** [comment]
It's not really an issue - as part of semantic versioning, libraries are allowed (and do) make breaking changes between **major** versions. It's expected. Therefore, our library cannot move to new major versions of our dependencies until we update or own major version number.

**Comment by tbertenshaw** [comment]
ok cool

**Comment by BowserKingKoopa** [comment]
This has created a big mess for me. Is there anyway to force it to use the latest storage package?

**Comment by mathewc** [comment]
See issue https://github.com/Azure/azure-webjobs-sdk/issues/631 - we've removed the version cap in the latest prerelease builds.

**Comment by BowserKingKoopa** [comment]
Thanks, you saved me.  I managed to somehow paint myself into a corner with this.

**Comment by mathewc** [comment]
Update: we've just released version 1.1.2 of the SDK on Nuget.org. This version is a hotfix to 1.1.1 that removes the Storage version cap that we had in place. So if you upgrade to 1.1.2 you should now be unblocked to upgrade to later storage versions. You should be fine upgrading to 6.2 - I did a test pass on that and it looked good. I haven't tried 7.0 yet.

**Comment by dabutvin** [comment]
if I am using `Microsoft.Azure.WebJobs version 1.1.2` is it okay to use `WindowsAzure.Storage version 8.4.0` ?

Thanks
