### ISSUE TITLE
Exception when AzureWebJobsDashboard is removed

### ISSUE THREAD

**Issue by fwd079** [Azure/azure-webjobs-sdk#629]
Hello,
Continued from [this StackOverflow question](http://stackoverflow.com/q/35345928/1659999) . If we do not want logging functionality then if we remove **AzureWebJobsDashboard** from connectionStrings then we get InvalidOperationException, telling us the ways how to add `DashboardConnectionString` properly.

Currently only solution is to pass null inside code. Something like:

`config.DashboardConnectionString = null;`

Easily testable by creating an Azure WebJob and then removing the AzureWebJobsDashboard from connectionStrings section of app.config file.

Thanks.

**Comment by christopheranderson** [comment]
May be fixed. @mathewc to verify

**Comment by paulbatum** [comment]
Dupe of #379

**Comment by fwd079** [comment]
Urrm, the bug is changed from "feature" to a "backlog"? Seriously?

**Comment by mathewc** [comment]
Also related to https://github.com/Azure/azure-webjobs-sdk/issues/563

**Comment by fwd079** [comment]
@mathewc cheers mate. :)
