### ISSUE TITLE
Suggestion: Dynamic service bus topic/queue names

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-webjobs-sdk#638]
We process data for multiple tenants in our system and wish to prevent one tenant from slowing down processing of requests for other tenants. This can happen when one tenant submits a large batch of messages into one of our queues.

One solution to this is to have a single queue per tenant. What I'd like is the ability to have a trigger that occurs based on a queue name pattern. I'm thinking something like:

    public void ProcessTenantMessage([ServiceBusTrigger("myqueue-*")] BrokeredMessage message, string tenant)
    {
        // ideally tenant would be the value from the * portion of the queue name
    }

The challenge would be that the system would have to periodically look for and wire-up listeners for new queues and then remove them if a queue was ever deleted. The benefit would be that each tenant would now be processed in parallel with others.

**Comment by mathewc** [comment]
Honestly, I don't think we'd add something like this to the SDK. This seems to call for a custom solution for your requirements. I'm not saying that something like this isn't interesting :), but I feel it's outside of the scope of the SDK.

**Comment by BrianVallelunga** [comment]
I understand and I may end up rolling my own.

**Comment by sharpcoder28** [comment]
Brian did you ever roll your own or come up with a different solution? I have a need for this as well. For phase one I think I'm just going to hard code a few queues and let them pick one and see how many messages are on it so they can pick one that's not being used.
