### ISSUE TITLE
WebJob will run first exe alphabetically in output folder

### ISSUE THREAD

**Issue by fsigalov** [Azure/azure-webjobs-sdk#646]
There is no config (that I can find) that determines which exe corresponds to the command of the webjob. I assumed it would be the project exe, but it's actually the first one when sorted alphabetically. I got the command to change just by renaming the exe (not changing any other config).
I think this is unintuitive. It should either always use the project output as the command, or allow user to specify the command.

**Comment by mathewc** [comment]
You can control this by placing a `run.cmd` script in your job directory. The WebJobs runtime will call that script allowing you to invoke the proper exe. More details in the Kudu wiki here: https://github.com/projectkudu/kudu/wiki/Web-Jobs
