### ISSUE TITLE
Add sdk for Azure WebJobs

### ISSUE THREAD

**Issue by fsigalov** [Azure/azure-webjobs-sdk#647]
I am producing events from Azure WebJobs. It works if I link against Microsoft.Applications.Telemetry.Azure and set `TestSupport.AllowRunNotOnAzure();`
Is there a better way to support WebJobs?

**Comment by mathewc** [comment]
I don't understand - can you please explain? Are you using the WebJobs SDK?

**Comment by fsigalov** [comment]
I shouldn’t open bugs this late... I’m sorry that was posted in the wrong forum.
What I meant is that Aria should support webJobs (they already support azure)
Sorry about that!
