### ISSUE TITLE
BindingFactory exceptions should not be TargetInvocationExceptions

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#652]
BindingFactory does some internal reflection and can throw TargetInvocationException with the useful exception in the InnerException. For example: if you supply an 'out IAsyncCollector<T>', which is not allowed, you'll have to check the InnerException to see why.

**Comment by MikeStall** [comment]
I think this was fixed a while ago. The MethodInvoke<> helper unwraps these.
