### ISSUE TITLE
Function return values instead of ICollector / IAsyncCollector

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-webjobs-sdk#656]
Currently the signature of your webjob functions must be essentially a side-effectful function with no tangible output: -

``` csharp
void Foo([QueueTrigger("input")] string input, [Queue("output)"] ICollector<string> outputs) {
   outputs.Add("bar");
}
```

or

``` fsharp
let foo([<QueueTrigger("input")>] input, [<Queue("output)">] outputs : ICollector<_>) =
   outputs.Add("bar")
```

It would be good to actually have the function return the output to the output queue - not only is this easier to test, it reduces dependencies i.e. two less types to worry about and is simply to reason about i.e. this now is just a plain method / function with some input and output : -

``` csharp
[Queue("output)"] 
string Foo([QueueTrigger("input")], string input) { return "bar" }
```

or

``` fsharp
[<Queue("output")>]
let foo([<QueueTrigger("input")>] input) = "bar"
```

The same approach could be used for asynchronous results if the return type is Task<T> rather than just T.

**Comment by christopheranderson** [comment]
I think the notion of being able to return something and have that routed as an output to a binding is a nifty idea, but it's fairly complex so this is likely to sit on our backlog for sometime.

**Comment by MikeStall** [comment]
We've added return value support for SDK, see   https://github.com/Azure/azure-webjobs-sdk/issues/1104
