### ISSUE TITLE
webjob-publish-settings.js does not validate against schema

### ISSUE THREAD

**Issue by mteper** [Azure/azure-webjobs-sdk#658]
"Continuous" job types seems incongruent with the schema. See R# discussion for more detail: https://youtrack.jetbrains.com/issue/RSRP-454885.

**Comment by mathewc** [comment]
Please move this issue to the Kudu repo, as it deals with core WebJobs, not the WebJobs SDK. Thanks :) https://github.com/projectkudu/kudu/issues

**Comment by mteper** [comment]
This issue was moved to projectkudu/kudu#1928
