### ISSUE TITLE
Testing webjobs "Nightlies"

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-webjobs-sdk#663]
Im trying to test some of the nightly changes and i cannot get Azure to restore the nuget packages from the nightly feed `http://www.myget.org/F/azure-appservice/api/v2/` (deployment using the Deployment source (i.e. from github)). I really need this configuration in order to be able to properly test changes. 

http://stackoverflow.com/questions/36084088/azure-ci-using-alternative-nuget-feed

**Comment by mathewc** [comment]
Our CI builds for the WebJobs.Extensions repo itself pulls pre-release packages from Myget to get pre-release versions of the core WebJobs SDK. Here's a pointer to our nuget config: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/.nuget/NuGet.Config

**Comment by tbertenshaw** [comment]
@mathewc  I see, i had updated my nuget.targets, but if i add this to my existing nuget.config and checkin it should work i guess. (but without the buildtools feed.)

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
	<packageRestore>
		<!--Allow NuGet to download missing packages -->
		<add key="enabled" value="True" />
		<!-- Automatically check for missing packages during build in Visual Studio -->
		<add key="automatic" value="True" />
	</packageRestore>
	<packageSources>
		<add key="nuget.org" value="https://www.nuget.org/api/v2/" />
		<add key="azure_app_service" value="https://www.myget.org/F/azure-appservice/api/v2" />
		<!--<add key="buildTools" value="https://www.myget.org/F/30de4ee06dd54956a82013fa17a3accb/" />-->
	</packageSources>
</configuration>
```
ill give that a try 
Cheers!

**Comment by tbertenshaw** [comment]
that worked a treat cheers!

**Comment by mathewc** [comment]
Noice :)
