### ISSUE TITLE
Guidance for implementing a multi subscription trigger

### ISSUE THREAD

**Issue by markanewman** [Azure/azure-webjobs-sdk#667]
Is there a way to have a single function watch a collection of subscriptions? Ideally I would like it to monitor the whole topic and if a new subscription came online that matched the correct path, it would star consuming from that too.
Something like this would be nice

`public async Task MultiWatchAsync([ServiceBusTrigger("Topic", "Type-*")] MyType request)`

I have this kind of working now with a custom MessageProcessor and dumping all of by types into 1 subscription, but I am looking for a better solution.

**Comment by bmcclory** [comment]
I wrote a custom trigger binding extension that does something like this. Essentially, a custom MultiSubscriptionListener that discovers a set of subscriptions at runtime and then creates message receivers foreach subscription. If new subscriptions are frequently created in your system, you might need some mechanism for notifying your listener that it must refresh it's subscription list / receivers.

You'll also need to be thoughtful about tuning your OnMessage options, as depending on the number of subscriptions you expect to discover and the volume of messages on those subscriptions. If you're not careful, you could spin up a very large number of message processing threads inside your web job!

Unfortunately, the service bus listeners/trigger types in the SDK are all internal, so you need to fork the SDK (or write your own extension from scratch) to do any of this.

**Comment by markanewman** [comment]
I implemented what you suggested. I definitely like how it *feels* to us a custom `ITriggerBinding`.

Thanks for the suggestion.
