### ISSUE TITLE
New logging: path segment has an extra 'functions.' segment

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk#670]
e.g. API is

    /api/functions/invocations/functions.GenericWebhookCSharp1/timeline

when it should just be

    /api/functions/invocations/GenericWebhookCSharp1/timeline

The `functions.` part seems like an implementation detail that we don't want to surface in API or dashboard UI (dashboard also shows it).

**Comment by MikeStall** [comment]
Fixed.
https://github.com/Azure/azure-webjobs-sdk-script/commit/ed7c143931200b448b29cff5c60e8046c8c55d42
