### ISSUE TITLE
Update Azure Storage package to later versions

### ISSUE THREAD

**Issue by bunceg** [Azure/azure-webjobs-sdk#672]
WebJobs SDK 1.1.1 has an AzureStorage Constraint of 4.3.0 - 5.0.2. As WindowsAzure.Storage is now > 6.1.0 this causes conflicts when pulling in packages that have these different dependencies.

1) Is there a reason that the package limit can't be changed?
2) is there a (wider) neccessity to refactor and rearchitect webjobs to only include these dependencies when necessary - for example I do not use *any* of the web job helper attributes to talk to service bus, blobs etc.  I only use web jobs as a container to execute my own functions - I feel I am including a lot of "junk" package dependences not needed in my scenarios.

**Comment by mathewc** [comment]
See https://github.com/Azure/azure-webjobs-sdk/issues/631 for details on the versioning. In the current prerelease builds we've relaxed the restriction.

Regarding dependencies - you only pull in ServiceBus if you're using the ServiceBus WebJobs package. The core WebJobs SDK will always reference the Azure SDK.

Curious to hear how you're using the SDK if you're not using any of the storage, etc. stuff. What does it buy you to use it as a container to execute your own functions?

**Comment by bunceg** [comment]
We have an architecural standard that we will not tie ourselves into any Cloud Architecture - our app runs on Azure but some customers could choose to run this on-premise in their own tenanted version. This means anything that accesses Service Bus, Azure Storage, Azure Search etc. is hidden behind adapter layers. It's so we can quickly deploy to On-Premise (or AWS) without ripping apart all the dependencies in our app (and as we use a lot of azure features this is quite important). It also helps for on-prem testing when we can easily swap out Azure components for stubs etc. without impacting the business logic or overall architecture at all.

This means we have our own api for (e.g.) listening to a service bus topic/queues and responding to those events. We then need to host these in a continuous process in the Azure environment. We use a web job for this. It's the same for the same for windows storage, we wrap up the SDK behind our own Api.

This design means that we only really talk directly to azure at the "edge" of the architecture. It's ok to use the web job SDK as this is a single console app that is easy to replace with (e.g.) a windows service for an on-prem deployment. e.g. the  "manager" of our service bus subscriptions is our own class in a seperate assembly that can be hosted in anything, as long as it's continuous.

If we need to move from Azure then we only need to touch the "edge" elements but the core of the app stays the same.

This means, for webjobs, we need the JobHost, RunAndBlock and then the [NoAutomaticTrigger] to invoke our own method in the webjob architecture... which then invokes our own Service Bus Manger "start" method.

Anything else for WebJobs just gets in the way for us. 

Last time I checked too this wasn't a particuarly clean scenario supported by WebJobs either as we can't intercept the shutdown CancellationTokenSource or access the TextWriter used by the WebJob Logging framework invoked on start

Hope this helps.

**Comment by mathewc** [comment]
My point is, if all you're using the SDK for is a Console app entry point, you don't need the SDK at all. You can just have a non-SDK Console app running in a vanilla Continuous WebJob. You should be able to remove the SDK references completely. https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/

**Comment by bunceg** [comment]
Hmm. Will this still update the dashboard or is the SDK needed for this?

That might have been my misunderstanding from the beginning....

**Comment by mathewc** [comment]
Yes, you only get Dashboard support if you use the SDK. Since the default VS template creates an SDK Console host for people, I often see people using the SDK when they don't need to - they really only want  a vanilla continuous WebJob. That sounds like your scenario.

**Comment by davidebbo** [comment]
To be clear: you get *some* dashboard support without the SDK. e.g. if you have a triggered WebJob, you'll see the list of past invocations. But if you have a Continuous WebJob, you won't get detailed info about what's happening inside your code.

**Comment by bunceg** [comment]
Sorry for using this thread as an advice column :p ... isn't it more complicated than that?

With the SDK you get the logging in the portal (not that essential if you have your own framework) but you can also intercept a shutdown request by using he Shutdown file, which is what the JobHost does for you.... or can you monitor this yourself instead?

**Comment by davidebbo** [comment]
Yes, see https://github.com/projectkudu/kudu/wiki/Web-Jobs#graceful-shutdown for details.
