### ISSUE TITLE
WebJobs dashboard has broken links

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk#677]
*Copying from https://github.com/projectkudu/WebJobsPortal/issues/240. Opened by @BilalAlam*

![image](https://cloud.githubusercontent.com/assets/17733334/14085844/0a092c4e-f4d7-11e5-8481-fa297b352b7c.png)

The "search blobs" link and the "about" link both don't seem to work at all.  We should fix that up or avoid showing the links.

**Comment by MikeStall** [comment]
Fixed.
