### ISSUE TITLE
Move SDK and Dashboard CI to App Veyor

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#681]
We need to migrate our remaining Team City jobs off of Team City. This will also allow us to start using C# 6.

**Comment by mathewc** [comment]
Update: I've done the work to move the tests to the public TestEasy package. That means our tests no longer run on our CI. We should move this project to our new AppVeyor CI setup.

**Comment by paulbatum** [comment]
Here's my thoughts on how to to tackle this:
1. Leave the signed SDK build on TC for now
2. Update the signed SDK job to drop the bits into a location accessible by AppVeyor (we could try mounting azure files as a file share)
3. Move the dashboard job to AppVeyor (it appears they have UI testing support - if it doesnt work out we can fallback to using our internal jenkins server)

**Comment by mathewc** [comment]
This work will also pave the way for us moving the SDK job over. With that job outputting its artifacts to an azure files share, we can move it to App Veyor as well, and set up a TeamCity / Jenkins job to do the signing.

**Comment by mamaso** [comment]
Closing this.

SDK has been moved, signed build has been moved, and dashboard has been deprioritized.
