### ISSUE TITLE
WebJobs.Logging needs to support log purge / retention policies

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#684]
The current design is based on a single table which won't allow us to efficiently delete / purge logs. We need to move to a rolling multi-table design which will allow us to delete old logs with a single table delete statement. This is how all other logging systems built on Table Storage are designed.

**Comment by sandeep-at-airlift** [comment]
Is there a date for this being fixed? I have to decide whether to invest in a homegrown logging solution or not. this is killing our ability to debug issues.

**Comment by mathewc** [comment]
We're not making any more investments in the Dashboard - the recommendation for logging going forward is to use Application Insights https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration.
