### ISSUE TITLE
Finish BindingFactory and other Extension binding helpers

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#686]
We need to:
- finalize the new APIs and public surface area
- add full unit tests for everything
- address all outstanding bugs

**Comment by MikeStall** [comment]
We'll remove BindingFactory complete; and superseded by the rule-based scheme off ExtensionContext.
Fixing this in conjunction with https://github.com/Azure/azure-webjobs-sdk/issues/1406
