### ISSUE TITLE
Finish Review + Testing of new Blob scanning strategy

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#687]
This will become the new default strategy for all BlobTriggers, we need to do a final review to make sure it won't regress anyone. We should also make sure all the test coverage we want is in place.

We might also want to consider exposing configuration knobs, similar to `JobHostQueuesConfiguration`.

**Comment by christopheranderson** [comment]
Could you take a look at this Hosam and check that we're good?

**Comment by petersondrew** [comment]
@mathewc,  if you're referring to the new hybrid strategy for blob triggers, we're putting it through its paces currently and are having issues with our functions not triggering when multiple blobs are uploaded at the same time (both in the storage emulator and on azure). It's usually something like 1 or 2 out of 5.

I haven't yet tracked down what's happening, but the behavior is very repeatable. After restarting our job host the blobs are picked up either instantly, or within a couple minutes.

My next step is to build against the source for 2.0 beta 1 and try to debug it, but I'm not super familiar with the code base. Anywhere I should start looking, or any additional logging I can squeeze out? I have trace set to Verbose already and nothing interesting shows up.

**Comment by brettsam** [comment]
If you wait without restarting are they eventually picked up? Would you mind sharing how you upload your blobs at the same time? That would help me construct a repro.

I have an idea of what may be happening but would like to make sure I'm testing exactly what you're seeing.

**Comment by petersondrew** [comment]
If I wait without restarting they are not being picked up in our experience. I discovered this issue when I noticed multiple days worth of blobs that had not been triggered.

We've been able to reproduce this in two ways, One, with PUT BLOB calls from an NSUrlSession in iOS, and the other with PUT BLOCK and PUT BLOCKLIST calls from HttpClient, both to a single container using SAS tokens in the query string. In both cases we have multiple PUT BLOB or PUT BLOCK calls happening concurrently from a single client. We have not tested it with singular calls from multiple clients concurrently.

Let me know if there's any pertinent information I've left out.

**Comment by petersondrew** [comment]
I had an additional question regarding the new strategy, after looking through the code: We plan on having thousands and thousands of containers, but only scanning a single incoming container for changes using this polling strategy. Is the per-container poll-limit based on the blob trigger (e.g., a trigger looking for blobs in one container) or is it based on the total number of containers in the storage account, even if they're excluded by the blob trigger? E.g. `[BlobTrigger("incoming/{blob}")] ICloudBlob inputBlob`

**Comment by brettsam** [comment]
If you don't have a BlobTrigger using a container, it won't be registered with the Listener, so we won't be scanning it.

Another question -- which nuget package version are you using when you see the issue you called out above?

**Comment by petersondrew** [comment]
Re: BlobTrigger - thanks, that clears up that question 😃 

Our web jobs are referencing WebJobs 2.0.0-beta1, and WindowsAzure.Storage 7.2.1

**Comment by brettsam** [comment]
Would it be easy for you try your scenario against our latest MyGet build and see if you can still repro the issue? https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds. I know we've fixed a few blob scanning issues since that build so it's possible that it's already been fixed. If not, I'll try to set up a repro myself.

**Comment by petersondrew** [comment]
I will try that in the AM, thank you.

**Comment by petersondrew** [comment]
I just wanted to follow-up (since I failed to before) and say that the issue I described did seem to resolve itself after updating to the nightly builds.
