### ISSUE TITLE
1.1.2 stable

### ISSUE THREAD

**Issue by vsutter** [Azure/azure-webjobs-sdk#690]
Hello,

Is there a date for the 1.1.2 in stable version?
I want to use EventHubConfiguration and EventHubTrigger classes in production environnement.
Wich version correspond master branch on GitHub ? Because i can see  EventHubConfiguration and EventHubTrigger classes but i can't see them when i download Microsoft.Azure.WebJobs.ServiceBus 1.1.1 nuget package.
Vincent

**Comment by mathewc** [comment]
We currently have the prerelease packages up on our myget feed (instructions [here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)). We haven't figured out release dates yet, but our plan is to try to get a beta release containing this up on nuget as soon as possible.

**Comment by mathewc** [comment]
Closing this since this isn't an issue. We'll be triaging things soon, and we'll set a date on the 1.1.2 milestone when we're complete.
