### ISSUE TITLE
AutoAbandon ?

### ISSUE THREAD

**Issue by funkycoding** [Azure/azure-webjobs-sdk#691]
Is it possible to add an option to OnMessageOptions to ignore the AbandonAsync call? aka: AutoAbandon or something?

I'm using the ServiceBusTrigger and if a message fails i just want the lock to run out and try again. Currently it's just triggering the function 5 times (delivery count on queue in azure) quickly in a row.

I'm happy to inherit and override, but had to share my 2ct :moneybag: :smile: 

```csharp
public override async Task CompleteProcessingMessageAsync(BrokeredMessage message, FunctionResult result, CancellationToken cancellationToken)
{
    if (result.Succeeded)
    {
        if (!MessageOptions.AutoComplete)
        {
            // AutoComplete is true by default, but if set to false
            // we need to complete the message
            cancellationToken.ThrowIfCancellationRequested();
            await message.CompleteAsync();
        }
    }
    else
    {
        cancellationToken.ThrowIfCancellationRequested();
        await message.AbandonAsync();
    };
}
```

**Comment by mathewc** [comment]
We can't add a property to `OnMessageOptions` since we don't own that Type (it's from the ServiceBus SDK). However, I hear your need to be able to customize this behavior. Note that we have a similar pattern in QueueTrigger (see [QueueProcessor](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs)). You'll get the same quick retry behavior for Azure Queues as well. People customize that by overriding the `ReleaseMessageAsync` to customize the visibility timeout.

So whatever we do for this, we'll want to provide a consistent solution across the various queue triggers.

**Comment by funkycoding** [comment]
> We can't add a property to OnMessageOptions since we don't own that Type (it's from the ServiceBus SDK). 

Kinda missed that part...probably due to a long work day :smile: 

I understand you rather have a consistent solution. For Azure Service Bus messages we can't set the visibility timeout (afaik). I'll just customize the MessagingProvider & MessageProcessor to fit my needs for now. Thanks for the reply!

**Comment by TimVinkemeier** [comment]
Hey,
interestingly, I am working on the exact same issue right now :smiley: 
@funkycoding pointed out to use a custom `MessageProcessor` and I am doing just that. However, I am not sure how to put in the "delay". If I understand correctly, there is no way to abandon the message without making it available again immediately. So, do I have to complete the message and send a clone of it again? If so, how can I get access to the queue from within the `MessageProcessor`?
Thanks :wink:

**Comment by mathewc** [comment]
I'd investigate the properties of the ServiceBus `BrokeredMessage` class to see if any allow you to make the message invisible for a time. I took a quick look - perhaps [ScheduledEnqueueTime](https://www.amido.com/code/azure-service-bus-how-to-delay-a-message-being-sent-to-the-queue/) is what you need. It seems to be a value that indicates when a message should be available in the queue.

**Comment by TimVinkemeier** [comment]
Thanks for your reply. I did that already, but unfortunately, ScheduledEnqueueTime only works before the message is enqueued, as far as the docs go - and my test seems to show that. The message has a ReceiveContext, which seems to contain some reference to the queue, but it is internal, so I do not want to use that. I tried to use a QueueClient from there to send a clone, but that somehow didn't work. When I'm back at work tomorrow (I live in Germany, +9h from you), I can share my current code, if that helps.

**Comment by mathewc** [comment]
Probably better for you to ask the ServiceBus SDK team - they'll know best what your options are.

**Comment by TimVinkemeier** [comment]
Okay. Could you get me in touch with someone?

**Comment by mathewc** [comment]
https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=servbus

**Comment by TimVinkemeier** [comment]
Alright, thanks for your help :smiley:

**Comment by christopheranderson** [comment]
Closing since this is related to Service Bus
