### ISSUE TITLE
Dashboard cannot show function detail

### ISSUE THREAD

**Issue by krmr** [Azure/azure-webjobs-sdk#692]
In some cases the dashboard will not show the details of an invocation if clicking on the link. This happens in all views showing individual function invocations. This might be caused if the invocation references a ParentId that does not exist.

This was observed in a setup with two WebJobs on two separate Web Apps configured to use different blob containers as dashboard storage. WebJob 'A' posted a message for WebJob 'B' on a service bus queue. For the resulting invocation of 'B' the details can not be displayed. Updating the corresponding log on blob storage by manually removing the 'ParentId' resolved the issue.

**Comment by christopheranderson** [comment]
@MikeStall  - Could you look into this? Is this just something we need to fail gracefully?

**Comment by MikeStall** [comment]
@krmr - that's a great repro, thanks. 
The invalid ParentId is causing a null lookup here https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Dashboard/ApiControllers/FunctionsController.cs#L425 , and then a null reference shortly thereafter.
