### ISSUE TITLE
Publish DNX console app as webjob from VS

### ISSUE THREAD

**Issue by deherle** [Azure/azure-webjobs-sdk#695]
Hi,

Would really love to have this feature in VS2015.  Any ETA on its addition?

Thanks.

Darin

**Comment by pherbel** [comment]
👍

**Comment by christopheranderson** [comment]
Is this just about WebJobs, the Web Apps feature, not the SDK? Because those issues belong over in Kudu - https://github.com/projectkudu/kudu/

**Comment by davidebbo** [comment]
It's actually more VS tooling than Kudu. But please note that DNX (now .NET Core) is going through drastic changes, so I doubt there will be much VS investments based on the old RC1 bits. @bradygaster may have more to say about this.

**Comment by bradygaster** [comment]
@davidebbo is correct. We are planning on adding Core WebJob support by SDK 3.0. That said, it is possible to do today. Take a look at this blog post for info: http://blog.lytzen.name/2016/03/auto-deploy-azure-web-job-with-aspnet-5.html

**Comment by deherle** [comment]
Thanks for the input... that blog post is a good start (with the console app as a separate project to boot!) until v3 of the SDK.

**Comment by davidebbo** [comment]
Great! Closing here since it's not really SDK issue.
