### ISSUE TITLE
Add support to specify converter manager per attribute

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk#697]
Example from : https://github.com/Azure/azure-webjobs-sdk-extensions/pull/74

```
public static void SendAppleNotification_Out_String(
            [TimerTrigger("*/45 * * * * *")] TimerInfo timerInfo,
           [NotificationHub(Platform = NotificationPlatform.Apns)] out string stringPayload)
         {
             stringPayload = "{ \"aps\":{ \"alert\":\"Notification Hub test notification\"} }";
         }
```

Platform is set at the attribute level. Converter manager needs to access this in order to convert string payload to appropriate type of native notification. As of now this is not possible as converterManager is global to the host.

**Comment by MikeStall** [comment]
This is handled now since the Attribute can be passed to the converter function. 
See https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/IConverterManager.cs
