### ISSUE TITLE
WindowsAzure.Storage Dependency <= 5.0.2 hampering ability to upgrade solution

### ISSUE THREAD

**Issue by etiennedetrace** [Azure/azure-webjobs-sdk#700]
Source for version 1.2.0 indicates use of many old NuGet packages. Will the new version FINALLY remove the restriction on Storage <=5.0.2? Causing many conflicts on a large Azure solution using much of the Azure platform.

**Comment by mathewc** [comment]
Update: we've just released version 1.1.2 of the SDK on Nuget.org. This version is a hotfix to 1.1.1 that removes the Storage version cap that we had in place. So if you upgrade to 1.1.2 you should now be unblocked to upgrade to later storage versions. You should be fine upgrading to 6.2 - I did a test pass on that and it looked good. I haven't tried 7.0 yet.

**Comment by mathewc** [comment]
FYI: We've released the [2.0.0-beta1](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.0.0-beta1) prerelease on Nuget. In this version, we've moved completely to the latest Storage SDK version.
