### ISSUE TITLE
Subscribe to multiple Service Bus Topics using same WebJob

### ISSUE THREAD

**Issue by RonakThakkar** [Azure/azure-webjobs-sdk#702]
Hi,

We have a tenant which has 2 sub companies. We created a separate Service Bus for each company. There is a possibility that another company will be added at run-time using Company Management UI that we created.

We have a WebJob that consumes event from Service Bus. What are the possible options to point same WebJob to 2 different service bus for different companies.

**Comment by mathewc** [comment]
A single job function is tied to a single ServiceBus connection. The trigger attribute model is not designed to allow you to have a single function that is triggered by **multiple** different connections/queues.

**Comment by RonakThakkar** [comment]
Can you suggest me a solution to the problem where I have multiple companies with service bus for each company but I would like to have Single WebJob to process them.

**Comment by sharpcoder28** [comment]
Use one service bus. Put the company ID in the message. Then use a factory to get the right class to process the message based on company.
