### ISSUE TITLE
Unit test BrokeredMessage

### ISSUE THREAD

**Issue by arthuronoszko** [Azure/azure-webjobs-sdk#703]
Hi!

I have troubles writing unit tests of methods that uses BrokeredMessage, since I do not know how to set the state of the message. For example, I have message.Complete() inside a method that I want to test, but it  throws exceptions since the message is not in the correct state. Any ideas of how to fix this?

This is the exception I get: System.InvalidOperationException : Operation is not valid due to the current state of the object.

BR
Arthur

**Comment by mathewc** [comment]
BrokeredMessage is part of the ServiceBus SDK - we don't own it or its testability. I can see that the type isn't really testable/mockable. Perhaps someone on the Service Bus Forum https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=servbus an help.

**Comment by arthuronoszko** [comment]
Thanks @mathewc ! I will ask at the correct forum instead :)
