### ISSUE TITLE
EventHub Trigger Consumer Group

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#704]
See forum issue [here](https://social.msdn.microsoft.com/Forums/en-US/104ff0ed-63a9-46e6-ac99-03c053e63a00/specifying-the-consumer-group-for-eventhub-trigger).

Another SO request [here](https://stackoverflow.com/questions/37485563/integrate-azure-functions-with-event-hub).

**Comment by mathewc** [comment]
@MikeStall This one keeps coming up. Can we ensure this works? We also need to enable this for Azure Functions.

**Comment by MikeStall** [comment]
One workaround that mitigates some of these scenarios is to initialize the EventProcessHost yourself and call EventHubConfiguration.AddEventProcessorHost() directly.

**Comment by markpjohnson** [comment]
+1 for choosing consumer group in Azure Functions

**Comment by mathewc** [comment]
This was already addressed a while ago in [this commit](https://github.com/Azure/azure-webjobs-sdk-script/commit/619cb178f3c22425b78660092d20a1b14fc87ea3). It will be released to Azure Functions in about a week. You can see an example [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/sample/EventHubTrigger/function.json) showing use of the new `consumerGroup` metadata property.

**Comment by MikeStall** [comment]
We also added ConsumerGroup to the EventHubTrigger attribute in the SDK, so this is fully fixed.

**Comment by bojingo** [comment]
Old closed issue, but I really wish ConsumerGroup would have been a property of the "AddReceiver" method. Reason: On the EventHubTrigger, because it is an attribute, the value has to be a compile-time constant. We are trying to make all the configuration-driven. "AddEventProcessorHost" solves this, but not as conveniently, IMO.
