### ISSUE TITLE
[Queue] inconsistency: null output shouldn't queue a "null" message

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#707]
For [Queue] binding (or any IAsyncCollector-compatible binding), assigning the out parameter to null  shouldn't queue a mesage. 

```
            public static void FuncWithOutTNull([Queue(OutputQueueName)] out PocoMessage value)
            {
                value = null;
            }
```
This is queueing a "null" string.  It shouldn't do anything.

**Comment by mathewc** [comment]
@MikeStall Can this be closed now?
