### ISSUE TITLE
FastLogger Should handle Table deletions

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#708]
While the host us up and running, if the FastLogger table is deleted from Table storage, it doesn't get recreated, and no logs are written.

The logger should optimistically write to the table and handle 404s by creating the table if it no longer exists.

**Comment by mathewc** [comment]
Also, we should change the name of the Default table created from "AzureFunctionsLogTable". The core SDK is independent of Azure Functions, and people will want to use FastLogging outside of AzureFunctions.

**Comment by MikeStall** [comment]
(commit comment from https://github.com/Azure/azure-webjobs-sdk/commit/dd176eed31aecd6d46e1df6bec1490cd6975f340 had typo referring to this bug. That commit was actually for #819 )

**Comment by mathewc** [comment]
I opened https://github.com/Azure/azure-webjobs-sdk/issues/832 for the table rename suggestion which was part of this issue above.
