### ISSUE TITLE
Make IArgumentBindingProvider<T> internal again?

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#713]
This interface was opened up to support binding extensibility (the ability to customize an existing binding). See wiki [here](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/Binding-Customization) for more information.  Specifically, we had users ask for the ability to add an IDictionary binding to our built in TableAttribute binding (see original issue [here](https://github.com/Azure/azure-webjobs-sdk/issues/517)). We used this interface to enable that.

I believe Mikes new binding stuff (ConverterManager) may support this in a more natural way. We should move the TableAttribute extensibility on top of that to verify.

**Comment by MikeStall** [comment]
We can cleanly solve this with the new CoverterManager approach.  Also related to https://github.com/Azure/azure-webjobs-sdk/issues/887
