### ISSUE TITLE
Webjobs.Extensions - Running Timer Trigger functions from mulitple instances

### ISSUE THREAD

**Issue by manums** [Azure/azure-webjobs-sdk#720]
Our intent is to have a timer based function processing some records from DB but I should also be able to scale out. This function will also do application specific data processing as part of it and call other web APIs and WCF Services. Hence we are looking for a solution which can be scaled out as per our need.

I read about Singleton being used by default. Is there a way where I can configure same function to run by multiple instances without blob lease?  If there is any alternative way to achieve this please suggest.

**Comment by mathewc** [comment]
The coordination mechanism for TimerTrigger across instances is blob leases, and that isn't configurable. This is described in more detail [here](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger). Note that this isn't a lock per invocation of your scheduled function, it is a startup time lock, so there is very little contention.

What issue do you have with blob leases?

**Comment by manums** [comment]
Thanks for link Timer Trigger and Singleton locks. This was more of a question than an issue. We need suggestions for below scenario.

There is a function which we would like to trigger from webjob at regular intervals like once in a min or so. We also want this function to run simultaneously from other instances when Scaled out, since there are not much locking resources. Can you suggest which extension can be used in this scenario if not TimerTrigger? or alternate proven solutions for this scenario.

**Comment by mathewc** [comment]
One pattern people use is a intermediary queue - you can queue the work items to be processed in the queue, and have a job function (QueueTrigger) that is monitoring that queue. This queue processing will scale as you add more instances.

So you could have the timer job running, and once per minute it discovers and enqueues the work that is needed, allowing it to be scaled out.

**Comment by jamesbascle** [comment]
I have a number of TimerTrigger webjobs that I need run on every instance of the job host.  It is to keep a local cache of data up to date.  Since the Singleton is strictly enforced on the TimerTrigger jobs, this is not doable, causing me to have to instantiate them myself in an infinite loop task that runs along side the job host.

This is obviously not ideal.  There really should be a way to let US decide whether we want it to be a singleton or not, just like every other trigger type.
