### ISSUE TITLE
ServiceBusTrigger - Automatic Lock renew bug

### ISSUE THREAD

**Issue by diogoguiomar** [Azure/azure-webjobs-sdk#724]
**"If the function runs longer than the PeekLock timeout, the lock is automatically renewed."**

True, although if the default Lock Duration is set (for example) 60 secs, here is what happens:
- Lock is renewed until message Complete();
- If it goes beyond those 60 sec default time:
- Message gets back on the queue (like an implicit Abandon()) when it Complete().

So at the end I get the message completed and a duplicate back into the queue

Simple test:
(in this case Lock Duration is set to 60 sec)

```
public class Program
{
    public static void Main()
    {
        JobHostConfiguration config = new JobHostConfiguration();
        config.UseServiceBus();
        JobHost host = new JobHost(config);
        host.RunAndBlock();

        Console.ReadLine();
    }
}
```

```
public class Functions
{
    public async Task ProcessQueue([ServiceBusTrigger("sbqueue")] BrokeredMessage message)
    {
        try
        {
            Console.WriteLine("New message triggered");
            Console.WriteLine("### Thread for message is going to sleep for 70 sec");
            Thread.Sleep(70000);
            Console.WriteLine("### Message processed and Completed");
        }
        catch (Exception exception)
        {
            Console.WriteLine("Abandoning");
        }
    }
}
```

**Comment by mathewc** [comment]
Correct - that is ServiceBus SDK behavior. The recommendation is to set the duration high enough to meet your application needs. Do you have another suggestion?

**Comment by diogoguiomar** [comment]
Since the max lock time that we are able to set is 5 minutes and we can't increase it, I'll always have a duplicate everytime my processing takes more than 5 minutes.

I tried to set autocomplete to false (so I could workaround with a "manual" way to renewlock) but had no effect at all.

**Comment by isabekyan** [comment]
Do have the same issue.
[This article](https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-webjobs-sdk-service-bus/) says 
> If the function runs longer than the PeekLock timeout, the lock is automatically renewed.

Is there **actual** documentation on Service Bus Queue Web Jobs?

**Comment by diogoguiomar** [comment]
According to Service Bus Queue configure options (I tested and it worked) for lock duration:
"The minimum value allowed is 5 seconds. The maximum value allowed is 5 minutes, and the default is 30 seconds."

No matter the time you set, the automatic Renew works (almost) like a charm. Although if (behind the scenes) the renew lock is used, there will be always a copy of the message sent back to the Queue (implicit Abandon()), even if it completes.

It seems the problem is not about Automatic renew or not, but what it does behind the scenes when it's renewed

**Comment by abramelin** [comment]
I think the reason may be a time skey between your computer running your app and the service bus computers. I have the issue in my dev environment (local computer) but not in production (running on Azure Web App servers). It seems that Automatic Lock Renewal does not compensate for time skews, thus renewing the lock too late if local time is behind service bus time.

When I receive a message I can look at my local time (DateTime.UtcNow) and compare with the messages brokeredMessage.LockedUntilUtc and see that the time difference is 28 seconds _more_ than my LockDuration (set on the queue at creation time). So I need to "manually" renew the lock before the lock actually runs out.
