### ISSUE TITLE
Is there a way to intercept function invocation?

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#734]
In the purpose of logging and make it transparent, I'd like to be able to intercept/override the methods before and after function invocation? Is it possible now? if not, is is something you're considering to add?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by christopheranderson** [comment]
I'm not sure if we have pre/post hooks for invocations. Mathew should be able to answer that. This might turn into a feature request.

**Comment by abatishchev** [comment]
Having such hooks would greatly improve the SDK in my opinion, also help us (at MPSIT Engineering), to have better logging at least.

**Comment by christopheranderson** [comment]
Is the existing logging mechanism insufficient in some way? Is there something we could do to make it better?

**Comment by abatishchev** [comment]
Please send some pointers where to look at?

We've tried `out TexWriter log` but this 'pollutes' function signature and body, also each function has to explicitly opt-in into logging this way. We're looking for something more transparent/lowerer level.

**Comment by christopheranderson** [comment]
We've got the `out TextWriter log` which is the way of associating log output to a particular invocation. We also have the WebJobs Dashboard which allows you to see input/output data for each Function, execution duration, etc. Are you familiar with that dashboard?

**Comment by abatishchev** [comment]
Yes, of course :) Here's the thing (it's related to https://github.com/Azure/azure-webjobs-sdk/issues/735): we write and then read logs programmatically as part of out end-to-end test. We didn't find another way to keep track which jobs were triggered by which messages.

**Comment by mathewc** [comment]
We've discussed allowing pre/post hooks before, and I thought we had a feature request logged for it, but I just looked and couldn't find it. I do think that would be a good idea.

Not exactly what you're asking for I don't think, but we do log [Started/Completed](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Loggers/TraceWriterFunctionInstanceLogger.cs#L27) events through our TraceWriter infrastructure. You can add your own TraceWriter instance to the `JobHostConfiguration.Tracing,Tracers` collection, using specific trace source.

**Comment by jamesbascle** [comment]
Check out my post in this thread https://github.com/Azure/azure-webjobs-sdk/issues/716

If you don't mind getting down and dirty into an IoC-based AOP framework, it'll do ya.

**Comment by VenkateshSrini** [comment]
Is there we can have something like ActionFilters like MVC. We have been using to extend the functionality of API greatly with this. Is that possible

**Comment by humbleice** [comment]
Intercepting WebJobs would be helpful for incorporating Application Insights.  I'm currently creating an operation context in the body of each job in order to correlate the job's telemetry data, but if that context could be created before the WebJob fires and finalized when it ends it would greatly simplify the code inside the job.

**Comment by jamesbascle** [comment]
Humble, check out my last post and link - this is exactly what I do to log messages from all functions to an external logging server.

**Comment by abatishchev** [comment]
Telemetry/AI is also what we need the interception for. Looking for an organic, built-in, extensible way to achieve this.

**Comment by brettsam** [comment]
We're tracking first-class AI integration here: https://github.com/Azure/azure-webjobs-sdk-script/issues/727

**Comment by humbleice** [comment]
@brettsam Is that conversation just for Functions or applicable for WebJobs in general?

**Comment by mathewc** [comment]
I just created a new feature issue to track this. I'll close this one and we can continue any feature discussion there, thanks everyone :)

**Comment by VenkateshSrini** [comment]
Can you please share the link to the new feature

**Comment by jamesbascle** [comment]
https://github.com/Azure/azure-webjobs-sdk/issues/980
