### ISSUE TITLE
Correlate queue messages, id is different between what is sent and what is received

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#735]
I try to keep track of job's status so try to correlate between the messages sent to queue and messaged received by queue and triggered function.

Here's how I'm sending message:
```csharp
var message = new CloudQueueMessage(Guid.NewGuid().ToString(), Guid.NewGuid().ToString());
message.SetMessageContent(content);
awaitqueue.AddMessageAsync(message);
```

Here's how I intercept message upon receiving:
```csharp
public class CustomQueueProcessor : QueueProcessor
{
	public override Task<bool> BeginProcessingMessageAsync(CloudQueueMessage message, CancellationToken cancellationToken)
	{
		return base.BeginProcessingMessageAsync(message, cancellationToken);
	}
}
```

But both `message.Id` and `message.PopReceipt` are different from what was sent. Why?

**Comment by abatishchev** [comment]
Bump.

**Comment by abatishchev** [comment]
@christopheranderson please take a look. We have to create custom queue processor/factory to write to custom blob to track queue. And this works so-so and for queue only. Nothing similar for instances for timers.

**Comment by mathewc** [comment]
The changing ID/PopReceipt values are not done by the WebJobs SDK. You can see this if you try a simple sample via the Azure Storage SDK directly. The following code:

```csharp
var queueClient = storageAccount.CreateCloudQueueClient();
CloudQueue queue = queueClient.GetQueueReference("test");

queue.Clear();

string messageId = Guid.NewGuid().ToString();
string popReceipt = Guid.NewGuid().ToString();
string value = Guid.NewGuid().ToString();
var messageIn = new CloudQueueMessage(messageId, popReceipt);
messageIn.SetMessageContent(value);
Console.WriteLine(string.Format("Sent: Id={0}, Pop={1}, Value={2}", messageId, popReceipt, value));
queue.AddMessage(messageIn);

var messageOut = queue.GetMessage();
Console.WriteLine(string.Format("Received: Id={0}, Pop={1}, Value={2}", messageOut.Id, messageOut.PopReceipt, messageOut.AsString));
```

Produces the following output (notice the ID/Pop values are different, but content is the same):

Sent: Id=17d25109-3595-4b0f-a7d4-ace6e97aa3a7, Pop=9b8def7a-3c18-4585-a9e2-8d0ab71f6f5f, Value=0a9aa0c9-c207-4d86-bb6b-d8ce0636e144

Received: Id=cd1e636e-8215-4e6a-afdc-a9c7b6da77b4, Pop=AgAAAAMAAAAAAAAAbx26tdjB0QE=, Value=0a9aa0c9-c207-4d86-bb6b-d8ce0636e144

**Comment by abatishchev** [comment]
Yes, that's exactly my point.
The only content is the same so to correlate we need to deserialize it and read some custom property (correlation id) so it should be there in the first place.
Why webjobs host writing a bunch of trace into blobs doesn't write something what could assist in the correlation?

**Comment by abatishchev** [comment]
Please reopen.

**Comment by mathewc** [comment]
I closed this issue because the title "Correlate queue messages, id is different between what is sent and what is received" specifically asked why the IDs of queue messages are different on send/receive. I investigated and determined that this is expected Azure Queues behavior.

If there is some feature request that can be tracked as a separate issue.
