### ISSUE TITLE
WebJob calls for non-existent queue, shows high queue dependency failure rate in Application Insights

### ISSUE THREAD

**Issue by gibwar** [Azure/azure-webjobs-sdk#741]
I've recently added some Application Insights telemetry capture to my web jobs and noticed some very odd dependency failures from the web jobs SDK. I have not been able to track down where they are coming from within the framework, but have been able to isolate it to the web job itself by having custom properties being added by a `TelemetryInitializer`.

It seems that every minute, two calls are made to Azure queues that don't exist, each with a random GUID attached to the queue name. Naturally, these queues don't exist on my storage account and therefore cause a 404 to be returned as well as a failed dependency to be automatically logged by AI.

This has led to over 1,800 failed calls on the Azure Queue, and with an empty queue to process, has caused the queue dependency failure rate in AI to go over 60% in the last 12 hours, which prevents me from being able to alert on real failures.

Here are some of the recent queue calls at the time of writing:

    [2016-06-03 09:40:16] https://{account}.queue.core.windows.net:443/azure-webjobs-host-a931fef7daac4e6f8df146b925db9568?comp=metadata, result: 404
    [2016-06-03 09:40:15] https://{account}.queue.core.windows.net:443/azure-webjobs-host-7595fb2a38494c159d4609d30acff9cc?comp=metadata, result: 404
    [2016-06-03 09:39:16] https://{account}.queue.core.windows.net:443/azure-webjobs-host-a931fef7daac4e6f8df146b925db9568?comp=metadata, result: 404
    [2016-06-03 09:39:15] https://{account}.queue.core.windows.net:443/azure-webjobs-host-7595fb2a38494c159d4609d30acff9cc?comp=metadata, result: 404

As a work around, I plan to add a `ITelemetryProcessor` to search for and filter out these failed events so that the instrumentation can provide a better view. However, this doesn't actually fix the problem/answer why the web job is looking for queues that don't exist.

**Comment by gibwar** [comment]
After digging through the source code, and spent a lot of head scratching in the `JobHostContextFactory` it looks like this _might_ be related to the fact that it's a continuous job (processing incoming queue messages) and checking to see if it should shut down or abort. I found where it's calling `HostQueueNames.GetHostQueueName(hostInstanceId.ToString("N"))` (around `...WebJobs.Host\Executors\JobHostContextFactory.cs:186`), which generates the above `azure-webjobs-host-{guid}` queue name, but I cannot figure out why it's generating a new id on each call.

**Comment by mathewc** [comment]
Queries to random queues _definitely_ should not be happening. The azure-webjobs-host-{guid} queue you reference is the control queue for the host, used for Dashboard invoke/abort/etc. messages. The mapping is 1:1 host to queue. We'll look into this and see if something strange might be happening. Thanks for reporting.

**Comment by mathewc** [comment]
With Dashboard logging enabled, there are two control queues that the JobHost will monitor for new messages. These **azure-webjobs-host-{guid}** queues you reference are used for Dashboard invoke/abort/etc. messages. One is for all instances of a particular JobHost (taking scale out into account), and the other is for each specific instance of the JobHost.

Note that if you're not using the Dashboard, you can disable it via `config.DashboardConnectionString = null'. These control queues will then no longer be monitored.

**Comment by pratap284** [comment]
Hi Mathew, 

Are you suggesting to use 'config.DashboardConnectionString = NULL' as an appsetting on the webjobs so that these queues doesn't get created?
