### ISSUE TITLE
Support for dynamic subscriptions? 

### ISSUE THREAD

**Issue by nibras85** [Azure/azure-webjobs-sdk#742]
I'm creating multiple subscriptions to a topic programmatically. Each subscriber will apply a filter based on a message property (based on a [SqlFilter](https://azure.microsoft.com/en-us/documentation/articles/service-bus-dotnet-how-to-use-topics-subscriptions/#_create-subscriptions-with-filters)).  Does the WebJobs SDK support this?

**Comment by mathewc** [comment]
No not currently. If you look at ServiceBusTriggerAttribute, to subscribe to a topic, both a topic and a subscription must be specified (e.g. `[ServiceBusTrigger("mytopic", "mysubscription")]`).

**Comment by christopheranderson** [comment]
Closing this since mathew answered this and we don't have a plan to support.

**Comment by flipchart** [comment]
Being able to specify the parameters to `ServiceBusTrigger` without constant values is a really big deal for us. In our case we want to run the same web job code, but with different topics and subscriptions based on configuration values. We can't use them because config values aren't constant.

**Comment by nieve** [comment]
Can you not at least remove the sealed from the attribute to allow users to customise this behaviour?
