### ISSUE TITLE
Gap between call

### ISSUE THREAD

**Issue by chibiliplop** [Azure/azure-webjobs-sdk#743]
I try to use the TimerTrigger for my webjob. Unfortunately i have a Gap of 5sec between each call. Let me explain i try to call my webjob every 1minutes. I do it as follow : 
` public static async Task Callback([TimerTrigger("00:01:00", RunOnStartup = true)] TimerInfo timerInfo)`

My problem is the gap between call. Every time the schedule is called 1minute and 5 seconds later. This is a big issue since my webjob collect data for a T instant and really need to be call each minutes without gap between.

Is something i can do? Is the lock system can be an problem i mean if the blob is lock for 60second the time to unlock and find out if we can run another schedule.

**Comment by mathewc** [comment]
It sounds like what you are saying is that you've scheduled your function to run once a minute, but your function (due to _your_ business logic) can run for over a minute? By design, we won't invoke another instance of your function if one is already outstanding. I.e. the next schedule interval starts _after_ the current invocation completes.

If this is the case for you, one option might be for your timer function to offload the long running work via queue or something.

Also, TimerTrigger and the other extensions live in the Extensions repo. Please log issues for them [there](https://github.com/Azure/azure-webjobs-sdk-extensions/issues), thanks :)

**Comment by chibiliplop** [comment]
My function never run over a minute. All the treatment take no more than 8sec in the worst case. I completely understand the way you work and it make sense to stop any invocation while one is running. You say that the next schedule interval starts after current invocation completes, do you mean that the timer firing after 1minute + processing time of the function ? In that case why the gap is always 5sec either if the function take 6seconds or 3 seconds to process ?

**Comment by mathewc** [comment]
Regarding the next scheduling, no that is not what I meant. I meant that we won't start another while one is already in progress. If your function takes less time than the interval, then you should be called on schedule regularly every minute.

The Singleton blob lease take for TimerTrigger is not a per invocation thing - it's a startup time thing. Your function will only be running on one instance (if you're scaled out). Once running, each invocation involves no locking.

What version of the Extensions package are you using? I'll try to repro this morning.

**Comment by chibiliplop** [comment]
So it's supposed to work as I was expected.
I use the version 1.0.1 of the Webjobs Extensions and webjob core is ate 1.1.2.
 The strange behaviour is when the program start. The log give me the next 5 occurrence of the schedule and the schedule is good: One time per minutes without gap. Unfortunately only the first call respect that schedule all the next occurrence is different from the planned schedule

**Comment by chibiliplop** [comment]
it's seem to work perfectly well with cron expression. Replacing the expression [TimerTrigger("00:01:00", RunOnStartup = true)] by [TimerTrigger("0 */1 * * * *", RunOnStartup = true)]. works well. Maybe the use of timestamp expression is implemented in an other way than cron.
