### ISSUE TITLE
Bug: DateTime argument cannot be passed from Dashboard to function execution (JSON deserialization bug)

### ISSUE THREAD

**Issue by hakenr** [Azure/azure-webjobs-sdk#748]
Hi,
when you publish a function with DateTime argument, it requires DateTime to be passed exactly in "O" format (as it is converted using StringToDateTimeConverter).It is currently not possible to pass valid DateTime from the Dashboard to the function as the string gets modified during deserialization.

The CallAndOverrideMessage is correctly JSON-serialized and passed through Queue.
As the host deserializes the message, the DateTime arguments get "converted":
![image](https://cloud.githubusercontent.com/assets/12828888/16063717/8bde7934-329b-11e6-85d0-9a46d6735a32.png)

The working repro is available here (only important files extracted):
https://github.com/hakenr/JsonDateTimeSerialization

**Comment by mathewc** [comment]
Thanks for taking time to construct a detailed repro :) Can you also share your actual job function definition (unless I missed it in your repo)? We'll take a look, thanks.

**Comment by hakenr** [comment]
Hi @mathewc!
My job function definition is as simple as
``` csharp
[NoAutomaticTrigger]
public void ExecuteDateRange(BusinessKind businessKind, DateTime dateFrom, DateTime dateTo)
{
	sapConnector.ImportCounterValues(businessKind, dateFrom, dateTo);
}
```
...but you can use any function which takes DateTime as the argument. In fact the issue will probably occur even if you use `string` as the argument type and pass parsable DateTime as its value (because it is related to incorrect deserialization of Dictionary<string, string> where there is no knowledge of the original argument type).

I tried to debug the repro I created and the pain is in the `PolymorphicJsonConverter`. If you remove the `[JsonConverter(typeof(HostMessageConverter))]` attribute from `HostMessage` the issue disappears.

If you try to step into `PolymorphicJsonConverter` the issue occurs in its `ReadJson` method where you call `serializer.Populate(json.CreateReader(), target)`.
``` csharp
public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
{
	// initial checks removed for better readability

	JToken json = JToken.ReadFrom(reader);

	Type typeToCreate = GetTypeToCreate(json) ?? objectType;

	object target = Activator.CreateInstance(typeToCreate);
	serializer.Populate(json.CreateReader(), target);  // <--- Put your breakpoint here
	return target;
}
```
The `json` instance there holds correct value "2016-05-14T15:05:23.9880814+02:00" and the `target` gets populated with "05/14/2016 15:05:23 +02:00".
