### ISSUE TITLE
WebJob SDK Queue Support for Storage Emulator

### ISSUE THREAD

**Issue by martinfletcher** [Azure/azure-webjobs-sdk#753]
I am getting this error with the latest Storage Emulator and SDK:

Unhandled Exception: System.InvalidOperationException: Failed to validate Microsoft Azure WebJobs SDK Dashboard Account.

This issue i raised in the #53 issue item, and this https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/ docs page.

Any help would be great.

**Comment by mathewc** [comment]
I assume you're using our latest prerelease package from myget? If so, then to configure for the emulator, your connection string values should look like below. I just tried this and it works for me. If it's not working for you, please point me to a repro project. I'm using emulator version v4.3.

```xml
  <connectionStrings>
    <add name="AzureWebJobsDashboard" connectionString="UseDevelopmentStorage=true" />
    <add name="AzureWebJobsStorage" connectionString="UseDevelopmentStorage=true" />
  </connectionStrings>
```

**Comment by coderangerdan** [comment]
Doesn't work for me at all, i have emulator v4.5 and latest v1.1.2 WebJobs so why isnt it working?

**Comment by mathewc** [comment]
The emulator changes are only available in the prerelease builds. Prerelease version 2.0.0-beta1 includes this support, or you might choose to use latest from our myget feed https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds.
