### ISSUE TITLE
BindingFactory shouldn't take a ConverterManager as a constructor parameter

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#756]
ConverterManager lets you set up a bunch of typeA -> typeB conversions. But from what I can tell, it's only used by one of the (currently) 6 BindTo\* methods. Some of the help text explains that ConverterManager is skipped for specific methods, but it seems easier to just require an IConverterManager is (optionally) passed into the single method that requires it.

**Comment by MikeStall** [comment]
We'll get this with   https://github.com/Azure/azure-webjobs-sdk/issues/686
