### ISSUE TITLE
Remove BindingFactory.AddValidator

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#757]
We already have AddFilter which can act as both a filter and a validator. I don't see anyone actually using AddValidator anywhere and I'm not sure it adds much value over AddFilter.

**Comment by mathewc** [comment]
What do we need to do here?

**Comment by brettsam** [comment]
I proposed a bunch of extension API improvements -- this is one of them. Not needed ASAP.

**Comment by lindydonna** [comment]
@brettsam Should we move this to the next milestone?

**Comment by MikeStall** [comment]
Will get this as part of  https://github.com/Azure/azure-webjobs-sdk/issues/686
