### ISSUE TITLE
The usage API does not return any data

### ISSUE THREAD

**Issue by panchagnula** [Azure/azure-webjobs-sdk#758]
https://github.com/Azure/azure-webjobs-sdk/pull/744  the change from this pull request doesn't have any data. Below are guidelines from Mike Stall

The volume api requires new logging instrumentation. Old bits won’t emit it. I don’t know exactly what the deployment schedule was; but old function instances running old instances won’t emit it. If they were hotpatched to new instances, then they should emit. 

Here are specific steps for below:
Update the connection string here to point to the function storage string:
https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Dashboard/Web.config#L4 

F5 the Dashboard project from VS. 

Use fiddler to call, something like this:
http://localhost:PORT/api/functions/volume?startTime=04/23/2016&endTime=2016-06-22T23:40:20Z&numberBuckets=65 

Put a breakpoint here to catch the api/functions/volume call:
https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Dashboard/ApiControllers/FunctionsController.cs#L211

**Comment by panchagnula** [comment]
this is now fixed I see data using this API

**Comment by mathewc** [comment]
So what changed? We haven't made any changes to the back-end.

**Comment by panchagnula** [comment]
no the API itself was not updated - but I noticed that the APP started showing usage data starting around noon of June 27th. short answer I am not sure what changed - did some sort of deployment happen yesterday?
