### ISSUE TITLE
Provide QueueTrigger for webjobs written in Java Code

### ISSUE THREAD

**Issue by mpujari** [Azure/azure-webjobs-sdk#759]
Seems like we don't have a way for having QueueTrigger written in Java for a webjob, all I find is .Net. I had asked this on [StackOverflow](http://stackoverflow.com/questions/38072495/can-we-write-azure-webjobs-with-queue-triggered-with-java) and they suggested to ask it over here.

**Comment by mathewc** [comment]
While we don't have plans to add Java support to the core WebJobs SDK (this repo), we do have a tracking item in the [Functions repo](https://github.com/Azure/azure-webjobs-sdk-script/issues/224) to track Java support. All the work we're doing for cross language support is going into [Azure Functions](https://azure.microsoft.com/en-us/services/functions/). Feel free to chime in on that issue.
