### ISSUE TITLE
GetQueueMetadata ClientOtherError 404

### ISSUE THREAD

**Issue by arangas** [Azure/azure-webjobs-sdk#765]
I have one webjob that sends queue messages, and another using a QueueTrigger to receive them. I'm fairly sure the messages are transmitting from one webjob to another without error. However, the related queue's PercentSuccess drops below 50% every day for a while. When I turn on diagnostic logging, I get messages that look like (broken up for readability and highlighted for emphasis):

- 1.0
- 2016-07-10T05:05:18.2221363Z
- **GetQueueMetadata**
- **ClientOtherError**
- **404**
- 6
- 6
- authenticated
- mystorageaccount
- mystorageaccount
- queue
- **"https://mystorageaccount.queue.core.windows.net:443/azure-webjobs-host-a1c8e88abf1d4b55b68c4c5f144ab71b?comp=metadata"**
- "/mystorageaccount/azure-webjobs-host-a1c8e88abf1d4b55b68c4c5f144ab71b"
- ed1c071c-0003-0049-0168-da67b4000000
- 0
- 100.117.108.31:49251
- 2015-12-11
- 447
- 0
- 126
- 0
- 0
- "Azure-Storage/7.1.2 (.NET CLR 4.0.30319.42000; Win32NT 6.2.9200.0)"
- "1e0e713b-6937-4f4e-8b2d-dcef724ccc92"

Is this how webjobs are supposed to behave? If so is it possible to change so that errors are not recorded in the logs? It's difficult to determine if there is a *real* problem in the queue.

I hope this is the right place to post this, as it appear to be related to the implementation of webjobs.

**Comment by mathewc** [comment]
When you say "broken up for readability" you don't mean that each of the bullet points above is a separate log entry I hope.

What do you have all the various diagnostic logs settings set to? Basically, help us set up a repro so we can investigate. Note that the 404 NotFound for the above control queue is expected and is not an error.

**Comment by arangas** [comment]
Haha no fortunately that is a single line, I just split it by the delimiter.

If 404s are expected on webjob control queues, the unfortunate side effect is that this causes a significant drop in the PercentSuccess storage diagnostics metric. I found it described in: [Metrics show low PercentSuccess or analytics log entries have operations with transaction status of ClientOtherErrors](https://azure.microsoft.com/en-us/documentation/articles/storage-monitoring-diagnosing-troubleshooting/#metrics-show-low-percent-success).

One workaround is to use a separate storage account for the webjobs queues, not monitor them, and use the StorageAccount attribute introduced in #395 to use queues for actual data in a different storage account.

It would be nice if there was a way for this to be filtered out on the Azure side of things though, as it probably isn't expected behaviour. :sweat_smile:

**Comment by mathewc** [comment]
Since we've had several complaints on this recently, I've opened up https://github.com/Azure/azure-webjobs-sdk/issues/770 to track the possibility of changing this behavior. Feel free to chime in there.
