### ISSUE TITLE
WebJobs deployed to a slot can't reach parent app's app settings

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-webjobs-sdk#772]
Is it a bug or a feature and well-known behavior that a webjobs host deployed to a non-prod slot cannot reach app settings from parent app, no matter whether they're set to slot-specific or not.

**Comment by davidebbo** [comment]
It's by design. Each slot has its own set of App Settings. Settings being slot-setting or not only affect the behavior during swap.

**Comment by abatishchev** [comment]
I see, this explains the behavior. I was under impression of inheritance, docs and blogs aren't clear enough. Thanks!

**Comment by patriksvensson** [comment]
@davidebbo Sorry for pinging you in a old and closes issue, Is there somewhere I can read about this that explains this in more greater detail?

**Comment by davidebbo** [comment]
@patriksvensson can you describe how the behavior you observe differs from what you expected? Based on that, I can help clarify.
