### ISSUE TITLE
Pause or stop the message processing.

### ISSUE THREAD

**Issue by phoxha** [Azure/azure-webjobs-sdk#773]
I have a webjobs app hosted in house (not on Azure).

For my processes I need to give users an option to stop/pause the message pump of a particular queue to process messages (I use a DB table to store the active/inactive queue). However, the messages should stay in the pump unprocessed. Once the user wants to restart the processing of that queue the message pump can continue. Defer method does not work here since it marks them with a flag and I can't retrieve the messages unless I know the guid etc.

How should this be handled?

When using the method below is there a way I can do a lookup before this method is triggered?
public static void SBBulkMigrationListener([ServiceBusTrigger("myqueuename")] BrokeredMessage m,
        TextWriter log)

**Comment by christopheranderson** [comment]
This might work today? @mathewc ?

**Comment by mathewc** [comment]
Currently the active job functions and queues to monitor are determined at startup time of the JobHost. There is no dynamic capability to start/stop a particular queue listener once the JobHost is running.

You can however use `DisableAttribute` which allows you to specify an app setting name (e.g. `[Disable(%DisableMyQueue%)]`) which will resolve the app setting named "DisableMyQueue" (you choose the name) to a boolean value and enable/disable the function.

**Comment by mathewc** [comment]
To add to what I said above there is another option that can enable more dynamic start/stop.

- use the overload of DisableAttribute that takes a Type. Apply `[Disable(typeof(MyProvider))]` to your function. That form of the attribute allows you to implement a boolean function to determine disable state
- you then just need to force a JobHost restart when the state should change. To do this, you'd pass a CancellationToken into your JobHost.RunAndBlock call, and cancel that token when you want to trigger a restart
- thus, you can determine dynamically when functions should start/stop (e.g. on a background timer, or via inline checks in other functions) and cause the host to restart and pick up the new enable value(s)
