### ISSUE TITLE
Expose WebJob Context Information To Custom TraceWriters

### ISSUE THREAD

**Issue by aaronhoffman** [Azure/azure-webjobs-sdk#774]
In an attempt to make reviewing/querying WebJob logs easier, I took advantage of the `JobHostConfiguration.Tracing.Tracers` collection and added a custom `SqlTraceWriter` to my WebJob project ([sample code here](https://gist.github.com/aaronhoffman/3e319cf519eb8bf76c8f3e4fa6f1b4ae)).

This works pretty well but can get somewhat confusing due to WebJobs being executed in parallel.

Would it be possible to expose some of the [WebJob Context](https://blog.kloud.com.au/2016/03/14/azure-webjob-logs-demystified/) information to the TraceWriter?

Either via a static class or by passing it into the `TraceWriter.Trace()` method perhaps?

The various *`InstanceId`s could be added to the SQL Table to help identify logs from the same job.

**Comment by christopheranderson** [comment]
Are there specific information on the context you'd like?

**Comment by aaronhoffman** [comment]
From: https://blog.kloud.com.au/2016/03/14/azure-webjob-logs-demystified/

`HostInstanceId`, `FunctionInstanceId`, `Function.FullName`, and the original message payload would be nice (for message queue trigger jobs).

And I'm not sure if it would be possible, but if there was a way to get a unique value identifying the Web Site instance and the `Deployment Slot` the webjob is running in, that would be great! I'm not sure if it's appropriate to pull a couple values from an environment variable or not... `WEBSITE_INSTANCE_ID` maybe?

**Comment by mathewc** [comment]
Related to #784 which asks for FunctionName.

**Comment by brettsam** [comment]
`TraceEvent.Properties` will now include function information -- available properties found here: https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Loggers/TraceEventExtensions.cs

**Comment by aaronhoffman** [comment]
I'd love to include this feature in a talk I'm giving in a couple weeks. What is the release schedule like for the related nuget package?

Looks like the last release was a 2.0.0 beta in July? https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.0.0-beta1 

49 commits behind current master https://github.com/Azure/azure-webjobs-sdk/compare/977072a...master

**Comment by mathewc** [comment]
@brettsam can get it up on our myget feed for you to access. We won't be doing nuget.org update for a while.
