### ISSUE TITLE
QueueTrigger for poison queues should peek messages, not delete them

### ISSUE THREAD

**Issue by stiiifff** [Azure/azure-webjobs-sdk#778]
Currently, when using a QueueTrigger for a poison queues, say for monitoring purpose, the poison messages are processed and then deleted from the poison queue ... which is somewhat counter-intuitive.
QueueTrigger should only peek messages for poison queues, either by convention if the queue name has the '-poison' suffix, or using an additional parameter in QueueTriggerAttribute e.g. 'bool PeekOnly'.

**Comment by abatishchev** [comment]
How would you differ from not yet processed and already processed messages then?

**Comment by mathewc** [comment]
Yes, I don't understand the problem. A poison queue is just like any other queue to be processed. If you've hooked up a job function to the queue, you want to process those failed messages like any other queue.

**Comment by stiiifff** [comment]
The use case I was trying to implement using QueueTrigger on poison queues was the following:
Send an administrative email whenever a new poison message is added to a poison queue (and expecting that the poison messages stay there so they can be re-processed later aka moved back to the main processing queue).
I understand that using a Peek, it is not feasible to differentiate not yet peeked from already peeked messages (cfr. @abatishchev's comment).
I reverted to using a recurring TimeTrigger and peeking the n first poison messages (if any), then sending an admin email.
Maybe just a warning in the docs ? :)

**Comment by mathewc** [comment]
The intent for poison queue processing is to have a job function that processes the queue by inspecting the messages in detail after they are dequeued, either retrying the processing or deciding that the payload is completely bad and moving it off to some other archive/log and sending notifications as needed.
