### ISSUE TITLE
Support .NET framework 4.6.1

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk#783]
We should allow folks to build WebJobs targeting .NET 4.6.1

We should look at this when we also look at dotnet core support.

**Comment by davidebbo** [comment]
There should be nothing blocking this today. Are you running into a specific issue?

**Comment by abatishchev** [comment]
We're targeting 4.6.1 from day 1 and everything works for us. Both web host and console app.

**Comment by JSkimming** [comment]
Same here, targeting 4.6.1 just fine.

**Comment by davidebbo** [comment]
Thanks both for confirming!
