### ISSUE TITLE
Blob scanning strategy can have gaps due to clock skew

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#785]
`ScanBlobScanLogHybridPollingStrategy` determines whether a blob is 'new' or not by comparing its timestamp to the local machine's time. I've seen instances where the clocks differ by a couple of seconds, causing a new blob to be missed in the poll. The blob is eventually seen by the log-scanning strategy that's also running, but it'd be nice if we can tighten this up to prevent the gap. I think this could be done by storing the newest `LastModifiedTime` of the blobs we've looked at rather than the `UtcNow` time of the local machine.

https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategy.cs#L181

**Comment by christopheranderson** [comment]
Same story as #786, Brett
