### ISSUE TITLE
Blob scanning a large container at startup can take several minutes

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#786]
In my tests on a local machine, I'm seeing the initial blob scan of a container take roughly 160 milliseconds per blob (to check receipts, etc). As you get more and more blobs, the time that it takes to perform the initial scan on startup gets longer and longer. We've seen our Script tests timeout after a minute of waiting for ~500 blobs to be scanned on startup.

The impact here is that if you have container with a large number of blobs, any new blobs may take several minutes before they are processed after the host starts.

We may be able to take an approach similar to that of Timers and store the 'latest processed time' in its own blob and read from there on startup, skipping all of the ones we know we've already looked at.

https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Blobs/Listeners/ScanBlobScanLogHybridPollingStrategy.cs

**Comment by christopheranderson** [comment]
@brettsam - could you look at this? @shobak101 isn't likely to have time in the near time to address this.

**Comment by brettsam** [comment]
Baseline -- Running locally with ~1100 blobs in a container, it takes right around 3.5 minutes for my machine to complete a full scan. This is because it takes roughly 150ms to process each blob and we do this sequentially.

### **Option 1: Store a 'Latest Blob Processed' timestamp in Blob storage.** 
If we know where we left off, we don't need to re-scan old, already-processed blobs during every restart. This is what is currently implemented in #824.

**Pros:** Doesn't matter how many blobs you have in the container, it'll never re-scan old blobs.
**Cons:** The fact that we scan all blobs on startup is a bit of a 'failsafe'. It means that even if something fell through the cracks, it'll get re-evaluated when the host starts.

I've mitigated the con by doing a couple of things:
- I only write the 'Latest Blob Processed' timestamp after we've successfully created Queue messages.
- If there were any errors in creating the Queue messages, I make sure to keep the timestamp rolled back to the earliest failure so that if the host were to crash, we'd pick it back up.
- I roll the timestamp back by 1ms so that we re-process the last item again upon startup. This is to account for the chance of timestamp rounding that blobs do. You could process a blob at 12:00:00 and have a new blob come in at 12:00:00.1, but it's timestamp would be rounded down to 12:00:00. By rounding the timestamp back slightly, you guarantee this will be picked up on a restart.

### **Option 2: Improve the ~150ms-per-blob scan time** 
I also looked into ways to shorten the processing time on large containers like this, knowing that for most already-processed blobs we look at, we'll find the receipt and move on. I noticed:
- The minimum number of requests we make to blob storage, even when we don't need to process the blob, is 2. This is because we first check if the blob exists, then check the receipt. If I flip those two checks, I can get this down to 1 for the most-likely case. If the blob receipt exists, we don't really need to check if the blob exists because we wouldn't process it anyway. That cuts a request out and makes things a little quicker.
- We can parallelize the requests. Right now we do everything serially. I did it the easiest (code-wise) way and fired off ~1100 tasks and waited for them all to complete.

Doing both of these, got my ~1100 scan down from 3.5 minutes to about 40 seconds. The bottleneck here is the number of outbound HTTP requests that .NET will allow you to make. I think it defaults to 2 which means you have lots of idle Tasks waiting for others to complete.

There may be other options here, too -- like during startup, call ListBlobs to load a max of 10,000 blob receipts (the max blobs we'll scan at once) into memory. Then do in-memory comparisons to determine whether we need to process the blob. If we don't find it in our list, make an actual HTTP call to verify. Once the initial scan is over, get rid of that list and go back to the 'query always' method. Big queries like that are much faster than doing 10,000 little queries. It wouldn't catch everything but it would save HTTP calls and get this running even faster.

**Pros:** Wouldn't have the subtle cons like Option 1. 
**Cons:** Doesn't scale as nicely -- still need to process each item individually up to the max of 10,000.

Maybe there's other options? Option 1 gives the fastest results, but Option 2 feels 'safer' since it's not tweaking the startup process.

**Comment by brettsam** [comment]
@mathewc @fabiocav @MikeStall -- PR #824 has been sitting for a while awaiting signoff. I get the sense that maybe it's not the right approach -- I wrote up some thoughts here and would like some feedback so I can get this moving forward.
