### ISSUE TITLE
Add a singleton output binding for Tables

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#790]
The Table binding supports a singleton input binding allowing you to bind to a single table record. However, it does **not** support a singleton output binding. I.e. `[Table("test", "PK", "RK")] out MyItem` is not supported. For output, you currently have to use ICollector/IAsyncCollector.

This is inconsistent and confusing.

**Comment by MikeStall** [comment]
This is also relate dto https://github.com/Azure/azure-webjobs-sdk/issues/887  . Making Tables use the binding rules (like Queue) would drive consistency which would naturally fix this.

**Comment by mathewc** [comment]
Moving this to 2.0.0 because Mike is working on a bunch of changes now in Table binding and this will go along with those.

**Comment by MikeStall** [comment]
I think table updates in place. So it's really like an an In/Out binding.

**Comment by MikeStall** [comment]
This was fixed with the "make tables use IAsyncCollector rule" above, and there's a test in TableTests.cs for it.

**Comment by mathewc** [comment]
Awesome, thanks :)
