### ISSUE TITLE
Service Bus Trigger - Problems with parallel processing of messages from queue post scaling out [When one instance is stuck processing a message]

### ISSUE THREAD

**Issue by manums** [Azure/azure-webjobs-sdk#791]
We have a web job which is scaled out to 5 instances listening to a service bus queue via service bus trigger. For one of the queue message processing was stuck with running status for long time (> 2 hours). During this time no other instance picked up other messages from **this queue**, but same web job was processing messages from other queues on the same instance.

Messages kept on piling up in the queue while the message was stuck processing the message. We had to kill the function invocation from WebJob Dashboard, after which remaining queue messages started getting processed by other instances as well.

This is a typical scale out scenario and we expected all instances to be processing messages concurrently from one queue. Even if one message is stuck on one of the instance, other instances should process new messages from the queue.  Can you help us understand this behavior, if there is any configuration that we are missing which can cause this behavior? 

LockDuration is set to 5 mins, AutoRenewTimeout is set to 10 min and Duplicate detection window is set to 1 min.

**Comment by mathewc** [comment]
Our ServiceBus trigger relies solely on the ServiceBus SDK MessageReceiver for receiving messages. Each job function across scaled out instances uses its own MessageReceiver, configured based on the settings you've set in [ServiceBusConfiguration](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusConfiguration.cs). We just configure the MessageReceiver with the options you configure.

It would be interesting for you to try to isolate this outside of the WebJobs SDK by creating a simple console app that uses a MessageReceiver configured the same way, and determine if you see the same behavior in that setup. That would mean that it's an error with the way SB is being configured.

**Comment by manums** [comment]
Thanks for the reply. We tested with another webjob which processes from other queue. When scaled out to 5 instances, this webjob (with servicebustrigger) was able to process messages in parallel as expected. There are no differences(in settings) between this new Test queue and the one which had issue. Both of these queues are under same service bus.

We will continue to root cause and provide more details if we find anything. Do you like the bug to be closed till then?

**Comment by mathewc** [comment]
Closing for now. Please reopen if you find an issue with the WebJobs SDK itself. Thanks :)
