### ISSUE TITLE
Is there a way to keep an azure function warm 24/7?

### ISSUE THREAD

**Issue by kdenz** [Azure/azure-webjobs-sdk#793]
With Lambda its done by having another function to retrigger itself at a fixed time interval, i wonder if at current stage something similar or better can be done with Azure functions?

**Comment by mathewc** [comment]
What are you trying to accomplish? In the Dynamic plan (Functions default) we efficiently spin down resources when we can based on whether your function needs to run or has any work to do.

You can always choose to run your functions in the Classic plan in Basic or Standard, which allows you to enable the Always On feature for your Function App.

**Comment by christopheranderson** [comment]
Closing this. Mathew's answer is correct.
