### ISSUE TITLE
Newtonsoft Dependency Problem

### ISSUE THREAD

**Issue by markolbert** [Azure/azure-webjobs-sdk#794]
I'm getting the following exception when running a webjob console app under Net46/VS 2015:

> System.IO.FileLoadException was unhandled
>   FileName=Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
>   FusionLog==== Pre-bind state information ===
> LOG: DisplayName = Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
>  (Fully-specified)
> LOG: Appbase = file:///C:/Data/Programming/ConnellCampaigns/src/UploadProcessor/bin/Debug/net46/win7-x64/
> LOG: Initial PrivatePath = NULL
> # Calling assembly : Microsoft.Azure.WebJobs.Host, Version=1.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
> 
> LOG: This bind starts in default load context.
> LOG: Using application configuration file: C:\Data\Programming\ConnellCampaigns\src\UploadProcessor\bin\Debug\net46\win7-x64\UploadProcessor.exe.Config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
> LOG: Redirect found in application configuration file: 6.0.0.0 redirected to 6.0.0.0.
> LOG: Post-policy reference: Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
> LOG: Attempting download of new URL file:///C:/Data/Programming/ConnellCampaigns/src/UploadProcessor/bin/Debug/net46/win7-x64/Newtonsoft.Json.DLL.
> WRN: Comparing the assembly name resulted in the mismatch: Major Version
> ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
> 
>   HResult=-2146234304
>   Message=Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>   Source=Microsoft.Azure.WebJobs.Host
>   StackTrace:
>        at Microsoft.Azure.WebJobs.Host.Protocols.PersistentQueueWriter`1.<EnqueueAsync>d__0.MoveNext()
>        at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
>        at Microsoft.Azure.WebJobs.Host.Protocols.PersistentQueueWriter`1.EnqueueAsync(T message, CancellationToken cancellationToken)
>        at Microsoft.Azure.WebJobs.Host.Loggers.PersistentQueueLogger.LogHostStartedAsync(HostStartedMessage message, CancellationToken cancellationToken)
>        at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.LogHostStartedAsync(IFunctionIndex functionIndex, HostOutputMessage hostOutputMessage, IHostInstanceLogger logger, CancellationToken cancellationToken)
>        at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__b.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__0.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__f.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__0.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Microsoft.Azure.WebJobs.JobHost.Start()
>        at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
>        at UploadProcessor.Program.Main(String[] args) in C:\Data\Programming\ConnellCampaigns\src\UploadProcessor\Program.cs:line 21
>   InnerException: 

Based on another issue I saw on github I removed Microsoft.Azure.WebJobs from project.json, saved the file, re-added it and saved the file again. But the problem still persists.

project.json:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.Azure.WebJobs": "1.1.2",
    "Newtonsoft.Json": "9.0.1"
  },

  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.Configuration": "4.0.0.0"
      }
    }
  }
}
```

program.cs:

```
    public class Program
    {
        public static void Main(string[] args)
        {
            var config = new JobHostConfiguration();

            if( config.IsDevelopment )
            {
                config.UseDevelopmentSettings();
            }

            JobHost host = new JobHost( config );
            host.RunAndBlock();
        }

    }
```

functions.cs:

```
    public class Functions
    {
        public static void ProcessQueueMessage( [QueueTrigger( "file-uploaded" )] TestMessage msg, TextWriter log )
        {
            log.WriteLine( $"file {msg.SourceFile} uploaded for processing" );

            log.WriteLine( $"created and disposed instance of ConnellContext" );
        }
    }

```

testmessage.cs:

```
    public class TestMessage
    {
        public string SourceFile { get; set; }
    }

```

What am I doing wrong?

**Comment by christopheranderson** [comment]
@markolbert - sorry we missed this somehow. Are you still seeing this?

**Comment by markolbert** [comment]
Sorry, but somehow the time zone stuff caught us up again. I have it on my calendar for 1 PM California time, 3 PM Central time.

If you can’t do at 3 PM Central time, please propose some other times that work for you and we’ll pick one.


-          Mark

**Comment by lindydonna** [comment]
@markolbert It looks like you replied to the wrong thread, can you take a look at the issue again?
