### ISSUE TITLE
Blob Only Storage Accounts not supported as primary storage account

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#797]
They aren't supported as the "primary" storage account (since we need access to queues, etc.). We need to document this, and ideally find a way to throw an error if the wrong type of account is used.

**Comment by christopheranderson** [comment]
Remaining work: Hide these blob storage accounts in the portal and document that we don't support them.

Closing this issue and tracking work in the docs issue list: https://github.com/Azure/Azure-Functions/issues/38
