### ISSUE TITLE
EventHubTrigger error: "Controller has already started"

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#800]
We've gotten a few reports on this issue now. We need to investigate to see how we allow the JobHost to get into this state, and prevent it.

https://social.msdn.microsoft.com/Forums/en-US/bb2f3726-82ec-43d2-b7fa-4b964b969da2/systeminvalidoperationexception-controller-has-already-started?forum=AzureFunctions

https://social.msdn.microsoft.com/Forums/azure/en-US/3bbdef39-58eb-4085-a336-c1088f6f6a73/issue-while-binding-multiple-functions-to-the-same-event-hub-trigger?forum=AzureFunctions

**Comment by aesalon** [comment]
Thanks for opening this issue; adding my Function's function.json as per request. Any other files that would be helpful?

Of note: I've also been experiencing binding issues with this same function which casue an exception like this: mscorlib: Object of type 'Microsoft.WindowsAzure.Storage.Table.TableQuery`1[Submission#0+AggregatedSettings]' cannot be converted to type 'System.Linq.IQueryable`1[Submission#0+AggregatedSettings]'.

When I removed the bindings and accessed table storage output and event hub input explicitly from within the function (going through the CloudStorageAccount.Parse, CloudTable, TableQuery<T> etc dance), I stopped getting the exception covered by this issue.

[function.zip](https://github.com/Azure/azure-webjobs-sdk/files/439811/function.zip)

**Comment by mathewc** [comment]
@MikeStall Is looking into this one. He can provide more details

**Comment by MikeStall** [comment]
notes: I can't repro the error (either in a Function or even in a standalone EventHub where I intentionally make some bad calls) The log in the original appears to be coming from: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHostManager.cs#L135

**Comment by christopheranderson** [comment]
This might be related to some of the consumer group issues we've seen?

**Comment by MikeStall** [comment]
The exception happens when multiples *threads* call EventProcessorHost.RegisterEventProcessorAsync on the same instance. (there's some TLS going on there) 
EventHubConfiguration has a global map of EventProcessorHosts. 
So I'm theorizing one way this could happen is if there's a refresh (file update), and ScriptHostManager orphans the old files (but the EPH is still active) and starts listening on the new files (same EPH), and so we end up with a double listen.

**Comment by MikeStall** [comment]
Fixed https://github.com/Azure/azure-webjobs-sdk/commit/669c35660533fe2ac713d0da606bed231ef66e7a

**Comment by stephlocke** [comment]
Hi, I'm getting issue. I guess in relation to wanting two eventhub related functions, & not because I upgraded to 0.5 today. Looking forward to next version with fix!

**Comment by MikeStall** [comment]
@stephlocke  - are you saying you have 2 functions that are listening on the same eventhub path?

**Comment by aesalon** [comment]
Coming back to this: I encountered this issue again via two Functions listening to the same EventHub (using separate consumer groups.) When both are enabled, the error occurs.

**Comment by MikeStall** [comment]
@aesalon  - thanks for comment. That's also related to https://github.com/Azure/azure-webjobs-sdk-script/issues/570 . Both of those bugs have been fixed, so you should see it resolved in the next release.

**Comment by aesalon** [comment]
@MikeStall Fantastic! Thank you. :)
