### ISSUE TITLE
Null exception when reading blob stream

### ISSUE THREAD

**Issue by markolbert** [Azure/azure-webjobs-sdk#803]
I have a simple loop that reads and processes lines from a text file stored on Azure:

```
public async Task<bool> Import()
{
    if( !ImportInit() ) return false;

    string line;

    try
    {
        // *** this next line is where the exception occurs ***
        while( ( line = _tr.ReadLine() ) != null )
        {
            bool okay = await ImportLine( line );
            if( !okay ) return false;
        }
    }
    catch( Exception e )
    {
        int i = 9;
        i++;
    }

    return ImportCleanup();
}
```
It throws the following exception, which appears to be from somewhere inside the Azure code base:

> > System.NullReferenceException occurred   HResult=-2147467261  
> > Message=Object reference not set to an instance of an object.  
> > Source=Microsoft.WindowsAzure.Storage   StackTrace:
> >        at Microsoft.WindowsAzure.Storage.Blob.BlobReadStreamBase.ConsumeBuffer(Byte[]
> > buffer, Int32 offset, Int32 count)
> >        at Microsoft.WindowsAzure.Storage.Blob.BlobReadStream.Read(Byte[] buffer,
> > Int32 offset, Int32 count)
> >        at Microsoft.Azure.WebJobs.Host.Blobs.WatchableReadStream.Read(Byte[]
> > buffer, Int32 offset, Int32 count)
> >        at System.IO.Compression.SubReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
> >        at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
> >        at System.IO.StreamReader.ReadBuffer()
> >        at System.IO.StreamReader.ReadLine()
> >        at UploadProcessor.TextFileImporter`1.<Import>d__13.MoveNext() in
> > C:\Programming\ConnellCampaigns\src\UploadProcessor\import\TextFileImporter.cs:line
> > 53   InnerException:
> 

The exception is reproducible (i.e., re-running the app always throws the exception on the same line from the file).

The stream I'm reading comes from a QueueTrigger method:

```
public async void ProcessUploadedFile( [QueueTrigger( BlobStorage.UploadQueue )] UploadMessage msg, [Blob("uploads/{BlobPath}", FileAccess.Read)] Stream blobStream, TextWriter log )
{
    StringWriter swLog = new StringWriter();

    LoggerConfiguration logConfig = new LoggerConfiguration()
         .WriteTo.TextWriter( swLog );

    var config = new JobHostConfiguration();
    if( config.IsDevelopment ) logConfig = logConfig.WriteTo.TextWriter( log );

    ILogger logger = logConfig.CreateLogger();

    logger.Information( $"{msg.SourceFile} uploaded for processing" );
    logger.Information( $"File type is {msg.UploadType.ToString()}, primary ID is {msg.PrimaryID}" );

    if( blobStream == null )
    {
        logger.Information( $"blobStream is undefined; is file available?" );
        return;
    }

    // if we got a zip file, make sure it has only one entry
    string ext = Path.GetExtension( msg.SourceFile ) ?? "";
    Stream src = null;
     if( ext.ToLower() == ".zip" )
     {
        logger.Information( $"{msg.SourceFile} is a zip archive, checking to see if it contains only one file" );

        ZipArchive archive = new ZipArchive( blobStream, ZipArchiveMode.Read );

        switch( archive.Entries.Count )
        {
            case 0:
                logger.Fatal( "Uploaded zip file is empty" );
                break;

            case 1:
                src = archive.Entries[ 0 ].Open();
                break;

            default:
                logger.Fatal( "Uploaded zip file has more than 1 entry" );
                break;
        }
    }
    else src = blobStream;

    if( src == null ) return;

    TextReader tr = new StreamReader( src );

    switch( msg.UploadType )
    {
        case UploadType.CountyVoter:
            await ImportCountyVoterDataAsync( msg.PrimaryID, tr, logger );
            break;

        default:
            logger.Fatal( $"Unknown import file type ({msg.UploadType.ToString()})" );
            break;
    }
}

private async Task ImportCountyVoterDataAsync( int countyID, TextReader tr, ILogger logger )
{
    ITextFileImporter importer = _importFactory.GetCountyVoterImporter( countyID, tr, logger );
    if( importer == null )
    {
        logger.Fatal( $"Couldn't find a TextFileImporter Type supporting CountyID = {countyID}" );
        return;
    }

    bool okay = await importer.Import();

    if( okay )
    {
        logger.Information( $"import succeeded" );
    }
    else logger.Fatal( "import failed" );
}
```
I can ignore the exception, and skip the line to continue processing...but I'd like to find out what's wrong.

Thoughts?

**Comment by markolbert** [comment]
An addendum...

On a hunch -- since I am new to async/await programming -- I converted all the code to synchronous methods. Voila! All 21,000 records were successfully imported.

What am I missing about reading blobs asynchronously?

**Comment by mathewc** [comment]
The issue is your method signature: you need to change it to return a **Task**, e.g.:

```csharp
public async Task ProcessUploadedFile(...)
```

**Comment by markolbert** [comment]
Sigh. An obvious error. Thanx!
