### ISSUE TITLE
Output binding to table storage with fsharp

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-webjobs-sdk#805]
I'm new to Azure Functions.

Any idea on how I can bind out to a Azure Storage Table with F#? I'm attempting to use ICollector (taken from C# example which works fine) but unfortunately it is not being recognised which I thought it would be as documented here - https://azure.microsoft.com/en-us/documentation/articles/functions-reference-csharp/. (Yes, I see that this is ref to C#)

Code:

```
open System
open System.IO

type Job = {
    PartitionKey :string; 
    RowKey: string; 
    Name :string
}

let inputPath = Environment.GetEnvironmentVariable("input")
let input = File.ReadAllText(inputPath)
let message = sprintf "F# script processed queue message '%s'" input
System.Console.Out.WriteLine(message)

let b = [{PartitionKey = "Key"; RowKey = Guid.NewGuid().ToString(); Name=input}]

let outputTable = new ICollector<Job>()
outputTable.Add(b)
```

With wanting to keep with F# as much as I possibly can with Azure Functions, if F# is yet to be fully supported, would you recommend a strategy of using C# for bindings and using F# for helper / supporting methods?  Plus, are there any gotcha's I need to know about?

Warmest regards,

Garrard.

**Comment by mathewc** [comment]
Hey, good news. We're about to roll out the new F# programming model for Azure Functions. F# will no longer be out of proc and will be first class like C# (i.e. no reading/writing to/from input files as above). You'll be able to bind to an ICollector directly in your function signature.

Take a look at the [updated samples](https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample) for a better idea on what to expect.

All that said, you can actually output multiple items using the current model. You just need to write multiple entities to the output as JSON. The runtime will parse and apply them implicitly to an ICollector. This is the model other script languages like BAT, Bash, etc. work.

**Comment by garrardkitchen** [comment]
Excellent news!  Thanks @mathewc

**Comment by mathewc** [comment]
FYI: You can actually try out this new version in advance of it becoming fully public by setting a simple app setting on your site. Details can be found [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Function-Runtime-Versioning).

**Comment by garrardkitchen** [comment]
Thanks @mathewc, I'll do this shortly.

**Comment by garrardkitchen** [comment]
Hi @mathewc, I've followed the instructions and now I'm seeing this? Is this correct?  I do not see any new F# sample code either.

![image](https://cloud.githubusercontent.com/assets/993890/18140334/fba12ca0-6fac-11e6-8c2c-97273ae9ef26.png)

**Comment by mathewc** [comment]
Yes that's right - minor portal bug with advanced versions, we're already tracking that.

We haven't updated the templates yet or the portal, just the runtime. However, on that runtime you can use the new F# model. Try with some of the samples I pointed you to, and modify to use ICollector.

**Comment by garrardkitchen** [comment]
Ah, ok. Will do. Thanks once again @mathewc.

**Comment by mathewc** [comment]
FYI - The templates have been updated in our repo here: https://github.com/Azure/azure-webjobs-sdk-templates/tree/dev/Templates they're just not live yet. So if you want to start from one of our templates, you can look at the updated ones there.

**Comment by garrardkitchen** [comment]
Thanks @mathewc. I'll take a look now

**Comment by garrardkitchen** [comment]
Hi @mathewc, I finally got there!

```
#if !COMPILED
#I "../../bin/Binaries/WebJobs.Script.Host"
#r "Microsoft.Azure.WebJobs.Host.dll"
#endif
#r "Microsoft.WindowsAzure.Storage"
open  Microsoft.WindowsAzure.Storage.Table
open System
open Microsoft.Azure.WebJobs.Host;

type Job() =
    inherit TableEntity()    
    member val Name = "" with get, set


let Run (input: string, outputTable: ICollector<'Job>, log: TraceWriter) =  
    log.Info(sprintf "F# script processed queue message '%s'" input)

    let b = new Job() 
    b.PartitionKey <- "Key"
    b.RowKey <- Guid.NewGuid().ToString()
    b.Name <- input
    
    b |> outputTable.Add
```    

Works as expected.

Thanks for all your help today.  Very much appreciated.

Warmest regards,

Garrard.

**Comment by mathewc** [comment]
Awesome :)
