### ISSUE TITLE
Job fails to stop

### ISSUE THREAD

**Issue by markanewman** [Azure/azure-webjobs-sdk#809]
I have several always on continuous WebJobs. During maintenance windows we stop the WebJobs to prevent them from reporting our other services are down and they can't connect. Depending on how long they have been running sometimes they will error out and stick in the "Disabling" status. When I look at the logs, I see the below. The only work around I have found is kill the Kudu process in process explorer, let that recycle the jobs, then stop them normally.

In the below example we chose a time when there should not have been any incoming processing. 

[08/31/2016 20:41:20 > 0991c1: SYS INFO] WebJob is still running
[09/01/2016 04:51:28 > 0991c1: SYS INFO] WebJob is still running
[09/01/2016 11:17:39 > 0991c1: SYS INFO] Status changed to Disabling
[09/01/2016 11:21:00 > 0991c1: SYS ERR ] Job failed due to exit code -1

**Comment by davidebbo** [comment]
This sounds more like a core WebJobs issue than something related to the WebJobs SDK (which despite the similar name, is a rather different thing). Could you open issue on https://github.com/projectkudu/kudu instead?
