### ISSUE TITLE
Service Bus topic trigger stops when using F#

### ISSUE THREAD

**Issue by JonCanning** [Azure/azure-webjobs-sdk#818]
The trigger works when it is set up, then after a while it will stop processing messages and the queue will build. I can wake it back up by opening the function page in Azure portal and going to 'Develop' to view the logs.

I think I've found a workaround by setting up a C# trigger on the same topic which seems to keep it alive.

**Comment by mathewc** [comment]
Are you using a Dynamic or Classic hosting plan? If the latter, the issue is likely that you don't have Always On enabled for your Function App, which means it will idle out after a period of no incoming requests. Always On keeps it alive for background processing.

**Comment by JonCanning** [comment]
I'm using Dynamic

**Comment by mathewc** [comment]
In Dynamic this shouldn't be happening. @tohling Any ideas? Sounds like a bug we'll need to repro.

**Comment by mathewc** [comment]
@JonCanning To confirm, you're saying that the workaround C# function you created was another ServiceBus trigger? Our triggering logic is not language specific, so I wouldn't expect that to help.

@tohling Confirmed to me that we are rolling out some updates today that will likely address this issue.

**Comment by JonCanning** [comment]
Yes, I created a function from the C# template in the same app, subscribed it to the same topic, and it seemed to keep the whole app running.

**Comment by christopheranderson** [comment]
Our updates have finished rolling out. Are you still seeing this issue, Jon? Are you using ~0.5?

**Comment by JonCanning** [comment]
I started having problems with timer triggers not firing too, so I deleted and recreated everything and it's been OK.
