### ISSUE TITLE
Make logging more resilient in the event of host crash + usability long running events

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#819]
Discussed on an internal thread. From @MikeStall -- 

What I’d like to do is:
-	Don’t send a “start” event – that would be too slow since it would guarantee double the log messages in the host path case. (say the function runs for 1 sec; we don’t want to emit 2 log msgs) 
-	Instead, send the heart  beat message and defer it for 10 seconds, and send every 30 sec after that.  That means quick 1s functions won’t be penalized.

**Comment by lindydonna** [comment]
From triage discussion: this causes a problem because it causes some logging events to be missed entirely. The reason for the change in behavior relative to Web Jobs is to improve logging performance.

@brettsam Will your "graceful shutdown" improvements make this issue less troublesome?

**Comment by lindydonna** [comment]
@MikeStall Please come up with a design that handles these failure cases and we'll try to make it fit for RC.

**Comment by brettsam** [comment]
If anything, the graceful shutdowns makes matters worse because now we'll deliberately shut the host down for timeouts. We don't have a way to grab metadata from all in-flight functions and log that they've been killed. 

I'm not sure what "potentially optimize failure cases" means here. We'll log if there's a failure. But if there's a host shutdown and you're in the middle of a 1-minute function run, we have no success or failure -- the function simply isn't complete when the host exits. And we don't forcefully kill any functions on a shutdown. If they don't exit quickly when we cancel the shutdown token (only available to C#), we'll never get any details about them.

Mike's design above is meant to let quick-running functions get by without paying any logging penalty and long-running functions save a heartbeat so we have a record of them.

**Comment by morsh** [comment]
Hi,
I'm hoping this is the right place to add those comments, but I'm experiencing the same problems with the following scenarios:
1. exceptions with requiring the function file like missing npm peckages exceptions
2. unhandled async exceptions like having an unhandled exception while expecting a callback

Basically I would expect monitoring the concurrent active node js requests and adding some process level exception handling.

**Comment by MikeStall** [comment]
#826 and #708 should fix this.
