### ISSUE TITLE
Allow EventHub triggers to bind to byte[] 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#825]
[EventHubTrigger("hub")] byte[] one --> binds to one event as a byte[]

[EventHubTrigger("hub")] byte[][] many--> binds to multiple events. 

This is technically a breaking change since byte[] today would bind to a multiple of type 'byte'; not a single of type byte[].

**Comment by christopheranderson** [comment]
@MikeStall - do you want to pick this up soon?

**Comment by mathewc** [comment]
Yeah, hopefully we can get this out in the next release.

**Comment by MikeStall** [comment]
If we register a Item --> byte[] with the converter manager, this should work.
