### ISSUE TITLE
Google webhooks

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk#828]
Would like to be able to process [Google webhooks](https://www.google.com/webmasters/tools/home). Currently, in order to do that, google requires ["property verification"](https://www.google.com/webmasters/tools/home) (via DNS or a file accessible from a web property).

**Comment by mathewc** [comment]
Did you mean to create this issue in the Azure Functions repo ([here](https://github.com/Azure/azure-webjobs-sdk-script/issues))?

**Comment by SeanFeldman** [comment]
Sigh... yes. If only the name of the repo had the word "functions" :)
Will move. Thank you @mathewc
