### ISSUE TITLE
Rename AzureFunctionsLogTable

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#832]
In the context of the core SDK, there are no "Azure Functions". We should name this something like "AzureWebJobsHostLogs" or something like that.

Code where this is hard coded is [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Logging/LogFactory.cs#L40).

**Comment by lindydonna** [comment]
This is going to be a breaking change, but should be done now vs. later.

**Comment by MikeStall** [comment]
Fix in commit.
