### ISSUE TITLE
Dashboard not showing parameters for 'in progress' functions

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#833]
When using "fast logging", an in progress function details page does not show any of the parameter info, etc.:

![capture](https://cloud.githubusercontent.com/assets/1056548/18653689/7104d130-7e90-11e6-9c7c-7d0b42dad4e8.PNG)

Compare that to a completed function:

![capture](https://cloud.githubusercontent.com/assets/1056548/18653713/92d451fa-7e90-11e6-955d-107c5353e31b.PNG)

We should be seeing the parameter info and other details for in progress functions.

**Comment by mathewc** [comment]
I think this may be related to https://github.com/projectkudu/AzureFunctionsPortal/issues/568, i.e. have the same underlying cause.

**Comment by MikeStall** [comment]
Fixed.
