### ISSUE TITLE
In new Dashboard, Search button leads to yellow screen of death

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk#840]
Steps:

- In a function app, go to dashboard
- Click on Search Blobs

Result: ASP.NET Yellow Screen of Death

Note: it works in the non-beta dashboard

**Comment by MikeStall** [comment]
This is a dup of https://github.com/Azure/azure-webjobs-sdk/issues/677 
They're crashing due to unregistered (Ninject) components. 

We should disable both buttons:  
1. Search blobs doesn't work in the Azure Functions; 
2. 'About' just shows the indexer logs; but Functions logging doesn't use indexing.

**Comment by davidebbo** [comment]
Note that the same issue repros if you're using the new Dashboard with a legacy site. So we can't just disable the buttons as that would regress existing functionality. But potentially we could disable them only for Function apps, and fix the issue for legacy sites.

**Comment by MikeStall** [comment]
I meant disable when used for Functions.  New dashboard on a legacy site should work.

**Comment by davidebbo** [comment]
Understood. So it sounds like there are two distinct work items:

1. Disable those buttons for functions
2. Fix the error for legacy scenarios

**Comment by MikeStall** [comment]
Actually, I think I can make SearchBlobs just work outright in Functions.  I'll go for that. 
For legacy - I just tested that and it works. Are you sure it's  a legacy site?

**Comment by davidebbo** [comment]
The legacy site I had tried on may have been dirty (might have been switched back and forth between old/new before), so let’s ignore if it doesn’t repro for you.

**Comment by lindydonna** [comment]
@MikeStall Did the disable button issue get fixed in your recent commits?

**Comment by MikeStall** [comment]
@lindydonna  - It's fixed in this PR: https://github.com/Azure/azure-webjobs-sdk/pull/846 
The PR is outstanding and hasn't been committed yet.

**Comment by MikeStall** [comment]
PR was commited. This is fixed.
