### ISSUE TITLE
net46 console app as WebJob

### ISSUE THREAD

**Issue by markolbert** [Azure/azure-webjobs-sdk#842]
I have a console app, using net46 as the target framework, which I would like to upload as a WebJob to Azure. The app works flawlessly on my local development machine.

While I can upload it to Azure via FTP, when Azure tries to start the job it crashes with an error involving a missing hostpolicy.dll file. 

How do I resolve this? Or is it not possible to use a net46 console app as a WebJob?

I used net46 as the target framework, rather than just using the default VS 2015 WebJob template, because I need to access an EF Core database defined in another assembly/project, and the EF Core tooling does not currently support creating class libraries; you have to engage in some trickery, involving creating an app, as a workaround. Unfortunately, the default WebJob template in VS2015 won't reference an exe as an ersatz dll.

- Mark

**Comment by davidebbo** [comment]
To help isolate, try running the exe by itself not as a WebJob, per [this page](https://github.com/projectkudu/kudu/wiki/Isolating-WebJobs-and-Deployment-script-issues).

**Comment by markolbert** [comment]
Thanx, David, I'd heard of Kudu, but hadn't tried using it yet.

After uploading the console app to a folder in the continuous jobs folder, I dropped into the folder via the Kudu console. I first tried running run.cmd, which generated an error (see below).

I then tried just running the console app itself -- UploadProcessor.exe -- and it ran fine within the Kudu console, just like it does on my development system.

Here's a listing showing the results of those two steps;

> D:\home\site\wwwroot\App_Data\jobs\continuous\UploadProcessor>run.cmd
> 'ï»¿UploadProcessor.exe' is not recognized as an internal or external command,
> operable program or batch file.
> 
> D:\home\site\wwwroot\App_Data\jobs\continuous\UploadProcessor>UploadProcessor.exe
> Found the following functions:
> UploadProcessor.Functions.ProcessVoterFactorMessage
> UploadProcessor.Functions.ProcessVoterBallotMessage
> UploadProcessor.Functions.ProcessEnvelopeSalutationMessage
> UploadProcessor.Functions.ProcessFactorMatchMessage
> UploadProcessor.Functions.ProcessWalkFileMessage
> UploadProcessor.Functions.ProcessPhoneFileMessage
> UploadProcessor.Functions.ProcessMailhouseFileMessage
> Job host started
> 

Those leading garbage characters in the first error message strike me as odd (all run.cmd has in it is a single line containing UploadProcessor.exe.

This almost strikes me as some kind of character set encoding problem. 

Thoughts?

- Mark

**Comment by markolbert** [comment]
Okay, a little more googling showed that, yes, it's an encoding problem. The run.cmd file, if created by VS, needs to be saved without the UTF-8 BOM, which requires going through Save As rather than just doing a typical Save. 

The uploaded stuff now runs fine under Kudu. Time to see  if it works as a WebJob.

Thanx for the help!

- Mark

**Comment by markolbert** [comment]
And it's a wrap! At least until the next problem comes along. Thanx!!!

**Comment by davidebbo** [comment]
Yeah, I've run into this BOM issue before. Very annoying...
