### ISSUE TITLE
Rename AzureFunctionsLogTable default table name

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#843]
Link to source [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Logging/LogFactory.cs#L40)

This is a core SDK logging feature and is not Functions specific. I suggest AzureWebJobsHostLog or something similar.

**Comment by lindydonna** [comment]
Duplicate of #832
