### ISSUE TITLE
Allow default Queue visibility timeout parameters to be customized

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#844]
Currently in our default QueueProcessor we hard code the visibility timeout for failed queue trigger invocations to `TimeSpan.Zero` (code [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs#L105)). While you can write and register your own custom queue processor to override this, we should provide a `JobHostQueuesConfiguration` knob at the host level that lets this default be set globally.

A configuration knob is particularly IMPORTANT in scenarios like **Azure Functions** where the possibility for users to write a custom QueueProcessor doesn't exist.

**Comment by mathewc** [comment]
Another question arose [here](https://stackoverflow.com/questions/40006372/azure-function-and-storage-queue-what-to-do-if-function-fails) asking for the ability to customize the invisibility timeout used when messages are dequeued.

**Comment by lindydonna** [comment]
Moving to Next since the request has come up from customers.

**Comment by kayomarz** [comment]
Thanks for adding this... its a nice feature!

I tried using the visibility timeout, setting it to 7 minutes but the queue message seems to become visible after a few seconds.

my host.json is:

    {
      "id": "6c8614e4e7a14c798439271d00bb0d23",
      "queues": {
        "visibilityTimeout": "00:07:00"
      }
    }

Does this seem ok? Does `"visibilityTimeout": "00:07:00"` correspond to 7 minutes?

This is with [azure-webjobs-sdk-script v1.0.10690](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.10690)

**Comment by mathewc** [comment]
Yes, that is the correct timespan format. I just tried this and it works for me as expected. Not that this setting controls the retry visibility for messages that fail processing. I.e. if your function fails, it will retry the message again after 7 minutes. You're not seeing that?

**Comment by kayomarz** [comment]
Thanks for the quick reply.

An App service is scaled out to two instances. Adding 1 single Item in
queue correctly triggers a queueTrigger(ed) job. However, In under a
minute, the second instance of  the queueTrigger also seems to get
triggered with the same queue message as the work item, even though the
first job is still running (the job runs for 5 mins)

Not sure if I'm doing something else wrong.

Now that I know that the visibility timeout is defined correctly, I'll
check if something else might be going wrong.

Thanks!

**Comment by dnlmcv** [comment]
Hi,

Still it is not working with azure functions. I've created an azure functions project in Visual Studio and configured the host.json file with following values: 
{
  "queues": {
     "visibilityTimeout" : "00:01:00"
    }
}
The messages are retried with 0 seconds timeout. Any input on this ?

Thank you

**Comment by dnlmcv** [comment]
@mathewc

**Comment by dnlmcv** [comment]
Hi @mathewc ,

Still it is not working with azure functions. I've created an azure functions project in Visual Studio and configured the host.json file with following values: 
{
  "queues": {
     "visibilityTimeout" : "00:01:00"
    }
}
The messages are retried with 0 seconds timeout. Any input on this ?

Thank you

**Comment by nickmkk** [comment]
Will the visibility timeout only apply to retried queue items or does it apply to newly added items to the queue as well?
