### ISSUE TITLE
Add Nuspec build validation

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#845]
I believe for the Extensions and Script repos, we have build validation in place to ensure nuspec versions match the actual required/referenced versions.

I don't think we have that enabled in this repo though. An instance [came up recently](https://github.com/Azure/azure-webjobs-sdk/pull/838) where this would have caught it.

@brettsam Can you add your validator to this repo as well? :)

**Comment by lindydonna** [comment]
Since it helps validation, should target 2.0.0-preview release
