### ISSUE TITLE
Support Append Blobs in triggers

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#858]
We have no support for Append Blobs today -- related to #859.

See original forum question: https://social.msdn.microsoft.com/Forums/en-US/ff949571-5056-4414-9a7b-4f9972f41187/updated-to-06-and-now-i-get-continual-framework-errors-in-the-log-any-ideas?forum=AzureFunctions

**Comment by moonytheloony** [comment]
Is this feature open to contribution?

**Comment by brettsam** [comment]
You're the third person to bring this up, which has it rising on my priority list. I'm going to take a look at it today to see if I can pull it together fairly quickly. Are you just looking for AppendBlob-as-trigger support?

**Comment by moonytheloony** [comment]
I can see that you fixed it already. May I contribute to some other pending item in the SDK?
