### ISSUE TITLE
Webjobs started before time with TimerTrigger

### ISSUE THREAD

**Issue by MrDesjardins** [Azure/azure-webjobs-sdk#866]
A job was supposed to run on a specific date and time and was fired before. 

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a webjob with SDK

2. The problem was with this configuration : 0 5 4 15 10 *

```
public static void ScriptABC([TimerTrigger("0 5 4 15 10 *")] TimerInfo timerInfo, TextWriter log)
{
    // Code here
}
```
3. We had a swap executed at Timer fired at 2016-10-**10T22:27**, the job got executed at Timer fired at 2016-10-10T**22:28**:52.4331974+00:00, 1 minute after.

#### Expected behavior

I expect to have this job only fired on [October 15 at 4h05min](http://cronexpressiondescriptor.azurewebsites.net/?Language=en-US&DayOfWeekStartIndexOne=false&Use24HourFormat=false&VerboseDescription=false&Expression=0+5+4+15+10+*). Timer fired at 2016-10-10T22:28:52.4331974+00:00.

#### Actual behavior

The job was launched at the wrong time. We are running on webjobs and multiple slots since few months. This job got added about 3 weeks ago, about 12 swaps got executed without firing this webjob.

#### Related information 

* Package version: 
```
  <package id="Microsoft.Azure.WebJobs" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Azure.WebJobs.Core" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Azure.WebJobs.Extensions" version="1.0.1" targetFramework="net461" />
  <package id="Microsoft.Web.WebJobs.Publish" version="1.0.12" targetFramework="net461" />
  <package id="ncrontab" version="3.1.0" targetFramework="net461" />
  <package id="WindowsAzure.Storage" version="7.0.0" targetFramework="net461" />
```
* I am using Azure with slots (prod and staging). Staging is having WEBJOBS_STOPPED to 1.

**Comment by davidebbo** [comment]
It sounds like the RunOnStartup behavior (see [wiki](https://github.com/Azure/azure-webjobs-sdk-extensions#timertrigger)). Though I believe the default should be false, so it's puzzling.

@mathewc any thoughts?

**Comment by brettsam** [comment]
A couple of things we can look at: 

1. If you look in your WebJobs host storage account, you should see a blob under `azure-webjobs-hosts/{hostid}/{functionname}/status`. We serialize the next (and last) scheduled invocation there. What is the value of that `status` blob? Since it sounds like you have two hosts, you should have two statuses. BTW -- You can open the blob in notepad; it's just JSON.
2. We do log on startup whether we're invoking the timer because it's (a) past due or (b) RunOnStartup is true. Unfortunately, that's only logged as Verbose so it likely won't help in this instance.

There have been quite a number of TimerTrigger fixes in our Extensions repo. Some examples that may be related to what you're seeing:

- https://github.com/Azure/azure-webjobs-sdk-extensions/pull/133
- https://github.com/Azure/azure-webjobs-sdk-extensions/pull/149

Are you able to move forward to take our [latest builds from MyGet](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)?

**Comment by brettsam** [comment]
@MrDesjardins -- please give our newest bits a try and reactivate if you continue seeing this. There have been quite a few Timer improvements since the build that you are currently using and I'm hopeful that this has already been fixed.

**Comment by boudinov** [comment]
Do you mean try WebJobs.Extensions version 2.0.0-beta2 ?

I have a similar issue where the a Continuous WebJob's timer function is run each time i do a slot swap. WebJob is automatically deployed with the web application (linked using Add/Existing project as Azure WebJob).
In settings.job i have "is_singleton": true
Timer function is set to run once 0 30 1 * * * with explicit set RunOnStartup = false
Staging slot has WEBJOBS_STOPPED set to true
Anyway, both slots have the same webjob storage configured.

WebJob has no versioning in assembly name, azure-webjob-hosts/ids/mystorageaccount contains a file MyCompany.WebJobs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.*.*  containing host id c1e27aa8fd0440dd972eb8bd05ec6b75.

What i notice in webjob logs is that HostInstanceId changes totally after each swap, but that sounds normal. What is stable and contains the host id are SharedQueueName, SharedDirectoryName, FunctionId, hearbeat etc..

I am adding couple of webjob logs files:
[FunctionCompleted_2519218889059582982_78cdca0d6212464aa0916b95eaf82a96.txt](https://github.com/Azure/azure-webjobs-sdk/files/618914/FunctionCompleted_2519218889059582982_78cdca0d6212464aa0916b95eaf82a96.txt)
[FunctionStarted_2519218889593500994_fc1bfd9cde664d2ca66d52c0859371f9.txt](https://github.com/Azure/azure-webjobs-sdk/files/618915/FunctionStarted_2519218889593500994_fc1bfd9cde664d2ca66d52c0859371f9.txt)
[HostStarted_2519218889615013920_b5e7f4081a114f06be6dc5dba0f75fb6.txt](https://github.com/Azure/azure-webjobs-sdk/files/618916/HostStarted_2519218889615013920_b5e7f4081a114f06be6dc5dba0f75fb6.txt)


Thanks
