### ISSUE TITLE
JobHostConfiguration ignores the StorageClientFactory

### ISSUE THREAD

**Issue by HerrKater** [Azure/azure-webjobs-sdk#867]
When specifying  StorageClientFactory instance in the JobHostConfiguration class, the JobHostConfiuration ignores this instance.

#### Repro steps
1. Create a webjob which gets called when an item is added to a queue storage
2. Make sure that the webjob throws an exception.
3. Create an inherited class of the StorageClientFactory that returns a queue client which retries the failed message only once. 
4. Specify an instance of this child StorageClientFactory in the JobHostConfiguration.
5. Start the webjob and put a message in the queue

#### Expected behavior

The webjob only gets triggered 2 times because we specified 1 as the retry count.

#### Actual behavior

The webjob will get triggered 5 times, which is the default behaviour.

#### Related information 

The bug is caused by a property called _services in the JobHostConfiguration class. It is a ConcurrentDictionary<Type, object> and it is used as a container for the different settings and their default values. 
It registers a base class of the StorageClientFactory in line 64 as default. The expected behaviour would be to overwrite it with the derived class. Because there is no EqualityComparer specified, when the child class gets registered, it doesn't overwrite the baseclass. Similarly, when the JobHost is asking for the StorageClientFactory, it returns the default base class as those two classes are not the same.

Suggested solution: specify an IEqualityComparer<Type> which returns true if the two classes are part of the same inheritance chain. Something like: x.IsAssignableFrom(y) || y.IsAssignableFrom(x);

* Links to source
https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/JobHostConfiguration.cs

**Comment by brettsam** [comment]
Would you mind showing your code for how you set this up? Specifically, what your StorageClientFactory class looks like and how you're setting up your JobHostConfiguration? It looks like we have at least one test (https://github.com/Azure/azure-webjobs-sdk/blob/master/test/Microsoft.Azure.WebJobs.Host.UnitTests/JobHostConfigurationTests.cs#L255-L268) for this scenario, so something different may be going on.

**Comment by HerrKater** [comment]
Please find my test code below:
I've seen the test, and I've checked the values of the _services properties, and for whatever reason it seems like it is doing the right thing, however it is still ignoring the retrycount because there are 5 exceptions in my log table.

` public class Program
    {
        static void Main()
        {
            using (IKernel kernel = new StandardKernel(new Bindings()))
            {
                var jobHostConfiguration = new JobHostConfiguration
                {
                    JobActivator = new JobActivator(kernel),
                    StorageClientFactory = new CustomClientFactory(ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ConnectionString)
                };
                var host = new JobHost(jobHostConfiguration);
                // The following code ensures that the WebJob will be running continuously
                host.RunAndBlock();
            }
        }


        public class CustomClientFactory:StorageClientFactory
        {
            private readonly string _connectionString;

            public CustomClientFactory(string connectionString)
            {
                _connectionString = connectionString;
            }

            public override CloudQueueClient CreateCloudQueueClient(StorageClientFactoryContext context)
            {
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(_connectionString);
                CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
                IRetryPolicy linearRetryPolicy = new LinearRetry(TimeSpan.FromMinutes(1), 1);
                queueClient.DefaultRequestOptions.RetryPolicy = linearRetryPolicy;
                return queueClient;
            }
        }
    }`

**Comment by brettsam** [comment]
I think I see the problem -- you actually want to change `jobHostConfiguration.Queues.MaxDequeueCount = 2;` You don't need a custom `StorageClientFactory` for this. 

`StorageClientFactory` is used for creating the client that we use to talk to your Queues. In this case, you're overriding the internal retry mechanism there. For example, if the client calls `Dequeue()`, it'll retry a certain amount of times if it gets a server error or timeout. That's all a part of the Azure Storage SDK and not really a part of WebJobs.

The `MaxDequeueCount` is used by WebJobs to determine how many times we should retry a failed function before moving it to the poison queue.

Give that a shot and let me know if it works as expected.

**Comment by HerrKater** [comment]
Thanks! It worked, the message is dequeued only two times, as expected. I only have one question, how do you specify an exponential backoff? at the minute the queue retries it immediately, which does not make too much sense, because if it failed first time because of a timeout, it is quite likely that if we retry immediately we just make things worse.

**Comment by brettsam** [comment]
You can create your own `QueueProcessorFactory`, pluggable in `jobHostConfiguration.Queues.QueueProcessorFactory`. There's an example of a custom factory that creates a processor here: https://github.com/Azure/azure-webjobs-sdk/blob/cfcf9e36c68d4d740dc70bbc3aa07c3dd633f397/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L610-L664

You can even see a note in the processor where it explains where you could apply your own backoff algorithm based on the `DequeueCount` of the message: https://github.com/Azure/azure-webjobs-sdk/blob/cfcf9e36c68d4d740dc70bbc3aa07c3dd633f397/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L658-L659
