### ISSUE TITLE
Has the async functionality changed with V2

### ISSUE THREAD

**Issue by tbertenshaw** [Azure/azure-webjobs-sdk#872]
With version 1 of the SDK I was able to use DI to inject configuration into the class which i could reference from within the Queue function. However I get an error on startup with V2 indexing the ProcessUploadQueueMessage function. I change the function signature to be static the error disappears but i cannot now reference my config from within the queue function. 

```
	public class FileUploadQueue
	{
		internal IApplicationConfiguration m_config;

		const string FileUploadQueueName = "%services.fileupload.queue.name%";

		public FileUploadQueue(IApplicationConfiguration config)
		{
			m_config = config;
		}

		public async void ProcessUploadQueueMessage([QueueTrigger(FileUploadQueueName)] UploadedContentNotification message,[SendGrid] SendGridMessage mailMessage, TextWriter log)
		{
	           //...
		}

	}
```

**Comment by mathewc** [comment]
What is the error message you get? Can you provide the rest of the repro code?

**Comment by mathewc** [comment]
I think we discussed this issue on issue https://github.com/Azure/azure-webjobs-sdk-extensions/issues/34. We made some breaking changes to the SendGrid extension in the latest beta builds.
