### ISSUE TITLE
WebJobs SDK dashboard - Remove legacy table reading 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#876]
After we split the logs to be stored across multiple tables; we needed to temporarily add a shim (LegacyTableReader) to read the old format. Remove the temp code.

**Comment by lindydonna** [comment]
This is cleanup, so moving to -release

**Comment by MikeStall** [comment]
Fixed with https://github.com/Azure/azure-webjobs-sdk/commit/a759f497f66a58d7b577f9fd7b85573dce529ae8
