### ISSUE TITLE
500 from dashboard

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#879]
Customer reported a 500 from dashboard. 
https://social.msdn.microsoft.com/Forums/en-US/0323e54d-aae3-4ffc-8449-d6c5c3f4f660/function-app-monitoring-not-working?forum=AzureFunctions&prof=required

Several APIs, /azurejobs/api/functions/definitions  are returning 500.

**Comment by davidebbo** [comment]
We should disable custom errors as we do for Kudu. Even though it's considered 'wrong', given that the code is OSS and the site is protected by scm endpoint, there is real downside. And it make diagnostics a lot easier as user can directly include the stack in their report.

**Comment by christopheranderson** [comment]
**Notes from triage:**
Need to poke the PowerBI template folks to properly set the dashboard settings. No further action to improve our APIs needed at this point.
