### ISSUE TITLE
Expose Logging APIs

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#880]
We've had frequent customer requests to expose the logging APIs. 

Make ILogReader and the corresponding dashboard REST APIs publically supported.

**Comment by mathewc** [comment]
Moving this to 2.0.0 release because we've added new public surface area for logging that we need to finalize.

**Comment by MikeStall** [comment]
Given the Functions & AppIsnights integration (See https://azure.microsoft.com/en-gb/updates/azure-functions-now-integrated-with-application-insights/ ) , we don't want to expose a dedicated logging API.
