### ISSUE TITLE
Service Bus: Every new binding creates a new MessagingFactory; breaks IBinder scenarios

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk#881]
When you ask for an `IBinder` for every function invocation (which languages like node do by default in Script) and use it to create a new Service Bus binding, we end up creating a new TCP connection for each invocation. This quickly exhausts the 250 connection limit in Dynamic SKUs.

**Comment by brettsam** [comment]
Note -- I've got one possible fix (not sure it's the best approach yet) with #877.

**Comment by brettsam** [comment]
Looping in others for discussion: @fabiocav @mathewc

From this article: https://azure.microsoft.com/en-us/documentation/articles/service-bus-performance-improvements/. 

On re-using factories:
> Service Bus client objects, such as QueueClient or MessageSender, are created through a MessagingFactory object, which also provides internal management of connections. You should not close messaging factories or queue, topic, and subscription clients after you send a message, and then re-create them when you send the next message. Closing a messaging factory deletes the connection to the Service Bus service, and a new connection is established when recreating the factory. Establishing a connection is an expensive operation that you can avoid by re-using the same factory and client objects for multiple operations. You can safely use the QueueClient object for sending messages from concurrent asynchronous operations and multiple threads.

On not re-using factories:
> **Multiple factories:** all clients (senders in addition to receivers) that are created by the same factory share one TCP connection. The maximum message throughput is limited by the number of operations that can go through this TCP connection. The throughput that can be obtained with a single factory varies greatly with TCP round-trip times and message size. To obtain higher throughput rates, you should use multiple messaging factories.

Some possible solutions here:

**1. Cache `MessagingFactory` instances based on the SB connection string.**  (this is what I'm doing in #877)
All ServiceBus bindings that have the same connection string would share the same `MessagingFactory`.
**Pros**: Fixes the bug in a fairly contained way.
**Cons**: Multiple ServiceBus attributes in the same app would use the same underlying factory, and thus the same connection. This is a change from how things work today where every usage of the ServiceBus attribute would get its own factory. In practice, I'm not sure how much of an effect it would have on apps.

**2. Have `Binder` cache `Binding` instances internally, based on attributes**
Use something like a mapping of `Attribute[]` to `Binding` in the `Binder` implementation to cache bindings. If a function uses the exact same binding attributes over-and-over (as scripts do), you'll get the same instance.
**Pros**: Mostly addresses the con of *#*1 above. Bindings themselves don't have to know about this behavior.
**Cons**: It's not clear that Attribute matching would work perfectly. My initial attempt worked, but it would need some more investigation. Also, this would affect all bindings rather than just the SB one like *#*1.

**3. Have `Binder` call `Dispose()` on Bindings; Have ServiceBusBinding implement `IDisposable`**
ServiceBusBinding could then close the connection after every invocation.
**Pros**: This would solve the problem we're seeing with connection exhaustion.
**Cons**: The connection startup is expensive. This would make C# scripts much faster than other languages.

**4. Rearchitect scripts to follow the same binding system as C# (not call `BindAsync()` with each invocation**
I don't know much about the work involved, but I believe @fabiocav was looking into this previously. I'm guessing it's a lot of work to get this working?

**Comment by christopheranderson** [comment]
**Notes from triage**
Waiting on feedback from @mathewc and @fabiocav. Not a great answer to approach this atm.
