### ISSUE TITLE
AzureStorageQueue trigger UI fields switch places

### ISSUE THREAD

**Issue by johnnliu** [Azure/azure-webjobs-sdk#888]
simple one, looks like a HTML layout issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create AzureStorageQueue trigger
2. Edit AzureStorageQueue trigger

#### Expected behavior

UI to be consistent

#### Actual behavior

UI seems to have shifted places as extra "Trigger Name" field appears

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Create: 

![image](https://cloud.githubusercontent.com/assets/1279372/19789091/90a3bb56-9cf8-11e6-8dbd-d5e13ca7649e.png)

Integrate:

![image](https://cloud.githubusercontent.com/assets/1279372/19789125/cd808a40-9cf8-11e6-9dae-f554fe6345c6.png)

**Comment by mathewc** [comment]
Thanks for reporting :) Moved to portal repo here: https://github.com/projectkudu/AzureFunctionsPortal/issues/700.
