### ISSUE TITLE
Job failed due to exit code -1073741819 using php file

### ISSUE THREAD

**Issue by suresu** [Azure/azure-webjobs-sdk#906]
![issue](https://cloud.githubusercontent.com/assets/23476560/20304569/019b5348-ab57-11e6-85c9-e926324a0739.png)

Iam using php file for creating webjobs, But the files automatically stopped and status is failed.
iam using settings.job in same path and waiting time is 10000. Any one help me how to increase the loading time for web job

**Comment by davidebbo** [comment]
If you're using PHP, you're not using the WebJob SDK, so not quite the right place. Though it does look related to [this issue](https://social.msdn.microsoft.com/Forums/en-US/033acad0-e33b-44c8-b93c-73307eccb771/webjobs-randomly-failing?forum=windowsazurewebsitespreview).

**Comment by suresu** [comment]
Could you please tell me the example?
