### ISSUE TITLE
Docs: NuGet links for Azure.WebJobs.ServiceBus

### ISSUE THREAD

**Issue by stephlocke** [Azure/azure-webjobs-sdk#907]
Hey folks,
To make it easier for people to get here, the code for the project, could you change the [nuget info](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.ServiceBus) to point here (or specifically to the [directory](https://github.com/Azure/azure-webjobs-sdk/tree/master/src/Microsoft.Azure.WebJobs.ServiceBus)) instead of:

- http://go.microsoft.com/fwlink/?LinkID=320971
- http://go.microsoft.com/fwlink/?LinkID=320972

Both of those point to a getting starting with webjobs tutorial, which doesn't seem like something someone searching for the servicebus nuget package would need or be looking for when clicking through to "Project Home"

**Comment by christopheranderson** [comment]
- [ ] @christopheranderson - should provide new text
- [ ] @mathewc - will update the packages

**Comment by paulbatum** [comment]
hey @christopheranderson can you give us the text? Otherwise I'm going to punt this out of the January milestone.

**Comment by mathewc** [comment]
Our nuget info now includes links to the repo release notes page, which should be sufficient.
