### ISSUE TITLE
Queue Metadata Failing to Bind - Not of Type String

### ISSUE THREAD

**Issue by JRKelso** [Azure/azure-webjobs-sdk#911]
When attempting to get queue metadata from Azure Function it throws an error saying id and popReceipt aren't of type String, however int dequeueCount is working just fine.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create default Azure Function as default Queue Trigger in C-Sharp

2. Create metadata parameter for queue messages of string id or string popReceipt

#### Expected behavior

Returns an Id and popReceipt strings

#### Actual behavior

Throws error "Binding data for 'id' is not of expected type String" failing in ClassDataBinding for BindAsync(BindingContext context)
Same for popReceipt

#### Known workarounds

Haven't been able to get any work around

#### Related information
Using https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage as a reference for getting queue metadata

**Comment by mathewc** [comment]
I just tried this in production on latest runtime version 1.0 and I can't repro - those queue properties bind correctly for me. Are you using the latest version 1.0?

**Comment by markheath** [comment]
I've run into this exact same issue with an F# function trying to bind to both `id` and `popReceipt`. Using runtime v1 

    Exception while executing function: Functions.QueueTriggerFSharp1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'id'. Microsoft.Azure.WebJobs.Host: Binding data for 'id' is not of expected type String.

and

     Exception while executing function: Functions.QueueTriggerFSharp1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'popReceipt'. Microsoft.Azure.WebJobs.Host: Binding data for 'popReceipt' is not of expected type String.


Here's a function that reproduces it:

````
type Person = {First:string;Second:string}
let Run(input: Person,  
        expirationTime: DateTimeOffset, 
        insertionTime: DateTimeOffset, 
        nextVisibleTime: DateTimeOffset,
        queueTrigger: string,
        popReceipt: string,
        dequeueCount: int,
        log: TraceWriter) = 
    log.Info(sprintf "input: '%A'\n\
                      expirationTime: %A\n\
                      insertionTime: %A\n\
                      nextVisibleTime: %A\n\
                      queueTrigger: %s\n\
                      popReceipt: %s\n\
                      dequeueCount: %d"
                      input expirationTime insertionTime 
                      nextVisibleTime queueTrigger
                      popReceipt
                      dequeueCount)
````

**Comment by markheath** [comment]
Figured it out. This error only occurs when you test your function using the "Test" section in the portal. Seems it doesn't actually post a real message to your real queue but fakes it in some way.
If you post a real message to the queue the binding works fine

**Comment by JRKelso** [comment]
@markheath That's what it is, thanks for the help! Tested by throwing a message into the queue from Postman and the function triggered fine with no errors and produced the ID and PopReceipt. I did the run from within the editor in Azure and it gave me the binding error.
