### ISSUE TITLE
ScriptHost initialization failed

### ISSUE THREAD

**Issue by kayomarz** [Azure/azure-webjobs-sdk#917]
Using WebJobs SDK Script Host as described in [Option 2 (No HTTP Function/WebHook Support)](https://github.com/Azure/azure-webjobs-sdk-script/wiki#option-2-no-http-functionwebhook-support)

The WebJobs log gives an error:

    [11/19/2016 08:49:23 > fdf520: INFO] ScriptHost initialization failed
    [11/19/2016 08:49:28 > fdf520: INFO] ScriptHost initialization failed
    [11/19/2016 08:49:33 > fdf520: INFO] ScriptHost initialization failed
    [11/19/2016 08:49:38 > fdf520: INFO] ScriptHost initialization failed

The problem occurs with **azure-webjobs-sdk-script** [v1.0.0-beta1-10574](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.0-beta1-10574)  (move to node 6.5.0)

The problem does not occur with [v1.0.0-beta1-10312](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.0-beta1-10312) but this version does not support node 6.x.x

Our project needs to use **azure-webjobs-sdk-script** with support  for **node 6.3.0** or greater.

Any help would be appreciated. Thanks!

**Comment by christopheranderson** [comment]
Hey @kayomarz - we need more info to repro. Could you provide one for us so we can investigate?

**Comment by christopheranderson** [comment]
Closing based on inactivity

**Comment by kayomarz** [comment]
@christopheranderson I tried it today using the latest azure-webjobs-sdk-script, it seems to work fine. Thanks for your response.
