### ISSUE TITLE
Is there any provision to listen to individual eventhub partitions with eventhub trigger for parallelism

### ISSUE THREAD

**Issue by banuthir** [Azure/azure-webjobs-sdk#933]
I've created an event hub with 8 partitions. Below function is called by webjob using the event hub trigger.
The webjob function is processing the partitions sequentially.. Is there any way to create dedicated listener for every partition in event hub to process the events in partitions parallelly?

I've seen some code and samples with worker role available here (https://github.com/sandrinodimattia/EventHubsDemo/blob/master/EventHubsDemo.Processor/Program.cs) Is there any sample which explains to do using event hub trigger ?

Main.cs
```csharp
eventHubConfig.AddEventProcessorHost(eventHubName, myListener);
                config.UseEventHub(eventHubConfig);                
                JobHost host = new JobHost(config);
                host.RunAndBlock();
```

Functions.cs
```csharp
public static void ReceiveEvents(
            [EventHubTrigger("eventhubname")] EventHubData[] events)
        {
```

**Comment by christopheranderson** [comment]
If you run the WebJobs on 8 instances, EventProcessorHost will automatically spread the work across the different instances.

**Comment by banuthir** [comment]
But, the costs associated with scaling out webjob instances across VMs would be more than running multiple webjobs in the same machine? what's the approach you would propose for scaling out?
