### ISSUE TITLE
Populating event hub name from app.config

### ISSUE THREAD

**Issue by banuthir** [Azure/azure-webjobs-sdk#934]
Event hub trigger attribute expects a hardcoded event hub name in the trigger attribute.
public static void ReceiveEvents(
            [EventHubTrigger("eventhubname")] EventData[] events)

It doesn't accept dynamic values. Is it already supported or how else can I make it configurable?

**Comment by christopheranderson** [comment]
`"%AppSettingName%"` will grab it from an App Setting.

**Comment by banuthir** [comment]
Great, i'll try this...
