### ISSUE TITLE
Webjobs started before time with TimerTrigger

### ISSUE THREAD

**Issue by boudinov** [Azure/azure-webjobs-sdk#937]
This issue is similar to #866 - I have a Continuous WebJob's timer function which is unexpectedly run sometimes when i do a slot swap:

`public static async Task NightBatch([TimerTrigger("0 30 1 * * *", RunOnStartup = false)] TimerInfo timerInfo)`

In question to last suggestion in #866, do you mean try WebJobs SDK and Extensions version 2.0.0-beta2 ? Will they work with current Azure infrastructure?

WebJob is automatically deployed with the web application (linked using Add/Existing project as Azure WebJob).
In settings.job i have "is_singleton": true
Timer function is set to run once 0 30 1 * * * with explicit set RunOnStartup = false
Staging slot has WEBJOBS_STOPPED set to true
Anyway, both slots have the same webjob storage configured.

WebJob has no versioning in assembly name, azure-webjob-hosts/ids/mystorageaccount contains a file MyCompany.WebJobs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.. containing host id c1e27aa8fd0440dd972eb8bd05ec6b75.

What i notice in webjob logs is that HostInstanceId changes totally after each swap, but that sounds normal. What is stable and contains the host id are SharedQueueName, SharedDirectoryName, FunctionId, hearbeat etc..

I am adding couple of webjob logs files:
[FunctionStarted_2519218889593500994_fc1bfd9cde664d2ca66d52c0859371f9.txt](https://github.com/Azure/azure-webjobs-sdk/files/634284/FunctionStarted_2519218889593500994_fc1bfd9cde664d2ca66d52c0859371f9.txt)
[HostStarted_2519218889615013920_b5e7f4081a114f06be6dc5dba0f75fb6.txt](https://github.com/Azure/azure-webjobs-sdk/files/634285/HostStarted_2519218889615013920_b5e7f4081a114f06be6dc5dba0f75fb6.txt)
[FunctionCompleted_2519218889059582982_78cdca0d6212464aa0916b95eaf82a96.txt](https://github.com/Azure/azure-webjobs-sdk/files/634286/FunctionCompleted_2519218889059582982_78cdca0d6212464aa0916b95eaf82a96.txt)

Sorry, not sure if i should create a new issue, or somehow reopen this.
Thanks

**Comment by brettsam** [comment]
2.0.0-beta2 should have the fix for what you're seeing and works with the current infrastructure. Give it a try and let us know if you see any other issues.
