### ISSUE TITLE
Add ETW events to get trigger telemetry

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk#940]
This is for the SDK in general, and not specific to Functions. It would allow us to determine the popularity of triggers across all scenarios running on App Service.

**Comment by lindydonna** [comment]
Assigning to @christopheranderson to follow up on the scenario and get someone assigned.

**Comment by christopheranderson** [comment]
This would be interesting. WebJobs SDK reporting is consistently skewed due to the lack of telemetry in this regard. If it benefits both Functions and WebJobs, it's a no brainer. I'll add this as a scenario in my monitoring planning doc I'm working on now.

**Comment by paulbatum** [comment]
The FunctionsMetrics table now has per binding telemetry. Closing as resolved.
