### ISSUE TITLE
Binder class in tags 1.1.1 and 1.1.2

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk#960]
Looking at the code, [`Binder` ](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Bindings/Runtime/Binder.cs#L19) class can be found on the `master` branch, but is missing on tags `1.1.1` and `1.1.2`. Yet it's back in [`Beta2.0.0-beta1`](https://github.com/Azure/azure-webjobs-sdk/blob/v2.0.0-beta1/src/Microsoft.Azure.WebJobs.Host/Bindings/Runtime/Binder.cs) and [2](https://github.com/Azure/azure-webjobs-sdk/blob/v2.0.0-beta2/src/Microsoft.Azure.WebJobs.Host/Bindings/Runtime/Binder.cs).

Is `master` branch a representation of what's the latest stable version is?

**Comment by mathewc** [comment]
No, the master branch is the branch we do our releases out of, and that includes the current in progress 2.0.0 release. So Binder is new in 2.0.0, not in 1.1.2.
