### ISSUE TITLE
Improve AutoResolve error message for setting resolution

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#965]
Users continue to have issues with this, the most recent one on SO here: https://stackoverflow.com/questions/41521465/azurefunctions-binding-to-sendgrid.

I'm thinking we can improve things by emitting a better error message in cases where we know the attribute value is supposed to be a indirect setting name not a value (i.e. AutoResolve + AllowTokens = false). In such cases we can simply add a message addendum to the effect, "The value specified should be the name of an app setting whose value is the value to use for the binding". Something like that.

**Comment by mathewc** [comment]
@MikeStall @brettsam What do you guys think?

**Comment by MikeStall** [comment]
Yes - I'm always for better error messages.  This shouldn't be an extension specific message. The appsetting lookup code is common and the error check and improved message should be coming from the SDK.  (which I know we all agree on since this bug is filed in the SDK repro and not extensions repro :) )

**Comment by brettsam** [comment]
Completely agree on everything.

**Comment by christopheranderson** [comment]
@lindydonna wants this too

**Comment by christopheranderson** [comment]
@paulbatum @davidebbo - please assign

**Comment by kashimiz** [comment]
Looks like this was fixed in PR #1164 .

**Comment by paulbatum** [comment]
@kashimiz Ugh, sorry about that. After looking at the PR I agree, closing this.
