### ISSUE TITLE
Allow binding contract to include runtime data

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk#968]
Binding contracts are static. So today, to bind to properties in an HttpRequestMEssage, we need an intermediate type like Info below to define the binding contract.  
It'd be nice if this trigger could say the binding contract was determined at runtime, so that:
1. Info wasn't required 
2. but also still get nice static errors for other triggers that do have a static contract (like [QueueTrigger] for a known poco type).  

```
using System.Net;

public class Info
{
    public string UserAccountID { get; set; }
    public string CampaignID { get; set; }
    public string ContactID { get; set; }
}

public static async Task<HttpResponseMessage> Run(Info info, HttpRequestMessage req, TraceWriter log)
{
    log.Info($"{info.UserAccountID} {info.CampaignID} {info.ContactID}");
    return req.CreateResponse(HttpStatusCode.OK);
}
```

We may have a similar issue when binding to JObject. 

```
Func(
  [QueueTrigger] JObject message, 
  string name, // pulled from message.Name
```

**Comment by mathewc** [comment]
Need to be careful here. There are a bunch of assumptions that exist currently around the fact that binding data has been strongly typed and validated at index time by static contract validation. E.g. related to validation of inputs, the fact that binding data all passes through a strongly typed properties potentially with business logic validation in place.

**Comment by MikeStall** [comment]
Another angle here - adding dot operators naturally opens this up. 
https://github.com/Azure/azure-webjobs-sdk/pull/1117

**Comment by MikeStall** [comment]
The dot operator support, now checked  in, is a sufficient solution here
