### ISSUE TITLE
Todo: Create a contribution guidelines - How to Start Contributing?

### ISSUE THREAD

**Issue by markwsanders** [Azure/azure-webjobs-sdk#973]
Hi,

Not sure if this is the right place to post this question. If not please let me know the best place to ask.

I would like to help contribute to the project but I have not contributed to an opensource project before. I have gone through the steps for the .NET Foundation approval but I'm not sure what to do next. Do I just wait for an assignment? Do I monitor issues and just randomly volunteer? Any direction would be appreciated.

Thanks!

**Comment by mathewc** [comment]
Hey Mark - thanks for the interest and offer to help :) Often people start by having an issue that has been bugging them (or affects them specifically) and they send a PR to unblock themselves. You could always look for an item that is pretty clear cut and doesn't look like it requires a bunch insider knowledge you might not have. If you found one, I suggest commenting on the issue with a design proposal/idea just so any required design discussion takes place first.

We'll also look at this issue in our next triage and will try to get some better guidance in place. E.g. we should really be using the "Help Wanted" tag on issues - that would allow you to search for such issues easily.

**Comment by markwsanders** [comment]
Thanks for the reply. I will keep a look out and see if any issue come across that I can get my feet wet with.

**Comment by mathewc** [comment]
Reopening so we look at this in triage :)
