### ISSUE TITLE
SetMetadata Throws Exception if Blob has No Content

### ISSUE THREAD

**Issue by markolbert** [Azure/azure-webjobs-sdk#993]
I have an application where I store metadata in the "virtual" directories I create within a blob storage account (and yes, I should probably be using the SMB/file storage system, but bear with me; this is a legacy situation, sort of).

I've discovered if I do this:

```
var _cloudMetadata = Container.GetBlockBlobReference( $"{Path}{FolderInfoBlobName}" );
// load stuff into metadata collection
_cloudMetadata.SetMetadata();
```
I get a StorageException complaining that the blob doesn't exist.

But if I do this:

```
var _cloudMetadata = Container.GetBlockBlobReference( $"{Path}{FolderInfoBlobName}" );
_cloudMetadata.UploadText("This is a placeholder blob, for storing metadata about the folder in which it exists");
// load stuff into metadata collection
_cloudMetadata.SetMetadata();
```

Everything's fine.

It's not a big deal to work around the issue by storing some dummy data in the blob. 

But, to me at least, it's counter-intuitive that I can't store metadata in a "valid" CloudBlockBlob until I fill it with something. It seems like the act of calling SetMetadata() ought to bring an empty blob into existence.

**Comment by markwsanders** [comment]
The issue you are experiencing is with the Azure Storage API. You would probably have a better chance of good discussion and possible resolution if you move this post to https://github.com/Azure/azure-storage-net/issues.

**Comment by markolbert** [comment]
LOl! Sorry, I'll move it.
