### ISSUE TITLE
Allow listener startup failures to be non fatal

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk#996]
Currently when the JobHost starts up, all listeners are also started, and if any listeners fail (e.g. due to an invalid ServiceBus connection string, etc.) the exception will bubble up and bring down the host.

We should consider allowing the host to have a mode where this is not the case. I mention a mode, because likely we want the default to remain the way it is. However, for advanced scenarios (e.g. Azure Functions) it is useful to be able to treat individual functions as more isolated units and allow the host to start even if one or more function listeners fail to start. We'd log the errors well, but allow functions non in error to start.

**Comment by mathewc** [comment]
Related to https://github.com/Azure/azure-webjobs-sdk-script/issues/635

**Comment by mathewc** [comment]
Somewhat related to the `FunctionIndexingException.Handled` (see usage [here](https://github.com/Azure/azure-webjobs-sdk/blob/5c162d503a488dc6e5904e99fa35ab078fd94402/src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs#L94)) property I added that allows Azure Functions to handle function index exceptions in a non fatal way.

**Comment by davidebbo** [comment]
Yes, I do agree that for Functions, we need to find a way to not make an issue in one Function cause the entire host to die. We already do this for a category of errors (like C# compile errors).

**Comment by mamaso** [comment]
Still needs changes in script repo
